kubernetes/enhancements

release-1.3/features-1.3.md
=> List of the with 1.3 features added

README.md
A feature is:
- Something that can span multiple releases
- Something that can sit on a backlog
=> README: it is unclear what a feature is

ISSUE_TEMPLATE.md
=> ISSUE_TEMPLATE: fix a broken link

OWNERS
Add aronchick, idvoretskyi, and myself as the initial OWNERS as we have
been involved in the last few weeks to make this repo successful for
v1.4.
Explicitly not adding @erictune right now even though he created the
repo because he is overloaded.
=> OWNERS: add idvoretskyi

ISSUE_TEMPLATE.md
Just removed duplicated "that"
=> Remove duplicated "that"

release-1.3/release-1.3.md
Adding this for parallelism to 1.4.  Will update other wikis to point here authoritatively.
@idvoretskyi @erictune
=> Adding release 1.3 schedule to features repo

README.md
Based on [Brandon's work](https://github.com/kubernetes/features/pull/41)
=> Cleans up README to make it more compact

release-1.4/Release-1.4.md
...to reflect our current targeted date of 20 September 2016
=> Update proposed 1.4 release date

release-1.5/release-notes-draft.md
ref/ kubernetes/kubernetes#37862
@spiffxp @saad-ali
=> Add release note about PodDisruptionBudget alpha->beta.

release-1.5/release-notes-draft.md
@idvoretskyi @sarahnovotny @spiffxp @kubernetes/sig-cluster-lifecycle
=> Fix sig-cluster-lifecycle statement and small other things in the draft

release-1.5/release-notes-draft.md
cc: @nikhiljindal @madhusudancs
=> Mark ConfigMap in federation as alpha

release-1.5/release-1.5.md
=> Fix scheduled release date for 1.5

release-1.5/release-notes-draft.md
So it can be more easily consumed by relnotes.
=> Remove extraneous info from draft

release-1.5/release-notes-draft.md
Sorry about adding release note this late.
It is somehow difficult to define what phase this feature should be. Bad new is the corresponding feature issue does not exist yet. If we must have it, please advise, thanks!
@bprashanth @thockin @saad-ali 
cc @matchstick
=> Adds release note for DNS Horizontal Autoscaling

release-1.5/release-notes-draft.md
Describe changes to `--force` where they belong.
=> Include information on force deletion

release-1.5/release-notes-draft.md
cc @kubernetes/sig-federation @matchstick @nikhiljindal @roberthbailey
=> [Federation] Add feature gates and lack of upgrade tests to the known issues section.

ISSUE_TEMPLATE.md
Before the Issue Template will be globally reimplemented, the quick fix.
=> Updated template with the new design proposals link

release-1.6/release-1.6.md
A proposal in line with our one release per quarter for the 1.6 release.  We can modify and update based on feedback at the next community meeting.
cc @idvoretskyi @calebamiles @sarahnovotny
=> 1.6 Schedule

release-1.6/release-1.6.md
Just cleaning up the outdated header at the top.
=> Cleanup 1.6 Release Readme

release-1.6/flake-reports/2017-03-03.md
Begin filing test flake reports as status reports under 1.6 release directory
=> Create Flake Report for 2017-03-03

release-1.6/go-signal-reports/2017-03-14.md
=> Create 2017-03-14 draft

release-1.6/release-notes-draft.md
=> Add release notes for scheduler features moving from alpha to beta, and new alpha feature.

release-1.6/release-notes-draft.md
cc/ @calebamiles 
ref/ kubernetes/kubernetes#43271
=> Add manual release note for #43271

release-1.6/go-signal-reports/2017-03-20.md
- updates suite failures
- updates flake counts
- adds broken test run issues to close by release team
=> Adds 2017-03-20 report

release-1.6/release-notes-draft.md
CC @kubernetes/sig-storage-misc
=> Rearrange/reword storage release notes for 1.6

release-1.6/release-notes-draft.md
For discussion in SIG-cluster-lifecycle.
Hailing @jbeda @luxas @pires @errordeveloper
=> kubeadm release notes draft for 1.6

release-1.6/release-notes-draft.md
add issue link and author to HPA features
=> add issue link and author to HPA features

release-1.6/release-notes-draft.md
to be more accurate and point to the docs
=> fix up the certificates api release notes

release-1.6/release-notes-draft.md
=> Add alpha scheduling feature at top of release notes

release-1.6/release-notes-draft.md
=> release note for HPA

release-1.6/release-notes-draft.md
Reverts kubernetes/features#231
=> Revert "release note for HPA"

release-1.6/release-notes-draft.md
Signed-off-by: Joe Beda <joe.github@bedafamily.com>
=> Add kubeadm to 'Themes' for 1.6

release-1.6/release-notes-draft.md
Many people are going to hit this doc in the next few days.  Consequently I have:
* re-ordered the points in perceived order of importance
* heavily copy-edited 
* linked to documentation where appropriate
=> Copy edit release notes

release-1.6/release-notes-draft.md
two spelling corrections and uppercase K in Kubernetes
=> spelling corrections

release-1.6/release-notes-draft.md
/cc @kubernetes/sig-node-pr-reviews @dchen1107 @derekwaynecarr @vishh 
/cc @ethernetdan @calebamiles
=> Add release note for the node components/kubelet

release-1.7/release-1.7.md, release-1.7/release_team.md
Just getting the ball rolling
**Needs to incorporate feedback from 1.6 retrospective and needs approval at community meeting**
=> Added the 1.7 proposed timeline

release-1.7/release_team.md
Thanks for volunteering, @ericchiang!
=> Eric Chiang fills CI Signal Lead for 1.7 Release

release-1.7/release-notes-draft.md
=> Add Federation ClusterSelector to release notes

release-1.7/release-notes-draft.md
This was rendering as "type=,count=" before this.
=> Fix formatting in GPU release note bullet.

release-1.7/release-notes-draft.md
Based on @thockin's comments in the draft doc.
=> update NetworkPolicy Action Required section

release-1.7/release-notes-draft.md
Update cri-containerd v0.1.0 release note.
=> Add cri-containerd v0.1.0 release note.

release-1.7/release-notes-draft.md
cc @roberthbailey @lukemarsden @jbeda @pipejakob @timothysc
=> Update the release notes for sig-cluster-lifecycle

release-1.7/release-notes-draft.md
This looks a little bit nicer :)
=> Format the NetworkPolicy yaml

release-1.7/release-notes-draft.md
updated known issues descriptions and links
removed gzip line item (it didn't get picked into the 1.7 release branch)
=> Update 1.7 known issues and links

release-1.7/release-notes-draft.md
ref: https://docs.google.com/document/d/1dWFkFJIHo3liTWomvB1ur6jqd6cnxvGb_jjE-3-c6Bo/edit?disco=AAAABN87-9Q
I really think CRDs should be mentioned, it's one of the major adds in this release for sure
cc @apsinha @deads2k @liggitt
=> Mention CRDs in major themes

release-1.7/release-notes-draft.md
This PR fixes incorrect release notes for kubernetes/kubernetes#44251.
=> Fix incorrect release notes for kubernetes/kubernetes#44251

release-1.7/release-notes-draft.md
Addresses https://github.com/kubernetes/features/pull/316#discussion_r124726659.
@luxas 
Signed-off-by: Random-Liu <taotaotheripper@gmail.com>
=> Remove extra `Alpha`.

release-1.7/release-notes-draft.md
This reverts commit 1d051a6e552d0d94be529327fbfaf773f98d0666.
=> Revert "Update release-notes-draft.md"

release-1.7/release-notes-draft.md
Thank you so much
- @dchen1107 
- @pwittrock 
- @grodrigues3 
- @idvoretskyi 
- @caesarxuchao 
for helping to get the release notes over the line
=> Sort changes by component and area

release-1.8/release_team.md
=> added most recent volunteers

release-1.8/release_notes_draft.md
Skeleton of storage features for release notes (will update as features solidify)
=> Add storage features to release notes.

release-1.8/release_notes_draft.md
=> draft of resource management node features relnotes

release-1.8/release_notes_draft.md
Added 'Taint nodes by condition' release notes.
=> Added 'Taint nodes by condition' release notes.

release-1.8/release_notes_draft.md
=> Add extended resources release note.

release-1.8/release_notes_draft.md
Signed-off-by: Christopher M. Luciano <cmluciano@us.ibm.com>
Special notes for your reviewer:
- Marked as WIP so that I can add Egress notes when the PR merges
=> Add network-policy features for SIG Network

release-1.8/release_notes_draft.md
Adding kube-proxy ipvs mode features for SIG network.
@thockin @quinton-hoole @haibinxie
=> Add kube-proxy ipvs mode features for SIG network 

release-1.8/release_notes_draft.md
PTAL @jdumars @calebamiles @radhikapc @kubernetes/sig-cluster-lifecycle-pr-reviews @andrewsykim @wlan0
=> Update release notes for SIG-Cluster-Lifecycle

release-1.8/release_notes_draft.md
This contains the final set of updates for SIG Autoscaling and SIG Instrumentation for the
1.8 release notes.
=> 1.8 release notes for SIG Autoscaling and SIG Instrumentation

release-1.8/release_notes_draft.md
This record:
https://github.com/kubernetes/kubernetes/pull/51943
=> record change about advanced auditing feature gate

release-1.8/release_notes_draft.md
/assign @pwittrock @fabianofranz
=> Update sig cli release note

release-1.8/release_notes_draft.md
Attempts to add SIG Node development themes for 1.8. Is this what you had in mind, @derekwaynecarr and @dchen1107?
=> Add SIG Node themes for 1.8

release-1.8/release_notes_draft.md
Cleaned up the list to check off sigs that are done with their contributions and also sigs for which release notes are not applicable.
=> update list of sigs with release notes

release-1.8/release_notes_draft.md
This includes the themes for SIG Autoscaling and Instrumentation, as well as a deprecation notice.
cc @piosz @mwielgus @luxas
=> 1.8 Themes and Updates for SIG Autoscaling and Instrumentation

release-1.8/release_notes_draft.md
in progress updating of sig-node release features.
=> WIP 1.8 sig-node release features

release-1.8/release_notes_draft.md
First draft of SIG Network major themes for the v1.8. release notes.
=> Add SIG Network themes to v1.8 release notes

release-1.8/release_notes_draft.md
break up SIG Node charter and SIG Node 1.8 themes with newline
=> touches up SIG Node 1.8 release themes

release-1.8/release_team.md
@dims has been doing a lot of bug triage
and I've been looking over test-infra's shoulder for general queue health
=> release-1.8: tweak release team secondaries

release-1.8/release_notes_draft.md, release-1.8/scalability_validation_report.md
cc @kubernetes/sig-scalability-misc @kubernetes/sig-release-members @wojtek-t @gmarek @countspongebob @spiffxp 
Let me know if I missed something.
=> Add sig-scalability release notes

release-1.8/release_notes_draft.md
cc @kubernetes/sig-auth-pr-reviews 
cc @radhikapc
=> 1.8 release notes: finalize auth items

release-1.8/release_notes_draft.md
=> Add release notes for CRI validation test suite and CRI CLI

release-1.8/release_notes_draft.md
=> fix code error

release-1.8/release_notes_draft.md
the top level information is covered in SIG level themes and in component updates.
=> Remove top level major themes in favor of SIG provided themes

release-1.8/release_notes_draft.md
cc @dims @radhikapc @andrewsykim @jagosan @wlan0
=> Add note about the PVL deprecation

release-1.8/release_notes_draft.md
=> sig-node updates for 1.8

release-1.8/release_notes_draft.md
@radhikapc @davidopp @timothysc
=> Add theme for SIG Scheduling

release-1.8/release_notes_draft.md
=> Fix broken links of scheduling design docs

release-1.8/release_notes_draft.md
@radhikapc PTAL. Fairly heavy copyedits but I'm as certain as I can be that I made no changes to technical meaning. There are still some too-long too-complex sentences, but I fixed what I could in a reasonable amount of time. Also focused on:
- consistent punctuation
- consistent high-level descriptions (not perfect, but better)
- consistent group/version vocabulary
- a few grammar fixes
- clearer explanations
=> Release notes

release-1.8/release_notes_draft.md
@Bradamant3  PTAL. Fairly heavy copyedits after discussing with owners of respective sections.  Tried to focused on:
- clearer explanations
- consistent punctuation
- consistent high-level descriptions 
- consistent terminology
=> copy / substantial edit of upgrade readiness section

release-1.8/release_notes_draft.md
In addition to #446 adding major theme for API Machinery.
=> Add Major theme for API Machinery

release-1.8/release_notes_draft.md
also re-ordered the entire theme section to be completely alphabetical by sig name. 🤷‍♀️
=> add API machinery themes

release-1.8/release_notes_draft.md
1. Re-ordered the sections alphabetically.
2. Edited for clarity and consistency.
3. Added consistent punctuation.
=> edit review of the Depreciations section

release-1.8/release_notes_draft.md
1. Re-ordered the sections alphabetically.
2. Edited for clarity and consistency.
3. Added consistent punctuation.
=> Edit review of the node components section

release-1.8/release_notes_draft.md
=> Add release notes of frakti runtime

release-1.8/release_notes_draft.md
@Bradamant3 PTAL. Fairly heavy copyedits
Tried to focused on:
clearer explanations
consistent punctuation
consistent terminology
=> edits on external dependencies, network sections

release-1.8/release_notes_draft.md
Source https://docs.google.com/spreadsheets/d/18V_8YvqemC96W17O_3WZ6H_kS7r77NAI9FqUHAM2MS0/edit#gid=0
=> add federation content

release-1.8/scalability_validation_report.md
Ref https://github.com/kubernetes/kubernetes/issues/51899
cc @kubernetes/sig-scalability-misc @liggitt @jdumars @abgworrall
=> Update release scalability-validation doc with performance regressions

release-1.8/release-notes-draft.md
/cc @yguo0905 @Random-Liu @mrunalp @feiskyer @dchen1107
=> Edit CRI-related items

release-1.8/release-notes-draft.md
update release note statement for cri-o
=> clarify cri-o support statement

release-1.8/release-notes-draft.md
PTAL @liggitt @jdumars @radhikapc
=> add pod deletion latency known issue

release-1.8/release-notes-draft.md
PTAL @dchen1107  @jdumars @radhikapc @abgworrall
=> add before upgrading item about kubelet failing with swap on

release-1.9/release_team.md
Based on the [nomination sheet](https://docs.google.com/spreadsheets/d/1NGEtufpSfYlJwsB_0D9gF80Y24JQEreut9gT_QIN6Kk/edit?usp=sharing) as of Oct 16.
**Please comment below to confirm acceptance of your role.**
|  **Role** | **Name** (**GitHub/Slack ID**)  | **Shadow Name(s) (GitHub/Slack ID), ...**
|  ------ | ------ | ------ |
|  Lead | Anthony Yeh ([@enisoc](https://github.com/enisoc)) | |
|  Secondary | Jaice Singer DuMars ([@jdumars](https://github.com/jdumars)) | |
|  Features | Ihor Dvoretskyi ([@idvoretskyi](https://github.com/idvoretskyi)) | |
|  Branch Manager | David Ashpole ([@dashpole](https://github.com/dashpole)) | |
|  Test Infra | Benjamin Elder ([@BenTheElder](https://github.com/BenTheElder)) | |
|  Docs | Zach Corleissen ([@zacharysarah](https://github.com/zacharysarah)) …
=> Add 1.9 release team

release-1.9/release-1.9.md
Updates to doc dates and requirements for docs PRs.
/cc @enisoc @Bradamant3
=> Updated doc dates and PR requirements

release-1.9/release-1.9.md
1 character fix to streamline page format
=> Fix doc heading to match others

release-1.9/release-notes-draft.md
DRAFT ONLY. But merge is welcome because there's a group of us waiting to do final cleanup.
Note especially that line spacing needs to be fixed up. I fixed up through the Before Upgrading section, then figured a PR was better sooner than later.
=> add first draft of markdown for release notes

release-1.9/release-notes-draft.md
Will merge Peter's PR after this one, please.
=> add known issues, fix line spacing and heading levels

release-1.9/release-notes-draft.md
Added rktlet, additional known issue
=> Final release notes

release-1.9/scalability_validation_report.md
=> Scalability validation report for 1.9.

ISSUE_TEMPLATE.md
During 1.8, some PRs got merged with the idea that tests would be written.  I think we should start asking for tests sooner to help produce more stable releases.
=> add section asking for testing

OWNERS, OWNERS_ALIASES
Larger pool of people capable of approving PRs to this repo
=> Sync k/features owners with k/sig-release

README.md
ref: kubernetes/kubernetes#57689
=> Follow sig list to kubernetes/community

README.md
/sig pm
/assign @idvoretskyi 
Signed-off-by: Stephen Augustus <foo@agst.us>
=> Remove references to `kubernetes-pm`

README.md
Fix a typo:
Spreadhsheets->Spreadsheets
=> Typo fix: Spreadhsheets->Spreadsheets

README.md
Closes: #601 
/sig pm
/assign @idvoretskyi 
Signed-off-by: Stephen Augustus <foo@agst.us>
=> Add descriptions for Features labels

OWNERS_ALIASES
I will be leading the 1.13 and trying to get ahead of any possible changes I will need to make
=> Add kacole2 to Owner Aliases

ISSUE_TEMPLATE.md, README.md
Related #620. 
/kind feature
/sig pm
=> Rename Features to Enhancements

README.md
Just a quick update to the current state of the repo.
=> README: document keps and the stage label

keps/sig-cluster-lifecycle/0003-cluster-api.md
Signed-off-by: Jorge Alarcon Ochoa <alarcj137@gmail.com>
=> Fixed broken links for 0003-cluster-api.md

keps/sig-windows/0000-20181221-windows-group-managed-service-accounts-for-container-identity.md
The header formatting was a bit off for the GMSA KEP. This PR fixes it. Thanks for catching it @michmike !
=> Fix header formatting for GMSA KEP

keps/sig-cluster-lifecycle/0029-20180918-kubeadm-phases-beta.md
This PR updates the "KEP0029 kubeadm-phases-beta" with the latest changes implemented during v1.13 cycle and with the actions planned for v1.14.
/assign @timothysc
/assign @neolit123 
@kubernetes/sig-cluster-lifecycle-pr-reviews
=> phases-v1.14-update

keps/sig-aws/20190128-cloud-controller-custom-endpoints.md
As discussed in [SIG-AWS on 1/25/2019](https://docs.google.com/document/d/1-i0xQidlXnFEP9fXHWkBxqySkXwJnrGJP9OGyP2_P14/edit#heading=h.92yhzwlnihr9)
/sig aws
/kind feature 
/assign @justinsb
/cc @mcrute
=> [sig-aws] Added AWS custom endpoint KEP

keps/sig-aws/draft-20181127-aws-alb-ingress-controller.md
update graduation criteria for alb ingress controller beta in v1.14
=> update graduation criteria for alb ingress controller beta

keps/sig-aws/20181127-aws-ebs-csi-driver.md
=> Update EBS CSI driver KEP for Beta release

OWNERS, keps/OWNERS, keps/sig-api-machinery/OWNERS, keps/sig-apps/OWNERS, keps/sig-auth/OWNERS, keps/sig-autoscaling/OWNERS, keps/sig-aws/OWNERS, keps/sig-azure/OWNERS, keps/sig-cli/OWNERS, keps/sig-cloud-provider/OWNERS, keps/sig-cluster-lifecycle/OWNERS, keps/sig-contributor-experience/OWNERS, keps/sig-instrumentation/OWNERS, keps/sig-network/OWNERS, keps/sig-node/OWNERS, keps/sig-release/OWNERS, keps/sig-scheduling/OWNERS, keps/sig-storage/OWNERS, keps/sig-testing/OWNERS, keps/sig-windows/OWNERS
Updated OWNERS file to include link to docs
=> Updated OWNERS file to include link to docs

keps/sig-release/20190121-artifact-management.md
This updates the owning SIG to SIG Release, based on the conversations from #721.
Adding the reviewers/approvers:
/assign @justinsb @dims
Commenters:
/cc @calebamiles @cblecker @tpepper @parispittman @Phillels @nikhita
=> KEP: Artifact management

keps/sig-cloud-provider/20190125-out-of-tree-vsphere.md
/assign @frapposelli 
ref https://github.com/kubernetes/enhancements/pull/767
=> set vSphere out-of-tree support KEP to implementable

keps/sig-scheduling/201901031-pod-priority-preemption.md
=> Add a KEP for graduating pod priority and preemption to GA

OWNERS_ALIASES
Per https://github.com/kubernetes/community/blob/master/sigs.yaml#L292-L311
=> Update sig-auth tech leads

keps/sig-scheduling/201901031-pod-priority-preemption.md
=> Fix typo in pod priority preemption KEP

keps/sig-api-machinery/0006-apply.md
This is me making all the obvious changes I can in ~1 hour. It is more accurate than what was there. I (or @apelisse) can make more changes--tell me what it needs. I left TODOs for some obvious things.
Of note the status should have been set to "implementable" probably 6 months ago. I did not really understand the KEP process; we had verbal go-aheads from the relevant sigs (CLI, API Machinery, Architecture).
=> Update apply kep for alpha

keps/sig-network/20190118-pod-dns-config.md
Updating KEP status to implementable for https://github.com/kubernetes/enhancements/issues/504.
Sorry that I missed this in the previous PR: https://github.com/kubernetes/enhancements/pull/700.
cc @claurence
=> Update pod DNS config KEP to implementable

keps/sig-api-machinery/00xx-publish-crd-openapi.md
Enhancement proposal for publishing CRD OpenAPI
ref: 
tracking issue: https://github.com/kubernetes/enhancements/issues/692
implementation: https://github.com/kubernetes/kubernetes/pull/71192
cc @liggitt @mbohlool @smarterclayton @sttts
=> [KEP] Publish CRD OpenAPI 

keps/sig-api-machinery/20190206-watch-bookmark.md
Ref https://github.com/kubernetes/kubernetes/issues/73585
@kubernetes/sig-api-machinery-api-reviews @jpbetz @liggitt 
@kubernetes/sig-scalability-misc 
/assign @lavalamp 
=> Add watch bookmark KEP

keps/0001-kubernetes-enhancement-proposal-process.md, keps/README.md
* Update KEP-0001 with new location for github repo
* Fix broken links to sig-architecture
=> Updates for KEP documentation

keps/sig-api-machinery/00xx-publish-crd-openapi.md, keps/sig-node/kubelet-resource-metrics-endpoint.md
/cc @justaugustus 
Ref: https://github.com/kubernetes/test-infra/pull/11359
=> Fix spelling errors to enable spell-check job

keps/sig-instrumentation/0031-kubernetes-metrics-overhaul.md
=> Add a link to the RuntimeClass metrics change PR

keps/sig-node/kubelet-resource-metrics-endpoint.md
Someone pointed this out today at the community meeting.  Thanks to @DirectXMan12 for letting me know!
/assign @brancz @dchen1107
=> Change Kubelet Resource Metrics Endpoint KEP status to implementable

keps/sig-scheduling/20190131-pod-priority-preemption.md
=> correct file name and last-updated section

keps/sig-cli/kustomize-subcommand-integration.md
The code for this has been merged https://github.com/kubernetes/kubernetes/pull/73033
=> update the status of kustomize subcommand integration kep

keps/sig-release/20190118-creating-packages.md
This is my first take after going through all the issues and slack conversations I could find.
There are still many unknowns for me.
Also I am not really that good with words, so any input highly appreciated!
=> KEP for packaging kubernetes artifacts

keps/sig-node/20190129-pid-limiting.md
=> keps: update pid limiting kep status

keps/sig-node/20190129-hugepages.md
updated status of kep to implemented with links to tests.
/cc @dchen1107
=> keps: hugepages implemented with link to tests

keps/sig-windows/20190103-windows-node-support.md
@jsturtevant finished an in-depth investigation on using memory limits+reserves on Windows, and how the behaviors differ from Linux. This adds his findings to the KEP to resolve the open issue.
/sig windows
/milestone v1.14
=> Notes on Windows memory provisioning

keps/sig-api-machinery/00xx-publish-crd-openapi.md
Update feature gate name. Target Alpha level in 1.14
/cc @liggitt @sttts
=> Update Publish CRD OpenAPI feature gate name and rollout target

keps/sig-node/runtime-class.md
=> Add `Monitoring` section into RuntimeClass KEP

keps/sig-cluster-lifecycle/20190227-artifact-generation.md
This KEP is for the work to be done for artifact generation. This was made based off this ticket https://github.com/kubernetes/kubernetes/issues/71677 and sets up the basis for the work needing done to implement it.
/assign @ncdc @timothysc @neolit123 @ixdy @hoegaarden
=> Artifact generation KEP

keps/sig-windows/20190103-windows-node-support.md
we made some updates to the KEP as part of the finalized tests and validations on windows features for k8s v1.14
=> updates to windows KEP for 1.14 impending GA

keps/sig-cli/kustomize-secret-generator-plugins.md
=> Expand mitigation section of kv generator plugin kep

keps/sig-auth/0034-20190123-harden-default-discovery-bindings.md
closes https://github.com/kubernetes/enhancements/issues/789
@liggitt PTAL
=> complete implementation history of KEP #789

keps/sig-api-machinery/20190228-priority-and-fairness.md
Just starting this.  Mainly only a goals discussion so far.
=> Added draft KEP for priority and fairness for apiserver requests

keps/0001-kubernetes-enhancement-proposal-process.md
* Remove deprecated kep-number references in response to ref: #703 
* Add Stewardship to KEP process docs
cc: @justaugustus
=> Add KEP Stewardship section

keps/sig-node/runtime-class-scheduling.md
For https://github.com/kubernetes/enhancements/issues/894
/sig node scheduling
/assign @bsalamat @dchen1107 @derekwaynecarr 
/cc @yastij 
/milestone v1.15
=> RuntimeClass scheduling KEP

keps/sig-instrumentation/0031-kubernetes-metrics-overhaul.md
This PR aims to add recently work to the metrics overhaul KEP.
=> Add recently work for KEP metrics overhaul

keps/sig-api-machinery/20190228-priority-and-fairness.md
an outcome from the last sync up
/cc @deads2k @lavalamp @MikeSpreitzer @wojtek-t @aaron-prindle
=> Reflect new goal: Provide guaranteed capacity for requests with lower priorities

keps/sig-api-machinery/20190322-server-side-get-to-ga.md
=> KEP: Promote server-side get APIs to GA

keps/sig-node/20190131-runas-groupid.md
=> update runasgroup kep by inlining contents

keps/sig-windows/20190103-windows-node-support.md
Kubernetes 1.14 included this KEP, so it is now 'implemented'
=> Updating status of the KEP to 'implemented'

keps/sig-architecture/2019-03-19-go-modules.md
* update details for vendor-management scripts
* update publishing bot steps
* add rationale for continuing to publish staging repos
=> Update go.modules KEP

keps/sig-network/20190324-remove-kube-proxy-autocleanup.md
Initial draft, from https://github.com/kubernetes/kubernetes/issues/75408
=> micro-KEP: don't automatically clean up rules in kube-proxy

keps/sig-apps/20190226-maxunavailable-for-statefulsets.md
=> add initial KEP for maxUnavailable in StatefulSets

keps/sig-api-machinery/0030-storage-migration.md
Updating the KEP with latest development and beta requirements.
/assign @yliaog @lavalamp @deads2k
=> Update the storage version migration KEP with beta requirements

keps/sig-cluster-lifecycle/0003-cluster-api.md
Signed-off-by: Vince Prignano <vincepri@vmware.com>
=> Update cluster-api reviewers, approvers and editors

keps/sig-node/20190129-pid-limiting.md
KEP changes to graduate SupportNodePidsLimit to beta.
=> Graduate SupportNodePidsLimit to beta

keps/sig-api-machinery/20190322-server-side-get-to-ga.md
Updated with feedback from sig-api-machinery
Will be used as tracking issue.
=> Server-side `kubectl get` to GA - Implementable

keps/sig-network/20190125-ingress-api-group.md
=> Add possible things to fix to Ingress GA KEP

keps/sig-cloud-provider/20190125-removing-in-tree-providers.md
Had a chat with @liggitt and he had mentioned that staging a subdirectory of a staging repo will cause lots of issues with go modules. The alternative he recommended was to introduce a legacy staging repository where we publish in-tree providers to and allow out-of-tree providers to optionally vendor it if they want to support it. 
The cons here are more repositories to manage, but this avoids issues with go modules and still achieves what we intended from the start. Vendoring the external legacy repo will be much easier than trying to publish subdirectories of a staged repo in an existing external repository.
=> KEP removing in-tree providers: introduce legacy staging repos

keps/sig-node/20190226-pod-overhead.md
Adding sig-windows and marking the KEP implementable.
=> Pod overhead implementable

keps/sig-release/20190331-release-notes.md
Rough draft for a KEP outlining several release notes improvements that have been discussed in various forums. I fully expect this to be iterated on quite a bit. 😄 
/sig release
/cc @calebamiles @tpepper @spiffxp
=> KEP for release notes improvements

keps/sig-cli/kubectl-staging.md
* first pass of KEP describing the movement of `pkg/kubectl` code into staging.
/sig cli
/area kubectl
=> Moving kubectl package code to staging

keps/sig-node/0035-20190130-topology-manager.md
Added Feature Gate and Kubelet Flags
Updated targeted release versions
=> Updates to Topology Manager KEP

keps/0001-kubernetes-enhancement-proposal-process.md
* Removing missing TOC items (with broken links)
* Fixing link to design proposals
=> Enhancement Proposal Repairs

keps/sig-storage/20190125-online-growing-persistent-volume-size.md
This is a conversion of https://github.com/kubernetes/community/pull/1535 to KEP format for feature https://github.com/kubernetes/enhancements/issues/531
=> Online Growing Persistent Volume Size KEP

keps/sig-cluster-lifecycle/kubeadm/0023-kubeadm-config.md
see:
https://github.com/kubernetes/enhancements/issues/970#issuecomment-487731578
/assign @timothysc @fabriziopandini
/priority critical-urgent
=> kubeadm: add implementable status to 0023-kubeadm-config.md

OWNERS_ALIASES
=> sig-cluster-lifecycle: update OWNER_ALIASES

OWNERS_ALIASES, SECURITY_CONTACTS
/assign @calebamiles @idvoretskyi @jdumars
=> Update OWNERS & SECURITY_CONTACTS

keps/sig-api-machinery/20190206-watch-bookmark.md
Ref https://github.com/kubernetes/enhancements/issues/956
=> Add Test plan for watch bookmarks KEP

keps/sig-windows/20190418-windows-security-context.md
1. Addressed review comments from PR https://github.com/kubernetes/enhancements/pull/972
2. Added sample pod specs with the fields populated
3. Clarified test case
=> Updates to KEP for Windows Security Options

keps/sig-auth/0014-dynamic-audit-configuration.md
adds test plan for dynamic audit
=> add test plan for dynamic audit

keps/sig-scheduling/20180409-scheduling-framework.md
/assign @misterikkit 
ref kubernetes/enhancements#624
=> Add test plans and graduation criteria to the scheduling framework KEP

keps/sig-scheduling/20190409-resource-quota-ga.md
Planning to promote resourcequotascopeselector to GA
/cc @bsalamat @derekwaynecarr @sjenning
=> Promote resourcequotascopeselector to GA

keps/sig-cli/20190318-kustomize-generators-transformers.md
As requested by the enhancement issue #993 
/assign @pwittrock  @monopole
=> add test plan and graduation criteria

keps/sig-storage/20181111-extend-datasource-field.md
This adds the implementable tag to the extend-datasources KEP.
=> Add implementable to extend-datasource KEP

keps/sig-api-machinery/20190226-network-proxy.md
Set KEP as implementable.
Set alpha graduation criteria.
Detailed HTTP-Connect vs GRPC plan.
Referenced reference implementation repo.
=> Move API Server Network Proxy to Implementable.

keps/sig-api-machinery/20190228-priority-and-fairness.md
Added discussion of design issues.
=> Added design discussion in 20190228-priority-and-fairness

keps/sig-api-machinery/20190228-priority-and-fairness.md
.. based on earlier review comments.
=> Brushing up 20190228-priority-and-fairness.md

keps/sig-aws/20190501-aws-nlb-beta.md
https://github.com/kubernetes/enhancements/issues/423
=> add kep for graduate nlb to beta

keps/sig-network/20190125-ingress-api-group.md
=> Add test plan for 1.14

keps/sig-cloud-provider/azure/20190125-out-of-tree-azure.md
Ref: https://github.com/kubernetes/cloud-provider/issues/6: Improving Azure Integration Docs
/sig azure
/assign @justaugustus @khenidak @craiglpeters
/cc @andrewsykim @andyzhangx
=> Improve Azure external cloud provider docs

keps/sig-api-machinery/20190425-structural-openapi.md
Regarding https://github.com/kubernetes/kubernetes/pull/77207#discussion_r282221538
=> sig-api-machinery: in structural-schema update embedded-resource

keps/sig-scheduling/20190221-even-pods-spreading.md
=> KEP Even Pods Spread update: add "Release Signoff Checklist" section

keps/sig-api-machinery/00xx-admission-webhooks-to-ga.md
Per https://github.com/kubernetes/kubernetes/pull/77563#discussion_r282690526
cc @liggitt @sttts @roycaihw
=> Resolve admission webhook question about ConnectionOptions

keps/sig-node/20190221-livenessprobe-holdoff.md
Adding test plan to meet implementable requirements.
/cc @thockin 
/cc @mrbobbytables
=> Add test plan for startupProbe

keps/sig-api-machinery/20190425-crd-conversion-webhook.md
Implemented in https://github.com/kubernetes/kubernetes/pull/77743.
=> sig-api-machinery: add ObjectMeta behaviour for crd conversion

keps/sig-instrumentation/20190404-kubernetes-control-plane-metrics-stability.md
=> Add implementation history for control-plane metrics stability KEP

keps/sig-network/20190125-ingress-api-group.md
Signed-off-by: Christopher M. Luciano <cmluciano@us.ibm.com>
=> ingress: Add links to merged and in progress PRs

keps/0001-kubernetes-enhancement-proposal-process.md, keps/sig-api-machinery/00xx-admission-webhooks-to-ga.md, keps/sig-api-machinery/00xx-publish-crd-openapi.md, keps/sig-api-machinery/20180415-crds-to-ga.md, keps/sig-api-machinery/20180731-crd-pruning.md, keps/sig-api-machinery/20190325-unions.md, keps/sig-api-machinery/20190426-crd-defaulting.md, keps/sig-api-machinery/20190607-owner-ref.md, keps/sig-cloud-provider/20190125-out-of-tree-aws.md, keps/sig-cloud-provider/20190125-out-of-tree-gce.md, keps/sig-cloud-provider/20190125-out-of-tree-ibm.md, keps/sig-cloud-provider/20190125-out-of-tree-openstack.md, keps/sig-cloud-provider/20190125-out-of-tree-vsphere.md, keps/sig-cloud-provider/azure/20180711-azure-availability-zones.md, keps/sig-cloud-provider/azure/20180809-cross-resource-group-nodes.md, keps/sig-cloud-provider/azure/20190125-out-of-tree-azure.md, keps/sig-cluster-lifecycle/addons/0035-20190128-addons-via-operators.md, keps/sig-cluster-lifecycle/kubeadm/0004-bootstrap-checkpointing.md, keps/sig-cluster-lifecycle/kubeadm/0015-kubeadm-join-control-plane.md, keps/sig-cluster-lifecycle/kubeadm/20190122-Certificates-copy-for-kubeadm-join--control-plane.md, keps/sig-cluster-lifecycle/wgs/0014-20180707-componentconfig-api-types-to-staging.md, keps/sig-cluster-lifecycle/wgs/0032-create-a-k8s-io-component-repo.md, keps/sig-instrumentation/20190404-kubernetes-control-plane-metrics-stability.md, keps/sig-instrumentation/20190605-metrics-stability-migration.md, keps/sig-node/20190221-livenessprobe-holdoff.md, keps/sig-node/runtime-class-scheduling.md, keps/sig-storage/20181111-extend-datasource-field.md, keps/sig-storage/20190130-csi-raw-block-support.md
* Clean up author objects to just be lists of usernames
* Clean up bare at sign as that is invalid YAML
* Fix raw markdown as `[]` are interpreted as lists
Signed-off-by: chuckha <ha.chuck@gmail.com>
=> Simple metadata fixes

keps/sig-api-machinery/20190206-watch-bookmark.md
Ref https://github.com/kubernetes/enhancements/issues/956
=> Add an item for testing plan for beta for WatchBookmarks feature

keps/sig-cluster-lifecycle/image-builder/20190612-image-builder.md
=> Initial proposal of an image-builer subproject

keps/sig-api-machinery/20190711-remove-selflink.md
/assign @lavalamp @deads2k @liggitt @smarterclayton 
@justinsb - something we used to talk in the past about to
=> Create KEP for deprecating and removing SelfLink

keps/sig-node/20190221-livenessprobe-holdoff.md
As discussed yesterday during sig-node meeting, I have added some background on the change.
=> Adding some justifications for startupProbe

keps/sig-scheduling/20180409-scheduling-framework.md
Update the scheduling framework proposal to reflect current implementation.
/assign @bsalamat
=> fix: update scheduling framework proposal to reflect current implementation

keps/sig-node/20180906-quotas-for-ephemeral-storage.md
=> Add beta milestone criteria

keps/sig-storage/20190408-volume-scheduling-limits.md
Proposal to update Volume Scheduling Limits KEP to address deficiency when counting volumes set to use topology-aware dynamic provisioning.
/assign @msau42 @jsafrane @gnufied @bsalamat
=> Update Volume Scheduling Limits KEP to address topology

keps/sig-scheduling/20190221-even-pods-spreading.md
/assign @bsalamat @Huang-Wei 
/priority backlog
=> fix: typo in even pod spreading

keps/sig-testing/20190605-presubmitconfig-in-tested-repo.md
/assign @cjwagner @fejta @stevekuznetsov 
/cc @matthyx @kdomanski
=> Add KEP for presubmit config in tested repo

keps/sig-cluster-lifecycle/kubeadm/20190506-kubeadm-machine-output.md
This patch introduces a KEP for Kubeadm that details how to enhance the command with support for machine/structured output.
Part of #1053
cc @bart0sh
=> kubeadm: Kubeadm Machine/Structured Output

keps/sig-instrumentation/20190605-metrics-validation-and-verification.md
Continuation of work on https://github.com/kubernetes/enhancements/pull/1089 
Discussed it with @logicalhan and @solodov, due close deadline I will be continuing work on it.
/cc @logicalhan @solodov @brancz
=> Metrics Validation and Verification

keps/sig-api-machinery/20180415-crds-to-ga.md
Update the test sections.
Add conformance plan details.
cc @roycaihw  @liggitt @sttts
=> Update test plan for CRDs to GA

keps/sig-api-machinery/20190426-crd-defaulting.md
=> crd-defaulting: specify validation of default values

keps/sig-windows/20190714-windows-csi-support.md
Updates:
1. Corrected config parameter from runtime path to kubelet pod path.
2. Added Adapter to locations.
=> Update config parameters for CSI Proxy and add Adapter to Locations

keps/sig-cluster-lifecycle/kubeadm/20190424-kubeadm-for-windows.md
=> Update Kubeadm Windows KEP for 1.16

keps/sig-cloud-provider/azure/20180809-cross-resource-group-nodes.md
=> Add Graduation Criteria for cross resource group nodes

keps/sig-auth/20190711-external-credential-providers.md
Retroactive KEP for
https://github.com/kubernetes/enhancements/issues/541
Documenting the Beta state and will revise this KEP in subsequent PRs
for GA design.
=> KEP for external credential provider

keps/sig-network/20181024-service-topology.md
Updates the Service Topology KEP to include graduation criteria. The most notable update is that the alpha implementation of Service Topology will not account for scalability which means PodLocator (whether as a core API or CRD) will not be implemented until the beta release.
=> Service Topology: add graduation criteria

keps/sig-cluster-lifecycle/kubeadm/20190722-Advanced-configurations-with-kubeadm-(Kustomize).md
This PR updates kubeadm-kustomize KEP with activities carried out during v1.16 cycle
/assign @timothysc @neolit123
=> kubeadm-kustomize-v1.16

keps/sig-storage/20190122-csi-inline-volumes.md
The actual CSIDriver API became a bit different. Why this was
considered useful is now also documented in the new "Alternatives"
section.
=> csi-inline-volumes.md: update for beta

keps/sig-windows/20190424-windows-cri-containerd.md
The ContainerD work tracked in #1001 was delayed and pushed out a few releases. This updates the KEP with current milestones and progress.
For reviewers - I used `19h1` since there wasn't a name for that in-progress version of Windows. The final name was Windows Server version 1903 so the KEP was updated to match. If there are dependencies on a future release of Windows found I'll probably call those 19H2 or 20H1 until they have an official name.
/sig windows
=> Updating milestone, project board & testgrid

keps/sig-api-machinery/20190226-network-proxy.md
Updating the KEP to reflect some minor implementation change from the 1.16 push (https://github.com/kubernetes/kubernetes/pull/82048)
=> Reflect minor implementation changes from the 1.16 push in the KEP.

keps/sig-cluster-lifecycle/kubeadm/20190506-kubeadm-machine-output.md
Changed KEP status to 'implementable'
=> kubeadm-machine-output: change status to 'implementable'

keps/sig-scheduling/20180409-scheduling-framework.md
=> feat: rename plugin context to cycle state

keps/sig-storage/20190129-csi-pod-info-on-mount.md
Update release info.
xref : https://github.com/kubernetes/enhancements/issues/603
=> Update docs for pod information to CSI calls

keps/sig-node/0009-node-heartbeat.md
Ref https://github.com/kubernetes/enhancements/issues/589
=> Update cheaper node heartbeats KEP

keps/sig-node/0009-node-heartbeat.md
Address offline feedback from @derekwaynecarr
=> Update node heartbeats KEP

keps/sig-architecture/20190412-conformance-behaviors.md
Updating this KEP so we can get started on it.
/kind kep
/assign @timothysc @hh 
/cc @kubernetes/cncf-conformance-wg
=> conformance: add design details, mark implementable

keps/sig-cluster-lifecycle/kubeadm/0023-kubeadm-config.md
And add a small section of what was already done in v1beta2.
/assign @timothysc 
/cc @neolit123 @fabriziopandini @ereslibre
=> kubeadm: Update config KEP for v1beta3

keps/sig-scheduling/20191012-graduate-taint-node-by-condition-to-ga.md
=> feat: initialize KEP for graduating TaintNodeByCondition to GA

keps/sig-architecture/2019-07-16-node-role-label-use.md
The KEP was implemented in 1.16 but will be alpha in 1.17 and the
migration process will begin.
=> Update node-role label KEP with official timeline

keps/sig-instrumentation/20181106-kubernetes-metrics-overhaul.md
Fix invalid(404) links in kubernetes-metrics-overhaul.md
=> Update links in kubernetes-metrics-overhaul.md

keps/sig-storage/20190129-csi-skip-attach.md
Record release information for skipping attach feature.
xref : https://github.com/kubernetes/enhancements/issues/770
=> Update release information for skip attach feature

keps/sig-cli/20190920-future-of-kubectl-cp.md
=> add KEP future of kubectl cp

keps/sig-cloud-provider/20190215-promoting-cloud-provider-labels.md
Also pushes proposed timeline by 1  release
=> update cloud provider GA label KEP to implementable

keps/sig-node/0035-20190130-topology-manager.md
These include but are not limited to:
* Topology Manager Policy names
* Using NUMA Node ID instead of Socket ID
* Topology Affinity calcuation logic
* Interfaces introduced
=> Added updates to KEP based on design discussion decisions

keps/sig-network/20190603-EndpointSlice-API.md
This PR updates the EndpointSlice KEP to reflect the work necessary for a beta release in 1.17. A significant portion of the changes represent updates that were made as part of the initial alpha API PR but had not yet been reflected here. 
This also includes an upgrade plan for adding a new label to indicate which controller is managing an EndpointSlice. Additionally I've outlined the rationale for not choosing a CRD for EndpointSlices.
Enhancement Issue: https://github.com/kubernetes/enhancements/issues/752
=> Adding beta requirements for EndpointSlice API

keps/sig-auth/20190916-noderestriction-pods.md
Clean up a few issues / comments from https://github.com/kubernetes/kubeadm/issues/1835
/assign @deads2k 
/assign @neolit123
=> Mirror pod restriction follow-up

keps/sig-storage/20190124-csi-topology.md
Added more details around upgrade and version skew considerations + testing.
=> update CSI topology kep for GA

keps/sig-api-machinery/20190329-less-object-serializations.md
=> Update less serializations KEP based on final implementation

keps/sig-network/20180612-ipv4-ipv6-dual-stack.md
* Add Phase 2 e2e tests to test plan
* Add Phase 4 heading
/sig network
Signed-off-by: Lachlan Evenson <lachlan.evenson@microsoft.com>
=> Dualstack - Add phase 2 e2e tests

keps/sig-scheduling/20191012-graduate-taint-node-by-condition-to-ga.md
=> feat(scheduling): update existing tests section

OWNERS_ALIASES
Reflecting SIG cloud provider chair changes.
/assign @andrewsykim
=> Reflecting SIG cloud provider chair changes.

keps/sig-architecture/20190731-production-readiness-review-process.md
Updates from recent discussions. This is a WIP as it is intended to solicit additional feedback.
=> prod readiness pilot phase

keps/sig-api-machinery/0006-apply.md
=> Fix x-kubernetes-list-map-keys

keps/sig-architecture/20191023-conformance-without-beta.md
@kubernetes/sig-architecture-feature-requests 
@timothysc 
@smarterclayton 
@deads2k 
@johnbelamaric 
@BenTheElder
=> Enable conformance without beta REST APIs or features

keps/sig-network/20190603-EndpointSlice-API.md
Although the initial vision for the `IP` address type was to be inclusive of both IPv4 and IPv6 addresses, that ended up complicating workflows in consumers like kube-proxy. In that case, and we anticipate many more, the consumer is only interested in a specific IP family for an endpoint. Both Endpoints and Services have moved toward using different resources per IP family. It only makes sense to mirror that behavior with EndpointSlices.
With that in mind, the proposed changes for beta will involve the following:
1. Add 2 additional address types: `IPv4` and `IPv6`.
2. Update the EndpointSlice controller to only create EndpointSlices with these address types.
3. Deprecate the `IP` address type, making it invalid for new EndpointSlices in 1.17 before becoming fully invalid in 1.18.
/sig …
=> Splitting IP address type into IPv4 and IPv6 for EndpointSlices

keps/sig-node/20190212-ephemeral-containers.md
These are changes to implementation that happened during API review. This updates
the KEP to match actual implementation in 1.16.
=> Update Ephemeral Containers KEP for 1.16 release

keps/sig-api-machinery/20180415-crds-to-ga.md, keps/sig-api-machinery/20190425-structural-openapi.md, keps/sig-api-machinery/20190426-crd-defaulting.md
modify the error crd url  https://github.com/kubernetes-sigs/controller-tools/tree/master/cmd/crd
the right url is https://github.com/kubernetes-sigs/controller-tools/tree/master/pkg/crd
=> modify the error crd url

keps/sig-scheduling/20180409-scheduling-framework.md
Meanwhile, the demo code's PluginFactory interface should be updated.
=> update the scheduler framework KEP for config args may be nil

keps/sig-architecture/20190731-production-readiness-review-process.md
Updates the KEP to add the creation of the production readiness review subproject.
=> Production readiness subproject

keps/sig-cloud-provider/20190125-out-of-tree-aws.md, keps/sig-cloud-provider/20190125-out-of-tree-gce.md, keps/sig-cloud-provider/20190125-out-of-tree-ibm.md, keps/sig-cloud-provider/20190125-out-of-tree-openstack.md, keps/sig-cloud-provider/20190125-out-of-tree-vsphere.md, keps/sig-cloud-provider/azure/20190125-out-of-tree-azure.md
Correct link mistakes  in keps/sig-cloud-provider.
=> correct cloud-controller-manager links in sig-cloud-provider

keps/sig-node/0009-node-heartbeat.md
Implemented and GA-ed as part of 1.17 release.
Fix #589
=> Mark NodeLease KEP as implemented

keps/sig-api-machinery/20190206-watch-bookmark.md
Implemented and GA-ed as part of 1.17 release.
Fix https://github.com/kubernetes/enhancements/issues/956
=> Mark WatchBookmarks KEP as implemented

keps/sig-architecture/20190731-production-readiness-review-process.md
Duplication of the existing questions causes confusion.
=> Update PRR KEP to link to current questionnaire

keps/sig-cloud-provider/20180530-cloud-controller-manager.md
the error url is : https://github.com/kubernetes/community/blob/master/contributors/devel/flexvolume.md
https://github.com/kubernetes/community/blob/master/contributors/devel/sig-storage/flexvolume.md
=> modify the error url of flexvolume.md

keps/sig-cloud-provider/providers/0004-cloud-provider-template.md
fix the broken link in  `keps/sig-cloud-provider/providers/0004-cloud-provider-template.md`
=> fix broken link

keps/sig-scheduling/20200114-multi-scheduling-profiles.md
Includes Summary, Motivation and Proposal
/assign @Huang-Wei @liggitt
=> Add KEP for Multi Scheduling Profiles

keps/sig-node/20190130-node-os-arch-labels.md
replace `TBD` with something better
=> fix title for 20190130-node-os-arch-labels.md

keps/sig-node/0009-node-heartbeat.md, keps/sig-node/20190129-pid-limiting.md, keps/sig-node/20190131-runas-groupid.md
=> cleanup(enhancements): typo

README.md
=> Add the 1.18 milestone tracking sheet link to README

keps/sig-cloud-provider/azure/20190722-ccm-instance-metadata.md, keps/sig-cluster-lifecycle/kubeadm/20190227-artifact-generation.md, keps/sig-windows/windows-runtimeclass-support.md
the error url is :  https://github.com/kubernetes/community/blob/master/contributors/devel/conformance-tests.md
https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/conformance-tests.md
=> Update links for conformance testing documentation

keps/sig-scheduling/20190221-pod-topology-spread.md
We're going to promote `EvenPodsSpread` to beta in 1.18. This PR updated all the necessary changes to qualify it for beta.
/cc @alculquicondor @ahg-g
=> Promote EvenPodsSpread to beta.

keps/sig-apps/20190318-PodDisruptionBudget-graduation-to-stable.md
During the effort to take PDBs to GA we have found additional issues that needs to be addressed. 
@kubernetes/sig-apps-pr-reviews 
@soltysh @kow3ns @barney-s @liggitt @mattfarina
=> Update KEP for taking PDBs to GA with additional tasks

keps/sig-scheduling/20180409-scheduling-framework.md
Two things: discuss PreFilterExtensions and ScoreExtensions and how we integrate with cluster autoscaler.
/cc @alculquicondor
=> Update the scheduler framework KEP

keps/sig-storage/20190129-csi-pod-info-on-mount.md, keps/sig-storage/20190129-csi-skip-attach.md
Move the GA implementation target for these features.
cc @msau42 @saad-ali
=> Update pod info and skip attach keps

keps/sig-cloud-provider/20190422-cloud-controller-manager-migration.md
Signed-off-by: andrewsykim <kim.andrewsy@gmail.com>
=> Add implementation details to CCM migration KEP

keps/sig-api-machinery/20200123-client-go-ctx.md
This is migrated from https://github.com/kubernetes/kubernetes/issues/46503.
/assign @deads2k @liggitt @lavalamp 
cc @maleck13 @kubernetes/sig-auth-feature-requests
=> KEP: Context support in k8s.io/client-go

keps/sig-node/0035-20190130-topology-manager.md
Update Topology Manager KEP to reflect recently introduced changes to individual policy merge strategies: https://github.com/kubernetes/kubernetes/pull/85798
=> Update Topology Manager with merge strategies

keps/sig-storage/20190130-csi-raw-block-support.md, keps/sig-storage/20191008-raw-block-support.md
=> Move raw block feature to GA in 1.18

keps/sig-cli/20191008-kubectl-events.md
KEP for adding `kubectl events` command. 
@soltysh @pwittrock
=> KEP for kubectl events

keps/sig-auth/20190730-oidc-discovery.md
=> Update OIDC KEP and mark implementable

keps/sig-api-machinery/20200123-client-go-ctx.md
And mark KEP is implementable.
@kubernetes/sig-api-machinery-api-reviews
=> add plan for consistent passing of *Options to clientset methods

keps/sig-network/20190125-ingress-api-group.md
This addresses some questions that came up in the corresponding implementation PR (https://github.com/cmluciano/kubernetes/pull/3). This proposes the following changes and clarification:
- Clarifies that the class field will be automatically populated with the value of the annotation through API conversion.
- Removes the suggestion that IngressClass resource could be used to limit the ingress classes available to end users of a cluster.
- Clarifies that IngressClass will be associated with ingresses that specify a matching name as the value of the class field or annotation.
- Clarifies that IngressClass will be optional - the value of a class field or annotation does not need a corresponding IngressClass resource.
- Clarifies that the IngressClass resource will be non-namespaced.
- Adds …
=> Clarifying Ingress V1 class field and resource

keps/sig-autoscaling/20190307-configurable-scale-velocity-for-hpa.md
A Test Section to track this change for the 1.18 release.
=> Updated the KEP with a Test Plan section

keps/sig-node/20190226-pod-overhead.md
update KEP to better describe the graduation criteria for beta.
=> pod-overhead: add beta criteria

keps/sig-node/0035-20190130-topology-manager.md
Add a Test Section to cover test plans for single and
multi-NUMA systems.
Signed-off-by: vpickard <vpickard@redhat.com>
=> Update Topology Manager KEP with a Test Plan section

keps/sig-release/20190121-artifact-management.md
Adds a proposed plan of action to establish a first storage location
for artifacts, and a first (non-redirecting) GCLB front-end, so that
we can start to gather data.
=> Artifact Serving: Proposal for milestone-0

keps/sig-release/20190121-artifact-management.md
Fix ToC from https://github.com/kubernetes/enhancements/pull/874
/assign @tpepper @calebamiles
=> keps: Update ToCs

keps/sig-cloud-provider/20190125-out-of-tree-aws.md, keps/sig-cloud-provider/20190125-out-of-tree-gce.md, keps/sig-cloud-provider/20190125-out-of-tree-ibm.md, keps/sig-cloud-provider/20190125-out-of-tree-openstack.md, keps/sig-cloud-provider/20190125-out-of-tree-vsphere.md, keps/sig-cloud-provider/azure/20190125-out-of-tree-azure.md
correct link error for  KEP for removing in-tree providers.
=> Correct sig cloud provider link errors

keps/sig-cloud-provider/providers/0004-cloud-provider-template.md
I happened to see some broken links when I go through it.
=> fix cloud provider template broken links

keps/sig-cluster-lifecycle/clusterapi/0003-cluster-api.md
/kind bug
/sig docs
the error url is: https://github.com/kubernetes/community/blob/master/contributors/devel/api-conventions.md
the right url is: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md
=> modify the error url of api-conventions

keps/sig-cli/20191111-kui.md
This PR adds a sig-cli/kui KEP.
=> Add kui KEP

keps/sig-cloud-provider/providers/20191206-cloud-provider-huaweicloud.md
Request for adding `Cloud Provider For HUAWEI CLOUD` into the Kubernetes ecosystem as per:
- [Cloud Provider Template](https://github.com/kubernetes/enhancements/blob/2a2714403c831719eff93062a1fc8eefd9238c71/keps/sig-cloud-provider/providers/0004-cloud-provider-template.md)
- [Reporting Conformance Test Results to Testgrid](https://github.com/kubernetes/enhancements/blob/2a2714403c831719eff93062a1fc8eefd9238c71/keps/sig-cloud-provider/0018-testgrid-conformance-e2e.md)
- [Cloud Provider Documentation Requirements](https://github.com/kubernetes/enhancements/blob/2a2714403c831719eff93062a1fc8eefd9238c71/keps/sig-cloud-provider/20180731-cloud-provider-docs.md)
/cc @andrewsykim @cheftako 
cc @kevin-wangzefeng
=> Request cloud provider for HUAWEI CLOUD

keps/sig-node/0035-20190130-topology-manager.md
Guaranteed alignment for multiple containers in a pod.
Removed limitations & one other nit.
WIP until relevant PRs are merged.
=> Topology Manager - Updates for 1.18

keps/sig-cloud-provider/providers/0022-cloud-provider-baiducloud.md
Hi Kim, this new PR is for applying for cloud provider subproject baiducloud, please review the doc and let me know if you have any questions, thanks! @andrewsykim
=> Request for Baidu Cloud Provider Subproject

OWNERS_ALIASES
See also https://github.com/kubernetes/community/pull/4566
=> Update SIG instrumentation leads

keps/sig-windows/20181221-windows-group-managed-service-accounts-for-container-identity.md
Updating the KEP as recommended at https://github.com/kubernetes/enhancements/issues/689#issuecomment-602796731
=> Mark GMSA KEP implemented

keps/sig-api-machinery/0015-dry-run.md
cc @julianvmodesto @palnabarun 
Fixes #576
=> Mark dry-run as implemented

keps/sig-cli/20200115-kubectl-diff.md
cc @julianvmodesto @palnabarun
Fixes #491
=> Mark kubectl-diff as implemented

keps/sig-auth/20190806-serviceaccount-tokens.md
Ref: https://github.com/kubernetes/kubernetes/issues/70679
Ref: https://github.com/kubernetes/enhancements/issues/542
=> propose safe adoption plan for in-cluster clients using fresh token

keps/sig-cluster-lifecycle/clusterapi/0003-cluster-api.md
=> update path api-conventions.md

keps/sig-node/20200127-taint-based-evictions.md
As mentioned in https://github.com/kubernetes/enhancements/issues/166#issuecomment-602795691, this issue has been graduated to GA in the latest release and its enhancement should be updated to stable
=> Update TaintBasedEvictions to implemented

keps/sig-network/0007-pod-ready++.md
Tabs are shown in red by the github markdown renderer
=> Removed tab

keps/sig-network/20180612-ipv4-ipv6-dual-stack.md
Add section for the different types of services.
Headless services weren't considered before.
Remove the need to bind on multiple ip addresses.
Be more restrictive using comma separated strings with CIDRs.
=> Update DualStack KEP

keps/sig-cloud-provider/20190125-out-of-tree-vsphere.md
This supersedes #1675 due to GitHub not doing the sane thing with branch and forks 😭 
Fixes: #670
/assign @andrewsykim @cheftako 
/cc @palnabarun @johnbelamaric
=> Set out-of-tree-vsphere KEP to implemented

keps/0001-kubernetes-enhancement-proposal-process.md, keps/sig-architecture/617-improve-kep-implementation/kep.yaml, keps/sig-contributor-experience/1553-issue-triage/kep.yaml
/assign @justaugustus @johnbelamaric @spiffxp
=> Remove references to sig-pm causing test failures

keps/sig-scheduling/20190409-resource-quota-ga.md
/assign huang-wei
ref: https://github.com/kubernetes/enhancements/issues/986
=> doc: update resource quota scope selectors KEP to implemented

OWNERS_ALIASES
/assign @brancz @logicalhan @ehashman 
cc @wojtek-t 
Context: https://groups.google.com/g/kubernetes-sig-instrumentation/c/j4WzdUE1S84
=> Add dashpole to sig-instrumentation-leads

keps/sig-architecture/960-conformance-behaviors/README.md, keps/sig-architecture/960-conformance-behaviors/kep.yaml
This PR is intended to update the behavior conformance KEP based upon what we have learned as we are implementing it.
=> Conformance Behaviors Phase 2

keps/sig-api-machinery/1693-warnings/README.md, keps/sig-api-machinery/1693-warnings/kep.yaml
Continued from https://github.com/kubernetes/enhancements/pull/1697, moved to implementable
Reviewers:
Approvers:
/assign @seans3 @lavalamp @smarterclayton
=> KEP 1693: move warnings proposal to implementable

keps/sig-storage/20191117-immutable-secrets-configmaps.md
Ref https://github.com/kubernetes/enhancements/issues/1412
=> Clarify wording in `Immutable Secret/ConfigMap' KEP and update implementation history

keps/sig-architecture/1618-conformance-profiles/README.md
=> Conformance Profiles additions 

keps/sig-cloud-provider/20191004-out-of-tree-credential-providers.md
* Staging directory and repository
* Simpler UX - pluginArgs and name instead of args, env vars and
command.
* Remove tokens from plugin response.
=> External Registry Credential Provider updates for 1.19

keps/sig-scheduling/20190926-default-even-pod-spreading.md
=> Update completed tasks and alpha target to 1.19

keps/sig-windows/20190418-windows-security-context.md
Marking the KEP 20190418-windows-security-context.md implemented. RunAsUsername and the GMSA specs that can be specified within a pod's Windows Security Context have both graduated to stable.
=> Marking KEP windows-security-context implemented

keps/sig-api-machinery/1693-warnings/README.md
Update with links to sig-instrumentation discussions and metric design tweaks
* sig-instrumentation discussion
* [notes](https://docs.google.com/document/d/1FE4AQ8B49fYbKhfg4Tx0cui1V0eI4o3PxoqQPUwNEiU/edit#bookmark=id.c3qdrgp1fvnc)
* [recording](https://www.youtube.com/watch?v=cOoDnSTkMc0&list=PL69nYSiGNLP1tue6RXLncPTGjfnBVHP-f&index=2&t=2m33s)
* [mailing list thread](https://groups.google.com/d/msgid/kubernetes-sig-instrumentation/62bfc7c8-aab3-41c7-99cb-e69cf88a0749%40googlegroups.com)
/sig api-machinery instrumentation
/cc @brancz @logicalhan @deads2k
=> KEP 1693: instrumentation updates

keps/sig-api-machinery/20190802-dynamic-coordinated-storage-version.md
=> Mark the storage version API and mechanism as implementable

OWNERS_ALIASES
Add myself to this alias and remove csbell (who stepped back from the role some time ago).
=> Update sig-multicluster-leads alias

OWNERS_ALIASES, keps/sig-multicluster/OWNERS
ref: https://github.com/kubernetes/enhancements/pull/1646
/assign @mrbobbytables @jeremyrickard @johnbelamaric 
/area enhancements
=> Update OWNERS_ALIASES and add keps/sig-multicluster OWNERS

pkg/kepval/keps/proposals.go, pkg/kepval/keps/proposals_test.go
We can add more validations later - I just want to unblock presubmits for correct KEPs now.
=> Update kep validations to support new kep.yaml fields

keps/sig-storage/1412-immutable-secrets-and-configmaps/README.md, keps/sig-storage/1412-immutable-secrets-and-configmaps/kep.yaml
Ref: #1412
Context: https://github.com/kubernetes/enhancements/pull/1620
=> Fill in PRR questionaire for Immutable Secrets/Configmap KEP and migrate to new template

keps/sig-storage/1432-volume-health-monitor/README.md, keps/sig-storage/1432-volume-health-monitor/kep.yaml
This PR adds alpha criteria to the volume health monitoring KEP.
=> Add alpha criteria

keps/sig-scheduling/20200114-multi-scheduling-profiles.md, keps/sig-scheduling/785-scheduler-component-config-api/README.md, keps/sig-scheduling/785-scheduler-component-config-api/kep.yaml
Ref #785 kubernetes/kubernetes#89701
Also links graduation of Multiple Scheduling Profiles to the component config graduation #1451
/wg component-standard
=> KEP: Graduate Scheduler Component Config API to Beta

pkg/kepval/keps/proposals.go, pkg/kepval/keps/proposals_test.go, pkg/kepval/keps/validations/yaml.go
=> Validate stage field from kep YAMLs

pkg/kepval/keps/validations/yaml_test.go
Currently the validation tests have some bad test data (sig and missing required fields). This PR updates the test data to be correct, so the tests now pass.
Fixes: #1777
Signed-off-by: Jeremy Rickard <rickardj@vmware.com>
=> Update kepval tests

keps/sig-cloud-provider/1771-versioning-policy-for-external-cloud-providers/README.md, keps/sig-cloud-provider/1771-versioning-policy-for-external-cloud-providers/kep.yaml
=> KEP: versioning policy for external cloud providers

keps/sig-windows/20190424-windows-cri-containerd.md
- Fixing various linting errors in KEP
- Updating KEP milestones
- Adding new PRR section
=> Updating Windows-CRI-ContainerD KEP for 1.19

keps/sig-node/20200205-build-kubelet-without-docker.md
Now that the diff has been merged, update to implemented and flesh out
implementation history.
=> Update dockerless KEP to implemented

keps/sig-scheduling/1258-default-even-pod-spreading/README.md, keps/sig-scheduling/1258-default-even-pod-spreading/kep.yaml
Ref #1258
Production Readiness Questionnaire left for next release
=> Update Default Even Pod Spreading KEP to new template

keps/sig-instrumentation/20191115-structured-logging.md
* Update reviewers and approvers (based on lgtms on https://github.com/kubernetes/enhancements/pull/1367)
* Add test plan
* Add Release signoff checklist
* Use updated Rediness Review Questionnaire
Update requested by 1.19 Release team for Enchancement freeze.
Ref https://github.com/kubernetes/enhancements/issues/1602
/cc @johnbelamaric
=> Update structured logging KEP for milestone

keps/sig-scheduling/1451-multi-scheduling-profiles/README.md, keps/sig-scheduling/1451-multi-scheduling-profiles/kep.yaml, keps/sig-scheduling/785-scheduler-component-config-api/kep.yaml
Completing new KEP requirements for Multi Scheduling Profiles.
ref #1451
=> Update Multi Scheduling Profiles KEP to new template and add production readiness

keps/sig-api-machinery/1623-standardize-conditions/README.md
Updating the standardize kep for tracking.
=> check boxes for standardize conditions kep

keps/sig-auth/541-external-credential-providers/README.md, keps/sig-auth/541-external-credential-providers/kep.yaml
=> Update external credential providers KEP with GA requirements

keps/sig-scheduling/902-non-preempting-priorityclass/kep.yaml
ref https://github.com/kubernetes/enhancements/issues/902
=> Fix status of NonPreempt Kep

keps/sig-instrumentation/1602-structured-logging/README.md, keps/sig-instrumentation/1602-structured-logging/kep.yaml
KEP issue https://github.com/kubernetes/enhancements/issues/1602
=> Use new format for Structured Logging KEP

keps/sig-cluster-lifecycle/kubeadm/20191125-remove-clusterstatus-from-kubeadm-config.md
=> kubeadm remove clusterstatus KEP: Make minor clarifications

keps/sig-scheduling/785-scheduler-component-config-api/kep.yaml
According to KEP template
/assign @ahg-g 
cc @wojtek-t
=> PRR as approver in scheduler component config KEP

keps/sig-scheduling/1451-multi-scheduling-profiles/kep.yaml, keps/sig-scheduling/785-scheduler-component-config-api/kep.yaml
=> Add comment on PRR approver for reviewed scheduling KEPs

keps/NNNN-kep-template/kep.yaml, keps/sig-auth/266-kubelet-client-certificate-bootstrap-rotation/kep.yaml, keps/sig-instrumentation/1602-structured-logging/kep.yaml, keps/sig-node/1797-configure-fqdn-as-hostname-for-pods/kep.yaml, keps/sig-scheduling/1258-default-even-pod-spreading/kep.yaml, keps/sig-scheduling/895-pod-topology-spread/kep.yaml, keps/sig-scheduling/902-non-preempting-priorityclass/kep.yaml, keps/sig-storage/1412-immutable-secrets-and-configmaps/kep.yaml, keps/sig-storage/1432-volume-health-monitor/kep.yaml, keps/sig-storage/1472-storage-capacity-tracking/kep.yaml, keps/sig-storage/1682-csi-driver-skip-permission/kep.yaml, keps/sig-storage/1698-generic-ephemeral-volumes/kep.yaml, keps/sig-storage/1710-selinux-relabeling/kep.yaml, keps/sig-storage/1790-recover-resize-failure/kep.yaml, keps/sig-storage/695-skip-permission-change/kep.yaml, pkg/kepval/keps/proposals.go, pkg/kepval/keps/proposals_test.go
As discussed on prod-readiness Slack channel
=> Switch feature gate to plural

keps/sig-network/1453-ingress-api/README.md, keps/sig-network/1453-ingress-api/kep.yaml
Signed-off-by: Christopher M. Luciano <cmluciano@us.ibm.com>
xref: #1453
=> ingress: Add updated KEP format for Ingress API GA

keps/sig-network/20180612-ipv4-ipv6-dual-stack.md
the error url is:
https://kubernetes.io/docs/concepts/containers/container-environment-variables
https://kubernetes.io/docs/concepts/containers/container-environment
=> modify the error url of container-environment

keps/sig-architecture/2019-07-16-node-role-label-use.md
=> Add PRR questions to node-role TOC

keps/sig-node/0009-node-heartbeat.md
=> broken link

keps/sig-node/20190920-pod-pid-namespace.md
This updates the process namespace sharing KEP to answer questions raised during a recent sig-node meeting.
=> Address questions about container namespace targeting

keps/sig-node/runtime-class-scheduling.md
=> feat: update runtime class scheduling status

keps/sig-network/20180612-ipv4-ipv6-dual-stack.md
This is a mix of cleanup edits and revisions around `preferDualStack`.  Given that the latter is not fully closed, we should not merge this until we conclude.
/hold
=> Dual stack KEP edits

ISSUE_TEMPLATE.md, README.md, docs/kepval.md, keps/0001-kubernetes-enhancement-proposal-process.md, keps/NNNN-kep-template/README.md, keps/sig-architecture/617-improve-kep-implementation/README.md
Did some light copy editing and removed a few references to sig-pm. A few of these references require replacement text.
=> Made a few copy edits

keps/sig-storage/1845-prioritization-on-volume-capacity/README.md, keps/sig-storage/1845-prioritization-on-volume-capacity/kep.yaml
ref: https://github.com/kubernetes/enhancements/issues/1845
/sig storage
=> KEP-1845: prioritization on volume capacity

keps/sig-network/20180612-ipv4-ipv6-dual-stack.md
Modifications:
1. Changes `.spec.preferDualStack` to `.spec.ipFamilyPolicy` enum.
2. Calls out defaulting for existing services.
3. Calls out handling for headless for without selector.
4. Explicitly calls out `ExternalName` nil fields expectations.
=> dualstack services: change fields to enum

keps/sig-auth/541-external-credential-providers/README.md
This doc change came from https://github.com/kubernetes/kubernetes/pull/91305#discussion_r438077530.
=> Update InstallHint doc upon feedback in related PR

keps/sig-autoscaling/20190307-configurable-scale-velocity-for-hpa.md
Did a minor correction for the last updated field.
=> Corrected the "last-updated" field

keps/sig-storage/1855-csi-driver-service-account-token/README.md, keps/sig-storage/1855-csi-driver-service-account-token/kep.yaml
Ref: kubernetes/kubernetes#86448
=> propose a way to get service account token for csi driver

keps/sig-storage/20190709-csi-snapshot.md
This PR updates the snapshot KEP following the Beta release.
=> Update Snapshot KEP for Beta

keps/sig-multicluster/1645-multi-cluster-services-api/README.md
=> MCS-API: Rename supercluster -> clusterset

README.md
=> update README.md to add 1.19 enhancements sheet

keps/sig-instrumentation/20190605-metrics-stability-migration.md
=> Update metric migration KEP with relevant PRs and current status

keps/sig-instrumentation/20190404-kubernetes-control-plane-metrics-stability.md
=> Update metric stability KEP status

keps/sig-contributor-experience/1553-issue-triage/README.md, keps/sig-contributor-experience/1553-issue-triage/kep.yaml
While there were several sections left unresolved to be discussed later  -  most of the discussions that did take place came back to what was originally discussed. ¯\\_(ツ)_/¯
/cc @castrojo 
/assign @justaugustus @nikhita @cblecker
=> KEP-1553: Update issue triage KEP to implementable

keps/sig-api-machinery/1164-remove-selflink/README.md, keps/sig-api-machinery/1164-remove-selflink/kep.yaml
=> PRR questionaire for SelfLink removal KEP

keps/sig-cli/20191111-kui.md
=> Fix typos and formatting

keps/sig-network/20190603-endpointslices/README.md
This is a follow up from the [related conversation on the sig-network mailing list](https://groups.google.com/g/kubernetes-sig-network/c/UoCOhayZfDY).
/cc @aojea @thockin @bowei
=> Clarifying future of Endpoints in EndpointSlice KEP

keps/sig-scheduling/1258-default-pod-topology-spread/README.md, keps/sig-scheduling/1258-default-pod-topology-spread/kep.yaml
Update what was accomplished in 1.19
To follow: Beta criteria for 1.20
Ref #1258
=> Implementation details for Default Pod Topology Spread

keps/sig-auth/1205-bound-service-account-tokens/README.md, keps/sig-auth/1205-bound-service-account-tokens/kep.yaml
add a section for migration of service account admission controller
ref: kubernetes/kubernetes#70679
=> add a section for service account admission controller migration

keps/sig-api-machinery/1965-kube-apiserver-identity/README.md, keps/sig-api-machinery/1965-kube-apiserver-identity/kep.yaml
=> mark kube-apiserver identity KEP implementable

keps/sig-storage/1845-prioritization-on-volume-capacity/README.md
ref: https://github.com/kubernetes/enhancements/issues/1845#issuecomment-700928688
=> KEP-1845: add graduation criteria for alpha/beta

keps/sig-storage/695-skip-permission-change/README.md, keps/sig-storage/695-skip-permission-change/kep.yaml
Also add some details about mount option support
xref - https://github.com/kubernetes/enhancements/issues/695
cc @msau42 @saad-ali @jsafrane
=> Update fsGroupChangePolicy for beta in 1.20

keps/sig-cli/1020-kubectl-staging/README.md, keps/sig-cli/1020-kubectl-staging/kep.yaml
/assign @pwittrock @seans3 @deads2k
=> Move kubectl-staging to the new KEP format

keps/sig-storage/284-enable-volume-expansion/README.md, keps/sig-storage/284-enable-volume-expansion/kep.yaml
xref https://github.com/kubernetes/enhancements/issues/284
Note to reviewers - I have not updated all the newly introduced sections in PRR but since this feature is already implemented as beta, can we incorporate these sections in later updates?
cc @kubernetes/sig-storage-pr-reviews
=> Bring volume expansion enhancement as a KEP

keps/sig-api-machinery/1623-standardize-conditions/README.md, keps/sig-api-machinery/1623-standardize-conditions/kep.yaml
This merged into k/k with associated docs on the type in 1.19.
=> mark conditions implemented

keps/sig-cli/1441-kubectl-debug/README.md, keps/sig-cli/1441-kubectl-debug/kep.yaml
This includes the following updates, in separate commits:
* Updates to the new KEP format
* Updates the KEP for details that changed during feature implementation
* Proposes support for using `kubectl set image` syntax for mutating multiple container images
* Fill out new KEP sections, expand test plan, promote to beta & seek PRR approval
=> KEP-1441: Update kubectl debug KEP for 1.20 release

keps/sig-apps/19-Graduate-CronJob-to-Stable/README.md, keps/sig-apps/19-Graduate-CronJob-to-Stable/kep.yaml
This builds on top of work started by @barney-s with slight changes to reflect the agreements made in SIG-Apps in the past weeks.
Enhencement issue is https://github.com/kubernetes/enhancements/issues/19
/assign @barney-s @kow3ns @janetkuo @tnozicka
=> KEP for Graduating CronJob to GA

keps/sig-node/2040-kubelet-cri/README.md, keps/sig-node/2040-kubelet-cri/kep.yaml
Signed-off-by: Mrunal Patel <mrunalp@gmail.com>
=> KEP 2040: Kubelet CRI support

keps/sig-storage/1855-csi-driver-service-account-token/README.md, keps/sig-storage/1855-csi-driver-service-account-token/kep.yaml
/cc @msau42 
/cc @kikisdeliveryservice
=> update kep to be eiligible for 1.20

keps/sig-node/2000-graceful-node-shutdown/README.md
* Add alpha graduation criteria
* Update implementation history
Addressing https://github.com/kubernetes/enhancements/issues/2000#issuecomment-702934662
=> Mark graceful node shutdown KEP as implementable

keps/sig-network/0752-endpointslices/README.md, keps/sig-network/0752-endpointslices/kep.yaml
Enhancement issue: https://github.com/kubernetes/enhancements/issues/752
/cc @freehan
=> Updating EndpointSlice KEP to include graduation to GA

keps/sig-storage/695-skip-permission-change/kep.yaml
cc @kubernetes/sig-storage-pr-reviews
=> Change latest milestone for fsgroup kep

keps/sig-storage/1682-csi-driver-skip-permission/README.md
Updates the KEP to match the implementation as performed in https://github.com/kubernetes/kubernetes/pull/92001/ .
=> Updates the FSGroupPolicy KEP to match implementation

keps/sig-instrumentation/1753-logs-sanitization/README.md, keps/sig-instrumentation/1753-logs-sanitization/kep.yaml
/cc @44past4 @dashpole @logicalhan @wojtek-t @ehashman @brancz
=> Move log sanitization to implementable

keps/sig-cluster-lifecycle/kubeadm/2067-rename-master-label-taint/README.md, keps/sig-cluster-lifecycle/kubeadm/2067-rename-master-label-taint/kep.yaml
draft:
https://docs.google.com/document/d/1kPs_zFconMU83LCOfBr_xKXfghn3y9VLLrTUSlCAf4s/edit#
this PR implements pending comments / suggestions from the above draft.
tracking issue at k/e:
https://github.com/kubernetes/enhancements/issues/2067
tracking issue at k/kubeadm:
xref https://github.com/kubernetes/kubeadm/issues/2200
=> sig-cl/kubeadm: add KEP for renaming the "master" label and taint

keps/sig-network/1507-app-protocol/README.md, keps/sig-network/1507-app-protocol/kep.yaml
Enhancement Issue: https://github.com/kubernetes/enhancements/issues/1507
/assign @dcbw @thockin
=> Updating AppProtocol KEP for GA

keps/sig-auth/541-external-credential-providers/README.md
Signed-off-by: Andrew Keesler akeesler@vmware.com
* The goal of these updates is to reach consensus on how best to wire cluster info into exec credential providers so that we can wrap up and merge the implementation (kubernetes/kubernetes#91192).
* These edits were suggested by @liggitt in a conversation we had last week.
* There are still some open questions which will be added as comments.
* Previous PR in this saga: https://github.com/kubernetes/enhancements/pull/1927.
=> Update exec credential provider KEP after convo with sig-auth

keps/NNNN-kep-template/README.md
/hold until after 1.20 enhancements freeze
=> PRR: require approval for implementable KEP status

keps/NNNN-kep-template/README.md
Just addeds some minor questions to better understand the desired outcome and measuring success. First PR so go easy. :)
=> keps: Clarify measuring success and desired outcomes in KEP template

keps/NNNN-kep-template/README.md
The PRR KEP has been migrated to the new KEP format.
=> Update PRR KEP link in KEP template

keps/sig-instrumentation/20191028-metrics-stability-to-beta.md
=> Revert part of #2098.  Metrics stability is not GA

keps/sig-node/606-compute-device-assignment/kep.yaml
Was found by @dashpole in https://github.com/kubernetes/enhancements/pull/1884#discussion_r499757816
Signed-off-by: Alexey Perevalov <alexey.perevalov@huawei.com>
=> Fix misprint in 606-compute-device-assignment

keps/sig-network/20180612-ipv4-ipv6-dual-stack.md
Keep the current behavior for the kubelet probes, i.e., the probe will use the default PodIP `Status.PodIP` if no host parameter is passed to the probe.
This is in favor of having a more resilient and predictable model, to avoid false negative or positives and complicate the healthcheck/probe logic in the kubelet.
Cases are extreme but possible:
- An app can be dual stack and one of the IP families is lagging behind the other, so the first check fails and it round robin. If the app flakes it can be round robin forever and not detect the probe is failing.
- An app can be single stack but open the same port in the other family, or in one of the families it does not return what the check expects
This does not mean that you can not use healthckecks for secondary IP families, because the CNI …
=> dual-stack probes/health checks

keps/sig-network/20190424-NodeLocalDNS-beta-proposal.md
=> Update NodeLocal DNSCache Beta KEP status to Implemented.

keps/sig-autoscaling/0001-container-resource-autoscaling.md
Minor updates to the KEP which reflect current implementation.
=> Updated container resource HPA KEP

keps/sig-node/20190221-livenessprobe-holdoff.md
=> Document implementation history of startupProbe

keps/sig-architecture/1659-standard-topology-labels/README.md, keps/sig-architecture/1659-standard-topology-labels/kep.yaml
=> Mark KEP 1659 as "implemented"

keps/sig-architecture/1659-standard-topology-labels/README.md
I noticed that I forgot to do these.
=> nits in KEP 1659

OWNERS_ALIASES
ref: https://github.com/kubernetes/community/pull/5322
Following https://github.com/kubernetes/community/blob/master/contributors/chairs-and-techleads/leadership-changes.md#leadership-changes
=> Add eddiezane to sig-cli-leads

keps/sig-security/OWNERS
added sig-security directory and OWNERS file, creating a home for future SIG Security KEPs
=> added SIG Security

keps/sig-network/2079-network-policy-port-range/README.md, keps/sig-network/2079-network-policy-port-range/kep.yaml
Signed-off-by: Ricardo Pchevuzinske Katz <ricardo.katz@gmail.com>
This PR adds the KEP for the PortRange addition in NetworkPolicy specification
Issue: #2079
/cc @andrewsykim @jayunit100 @abhiraut 
/assign @thockin @caseydavenport
=> KEP 2079 - Add PortRange KEP

keps/sig-network/1453-ingress-api/kep.yaml, keps/sig-node/1898-hardened-exec/kep.yaml, keps/sig-node/2000-graceful-node-shutdown/kep.yaml, keps/sig-node/2040-kubelet-cri/kep.yaml, keps/sig-storage/1698-generic-ephemeral-volumes/kep.yaml, pkg/kepval/keps/proposals.go, pkg/kepval/keps/validations/yaml.go, pkg/kepval/util/errors.go
=> Extend kepval to validate milestones

keps/sig-contributor-experience/1553-issue-triage/README.md, keps/sig-contributor-experience/1553-issue-triage/kep.yaml
Mark KEP as implemented and add more items to the implementation history.
=> KEP-1553: Change status to implemented

cmd/kepval/main_test.go
Follow up from https://github.com/kubernetes/enhancements/pull/2180
=> PRR approval descriptive errors

keps/sig-cli/1440-kubectl-events/README.md, keps/sig-cli/1440-kubectl-events/kep.yaml, keps/sig-cli/1802-kustomize-components/README.md, keps/sig-cli/1802-kustomize-components/kep.yaml, keps/sig-cli/491-kubectl-diff/README.md, keps/sig-cli/491-kubectl-diff/kep.yaml, keps/sig-cli/859-kubectl-headers/README.md, keps/sig-cli/859-kubectl-headers/kep.yaml, keps/sig-cli/993-kustomize-generators-transformers/README.md, keps/sig-cli/993-kustomize-generators-transformers/kep.yaml
=> Migrate some cli keps to new template

keps/provider-aws/423-network-load-balancer/README.md, keps/provider-aws/423-network-load-balancer/kep.yaml, keps/provider-aws/629-alb-ingress-controller/README.md, keps/provider-aws/629-alb-ingress-controller/kep.yaml, keps/provider-aws/630-ebs-csi-driver/README.md, keps/provider-aws/630-ebs-csi-driver/kep.yaml
=> Migrate some aws keps to new template

keps/sig-contributor-experience/2225-contributor-site/README.md, keps/sig-contributor-experience/2225-contributor-site/kep.yaml
Some of the KEP text is not necessarily relevant to current state, but this at least fleshes out some of the history.
/assign @castrojo @cblecker @nikhita
=> KEP-2225: Add implementation history and implemented stats

keps/sig-api-machinery/1295-insecure-backend-proxy/README.md, keps/sig-api-machinery/1295-insecure-backend-proxy/kep.yaml
This is on the path to moving to GA.  I need to
1. convert to new kep format
2. answer PRR questions
3. indicate that we'll use integration tests in lieu of e2e tests for this particular case and explain why.  Also, retarget to GA
4. retarget the issue
5. update the code to be GA in feature gate
6. indicate complete in kep
=> convert to new dir structure

keps/sig-node/2221-remove-dockershim/README.md, keps/sig-node/2221-remove-dockershim/kep.yaml
Created KEP to track the dockershim removal
https://github.com/kubernetes/enhancements/issues/2221
/sig node
=> created an enhancement issue for dockershim removal

keps/prod-readiness/sig-scheduling/1923.yaml, keps/sig-scheduling/1923-prefer-nominated-node/README.md, keps/sig-scheduling/1923-prefer-nominated-node/kep.yaml
Signed-off-by: Dave Chen <dave.chen@arm.com>
=> Mark the KEP of "prefer nominated node" as "implementable"

keps/sig-node/2254-cgroup-v2/README.md, keps/sig-node/2254-cgroup-v2/kep.yaml
ref #2220
Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>
=> Migrate cgroup-v2 kep to new template

keps/sig-api-machinery/1904-efficient-watch-resumption/README.md, keps/sig-api-machinery/1904-efficient-watch-resumption/kep.yaml
Ref https://github.com/kubernetes/enhancements/issues/1904
=> Update "Efficient watch resumption KEP" to target Beta graduation in 1.21

keps/sig-api-machinery/1872-manifest-based-admission-webhooks/kep.yaml, keps/sig-auth/1205-bound-service-account-tokens/kep.yaml, keps/sig-contributor-experience/1553-issue-triage/kep.yaml, keps/sig-instrumentation/383-new-event-api-ga-graduation/kep.yaml, keps/sig-network/1669-graceful-termination-local-external-traffic-policy/kep.yaml, keps/sig-release/0000-anago-to-krel-migration/kep.yaml, keps/sig-release/1498-kubernetes-yearly-support-period/kep.yaml, keps/sig-release/1729-rebase-images-to-distroless/kep.yaml, keps/sig-release/1731-publishing-packages/kep.yaml, keps/sig-release/1732-artifact-management/kep.yaml, keps/sig-release/1733-release-notes/kep.yaml, keps/sig-release/1734-k8s-image-promoter/kep.yaml, keps/sig-storage/1790-recover-resize-failure/kep.yaml, keps/sig-storage/1855-csi-driver-service-account-token/kep.yaml, keps/sig-storage/1979-object-storage-support/kep.yaml, keps/sig-storage/284-enable-volume-expansion/kep.yaml, keps/sig-storage/695-skip-permission-change/kep.yaml
Ref https://github.com/kubernetes/enhancements/issues/2220
=> Fill in kep-number in kep.yaml in different keps

keps/sig-cli/2206-openapi-features-in-kustomize/README.md, keps/sig-cli/2206-openapi-features-in-kustomize/kep.yaml
This pull request adds proposal to add an OpenAPI field to kustomize for custom resource support. It was presented to the SIG-CLI group at the 12/16/20 meeting.
=> added `openapi features in kustomize` kep

keps/sig-auth/1205-bound-service-account-tokens/README.md, keps/sig-auth/1205-bound-service-account-tokens/kep.yaml
=> prepare KEP for bound beta and rootca ga

keps/sig-api-machinery/2144-clientgo-apply/README.md
Idea here is to provide a constructor to resolve the issues around apply options. This keeps the apply function signature consistent with the rest of the method signatures while still providing guidance to users on how the fieldManager and force fields should be set.
=> Resolve apply options issues for Apply for client-go KEP

keps/prod-readiness/sig-apps/2255.yaml, keps/sig-apps/2255-pod-cost/README.md, keps/sig-apps/2255-pod-cost/kep.yaml
=> Promote pod deletion cost KEP to implementable

keps/sig-testing/2290-new-label-for-trusted-PR-identification/README.md, keps/sig-testing/2290-new-label-for-trusted-PR-identification/kep.yaml, keps/sig-testing/2291-presubmit-config-inside-the-tested-repo/README.md, keps/sig-testing/2291-presubmit-config-inside-the-tested-repo/kep.yaml
Related to: https://github.com/kubernetes/enhancements/issues/2220
Migrating the old KEP files into new format - sig-testing
=> Migrated KEP to new format - sig-testing

keps/sig-cloud-provider/azure/2328-ccm-instance-metadata/README.md, keps/sig-cloud-provider/azure/2328-ccm-instance-metadata/kep.yaml
Related with https://github.com/kubernetes/enhancements/issues/2220, migrate KEP to the new format.
=> Migrate KEP 2328 to new format

keps/sig-node/1972-kubelet-exec-probe-timeouts/kep.yaml
=> Updated kep.yaml for exec timeout to "implemented"

keps/sig-node/606-compute-device-assignment/kep.yaml
Hello!
- Mark the KEP 606-compute-device-assignment as implemented
- Enhancement issue: https://github.com/kubernetes/enhancements/issues/606
Thanks to everyone who participated in this effort and helped make this API to G.A
Special shoutout to @dashpole @derekwaynecarr and @dchen1107, as well as all the Enhancements Leads that pinged us on the issue :D !
/sig node
=> Mark KEP 606-compute-device-assignment as implemented

keps/sig-node/688-pod-overhead/README.md, keps/sig-node/688-pod-overhead/kep.yaml
See kubernetes/kubernetes#88338
/sig node
/kind cleanup
KEP #688
=> Updating to reflect the today state of PodOverhead

keps/prod-readiness/sig-apps/2214.yaml, keps/sig-apps/2214-indexed-job/README.md, keps/sig-apps/2214-indexed-job/kep.yaml
Ref #2214  kubernetes/kubernetes#97169
/sig apps
=> Add KEP for Indexed Job in implementable status

cmd/kepctl/query.go, pkg/kepctl/query.go
Fixes: https://github.com/kubernetes/enhancements/issues/2279
=> Additional query options to kepctl query - author, approver

pkg/kepctl/kepctl.go
kepctl query was only searching the first 30 PRs. This is very bad. This fixes it.
Note: when querying using a SIG regexp, this is takes a lot longer now. That's because it queries all PRs once for each SIG, rather than just once. That will be fixed in a later PR as it is not a functional issue.
/assign @jeremyrickard
/cc @wojtek-t
=> Page through all PRs

keps/sig-cli/2257-kui/README.md, keps/sig-cli/2257-kui/kep.yaml
This PR updates Kui (enhancement issue #2257)  to use the new KEP template (ref #2220)
=> Update Kui KEP to new template

OWNERS_ALIASES
Ref: https://github.com/kubernetes/community/issues/5442
/hold
until https://github.com/kubernetes/community/pull/5443 merges
/cc @alisondy @castrojo @mrbobbytables 
/assign @mrbobbytables
=> Add alisondy to sig-contributor-experience-leads

cmd/kepctl/query.go, pkg/kepctl/query.go
This is Solution 1 as mentioned in the issue.
Fixes #2319
/assign
/area enhancements
/sig release
/kind feature
=> kepctl: add support to query all SIGs

keps/sig-cli/1441-kubectl-debug/README.md
fix broken link https://git.k8s.io/enhancements/keps/sig-node/20190212-ephemeral-containers.md
Signed-off-by: Cria Hu  <huyuqing@inspur.com>
=> modify error url

keps/sig-scheduling/2372-node-labels-quota/README.md, keps/sig-scheduling/2372-node-labels-quota/kep.yaml
I didn't change the format of the README nor I added PRR. This will be left for when we want to actually implement this.
/assign @Huang-Wei
=> Move node label quota to new KEP format

keps/sig-apps/2360-optional-service-environment-variables/README.md, keps/sig-apps/2360-optional-service-environment-variables/kep.yaml
Migrating the old KEP files into new format - sig-apps
=> Migrating from old kep to new template - kep-number: 2360

keps/prod-readiness/sig-instrumentation/1209.yaml, keps/sig-instrumentation/1209-metrics-stability/README.md, keps/sig-instrumentation/1209-metrics-stability/kep.yaml
@logicalhan as promised here's the scaffolding, you'll need to fill this out later for graduation once this merges.
This merges all of the four #1209 docs into one meta.
/assign @logicalhan
=> Migrate KEP-1209 to new template

keps/prod-readiness/sig-node/2053.yaml, keps/sig-node/2053-downward-api-hugepages/README.md, keps/sig-node/2053-downward-api-hugepages/kep.yaml
this will graduate the feature to beta but leave it off by default.
=> intent to promote downward api for hugepages to beta

keps/prod-readiness/sig-node/1967.yaml, keps/sig-node/1967-size-memory-backed-volumes/README.md, keps/sig-node/1967-size-memory-backed-volumes/kep.yaml
Plan to promote the existing Alpha feature to Beta during 1.21 cycle per original KEP plan.
=> Intention to promote SizeMemoryBackedVolumes to beta

keps/sig-architecture/0000-kep-process/README.md, keps/sig-architecture/0000-kep-process/kep.yaml
=> Migrate KEP process template to the new template

keps/prod-readiness/sig-storage/2317.yaml, keps/sig-storage/2317-fsgroup-on-mount/README.md, keps/sig-storage/2317-fsgroup-on-mount/kep.yaml
xref https://github.com/kubernetes/enhancements/issues/2317
/sig storage
=> Add fsgroup mount proposal

keps/prod-readiness/sig-apps/19.yaml, keps/sig-apps/19-Graduate-CronJob-to-Stable/README.md, keps/sig-apps/19-Graduate-CronJob-to-Stable/kep.yaml
=> KEP-19: Graduate CronJob to stable: update stage and milestone

keps/prod-readiness/sig-apps/2232.yaml, keps/sig-apps/2232-suspend-jobs/README.md, keps/sig-apps/2232-suspend-jobs/kep.yaml
KEP issue: https://github.com/kubernetes/enhancements/issues/2232
/sig apps
/cc @soltysh @ahg-g @alculquicondor
=> KEP 2232: add Suspend Job in implementable status

keps/sig-apps/2214-indexed-job/README.md
/sig apps
Ref #2214 
I realized that I should include the JobStatus API change in alpha. Otherwise, I would have to introduce a separate feature gate once we decide to add the field.
However, I will limit alpha for #2307 to not support Indexed Jobs.
=> Add completedIndexes to Indexed Job status

keps/prod-readiness/sig-storage/1845.yaml, keps/sig-storage/1845-prioritization-on-volume-capacity/README.md
we have this feature targeted to 1.21, xref: https://github.com/kubernetes/kubernetes/pull/96347
=> KEP-1845: update the alpha/beta milestones

keps/prod-readiness/sig-instrumentation/1209.yaml, keps/sig-instrumentation/1209-metrics-stability/README.md, keps/sig-instrumentation/1209-metrics-stability/kep.yaml
Filling out the needed things for graduating metrics stability framework.
=> expand on GA requirements for metrics stability framework

keps/sig-apps/2232-suspend-jobs/kep.yaml
=> suspend job: fix kep.yaml title

keps/sig-network/20190920-external-dns.md, keps/sig-storage/1472-storage-capacity-tracking/kep.yaml
Caught some missing fields as part of https://github.com/kubernetes/enhancements/pull/2409.
/assign @palnabarun @jeremyrickard
=> keps: Minor content fixes

keps/sig-instrumentation/1209-metrics-stability/20191028-metrics-stability-to-beta.md, keps/sig-instrumentation/1209-metrics-stability/README.md
Updating stability KEPs with up-to-date information.
=> Update stability KEP(s) with current status(es)

keps/prod-readiness/sig-storage/1855.yaml, keps/sig-storage/1855-csi-driver-service-account-token/README.md, keps/sig-storage/1855-csi-driver-service-account-token/kep.yaml
=> prepare CSIServiceAccountToken for beta

keps/prod-readiness/sig-storage/1698.yaml, keps/sig-storage/1698-generic-ephemeral-volumes/README.md, keps/sig-storage/1698-generic-ephemeral-volumes/kep.yaml
This marks items as completed which are (or soon will be) done.
PRR review will happen as part of merging this PR.
=> generic ephemeral volumes: PRR and beta review

keps/prod-readiness/sig-auth/1205.yaml, keps/sig-auth/1205-bound-service-account-tokens/README.md, keps/sig-auth/1205-bound-service-account-tokens/kep.yaml
=> add missing PRR sections

keps/prod-readiness/sig-storage/1432.yaml, keps/sig-storage/1432-volume-health-monitor/README.md, keps/sig-storage/1432-volume-health-monitor/kep.yaml
Enhancement issue: https://github.com/kubernetes/enhancements/issues/1432
=> Update volume health KEP

keps/prod-readiness/sig-instrumentation/647.yaml, keps/sig-instrumentation/647-apiserver-tracing/README.md, keps/sig-instrumentation/647-apiserver-tracing/kep.yaml
=> Move tracing to 1.21 milestone

keps/prod-readiness/sig-api-machinery/1295.yaml
See the PRR here https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/1295-insecure-backend-proxy/README.md#production-readiness-review-questionnaire
=> confirm PRR reviewer for insecure-skip-backend-proxy

keps/prod-readiness/sig-node/1769.yaml, keps/sig-node/1769-memory-manager/README.md, keps/sig-node/1769-memory-manager/kep.yaml
Update due to comment: https://github.com/kubernetes/enhancements/issues/1769#issuecomment-774876708
=> Submitting a KEP for production readiness approval

keps/prod-readiness/sig-api-machinery/555.yaml, keps/sig-api-machinery/555-server-side-apply/README.md, keps/sig-api-machinery/555-server-side-apply/kep.yaml
Update Server Side Apply KEP for 1.21 GA.
Adds PRR and Graduation Criteria to GA.
=> Update Server Side Apply KEP for 1.21 GA

keps/prod-readiness/sig-node/2411.yaml, keps/sig-node/2411-cri-container-log-rotation/README.md, keps/sig-node/2411-cri-container-log-rotation/kep.yaml
This adds a KEP for issue https://github.com/kubernetes/enhancements/issues/2411
Signed-off-by: Urvashi Mohnani <umohnani@redhat.com>
=> Add KEP for enabling CRIContainerLogRotation by default

keps/prod-readiness/sig-cloud-provider/1959.yaml, keps/sig-cloud-provider/1959-service-lb-class-field/README.md, keps/sig-cloud-provider/1959-service-lb-class-field/kep.yaml
Add alpha prod readiness review for KEP-1959
=> KEP-1959: add prod readiness review for alpha

keps/sig-node/277-ephemeral-containers/README.md
This proposes changes to the Ephemeral Containers KEP that allow deletion of ephemeral containers and configuring of security context.
See: #277
=> Propose removing and security context for Ephemeral Containers

keps/prod-readiness/sig-node/277.yaml, keps/sig-node/277-ephemeral-containers/README.md, keps/sig-node/277-ephemeral-containers/kep.yaml
This updates graduation criteria and completes PRR sections.
=> Update Ephemeral Containers KEP for beta in 1.21

keps/prod-readiness/sig-apps/1591.yaml, keps/sig-apps/1591-daemonset-surge/README.md, keps/sig-apps/1591-daemonset-surge/kep.yaml
APIs and gate went into 1.20, impl will go into 1.21.
=> Update DaemonSet KEP for Alpha in 1.21

keps/prod-readiness/sig-node/2000.yaml, keps/sig-node/2000-graceful-node-shutdown/README.md, keps/sig-node/2000-graceful-node-shutdown/kep.yaml
* Target beta in 1.21
* Add PRR review
Enhancement issue:  https://github.com/kubernetes/enhancements/issues/2000
=> KEP 2000: Update graceful shutdown KEP for beta

keps/prod-readiness/sig-api-machinery/2161.yaml, keps/sig-api-machinery/2161-apiserver-default-labels/README.md, keps/sig-api-machinery/2161-apiserver-default-labels/kep.yaml
Follow up to #2162, moving it to implementable , fixes https://github.com/kubernetes/enhancements/issues/2112
=> apiserver default labels ~ Implementable

keps/prod-readiness/sig-node/2040.yaml, keps/sig-node/2040-kubelet-cri/README.md, keps/sig-node/2040-kubelet-cri/kep.yaml
@derekwaynecarr @dchen1107  ptal.
Signed-off-by: Mrunal Patel <mrunalp@gmail.com>
=> Update CRI kep with latest status

keps/prod-readiness/sig-instrumentation/1748.yaml, keps/sig-instrumentation/1748-pod-resource-metrics/README.md, keps/sig-instrumentation/1748-pod-resource-metrics/kep.yaml
Pod resource metrics will go to beta in 1.21
=> Update pod resource metrics KEP for beta with PRR

keps/prod-readiness/sig-instrumentation/2305.yaml, keps/sig-instrumentation/2305-metrics-cardinality-enforcement/README.md, keps/sig-instrumentation/2305-metrics-cardinality-enforcement/kep.yaml
Update the metric cardinality kep with the request [here](https://github.com/kubernetes/enhancements/issues/2305#issuecomment-774361070)
/assign @johnbelamaric  - for PRR approval
The kep has already been approved. /assign @logicalhan for reviewing the updated part of the kep.
=> Update the metric cardinality kep

keps/prod-readiness/sig-testing/2464.yaml, keps/sig-testing/2464-kubetest2-ci-migration/kep.yaml
ref: #2464 
/cc @BenTheElder @spiffxp @johnbelamaric @saschagrunert
=> Move Kubetest2 CI migration to implementable

keps/prod-readiness/sig-node/213.yaml, keps/sig-node/213-run-as-group/README.md, keps/sig-node/213-run-as-group/kep.yaml
=> Promote RunAsGroup to GA

keps/sig-storage/2451-service-account-token-volumes/README.md, keps/sig-storage/2451-service-account-token-volumes/kep.yaml
Migrating the old KEP files into new format - sig-storage
=> Migrating from old kep to new template: sig-storage 

keps/sig-cluster-lifecycle/addons/2492-Addons-via-Operators/README.md, keps/sig-cluster-lifecycle/addons/2492-Addons-via-Operators/kep.yaml, keps/sig-cluster-lifecycle/addons/2494-Manifest-Bundle/README.md, keps/sig-cluster-lifecycle/addons/2494-Manifest-Bundle/kep.yaml, keps/sig-cluster-lifecycle/clusterapi/2495-Kubernetes-Cluster-Management-API/README.md, keps/sig-cluster-lifecycle/clusterapi/2495-Kubernetes-Cluster-Management-API/kep.yaml, keps/sig-cluster-lifecycle/etcdadm/2496-etcdadm/README.md, keps/sig-cluster-lifecycle/etcdadm/2496-etcdadm/kep.yaml, keps/sig-cluster-lifecycle/image-builder/2497-Kubernetes-Image-Builder/README.md, keps/sig-cluster-lifecycle/image-builder/2497-Kubernetes-Image-Builder/kep.yaml
Migrating the old KEP files into new format - sig-cluster-lifecycle
=> Migrating from old kep to new template: sig-cluster-lifecycle

keps/sig-instrumentation/1602-structured-logging/README.md
/assign @serathius 
/cc @ehashman
=> Fix typos in structured logging KEP README

keps/sig-node/2221-remove-dockershim/README.md
I meant 2022, not 2021
/sig node
/kind cleanup
=> Small typo in year

keps/sig-cli/1020-kubectl-staging/kep.yaml
As requested by @annajung in https://github.com/kubernetes/enhancements/issues/1020#issuecomment-756388434
/assign @eddiezane
=> Update KEP 1020 status to implemented

keps/sig-auth/1513-certificate-signing-request/README.md
The decision was explicitly considered and made consciously.  This adds a detailed explanation for this particular field.
@kubernetes/sig-auth-pr-reviews 
=> elaborate on the decision to make spec.signer required for CSRs

pkg/kepval/repository.go
Ref #2220 
/assign @justaugustus @johnbelamaric
=> Minor kepval changes to better validate dir-based templates

keps/sig-instrumentation/1602-structured-logging/README.md
=> Add e2e tests requirements for Beta structured logging

keps/sig-node/2129-remove-cadvisor-json-metrics/README.md
/assign @annajung @ehashman @dchen1107
=> Add manual test for removal of endpoints

keps/sig-node/2254-cgroup-v2/README.md
=> Update cgroup v2 deps status

keps/sig-apps/2232-suspend-jobs/README.md
/sig apps
cc @soltysh @ahg-g @alculquicondor
=> suspend jobs: add note about StartTime and ADS

keps/sig-api-machinery/1040-priority-and-fairness/README.md
This builds on #2543 by switching the scheduling in the virtual world and including a more detailed explanation of why it is expected to be efficient at runtime.
=> Swich from serial to concurrent transmision in virtual world

keps/sig-apps/2214-indexed-job/README.md, keps/sig-apps/2214-indexed-job/kep.yaml
Incorporate fixes done during implementation.
Ref #2214
=> Update implementation history for Indexed Job

keps/sig-cloud-provider/2436-controller-manager-leader-migration/README.md
This PR fixes errors in sample configuration and indents.
https://github.com/kubernetes/enhancements/issues/2436
/kind cleanup
=> (KEP-2436) fix errors in sample configuration and formatting.

keps/sig-instrumentation/1209-metrics-stability/README.md, keps/sig-instrumentation/1209-metrics-stability/kep.yaml, keps/sig-instrumentation/1209-metrics-stability/kubernetes-control-plane-metrics-stability.md
=> update status on metric stability framework

keps/sig-storage/1412-immutable-secrets-and-configmaps/README.md, keps/sig-storage/1412-immutable-secrets-and-configmaps/kep.yaml
=> Mark Immutable secrets/configmaps KEP as implemented

keps/prod-readiness/sig-apps/2255.yaml, keps/sig-apps/2255-pod-cost/README.md, keps/sig-apps/2255-pod-cost/kep.yaml
=> Promote PodDeletionCost to Beta

keps/sig-auth/1393-oidc-discovery/kep.yaml
The Enhancement is now GA: https://github.com/kubernetes/enhancements/issues/1393
=> Mark ServiceAccountIssuerDiscovery KEP implemented

keps/sig-node/1967-size-memory-backed-volumes/README.md, keps/sig-node/1967-size-memory-backed-volumes/kep.yaml
related to https://github.com/kubernetes/enhancements/issues/1967
related to https://github.com/kubernetes/kubernetes/pull/101048
=> Move 1967 Support to size memory backed volumes to Beta

keps/sig-apps/2307-job-tracking-without-lingering-pods/README.md, keps/sig-apps/2307-job-tracking-without-lingering-pods/kep.yaml
Ref #2307 
- Update target milestones
- Use shorter feature gate name
- Add finalizer for Jobs
- Count deleted running Pods as failed to simplify counting orphan pods
- Add support for Indexed Jobs since alpha, with a simplified algorithm.
/sig apps
=> Update KEP for Job Tracking

keps/NNNN-kep-template/README.md
Update the "how can a rollout fail" to include rollbacks. Add text to poke people to think about HA and large clusters.
/assign @deads2k @ehashman @wojtek-t
=> Tweak PRR guidance to consider HA

keps/prod-readiness/sig-scheduling/2249.yaml, keps/sig-scheduling/2249-pod-affinity-namespace-selector/README.md, keps/sig-scheduling/2249-pod-affinity-namespace-selector/kep.yaml
ref https://github.com/kubernetes/enhancements/issues/2249
=> graduate pod affinity namespaceselector to beta

keps/sig-auth/1393-oidc-discovery/kep.yaml
=> mark OIDC discovery feature as implemented

keps/prod-readiness/sig-apps/2599.yaml, keps/sig-apps/2599-minreadyseconds-for-statefulsets/README.md, keps/sig-apps/2599-minreadyseconds-for-statefulsets/kep.yaml
Introduce minReadySeconds in StatefulSets
=> Introduce minReadySeconds in StatefulSets

keps/sig-network/1024-nodelocal-cache-dns/README.md
=> Update NodeLocalDNS KEP with HA option in IPVS

keps/sig-storage/2317-fsgroup-on-mount/kep.yaml
Switch milestone of fsgroup proposal
=> Change milestone of mount fsgroup proposal

keps/sig-api-machinery/1040-priority-and-fairness/README.md
/assign @lavalamp @deads2k 
/cc @MikeSpreitzer @tkashem @yue9944882 
I'm aware that there are couple rough edges here when opening the PR, but it should make the discussion more concrete and more targeted if we have something specific to refer to.
=> Update P&F KEP with support LIST requests

keps/sig-api-machinery/1040-priority-and-fairness/README.md
Split from https://github.com/kubernetes/enhancements/pull/2632
/assign @lavalamp @deads2k 
/cc @MikeSpreitzer @tkashem @yue9944882
=> Update P&F KEP with support WATCH requests 

keps/sig-scheduling/2249-pod-affinity-namespace-selector/kep.yaml
ref https://github.com/kubernetes/enhancements/issues/2249
=> Updated latest milestone of Pod Affinity NamespaceSelector

keps/sig-node/2000-graceful-node-shutdown/README.md
s/killPodfunction/killPod function
=> Small space typo fix

keps/sig-network/1864-disable-lb-node-ports/kep.yaml
Signed-off-by: Hanlin Shi <shihanlin9@gmail.com>
Update the maturity and milestone of ServiceLBNodePortControl feature.
=> Update ServiceLBNodePortControl feature status

keps/sig-node/34-sysctl-fields/README.md, keps/sig-node/34-sysctl-fields/kep.yaml
=> Mark sysctls as implemented

keps/prod-readiness/sig-node/2413.yaml, keps/sig-node/2413-seccomp-by-default/README.md, keps/sig-node/2413-seccomp-by-default/kep.yaml
This adds the corresponding KEP for https://github.com/kubernetes/enhancements/issues/2413
PTAL @mrunalp @kubernetes/sig-node-proposals
=> Add KEP for enabling seccomp by default

keps/prod-readiness/sig-api-machinery/1693.yaml, keps/sig-api-machinery/1693-warnings/README.md, keps/sig-api-machinery/1693-warnings/kep.yaml
Updated milestone to GA, added PRR questionnaire
for api-machinery ack
/assign @ehashman 
for PRR
For https://github.com/kubernetes/enhancements/issues/1693
=> GA 1693: warnings

keps/sig-apps/1847-autoremove-statefulset-pvcs/README.md, keps/sig-apps/1847-autoremove-statefulset-pvcs/kep.yaml
=> Update KEP 1847 for 1.22 milestone

keps/prod-readiness/sig-network/2433.yaml, keps/sig-network/2433-topology-aware-hints/README.md, keps/sig-network/2433-topology-aware-hints/kep.yaml
This is a follow up from https://github.com/kubernetes/enhancements/pull/2706#discussion_r629881918.
/sig network
=> Updating topology stage to beta for PRR approval

keps/sig-node/281-dynamic-kubelet-configuration/README.md, keps/sig-node/281-dynamic-kubelet-configuration/kep.yaml
This is a backfill of the Dynamic Kubelet Configuration KEP.
- KEP: https://github.com/kubernetes/enhancements/issues/281
- Initial PR: https://github.com/kubernetes/kubernetes/pull/29459 I took the list of reviewers from it
- I kept all the PRR sections as TODO for the upcoming deprecation effort
=> backfill the dynamic kubelet configuration kep #281

keps/sig-storage/2317-fsgroup-on-mount/README.md
Fill up implementation history, drawback and alternatives etc. 
xref #2317
=> Add new sections in kep

keps/sig-api-machinery/1040-priority-and-fairness/README.md
Ref https://github.com/kubernetes/enhancements/issues/1040
Follow up from https://github.com/kubernetes/enhancements/pull/2632/files#r625907446 discussion
/cc @tkashem @MikeSpreitzer
=> State P&F goals explicitly

pkg/repo/output.go, pkg/repo/query.go
Fixes #2321 
/assign
/area enhancements
/sig release
/kind feature
=> kepctl: add CSV output support to query subcommand

README.md
=> modify links of README.md

keps/prod-readiness/sig-cloud-provider/2436.yaml, keps/sig-cloud-provider/2436-controller-manager-leader-migration/README.md, keps/sig-cloud-provider/2436-controller-manager-leader-migration/kep.yaml
This PR requests Production Readiness Review for KEP-2436, which is going beta in milestone 1.22
https://github.com/kubernetes/enhancements/issues/2436
=> PRR: KEP-2436 Leader Migration for Controller Managers to beta

keps/prod-readiness/sig-node/2712.yaml, keps/sig-node/2712-pod-priority-based-graceful-node-shutdown/README.md, keps/sig-node/2712-pod-priority-based-graceful-node-shutdown/kep.yaml
@derekwaynecarr @bobbypage 
Signed-off-by: Mrunal Patel <mrunalp@gmail.com>
=> Pod priority based graceful node shutdown

keps/prod-readiness/sig-windows/1122.yaml, keps/sig-windows/1122-windows-csi-support/README.md, keps/sig-windows/1122-windows-csi-support/kep.yaml
=> Update CSI Windows KEP for GA

keps/sig-instrumentation/1602-structured-logging/kep.yaml
=> Update KEP 1602 milestone metadata

keps/prod-readiness/sig-api-machinery/2558.yaml, keps/sig-api-machinery/2558-publish-version-openapi/README.md, keps/sig-api-machinery/2558-publish-version-openapi/kep.yaml
Ref: https://groups.google.com/g/kubernetes-sig-architecture/c/UmPwm-J3ztE/m/QckZWJAABQAJ
For https://github.com/kubernetes/enhancements/issues/2558
Follow up to https://github.com/kubernetes/enhancements/pull/2559
POC in https://github.com/kubernetes/kubernetes/pull/99307
/cc @thockin @liggitt @dims @hh @lavalamp @sttts @deads2k 
=> Add KEP for publishing versioning info in OpenAPI

keps/prod-readiness/sig-network/2079.yaml, keps/sig-network/2079-network-policy-port-range/README.md, keps/sig-network/2079-network-policy-port-range/kep.yaml
Signed-off-by: Ricardo Pchevuzinske Katz <ricardo.katz@gmail.com>
This PR proposes the graduation of KEP #2079  to Beta
/assign @wojtek-t @JamesLaverack @thockin 
/sig network
=> Propose EndPort graduation to Beta

keps/prod-readiness/sig-api-machinery/2161.yaml
https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/2161-apiserver-default-labels/README.md has completed PRR, but slipped past some automation.  This adds me as the approver so the paperwork is correct for future scripts.
=> update automatic namespace labels KEP PRR file

keps/prod-readiness/sig-node/2238.yaml, keps/sig-node/2238-liveness-probe-grace-period/README.md, keps/sig-node/2238-liveness-probe-grace-period/kep.yaml
=> Update probe grace period KEP to beta

keps/prod-readiness/sig-storage/1790.yaml, keps/sig-storage/1790-recover-resize-failure/README.md, keps/sig-storage/1790-recover-resize-failure/kep.yaml
xref https://github.com/kubernetes/enhancements/issues/1790
=> Fix recover from resizing kep based on pod resizing design

keps/prod-readiness/sig-node/2254.yaml, keps/sig-node/2254-cgroup-v2/README.md, keps/sig-node/2254-cgroup-v2/kep.yaml
Replaces #2689 to address comments
=> Cgroups v2: Update latest milestone

keps/prod-readiness/sig-node/2254.yaml, keps/sig-node/2254-cgroup-v2/README.md, keps/sig-node/2254-cgroup-v2/kep.yaml
Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>
=> cgroupv2: update latest-milestone

pkg/repo/validate.go
Factored validate file into own func, the defer was not being
called on each iteration. This results in the tool keeping
every KEP yaml open during execution.
=> Fix too many open files

hack/.notableofcontents, keps/prod-readiness/README.md
Per conversation with @JamesLaverack and @justaugustus on Slack, this PR adds some documentation for PRRs to their containing folder.
=> added readme for PRR process

keps/sig-windows/1981-windows-privileged-container-support/README.md
Add note from feedback so we do loose track for graduation
xref: https://github.com/kubernetes/kubernetes/pull/99576/files#r632577140
=> Update graduation criteria for alpha

keps/sig-scheduling/2458-node-resource-score-strategy/kep.yaml
ref: https://github.com/kubernetes/enhancements/issues/2458
=> update latest-milestone for single scoring plugin kep

keps/prod-readiness/sig-network/2086.yaml, keps/sig-network/2086-service-internal-traffic-policy/README.md, keps/sig-network/2086-service-internal-traffic-policy/kep.yaml
=> KEP-2086: update beta milestone for v1.22

keps/prod-readiness/sig-scheduling/1923.yaml, keps/sig-scheduling/1923-prefer-nominated-node/README.md, keps/sig-scheduling/1923-prefer-nominated-node/kep.yaml
ref: https://github.com/kubernetes/enhancements/issues/1923
Signed-off-by: Dave Chen <dave.chen@arm.com>
=> Graduate prefer nominated node to beta

keps/sig-apps/19-Graduate-CronJob-to-Stable/kep.yaml
Follow up to https://groups.google.com/g/kubernetes-sig-release/c/LejSpoeCiWg/m/FtWBMrzzAgAJ
=> Fix kep.yaml for cronjob KEP for 1.22

keps/sig-architecture/917-go-modules/README.md
Ref: https://github.com/kubernetes/kubernetes/pull/102454#issuecomment-851912151
/hold
for https://github.com/kubernetes/kubernetes/pull/102454 to merge
/cc @liggitt @dims
=> Update go modules KEP to stop publishing synthetic Godeps.json files

keps/sig-apps/19-Graduate-CronJob-to-Stable/README.md
Mention issue for timezone support.
Also includes a link to the prior effort.
=> KEP-19: mention issue for timezone support

keps/sig-cloud-provider/2436-controller-manager-leader-migration/README.md
This is a minor change of KEP-2436 Leader Migration for Controller Managers https://github.com/kubernetes/enhancements/issues/2436 that defines support of `*` in the `component` field, and use `*` in the default configuration.
(Impact on release) This PR is purely implementation details intended to improve usability. There is no change to any promise or graduation criteria. This PR will in no way undermine Production Readiness.
=> KEP-2436: wildcard and default value

keps/sig-apps/2307-job-tracking-without-lingering-pods/README.md
Then, the finalizer can be used by the job controller to determine if the Job should be tracked with finalizers.
There is no longer need for a distinction between empty struct and nil.
/sig apps
=> Add Job finalizer on creation strategy

.github/issue_template.md, .github/pull_request_template.md
Signed-off-by: Anna Jung (VMware) <antheaj@vmware.com>
- duplicate of https://github.com/kubernetes/enhancements/pull/2554 with a few changes
- Add a pull request template to the repo
fixes https://github.com/kubernetes/enhancements/issues/2518
=> Add pull request template

keps/sig-apps/2307-job-tracking-without-lingering-pods/README.md
And add note about keeping the legacy behavior
#2307
/sig apps
=> Update use of Job annotation instead of finalizer

keps/sig-node/2400-node-swap/README.md
Per https://github.com/kubernetes/kubernetes/pull/102823/files#r653144961
=> Update NoSwap SwapBehavior to LimitedSwap

keps/sig-auth/2784-csr-duration/README.md, keps/sig-auth/2784-csr-duration/kep.yaml
- One-line PR description: Update CSR Duration KEP to match implementation
- Issue link: #2784
=> KEP-2784: Update CSR Duration KEP to match implementation

keps/sig-cluster-lifecycle/wgs/783-component-base/README.md
Signed-off-by: Madhav Jivrajani <madhav.jiv@gmail.com>
- One-line PR description: fix link for component arch diagram in component base kep. 
- Issue link: none 
=> Fix link for component architecture image

keps/sig-node/2400-node-swap/README.md, keps/sig-node/2400-node-swap/kep.yaml
- One-line PR description: Renames feature flag to NodeSwap from NodeSwapEnabled
- Issue link: #2400
- Other comments: See https://github.com/kubernetes/kubernetes/pull/103553
=> KEP-2400: Rename feature flag to NodeSwap

keps/sig-storage/1472-storage-capacity-tracking/README.md
- One-line PR description: storage capacity: mutable CSIDriverSpec field
- Issue link: https://github.com/kubernetes/enhancements/issues/1472
=> KEP-1472: storage capacity: mutable CSIDriverSpec field

OWNERS_ALIASES
Context:
kubernetes/community#5728
=> Add sig-auth lead

keps/sig-api-machinery/1693-warnings/kep.yaml
=> Mark 1693 warnings KEP as implemented

keps/sig-storage/1855-csi-driver-service-account-token/kep.yaml
- One-line PR description: change status to `implemented`
- Issue link: https://github.com/kubernetes/enhancements/issues/2047
/cc @msau42
=> KEP-1855: update the state of CSIServiceAccountToken

keps/sig-node/1797-configure-fqdn-as-hostname-for-pods/kep.yaml
- One-line PR description: Change status to implemented
- Issue link: https://github.com/kubernetes/enhancements/issues/1797
=> KEP-1797: Changing status to implemented

keps/sig-windows/2258-node-service-log-viewer/kep.yaml
Update the milestones on the KEP for node service log viewer
=> KEP-2258: Update milestones

keps/sig-apps/2232-suspend-jobs/kep.yaml
- One-line PR description: Updates the status to implemented. I must have forgotted to do this when graduating the KEP to beta. Implementation, etc. are all done, this is a simple status update.
- Issue link: https://github.com/kubernetes/enhancements/issues/2232
- Other comments: cc @alculquicondor @soltysh @janetkuo
=> KEP-2232: mark as implemented

keps/prod-readiness/sig-apps/2307.yaml, keps/sig-apps/2307-job-tracking-without-lingering-pods/README.md, keps/sig-apps/2307-job-tracking-without-lingering-pods/kep.yaml
Ref #2307
Updates graduation criteria and completes PRR.
=> Graduate JobTrackingWithFinalizers to beta in 1.23

keps/sig-network/0752-endpointslices/kep.yaml
- One-line PR description: EndpointSlice Enhancement has graduated and can be considered implemented.
- Issue link: https://github.com/kubernetes/enhancements/issues/752
fixes #752 
/cc @aojea @robscott @wojtek-t
=> KEP-752: Updating status to implemented

keps/sig-network/2438-dual-stack-apiserver/README.md, keps/sig-network/2438-dual-stack-apiserver/kep.yaml
Make the apiserver service dual-stack in dual-stack clusters
=> KEP 2438: Dual-stack apiserver

keps/prod-readiness/sig-cli/1440.yaml, keps/sig-cli/1440-kubectl-events/README.md, keps/sig-cli/1440-kubectl-events/kep.yaml
- One-line PR description: update KEP-1440 with new KEP template and PRR needed for alpha implementation
- Issue link: #1440
- Other comments: as requested in https://github.com/kubernetes/enhancements/issues/1440#issuecomment-911867179
/assign @eddiezane 
for sig-cli review
for PRR review
=> KEP-1440: Update  KEP with new template and PRR

keps/sig-node/1287-in-place-update-pod-resources/kep.yaml, keps/sig-node/2273-kubelet-container-resources-cri-api-changes/kep.yaml
- One-line PR description: In-place pod vertical scaling slipped to 1.23 so we need to update milestones the core feature KEP and the related CRI changes KEP.
- Issue link:
- https://github.com/kubernetes/enhancements/issues/1287
- https://github.com/kubernetes/enhancements/issues/2273
=> Update milestones for In-place pod vertical scaling and Kubelet CRI changes KEPs

keps/prod-readiness/sig-storage/2317.yaml, keps/sig-storage/2317-fsgroup-on-mount/README.md, keps/sig-storage/2317-fsgroup-on-mount/kep.yaml
- One-line PR description: Completing PRR questionnaire
/assign @deads2k @gnufied
/cc @jsafrane @xing-yang 
/sig storage
=> KEP-2317: PRR questionnaire for DelegateFSGroupToCSI beta

keps/prod-readiness/sig-storage/2317.yaml, keps/sig-storage/2317-fsgroup-on-mount/README.md, keps/sig-storage/2317-fsgroup-on-mount/kep.yaml
- One-line PR description: update KEP metadata for beta; update feature gate name to the latest version
/assign @gnufied @salaxander 
/sig storage
=> FSGroup CSI delegation KEP: update metadata, update feature gate name to the latest version

keps/prod-readiness/sig-cloud-provider/1959.yaml, keps/sig-cloud-provider/1959-service-lb-class-field/kep.yaml
- One-line PR description: update ServiceLoadBalancerClass feature to GA for v1.23
- Issue link: https://github.com/kubernetes/enhancements/issues/1959
=> kep-1959: update ServiceLoadBalancerClass feature to GA

keps/sig-cli/2590-kubectl-subresource/kep.yaml
Update milestone of kubectl subresource KEP (KEP 2590)
- Issue link:
https://github.com/kubernetes/enhancements/issues/2590
=> kep: kubectl subresource - update milestone

keps/sig-apps/1847-autoremove-statefulset-pvcs/README.md, keps/sig-apps/1847-autoremove-statefulset-pvcs/kep.yaml
- One-line PR description: Updating milestone for 1.23
- Issue link: #1847
=> Update for 1.23 plans

keps/sig-apps/2255-pod-cost/README.md
Just a tiny typo
- Issue link:
=> Fix tiny typo

keps/sig-node/2040-kubelet-cri/kep.yaml
Signed-off-by: Mrunal Patel <mpatel@redhat.com>
Update milestone for 1.23
- Issue link:
https://github.com/kubernetes/enhancements/issues/2040
@mikebrow @deads2k ptal
=> KEP 2040: Update milestone for beta to 1.23

keps/prod-readiness/sig-scheduling/2891.yaml, keps/sig-scheduling/2891-simplified-config/README.md, keps/sig-scheduling/2891-simplified-config/kep.yaml
- One-line PR description: Adds the initial KEP for a simplified multi-point scheduler plugin config
- Issue link: https://github.com/kubernetes/enhancements/issues/2891
=> KEP-2891: Simplified scheduler plugin config

keps/prod-readiness/sig-cloud-provider/2699.yaml, keps/sig-cloud-provider/2699-add-webhook-hosting-to-ccm/README.md, keps/sig-cloud-provider/2699-add-webhook-hosting-to-ccm/kep.yaml
Adding the ability to create cloud providers processes supporting
webhooks. This is specifically a framework change.
Replaces #2701
=> Adding webhook extension support to the CCM

keps/sig-storage/625-csi-migration/README.md, keps/sig-storage/625-csi-migration/kep.yaml
- One-line PR description: Update some wording for CSI Migration KEP
/cc @msau42 
/sig storage
=> KEP-625: Update wording for CSI Migration kep
