release-1.3/features-1.3.md
dlorenc seems to be doing all of the hacking here, I don't think we should
overload bgrant with more stuff.
7376cbd (Brandon Philips, 28 minutes ago)
release-1.3/features-1.3: add CoreOS to minikube
I work at CoreOS and contributed the VMware Fusion backend for minikube and
fixed upstream libmachine bugs.
=> 683ed1d (Brandon Philips, 27 minutes ago)    release-1.3: features-1.3: make dlorenc the minikube assignee

release-1.4/Release-1.4.md
As we have discussed during the 2016/07/14 Kubernetes community meeting, this is the proposal to move https://github.com/kubernetes/community/wiki/Release-1.4 to the features repo.
=> Added Release-1.4.md

ISSUE_TEMPLATE.md
During the 1.3 retrospective one of the things we identified was that UX
and docs were coming long after a feature was perceived to be "done".
Further, the proposals might have changed while the feature was being
built. A few examples of this are PetSet or RBAC which landed in 1.3 but
the user experience rough sketch would have been helpful to get everyone
understanding the feature and as a starting off point for writing "real
docs".
=> ISSUE_TEMPLATE: add a requirement for WIP docs

release-1.4/Release-1.4.md
In the 1.4 schedule, the release date for 1.5 was off.
=> Update the 1.5 release date to Mon Nov 7

ISSUE_TEMPLATE.md
The terms "before alpha", "before beta", "before stable" may confuse the actual meaning of the section. 
I'd like to name the section with the "stage" purely, while checked or unchecked bullet will define the actual status of the feature.
=> Removing the word "before" (stage) in the feature checklist

EXCEPTIONS.md
Prior to the change, the Markdown rendering created a long-running paragraph without line breaks that didn't match the source's intent.
Compare current [source](https://raw.githubusercontent.com/kubernetes/features/bdb3cb9e41c656c62e67230bb05107173ca5c619/EXCEPTIONS.md) to current [rendering](https://github.com/kubernetes/features/blob/bdb3cb9e41c656c62e67230bb05107173ca5c619/EXCEPTIONS.md).
=> Improve readability of rendered exception questionnaire

release-1.5/release-notes-draft.md
Adds a brief note on what versions of external dependencies were used in CI. In future releases this section should link to an easy to understand test matrix for users.
=> Add brief section about external dependencies

release-1.6/release-1.6.md
notifies community that only milestone will determine whether an issue is release blocking or not
=> update release blocking issue handling for 1.6

release-1.6/release-notes-draft.md
Add some more detail and references.
This is a continuation of #211.
Astute readers will notice that I accidentally checked this in directly and then reverted it.  Sorry about that.
=> Tweak kubeadm release notes

release-1.6/release-notes-draft.md
We really need people to back up before attempting this upgrade, and to understand the scenarios where there is no alternative but to restore from backup.
I hope this is enough to persuade users that a backup really is needed this time, but I worry that it's still not enough.
=> Try to persuade people to backup etcd

release-1.7/release_team.md
Proposes Caleb Miles (myself) as the Release Team Secondary for 1.7. The Secondary has helped picked up less technical work to allow the Release Team Lead to load shed.
=> Propose Caleb Miles as member of 1.7 release team

release-1.7/release-notes-draft.md
I do not have the committed hours to shepherd release notes all the way through but have volunteered to do a quick first cut, mostly based on the features spreadsheet.  I have dropped TODO's on places that need filling in.  I will send followon PR's as I am able to help with content and wordsmithing.
I started with the release-1.5/release-notes-draft.md file, and removed all content under the existing headings.
I used the following script to start populating the features section
```sh
for sig in $(hub issue -M 6 | sed -e 's|.*sig/\([^ ]*\).*|\1|g' | sort | uniq); do
echo "- **$sig**"
for stage in alpha beta stable; do 
hub issue -M 6 -l sig/$sig,stage/$stage -f \
"  - [$stage] %t ([kubernetes/features%i](%U))%n";
done
done
```
I noticed the following sections in the …
=> Initial incomplete release notes draft for 1.7

release-1.7/release-notes-draft.md
it seems like there was a different space character used in those two lines.
=> fix 1.7 release notes indentation to properly show sublists

release-1.7/release-notes-draft.md
ref: https://github.com/kubernetes/release/pull/356
FYI @dchen1107 @jbeda
=> Add note about cAdvisor not listening on 0.0.0.0 by default in the kubeadm packages

release-1.7/release-notes-draft.md
It is appropriate that kubernetes/kubernetes#42336 is in Enhancement of CLI.
> * Kubectl config use-context now supports completion ([#42336](https://github.com/kubernetes/kubernetes/pull/42336), [@superbrothers](https://github.com/superbrothers))
=> Move kubernetes/kubernetes#42336 to Enhancement of CLI

release-1.8/release-1.8.md, release-1.8/release_team.md
Approximate timeline and schedule for the Kubernetes 1.8 release
@kubernetes/sig-release-misc
=> First pass at 1.8 schedule

release-1.8/release_team.md
Updated to the release team as agreed upon by SIG Release 7/21/2017, 21:00 UTC.  Vacancies still need volunteers.
=> Updated the release team as it currently stands

release-1.8/release_notes_draft.md
These are mostly populated from the [issues](https://github.com/kubernetes/features/issues?q=is%3Aopen+is%3Aissue+milestone%3A1.8+label%3Asig%2Fcluster-lifecycle) labeled for sig/cluster-lifecycle and 1.8. I have reworded them in places to change from future to past tense and have more consistent verbiage.
CC @timothysc @luxas @justinsb @jbeda @mkumatag @ixdy @wlan0 @aaronlevy @diegs
Could everyone on the above CC list please take a look at the feature(s) you own and sign off on their representation here?
Also, if there is anything that is definitely going to slip the 1.8 release, now is a good time to pull it out of the release notes and update its issue.
=> First draft of SIG Cluster Lifecycle related relnotes.

release-1.8/release_notes_draft.md
This notes that autoscaling/v2 is graduating from alpha1 to beta1, and
adds a warning about upgrade compatibility.
=> Release Notes: v1.8: Add HPA v2 graduation notes

release-1.8/release_notes_draft.md
Our draft was already merged in https://github.com/kubernetes/features/pull/391, so checking off the SIG from the checklist.
=> Checking off SIG Cluster Lifecycle for 1.8 draft.

release-1.8/release_notes_draft.md
apps/v1beta2 is a new API version in 1.8. Changes to this API within the same release does not require a release note. 
extensions/v1beta1 Deployment field deprecation should be announced.
=> Fix deprecation announcements for sig-apps

release-1.8/release_notes_draft.md
=> release notes: high level sig-auth release notes for 1.8

release-1.8/release_notes_draft.md
Release notes for Docker 1.13 (17.03) validation in https://github.com/kubernetes/kubernetes/issues/42926.
/assign @dchen1107 
/assign @radhikapc
=> Add Docker release notes for 1.8

release-1.8/release_notes_draft.md
Add notes about advanced auditing changes. cc @sttts @CaoShuFeng @soltysh 
https://github.com/kubernetes/kubernetes/pull/48051 has been approved, so adding it here.
/cc @radhikapc
=> sig-auth release notes: add advanced audit to action required, add selfsubjectrulesreview

EXCEPTIONS.md
We're a team now so reflect that.
**cc: @kubernetes/kubernetes-release-managers**
=> Use "Release Team Lead" rather than "Release Czar" when describing the exception process

release-1.8/release_notes_draft.md
Marking SIG-OpenStack complete, both v1.8 milestone targeted items were merged with release-note-none.
=> Mark SIG-OpenStack complete

release-1.8/release_notes_discussion.md
This document began as a discussion between Radhika and Jennifer about possible changes to the release notes and issues that need to be addressed (but not necessarily tracked as GH issues or in GH PRs). Sharing with the larger team.
=> add working doc for discussing release note revisions

release-1.8/release_notes_draft.md
=> Update 1.8 release notes for sig-storage

release-1.8/release_notes_draft.md
we have no release artifacts for kubernetes/kubernetes v1.8,
so no release notes either; ongoing improvements are taking
place over in kubernetes/test-infra
=> sig-testing release notes for v1.8

release-1.8/release_notes_draft.md
Note, #442 should be merged as well to close out SIG Apps.
/cc @jdumars @spiffxp
=> Updating the 1.8 release notes per SIG Apps changes

release-1.8/release_notes_draft.md
When the major theme bullet was remoted naming the objects from the
apps/v1beta2 it left an information gap. This restores the list
of objects now under a SIG
=> Restore names changed in the apps api group

release-1.8/release_notes_draft.md
The design proposals were organized according to SIGs in kubernetes/community#1010. This led to a couple of broken links.
=> Fix links in 1.8 release notes

release-1.8/release_notes_draft.md
- Auditing is still not enabled by default, but if auditing is enabled then advanced auditing is the default behavior
- The policy file is only required if auditing should be enabled.
=> Tweak audit beta release notes

release-1.8/release_notes_draft.md
I generated this release note using github APIs and looking into PRs and Issues with sig-api-machinery label. Thus we may have missed some PRs as we do not mandate sig labels on PRs (yet). The categories are all guesses and needs your comment.
cc @lavalamp @kubernetes/sig-api-machinery-pr-reviews
=> API Machinery release notes

release-1.8/release-notes-draft.md
Sub-sections still to do:
- Scheduling
- Storage
At this point edits are minimal for consistency and clarity where possible. Some items could still use clarification from the sig. I'll see what I can do on Wednesday.
Also did not alphabetize sections bc the sig seemed to have something of a rationale for the order of components that they provided.
=> finish edits to Workloads API release notes

release-1.8/release-notes-draft.md
Add deprecation notice for the openstack-heat kube-up provider. This
continues efforts to deprecated and remove the providers under cluster/
See also https://github.com/kubernetes/kubernetes/issues/49213
=> Add deprecation notice for `openstack-heat`

release-1.9/release-1.9.md
This is my attempt to reorganize the release page, while also making the following changes:
* Propose a policy for disabling incomplete features after code freeze.
* Add code slush date prior to code freeze.
* Reduce number of alphas (before code freeze), increase betas (after code freeze).
* Merge all dates into one timeline with key dates emphasized.
All the major anchor dates (feature freeze, code freeze, final cut) remain unchanged.
I plan to bring up these changes at the release team and sig-release meetings today.
=> [1.9] Update schedule.

EXCEPTIONS.md
A recent exception request linked to a k/k issue covering the feature
and triggered discussion on whether that is sufficient.  This change
clarifies that a feature issue in the feature repo is expected.
Signed-off-by: Tim Pepper <tpepper@vmware.com>
=> Clarify features repo issue is required

OWNERS, OWNERS_ALIASES
This adds an additional section to `OWNERS[_ALIASES]` for the Release Team Features Lead.
Mostly for giving me magic powers to approve PRs in `k/features` for the next (1.12) release.
/assign @idvoretskyi @calebamiles
=> Add `features-maintainers` section to OWNERS files

README.md
Fixed a broken link pointing to an old version of SIG Product Management to PM SIG. Adjusted the links pointing to the blogs after the new blog cutover so there is no redirection page
Signed-off-by: Kendrick Coleman <kendrickc@vmware.com>
=> Fixed Broken Links

keps/sig-cloud-provider/0002-cloud-controller-manager.md
update cloud-provider interface link from https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/cloud.go#L31 to  https://github.com/kubernetes/cloud-provider/blob/master/cloud.go#L43
=> update outdated link in cloud-provider kep

keps/sig-instrumentation/0031-kubernetes-metrics-overhaul.md
As discussed at the informal SIG meeting today, this KEP's status should be "implementable" now that it's been merged. Follow up to https://github.com/kubernetes/community/pull/2909
Also added myself as a coauthor of this KEP for the work I did on the google doc version and removed some non-existent participating SIGs that seemed to have slipped past the first draft :)
/assign @brancz @DirectXMan12
=> keps/sig-instrumentation: Update status of 0031 to "implementable"

keps/sig-instrumentation/0031-kubernetes-metrics-overhaul.md
While looking into the kubelet API, I noticed the existance of the `/metrics/probes` endpoint, and noticed it violates the instrumentation guidelines in the same way as the cAdvisor labels do. Therefore adding those to the metrics overhaul KEP.
@DirectXMan12 @ehashman @mxinden @piosz @coffeepac @s-urbaniak @metalmatze
=> Add additional metrics guideline violations to metrics overhaul

keps/sig-instrumentation/0031-kubernetes-metrics-overhaul.md
Already a PR approved to change workqueue metrics to follow the instrumentation guidelines: https://github.com/kubernetes/kubernetes/pull/71300.
So adding those to the metrics overhaul KEP.
@brancz @DirectXMan12 @ehashman @mxinden @piosz @coffeepac @s-urbaniak @metalmatze
=> Add workqueue metrics changes to metrics overhaul

keps/sig-scheduling/34-20180703-coscheduling.md
Signed-off-by: Da K. Ma <klaus1982.cn@gmail.com>
Moved https://github.com/kubernetes/community/pull/2337 to k/enhancements.
/cc @bsalamat, @vishh, @mindprince, @jlewi
/cc @kubernetes/sig-scheduling-feature-requests
=> Coscheduilng.

keps/sig-api-machinery/35-storage-version-hash.md
The `StorageVersionHash` helps the [storage version migrator](https://github.com/kubernetes-sigs/kube-storage-version-migrator) to detect when a resource needs migration.
/assign @liggitt @yliaog @deads2k @lavalamp
=> [KEP] Adding StorageVersionHash to the discovery API

keps/sig-instrumentation/0031-kubernetes-metrics-overhaul.md
Some PRs are submitted to change apiserver/kubelet/scheduler/proxy metrics to follow the instrumentation guidelines: kubernetes/kubernetes#71300.
So adding those to the metrics overhaul KEP.
@brancz @DirectXMan12 @ehashman @mxinden @piosz @coffeepac @s-urbaniak @metalmatze
=> Add more metrics changes to metrics overhaul

keps/sig-api-machinery/34-storage-hash.md
Proposing adding a `resourceID` field to every resource's discovery doc. If two resource endpoints refer the same set of objects, their `resourceID`s are the same. This enables clients to detect if two resource endpoints are referring the same set of objects.
Moved from https://github.com/kubernetes/community/pull/2805.
=> [KEP] Adding ResourceID to the discovery API

keps/sig-windows/0000-20190103-windows-node-support.md, keps/sig-windows/OWNERS
Adds a KEP covering Windows support and a sig-windows directory for it to live in.
=> Create KEP for Windows Node Support

keps/sig-windows/0000-20181221-windows-group-managed-service-accounts-for-container-identity.md
1. Introduced a CRD for tracking GMSA credspecs (instead of configmaps). 
2. Clarified goals/non-goals around restricting users within namespaces from using GMSAs.
3. Incorporated feedback around making admission controller look-up and populate cred spec data rather than CRI.
=> Incorporate feedback from reviews of GMSA KEP

OWNERS_ALIASES
- Dumps `OWNERS_ALIASES` from k/org
- Add comments on `features-maintainers` and `pm-maintainers`
- Add @claurence (1.14 Enhancements) to `features-maintainers`
/assign @idvoretskyi @jdumars
=> Bump OWNERS_ALIASES

keps/sig-node/0014-runtime-class.md, keps/sig-node/runtime-class.md
Cleanup RuntimeClass KEP to match the alpha implementation:
- Removed the references to the `legacy` RuntimeClass. This didn't end up getting implemented, and I think it just adds unnecessary complexity.
- Moved enhancement ideas from non-goals to their own section at the end
Enumerated beta criteria, please LMK if you think anything is missing!
- Added monitoring criteria
- Removed default selection. I think this is better handled by a cluster policy mechanism (e.g. PodSecurityPolicy)
/sig node
/kind design
/milestone v1.14
=> RuntimeClass Beta criteria

README.md
This PR adds a bullet to the "an enhancement is anything that" list in the README which establishes that the act of graduating a thing from A to B requires a KEP (which should contain an articulated graduation criteria and test plan). The reason for tracking this information in KEPs is so that we can minimize our dependence on external tools by centralizing information about the Enhancement into the KEP itself.
/assign @spiffxp @justaugustus
=> Add stage graduation to the list of issues that require a KEP

keps/sig-windows/20190103-windows-node-support.md
Updating the windows KEP as we move the KEP towards implementable stage
=> Updating Windows KEP for GA

OWNERS, OWNERS_ALIASES, keps/OWNERS
Now that we've distinguished between:
- Who reviews/approves KEPs (SIG Architecture)
- Who stewards the KEP process (SIG PM)
I'd like the enhancements repo to reflect that in OWNERS.
This should push the needle forward on reducing the cognitive burden on KEP reviewers.
For now, `kep-reviewers` and `kep-approvers` are the same set of people.
Let me know if there are additional people I should include.
/assign @calebamiles @idvoretskyi @jdumars @bgrant0607 @jbeda @mattfarina @spiffxp 
/cc @lachie83 
/hold
=> Delineate owners of KEP reviews and KEP process ownership

keps/sig-network/20190118-pod-dns-config.md
Per https://github.com/kubernetes/enhancements/issues/504#issuecomment-455233815, converting [the old design proposal](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/network/pod-resolv-conf.md) to a new KEP so that we can GA this feature with k8s 1.14.
No actual changes for this conversion.
/assign @bowei @thockin 
cc @claurence
=> Convert design proposal for Pod DNS Config to KEP

keps/sig-windows/20190103-windows-node-support.md
This PR adds the API details that @bgrant0607 requested. I'm currently double checking the pod & container objects to see if any other notes are needed and will remove the hold by EOD
Update history
- 25 Jan 12:13 PST - first draft
- 25 Jan 4:44 PST - draft complete, waiting for review
/sig windows
=> Adding API section to Windows KEP

keps/sig-windows/20190103-windows-node-support.md
I don't think the limitation of not supporting privileged containers is especially important to call out specifically for DaemonSets in particular, since it applies to all containers. I also verified that Jobs and CronJobs both work as expected.
/sig windows
/assign @PatrickLang 
/assign @michmike
=> Clarify supported workload controllers

keps/sig-cluster-lifecycle/20190122-Certificates-copy-for-kubeadm-join--control-plane.md
This PR adds a new KEP proposing a solution for automating the certificate copy for the for kubeadm join --control-pane workflow (rif [KEP0015](https://github.com/kubernetes/enhancements/blob/master/keps/sig-cluster-lifecycle/0015-kubeadm-join-control-plane.md), tracking issue for v1.14 release [issue 357](https://github.com/kubernetes/enhancements/issues/357))
/assign @timothysc
/assign @luxas 
/cc @detiber 
/cc @mattmoyer 
/cc @chuckha 
/cc @liztio 
@kubernetes/sig-cluster-lifecycle-pr-reviews
=> Certificates copy for kubeadm join --control-pane

keps/sig-windows/20181221-windows-group-managed-service-accounts-for-container-identity.md
Thanks so much for the detailed review and feedback on the GMSA KEP so far. 
Updating status of GMSA KEP to implementable based on having addressed all outstanding feedback so far from latest review in https://github.com/kubernetes/enhancements/pull/694. Approvers: @PatrickLang , @yujuhong and @liggitt  PTAL so that we can get started on the Alpha implementation of GMSA.
cc @JeremyWx @wk8
=> Update status of GMSA KEP to Implementable

keps/sig-storage/20190124-csi-topology-support.md
KEP for #557 
The original design doc was written before KEP requirements were in place, so the content is kept in the original doc. Missing information required for feature freeze is added here.
/assign @msau42 @saad-ali
=> KEP for CSI topology design.

keps/sig-storage/0035-20190122-inline-csi-volumes-support.md
Currently, volumes that are backed by CSI drivers can only be used with the `PersistentVolume` and `PersistentVolumeClaim` objects. This proposal is to implement support for the ability to nest CSI volume declarations within pod specs:
```yaml
apiVersion: v1
kind: Pod
metadata:
name: testpod
spec:
containers:
...
volumes:
- name: vol
csi:
driver: mock.storage.kubernetes.io
volumeAttributes:
name: "Mock Volume 1"
volumeHandle: "1"
```
This would put CSI drivers on feature parity with existing in-tree storage plugins which already support this volume deployment mode.
Related feature entry - https://github.com/kubernetes/enhancements/issues/596
This KEP started life as  feature [#2273](https://github.com/kubernetes/community/pull/2273).  
/sig storage
=> Inline CSI volumes support KEP

keps/sig-windows/20190103-windows-node-support.md
this PR should be the final one to set the Windows Node KEP to implementable for the 1.14 release of K8s. We want to promote the functionality to stable
=> setting Windows Node KEP to implementable

keps/sig-cloud-provider/20190125-out-of-tree-vsphere.md
Update the KEP from draft doc published with #735, this KEP tracks issue #670
=> Update KEP for out-of-tree vSphere cloud provider

keps/sig-api-machinery/00xx-admission-webhooks-to-ga.md
Enhancement proposal to promote Admission Webhooks to GA.
@deads2k @liggitt @sttts @erictune @caesarxuchao @roycaihw @fedebongio @lavalamp
=> Admission Webhook to GA

keps/sig-node/20190129-hugepages.md
Migrates the previous hugepages design from community repository into KEP format.
The goal is to promote hugepages feature to GA as it has been under beta for many releases, and has usage and adoption without issue.  This document captures what was discussed in the Jan 15 SIG-Node call without objection.
See:
https://docs.google.com/document/d/1Ne57gvidMEWXR70OxxnRkYquAoMpt56o75oZtg-OeBg/edit#heading=h.w4ic0si7v0do
/cc @dchen1107
=> HugePages KEP

keps/sig-node/20190129-pid-limiting.md
The following captures what was discussed in SIG Node on Dec 18, 2018.
See:
https://github.com/kubernetes/community/blob/master/sig-node/archive/meeting-notes-2018.md#dec-18
The KEP is aligned with latest state of code, what is not yet implemented or merged is the NodeAllocatable enforcement that we would like to tackle time-permitting.
=> KEP Pid Limiting

keps/sig-cloud-provider/20190125-removing-in-tree-providers.md
Updating based on current/future work in https://github.com/kubernetes/kubernetes/issues/69585 
/assign @cheftako @dims @mcrute
=> update cloud provider dependency list in KEP 20190125-removing-in-tree-providers

keps/sig-instrumentation/0035-20190131-event-series.md
this is wraps kubernetes/community#1141 on a KEP, adds implementation history and graduation criteria.
/assign @wojtek-t @bgrant0607 
/sig scalability
=> add a kep to wrap already existing event design

keps/sig-storage/20190129-csi-volume-resizing.md
xref https://github.com/kubernetes/enhancements/issues/556
=> Start adding a KEP for csi volume resizing

keps/0000-kep-template.md
The last section of the KEP template was not in the sample TOC.
/kind cleanup
=> Add missing item to TOC.

keps/sig-api-machinery/00xx-admission-webhooks-to-ga.md
follow up to https://github.com/kubernetes/enhancements/pull/736#issuecomment-459623154
* include "convert to requested-version capability" in planned for GA list, along with motivation (https://github.com/kubernetes/enhancements/pull/736#discussion_r252396191), indicates design is still in progress and will be updated/approved in the KEP prior to implementation
* include "mutating plugin ordering" in planned for GA list, along with motivation (https://github.com/kubernetes/enhancements/pull/736#discussion_r252396191), indicates design is still in progress and will be updated/approved in the KEP prior to implementation
* resolve unset vs `*` for scope field (https://github.com/kubernetes/enhancements/pull/736#discussion_r252246860)
* mention the service port capability will be added to …
=> Webhook admission KEP updates

keps/sig-auth/0034-20190123-harden-default-discovery-bindings.md
@liggitt @tallclair PTAL
See also: https://github.com/kubernetes/kubernetes/issues/72115
=> create KEP to harden the default RBAC discovery clusterrolebindings

keps/sig-testing/20190118-breaking-apart-the-kubernetes-test-tarball.md
This might not be a big enough change to warrant a KEP, but it still seemed like a good way to outline the rationale and some trade-offs.
This kinda seems to be split between sig-testing and sig-release; it's unclear whether sig-architecture should consider this as well.
/assign @spiffxp @BenTheElder 
as he was very enthusiastic on slack
cc @dims as well
x-ref tracking issue #714
=> Breaking apart the test tarball KEP

keps/sig-cluster-lifecycle/20190122-Certificates-copy-for-kubeadm-join--control-plane.md
@neolit123 @claurence @timothysc 
When I worked on https://github.com/kubernetes/enhancements/pull/713, in the rush for getting this in before the enhancement freeze, I forgot to set the status implemented. This PR fixes this
Hopefully, this will help in getting back https://github.com/kubernetes/enhancements/issues/357 enhancement into tracked status.
Sorry again for this oversight
I hope in future some better tooling around KEP will help people in combining the requirements of a process that is getting more and more formal with a format (markdown) that is just a little bit more that free text
@kubernetes/kep-maintainers
=> set implemented status to certificates copy for kubeadm join KEP

keps/sig-windows/20190103-windows-node-support.md
While reviewing part of the API reference, @liggitt called out a few fields that weren't  ( see https://github.com/kubernetes/enhancements/pull/799#discussion_r254029446 ).
This adds them to the API reference for completeness sake.
=> Adding clarifications on PodSecurityContext

keps/0000-kep-template.md
Brings @pwittrock's updates in #690 over...
Update KEP template
- Add release checklist
- Expand upon graduation criteria
- Add test plan section
- Add upgrade / downgrade section
- Add version skew section
Additionally:
- Clarify some requirements in Release Team checklist
- Do away with KEP number in template
Phil and I discussed earlier in the week that I'd pick this up, so he doesn't have to be responsible for iterating on any changes suggested.
/assign @calebamiles @spiffxp @pwittrock @bgrant0607 
/sig pm architecture
/hold
Fixes: kubernetes/community#2245
=> Revise KEP template

ISSUE_TEMPLATE.md
Drop the link to test plan, that should now be part of KEP
=> s/Design Proposal/KEP

keps/sig-node/kubelet-resource-metrics-endpoint.md
As described in https://github.com/kubernetes/kubernetes/issues/68522, a long-term goal is to reduce the set of metrics provided by the kubelet to make monitoring.
**Resource Metrics** == Core Metrics.  The term "Core" is overloaded, so I am trying to switch to using this terminology.  This is about metrics for first-class resources, such as cpu, and memory.
Feature Issue: https://github.com/kubernetes/enhancements/issues/727.  This is ideally targeted for 1.14, but obviously pending approval.
cc @kubernetes/sig-node-proposals 
@kubernetes/sig-instrumentation-api-reviews
=> [KEP] Kubelet Resource Metrics Endpoint

keps/sig-api-machinery/storage-migration-auto-trigger.md
We will add a new API and a controller to the [storage migrator repo](https://github.com/kubernetes-sigs/kube-storage-version-migrator), to automatically start storage version migration when the storage version changes.
See this [previous KEP](https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/35-storage-version-hash.md) for how storage version is exposed in the discovery doc.
/assign @yliaog @lavalamp @deads2k 
=> Adding the storage migration triggering controller

keps/sig-release/20190121-artifact-management.md
=> Add details about the design of the redirector.

keps/sig-api-machinery/00xx-publish-crd-openapi.md
We didn't change the status from `provisional` to `implementable` before merging the KEP. There is no open question left. This PR changes the status.
/assign @deads2k @lavalamp 
for approval
=> Mark Publish CRD OpenAPI KEP as implementable

keps/0001-kubernetes-enhancement-proposal-process.md, keps/README.md, keps/YYYYMMDD-kep-template.md, keps/sig-release/20190121-artifact-management.md
Updates KEP template and meta KEP to follow the `YYYYMMDD-kep-name.md` file name format.
Wasn't sure if the filenames were intentionally left like this or just forgotten, figured I'd open a PR anyways :). 
/assign @justaugustus @calebamiles
=> Rename KEP template file name to follow KEP template

keps/OWNERS
After scrolling some of the open PRs, seems redundant to tag KEP changes as `kind/kep`, `sig/architecture`, and `sig/pm`.
`kind/kep` should suffice. This removes the SIG labels.
=> Remove sig/{architecture,pm} labels from KEP directory

keps/sig-windows/20190103-windows-node-support.md
Over the last week we got a few more test runs added (GCE & vSphere), and updated the naming. This PR just fixes the links.
@benmoss or @astrieanna - does the vSphere test pass description look ok to you?
@yujuhong - does the GCE link look ok to you?
=> Fixing testgrid links in Windows KEP

keps/sig-cli/0024-kubectl-plugins.md
/assign @juanvallejo @pwittrock @seans3
=> Change kubectl plugins KEP to implemented

keps/sig-storage/20190122-csi-inline-volumes.md
This is to add changes suggested by @liggitt after KEP merged.
These are mostly cosmetic with design updates that still keep the KEP status implementable.
Original KEP - https://github.com/kubernetes/enhancements/pull/716
=> CSI inline volume support KEP with suggested updates

keps/sig-windows/20190103-windows-node-support.md
Some common network utilities (e.g. ping, traceroute) used for troubleshooting and diagnosis are based on ICMP messaging. This commit is adding a clarification on what network flows can be expected to work are on Windows containers using the ICMP protocol.
=> Added Windows KEP clarification on ICMP protocol support.

keps/sig-cloud-provider/20190125-removing-in-tree-providers.md
Doing some KEP clean up for cloud provider extraction efforts.
/assign @cheftako @dims @jagosan @hogepodge @d-nishi @mcrute
=> cleaning up KEP-removing-in-tree-providers

keps/sig-network/20190118-pod-dns-config.md
Per https://github.com/kubernetes/enhancements/issues/504#issuecomment-466557563, retrospectively adding test plan to the pod DNS config KEP.
/assign @thockin @bowei 
cc @claurence
=> Add test plan to pod DNS config KEP

keps/sig-node/0035-20190130-topology-manager.md
KEP merged to community repo: https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node/topology-manager.md
Moving to enhancements repo as per 1.14 release requirements for each feature to have a KEP in this repo.
Topology Manager component in Kubelet which collects hints from other Kubelet components in order to create a best fit Socket alignment.
=> Topology Manager KEP (Moving to new repo)

keps/sig-api-machinery/0006-apply.md
Retroactively summarize the testing plan described in https://github.com/kubernetes/enhancements/issues/555 here in the KEP.
Everything described here is already implemented.
=> Add testing plan to Apply KEP

keps/sig-scheduling/20190131-pod-priority-preemption.md
=> Add testing plan to priority and preemption KEP

keps/sig-storage/20190204-scale-testing.md
Develop a plan on how to test scalability of K8s storage
@kubernetes/sig-storage-feature-requests 
@kubernetes/sig-scalability-feature-requests
=> Add storage scale testing kep

keps/sig-cli/kubectl-commands-in-headers.md
KEP PR Approvers:
- @deads2k 
- @soltysh
=> Proposal for adding headers with the command name to kubectl requests

keps/README.md
Update verbiage stating KEPs have been made mandatory since release 1.14
Signed-off-by: Lachlan Evenson <lachlan.evenson@microsoft.com>
=> Update KEP usage statement

keps/sig-testing/20190118-breaking-apart-the-kubernetes-test-tarball.md
https://github.com/kubernetes/kubernetes/pull/74065 merged a few weeks ago, and everything is looking good. Update the KEP accordingly.
/assign @spiffxp @tpepper 
x-ref kubernetes/enhancements#714
=> update split test tarballs KEP: status -> implemented

keps/sig-auth/0000-20170814-bounding-self-labeling-kubelets.md
There was some in-tree use of node-labels that needed to be [cleaned up in 1.14](https://github.com/kubernetes/kubernetes/pull/74424), which pushed the implementation timeline out
=> Update node self-labeling implementation timeline

keps/sig-architecture/2019-03-19-go-modules.md
Initial go modules draft KEP.
/sig architecture testing release api-machinery
/cc @lavalamp @sttts
=> initial go modules draft

keps/sig-release/20190219-publishing-packages.md
The purpose here is to get alignment on the Goals/Non-Goals and the rough proposal to get this KEP merged as `provisional` early.
Further (implementation) details and eventually the transition to `implementable` can be done with further PRs.
Supersedes: https://hackmd.io/PbH8KD09SFC0yn7ZhqVTRA?both
/cc @timothysc @sumitranr @Klaven @ixdy @ncdc @spiffxp @tpepper 
/sig release
/area release-eng
/kind kep
=> Add KEP for publishing packages in `provisional` state

keps/sig-apps/sidecarcontainers.md
This adds some clarification around a few points and adds some initial implementation details. 
I didn't want to go too specific with code example as I'm not sure how valuable that would be at this stage and instead just call out the places where I think we should implement the logic so we can discuss whether this seems like a sensible approach. Once some POCing has been done we can link to the POC branch in the implementation details.
/assign @enisoc @kow3ns
=> add implementation details to sidecar kep

OWNERS_ALIASES, keps/sig-architecture/OWNERS
This adds an OWNERS file to the sig arch kep directory and updates the list of sig arch chairs to match what's in community.
/cc @bgrant0607 @jdumars 
=> Updating OWNERS for sig-architecture

keps/sig-node/runtime-class.md
Follow up from the recommendations in this document:
https://docs.google.com/document/d/1hH99thfjpVDG77GgBUT0yXtHb1u8E0zcT_kviwjG1k8/edit
TL;DR is that we won't make any code changes for RuntimeClass upgrades in the beta release, although I am refining the recommended approach to upgrades: only create a new RuntimeClass when there are user-facing changes and applications need to be modified.
/sig node
/milestone v1.14
/assign @dchen1107
=> Revisit RuntimeClass upgrade story

keps/sig-network/20190324-remove-kube-proxy-autocleanup.md
Iterating on the kube-proxy clean up KEP based on https://github.com/kubernetes/kubernetes/issues/75360, https://github.com/kubernetes/kubernetes/pull/75377 & https://github.com/kubernetes/enhancements/pull/915
=> sig-network: updates to kube-proxy clean up KEP

keps/sig-node/20190212-ephemeral-containers.md
This is a port of the existing Ephemeral Containers proposal to a KEP candidate. I've refocused the document on the API and kubelet changes, and put changes to kubectl out of scope for this document. I've also updated the API for changes we've made during API review.
This KEP draft is still marked provisional for a quick merge and to get the process started.
Original document: https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node/troubleshoot-running-pods.md
=> Port Troubleshooting Running Pods proposal to KEP

keps/sig-api-machinery/20190129-legacyflag.md
Proposes a wrapper library around pflag, that can improve the experience
of defining a command-line interface while implementing componentconfig.
Example implementation of a subset of kflag here: https://github.com/kubernetes/kubernetes/pull/73494
=> legacyflag

keps/sig-node/runtime-class-scheduling.md
Updated the RuntimeClass scheduling KEP to use native scheduler support rather than a mixin approach.
This approach uses a cleaner API (doesn't need to mixin a bunch of rules into the pod's node affinity), it let's us use the more expressive `NodeSelector` API, and provides a nice user experience in the error case.
I am opening this PR to continue the discussion @bsalamat started [here](https://github.com/kubernetes/enhancements/pull/896#discussion_r267141010)
/sig node scheduling
/assign @bsalamat @derekwaynecarr @dchen1107 
/cc @yastij 
/milestone v1.15
=> [RuntimeClass scheduling] native scheduler support, ready to implement

keps/sig-node/20190226-pod-overhead.md
Initial push for the pod overhead KEP.
=> keps: sig-node: initial  pod overhead proposal

keps/sig-storage/20181111-extend-datasource-field.md
Propose extending DataSource field in PVCs to allow existing in
namespace PVCs (Clones) and external data population CRDs (Populators).
=> Propose KEP to extend allowed DataSource entries to include PVC

keps/sig-apps/sidecarcontainers.md
I've updated this KEP https://github.com/kubernetes/enhancements/issues/753 to match the new template format such as adding the release signoff checklist.
Added my initial thoughts on Graduation criteria, Upgrade/Downgrade strategy and Version Skew. I'll add the test plan in a separate PR as that could do with its own discussion.
/sig apps
/sig node
/assign @enisoc @kow3ns
=> add release checklist, grad criteria, upgrade strategy to sidecar kep

keps/sig-node/20190221-initializationFailureThreshold-health-probes.md
/assign @kubernetes/sig-node-proposals
=> KEP for adding initializationFailureThreshold to health probes

keps/sig-node/20190212-ephemeral-containers.md
This marks the Ephemeral Containers KEP as implementable, signaling that the approvers have approved this KEP for implementation.
=> Mark Ephemeral Containers KEP as implementable

keps/sig-cloud-provider/20180530-cloud-controller-manager.md
Update the external CCM KEP to clarify in the repository requirements
section that co-locating additional provider feature implementations is optional. This applies to features such as CSI and CNI.
=> Clarify that colocating CSI code with CCM is optional

keps/sig-scheduling/20190221-even-pods-spreading.md
As a follow-up of discussion https://github.com/kubernetes/kubernetes/issues/72479#issuecomment-455464871
Tracking issue: #895
/kind design
=> KEP of even pods spreading

keps/sig-instrumentation/draft-20190404-kubernetes-control-plane-metrics-stability.md
This KEP proposes a strategy for treating control-plane metrics more properly as an API. This is in line with the [groups discussion](https://groups.google.com/forum/#!topic/kubernetes-sig-instrumentation/Qh3FiPERUs4) and the last discussion from the sig-instrumentation meeting.
=> Proposal for control-plane metrics stability

keps/sig-windows/20190418-windows-security-context.md
This is a KEP to cover the addition of the API enhancements related to GMSA and RunAsUsername to the pod security context and the container security context.
While the GMSA KEP covers the details around the GMSA fields, we did note that the specific API fields are speculative and may change. This KEP is where the structure and field names for the GMSA field as well as the RunAsUserName field will be finalized.
=> KEP for Windows security context

keps/sig-node/20190226-pod-overhead.md
Clarify what Overhead is in the pod spec, and behavior when
this is manually defined without a runtimeClass.
Clarify other opens in the proposal based on feedback.
=> kep: pod-overhead: clarify handling of Overhead

keps/sig-cluster-lifecycle/kubeadm/0023-kubeadm-config.md
Rename and update a bit the KEP for kubeadm config. Most importantly:
- The KEP is not bound to v1beta1.
- The notion of v1beta2 was added.
- Added @fabriziopandini and @neolit123 to the approvers.
- Added a short implementation history.
- Added some of the proposed changes for v1beta2.
/assign @fabriziopandini @timothysc @neolit123 @luxas 
/cc @kad @detiber @yagonobre @ereslibre
=> kubeadm: Update the config KEP

keps/sig-api-machinery/00xx-admission-webhooks-to-ga.md
Each matching object is sent to the webhook in individual request instead of being sent in a list.
/assign @liggitt @mbohlool
=> Updating the webhook GA KEP about delete collection

keps/sig-cluster-lifecycle/kubeadm/0015-kubeadm-join-control-plane.md, keps/sig-cluster-lifecycle/kubeadm/20190122-Certificates-copy-for-kubeadm-join--control-plane.md
This PR update kubeadm HA KEPs (join control plane and automatic copy certs) with v1.14 achievements and activities planned for v1.15
/assign  @timothysc @neolit123 @rosti 
@kubernetes/sig-cluster-lifecycle-pr-reviews
=> kubeadm HA KEPs updated for v1.15

keps/sig-api-machinery/00xx-admission-webhooks-to-ga.md
follow up to https://github.com/kubernetes/enhancements/pull/736#issuecomment-459623154 with proposed design for "conversion to requested-version" capability (https://github.com/kubernetes/enhancements/pull/736#discussion_r252396191)
/assign @lavalamp @deads2k @mbohlool
=> update webhook admission proposal with "convert to webhook-requested version"

keps/sig-api-machinery/20180415-crds-to-ga.md
We'd like to graduate CRDs sub-features to beta in 1.15 and then graduate CRDs to GA in a following release, ideally 1.16.
The purpose of this KEP is to establish consensus for the remaining essential improvements needed to move CRDs to GA. In particular, we'd like to agree on the features and tests required.
A couple sections, particularly the test and scale goals sections, are not complete. Feedback on what we should include in those sections would be very helpful.
=> sig-api-machinery: add "Graduate CustomResourceDefinitions to GA"

keps/sig-node/20190226-pod-overhead.md
Signed-off-by: Eric Ernst <eric.ernst@intel.com>
=> kep: pod-overhead: address formatting issue

keps/sig-scheduling/20190221-even-pods-spreading.md
update of KEP even pods spreading
- update TopologySpreadConstraints to use a slice
- change status to `implementable`
- update "Test Plan" and "Graduation Criteria" sections
/assign @bsalamat 
/kind design
=> update of KEP even pods spreading

keps/sig-api-machinery/20190425-crd-conversion-webhook.md
We intend to promote CRD conversion webhooks to v1beta1 in Kubernetes 1.15. 
Since we typically document criteria in the KEP, I'm first porting the existing [customresource-conversion-webhook.md design doc](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/api-machinery/customresource-conversion-webhook.md) from kubernetes/community to a KEP.
See graduation criteria section of the v1beta1 criteria, which I've added in a separate commit in this PR.
=> sig-api-machinery: port CRD conversion webhook design doc to KEP, add v1beta1 criteria

keps/sig-network/20190423-service-lb-finalizer.md
This KEP proposes the plan for adding finalizer protection for service load balancer. The work has been started a long while back but unfortunately hasn't been delivered yet. We are looking forward to making it happen in 1.15.
Note that many content is derived from the original implementation (https://github.com/kubernetes/kubernetes/pull/54569) of this feature.
Enhancement issue: https://github.com/kubernetes/enhancements/issues/980
=> KEP: Finalizer Protection for Service LoadBalancers

keps/sig-storage/20190408-volume-scheduling-limits.md
This KEP changes existing scheduler predicates for volume limits from using `Node.status.allocatable` to `CSINode.spec.drivers["xyz"]` for CSI drivers and in-tree volumes (in some cases).
Feature: https://github.com/kubernetes/enhancements/issues/554
=> Add KEP for volume scheduling limits

keps/sig-scheduling/20190312-pod-affinity-and-anti-affinity-support-gt-and-lt-operators.md
As a follow-up of discussion https://github.com/kubernetes/kubernetes/pull/72556#issuecomment-453274688
/kind design
cc/ @bsalamat @k82cn @ravisantoshgudimetla @misterikkit @resouer @Huang-Wei @liggitt
=> KEP of pod affinity/anti-affinity supports Gt and Lt operators

keps/sig-storage/20190129-csi-volume-resizing.md
=> Follow up CSI resizing updates for 1.15 release

keps/sig-api-machinery/20190325-unions.md
Not meant to be a feature, mostly to document what we're doing.
=> Initial KEP for API union/oneOf

keps/sig-api-machinery/20190322-server-side-get-to-ga.md
* beta version deprecation is "9 months or 3 releases (whichever is longer)"
* delay controller update to 1.16
/cc @smarterclayton
=> Update server-side get deprecation/implementation timeline

keps/sig-node/20190212-ephemeral-containers.md
I reviewed the KEP more closely, and wanted to clarify what would / would not work on Windows. Since most of the use cases depend on Linux-only features, I'm proposing listing Windows support as a non-goal.
I also added an alternative approach under `[Alternatives]` that would be compatible. I think it's worth including that for completeness in case someone wants to develop using an approach that would work on both OSs.
/assign @verb 
cc @yujuhong
=> Ephemeral container KEP - Updating with info on Windows applicability

keps/sig-storage/20190120-ExecutionHook-apichange.md, keps/sig-storage/20190120-execution-hook-design.md
This PR proposes ExecutionHook API design.
=> ExecutionHook API Design

keps/sig-api-machinery/20190228-priority-and-fairness.md
No sharing between priority levels.
No distinction between mutating and read-only requests.
I think this is what we agreed in the meeting today.
=> Added simplified proposal for priority and fairness in apiservers

keps/sig-cli/kubectl-staging.md
* Fleshes out proposal for moving `pkg/kubectl` into staging
* Describes process of creating staging directory
* Explains the disposition of the current `kubernetes/kubectl` repository content
* Adds a brief timeline
/sig cli
/area kubectl
=> Significantly fleshed out "move pkg/kubectl into staging"  proposal from feedback

keps/sig-network/20190125-ingress-api-group.md
Fleshes out some details regarding the issues we wish to tackle in the 1.15+ releases.
Implementation and details are WIP.
This is an initial pass.
@thockin @liggitt @aledbf
=> Add Ingress GA details

keps/sig-node/compute-device-assignment.md
This changes the status to implementable (since the KEP came from before that requirement), and adds graduation criterion and implementation history.
/assign @derekwaynecarr @dchen1107 
cc @RenaudWasTaken @jiayingz
=> Move kubelet pod resources endpoint to implementable

keps/sig-instrumentation/20190425-metrics-watch-api.md
This KEP proposes adding watch capability to metric APIs. Details are left out for now - this is an initial draft to start discussions.
/sig autoscaling
@kubernetes/sig-instrumentation-proposals
@brancz @markusthoemmes @josephburnett @mwielgus
=> Draft proposal for watch support on metric APIs

keps/sig-cluster-lifecycle/kubeadm/20190424-kubeadm-for-windows.md
=> Kubeadm for Windows KEP

keps/sig-network/20180612-ipv4-ipv6-dual-stack.md
Fixes #563 
This PR adds to the great work in #648. Specifically we have expanded the scope of authors in include community members that have expressed interest in helping with the KEP and implementation.
At PR submission the following changes have been made to the KEP in #648:
* Add new authors
* Update last-updated
* Add Implementation Plan section
/cc  @leblancd @rpothier @khenidak @feiskyer @thockin
=> Add revised IPv4/IPv6 dual stack KEP

keps/sig-api-machinery/20190425-structural-openapi.md
This is needed so we can catch/forbid explicit false values from the user to avoid confusion
=> apiextensions: clarify XPreserveUnknownFields type in structural schema

keps/sig-instrumentation/42-kubernetes-control-plane-metrics-stability.md
This PR removes the draft versioning of the filename and assigns a KEP number to the control-plane metrics stability KEP.
=> remove draft versioning from control-plane stability kep

keps/sig-node/20190226-pod-overhead.md
As discussed in sig-node & api review, don't distinguish between requests & limits for pod overhead.
/assign @egernst @thockin 
/cc @dchen1107 @derekwaynecarr 
/sig node
/milestone v1.15
=> Collapse overhead requests & limits to a single value

keps/sig-api-machinery/00xx-admission-webhooks-to-ga.md
Adds details of the opt-in re-invocation mechanism
/cc @deads2k @lavalamp
=> Add mutating webhook re-invocation details

keps/sig-node/runtime-class-scheduling.md
Follow ups from the RuntimeClass scheduling API / architecture review. Concerns raised in the review:
- The term `Topology` is too ambiguous and overloaded
- @thockin was concerned about adding new special cased scheduler predicates.
This update addresses those concerns by:
- Renaming `Topology` to `Scheduling`
- Replacing the `corev1.NodeSelector` type with `map[string]string`. This makes the merging logic much simpler, so we can mix in the node selector in admission and leave the scheduler untouched. If we find a need for the more complicated node selector logic in the future, we can revisit this decision with an additional field.
/assign @thockin @dchen1107 @bsalamat @yastij 
/sig node
/milestone v1.15
=> Runtimeclass scheduling updates

keps/sig-network/20190125-ingress-api-group.md
Expand the example to be clear that multiple labels in the hostname will not match a wildcard.
=> Clarify host wildcard matching

keps/sig-api-machinery/00xx-admission-webhooks-to-ga.md
Updated KEP with outcome of implementation-time changes
/cc @sttts @caesarxuchao @deads2k
=> update objectSelector design

keps/sig-instrumentation/20181106-kubernetes-metrics-overhaul.md, keps/sig-instrumentation/20190131-event-series.md, keps/sig-instrumentation/20190404-kubernetes-control-plane-metrics-stability.md
Cleaning up instrumentation KEP filenames. 
/cc @spiffxp 
/assign @brancz 
=> remove prefixed KEP version numbers from instrumentation KEPs (now obsolete)

keps/sig-api-machinery/20190607-owner-ref.md
OwnerReferences are used to track garbage collection references.  Today they use `kind`.  This is a serialization format not a URL to access on the kube-apiserver.  To find a URL, a series of upwards of 20 discovery calls are made to find every resource in the cluster to find a list of potential resources (URLs more or less).  This approximates user intent and mostly works, but it is inefficient and unnecessarily vulnerable to network outages.
This KEP proposes adding an optional `resource` field to OwnerReferences.  If provided, this will be the authoritative value and no lookup or approximation of user intent will be required.  If not provided, the `kind` will be used as it is today. If both are provided, old clusters continue to work and new clusters will be more efficient and …
=> propose resource field on OwnerReference

keps/sig-apps/sidecarcontainers.md
This is my first pass at a test plan for the Sidecar KEP https://github.com/kubernetes/enhancements/issues/753,  I wasn't entirely sure how much detail was expected here, any input from sig-testing would be much appreciated.
/sig apps
/sig node
/sig testing
/assign @kow3ns @enisoc
=> add test plan to sidecar kep

keps/sig-api-machinery/20190612-crd-group-protection.md
API groups are organized by namespace, similar to java packages.  `authorization.k8s.io` is one example.  When users create
CRDs, they get to specify an API group and their type will be injected into that group by the kube-apiserver.
The *.k8s.io or *.kubernetes.io groups are owned by the Kubernetes community and protected by API review (see [What APIs need to be reviewed](https://github.com/kubernetes/community/blob/master/sig-architecture/api-review-process.md#what-apis-need-to-be-reviewed),
to ensure consistency and quality.  To avoid confusion in our API groups and prevent accidentally claiming a
space inside of the kubernetes API groups, the kube-apiserver needs to be updated to protect these reserved API groups.
This KEP proposes adding an `api-approved.kubernetes.io` annotation to …
=> protect kubernetes community owned API groups in CRDs

keps/sig-apps/sidecarcontainers.md
This is my suggestion for how we could implement the API for defining the sidecars https://github.com/kubernetes/enhancements/issues/753. 
Having a bool was not very popular, having an enum instead seemed to have more support so I'm suggesting we have `lifecycle.type: Sidecar`
I'm not sure what the default value should be for `type`, I suggested `Standard` here but some other suggestions could be `Default`, `Main`, `Primary`.
/sig apps
/sig node
/assign @kow3ns @enisoc
=> Sidecar KEP API implementation

keps/sig-instrumentation/20190605-metrics-stability-migration.md
This KEP proposes a strategy for migrating control-plane metrics to use the metrics framework which was the output of the control-plane metrics stability KEP.
=> Proposal for metrics stability migration

keps/sig-apps/sidecarcontainers.md
This PR moves the sidecars KEP https://github.com/kubernetes/enhancements/issues/753 to be implementable. Allowing us to progress with developing the feature for 1.16.
If anyone thinks something is missing from the proposal now's the time to discuss it.
/sig apps
/sig node
/assign @kow3ns @enisoc
=> Change sidecars kep to implementable

Gopkg.lock, Gopkg.toml, hack/verify-all-metadata.sh, hack/verify.sh, vendor/github.com/chuckha/kepview/LICENSE, vendor/github.com/chuckha/kepview/cmd/kepval/main.go, vendor/github.com/chuckha/kepview/keps/proposals.go, vendor/github.com/chuckha/kepview/keps/validations/yaml.go, vendor/github.com/chuckha/kepview/main.go, vendor/github.com/pkg/errors/LICENSE, vendor/github.com/pkg/errors/errors.go, vendor/github.com/pkg/errors/stack.go, vendor/gopkg.in/yaml.v2/LICENSE, vendor/gopkg.in/yaml.v2/LICENSE.libyaml, vendor/gopkg.in/yaml.v2/NOTICE, vendor/gopkg.in/yaml.v2/apic.go, vendor/gopkg.in/yaml.v2/decode.go, vendor/gopkg.in/yaml.v2/emitterc.go, vendor/gopkg.in/yaml.v2/encode.go, vendor/gopkg.in/yaml.v2/parserc.go, vendor/gopkg.in/yaml.v2/readerc.go, vendor/gopkg.in/yaml.v2/resolve.go, vendor/gopkg.in/yaml.v2/scannerc.go, vendor/gopkg.in/yaml.v2/sorter.go, vendor/gopkg.in/yaml.v2/writerc.go, vendor/gopkg.in/yaml.v2/yaml.go, vendor/gopkg.in/yaml.v2/yamlh.go, vendor/gopkg.in/yaml.v2/yamlprivateh.go
Validate KEP metadata
`verify-all-metadata` is omitted from `verify` because `verify-all-metadata` is failing as there are many errors in metadata validation across old KEPs.
A couple of next few steps:
* fix the validations on every existing KEP
* add this as a non-blocking prow pull job to raise attention that this is being checked
* we should add another verify step that only verifies the modified files in a PR, `kepval` is set up nicely to do that, but requires some understanding of k8s-infra
cc @justaugustus
=> Adds metadata verification

keps/sig-node/0035-20190130-topology-manager.md
The decision was made to update the TopologyManager interface and
respective SocketMask interfaces to be more user friendly. These changes
have already been merged into Kubernetes. This commit brings the KEP in
line with these changes.
=> Update TopologyManager KEP to reflect already-merged changes.

keps/sig-storage/20190122-csi-inline-volumes.md
Defines how to support persistent and inline volumes in the same driver installation and cleans up some language.
Related-to: https://github.com/kubernetes/kubernetes/issues/79624
=> inline and persistent volumes

keps/sig-cloud-provider/20190215-promoting-cloud-provider-labels.md
Enhancement issue: https://github.com/kubernetes/enhancements/issues/837 
This is a KEP proposing we promote the following beta labels to GA:
* `beta.kubernetes.io/instance-type` -> `node.kubernetes.io/instance-type`
* `failure-domain.beta.kubernetes.io/zone` -> `topology.kubernetes.io/zone`
* `failure-domain.beta.kubernetes.io/region` -> `topology.kubernetes.io/region`
From what I can tell, this has implications for nodes and volumes. 
/assign @dims @liggitt @msau42 @saad-ali @thockin
=> Promoting cloud provider labels to GA

keps/sig-scheduling/20180409-scheduling-framework.md
Since PR(https://github.com/kubernetes/kubernetes/pull/78162) has been merged, we need update the section `Custom Scheduler Plugins(out of tree)` for the new scheduler framework.
=> Update Custom Scheduler Plugins section for new scheduler framework

keps/sig-api-machinery/20190711-remove-selflink.md
As this this required to happen before feature freeze
=> Remove SelfLink KEP implementable

keps/sig-network/20190603-EndpointSlice-API.md
The proposal doc has been circulating for quite a while. https://docs.google.com/document/d/1sLJfolOeEVzK5oOviRmtHOHmke8qtteljQPaDUEukxY/edit
Formally converting the proposal into a KEP
=> KEP: EndpointSlice API 

hack/update-toc.sh, hack/verify-kep-metadata.sh, hack/verify-spelling.sh, hack/verify-toc.sh
- fix all scripts to get the repo root correctly
- create a tempdir in all scripts and use this to perform go get in module mode and store output binaries
- fix some minor quoting issues
avoids creating go.mod / go.sum in the repo when running these scripts locally, fixes non-functional `hack/update-toc.sh` which was using (non-existent) vendor instead of go modules
=> fix scripts and go modules

keps/sig-windows/20190714-windows-csi-support.md
Proposal for enhancements to support CSI plugins on Windows nodes.
=> KEP: Support for CSI Plugins on Windows Nodes

hack/update-toc.sh, hack/verify-toc.sh
follow up to https://github.com/kubernetes/enhancements/pull/1181
_actually_ fixes hack/update.toc.sh
in the future we should consider using a go.mod instead like https://github.com/kubernetes/enhancements/pull/1175 (though note comments there regarding tools.go..)
=> set update-toc.sh version and add a note to keep in sync

keps/sig-api-machinery/20180415-crds-to-ga.md
This proposes that our scale targets for CRD to GA be based on [API call latency SLIs/SLOs](https://github.com/kubernetes/community/blob/master/sig-scalability/slos/api_call_latency.md#api-call-latency-slisslos-details) and [kubernetes thresholds](https://github.com/kubernetes/community/blob/master/sig-scalability/configs-and-limits/thresholds.md#kubernetes-thresholds).
For details on scalability data gathered, see: https://docs.google.com/document/d/1tEstPQvzGvaRnN-WwGUWx1H9xHPRCy_fFcGlgTkB3f8/edit#
=> sig-api-machinery: Add scale targets to CRDs to GA KEP

cmd/kepval/main.go, cmd/kepval/main_test.go, docs/kepval.md, go.mod, go.sum, hack/verify-kep-metadata.sh, pkg/kepval/keps/proposals.go, pkg/kepval/keps/proposals_test.go, pkg/kepval/keps/validations/yaml.go, pkg/kepval/keps/validations/yaml_test.go
This moves kepval and the go definition of a KEP into the enhancements repo.
The hack script is fixed to use go test to test validations instead of installing an external script simplifying the process greatly.
This will fail golint as I have not documented the series of custom errors created in validation to good spec. However, as none of the verification tools have been set up so there will not be any failing test.
I can make an issue to add those scripts as a followup item *or* I can do it as part of this PR, but it might add an additional 500-600 lines of bash. The decision is up to the owners preference. I've watched @neolit123 do it 3 times in the past month or so and am pretty sure I know how it goes!
cc @justaugustus 
please tag anyone else you like
=> Merge kepval into the enhancements repo

keps/sig-api-machinery/20180415-crds-to-ga.md
Now that all the updates for the `CRDs to GA` KEP have merged, set its status to implementable.
cc @sttts @liggitt @roycaihw @lavalamp @deads2k @caesarxuchao
=> Set CRDs to GA KEP status to implementable

keps/sig-storage/20190122-csi-inline-volumes.md
This adds the implementation history and checks which of the proposed
tests are implemented.
/cc @vladimirvivien @kfox111 @msau42
=> csi-inline-volumes.md: prepare for beta

keps/sig-storage/20181111-extend-datasource-field.md
Update KEP to note graduation from Alpha to Beta for sig-storage cloning feature in 1.16.  Also add a note regarding the storageClass restrictions on cloning.
issue: #989
=> Update KEP to reflect volume cloning  beta in 1.16

keps/sig-apps/20190318-PodDisruptionBudget-graduation-to-stable.md
/sig apps
/assign @kow3ns @liggitt
=> Add a KEP for graduating PodDisruptionBudget to stable

keps/sig-storage/20190709-csi-snapshot.md
This KEP is for the volume snapshot feature.
=> Bring Volume Snapshot to Beta

keps/sig-cloud-provider/20190729-building-without-in-tree-providers.md
KEP for https://github.com/kubernetes/enhancements/issues/1179
Previously discussed in SIG Cloud Provider, and with some SIG Release members. This is Nominally SIG Cloud Provider but the alternate build mode should also interest and include SIG Release.
=> add building without in tree providers

keps/sig-api-machinery/20190228-priority-and-fairness.md
Fix the exhibited `shuffleDealAndPick` function so that it follows the golang convention that a comment comes _before_ the thing being commented.  Originally this function used the opposite order, but modified by `gofmt`, which does not respect the opposite order and thus re-ordered the text a little making it confusing.
=> Clarify 20190228-priority-and-fairness.md

keps/sig-network/20190714-IPv6-beta-proposal.md
Graduate IPv6 support to beta, it was in alpha status since 1.9 and a CI system was added to avoid regressions and guarantee the quality
Ref: https://github.com/kubernetes/enhancements/issues/1138
=> Graduate IPv6 support to beta

keps/sig-scheduling/20180409-scheduling-framework.md
/kind feature
As the discussion on https://github.com/kubernetes/kubernetes/pull/80383, we decided to merge the normalize score extension point into the score.
/assign @bsalamat @ahg-g
=> feat: remove normalize score section in the scheduling framwork

keps/sig-api-machinery/20190228-priority-and-fairness.md
.. to avoid confusion with the other usage of the word "priority".
This matches a change made in the implementation months ago.
This PR deliberately avoids making the change in the exhibited
configuration objects because there are other PRs against those in
progress.
=> Changed matching "priority" to "precedence"

keps/sig-api-machinery/20190228-priority-and-fairness.md
The purpose of this PR is to add to the KEP some supporting details of observed requests, so that we can understand the traffic we are trying to classify.
=> Extend the API priority and fairness KEP with observed request details

keps/sig-instrumentation/20190605-metrics-stability-migration.md
Mark kubelet metrics migration to standard Prometheus collector as done
as a result of this: https://github.com/kubernetes/kubernetes/pull/81573
=> Mark kubelet metrics migration to standard prometheus collector as done

keps/sig-auth/20190806-serviceaccount-tokens.md
In preperation for GA.
Content is unchanged from design proposal. It's just been reformatted
into a KEP, with a graduation criteria section added. It could use a
Goals and Non-Goals section but I don't think it's worth hashing out in
the initial migration to a KEP.
@kubernetes/sig-auth-proposals
=> add retroactive Bound Service Account token

keps/sig-api-machinery/20190322-server-side-get-to-ga.md
Clarifies the state in 1.16, where we add the metadata client, switch GC, namespace, and quota count generic controllers to use the partial object metadata informer.
=> Update server-side get to GA proposal with 1.16 commitments and final state

keps/sig-api-machinery/20190625-api-compression-to-ga.md
This KEP proposes how we can move the API server alpha api compression feature to GA by correcting the previous implementation and preventing performance regression.
=> Bring gzip compression for API server to GA

keps/sig-api-machinery/20190802-dynamic-coordinated-storage-version.md
Supersedes #1201, #1176
The main differences from #1176 is the API schema, and that in this KEP we don't bother to fix the storageVersionHash in the discovery document.
The main difference from #1201 is that we don't ask apiservers to vote on the storage version they use. I started this new KEP instead of iterate on #1201 because the voting mechanism there might be useful in the future.
/assign @lavalamp @wojtek-t @deads2k @yliaog@sanchezl
=> StorageVersion API for HA master

keps/sig-api-machinery/20190425-structural-openapi.md
The previous text's wording was confusing. Found during CRD v1 review (https://github.com/kubernetes/kubernetes/pull/79604#issuecomment-520077712)
/cc @sttts @roycaihw
=> Clarify ratcheting validation for v1 CRDs

keps/sig-scheduling/20180409-scheduling-framework.md
Currently provided link to `https://github.com/kubernetes/enhancements/blob/master/keps/sig-cluster-lifecycle/0032-create-a-k8s-io-component-repo.md` does not work as it was moved under `keps/sig-cluster-lifecycle/wgs` directory.
=> Scheduling framework: fix link to keps/sig-cluster-lifecycle/0032-create-a-k8s-io-component-repo.md

keps/sig-storage/20190204-kubernetes-csi-release-process.md
This gets added as a KEP because the proposed solution will have to run on CNCF resources (Prow) and publish to the same destination as core Kubernetes (gcr.io). However, this proposal is independent of any particular Kubernetes release and thus does not need to be tracked.
/sig storage
/cc @msau42
=> kubernetes-csi release process

keps/sig-architecture/20190731-production-readiness-review-process.md
This proposal introduces a production readiness review process for features
merging as alpha or graduating to beta or GA. The review process is intended to
ensure that features merging into Kubernetes are supportable, can be safely
operated in production environments, and can be disabled or rolled back in the
event they cause increased failures in production.
=> Introduce KEP for production readiness review

keps/sig-network/20190613-kube-proxy-component-config.md
This change is intended to propose a process and desired goals by which kube-proxy's component configuration is to be graduated to beta.
Note: This is set to `implementable` as work can start on it as soon as it merges.
ToDo: Tracking issue.
/cc @luxas @mtaufen @sttts @vllry
=> kube-proxy component config graduation to beta

OWNERS_ALIASES
We updated the leads in [community ](https://github.com/kubernetes/community/pull/4051), but seems that it didn't get propagated to enhancements repo
=> Update sig-scheduling owners.

keps/sig-scheduling/20180409-scheduling-framework.md
This is based on the possible outcome of https://github.com/kubernetes/kubernetes/issues/82897, which suggest that we may need to allow pre-filter plugins to define Add/RemovePod APIs for incremental state updates.
=> Modify pre-filter section in the scheduling framework

keps/sig-node/20190920-pod-pid-namespace.md
This is a port of the pre-KEP [Shared PID Namespace proposal](https://git.k8s.io/community/contributors/design-proposals/node/pod-pid-namespace.md) to the KEP format. None of the content has been changed except for Graduation Criteria and Implementation History.
=> Port Process Namespace Sharing proposal to KEP

keps/sig-scheduling/20190926-default-even-pod-spreading.md
Done: Summary, Motivation, Proposal, Design Details (Alpha Graduation Criteria), Alternatives.
Feature: #1258
Main repo issue: kubernetes/kubernetes#80639
=> Add KEP for default Even Pods Spreading

keps/sig-node/20190129-hugepages.md
This change adds support of multiple sizes huge pages on a
container level to support the following use cases:
- VMs running on a Kubernetes infrastructure (QEMU, libvirt, etc)
- Applications using more than one huge page size
=> Huge pages KEP: support multiple sizes huge pages on a container level

keps/sig-api-machinery/20190927-insecure-backend-proxy.md
When trying to get logs for a pod, it is possible for a kubelet to have an expired serving certificate. If a client chooses, it should be possible to bypass the default behavior of the kube-apiserver and allow the kube-apiserver to skip TLS verification of the kubelet to allow gathering logs.  This is safe because the kube-apiserver's credentials are always client certificates which cannot be replayed by an evil-kubelet and risk is contained to an evil-kubelet returning false log data.  If the user has chosen to accept this risk, we should allow it for the same reason we have an option for `--insecure-skip-tls-verify`.
On self-hosted clusters it is possible to end up in a state where a kubelet's serving certificate has expired so a kube-apiserver cannot verify the kubelet identity, *but* …
=> add an option for skipping tls verifiation on logs requests

keps/sig-api-machinery/20190226-network-proxy.md
This PR sets the Beta requirements for the KAS Network Proxy effort.
https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/20190226-network-proxy.md
/assign @andrewsykim @lavalamp 
Issues: https://github.com/kubernetes/enhancements/issues/1281
=> Adding in the Beta requirements for KAS Network Proxy

keps/sig-autoscaling/20190307-configurable-scale-velocity-for-hpa.md
I have update the proposal with changes to make the configurable scaling behavior more intuitive and in line with suggestions received during when this proposal was initial made #853 
The changes I have made are:
1. ~~Remove the `delaySeconds` options for scale down and scale up. This option is mean to prevent flapping of the replicas. But as suggested in the original PR this is a stabilization feature and I have changed the name to indicate this. I also believe there is no reason anyone would want to stabilize while scaling up. In fact this is non-intuitive because it looks similar to the `periodSeconds` use to specify the scaling rules. So now there is only one place where the `stabilizationWindow` can be specified and it is at the same level as the scale up and scale down behavior.~~ …
=> Modified proposal for configurable HPA to use a single field to specify allowed changes

keps/sig-scheduling/20191011-graduate-schedule-daemonset-pods-to-ga.md
/assign @k82cn @ahg-g
/sig apps
ref: https://github.com/kubernetes/enhancements/issues/548
=> feat(scheduling): initialize kep for graduating schedule daemonset pods

keps/sig-cluster-lifecycle/kubeadm/0029-20180918-kubeadm-phases-beta.md
This update to the kubeadm phases kep is to add support for phases in the `kubeadm upgrade apply` workflow. 
issues resolved by this: 
https://github.com/kubernetes/kubeadm/issues/1318
https://github.com/kubernetes/kubeadm/issues/1756
I also updated the KEP to document the `kubeadm upgrade node` phases workflow.
=> update kubeadm phases kep to support upgrade

keps/sig-network/20180612-ipv4-ipv6-dual-stack.md
This PR updates the dual-stack KEP to include phase 3 works and amends the content to match the phase 1 and 2 implementation.
Complete changes list
* Consistent on dual-stack
* Update last-updated
* Add Services proposal
* Update Endpoint proposal
* Remove extra Graduation Criteria section
* Update CoreDNS non-goal
* Update proposal to match phase 1 & 2 implementation
* Update phase 1 & 2 k8s release
* Add phase 3
* Update kubectl get pods outputs
* Update kubectl describe pod output
* Update Downward API implementation details
* Update e2e tests based on phase 2 implementations
* Update container runtime verbiage
/sig network
Signed-off-by: Lachlan Evenson <lachlan.evenson@microsoft.com>
=> Add dual-stack phase 3 details

keps/sig-auth/20190916-noderestriction-pods.md
Extend the NodeRestriction admission controller to add further limitations on a node's effect on
pods:
1. Restrict labels to a whitelisted prefix: `unrestricted.node.kubernetes.io/`
2. Restrict annotations to well-known annotations and a whitelisted prefix: `unrestricted.node.kubernetes.io/`
3. Restrict mirror pod OwnerReferences to only allow a node reference.
/sig auth
/sig node
/milestone v1.17
/assign @liggitt @mikedanese @derekwaynecarr 
/cc @deads2k @smarterclayton
=> Extended NodeRestriction for Pods KEP

keps/sig-storage/20191008-raw-block-support.md
Raw block volumes started implementation before KEP process was introduced. This PR adds a stub for this feature, copying / referencing the original design.
Introduced chapters about testing and feature graduation, they were not parts of the original design.
Trying GA in 1.17.
@kubernetes/sig-storage-feature-requests 
/assign @msau42 @saad-ali
=> Add KEP for block volume support

keps/sig-network/20181024-service-topology.md
Add a test plan for the service topology KEP, as required by the new criteria.
=> kep/service-topology: add test plan

OWNERS_ALIASES
@janetkuo is one of the SIG Apps chairs. You can see it at https://github.com/kubernetes/community/blob/master/sigs.yaml#L128-L141. Adding to the SIG Apps owners over here.
=> Adding Janet Kuo to the SIG Apps owners

keps/sig-api-machinery/0006-apply.md
Improve KEP by adding topology description
/cc @kwiesmueller @jennybuckley @lavalamp
=> Apply KEP: Document toplogy

OWNERS_ALIASES
Per the [OWNERS cleanup email](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/kubernetes-dev/4160VsBL7OI/BsBRZSqpCQAJ) from @mrbobbytables, this PR updates the leads for SIG Docs to match [kubernetes/org](https://github.com/kubernetes/org/blob/master/OWNERS_ALIASES#L39-L42).
/assign @Bradamant3 @jimangel 
/cc @kbarnard10
=> Update SIG Docs leads to match k/org

keps/sig-node/20190129-hugepages.md
- add example of CRI update
- Support container isolation of huge pages
More information is available in below issue.
https://github.com/kubernetes/kubernetes/issues/80716
=> Update huge pages KEP for container isolation of huge pages

keps/sig-auth/20190730-oidc-discovery.md
Per discussion on the PR. This just copies the original proposal; it hasn't been revised per comments / discussions.
Those on the prior discussion:
/cc @mikedanese @liggitt @enj @micahhausler @ericchiang
=> Move kubernetes/community#2314 to a KEP.

keps/sig-storage/20190130-csi-raw-block-support.md
The refactoring needed for separating NodeStage / NodePublish is quite large and we'd like to make sure it's well tested before declared GA.
It was discussed on today's SIG storage meeting.
cc @mkimuram @wongma7 @msau42
=> Keep CSI Raw block feature beta in 1.17

keps/sig-network/20190125-ingress-api-group.md
This is a recovered version of https://github.com/kubernetes/enhancements/pull/1036, which I closed by accident.
=> Ingress GA, updated KEP, merged review comments (recovered version of #1036)

keps/sig-network/20190423-service-lb-finalizer.md
Enhancement issue: https://github.com/kubernetes/enhancements/issues/980
The thinking is to do a lightweight promotion to GA as there is no behavioral changes from the Beta phase.
Let me know if there is any objection, thanks!
/assign @bowei @andrewsykim @thockin
=> Update graduation criteria for service finalizer KEP

keps/sig-network/20181024-service-topology.md
Per discussions in https://github.com/kubernetes/kubernetes/pull/72046#issuecomment-534464680, updating the Service Topology KEP to address the intersection of `topologyKeys` and `externalTrafficPolicy`.
=> Service Topology: add consideration for externalTrafficPolicy=Local

keps/sig-architecture/2019-03-19-go-modules.md
Triggered by discussion in https://github.com/kubernetes/kubernetes/issues/84608
Specifically, see various scenarios in https://github.com/kubernetes/kubernetes/issues/84608#issuecomment-548821995
cc @sttts
=> Update published modules with v0.x.y tags

keps/sig-apps/sidecarcontainers.md
After some discussion on the implementation PR https://github.com/kubernetes/kubernetes/pull/80744 some issues cropped up that need clarifying in the KEP.
Firstly TerminationGracePeriod, I've updated the wording to be more explicit over how exactly it would behave in the current design. 
There was a suggestion that perhaps both the Sidecars and Containers could have a separate GracePeriod, e.g. if `TerminationGracePeriod: 30s`, the Containers would have 30 seconds to Terminate and then the Sidecars would have 30 seconds. So you could end up with 2xGracePeriod. But I'm not sure whether we should go with this or not.
In regards to PodPhase, we originally said not to change this I noticed one particularly odd case which made me think it might need a tweak for this to work. 
If your Pod has …
=> update sidecars kep, changes to TerminationGracePeriod/Pod phase

keps/sig-cloud-provider/20190125-out-of-tree-openstack.md
Openstack Cloud Provider has been implemented from long, This PR updated the KEP with current status of provider work. Fixes:#669
=> Update OpenStack Cloud Provider KEP

keps/sig-instrumentation/20190404-kubernetes-control-plane-metrics-stability.md
Update KEP according to the discussion on https://github.com/kubernetes/kubernetes/pull/84292
cc @logicalhan @brancz @ehashman
=> Update KEP(metrics stability) about the escape hatch flag

keps/sig-architecture/20191023-conformance-without-beta.md
Merged prematurely [missing a couple acks from reviewer/approvers](https://github.com/kubernetes/enhancements/pull/1332#issuecomment-546552609).
approver/reviewer acks:
=> Move "conformance without beta" KEP to implementable

keps/sig-network/20190920-external-dns.md
A proposal to move ExternalDNS out of kubernetes-incubator and move it into the Kubernetes organization.
=> Proposal moving ExternalDNS into Kubernetes organization

keps/sig-api-machinery/20190802-dynamic-coordinated-storage-version.md
The bootstrap ordering introduces a single point of failure to the cmd/kube-apiserver binary, so I want to discuss it before implementing it.
/assign @lavalamp @deads2k
=> Update the storage version API KEP with implementation details

keps/sig-cli/kustomize-secret-generator-plugins.md
the error url is : https://github.com/kubernetes-sigs/kustomize/blob/master/docs/kustomization.yaml
the right url is :  https://github.com/kubernetes-sigs/kustomize/blob/master/examples/helloWorld/kustomization.yaml
=> modify the error url of kustomization.yaml

keps/sig-storage/20191117-immutable-ephemeral-volumes.md
@kubernetes/sig-storage-pr-reviews 
@kubernetes/sig-node-proposals 
@kubernetes/sig-apps-pr-reviews 
@saad-ali @msau42 @derekwaynecarr @yujuhong @janetkuo - I would appreciate any feedback on it
@kubernetes/sig-scalability-feature-requests @mm4tt - FYI
=> KEP for ability to switch-off Secrets/ConfigMaps updates for running Pods

keps/sig-instrumentation/20181106-kubernetes-metrics-overhaul.md, keps/sig-instrumentation/20190404-kubernetes-control-plane-metrics-stability.md
Some broken links update:
* github.com/kubernetes/community/blob/master/contributors/devel/instrumentation.md --> github.com/kubernetes/community/blob/master/contributors/devel/`sig-instrumentation`/instrumentation.md
* github.com/kubernetes/enhancements/blob/master/keps/sig-instrumentation/0031-kubernetes-metrics-overhaul.md --> github.com/kubernetes/enhancements/blob/master/keps/sig-instrumentation/`20181106`-kubernetes-metrics-overhaul.md
=> Update broken links from keps/sig-instrumentation

keps/sig-api-machinery/0015-dry-run.md
For server-side dry-run GA, we want to support `--dry-run=server`.
This change updates the KEP to describe this plan, as discussed in https://github.com/kubernetes/kubernetes/issues/85652
=> Update dry-run KEP with kubectl plan

keps/sig-auth/20190116-service-account-external-signing.md
This is my first KEP, any input on structure or details is appreciated.
Initial implementation PR is kubernetes/kubernetes#73110
/sig auth
/cc @mikedanese @liggitt @tallclair
=> Added service account external signer KEP

keps/sig-network/20191104-iptables-no-cluster-cidr.md
KEP to update iptables to have alternate ways of detecting cluster originated traffic instead of using the cluster cidr.
=> KEP: kube-proxy detect "local" traffic w/o cluster CIDR

keps/sig-storage/20191117-immutable-secrets-configmaps.md
Also fill out:
- test plan
- graduation criteria
- version skew strategy
Ref https://github.com/kubernetes/enhancements/issues/1412
/assign @saad-ali 
/cc @yujuhong @lavalamp @msau42 @thockin @derekwaynecarr @kubernetes/sig-storage-feature-requests
=> Mark "Immutable Secrets/ConfigMaps" KEP implementable

keps/sig-cloud-provider/providers/0004-cloud-provider-template.md
the error url: https://github.com/kubernetes/community/blob/master/keps/sig-cloud-provider/0019-cloud-provider-documentation.md
modify to : https://github.com/kubernetes/enhancements/blob/master/keps/sig-cloud-provider/20180731-cloud-provider-docs.md
/kind bug
/sig docs
=> modify the error url about cloud-provider

keps/sig-network/0015-20180614-SCTP-support.md
There don't seem to be any docs on what the KEP `status` values mean, but I assume it shouldn't be `implemented` until it's GA? So I bumped it back to `implementable`.
There are two "FIXME"s to figure out, plus I'm pretty unsure about the beta->GA criteria. (Especially the "2 implementations" part.)
cc @kubernetes/sig-network-misc
=> Update SCTP KEP with Graduation Criteria

keps/sig-auth/0000-20170814-bounding-self-labeling-kubelets.md
Updating timeline since we didn't turn off node labeling on create until 1.16
/cc @mikedanese
=> Update node self-labeling timeline

keps/sig-cluster-lifecycle/kubeadm/20190122-Certificates-copy-for-kubeadm-join--control-plane.md
/kind bug
/sig docs
the error url is :
https://github.com/kubernetes/enhancements/blob/master/keps/sig-cluster-lifecycle/0015-kubeadm-join-control-plane.md
the right url is :
https://github.com/kubernetes/enhancements/blob/master/keps/sig-cluster-lifecycle/kubeadm/0015-kubeadm-join-control-plane.md
=> modify the error url of kubeadm

keps/sig-scheduling/20191011-graduate-schedule-daemonset-pods-to-ga.md
=> feat(scheduling): update KEP to implemented

keps/sig-instrumentation/0034-distributed-tracing-kep.md
[Relevant enhancement feature issue](https://github.com/kubernetes/enhancements/issues/647)
=> Propose KEP: Leveraging Distributed Tracing to Understand Kubernetes Object Lifecycles

keps/sig-api-machinery/0006-apply.md
Address the Status Wiping Issue for Server-Side Apply reported in https://github.com/kubernetes/kubernetes/issues/75564
/wg apply
/cc @apelisse @jennybuckley
=> add status wiping section to apply kep

keps/sig-cloud-provider/20190722-ccm-instance-metadata.md, keps/sig-cloud-provider/azure/20190722-ccm-instance-metadata.md
KEP:  Support Instance Metadata Service with Cloud Controller Manager.
Refer https://github.com/kubernetes/cloud-provider/issues/30.
/assign @andrewsykim @craiglpeters @justaugustus
=> KEP: Support Instance Metadata Service with Cloud Controller Manager

keps/sig-api-machinery/00xx-admission-webhooks-to-ga.md, keps/sig-api-machinery/20180731-crd-pruning.md, keps/sig-api-machinery/20190425-structural-openapi.md, keps/sig-api-machinery/20190426-crd-defaulting.md, keps/sig-api-machinery/20190612-crd-group-protection.md
Mark KEPs for GA features as "implemented".
=> keps/sig-api-machinery: mark implemented keps

keps/sig-auth/20190607-certificates-api.md
Adds the ability for CSRs to have different signers while keep backward compatibility with existing consumers of v1beta1.  This is on the path to a GA API.
@kubernetes/sig-auth-api-reviews 
=> add multiple signers to CSRs

keps/sig-cli/20190805-kubectl-debug.md, keps/sig-cli/20190805-pod-troubleshooting.md
Adds a provisional KEP proposing a new `kubectl debug` command based on #277. KEP is not yet fully described, but feedback is welcome.
=> Add KEP for kubectl debug

keps/sig-network/20190125-ingress-api-group.md
This PR has a lot of discussion, the final proposal ended up being very simple:
* Default to ImplementationSpecific PathType for Ingress to ensure backwards compatibility
---
_For posterity, here's what the original proposal was:_
To ensure backwards compatibility, we need to ensure that existing Ingresses continue to be valid. Both `Exact` and `Prefix` path types include more validation than currently included by ingresses, specifically that they must not contain consecutive `'/'` characters. Additionally, Ingress path validation currently includes a requirement that all paths are valid regexes, something not required by either `Exact` or `Prefix` path types. The new `ImplementationSpecific` path type comes with no API validation as defined by this KEP. 
As I see it, there are several …
=> Clarifying default Ingress PathType and corresponding validation.

keps/sig-network/20190125-ingress-api-group.md
There were some questions in https://github.com/kubernetes/enhancements/pull/1413 around the path matching logic proposed in the original KEP, specifically the proposal to ignore trailing slashes in paths. I talked with @bowei about the background here, and apparently this was intended to be applicable to only prefix path matching. The idea is that if you want to match exactly "/foo/", you could use an exact path type, but treating "/foo/" and "/foo" as equivalent prefixes will likely be helpful for end users. This PR clarifies the path matching logic proposed here and adds more examples of what should and shouldn't match.
/sig network
/cc @bowei @aledbf @hbagdi @szuecs 
=> Clarifying Ingress V1 Path Matching

keps/sig-network/0030-nodelocal-dns-cache.md
Fix wrong word: 'repond' to 'respond'
/kind bug
/sig network
=> Modify wrong word of sig-network nodelocal dns

keps/sig-storage/20190408-volume-scheduling-limits.md
Volume limits has graduated to GA in v1.17: https://github.com/kubernetes/kubernetes/pull/83568
Mark KEP as implemented so #554 can be closed.
/assign @gnufied @msau42
CC @jeremyrickard
=> Mark Volume Scheduling Limits KEP as implemented

keps/sig-scheduling/20200114-taint-based-evictions.md
Based on this comment in the TBE issue (https://github.com/kubernetes/enhancements/issues/166#issuecomment-573812894) we are creating an enhancement to officially track the promotion of Taint Based Evictions to GA
=> Promote taint based evictions to GA

cmd/kepify/main.go, pkg/kepval/keps/proposals.go
`go run cmd/kepify/main.go --dir keps --output out.json`
=> kepify: New command to generate KEP json for Netlify

OWNERS_ALIASES
/assign @timothysc
xref: https://github.com/kubernetes/community/tree/master/sig-cluster-lifecycle#leadership
Remove luxas to sync with k/community as requested by justaugustus.
=> OWNERS_ALIASES: add fabriziopandini and neolit123 to SCL leads

keps/sig-cloud-provider/azure/20190125-out-of-tree-azure.md
Mark KEP Support Out-of-Tree Azure Cloud Provider as implementable and fix the broken links.
Refer https://github.com/kubernetes/enhancements/issues/667.
=> Mark KEP Support Out-of-Tree Azure Cloud Provider as implementable

keps/sig-api-machinery/20190425-structural-openapi.md
modify the error url : https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiextensions-apiserver/pkg/controller/openapi/conversion.go
the right url is :  https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiextensions-apiserver/pkg/controller/openapi/v2/conversion.go
=> modify the error url of conversion.go

keps/sig-api-machinery/20190711-remove-selflink.md
modify the error url: 
https://github.com/kubernetes-client/java/blob/master/kubernetes/src/main/java/io/kubernetes/client/models/V1ListMeta.java
https://github.com/kubernetes-client/java/blob/master/kubernetes/src/main/java/io/kubernetes/client/models/V1ObjectMeta.java
the right url is :
https://github.com/kubernetes-client/java/blob/master/kubernetes/src/main/java/io/kubernetes/client/openapi/models/V1ListMeta.java
https://github.com/kubernetes-client/java/blob/master/kubernetes/src/main/java/io/kubernetes/client/openapi/models/V1ObjectMeta.java
=> modify the error url of java-client

keps/sig-scheduling/20190926-default-even-pod-spreading.md
Now that the framework's migration is mostly done, it makes more sense to put this feature in terms of it. It greatly simplifies the Component Config API.
Also add its own feature flag, so that Even Pod Spreading can graduate on its own. This also simplifies the semantics of using Policy API.
=> Use framework's PluginConfig for default pod spreading

keps/sig-windows/windows-runtimeclass-support.md
One of the tasks mentioned in this KEP - adding a node label - was completed for 1.17 and documented. Marking it done.
PRs:
kubernetes/website#16697
kubernetes/kubernetes#84472
Master tracking for KEP: https://github.com/kubernetes/enhancements/issues/1301
/sig windows
=> Marking node label for OS version complete in 1.17

keps/sig-windows/20190424-windows-cri-containerd.md
This is a quick update - this enhancement https://github.com/kubernetes/enhancements/issues/1001 slipped from 1.17. Changing milestones to 1.18.
/assign michmike
=> Update milestones for Windows ContainerD

OWNERS_ALIASES
This PR propagates https://github.com/kubernetes/community/pull/4431 to k/enhancements.
=> Update Huang-Wei as new sig-scheduling co-lead

keps/sig-network/0030-nodelocal-dns-cache.md
Modified the existing KEP, as discussed in https://github.com/kubernetes/enhancements/pull/1307
=> GA graduation criteria for NodeLocal DNSCache

keps/sig-cluster-lifecycle/kubeadm/20191125-remove-clusterstatus-from-kubeadm-config.md
This KEP is proposing a new mode for tracking the list of the API endpoints in a cluster, thus allowing to remove the  `ClusterStatus` entry in the `kubeadm-config` ConfigMap and solve the problems that arise when, for any reasons, such entry does not reflect anymore the real status of the cluster.
/assign @neolit123 @rosti @ereslibre @ncdc @timothysc
=> Kubeadm: Remove ClusterStatus from kubeadm-config

keps/sig-auth/20190607-certificates-api.md
* Fixes typo in kubelet client signer name
* Adds format details for status.certificates
* Describes validation in v1beta1 (none!) and v1
* PEM-formatted blocks of type "CERTIFICATE", with no headers
* Default meaning of additional certificates blocks is to treat them as intermediate certificates, signers may define different meaning for their signerNames if desired (e.g. issuing multiple certificates cross-signed by different CAs)
cc @kubernetes/sig-auth-api-reviews @mikedanese @munnerz @deads2k @enj
=> Describe status.certificates format, intermediates

keps/sig-network/20191227-app-protocol.md
The lack of standardized application protocol support for Services and Endpoints has frustrated countless Kubernetes end users. With EndpointSlices, we added a new `AppProtocol` field as a first step, adding that same field to Services and Endpoints will ensure full API support for application protocols. 
This [issue was initially raised here](https://github.com/kubernetes/kubernetes/issues/40244) where @thockin suggested filing a KEP. I'm happy to also file a PR with implementation if this is something we want to proceed with. I'd love to get this into 1.18 if possible.
/sig network
/cc @thockin @dcbw
=> KEP: Adding AppProtocol to Services and Endpoints

cmd/kepify/main.go, pkg/kepval/keps/proposals.go
This makes the JSON output of the kepify tool a bit easier parsable, since we now marshal into an array of objects. Beside this, we add the KEP ID (hashed value) as `ID` field to each proposal as well.
We have to avoid dashes in the JSON keys to be able to directly map the keys into Typescript structures.
Follow up of: https://github.com/kubernetes/enhancements/pull/1467
Initiated by: https://github.com/kubernetes-sigs/release-notes/pull/140
The new layout:
```json
[
{
"id": "5322b8bc501906188172ab1818558107",
"title": "aws-k8s-tester",
"authors": ["@gyuho"],
"owningSig": "sig-cloud-provider",
"participatingSigs": null,
"reviewers": ["@d-nishi", "@shyamjvs"],
"approvers": ["@d-nishi", "@shyamjvs"],
"editor": "TBD",
"creationDate": "2018-11-26",
"lastUpdated": "2018-11-29",
"status": …
```
=> Modify KEPify JSON output

keps/sig-network/20181024-service-topology.md
The EndpointSlice controller needs to be updated to use the new TopologyKeys field on Services when populating topology data.
Enhancement Issue: https://github.com/kubernetes/enhancements/issues/536
/sig network
/cc @imroc @johnbelamaric 
=> Updating Service Topology KEP to include EndpointSlice Controller Changes

keps/sig-scheduling/20200114-multi-scheduling-profiles.md
Add Test Plan and Alpha Graduation criteria.
Also:
- Specify validation of Plugins.QueueSort
- Remove AlgorithmSource (kubernetes/kubernetes#87526)
=> Set "Multi Scheduling Profiles" to "implementable"

keps/sig-cluster-lifecycle/kubeadm/20190424-kubeadm-for-windows.md
Based on discussions we've had with SIG Windows and SIG Cluster Lifecycle we've decided to revise this KEP to reflect a new approach using DaemonSets to run CNI and kube-proxy. This is the first pass at updating it to reflect the new workflow.
@PatrickLang 
@neolit123 
/assign @michmike @fabriziopandini @timothysc 
/sig windows
=> Update kubeadm Windows KEP to reflect new DaemonSet-based approach

keps/sig-storage/20181111-extend-datasource-field.md
Update KEP to note graduation from Beta to GA for sig-storage cloning
feature in 1.18. Also add testing section to KEP.
issue: #989
=> Update PVC DataSource to GA

keps/sig-cloud-provider/azure/20190125-out-of-tree-azure.md
=> Fix typo in 20190125-out-of-tree-azure.md

keps/sig-cloud-provider/20180530-cloud-controller-manager.md
Typo from `kuberetes` to `kubernetes `.
=> Fix typo for 20180530-cloud-controller-manager.md

keps/sig-node/0035-20190130-topology-manager.md
This PR updates the TopologyManager KEP with its proper milestone information for Kubernetes v1.17 and v1.18.
=> Update TopologyManager KEP with new milestone information

keps/sig-autoscaling/20181106-in-place-update-of-pod-resources.md, keps/sig-node/20181106-in-place-update-of-pod-resources.md, keps/sig-node/20191025-kubelet-container-resources-cri-api-changes.md
One of the items/comments that is related to [In-Place Pod Vertical Scaling KEP](https://github.com/kubernetes/enhancements/pull/686#) is to extend/update the CRI API to better support different Container runtimes such as Windows etc for resource update. 
This mini KEP outlines the proposed changes to CRI API to accomplish that review item. This does not block implementation of Vertical Scaling KEP, but would be good to have in the time-frame of implementation of In-Place Pod Vertical Scaling feature.
CC: @PatrickLang @dashpole @derekwaynecarr @dchen1107 @yujuhong
=> In-Place Vertical Pod Scaling KEP to implementable, and mini-KEP for CRI extensions

keps/sig-storage/20200120-skip-permission-change.md
Design proposal for https://github.com/kubernetes/enhancements/issues/695
/sig storage
/assign @liggitt @msau42 @jingxu97
=> Add skip permission change kep

keps/sig-storage/20190129-csi-migration.md
/assign @jeremyrickard 
/assign @saad-ali @jsafrane @msau42 @misterikkit 
/cc @ddebroy @leakingtapan @andyzhangx @xing-yang 
Copying over test plan from design doc and clarifying some specific points.
/sig storage
=> Add test plan from design doc to KEP for CSI storage migration

keps/sig-storage/20190530-pv-health-monitor.md
Moving https://github.com/kubernetes/community/pull/1484 here
=> PV health monitor KEP

keps/sig-cloud-provider/20191004-out-of-tree-credential-providers.md
This is the second iteration of the credential provider extraction KEP.   This iteration proposes building on top of the ExecCredential API which defines specifying a binary to execute and the interface between client-go and the credential process.   The ExecCredential API is currently used for client side authentication credentials not currently supported by client-go.
This approach was chosen because it is the simplest and meets all the requirements for removing the credential provider from Kubernetes core without adding significant complexity which will delay the entire cloud provider migration/extraction effort.
The other proposals have been moved to "alternatives considered".
=> Credential provider extraction

keps/sig-cluster-lifecycle/kubeadm/20190722-Advanced-configurations-with-kubeadm-(Kustomize).md
The Cluster Addons sub-project decided to use `cluster-addons` across Slack, Github, etc consistently, cf https://github.com/kubernetes/org/issues/1583
=> repository was renamed to cluster-addons

keps/sig-cli/20200115-kubectl-diff.md
This addresses a nit regarding our KEP metadata because `implemented` is reserved for stable GA graduation. See https://github.com/kubernetes/enhancements/issues/491#issuecomment-579666531.
cc @palnabarun
=> Fix status for `kubectl diff` kep

keps/sig-network/20191227-app-protocol.md
I missed a test plan in the original KEP. This should be remarkably straightforward to test. As suggested by @jeremyrickard, I'll also be filing an [Exception Request](https://github.com/kubernetes/sig-release/blob/master/releases/EXCEPTIONS.md) for this. 
Enhancement Issue: https://github.com/kubernetes/enhancements/issues/1507
/sig network
=> Adding test plan for AppProtocol KEP

keps/sig-api-machinery/0015-dry-run.md
Add the missing sections. The changes for GA had already been discussed and approved as part of #1399
=> kep/dry-run: Add required release sections

keps/sig-auth/20190607-certificates-api.md
Adds a test plan to the CSR KEP
/cc @mikedanese 
fyi @jeremyrickard
=> Update CSR test plan

keps/sig-node/20190129-hugepages.md
Using some of the pod examples from the document raises
pod validation errors.
The reason is that volume names must conform DNS-1123
label convention. They can't contain uppder case
alphabetic characters.
Lowercased volume names to satisfy DNS-1123 requirements.
=> Fix volume names for hugepage mounts

keps/sig-network/20190125-ingress-api-group.md
Before / as Ingress goes GA, provide clear-enough and current-enough documentation. Update _Graduate Ingress to GA_ to note this as a requirement for graduation.
/sig docs
/sig network
=> Document Ingress for GA

keps/sig-auth/20190607-certificates-api.md
Whilst implementing the recent changes in #1400 in kubernetes/kubernetes, we discovered an ambiguity in the wording for the requirements around x509 extensions for `kubelet-serving` specified CertificateSigningRequests.
This patch amends the KEP according to the actual requirements/expectations, based on how the kubelet actually behaves: https://github.com/kubernetes/kubernetes/blob/d90dd93855ab6c3ccda73dfbd3d19c81f56abca5/pkg/kubelet/certificate/kubelet.go#L89-L103
/cc @liggitt
/assign @enj
=> Clarify requirements for permitted x509 extensions

keps/sig-node/20190129-hugepages.md
Update hugepages KEP to meet release checklist.
In the checklist, there are :
- Test plan is in place, giving consideration to SIG Architecture and SIG Testing input
- "Implementation History" section is up-to-date for milestone
Full version of checklist can be found here:
https://github.com/kubernetes/enhancements/blob/master/keps/YYYYMMDD-kep-template.md#release-signoff-checklist
=> Update hugepages KEP for 1.18 rel

keps/sig-node/20170523-cpu-manager.md
CPU Manager is in beta, it was introduced in 1.8 as alpha then it went beta in 1.10.
Migrate cpu-manager.md from [kubernetes/community](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node/cpu-manager.md) **to maintain the future enhancement for cpu manager.**
I will propose a new enhancement later as part as beta.
The initial date of this kep comes from the date of its initial [commit](https://github.com/kubernetes/community/pull/654/commits). 
```
Added initial draft of CPU manager proposal.
ConnorDoyle committed on May 23, 2017
```
=> migrate cpu-manager.md from kubernetes/community

keps/sig-scheduling/20190221-pod-topology-spread.md
Tweak `sig-scheduling/20190221-pod-topology-spread.md`: before this feature goes GA, ensure that documentation for this feature is clear and complete.
Completeness might include:
- consider what diagrams might be appropriate and, at a minimum, log an issue against [k/website](https://github.com/kubernetes/website/) to track adding those diagrams.
- Add a task page that explains how to spread Pods for a workload across multiple failure zones.
There is existing documentation and that seems OK enough for the feature to move to Beta.
=> Require documentation for EvenPodsSpread feature

keps/sig-api-machinery/20191210-consistent-reads-from-cache.md
This idea has been around for awhile and there is interest in working on it for 1.18, so I've put it in KEP form.
cc @wojtek-t @jingyih @liggitt
=> KEP: Consistent Reads from Cache

keps/sig-node/20191118-cgroups-v2.md
Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>
=> add KEP for cgroups v2 support

keps/sig-cloud-provider/providers/0020-cloud-provider-alibaba-cloud.md
/kind bug
/sig docs
the error url is: https://github.com/kubernetes/community/blob/master/keps/sig-cloud-provider/0002-cloud-controller-manager.md
the right url is: https://github.com/kubernetes/enhancements/blob/master/keps/sig-cloud-provider/20180530-cloud-controller-manager.md
=> modify the error url of cloud-controller-manager.md

keps/sig-node/20200127-taint-based-evictions.md
This was erroneously merged under sig-scheduling, but it should be under sig-node
See https://github.com/kubernetes/kubernetes/pull/87487#issuecomment-578266832
/sig node
=> Move TaintBasedEvictions GA kep from scheduling to node

keps/sig-auth/20190730-oidc-discovery.md
/hold
Only makes sense if https://github.com/kubernetes/kubernetes/pull/88344 is accepted.
/kind bug
/assign @mtaufen @liggitt @mikedanese
@kubernetes/sig-auth-pr-reviews
/sig auth
/milestone v1.18
=> oidc discovery kep: include system:serviceaccounts binding details

keps/sig-storage/20180515-svcacct-token-volumes.md
this PR is a copy of the pre-existing design proposal kubernetes/community#1973 and we would like to convert the design proposal into this KEP and iterate on it. more changes can be expected in subsequent PRs to this KEP with the goal of GA this feature which provides nice security properties.
=> port serviceaccount token volume design proposal to KEP

keps/sig-instrumentation/20191115-structured-logging.md
Review progress:
Please let me know if you think you should be added to this list.
Proposal was presented on:
- sig-instrumentation meeting 2019-12-12
- sig-architecture meeting 2020-01-16
- wg-component-standard meeting 2020-02-11
PR will be merged when all reviewers give their lgtm.
=> [KEP][sig-instrumentation] Structured logging

keps/sig-instrumentation/20191115-structured-logging.md
This PR moves Structured Logging KEP into implementable state and does some minor fixes.
Can you approve changing of KEP state into "implementable"?
=> Move Structured Logging KEP into implementable state

keps/sig-docs/20191020-doc-policies-for-third-party-content.md
Feature docs are not a place for vendor pitches. Nevertheless, SIG Docs has seen pull requests that are more or less a request to place advertising content on the Kubernetes website.
Feature docs also contain content hosted in multiple places (“dual-sourced content”). A good practice for code project docs is to host single-sourced content only, and to provide links to other providers’ single-sourced content.
This ~draft~ KEP defines a policy on documentation content, so that authors can judge what is appropriate to propose, and so that PR approvers can make consistent, fair decisions during the review process.
Related issue: #1326
/kind kep
/sig docs
=> KEP: 3rd party content in documentation

keps/sig-node/20190129-pid-limiting.md
Currently, the kubelet ranks pods for out-of-pid eviction only by PodPriority. When there are many pods of the same priority, it ranks them randomly, which is not ideal. In the case of a fork bomb, the kubelet prevents the node from running out of pids, but may evict many innocent pods before choosing the fork bomb.
See https://github.com/kubernetes/kubernetes/issues/89284 for details on the implementation.
/sig node
/assign @derekwaynecarr
=> Add pod-level process stats to the summary API for out-of-pid eviction

keps/sig-architecture/1635-prevent-permabeta/README.md, keps/sig-architecture/1635-prevent-permabeta/kep.yaml, keps/sig-architecture/20191001-prevent-permabeta.md
When a feature reaches beta, it is turned on by default.  This is great for getting feedback, but it can also lead to state where users and vendors start building important infrastructure against APIs that are not considered stable. In addition, once a feature is on by default, the incentive to further stabilize appears to diminish. See the features that have been beta for a long time: CSRs as a for instance.
APIs and features should not languish in beta.  They should take feedback and progress towards GA by either
1. meeting GA criteria and getting promoted, or
2. having a new beta and deprecating the previous beta
This must happen within six months (two releases).  If it does not, the API will be deprecated with an announced intent to remove the feature per the deprecation policy. …
=> Require Transition from Beta

keps/sig-architecture/960-conformance-behaviors/README.md
/kind bug
/sig docs
the error url is: https://github.com/kubernetes/kubernetes/blob/master/test/conformance/testdata/conformance.txt
https://github.com/kubernetes/kubernetes/blob/master/test/conformance/testdata/conformance.yaml
=> modify the error url of conformance

keps/sig-cloud-provider/20191004-out-of-tree-credential-providers.md
the error url is:  
https://github.com/kubernetes/enhancements/blob/master/keps/sig-cloud-provider/2019-01-25-removing-in-tree-providers.md
the right url is: 
https://github.com/kubernetes/enhancements/blob/master/keps/sig-cloud-provider/20190125-removing-in-tree-providers.md
=> modify the error url of removing-in-tree-providers

OWNERS_ALIASES
* @jsafrane and @msau42 are sig-storage tech leads.
* @saad-ali and @xing-yang are sig-storage co-chairs.
* And remove @childsb.
See https://github.com/kubernetes/community/tree/master/sig-storage
=> Update OWNERS_ALIASES for SIG-Storage

keps/sig-autoscaling/0001-container-resource-autoscaling.md
This is an initial proposal to have scaling for target based on container resources.
=> KEP for HPA scaling based on container resources

keps/sig-network/20190603-EndpointSlice-API.md
The actually [implemented flag](https://github.com/kubernetes/kubernetes/blob/7da9bdc4f64a5014a4b45cc34c8a86976db1ce11/cmd/kube-controller-manager/app/options/endpointslicecontroller.go#L45) in controller manager for configuring the max endpoints per slice is `MaxEndpointsPerSlice` instead of  MaxEndpointThreshold.
This PR is going to correct this.
/sig network
/cc @robscott 
Thanks.
=> Correct max endpoints per slice flag.

keps/sig-network/20190423-service-lb-finalizer.md
Ref https://github.com/kubernetes/enhancements/issues/980#issuecomment-570606885, service finalizer has graduated to stable in 1.17.
/cc @jeremyrickard
=> Update service finalizer KEP to implemented

keps/sig-contributor-experience/1553-issue-triage/README.md, keps/sig-contributor-experience/1553-issue-triage/kep.yaml
Improve issue triage in `kubernetes/kubernetes` by defining a workflow and automation for contributors.
_Note: This PR uses the modified KEP template being proposed in https://github.com/kubernetes/enhancements/pull/1545_
/milestone v1.18
/kind feature
/sig contributor-experience pm release
cc: @kubernetes/sig-release-admins
ref:
- https://github.com/kubernetes/enhancements/issues/1553
- https://groups.google.com/forum/#!topic/kubernetes-sig-contribex/BvGmOQ0v5f0
- kubernetes/community#3456
- kubernetes/community#3455
- kubernetes/test-infra#16298
- kubernetes/test-infra#16299
=> keps/contribex: Add KEP-1553 (Issue Triage Workflow and Automation)

keps/sig-storage/20181111-extend-datasource-field.md, keps/sig-storage/20190129-csi-pod-info-on-mount.md, keps/sig-storage/20190129-csi-skip-attach.md, keps/sig-storage/20190130-csi-raw-block-support.md, keps/sig-storage/20191008-raw-block-support.md
Marking couple of KEPs that reached GA in this release:
* Extend usage of Volume DataSource to allow PVCs for Cloning: reached GA in https://github.com/kubernetes/enhancements/issues/989
* Pass Pod information in CSI calls: https://github.com/kubernetes/enhancements/issues/603
* Skip attach for non-attachable CSI volumes: https://github.com/kubernetes/enhancements/issues/770
* CSI raw block: https://github.com/kubernetes/enhancements/issues/565
* Raw block: https://github.com/kubernetes/enhancements/issues/351
=> Mark 1.18 storage GA features as implemented

OWNERS, OWNERS_ALIASES, keps/OWNERS
- Transfer Enhancements subproject ownership to SIG Arch
- Update Enhancements subproject owners
- @jeremyrickard 
- @johnbelamaric 
- @justaugustus 
- @mrbobbytables
~Email to follow shortly...~
Email retiring SIG PM and announcing transfer of Enhancements subproject to SIG Arch: https://groups.google.com/d/topic/kubernetes-dev/RU8iINF758Y/discussion
/assign @dims @johnbelamaric @derekwaynecarr 
/hold
/milestone v1.19
/sig architecture pm
=> Transfer Enhancements subproject ownership to SIG Arch

keps/sig-storage/20180515-svcacct-token-volumes.md
currently the mode of projected service account volume is 0600 effectively 0400, which may not work in pods with non-root containers. see https://github.com/kubernetes/kubernetes/issues/74565.
+   *Case 1:* The pod has an fsGroup set. We can set the file permission on the
token file to 0600 and let the fsGroup mechanism work as designed. It will
set the permissions to 0640, chown the token file to the fsGroup and start
the containers with a supplemental group that grants them access to the
token file. This works today.
+   *Case 2:* The pod’s containers declare the same runAsUser for all containers
in the pod. We chown the token file to the pod’s runAsUser to grant the
containers access to the token.
+   *Fallback:* We set the file permissions to world readable (0644) to match the …
=> proposal for file permission handling in projected service account volume

keps/sig-api-machinery/1693-warnings/README.md, keps/sig-api-machinery/1693-warnings/kep.yaml
This proposes a mechanism for surfacing use of deprecated APIs to users via `Warning` headers, and to administrators via metrics/audit events.
Proof-of-concept at https://github.com/kubernetes/kubernetes/pull/73032
/sig api-machinery architecture cli instrumentation
=> KEP 1693: Warning mechanism for use of deprecated APIs

keps/sig-storage/20190124-csi-topology.md, keps/sig-storage/20190124-local-persistent-volumes.md
=> Update sig-storage features as implemented

keps/sig-node/20200205-build-kubelet-without-docker.md
A KEP proposing supporting building a Kubelet without any "Docker-specific" code or dependency on the `docker/docker` Golang library, via the use of build tags.
=> Build Kubelet without Docker

keps/sig-architecture/2019-07-16-node-role-label-use.md
We did nothing in 1.18 to see if the feature could be tolerated in
all clouds, and now we know that it can.
=> Update node-role KEP timeline for beta in 1.19

cmd/kepval/main.go, cmd/kepval/main_test.go, keps/sig-architecture/617-improve-kep-implementation/kep.yaml, keps/sig-auth/20190711-external-credential-providers.md, pkg/kepval/keps/proposals.go, pkg/kepval/keps/validations/yaml.go
@kubernetes/enhancements-admins
=> Add support for symlinks and KEP metadata files

keps/sig-api-machinery/1693-warnings/README.md
xref #1693 
allow further review from https://github.com/kubernetes/enhancements/pull/1694
* made copy-edits
* addressed feedback from sig-cli, sig-api-machinery, and sig-architecture discussions
* added CRD deprecated and deprecationWarning fields
* added admission webhook warnings field in admissionreview response
* added kubectl `--warnings-as-errors` option
* added details about size limits and handling of excessive numbers of warnings
Reviewers:
Approvers:
=> KEP 1693: copy edits, GA criteria, kubectl warnings-as-errors option, extension mechanisms

keps/sig-auth/0000-20170814-bounding-self-labeling-kubelets.md
Last item in the timeline is complete in 1.19 in https://github.com/kubernetes/kubernetes/pull/90307
/sig auth
/cc @mikedanese
=> Mark node labeling KEP as implemented

.githooks/pre-commit, Makefile
Adds a makefile that serves as an entrypoint to the various `hack/verify*` scripts along with an optional git pre-commit hook that will execute the `hack/verify.sh` script.
/assign @justaugustus @johnbelamaric @jeremyrickard
=> Add Makefile and optional pre-commit hooks

keps/sig-node/20190717-seccomp-ga.md
This is a proposal to upgrade the seccomp annotation on pods & pod security policies to a field, and
mark the feature as GA. This proposal aims to do the _bare minimum_ to clean up the feature, without
blocking future enhancements.
/sig-node
/sig-auth
/assign @liggitt @dchen1107 @derekwaynecarr 
/cc @jessfraz
=> KEP for promoting seccomp to GA

keps/sig-node/20200205-build-kubelet-without-docker.md
The diff is ready to merge, so we can mark as implementable for 1.19.
cc @dims @derekwaynecarr @dchen1107
=> Mark dockerless KEP implementable for 1.19

keps/NNNN-kep-template/README.md, keps/NNNN-kep-template/kep.yaml
This PR adds the PRR questionnaire as a formal part of the KEP, and makes it required when targeting the enhancement at a release.
A follow up PR in k/community will remove the questionnaire from there and point folks here.
/sig release
/assign @wojtek-t @deads2k @justaugustus
=> Add PRR questionnaire to KEP template, require for targeting

keps/sig-api-machinery/1623-standardize-conditions/README.md, keps/sig-api-machinery/1623-standardize-conditions/kep.yaml
While many Kuberentes APIs have `.status.conditions`, the schema of `condition` varies a lot between them. There is very little commonality at the level of serialization, proto-encoding, and required vs optional. Conditions are central enough to the API to make a common golang type with a fixed schema. The schema can be a strong recommendation to all API authors.
=> provide recommended .status.conditions schema

keps/sig-auth/20190607-certificates-api.md
Update the signerName definitions to clarify x509 extension handling (matches docs released with 1.18 at https://kubernetes.io/docs/reference/access-authn-authz/certificate-signing-requests/#kubernetes-signers)
* Enumerate specific SAN types (Email, URI, IP, DNS)
* `kubernetes.io/kube-apiserver-client` ensures the request is for [client key usage](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/certificates/signer/signer.go#L148-L149), and [passes through requested extensions](https://github.com/kubernetes/kubernetes/blob/release-1.18/pkg/controller/certificates/authority/authority.go#L70-L82), which get truncated to [just  URI/Email/IP/DNS SANs by the signer](https://github.com/kubernetes/kubernetes/blob/release-1.18/pkg/controller/certificates/authority/policies.go#L3 …
=> Update x509 extension handling to match signerName implementation

keps/sig-auth/20190607-certificates-api.md
/sig auth
/assign @mikedanese @deads2k 
/cc @munnerz
=> CSR v1 details, Approved/Denied/Failed conditions

keps/NNNN-kep-template/README.md, keps/NNNN-kep-template/kep.yaml, keps/sig-storage/1412-immutable-secrets-and-configmaps/kep.yaml, keps/sig-storage/1432-volume-health-monitor/kep.yaml, pkg/kepval/keps/proposals.go, pkg/kepval/keps/proposals_test.go
The name is intended to refer to rolling back the enablement of the
feature, but can cause confusion. It can be mixed up with what the
consequences of rolling back the version are, rather than just the
enablement.
=> Change PRR rollback-supported to disable-supported

keps/sig-auth/266-kubelet-client-certificate-bootstrap-rotation/README.md, keps/sig-auth/266-kubelet-client-certificate-bootstrap-rotation/kep.yaml
Convert [community proposal](https://github.com/kubernetes/community/pull/768) to KEP format, add additional KEP sections (test plan, skew considerations, graduation criteria)
The feature was implemented in the 1.4-1.8 timeframe, stabilized in the 1.8-1.11 timeframe, and has been waiting in beta status for the CSR API to graduate to v1. 
This KEP is primarily to document the design of the already-implemented feature, and establish graduation criteria for flipping the feature gate from Beta to GA in 1.19.
/sig auth node
/cc @mikedanese @smarterclayton @johnbelamaric
=> Retroactive KEP-266: Kubelet client certificate bootstrap/rotation

keps/sig-api-machinery/20200309-consistent-resource-versions-semantics.md, keps/sig-api-machinery/20200309-consistent-resource-versions-semantics/README.md, keps/sig-api-machinery/20200309-consistent-resource-versions-semantics/kep.yaml
Per discussion in [SIG api-machinery bi-weekly meeting a couple weeks ago](https://docs.google.com/document/d/1x9RNaaysyO0gXHIr1y50QFbiL1x8OWnk2v3XnrdkT5Y/edit#bookmark=id.3kvpricxohe8), we like to make the semantics of resource version consistent for LIST requests.
Working prototype: [jpbetz/rv-semantics](https://github.com/kubernetes/kubernetes/compare/master...jpbetz:rv-semantics)
/cc @cheftako @lavalamp @deads2k @liggitt
=> KEP: Make resource version semantics consistent

keps/sig-network/20190603-EndpointSlice-API.md
The most notable addition here is a new concept of EndpointsMirroring. This will ensure that custom Endpoints are mirrored to EndpointSlices automatically. Beyond this addition, this clarifies the roll out plan and updates anything that has become outdated.
/sig network
/cc @liggitt @freehan @thockin
=> Updating EndpointSlice KEP to include EndpointsMirroring and plans for 1.19 and beyond

keps/sig-network/20191227-app-protocol.md
It ended up requiring a few more steps to add a new field to a v1 API. I've added those in the proposed roadmap here.
/sig network
=> Adding proposed roadmap to AppProtocol KEP

OWNERS_ALIASES
ptone has stepped down as a lead
ref: https://github.com/kubernetes/community/pull/4778
=> Update wg-iot-edge leads

README.md, keps/README.md
Adds a brief description of the kep number to the faq.
Also updates a few references to sig-pm in the root README.
/assign @justaugustus @johnbelamaric @jeremyrickard 
Fixes: https://github.com/kubernetes/enhancements/issues/1721
=> Add note regarding KEP number to faq

keps/sig-cluster-lifecycle/kubeadm/1739-customization-with-patches/README.md, keps/sig-cluster-lifecycle/kubeadm/1739-customization-with-patches/kep.yaml
this KEP comes with a proposal that replaces the existing Alpha feature for patching using Kustomize.
note that the new KEP template format is used.
xref:
https://github.com/kubernetes/kubeadm/issues/2046
https://github.com/kubernetes/enhancements/issues/1739
=> kubeadm: add KEP for customization with patches

keps/NNNN-kep-template/README.md
When people write KEPs with no line breaks, it's harder to review them because you can only add comments at the paragraph level rather than (approximately) the sentence level. So explicitly recommend line breaks.
(Not sure this is the best place to do that...)
=> template: recommend line breaks

keps/sig-auth/1687-hierarchical-namespaces-subproject/README.md, keps/sig-auth/1687-hierarchical-namespaces-subproject/kep.yaml
A KEP for the submission of hierarchial namespace controller as a subproject of sig-auth. The filename and status represents a provisional draft until discussed at the sig-auth meeting on April 15th 2020. 
cc: @adrianludwin @tashimi  @srampal
=> Initial proposal for hierarchial namespace controller subproject

keps/sig-scheduling/785-scheduler-component-config-api/README.md, keps/sig-scheduling/785-scheduler-component-config-api/kep.yaml
And add Production Readiness Questionnaire
ref #1451
=> Update Scheduler Component Config KEP to new template

keps/sig-storage/1710-selinux-relabeling/README.md, keps/sig-storage/1710-selinux-relabeling/kep.yaml
This KEP tries to speed up the way how volumes (incl. persistent volumes) are made available to Pods on systems with SELinux in enforcing mode.
Current way includes recursive relabeling of all files on a volume before a container can be started. This is slow for large volumes.
Familiarity with [`fsGroupChangePolicy` KEP is suggested](https://github.com/kubernetes/enhancements/blob/master/keps/sig-storage/20200120-skip-permission-change.md)
=> Add KEP for SELinux label change

keps/sig-storage/1472-storage-capacity-tracking/README.md, keps/sig-storage/1472-storage-capacity-tracking/kep.yaml
This KEP explains how CSI drivers can expose how much capacity a storage system has available via the API server. This information can then be used by the Kubernetes Pod scheduler to make more intelligent decisions when placing:
- pods with ephemeral inline volumes
- pods with persistent volumes that haven't been been created yet (`WaitForFirstConsumer` binding mode)
Enhancement issue: https://github.com/kubernetes/enhancements/issues/1472
=> Storage Capacity Constraints for Pod Scheduling

keps/sig-storage/1698-generic-ephemeral-volumes/README.md, keps/sig-storage/1698-generic-ephemeral-volumes/kep.yaml
This describes an alternative, more general approach for specifying volumes inside a pod spec ("inline"), with a lifecycle of the volumes that is tied to the lifecycle of the pod ("ephemeral").
Enhancement issue: https://github.com/kubernetes/enhancements/issues/1698
=> generic ephemeral inline volumes KEP

keps/sig-storage/20200508-move-utils-mount-2staging.md
To solve some maintenance issues mentioned in the KEP, we are requesting to move utils/mount package into k/k repo so that we can better manage and test the package.
sig/storage sig/architecture sig/testing
=> Request to move vendored utils/mount library to staging

keps/sig-scheduling/895-pod-topology-spread/README.md, keps/sig-scheduling/895-pod-topology-spread/kep.yaml
=> Add Pod Topology Spread KEP to new template

keps/sig-api-machinery/20190226-network-proxy.md
KMS connects via unix domain sockets (UDS). Since this is local, it should not be a part egress traffic.
ImagePolicyWebhook has been in alpha for two years without active development to beta. There was also talk that it may be deprecated and I believe it should be excluded from the network proxy beta requirements.
=> Remove KMS and image policy wh from network proxy beta requirements

keps/sig-storage/1790-recover-resize-failure/README.md, keps/sig-storage/1790-recover-resize-failure/kep.yaml
Add a KEP for recovering from resize failure.
xref: https://github.com/kubernetes/enhancements/issues/1790
/assign @msau42 @jsafrane @saad-ali 
cc @kubernetes/sig-storage-api-reviews
=> Add KEP for recovering from volume expansion failure.

keps/sig-storage/1682-csi-driver-skip-permission/README.md, keps/sig-storage/1682-csi-driver-skip-permission/kep.yaml
Currently before bind mounting a CSI volume for a Pod, we use imprecise heuristics,
such as presence of fsType on the PVC to determine if the volume supports fsGroup based
permission change. These heuristics are known to be fragile, and cause problems with different
storage types.
This proposal is to include a new field, `csidriver.spec.SupportsFSGroup`, that can define if a CSI Driver supports fsGroup based permission changes.
Addresses [issue 1682](https://github.com/kubernetes/enhancements/issues/1682).
=> Include KEP for CSI Drivers indicating support of fsGroup

keps/sig-node/20190717-seccomp-ga.md
Amendments around RuntimeProfile and LocalhostProfile on Tim's [initial KEP](https://github.com/kubernetes/enhancements/pull/1148). The goal remains unchanged: to do the _bare minimum_ to clean up the feature, without blocking future enhancements.
/sig-node
/sig-auth
/assign @liggitt @dchen1107 @derekwaynecarr @tallclair 
/cc @jessfraz
=> Seccomp GA

keps/sig-multicluster/1645-multi-cluster-services-api/README.md, keps/sig-multicluster/1645-multi-cluster-services-api/kep.yaml
Create a provisional KEP for MC services based on SIG conversations and
this original doc: http://bit.ly/k8s-mc-svc-api-proposal
=> Multi-Cluster Services API

keps/sig-api-machinery/20190228-priority-and-fairness.md
/kind feature
this pull is for discussing necessary criterias of moving toward beta for APIPriorityAndFairness
/cc @lavalamp @deads2k @MikeSpreitzer
=> Documenting APIPriorityAndFairness beta criteria

keps/sig-instrumentation/383-new-event-api-ga-graduation/README.md
the [383-new-event-api-ga-gradution](https://github.com/kubernetes/enhancements/blob/master/keps/sig-instrumentation/383-new-event-api-ga-graduation/README.md) introduce an [API Change](https://github.com/kubernetes/enhancements/blob/master/keps/sig-instrumentation/383-new-event-api-ga-graduation/README.md#api-changes) in Event Object. 
And the [related-changes](https://github.com/kubernetes/enhancements/blob/master/keps/sig-instrumentation/383-new-event-api-ga-graduation/README.md#other-related-changes) section defines a **event.reportingComponent** field name witch is defined as **reporingController** in Event struct.
Maybe this is a typo?
=> fix(typo): replace reportingComponent with reportingController

keps/NNNN-kep-template/kep.yaml, pkg/kepval/keps/proposals.go, pkg/kepval/keps/proposals_test.go
This would make easier to build tooling to e.g. find keps without approver assigned.
/cc @justaugustus
=> Explicit PRR Approver field in kep.yaml

keps/sig-instrumentation/383-new-event-api-ga-graduation/README.md, keps/sig-instrumentation/383-new-event-api-ga-graduation/kep.yaml
A new PRR questionnaire section was added to the KEP template as a required section in #1620, so this pull request is to add this section to align with that requirement and answer all questions regarding the fact that we're targeting GA graduation in 1.19.
=> Add PRR questionnaire section to New Event API KEP

cmd/kepval/main.go, cmd/kepval/main_test.go
Make run() accept an io.Writer. When invoking the application
from the command line pass os.Stderr to it.
For unit tests pass a bytes.Buffer pointer.
Before:
exit code was 1 and not 0. Please see output.
After:
exit code was 1 and not 0. Output:
some-kep-path/kep.yaml has an error: "yaml: unmarshal errors:\n
line 26: field "foo" not found in type keps.Proposal"
=> kepval: surface the reason for errors during KEP validation

keps/sig-cloud-provider/providers/0020-cloud-provider-alibaba-cloud.md
the error url is: https://github.com/kubernetes/community/blob/master/keps/sig-cloud-provider/0018-testgrid-conformance-e2e.md
the right url is: https://github.com/kubernetes/enhancements/blob/master/keps/sig-cloud-provider/0018-testgrid-conformance-e2e.md
=> modify the error url of cloud-provider

keps/sig-network/20190714-IPv6-beta-proposal.md
the error url is:
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.9.md#ipv6
https://github.com/kubernetes/kubernetes/blob/release-1.9/CHANGELOG-1.9.md#ipv6
=> modify the error url of ipv6

keps/sig-contributor-experience/0007-20180403-community-forum.md
the error url is:
https://github.com/kubernetes/community/blob/master/keps/sig-contributor-experience/0005-contributor-site.md
https://github.com/kubernetes/enhancements/blob/master/keps/sig-contributor-experience/0005-contributor-site.md
=> modify the error url of contributor

keps/sig-autoscaling/0001-container-resource-autoscaling.md
The KEP has been [implemented](https://github.com/kubernetes/kubernetes/pull/90691). Also updated the test plan.
=> Mark KEP implementable and add test plan

keps/sig-node/0035-20190130-topology-manager.md
This proposal adds an API to allow a device plugin to forward a "preferred allocation" to the `devicemanager` so it can incorporate this information into its allocation decisions. It leaves the `devicemanager` in charge of making the final allocation, but gives the plugin the chance to help influence it more directly.
Using this new API call, the `devicemanager` will call out to a plugin at pod admission time, asking it for a preferred device allocation of a given size from a list of available devices. One call will be made per-container for each pod.
The list of available devices passed to the `GetPreferredAllocation()` call do not necessarily match the full list of available devices on the system. Instead, the `devicemanager` treats the `GetPreferredAllocation()` call as a "last-level" …
=> Add proposal for GetPreferredAllocation() to TopologyManager KEP

keps/sig-scheduling/1819-scheduler-extender/README.md, keps/sig-scheduling/1819-scheduler-extender/kep.yaml
ref: #1819
The main content is converted from [scheduler extender design proposal in community repo](https://github.com/cofyc/community/blob/master/contributors/design-proposals/scheduling/scheduler_extender.md) with some updates:
- update Filter/Prioritize/Bind interface API to latest code
- add Preempt API definitions
=> Convert scheduler extender design proposal in community repo to a KEP

keps/sig-release/1498-kubernetes-yearly-support-period/README.md, keps/sig-release/1498-kubernetes-yearly-support-period/kep.yaml
Discussion with SIGs over the past months shows a general consensus this
KEP is implementable and also that the proposal has increased in being desired
by our project's consumers as they struggle with operational
complexities in 2020 relative to COVID.
As it stands the KEP and WG LTS had focused on starting with the
1.19 release, but additional recent discussion points at a desire
for the implementation to include also 1.18, 1.17, and 1.16.
Signed-off-by: Tim Pepper <tpepper@vmware.com>
=> WG LTS: mark annual support cycle KEP implementable

keps/sig-cli/kustomize-secret-generator-plugins.md
the error url is: https://github.com/kubernetes-sigs/kustomize/tree/master/pkg/target
the right url is: https://github.com/kubernetes-sigs/kustomize/tree/master/api/internal/target
=> modify the error url of kustomize

keps/sig-scheduling/1819-scheduler-extender/README.md
ref: https://github.com/kubernetes/enhancements/issues/1819
addresses the option 3 API change proposed in https://github.com/kubernetes/kubernetes/issues/91281#issuecomment-632367930
=> scheduler/extender: Extend ExtenderFilterResult to include UnschedulableAndUnresolvable nodes

keps/sig-node/0035-20190130-topology-manager.md
- Support pod level resource alignment
- to achieve higher performance when deploying a pod that has inter-connected containers to work, for example:
```
A Pod has two containers, container1 runs a DPDK application with cpu pinning ,sr-iov nic, hugepages, memory.
Container2 runs in-memory database (with exclusive cpu and memory) and DPDK app of container1 accesses this database over shared memory.
- All resources of both containers should be located on the same NUMA node.
=> NUMA locality of memory and hugepages will be aligned by Memory Manager in the future.
=> We need pod-level-single-numa-node policy to bind all containers in the Pod to the same NUMA node to avoid performance degradation.      
A Pod has two containers, those containers run a DPDK application with cpu pinning, sr-iov …
```
=> Update Topology Manager to support pod-level resource alignment

keps/sig-cli/1802-kustomize-components.md
This enhancement proposal introduces components, a new kind of
Kustomization that allows users to define reusable kustomizations.
Main discussion: kubernetes-sigs/kustomize#1251
User story that spawned this KEP: kubernetes-sigs/kustomize#2438
=> Add Kustomize components KEP

keps/sig-network/1669-graceful-termination-local-external-traffic-policy/README.md, keps/sig-network/1669-graceful-termination-local-external-traffic-policy/kep.yaml, keps/sig-network/1672-tracking-terminating-endpoints/README.md, keps/sig-network/1672-tracking-terminating-endpoints/kep.yaml
This PR adds two related, but separate KEPS:
Adds a field `terminating` to the `endpointCondition` field in the EndpointSlice API. This allows consumers of the API to know when a pod is terminating in case extra steps are required during a pod's graceful termination period.  One use-case (in addition to the one below) is to simplify the graceful termination logic in the IPVS proxier, more details in the PR.
Uses the proposed changes to EndpointSlice API above to enable zero downtime deployments for Services with Type=LoadBalancer/NodePort and ExternalTrafficPolicy=Local. This is mainly accomplished by redirecting traffic to ready terminating endpoints if all endpoints on a given node are terminating.
Continuing discussion from https://github.com/kubernetes/kubernetes/issues/85643#issuecomm …
=> Graceful Termination for External Traffic Policy Local

keps/sig-network/1860-kube-proxy-IP-node-binding/README.md, keps/sig-network/1860-kube-proxy-IP-node-binding/kep.yaml
First draft of KEP to allow an option to change kube proxy behaviour regarding the LoadBalancer IPs
Signed-off-by: Patrik Cyvoct <patrik@ptrk.io>
=> Make Kubernetes aware of the LoadBalancer behaviour

keps/sig-network/20180612-ipv4-ipv6-dual-stack.md
updates dualstack kep as per comments found here https://github.com/kubernetes/kubernetes/pull/86895 in prep for dualstack next phase.
@thockin + @aojea + @lachie83 - I think need to revise the `CoreDNS Operation` section. The `resolution` is a function of how the client asks for address. DNS Servers typically respond with all  records they have about name irrespective of protocol version used to make the query.
=> dualstack services

keps/sig-multicluster/1645-multi-cluster-services-api/README.md, keps/sig-multicluster/1645-multi-cluster-services-api/kep.yaml
- Adds initial pass at multi-cluster Headless support based on previous weekly meeting & PR discussions.
- Reorganizes behavioral spec based on discussion from previous PR.
- Adds test plan, upgrade story, graduation criteria.
- Moves derived cluster state on `ServiceImport` to `Status`.
- Removes service topology and dual-stack related fields as both are still in flux.
=> MCS: Add Headless support and graduation criteria

keps/sig-storage/1698-generic-ephemeral-volumes/README.md
This is meant to explain better why the change is useful and cannot be
solved differently.
This proposal and various alternatives had been discussed, but the KEP didn't capture all of that.
/cc @smarterclayton
=> generic ephemeral volume: reword introduction, expand drawbacks and alternatives

keps/sig-api-machinery/0006-apply.md
This change updates the server-side apply KEP with the strategy for upgrading client-side `kubectl apply`'s `last-applied-configuration` annotation to server-side apply, as originally provided by @jennybuckley in [Upgrade pathway: Client Side Apply to Server Side Apply](https://docs.google.com/document/d/1_YKsMttYZmIw2cSg-jH5PExHjA7FUyALAgHuXDDBcFY/edit#heading=h.9ip5iwufl35h).
WIP here: https://github.com/kubernetes/kubernetes/pull/84134
Umbrella: https://github.com/kubernetes/kubernetes/issues/73723
/wg apply
=> Update Server-Side Apply KEP with upgrade strategy from client-side apply

keps/sig-network/1453-ingress-api/README.md
With Ingress going to v1 in 1.19, we'll need to wait 3 releases (1.19, 1.20, and 1.21) before removing v1beta1 APIs.
/sig network
/cc @cmluciano 
=> Moving Ingress v1beta1 deprecation to 1.22

keps/sig-network/1864-disable-lb-node-ports/README.md, keps/sig-network/1864-disable-lb-node-ports/kep.yaml
Allow node ports to be disabled for Service Type=LoadBalancer as per https://github.com/kubernetes/kubernetes/issues/69845. 
This is useful for VIP-based implementations of Service Type=LoadBalancer where the node port is not needed. The two largest motivations for this feature is:
* unnecessarily exposed ports can fail regulatory/compliance requirements
* the number of loadbalancers is limited by the # of available node ports.
=> optionally disable node ports for Service Type=LoadBalancer

keps/sig-node/1867-disable-accelerator-usage-metrics/README.md, keps/sig-node/1867-disable-accelerator-usage-metrics/kep.yaml
What type of PR is this?
/kind feature
What this PR does / why we need it: Adds the "Disable AcceleratorUsage Metrics" KEP
TLDR: Add a FeatureGate to Disable the AcceleratorUsage Metrics collected by Kubelet.
Kubelet should no longer be collecting metrics from devices as the path decided by Sig-node is to use the pod resources API and have device vendors expose metrics through their own metrics container.
Some context that I left out of the KEP, because Kubelet has an open handle on the NVIDIA driver, this breaks any infrastructure interactions (e.g: Removing or Updating the driver) with the NVIDIA driver. In other words any actions related to the NVIDIA driver cannot be taken without killing the kubelet.
/cc @dashpole
/sig node
/stage alpha
Does this PR introduce a user-facing change?: …
=> Disable AcceleratorUsage Metrics initial kep

keps/sig-apps/0753-sidecarcontainers.md
This commit just marks the KEP as provisional, adds a dependency on the
kubelet node shutdown work that is coming and, while we are there,
renames it to use the existing issue tracking number.
Signed-off-by: Rodrigo Campos <rodrigo@kinvolk.io>
As we talked during last SIG-node meeting (June 23 2020), this updates the sidecar KEP. As we talked too, other PRs will follow to highlight some tricky cases I've identified in this KEP (so we can discuss what we want to do and address all concerns), other more general alternatives and why they were discarded, etc. For that reason, all checks are removed now, as I understand we want to review this in detail again and adjust.
We didn't talk about how the dependency should be, so here I propose this (better explained in the PR):  sidecar to graduate …
=> sidecar: Add dependency and mark as provisional

keps/sig-auth/541-external-credential-providers/README.md
Signed-off-by: Andrew Keesler <akeesler@vmware.com>
This change comes from the website docs PR: https://github.com/kubernetes/website/pull/22441.
The belief here is that the proposed `installHint` doc makes it easier for website docs readers to understand what the `installHint` field does. It also nicely parallels the `InstallHint` Go field doc.
It also also introduces valid YAML to the `kubeconfig` example.
CC @enj
=> Update installHint doc upon feedback in user-facing docs

keps/sig-api-machinery/20190228-priority-and-fairness.md
The existing design for Fair Queuing for Server Requests is broken.  It aims for equal division of capacity among non-empty queues rather than the max-min fair result.  This PR revises the design, to achieve max-min fairness.
=> Make Fair Queuing for Server Requests achieve max-min fairness

keps/0001-kubernetes-enhancement-proposal-process.md
It appears that the []() syntax doesn't work inside the `<b>` tags. Use `href`
instead.
=> keps/0001: Fix link to template

keps/sig-architecture/1659-standard-topology-labels/README.md, keps/sig-architecture/1659-standard-topology-labels/kep.yaml
Kubernetes has always taken the position that "topology is arbitrary", and
designs dealing with topology have had to take that into account.  Even so, the
project has two commonly assumed labels - `topology.kubernetes.io/region` and
`topology.kubernetes.io/zone` - which are used in many components, generally
hard-coded and not extensible.  Those labels have relatively well understood
meanings, and (so far) have been sufficient to represent what most people need.
This KEP proposes to declare those labels, and possibly one more, as "standard"
and give them more well-defined meanings and semantics.  APIs that handle
topology can still handle arbitrary topology keys, but these common ones may be
handled automatically.
/cc @robscott 
/cc @freehan
/cc @jeremyot
/cc @andrewsykim 
/cc @dcbw 
/cc …
=> Add KEP 1659 - standard topology labels

keps/sig-node/1867-disable-accelerator-usage-metrics/README.md, keps/sig-node/1867-disable-accelerator-usage-metrics/kep.yaml
- Marks KEP as implementable
- Updates the reviewers and approvers fields with sig-node reviewers and approvers
- Fix typo in the test plan (since we only have a single test)
Signed-off-by: Renaud Gaubert <rgaubert@nvidia.com>
=> Mark accelerator-usage-metrics as implementable

keps/sig-cloud-provider/20190729-building-without-in-tree-providers.md
fixes https://github.com/kubernetes/enhancements/issues/1179#issuecomment-615410714
=> mark building without in-tree providers implemented

keps/sig-architecture/960-conformance-behaviors/README.md, keps/sig-architecture/960-conformance-behaviors/kep.yaml
As discussed in the [June 30 Conformance Meeting](https://docs.google.com/document/d/1W31nXh9RYAb_VaYkwuPLd1hFxuRX3iU0DmaQ4lkCsX8/edit#heading=h.hyqvyh9r34), abandoning this KEP.
Future PRs will remove the dead code.
=> Abandon Conformance Behaviors KEP

keps/sig-instrumentation/20181106-kubernetes-metrics-overhaul.md
=> Mark SIG Instrumentation metrics overhaul KEP as implemented

keps/sig-api-machinery/1904-efficient-watch-resumption/README.md, keps/sig-api-machinery/1904-efficient-watch-resumption/kep.yaml
Ref https://github.com/kubernetes/enhancements/issues/1904
=> Mark efficient watch resumption KEP as implementable

keps/sig-apps/0753-sidecarcontainers.md
In-page link was [text][url] instead of [text](url).
Signed-off-by: Tim Pepper <tpepper@vmware.com>
=> trivial: fix broken link markdown

keps/sig-multicluster/1645-multi-cluster-services-api/README.md
- Add implementation plan and naming to graduation criteria
- Change ServiceImport.Spec.IP to list (currently limited at 1) to
align with dual stack plans.
=> Update graduation criteria and dual stack prep

pkg/kepctl/query.go, pkg/kepval/keps/validations/yaml.go
This allows passing one or more regexp instead of strings to the `kepctl query` command. This makes discoverability way better. For example, with this and the PRR PR I have out, I could use `kepctl query --sig '.*' --prr '@johnbelamaric' --include-prs --status provisional` to get a list of all Provisional KEPs for which I am assigned as a PRR reviewer.
However, it means the CLI tool only will work if you are online, since the SIG list is loaded in the package `init` of the validations module. Maybe we should embed the list as of the build time?
=> Use a regexp instead of strings for SIGs in query

keps/sig-storage/177-volume-snapshot/tighten-validation-webhook-crd.md
Following the naming convention for finalizers at: https://github.com/kubernetes-csi/external-snapshotter/blob/c436f5ccb3c1942890caf8c6b839678613d577e7/pkg/utils/util.go#L62
=> Change k8s.io to kubernetes.io in the label key for invalid objects.

OWNERS_ALIASES, keps/sig-scheduling/34-20180703-coscheduling.md
Reported by @andrewsykim and blocking https://github.com/kubernetes/enhancements/pull/1960.
I've also updated the OWNERS_ALIASES here to be in sync w/ k/community: https://github.com/kubernetes/community/blob/eaac6a1fe01a205d38af9a673d3d57be9357803e/OWNERS_ALIASES
/assign @jeremyrickard @andrewsykim 
FYI @k82cn @bsalamat @vishh
=> Drop the now-archived WG Machine Learning from KEP metadata

keps/sig-release/1733-release-notes/README.md, keps/sig-release/1733-release-notes/kep.yaml
This update for the release notes KEP should layout the current state of
the implementation.
Refers to https://github.com/kubernetes/enhancements/issues/1733
/cc @puerco @justaugustus @jeefy
=> Update release-notes KEP to reflect the current state

keps/sig-node/1967-size-memory-backed-volumes/README.md, keps/sig-node/1967-size-memory-backed-volumes/kep.yaml
Improve portability of pods that consume memory backed volumes by decoupling the size of the volume from the node that runs the pod.
=> Size memory backed volumes

OWNERS
The label being applied to every PR has made it difficult to triage what items actually belong to sig-arch.
/assign @jeremyrickard @johnbelamaric @justaugustus
=> Remove root OWNERS applied sig-arch label

keps/sig-auth/20190607-certificates-api.md, keps/sig-auth/266-kubelet-client-certificate-bootstrap-rotation/README.md, keps/sig-auth/266-kubelet-client-certificate-bootstrap-rotation/kep.yaml
https://github.com/kubernetes/enhancements/issues/1513
https://github.com/kubernetes/enhancements/issues/266
=> Mark CSR GA KEPs as implemented

keps/sig-node/20190129-pid-limiting.md
Promote pid limiting features to GA.
Feature has been enabled and on by default since 1.15.
Both features have node_e2e testing coverage.
Features:
- SupportNodePidsLimit
- SupportPodPidsLimit
More granular ability to apply pid limits per pod can be evaluated in future.
=> Promote PidLimits to GA

keps/sig-release/1498-kubernetes-yearly-support-period/README.md, keps/sig-release/1498-kubernetes-yearly-support-period/kep.yaml
This KEP has been implemented for 1.19 and newer.
Signed-off-by: Tim Pepper <tpepper@vmware.com>
=> LTS: mark 1 year support KEP 1498 "implemented"

ISSUE_TEMPLATE.md, keps/README.md
Before KEPs are created, they are intended to be discussed and socialized with the owning SIG. This field adds a discoverability point between the tracking issue and the original conversation around the KEP.
/hold
/cc @LappleApple @kikisdeliveryservice 
=> Add discussion link to issue template

keps/sig-api-machinery/1965-kube-apiserver-identity/README.md, keps/sig-api-machinery/1965-kube-apiserver-identity/kep.yaml
This KEP proposes assigning a unique ID to each kube-apiserver in an HA cluster. 
/assign @caesarxuchao @lavalamp @MikeSpreitzer @deads2k 
Tracking issue: https://github.com/kubernetes/enhancements/issues/1965. Original [proposal](https://docs.google.com/document/d/1ed7miqlFY7-9lZxE7gzoyx_MFQCtFEDqtcKMpaAmHys/edit?usp=sharing).
=> Adding KEP for kube-apiserver identity

keps/sig-auth/541-external-credential-providers/README.md
Signed-off-by: Andrew Keesler <akeesler@vmware.com>
* The goal of these updates is to reach consensus on how best to wire cluster info into exec credential providers so that we can wrap up and merge the implementation (https://github.com/kubernetes/kubernetes/pull/91192).
* These updates come from feedback on https://github.com/kubernetes/kubernetes/pull/91192.
* https://github.com/kubernetes/kubernetes/pull/91192/files#r445956896 (`ProxyURL`)
* https://github.com/kubernetes/kubernetes/pull/91192/files#r445957437 (`client.authentication.k8s.io/exec `)
@liggitt - would you be willing to submit your opinion about these updates? I reach out to you because you and @enj discussed a proper superset of these changes in https://github.com/kubernetes/kubernetes/pull/91192. I understand this is not …
=> Update exec credential provider KEP with feedback from cluster info PR

go.sum, pkg/kepctl/kepctl.go, pkg/kepctl/kepctl_test.go, pkg/kepctl/query.go
Previously, it would give errors as it could not find the files. It assumed they were in the root of the SIG's KEP directory.
=> kepctl: fix query when KEPs are nested in directories

keps/sig-node/20190717-seccomp-ga.md
The implementation is done for v1.19.0 and we now can mark this KEP as
`implemented`.
/cc @tallclair @pjbgf @hasheddan
=> Update seccomp KEP as implemented

keps/sig-instrumentation/383-new-event-api-ga-graduation/README.md, keps/sig-instrumentation/383-new-event-api-ga-graduation/kep.yaml
The new Events API has been graduated to GA  in 1.19, so mark this KEP as implemented.
Also add implementation PRs to the Implementation History section for the record.
=> Update status of New Events API KEP to implemented

keps/sig-contributor-experience/1553-issue-triage/README.md
The rest of the KEP was updated to include PRs as in scope for the issue-triage label, but it was neglected in the specific design details.
/cc @nikhita @cblecker
=> KEP-1553: Include PRs as in scope in design details

keps/sig-node/20190717-seccomp-ga.md, keps/sig-node/20191205-container-streaming-requests.md, keps/sig-node/277-ephemeral-containers/README.md, keps/sig-node/277-ephemeral-containers/kep.yaml
This migrates the Ephemeral Containers KEP to the new directory-based format. No changes have been introduced, except:
1. I added a new summary of the proposal in the **Proposal** section, as required by the new template
2. I moved the API details from **Proposal** to **Design Details**
3. I added conformance test graduation criteria, as required by the new template.
4. I have not filled in new sections of the template, most notably the **PRR** sections.
I'd like to merge this as a separate PR to make it easier to review future PRs, which will actually propose new behavior or content changes.
=> KEP-277: Switch Ephemeral Containers KEP to directory-based format

keps/sig-cloud-provider/azure/20190125-out-of-tree-azure.md
/assign @craiglpeters @andyzhangx
=> Update Out-of-Tree Azure Cloud Provider KEP

keps/sig-node/1898-hardened-exec/README.md, keps/sig-node/1898-hardened-exec/kep.yaml
Harden exec requests against SSRF vulnerabilities. See https://github.com/kubernetes/kubernetes/issues/92914 for motivation.
For https://github.com/kubernetes/enhancements/issues/1898.
/sig node api-machinery
/area security
/cc @liggitt @cjcullen @mtaufen
=> KEP: hardened exec requests

keps/sig-storage/695-skip-permission-change/kep.yaml
Fixes beta target of the kep.
cc @kubernetes/sig-storage-pr-reviews
=> Change beta target for skipping volume permission change KEP

keps/sig-node/606-compute-device-assignment/README.md, keps/sig-node/606-compute-device-assignment/kep.yaml, keps/sig-node/compute-device-assignment.md
Hello!
This PR updates the Compute Devices KEP to detail the thought process and plan to graduate the PodResources feature to G.A.
Some of the considerations come from the new KEP template which were helpful in pointing some of things that were missing from the current implementation, namely:
- Metrics which will be added shortly (`pod_resources_requests_total`)
- Rate/Memory/Resource Limiting of the service which will also be added shortly
Refer to the enhancement issue here: https://github.com/kubernetes/enhancements/issues/606
Finally this PR updates the KEP to follow the new template. Note that I'm still fairly new with the process and might have overlooked some fields or mis-answered them because of a lack of understanding :) 
/cc @dashpole 
/sig node
/stage stable
I hope this will …
=> G.A Plan for Compute Devices + Updated to follow KEP template

keps/sig-node/1867-disable-accelerator-usage-metrics/README.md, keps/sig-node/1867-disable-accelerator-usage-metrics/kep.yaml
Hello there!
This PR updates the DisableAcceleratorUsageMetrics KEP with the following changes:
- Graduates the KEP to beta
- Updates the KEP history
- Updates the KEP checklist
Signed-off-by: Renaud Gaubert <rgaubert@nvidia.com>
/sig node
/cc @derekwaynecarr @dchen1107 @dashpole
=> Graduate DisableAcceleratorUsageMetrics to beta

keps/sig-windows/1001-windows-cri-containerd/README.md, keps/sig-windows/1001-windows-cri-containerd/kep.yaml
Adding kep.yaml for windows-cri-containerd KEP
https://github.com/kubernetes/enhancements/issues/1001
=> Adding kep.yaml for windows-cri-containerd KEP

keps/sig-node/1797-configure-fqdn-as-hostname-for-pods/README.md, keps/sig-node/1797-configure-fqdn-as-hostname-for-pods/kep.yaml
This update should contain all information required for the KEP to be able to graduate the feature to at least beta.
=> Update FQDN Hostname KEP to beta

keps/sig-node/2000-graceful-node-shutdown/README.md, keps/sig-node/2000-graceful-node-shutdown/kep.yaml
Enhancement issue: https://github.com/kubernetes/enhancements/issues/2000
=> Add node shutdown KEP

keps/sig-node/1972-kubelet-exec-probe-timeouts/README.md, keps/sig-node/1972-kubelet-exec-probe-timeouts/kep.yaml
Kubelet today does not respect exec probe timeouts. This is an unexpected behavior
since the timeout value is supported in the Container Probe API. Because exec probe timeouts
were never respected by kubelet, a new feature gate `ExecProbeTimeouts` will be introduced
so users have an easy way to revert back if the newly introduced probe timeout results
in unexpected behavior.
KEP issue: https://github.com/kubernetes/enhancements/issues/1972
=> KEP-1972: kubelet exec probe timeouts

keps/sig-node/1797-configure-fqdn-as-hostname-for-pods/README.md
Forgot to add the check to Production Readiness approval in my previous PR https://github.com/kubernetes/enhancements/pull/1962.
=> Adding check for readiness approval in FQDN Hostname KEP 

keps/sig-scheduling/1258-default-pod-topology-spread/README.md, keps/sig-scheduling/1258-default-pod-topology-spread/kep.yaml
Refs #1258 
Includes:
- Updated API to account for disabling defaults
- Pending implementation details
- Production Readiness Questionnaire
=> DefaultPodTopologySpread graduation to Beta

keps/sig-apps/1591-daemonset-surge/README.md, keps/sig-apps/1591-daemonset-surge/kep.yaml
Many infrastructure components require DaemonSets to place pods on
each node, but the current update strategies limit end users from
minimizing disruption during updates. It should be possible to
surge daemonsets if a user requests it to allow handoff from one
running pod to another, like Deployments.
Extracts the specific Surge portion from #1140.
=> DaemonSets should allow MaxSurge to minimize workload downtime during upgrade

keps/sig-node/1898-hardened-exec/README.md, keps/sig-node/1898-hardened-exec/kep.yaml
I decided to add an additional feature gate, `DeprecatedKubeletStreamingAPI`, and move the backwards-incompatible Kubelet changes behind this feature gate. This feature gate will not follow the normal gradual rollout, since these APIs are not intended to be user-facing, but will provide an escape hatch for someone depending on them today.
I also filled out the PRR, and marked the KEP as implementable.
Forr PRR approval:
/assign @deads2k 
For implemantable:
/assign @derekwaynecarr 
/milestone v1.20
For https://github.com/kubernetes/enhancements/issues/1898
=> Hardened Exec Requests: Fill in PRR, add Kubelet feature gate, mark implementable

keps/sig-api-machinery/1929-built-in-default/README.md, keps/sig-api-machinery/1929-built-in-default/kep.yaml
Create KEP for built-in defaulting, along with mechanisms so that defaulting can behave the same for CRDs.
Proposes the creation of a new `default` marker for built-in types, and align the default marker in kubebuilder.
That marker will decide what default field we end-up with in the openapi and how this flag will be used.
=> Create KEP for built-in Defaulting

keps/sig-node/2053-downward-api-hugepages/README.md, keps/sig-node/2053-downward-api-hugepages/kep.yaml
Adding support for hugepages in the downward API requires validation to loosen.
As a result, we need to coordinate adding support in the kubelet, and ensure that the feature on the kube-apiserver is not enabled for 2 releases to ensure all nodes in the cluster have latest support before enabling the feature by default for existing clusters.  This KEP describes that process.
=> Downward API support for HugePages

keps/sig-node/1985-remove-dockershim/README.md, keps/sig-node/1985-remove-dockershim/kep.yaml
=> Removing dockershim from kubelet

keps/sig-node/2043-pod-resource-concrete-assigments/README.md, keps/sig-node/2043-pod-resource-concrete-assigments/kep.yaml
This change is necessary for resource with topology exporting daemon,
which used in topology aware scheduling.
This PR proposes following changes:
- Adds cpuids and hardware topology of devices into podresource interface
- Extends podresources interface by Watch endpoint
- Extends podresources interface by GetAllocatableResources endpoint
Information about CPU is keeping in cpu_ids, since it's  enough to
represent both quantity and numaid. NUMAid can be obtained from
cadvisor MachineInfo, since id in cpus_ids is a thread_id.
This API doesn't provide cpu fraction, since it could be obtained from
Pod's request/limits and in case of non-integer CPU quantity and
non-guaranteed QoS cpu assigned is not exclusive and NUMA id is not
interesting.
Issue: #2043
=> PodResources interface enhancements

keps/sig-network/1672-tracking-terminating-endpoints/README.md
Add alpha graduation criteria for EndpointSlice API tracking terminating condition. 
=> KEP-1672: add alpha graduation criteria

OWNERS_ALIASES, SECURITY_CONTACTS
- OWNERS: Add Lauri Apple as an Enhancements subproject owner
- OWNERS: Sync OWNERS_ALIASES w/ k/community
- OWNERS: Update SECURITY_CONTACTS
This has been approved by all @kubernetes/sig-architecture-leads and @kubernetes/enhancements subproject owners.
ref: https://groups.google.com/g/kubernetes-sig-architecture/c/_LcElBQ0uc8, https://kubernetes.slack.com/archives/C5P3FE08M/p1601585313029600, https://github.com/kubernetes/org/pull/2241
cc: @LappleApple
=> OWNERS: Add Lauri Apple as an Enhancements subproject owner

keps/sig-network/1669-graceful-termination-local-external-traffic-policy/README.md
Adding alpha graduation criteria for KEP-1669, which improves kube-proxy's handling of external traffic, specifically when all local endpoints are terminating.
=> KEP-1669: add alpha graduation criteria

keps/sig-network/2030-endpointslice-subsetting/README.md, keps/sig-network/2030-endpointslice-subsetting/kep.yaml
This allows produces of EndpointSlices to segment them into logical chunks enabling API consumers like kube-proxy to watch only a subset of all EndpointSlices. This provides a natural starting point for topology aware routing and dramatically increases scalability.
Enhancement Issue: https://github.com/kubernetes/enhancements/issues/2030.
This is a prerequisite to https://github.com/kubernetes/enhancements/issues/2004.
/sig network
/cc @JeremyOT @andrewsykim @bowei @danwinship @thockin 
=> KEP 2030: EndpointSlice Subsetting and Selection

keps/sig-cluster-lifecycle/kubeadm/2067-rename-master-label-taint/README.md
just adding some blank lines to separate the stages.
otherwise they end up clumped on the same lines.
also change "primary" / "secondary" to "first" / "second" to match:
https://github.com/kubernetes/enhancements/issues/2067
=> sig-cl/kubeadm: fix markdown issue in "rename master" KEP

keps/sig-auth/541-external-credential-providers/README.md, keps/sig-auth/541-external-credential-providers/kep.yaml
Signed-off-by: Andrew Keesler <akeesler@vmware.com>
- Per sig-release, this PR is out of date with the required KEP format.
- This PR should bring this KEP up to date with the required KEP format.
- PRR: https://github.com/kubernetes/enhancements/blob/master/pkg/kepctl/testdata/templates/README.md#production-readiness-review-questionnaire
- `kep.yaml` format: https://github.com/kubernetes/enhancements/blob/master/keps/NNNN-kep-template/kep.yaml
-  Previous PR in this saga: https://github.com/kubernetes/enhancements/pull/2023.
=> exec credential provider: updates after sig-release feedback

keps/sig-api-machinery/1040-priority-and-fairness/README.md, keps/sig-api-machinery/1040-priority-and-fairness/kep.yaml
I've filled in most of the questions in the PRR to the best of my (limited) knowledge -- please take a look and let me know if there are corrections to be made. I don't know enough to answer some of the questions - I'd appreciate your input on some of these questions.
/cc @lavalamp @wojtek-t @ahg-g @MikeSpreitzer
=> priority and fairness: add production readiness review

keps/sig-node/kubelet-resource-metrics-endpoint.md
in 1.18, we moved the endpoint from /metrics/resource.  In 1.20, we removed the original /metrics/resource/v1alpha1 endpoint.
/assign @derekwaynecarr @dchen1107 
cc @RainbowMango @brancz @ehashman @logicalhan @serathius
=> Updates to the kubelet resource metrics KEP

keps/sig-node/kubelet-resource-metrics-endpoint.md
KEPs now must have a separate test plan to graduate.  Addresses: https://github.com/kubernetes/enhancements/issues/727#issuecomment-703039527
/assign @dchen1107 @derekwaynecarr 
cc @brancz @logicalhan @ehashman
=> Move test plan to its own section in kubelet resource metric KEP

keps/sig-instrumentation/1748-pod-resource-metrics/README.md, keps/sig-instrumentation/1748-pod-resource-metrics/kep.yaml
Report metrics about pod resource reservation as observed by scheduler, quota, and kubelet subsystems in a way that makes administrators able to easily build dashboards and perform reporting on real resource usage.
Tied to #1748
=> kep: Pod resource metrics

ISSUE_TEMPLATE.md
As we kick off the 1.20 release, there has been a discussion with the Enhancement team and Docs team on improving the current process of tracking all the necessary release requirements from Enhancement owners. 
Based on the discussion, @kikisdeliveryservice (Enhancement lead) and I (Docs lead) believe that adding a docs section in the issue template would help. This will make sure Enhancement owners are aware of docs requirements earlier in the process when an issue is created (An item from 1.17 retro) and help both the enhancement/docs team to not dig through all the comments to figure out where docs PR(s) were shared. 
/assign @mrbobbytables @jeremyrickard @justaugustus @johnbelamaric 
/hold 
for feedback
Example: https://github.com/kubernetes/enhancements/issues/757
=> Add Documentation PR section to the issue template

ISSUE_TEMPLATE.md
Modify the issue template to divide up into `alpha`, `beta`, and `stable` to track resource changes based on the release. (This is a follow up on https://github.com/kubernetes/enhancements/pull/2016 based on https://github.com/kubernetes/enhancements/pull/2016#issuecomment-713118605)
/hold
for feedback from the Enhancement team
cc @justaugustus @mrbobbytables @kikisdeliveryservice
=> Update issue template to divide into alpha/beta/stable

keps/sig-node/0035-20190130-topology-manager.md
As Topology Manager Scope feature wasn't included in v1.19 the current target release is v1.20.
=> Update Topology Manager Graduation Criteria

keps/sig-api-machinery/1929-built-in-default/README.md
cc @sttts @liggitt @DirectXMan12 @jpbetz
=> Address "Built-in Defaulting" KEP feedback

keps/sig-network/2086-service-internal-traffic-policy/README.md, keps/sig-network/2086-service-internal-traffic-policy/kep.yaml
There has been some discussions in SIG Network about next steps for Service Topology. See this thread for more context: https://groups.google.com/forum/#!topic/kubernetes-sig-network/wXd1D_fKjqU 
Another approach we can start experimenting with, in addition to the existing `topologyKeys` field would be to add an `internalTrafficPolicy` field to Service that takes a more direct approach to solving the "route to node-local endpoints" use-case. This KEP proposes 3 internal traffic policies for alpha:
* Cluster (default): route to all cluster-wide endpoints.
* PreferLocal: route to node-local endpoints if it exists, otherwise route to cluster-wide endpoints.
* LocalOnly: only route to local endpoints, drop otherwise.
In this way we can …
=> KEP-2086: Service Internal Traffic Policy

keps/sig-node/2043-pod-resource-concrete-assigments/README.md, keps/sig-node/2043-pod-resource-concrete-assigments/kep.yaml
For capacity reasons, the implementation of the Watch extension proposed
in this KEP has to be postponed to 1.21. We are still actively pursuing
all the other simpler changes to be part of 1.20.
This PR fixes the KEP to reflect that the implementation will be
completed in 1.21 and not in 1.20.
Signed-off-by: Francesco Romani <fromani@redhat.com>
=> podresources: move the completion to 1.21

keps/sig-auth/541-external-credential-providers/README.md
Signed-off-by: Andrew Keesler <akeesler@vmware.com>
This PR is to stage KEP updates that were made as a part of the exec credential plugin cluster info PR: https://github.com/kubernetes/kubernetes/pull/95489/.
=> exec credential provider: updates to KEP after cluster info PR

keps/sig-node/2043-pod-resource-concrete-assigments/README.md, keps/sig-node/606-compute-device-assignment/README.md
According to implementation the service has name PodResourcesLister,
but in the keps it's the same as message name - just PodResources.
Signed-off-by: Alexey Perevalov <alexey.perevalov@huawei.com>
=> Fix PodResourcesLister service name

keps/sig-cluster-lifecycle/kubeadm/2067-rename-master-label-taint/README.md
Add a link to the ADR (Architectural Decision Record) from WG Naming
about the "master" to "control plane" rename to formalize the decision.
http://git.k8s.io/community/wg-naming/recommendations/master-control-plane.md
=> sig-cluster-lifecycle/kubeadm: add ADR link to kubeadm master rename KEP

keps/sig-node/2043-pod-resource-concrete-assigments/README.md
Reviews during the implementation of this KEP highlighted
that current description in the KEP is too terse and too light
on description. This PR fixes this.
Signed-off-by: Francesco Romani <fromani@redhat.com>
=> doc: clarify the usage of GetAllocatableResources

keps/sig-release/0000-anago-to-krel-migration/README.md, keps/sig-release/0000-anago-to-krel-migration/kep.yaml
This adds the KEP for the migration from bash code (anago) to golang (krel) in k/release.
/cc @kubernetes/sig-release-leads
=> Add Anago to Krel migration KEP

keps/sig-network/1860-kube-proxy-IP-node-binding/README.md, keps/sig-network/1860-kube-proxy-IP-node-binding/kep.yaml
Signed-off-by: Patrik Cyvoct <patrik@ptrk.io>
Since https://github.com/kubernetes/kubernetes/pull/92312 is merged, this KEP should be updated
Ref #1860
=> Set KEP 1860 as implementable

keps/sig-network/2004-topology-aware-subsetting/README.md, keps/sig-network/2004-topology-aware-subsetting/kep.yaml, keps/sig-network/2030-endpointslice-subsetting/kep.yaml
This also adds some notes about node local traffic and DNS.
=> Updating topology KEPs to reflect updated 1.21 alpha target

keps/sig-network/0752-endpointslices/README.md, keps/sig-network/0752-endpointslices/kep.yaml
This reflects the changes that were added in https://github.com/kubernetes/kubernetes/pull/96440.
/sig network
=> Updating EndpointSlice KEP for 1.20

cmd/kepctl/query.go, pkg/kepctl/kepctl.go, pkg/kepctl/query.go
Added an `--output` flag to `kepctl query` which accepts yaml, json or nothing
which is the default behavior and prints as a table to the standard output.
Related to #2095 
- Add a flag for specifying the columns that we want in the output
- Add the `link` attribute to the YAML and JSON as well.
/hold
(for reviews)
=> Add YAML and JSON printers to kepctl query

README.md
I noticed that the link for 1.20 was missing from the README. I tested and found that this bitly link takes us to the right place, so figured I would list it here.
=> Adding missing link to 1.20 enhancements tracking

keps/sig-cluster-lifecycle/kubeadm/2067-rename-master-label-taint/README.md
the link changed here to include indexing:
https://github.com/kubernetes/community/pull/5342
/cc @fabriziopandini @SataQiu 
looking for LGTM. thanks.
=> sig-cluster-lifecycle/kubeadm: change link to "master" rename ADR

keps/sig-release/0000-anago-to-krel-migration/kep.yaml
With the merge of the anago removal PR we can now consider that KEP as
done.
cc @kubernetes/release-engineering @kubernetes/sig-release-leads 
/hold
Requires https://github.com/kubernetes/release/pull/1765
=> Mark anago krel migration KEP as implemented

keps/sig-cluster-lifecycle/addons/20200121-manifest-bundle.md
This is a draft for the bundle manifest kep discussed in cluster-addons (and in kubebuilder, a while ago).
=> Add manifest bundle kep

keps/sig-network/614-SCTP-support/README.md, keps/sig-network/614-SCTP-support/kep.yaml
Code (https://github.com/kubernetes/kubernetes/pull/95566) and docs (https://github.com/kubernetes/website/pull/24593) are now updated. SCTP is GA in 1.20.
=> Mark SCTP as implemented

keps/sig-storage/177-volume-snapshot/kep.yaml
Snapshot is GA.  Change status to implemented.
Issue: https://github.com/kubernetes/enhancements/issues/177
=> Change KEP status to implemented

pkg/kepctl/query.go
Recent refactor of `kepval` validations broke this. I guess our CI doesn't even build `kepctl`.
=> Fix reference to validations.Sigs() since refactor

keps/sig-apps/592-ttl-after-finish/README.md, keps/sig-apps/592-ttl-after-finish/kep.yaml, keps/sig-apps/706-portable-service-definitions/README.md, keps/sig-apps/706-portable-service-definitions/kep.yaml, keps/sig-apps/961-maxunavailable-for-statefulset/README.md, keps/sig-apps/961-maxunavailable-for-statefulset/kep.yaml, keps/sig-apps/981-poddisruptionbudget-for-custom-resources/README.md, keps/sig-apps/981-poddisruptionbudget-for-custom-resources/kep.yaml
=> Migrate some apps KEPs to new template

keps/NNNN-kep-template/README.md, keps/sig-architecture/1194-prod-readiness/README.md, keps/sig-architecture/1194-prod-readiness/kep.yaml
In 1.21, PRR is required. This PR updates the associated KEP and the KEP template to reflect this.
/assign @wojtek-t @deads2k
=> Update PRR KEP and KEP template for implementation

keps/sig-autoscaling/117-hpa-metrics-specificity/README.md, keps/sig-autoscaling/117-hpa-metrics-specificity/kep.yaml, keps/sig-autoscaling/1610-container-resource-autoscaling/README.md, keps/sig-autoscaling/1610-container-resource-autoscaling/kep.yaml, keps/sig-autoscaling/853-configurable-hpa-scale-velocity/README.md, keps/sig-autoscaling/853-configurable-hpa-scale-velocity/kep.yaml
=> Migrate remaining autoscaling keps to new template

keps/sig-contributor-experience/0000-community-forum/README.md, keps/sig-contributor-experience/0000-community-forum/kep.yaml, keps/sig-contributor-experience/1553-issue-triage/kep.yaml, keps/sig-contributor-experience/2225-contributor-site/README.md, keps/sig-contributor-experience/2225-contributor-site/kep.yaml
This is a no-op. Just migrates the old keps to the new format. 
The contributor site kep will need some follow-up to update the implementation history and details.
/kind cleanup
ref: #2220
=> ContribEx: Migrate old keps to new format

keps/sig-architecture/1143-node-role-labels/README.md, keps/sig-architecture/1143-node-role-labels/kep.yaml, keps/sig-architecture/1333-conformance-without-beta/README.md, keps/sig-architecture/1333-conformance-without-beta/kep.yaml, keps/sig-architecture/917-go-modules/README.md, keps/sig-architecture/917-go-modules/kep.yaml
=> Migrate remaining architecture keps to new template

keps/sig-docs/1326-third-party-content-in-docs/README.md, keps/sig-docs/1326-third-party-content-in-docs/kep.yaml, keps/sig-network/1611-network-policy-validation/README.md, keps/sig-network/1611-network-policy-validation/kep.yaml, keps/sig-node/375-cpu-manager/README.md, keps/sig-node/375-cpu-manager/kep.yaml, keps/sig-testing/714-break-test-tarball/README.md, keps/sig-testing/714-break-test-tarball/kep.yaml
=> Migrate few missed keps to new template

keps/sig-scheduling/1819-scheduler-extender/README.md
see https://github.com/kubernetes/kubernetes/pull/92866#discussion_r496160188
=> KEP-1819: notes on the order of extenders

keps/sig-api-machinery/2144-clientgo-apply/README.md, keps/sig-api-machinery/2144-clientgo-apply/kep.yaml
We would like to merge this KEP as provisional and then work toward implementable. We're targeting 1.21 for this feature. We have `<<[UNRESOLVED` tags for issues we know need to be resolved before transitioning to implementable.
We have a working prototype for the kubernetes code generators: https://github.com/kubernetes/kubernetes/pull/95988 (for the leading alternative) and https://github.com/jpbetz/kubernetes/tree/apply-client-go-builders (for the "builders" alternative where getters and getters are generated).
@jennybuckley is working on code generators for controller-tools that will be circulated with the Kubebuilder community to get feedback on the utility of the approach proposed by this KEP.
/wg api-expression
cc @jennybuckley @apelisse @kwiesmueller
=> Provisional KEP: Apply for client-go's typed clients

cmd/kepval/main_test.go
Rather than reverting the larger PR I am putting in this small PR that just disables enforcement.
/cc @ehashman @deads2k
=> Disable enforcement of PRR requirements

keps/sig-cloud-provider/2133-out-of-tree-credential-provider/kep.yaml, keps/sig-node/2133-kubelet-credential-providers/README.md, keps/sig-node/2133-kubelet-credential-providers/kep.yaml
=> KEP-2133: kubelet credential provider plugins

hack/.notableofcontents, keps/sig-cluster-lifecycle/clusterapi/README.md
The issue regarding this was originally raised at https://github.com/kubernetes-sigs/cluster-api/issues/3791 
Cluster-API enhancements proposals are updated independently in it's repository. The README gives link to those proposals.
=> Add README for cluster-api keps

pkg/kepval/keps/proposals.go
The `Filename` field was (accidentally?)  getting removed in this PR. https://github.com/kubernetes/enhancements/commit/fd2a0c4480d82dd98c810c2e0a25f13382935429
Without this field, `kepctl` won't compile.
```
$go build -o kepctl ./cmd/kepctl
pkg/kepctl/create.go:118:3: t.Filename undefined (type *keps.Proposal has no field or method Filename)
```
After this PR, `go build -o kepctl ./cmd/kepctl` worked.
=> Fixed kepctl compile error

keps/sig-auth/1687-hierarchical-namespaces-subproject/README.md, keps/sig-auth/1687-hierarchical-namespaces-subproject/kep.yaml
In the bi-weekly sig-auth meeting today, the leads have indicated this KEP has met the intake criteria and therefore should become a sub-project with it's own git repo. As such, we are moving the KEP to implementable so we can start work to create the repo.
=> Move keps/sig-auth/1687 to implementable

keps/sig-release/1733-release-notes/README.md, keps/sig-release/1733-release-notes/kep.yaml
The implementation of the KEP is now done which should also close the
corresponding issue.
Closes https://github.com/kubernetes/enhancements/issues/1733
=> Mark release notes KEP as implemented

keps/sig-api-machinery/2161-apiserver-default-labels/README.md, keps/sig-api-machinery/2161-apiserver-default-labels/kep.yaml
thx to @rikatz @thockin , ok ! here we go... lets see if we can workaround the issues so far in https://github.com/kubernetes/enhancements/pull/2113/files by adding default labels.
Fixes #2161
=> Apiserver namespace labels

OWNERS_ALIASES
as per kubernetes/community#5386, i am stepping down from sig-windows chair.
updating with the new chairs and TLs for sig-windows
Signed-off-by: Michael Michael michmike@cs.stanford.edu
=> michmike vacating sig-windows chair position

keps/sig-api-machinery/1904-efficient-watch-resumption/kep.yaml
This should be set to 1.21 in the PRR approval request PR (#2274), not here. Otherwise this causes us to be unable to re-enable PRR validation in #2280.
=> Set latest-milestone back to 1.20

keps/prod-readiness/sig-apps/592.yaml, keps/sig-apps/592-ttl-after-finish/README.md, keps/sig-apps/592-ttl-after-finish/kep.yaml
=> Updates the ttl-to-finished KEP to graduate the feature to Beta.

keps/sig-architecture/1635-prevent-permabeta/README.md, keps/sig-architecture/1635-prevent-permabeta/kep.yaml
Some description of mechanics to ease https://github.com/kubernetes/enhancements/issues/1635 in case I win the lottery this Tuesday. :)
The kube-apiserver automatically stops serving beta APIs after they expire, but there is grace during the alpha tags to ensure we can ship the v1.N-1.  This ensures no human action is required to remove the APIs, but also gives a way to remove them in a controlled way and avoid red CI.
=> describe mechanics of handling beta removal to avoid developer disruption

keps/prod-readiness/sig-api-machinery/1904.yaml, keps/sig-api-machinery/1904-efficient-watch-resumption/kep.yaml
Ref #1904
Follow up from: https://github.com/kubernetes/enhancements/pull/2267
I filled in the PRR in: https://github.com/kubernetes/enhancements/pull/2267 and apparently forgot to "git add" the PRR file :(
I Daniel approved that in the meantime :)
=> PRR Approval for Beta of efficient watch resumption KEP

keps/sig-storage/1900-volume-snapshot-validation-webhook/kep.yaml
Snapshot is already GA. Change status to implemented so that we can close the issue: https://github.com/kubernetes/enhancements/issues/1900
=> Change snapshot validation webhook KEP status to implemented

keps/sig-api-machinery/1295-insecure-backend-proxy/README.md, keps/sig-api-machinery/1295-insecure-backend-proxy/kep.yaml
target insecure-backend-proxy for stable in 1.21.  This requires adding a PRR section.
=> update insecure-backend-proxy feature to target GA.  Add PRR

cmd/kepval/main_test.go
This re-enables the enforcement of PRR approval, as discussed in the recent leads meeting.
One is in conjunction with https://github.com/kubernetes/community/pull/5413 which addresses:
* additional documentation around how to request approval, including an example PR
* clarification around the date by which approval is required
* details on how to join the PRR approver team
* explain why these reviews require a separate team that is not simply the SIG leads
One other concern raised was that this could be a bottleneck. Our experience based upon our dry runs in 1.19 and 1.20 is that this is not the case. With three team members and ~40 or so KEPs needing review per release cycle, the burden is not unreasonable. Especially since the team does not review code, but rather just the KEPs and …
=> Re-enable PRR approval requirement

keps/sig-network/563-dual-stack/README.md, keps/sig-network/563-dual-stack/kep.yaml
These updates to the KEP reflect the tests added for 1.20 and the additional test-related item in the graduation criteria (dualstack tests run as pre-submit blocking for PRs).
=> Updates to KEP 563: test plan, graduation criteria

keps/sig-node/2000-graceful-node-shutdown/README.md
Updating the graceful node shutdown KEP implementation history now that the feature is in alpha as of 1.20
Enhancement issue: https://github.com/kubernetes/enhancements/issues/2000
=> Update Graceful Node Shutdown KEP 1.20 Alpha

keps/sig-node/277-ephemeral-containers/README.md
=> chore: fix broken links in KEP-277

keps/sig-node/1972-kubelet-exec-probe-timeouts/README.md
A few fixes including an update for feature flag removal criteria for the https://github.com/kubernetes/kubernetes/pull/98085
KEP: #1972 
/sig node
=> Updated graduation criteria for ExecProbeTimeout removal

keps/sig-node/1287-in-place-update-pod-resources/kep.yaml, keps/sig-node/2273-kubelet-container-resources-cri-api-changes/README.md, keps/sig-node/2273-kubelet-container-resources-cri-api-changes/kep.yaml
Migrated the one sig-node kep to the new format.
keps/sig-node/1342-kubelet-container-resources-cri-api-changes Folder added and few links updated.
ref: #2220
=> Migrated KEP to new format | sig-node | kubelet-container-resources-cri-api-changes 

keps/sig-network/563-dual-stack/README.md
Additional tests to go along with the ones added in https://github.com/kubernetes/enhancements/pull/2318 - these tests were fixed by @aramase in https://github.com/kubernetes/test-infra/pull/20593 and are now completing correctly.
=> Update to KEP 563 - documenting additional tests

pkg/kepctl/query.go, pkg/kepctl/query_test.go
Related to https://github.com/kubernetes/enhancements/issues/2297
```
$ go test -v query_test.go create.go  kepctl.go  promote.go query.go  
=== RUN   TestValidate
=== RUN   TestValidate/Valid_SIG
=== RUN   TestValidate/Invalid_SIG
=== RUN   TestValidate/Unsupported_Output_format
--- PASS: TestValidate (0.00s)
--- PASS: TestValidate/Valid_SIG (0.00s)
--- PASS: TestValidate/Invalid_SIG (0.00s)
--- PASS: TestValidate/Unsupported_Output_format (0.00s)
PASS
ok  	command-line-arguments	2.798s
```
=> query_test.go added - TestValidate method defined

keps/prod-readiness/sig-network/2200.yaml, keps/sig-network/2200-externalips-admission/README.md, keps/sig-network/2200-externalips-admission/kep.yaml
This KEP proposes to add a surgical admission controller (optional) to
block use of the `Service.spec.externalIPs` misfeature.
See CVE-2020-8554: Man in the middle using LoadBalancer or ExternalIPs (https://github.com/kubernetes/kubernetes/issues/97110)
for details.
=> KEP 2200: Block service ExternalIPs via admission

api/proposal.go, cmd/kepify/main.go, pkg/kepctl/create.go, pkg/kepctl/create_test.go, pkg/kepctl/kepctl.go, pkg/kepctl/kepctl_test.go, pkg/kepctl/query.go, pkg/kepval/keps/proposals.go
Creates an `api/` package to hold the current state of the world for the KEP template.
Part of https://github.com/kubernetes/enhancements/issues/2348.
=> api: Initial commit

keps/prod-readiness/sig-network/2079.yaml, keps/sig-network/2079-network-policy-port-range/README.md, keps/sig-network/2079-network-policy-port-range/kep.yaml
Signed-off-by: Ricardo Pchevuzinske Katz <ricardo.katz@gmail.com>
=> Add some more answers into PRR review in EndPort kep

keps/prod-readiness/sig-auth/1393.yaml, keps/sig-auth/1393-oidc-discovery/README.md, keps/sig-auth/1393-oidc-discovery/kep.yaml
Add PRR survey as part of preparing to move to GA.
=> Add PRR survey to OIDC Discovery KEP

cmd/kepctl/query.go, pkg/kepctl/query_test.go
Signed-off-by: Ling Samuel <lingsamuelgrace@gmail.com>
#2298 deleted `Validate` args.
Also the test function name conflicts https://github.com/kubernetes/enhancements/blob/0f5924859f15b4f54c682dc9d3f11553c584b65b/pkg/kepctl/kepctl_test.go#L30
=> Fix query cmd `opts.Validate` and test func name

keps/sig-cli/2377-Kustomize/README.md, keps/sig-cli/2377-Kustomize/kep.yaml, keps/sig-cli/2379-kubectl-plugins/README.md, keps/sig-cli/2379-kubectl-plugins/kep.yaml, keps/sig-cli/2380-data-driven-commands-for-kubectl/README.md, keps/sig-cli/2380-data-driven-commands-for-kubectl/kep.yaml, keps/sig-cli/2381-future-of-kubectl-cp/README.md, keps/sig-cli/2381-future-of-kubectl-cp/kep.yaml, keps/sig-cli/2382-kustomize-exec-secret-generator/README.md, keps/sig-cli/2382-kustomize-exec-secret-generator/kep.yaml, keps/sig-cli/2383-extend-kustomize-patches-to-multiple-targets/README.md, keps/sig-cli/2383-extend-kustomize-patches-to-multiple-targets/kep.yaml, keps/sig-cli/2384-kustomize-file-processing-integration/README.md, keps/sig-cli/2384-kustomize-file-processing-integration/kep.yaml, keps/sig-cli/2385-kustomize-secret-generator-plugins/README.md, keps/sig-cli/2385-kustomize-secret-generator-plugins/kep.yaml, keps/sig-cli/2386-kustomize-subcommand-integration/README.md, keps/sig-cli/2386-kustomize-subcommand-integration/kep.yaml
Migrating the old KEP files into new format - sig-cli
=> Migrating from old kep to new template -sig cli keps

pkg/kepctl/kepctl.go, pkg/kepval/prrs/approvals.go
While querying for KEPs needing PRR approval, I saw we were still missing some KEPs. This is because people aren't setting `prrApprovers` in `kep.yaml` and are instead just setting it in the PRR approval request yaml. This hacky PR allows us to search those too.
/assign @wojtek-t @deads2k 
/cc @jeremyrickard
=> Look at PRR approval request when querying KEPs

keps/sig-network/563-dual-stack/README.md
Minor updates to dual stack kep
=> dualstack kep updates

keps/prod-readiness/sig-scheduling/2249.yaml, keps/sig-scheduling/2249-pod-affinity-namespace-selector/README.md, keps/sig-scheduling/2249-pod-affinity-namespace-selector/kep.yaml
=> Add KEP for Pod Affinity NamespaceSelector

keps/sig-instrumentation/383-new-event-api-ga-graduation/README.md, keps/sig-instrumentation/383-new-event-api-ga-graduation/kep.yaml
The KEP should be in implementable status since we haven't migrate all components to use the new API. Updated the KEP to indicate the remaining work that needs to be done for graduating new Event API.
=> Update new events KEP to indicate latest status

keps/sig-apps/592-ttl-after-finish/README.md
Ref: #592
Added an explicit test plan section as required by enhancement tracking.
=> Add test plan section to ttl-after-finished KEP

keps/prod-readiness/sig-storage/1472.yaml, keps/sig-storage/1472-storage-capacity-tracking/README.md, keps/sig-storage/1472-storage-capacity-tracking/kep.yaml
This marks items as completed which are (or soon will be) done.
PRR review will happen as part of merging this PR.
=> storage capacity: PRR and beta review

keps/sig-instrumentation/647-apiserver-tracing/README.md
OpenTelemetry recently got its own reserved port number, 4317.  https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.txt
/assign @ehashman @brancz @logicalhan
=> Switch to the reserved port for opentelemetry

keps/sig-testing/2420-reducing-kubernetes-build-maintenance/README.md, keps/sig-testing/2420-reducing-kubernetes-build-maintenance/kep.yml
see: https://github.com/kubernetes/enhancements/issues/2420
previous discussion: https://github.com/kubernetes/kubernetes/issues/88553
=> add KEP 2420: Reducing Kubernetes Build Maintenance

keps/prod-readiness/sig-cli/2227.yaml, keps/sig-cli/2227-kubectl-default-container/README.md, keps/sig-cli/2227-kubectl-default-container/kep.yaml
https://github.com/kubernetes/enhancements/issues/2227 is the issue to track this feature.
I opened https://github.com/kubernetes/kubernetes/pull/97099
Fixes https://github.com/kubernetes/kubernetes/issues/96986, a similar solution like https://github.com/kubernetes/kubernetes/pull/87809
There is a discussion in #95293 which is in process for generic default container.
```
Users might specify the `kubectl.kubernetes.io/default-container` annotation in a Pod to preselect container for kubectl commands.
```
@mfojtik & @howardjohn
@dougsland @eddiezane @soltysh
=> add KEP-2227 for default container used by kubectl

keps/prod-readiness/sig-apps/2185.yaml, keps/sig-apps/2185-random-pod-select-on-replicaset-downscale/README.md, keps/sig-apps/2185-random-pod-select-on-replicaset-downscale/kep.yaml
This introduces the KEP for random replicaset downscale (as previously discussed in https://github.com/kubernetes/kubernetes/issues/96748). Currently addresses sections for alpha designation, looking for feedback from sig-apps and sig-scheduling
re: https://github.com/kubernetes/enhancements/issues/2185
/sig apps
=> Add KEP for random ReplicaSet downscale

keps/prod-readiness/sig-network/2365.yaml, keps/sig-network/2365-ingressclass-namespaced-params/README.md, keps/sig-network/2365-ingressclass-namespaced-params/kep.yaml
This proposes adding a new optional Namespace field to IngressClass Parameters references.
Enhancement Issue: https://github.com/kubernetes/enhancements/issues/2365
/sig network
/cc @danehans @cmluciano @hbagdi @bowei 
/assign @johnbelamaric @thockin
=> Adding KEP 2365: IngressClass Namespaced Params

keps/prod-readiness/sig-network/0752.yaml, keps/sig-network/0752-endpointslices/README.md, keps/sig-network/0752-endpointslices/kep.yaml
This PR proposes to add a per endpoint `zone` field and remove the per endpoint `topology` field. The proposal includes how to preserve the information in the `topology` field once resources are upgraded to v1
/cc @robscott 
/sig network
=> Update EndpointSlice GA to include zone for 1.21

keps/sig-cloud-provider/2390-reporting-conformance-test-results-to-testgrid/README.md, keps/sig-cloud-provider/2390-reporting-conformance-test-results-to-testgrid/kep.yaml, keps/sig-cloud-provider/2392-cloud-controller-manager/README.md, keps/sig-cloud-provider/2392-cloud-controller-manager/kep.yaml, keps/sig-cloud-provider/2393-cloud-provider-documentation/README.md, keps/sig-cloud-provider/2393-cloud-provider-documentation/kep.yaml, keps/sig-cloud-provider/2394-support-out-of-tree-AWS-cloud-provider/README.md, keps/sig-cloud-provider/2394-support-out-of-tree-AWS-cloud-provider/kep.yaml, keps/sig-cloud-provider/2395-removing-in-tree-cloud-providers/README.md, keps/sig-cloud-provider/2395-removing-in-tree-cloud-providers/kep.yaml
Migrating the old KEP files into new format - sig-cloud-provider
=> Migrating from old kep to new template: sig-cloud-provider  keps

keps/prod-readiness/sig-apps/2307.yaml, keps/sig-apps/2307-job-tracking-wihout-lingering-pods/README.md, keps/sig-apps/2307-job-tracking-wihout-lingering-pods/kep.yaml
Ref #2307 kubernetes/kubernetes#8486
/sig apps
=> Add KEP for job tracking in implementable status

keps/prod-readiness/sig-auth/541.yaml, keps/sig-auth/541-external-credential-providers/README.md, keps/sig-auth/541-external-credential-providers/kep.yaml
**Context**
- We need to add some metrics to the exec plugin feature set to get it to GA quality.
- This mostly came out of discuss on a previous PR here: https://github.com/kubernetes/enhancements/pull/2096#discussion_r503517168.
- I tried to take some initial strawperson opinions on other stuff. I will add some comments for questions that came up during the design.
- Exec plugin feature set delivery is tracked here: https://github.com/kubernetes/enhancements/issues/541.
=> exec credential provider: prep for 1.21 (first pass at metrics design, PRR updates)

keps/prod-readiness/sig-network/1507.yaml, keps/sig-network/1507-app-protocol/README.md, keps/sig-network/1507-app-protocol/kep.yaml
This feature has already reached GA. The only thing happening in the 1.21 release cycle is removing the feature gate. As a follow up to https://github.com/kubernetes/enhancements/issues/1507#issuecomment-770334761 and the [associated Slack thread](https://kubernetes.slack.com/archives/C1L57L91V/p1611855486052700), this adds a PRR to this KEP. 
/assign @deads2k 
/sig network
=> Adding PRR for AppProtocol KEP

keps/prod-readiness/sig-instrumentation/1602.yaml, keps/sig-instrumentation/1602-structured-logging/README.md, keps/sig-instrumentation/1602-structured-logging/kep.yaml
/cc @serathius @dims @wojtek-t 
SIG Instrumentation would like to target beta for structured logging in 1.21. I am volunteering to help out @serathius with coordination. I can commit to migrating the kubelet in 1.21.
Once this change is approved/merges, I will go file issues documenting all the work required for this release.
ref #1602
=> Update structured logging for 1.21

keps/sig-instrumentation/1602-structured-logging/README.md
Rephrasing current Beta scope and adding  additional points based on work remaining from Alpha:
* For alpha json format doesn't support any klog features (available via command line flags). Implementing all of them would take enormous work, so we should agree which features should be supported long term and plan for deprecation of others. 
Motivation: We need base feature parity for logging formats so users can switch them relatively easily.
/assign @ehashman 
/cc @44past4 @thockin @DirectXMan12
=> Scope structured logging Beta

keps/prod-readiness/sig-node/2403.yaml, keps/sig-node/2403-pod-resources-allocatable-resources/README.md, keps/sig-node/2403-pod-resources-allocatable-resources/kep.yaml
In order to simplify and make more understandable the KEP, and
to comply with the new process, we extract the unit of work still
ongoing in this KEP from https://github.com/kubernetes/enhancements/pull/1884
Work in this area was done during the 1.20 and 1.21 cycles  in
https://github.com/kubernetes/kubernetes/pull/95734
Rationale, discussion and documentation for all the changes including
the one proposed in this KEP have been described in
https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/2043-pod-resource-concrete-assigments
and reported here were relevant
Signed-off-by: Francesco Romani <fromani@redhat.com>
=> Add GetAllocatableResource to PodResource API

keps/prod-readiness/sig-cli/859.yaml, keps/sig-cli/859-kubectl-headers/README.md, keps/sig-cli/859-kubectl-headers/kep.yaml
* Updates the SIG CLI KEP 859 to the new KEP format.
* Updates the `README.md` to include new sections.
* Updates the `kep.yaml` to include new fields.
* Adds `859.yaml` to the SIG CLI production readiness review.
=> Updates SIG CLI KEP 859 to new format

keps/sig-network/0752-endpointslices/README.md
This is just a clarification that the topology field is being removed from the GA API only that was proposed in #2367. 
No additional changes are proposed as part of this PR.
/cc @robscott 
/assign @wojtek-t @thockin
=> Clarify topology removal in GA API

keps/sig-api-machinery/365-paginated-lists/README.MD, keps/sig-api-machinery/365-paginated-lists/kep.yaml
Move https://raw.githubusercontent.com/kubernetes/community/master/contributors/design-proposals/api-machinery/api-chunking.md into enhancements in its current state.  This is the state we have today, without any changes.
=> move Paginated API Lists from community repo

keps/prod-readiness/sig-node/2238.yaml, keps/sig-node/2238-liveness-probe-grace-period/README.md, keps/sig-node/2238-liveness-probe-grace-period/kep.yaml
See #2238. Straw proposal to be discussed at the next SIG Node meeting.
/sig node
/cc @smarterclayton @derekwaynecarr
=> Configurable probe termination grace periods

keps/sig-cloud-provider/991-cloud-controller-migration/README.md, keps/sig-cloud-provider/991-cloud-controller-migration/kep.yaml
differentiate lock type between 'leases' and 'endpoints'
=> cloud controller manager migration: default values and lease types update.

keps/prod-readiness/sig-network/2086.yaml, keps/sig-network/2086-service-internal-traffic-policy/README.md, keps/sig-network/2086-service-internal-traffic-policy/kep.yaml
The PRR for KEP-2086 is already filled out for alpha but it needs to be approved
=> KEP-2086: alpha prod readiness review

keps/prod-readiness/sig-network/2433.yaml, keps/sig-network/2433-topology-aware-hints/README.md, keps/sig-network/2433-topology-aware-hints/kep.yaml
This is a follow up to https://github.com/kubernetes/enhancements/pull/2355 and https://github.com/kubernetes/enhancements/pull/2354 and represents what I hope will be a simpler and better approach for topology aware routing.
Enhancement issue: https://github.com/kubernetes/enhancements/issues/2433
/cc @andrewsykim @bowei @dcbw 
/assign @thockin @wojtek-t 
/sig network
=> Adding KEP 2433: Topology Aware Hints

keps/prod-readiness/sig-apps/1847.yaml, keps/sig-apps/1847-autoremove-statefulset-pvcs/README.md, keps/sig-apps/1847-autoremove-statefulset-pvcs/kep.yaml
A KEP for autodeletion of StatefulSet PVCs.
Issue #1847
This is a clone of https://github.com/kubernetes/enhancements/pull/1915 in order to make progress as the original PR author has gotten swamped with other work.
I have tried to address all outstanding comments on that PR. Please let me know what I missed!
/cc @msau42 
/cc @janetkuo 
/cc @kk-src
/cc @ krmayankk
=> Autodelete StatefulSet PVCs

keps/README.md
I was looking for KEP-1 today so I noticed that it was moved in https://github.com/kubernetes/enhancements/commit/353137c2716c4d56895974e198139e5e3bd2282d but some links in keps/README.md were still pointing at the old spot. Just updating them to the new location and renaming links to KEP-0000 instead of the old KEP-1 to match the new kep.yaml from 353137c2716c4d56895974e198139e5e3bd2282d.
=> Fix links to the KEP on the KEP process

keps/prod-readiness/sig-node/2133.yaml, keps/sig-node/2133-kubelet-credential-providers/README.md, keps/sig-node/2133-kubelet-credential-providers/kep.yaml
Adding beta milestone and beta requirements for PRR for the Kubelet Credential Provider KEP. 
=> KEP-2133: add beta milestone and prod readiness review

keps/prod-readiness/sig-node/34.yaml, keps/sig-node/34-sysctl-fields/README.md, keps/sig-node/34-sysctl-fields/kep.yaml
**NOTE:** This KEP was implemented in 1.4 and went beta in 1.11 and long predates PRR. I migrated the KEP to the new template and completed the PRR requirements as best I could. I think I put a note on the KEP for where the copy-pasting from the beta KEP ended.
The feature flag has defaulted to on for at least all current supported releases. We would like to graduate this in 1.21 and follow up on any remaining usability work in a separate KEP.
/cc @pacoxu 
/sig node
xref #34
=> Migrate KEP-34 to new template

keps/prod-readiness/sig-instrumentation/1933.yaml, keps/sig-instrumentation/1933-secret-logging-static-analysis/README.md, keps/sig-instrumentation/1933-secret-logging-static-analysis/kep.yaml
[KEP-1933](https://github.com/kubernetes/enhancements/issues/1933) associated analysis is currently running in Prow in `beta` state - running on every PR, but not yet blocking on failure.  [Failures](https://prow.k8s.io/?job=pull-kubernetes-verify-govet-levee&state=failure) are infrequent and appear to be related to build or merge failures, not failures in the test itself.  Execution of the test target itself [appears to be running soundly](https://prow.k8s.io/?job=pull-kubernetes-verify-govet-levee) overall.
=> [KEP-1933] Production Readiness Review.

keps/prod-readiness/sig-storage/625.yaml, keps/sig-storage/625-csi-migration/README.md, keps/sig-storage/625-csi-migration/kep.yaml
This PR updates the CSI Migration KEP to include the Production Readiness Review Questionnaire
=> Update CSI Migration Kep to include PRRQ

keps/prod-readiness/sig-network/1864.yaml, keps/sig-network/1864-disable-lb-node-ports/README.md, keps/sig-network/1864-disable-lb-node-ports/kep.yaml
Answers alpha PRR questions for KEP-1864, which allows a user to disable node ports for Service Type=LoadBalancer. Prior to GA we should fill in the rest of the PRR questions.
=> KEP-1864: add prod readiness review and beta milestone

keps/prod-readiness/sig-scheduling/2458.yaml, keps/sig-scheduling/2458-node-resource-score-strategy/README.md, keps/sig-scheduling/2458-node-resource-score-strategy/kep.yaml
https://github.com/kubernetes/enhancements/issues/2458
=> Added KEP for Node Resource Score Strategy

keps/prod-readiness/sig-cloud-provider/2025.yaml, keps/sig-cloud-provider/2025-extend-konnectivity-for-both-directions/README.md, keps/sig-cloud-provider/2025-extend-konnectivity-for-both-directions/kep.yaml
Enhancement issue: #2347
Rendered version: https://github.com/irozzo-1A/enhancements/tree/extend-konnectivity/keps/sig-cloud-provider/2025-extend-konnectivity-for-both-directions
=> KEP: Extending Apiserver Network Proxy to handle traffic originated from Node network

keps/prod-readiness/sig-node/2129.yaml, keps/sig-node/2129-remove-cadvisor-json-metrics/README.md, keps/sig-node/2129-remove-cadvisor-json-metrics/kep.yaml
There were some concerns raised about the removal of cAdvisor json metrics, and i'd like to get a clear signal from sig-node leads on whether we should move forward with the deprecation or restore the endpoint by default: https://github.com/kubernetes/kubernetes/issues/68522#issuecomment-715462010.
I'm hoping the KEP format also makes it easy for those on the referenced issue to discuss their concerns with removal of these endpoints.
/sig node
cc @bobbypage @dims @SergeyKanzhelev @smarterclayton 
/assign @derekwaynecarr @dchen1107 
/milestone 1.21
=> Add KEP for removing cAdvisor json metrics

keps/prod-readiness/sig-storage/625.yaml, keps/sig-api-machinery/2161-apiserver-default-labels/kep.yaml
Validation errors found as a result of https://github.com/kubernetes/enhancements/pull/2409.
ref: https://github.com/kubernetes/enhancements/pull/2409#discussion_r573545015, https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/enhancements/2409/pull-enhancements-verify/1359402306486931456
=> keps: Fix incorrect stages on PRR targeting v1.21

keps/sig-scheduling/2249-pod-affinity-namespace-selector/README.md
#2249
We initially proposed to disallow empty namespaceSelector. Users however can select all namespaces as follows:
```
- Key: unused-label
operator: DoesNotExist
```
Selecting all namespaces will likely be a common usage pattern, which we can easily special case and optimize in the scheduler implementation (by avoiding listing namespaces and matching against their labels since all namespaces are eligible). And so I am suggesting we drop the restriction on empty namespaceSelector to avoid forcing users to opt into the pattern above which requires more processing.
@wojtek-t @liggitt @Huang-Wei @alculquicondor
=> Remove the restriction on empty namespaceSelector in podaffinity

keps/sig-node/2221-remove-dockershim/README.md
Postponement of Dockershim removal was discussed at SIG Node meeting today and we had no objections.
Also back tracked checkboxes since the deprecation was already implemented and did minor updates.
/sig node
=> updated Dockershim KEP and postponed  graduation date for one release

keps/sig-network/0030-nodelocal-dns-cache.md, keps/sig-network/2447-Make-kube-proxy-service-abstraction-optional/README.md, keps/sig-network/2447-Make-kube-proxy-service-abstraction-optional/kep.yaml, keps/sig-network/2448-Remove-kube-proxy-automatic-clean-up-logic/README.md, keps/sig-network/2448-Remove-kube-proxy-automatic-clean-up-logic/kep.yaml, keps/sig-network/2449-move-externalDNS-out-of-kubernetes-incubator/README.md, keps/sig-network/2449-move-externalDNS-out-of-kubernetes-incubator/kep.yaml, keps/sig-network/2450-Remove-knowledge-of-pod-cluster-CIDR-from-iptables-rules/README.md, keps/sig-network/2450-Remove-knowledge-of-pod-cluster-CIDR-from-iptables-rules/kep.yaml
Migrating the old KEP files into new format - sig-network
=> Migrating from old kep to new template: sig-network 

OWNERS_ALIASES
I would like to [apply to become an approver](https://github.com/kubernetes/community/blob/master/sig-architecture/production-readiness.md#becoming-a-prod-readiness-reviewer-or-approver) on the PRR team to help expand the team.
Some PRR reviews I've completed:
- https://github.com/kubernetes/enhancements/pull/2468
- https://github.com/kubernetes/enhancements/pull/2428
- https://github.com/kubernetes/enhancements/pull/2312
- https://github.com/kubernetes/enhancements/pull/2286
- https://github.com/kubernetes/enhancements/pull/2052
I am an [experienced KEP reviewer](https://github.com/kubernetes/enhancements/pulls?q=is%3Apr+reviewed-by%3Aehashman) as I am an approver for SIG Instrumentation.
/cc @johnbelamaric @deads2k @wojtek-t
=> Add ehashman to PRR team

keps/sig-api-machinery/1693-warnings/README.md, keps/sig-instrumentation/1209-metrics-stability/README.md, keps/sig-instrumentation/1209-metrics-stability/kep.yaml, keps/sig-instrumentation/1209-metrics-stability/kubernetes-control-plane-metrics-stability.md, keps/sig-instrumentation/1209-metrics-stability/metrics-stability-migration.md, keps/sig-instrumentation/1209-metrics-stability/metrics-stability-to-beta.md, keps/sig-instrumentation/1209-metrics-stability/metrics-validation-and-verification.md, keps/sig-instrumentation/647-apiserver-tracing/README.md, keps/sig-node/727-resource-metrics-endpoint/README.md
Ref #2220 
Given it's effectively a single KEP, just different parts are splitted across multiple `sub-keps`, this cleans it up by merging all metadata to (and removed dates from the names, which was the old convention).
/assign @logicalhan @brancz @dashpole @ehashman
=> Cleanup metadata in metrics stability kep

keps/sig-instrumentation/1602-structured-logging/README.md
@serathius typically as part of beta, some benchmarking or measurements are performed. Since we will fully migrate the kubelet during this release, a teammate of mine suggested that after code freeze (but before test freeze) we should look at kubelet log volumes for 1.20, 1.21 non-JSON and 1.21 JSON.
WDYT?
=> Add log volume benchmark

keps/sig-cloud-provider/providers/0000-cloud-provider-template/README.md, keps/sig-cloud-provider/providers/0000-cloud-provider-template/kep.yaml, keps/sig-cloud-provider/providers/2530-alibaba-cloud/README.md, keps/sig-cloud-provider/providers/2530-alibaba-cloud/kep.yaml, keps/sig-cloud-provider/providers/2531-baidu-cloud/README.md, keps/sig-cloud-provider/providers/2531-baidu-cloud/kep.yaml, keps/sig-cloud-provider/providers/2532-huawei-cloud/README.md, keps/sig-cloud-provider/providers/2532-huawei-cloud/kep.yaml
Ref #2220 
/assign @andrewsykim @cheftako
=> Migrate remaining cloud-provider KEPs to new template

keps/sig-scheduling/1451-multi-scheduling-profiles/kep.yaml, keps/sig-scheduling/785-scheduler-component-config-api/kep.yaml
We are releasing a v1beta2 in 1.21 that we intend to graduate to v1 next release.
With it, scheduling profiles will graduate too.
=> Update target stable milestone for scheduler CC

keps/sig-instrumentation/1602-structured-logging/README.md
A prior discussion determined kubectl and kubeadm
as components that should not be migrated.
/cc @ehashman
=> 1602-structured-logging: add note about excluded components

keps/sig-testing/2539-continuously-deploy-k8s-prow/README.md, keps/sig-testing/2539-continuously-deploy-k8s-prow/kep.yaml
As suggested on sig-testing meeting today, creating this KEP for open discussion. This is based off of the design doc presented on sig-testing https://docs.google.com/document/d/1pBouf_tgJJ2Gga9Xa5-xObLjN7PiVXiBzL3RYTy56ng.
This proposal is aiming at automate the deployment of k8s prow for easing prow oncall workloads.
=> KEP: (sig-testing) continuously deploy k8s prow

OWNERS_ALIASES
@LappleApple and I would like to propose the following leadership additions to the Enhancements subproject:
- Add @kikisdeliveryservice as subproject owner
- Add @annajung and @palnabarun as `enhancements-reviewers`
- Add @palnabarun to `kep-tools-reviewers`
Each of these contributors have been shining examples of leadership and have deep knowledge of the process as it has evolved the last few cycles.
/hold for approval from @kubernetes/enhancements and @kubernetes/sig-architecture-leads 
cc: @kubernetes/sig-release-leads @kubernetes/release-team-leads 
/assign @LappleApple @dims @jeremyrickard @johnbelamaric
=> OWNERS: Update Enhancements subproject owners

keps/sig-instrumentation/647-apiserver-tracing/README.md
I'm making some updates to the KEP based on feedback in the implementation PR: https://github.com/kubernetes/kubernetes/pull/94942
Major Changes:
* Remove service from the configuration
* Add sampling rate to the configuration
* Add User Stories
Naming Updates:
* Rename Master->ControlPlane
* Rename OpenTelemetryClientConfiguration->TracingConfiguration
Open Question:
* Should we change from a configuration file to just use flags?
/assign @lavalamp 
cc @logicalhan @lilic @sttts @ehashman @brancz
=> Apiserver tracing updates

keps/sig-node/2411-cri-container-log-rotation/README.md
Update the graduation criteria for GA as one of the
issues mentioned no longer applies.
Based on the comment from https://github.com/kubernetes/kubernetes/issues/64760#issuecomment-773128499, the log loss issue does not apply to CRI container runtimes. Updating the KEP to remove it from the graduation criteria.
Signed-off-by: Urvashi Mohnani <umohnani@redhat.com>
=> Update CRIContainerLogRotation KEP

OWNERS_ALIASES
Following the announcement in https://groups.google.com/g/kubernetes-sig-apps/c/GS7-HNoeDPo/m/aQpoWhqsAwAJ.
=> Replace prydonius with soltysh for sig-apps leads

keps/sig-apps/2185-random-pod-select-on-replicaset-downscale/README.md, keps/sig-apps/2185-random-pod-select-on-replicaset-downscale/kep.yaml
In https://github.com/kubernetes/kubernetes/pull/99212, we mistakenly added this feature gate as `LogarithmicScaleDown`. This is not a huge error, as both are relatively descriptive, but since it is past code freeze it is probably easier to update the KEP to be consistent rather than rename the flag.
There is also a PR to document this flag in https://github.com/kubernetes/website/pull/27221
=> Rename RandomReplicaSetDownScale feature gate to LogarithmicScaleDown

keps/sig-testing/2539-continuously-deploy-k8s-prow/README.md, keps/sig-testing/2539-continuously-deploy-k8s-prow/kep.yaml
This is updating KEP-2539 based on comments from https://github.com/kubernetes/enhancements/pull/2540
=> KEP-2539: Addressing comments from #2540

keps/sig-node/1287-in-place-update-pod-resources/README.md
This was originally not really intended to be committed, but to get the questions debated and answered.  Now that most of the details are hammered out, we should probably keep it.
@vinaykul
=> API modifications for in-place pod resize KEP

keps/sig-autoscaling/853-configurable-hpa-scale-velocity/README.md
The `Disabled` value for `selectPolicy` was implemented after the KEP was merged.
=> Updated Scaling Behavior KEP to reflect implementation

keps/sig-storage/1698-generic-ephemeral-volumes/README.md, keps/sig-storage/1698-generic-ephemeral-volumes/kep.yaml
This addresses some TODOs from the PRR review.
The metrics PR has been merged: https://github.com/kubernetes/kubernetes/pull/99115
=> generic ephemeral volumes: document metrics and tests

hack/.notableofcontents
On the version of grep shipped with macs, the blank line in the `hack/.notableofcontents` file matches everything, breaking the `hack/update-toc.sh` script.
=> Delete blank line from .notableofcontents

keps/sig-cluster-lifecycle/kubeadm/2568-kubeadm-non-root-control-plane/README.md, keps/sig-cluster-lifecycle/kubeadm/2568-kubeadm-non-root-control-plane/kep.yaml
This KEP proposes that the control-plane in kubeadm be run as non-root. If containers are running as root an escape from a container may result in the escalation to root in host. CVE-2019-5736 is an example of a container escape vulnerabilty that can be mitigated by running containers/pods as non-root.
xref https://github.com/kubernetes/enhancements/issues/2568
=> KEP-2568: Run control-plane as non-root in kubeadm.

keps/sig-apps/85-Graduate-PDB-to-Stable/README.md
This updates the KEP after PDBs were promoted to GA in 1.21. 
The Eviction API could not be promoted for 1.21, so this also updates the doc with remaining work to get Eviction to GA.
=> Update PDB KEP with latest status

keps/sig-scheduling/624-scheduling-framework/README.md
closes #2603  
change the broken link as shown below with the working link
```diff
- https://github.com/kubernetes/enhancements/blob/master/keps/sig-cluster-lifecycle/wgs/0032-create-a-k8s-io-component-repo.md
+ https://github.com/kubernetes/enhancements/blob/master/keps/sig-cluster-lifecycle/wgs/783-component-base/README.md
```
present in  /keps/sig-scheduling/624-scheduling-framework/README.md
=> Updated the README.md file to change the broken link with the new link

keps/sig-cluster-lifecycle/kubeadm/970-kubeadm-config/README.md, keps/sig-cluster-lifecycle/kubeadm/970-kubeadm-config/kep.yaml
Add updates for v1beta3 which is planned for 1.22.
=> sig-cluster-lifecycle: update the kubeadm config KEP for 1.22

keps/sig-node/277-ephemeral-containers/README.md
This change was requested by SIG auth for compatibility with admission controllers.
=> KEP-277: Use Pod for /ephemeralcontainers

keps/NNNN-kep-template/README.md
I noticed during PRR review in 1.21 that some feature didn't not separately address how an end user could know if a feature was working.  This is particularly problematic when spanning versions where default enabled has changed.
=> refine PRR questions to include how an end user can self-diagnose

keps/NNNN-kep-template/README.md
/cc @johnbelamaric @deads2k @wojtek-t 
As promised from our [PRR meeting review](https://docs.google.com/document/d/10QkXwiZfBL7wBKHHFslooXvGDKHA75jkkgiIXuKFryM/edit#heading=h.vq2bewg3xnhm).
SLIs stem from SLOs, not the other way around. Switched the order and updated the template guidance to match this.
=> Move SLOs above SLIs in PRR template

OWNERS_ALIASES
As part of going fully emeritus, I'm removing myself as a lead from WGs and SIGs.
I've added @irvifa; she's been a SIG Docs chair for well over a year now.
/sig docs
/wg naming
Related PRs:
- https://github.com/kubernetes/community/pull/5733
- https://github.com/kubernetes/org/pull/2649
- https://github.com/kubernetes/website/pull/27637
=> Going emeritus, remove myself and add irvifa

keps/prod-readiness/sig-release/2572.yaml, keps/sig-release/2572-release-cadence/README.md, keps/sig-release/2572-release-cadence/kep.yaml
Enhancement tracking issue: https://github.com/kubernetes/enhancements/issues/2572
cc: @kubernetes/sig-release-leads @kubernetes/sig-architecture-leads @kubernetes/sig-testing-leads
=> sig-release: Add release cadence KEP

keps/sig-apps/2214-indexed-job/README.md, keps/sig-apps/2214-indexed-job/kep.yaml
As part of beta graduation, to support tightly coupled parallel jobs.
As presented in https://github.com/kubernetes/kubernetes/issues/99497#issuecomment-819694258
/sig apps
This PR builds on top of #2616 (beta graduation update with no extra features).
=> Add stable hostname to Indexed job

keps/sig-cli/2299-kustomize-plugin-composition/README.md, keps/sig-cli/2299-kustomize-plugin-composition/example/composition/base/composition.yaml, keps/sig-cli/2299-kustomize-plugin-composition/example/composition/base/resources/configmap.yaml, keps/sig-cli/2299-kustomize-plugin-composition/example/composition/composition.yaml, keps/sig-cli/2299-kustomize-plugin-composition/example/kustomization/kustomization.yaml, keps/sig-cli/2299-kustomize-plugin-composition/example/kustomization/prod-integration-base/builtins-base/kustomization.yaml, keps/sig-cli/2299-kustomize-plugin-composition/example/kustomization/prod-integration-base/builtins-base/resources/configmap.yaml, keps/sig-cli/2299-kustomize-plugin-composition/example/kustomization/prod-integration-base/kustomization.yaml, keps/sig-cli/2299-kustomize-plugin-composition/example/kustomization/prod-integration-base/prod-plugin-transformation/kustomization.yaml, keps/sig-cli/2299-kustomize-plugin-composition/example/kustomization/prod-integration-base/prod-plugin-transformation/plugins-base/kustomization.yaml, keps/sig-cli/2299-kustomize-plugin-composition/example/kustomization/prod-integration-base/prod-plugin-transformation/plugins-base/lb.yaml, keps/sig-cli/2299-kustomize-plugin-composition/example/kustomization/prod-integration-base/prod-plugin-transformation/plugins-base/logger.yaml, keps/sig-cli/2299-kustomize-plugin-composition/example/kustomization/prod-integration-base/prod-plugin-transformation/plugins-base/web-server.yaml, keps/sig-cli/2299-kustomize-plugin-composition/kep.yaml
This KEP proposes a new Kustomize API (`kind`) that is oriented around Kustomize plugins, making them a first-class expression of a resource configuration bundle. This new API provides new sophisticated capabilities for using plugins as composable units and includes support for automatic discovery and installation of plugins. It showcases plugins as a way to implement composable, declarative client-side abstractions. 
Enhancement tracking issue: https://github.com/kubernetes/enhancements/issues/2299
cc @pwittrock @campoy
=> KEP 2299: Kustomize Plugin Composition API

keps/sig-instrumentation/647-apiserver-tracing/kep.yaml
It didn't make it in 1.21 because of godep problems.  Bumping to 1.22
/assign @ehashman
=> move tracing alpha to 1.22

keps/prod-readiness/sig-cluster-lifecycle/2568.yaml, keps/sig-cluster-lifecycle/kubeadm/2568-kubeadm-non-root-control-plane/README.md, keps/sig-cluster-lifecycle/kubeadm/2568-kubeadm-non-root-control-plane/kep.yaml
[KEP-2568](https://github.com/kubernetes/enhancements/tree/master/keps/sig-cluster-lifecycle/kubeadm/2568-kubeadm-non-root-control-plane) proposes that we run the kubeadm control-plane as non-root and follow other security best practices.
=> [KEP-2568] Production Readiness Review.

keps/prod-readiness/sig-apps/2232.yaml, keps/sig-apps/2232-suspend-jobs/README.md, keps/sig-apps/2232-suspend-jobs/kep.yaml
ref: https://github.com/kubernetes/enhancements/issues/2232
/sig apps
/cc @ahg-g @alculquicondor @soltysh @wojtek-t
=> suspended jobs: graduate to beta

keps/sig-network/563-dual-stack/README.md, keps/sig-network/563-dual-stack/kep.yaml
We anticipate keeping dual-stack networking (https://github.com/kubernetes/enhancements/issues/563) listed as beta for 1.22 while we gather user feedback, now that it will be turned on in beta at various providers. We anticipate going to stable for 1.23, depending on said feedback.
This PR contains:
- typo fixes
- implementation plan version additions
- PRR feature-gate clarifications and updates (as it will be behind a feature gate for now, but eventually won't be)
KEP being updated in this PR: https://github.com/kubernetes/enhancements/tree/master/keps/sig-network/563-dual-stack  
=> KEP-563 - dual-stack updates

keps/sig-network/536-topology-aware-routing/README.md, keps/sig-network/536-topology-aware-routing/kep.yaml
This also commits us to removing the implementation in the 1.22 cycle.
/sig network
=> Updating KEP 536 to note that it has been replaced by KEP 2433

keps/sig-windows/1981-windows-privileged-container-support/README.md, keps/sig-windows/1981-windows-privileged-container-support/kep.yaml
Updating milestones for Windows HostProcess container alpha release.
This KEP was approved for v1.21 but implementation PRs did not merge before code freeze so this is slipping into v1.22 release
=> Updating Windows HostProcess container KEP for v1.22 alpha release

keps/sig-cloud-provider/1179-building-without-in-tree-providers/README.md
This change fixes the internal links from the older format to the
currently used directory/document structure.
=> update internal links in kep 1179

keps/prod-readiness/sig-windows/2258.yaml, keps/sig-windows/2258-node-service-log-viewer/README.md, keps/sig-windows/2258-node-service-log-viewer/kep.yaml
KEP to introduce kubectl option for viewing logs of system services on Windows and Linux nodes.
Co-authored-by: Christian Glombek <cglombek@redhat.com>
=> KEP 2258: Node service log viewer

keps/prod-readiness/sig-network/2595.yaml, keps/sig-network/2595-expanded-dns-config/README.md, keps/sig-network/2595-expanded-dns-config/kep.yaml
Enhancement issue: #2595 
previous discussion: https://github.com/kubernetes/kubernetes/pull/100583
=> Add expanded DNS configuration KEP

keps/sig-apps/1847-autoremove-statefulset-pvcs/README.md
Here are changes to the StatefulSet autodelete KEP after going through the api review (k/k PR https://github.com/kubernetes/kubernetes/pull/99378).
/assign @msau42 
=> Update PersistentVolumeClaimPolicy to approved api

keps/sig-network/2433-topology-aware-hints/README.md, keps/sig-network/2433-topology-aware-hints/kep.yaml
This updates the KEP to correctly reference the annotation we ended up settling on in the last cycle (along with a suggested naming update). It also includes significant test plan updates.
Although this sticks with the 1.22 target for beta, I'm not completely sure I'll have the time to get all of the graduation criteria in place for this cycle (most notably the e2e tests). So although this is something I'm hoping to graduate in this cycle, it may not happen. 
/sig network
/cc @andrewsykim @aojea @bowei @maplain 
=> Updating Topology Hints KEP for 1.22

keps/prod-readiness/sig-auth/541.yaml, keps/sig-auth/541-external-credential-providers/README.md
KEP updates needed for this feature set to go GA in 1.22.
1.22 KEP tracking: https://github.com/kubernetes/enhancements/issues/541#issuecomment-799372909.
=> exec credential provider: pre-1.22 stuff (update with shipped metrics API, InteractiveMode API, GA API review)

keps/prod-readiness/sig-apps/1591.yaml, keps/sig-apps/1591-daemonset-surge/README.md, keps/sig-apps/1591-daemonset-surge/kep.yaml
Most of the questions in the PRR section seems answered and if needed they can be answered when GA'ing.
=> Graduate DS maxSurge to beta

keps/prod-readiness/sig-cloud-provider/1959.yaml, keps/sig-cloud-provider/1959-service-lb-class-field/README.md, keps/sig-cloud-provider/1959-service-lb-class-field/kep.yaml
Update Beta graduation criteria and answer PRR questions for beta.
=> KEP-1959: promote loadbalancerclass feature to beta in v1.22.

keps/sig-api-machinery/1040-priority-and-fairness/README.md, keps/sig-api-machinery/1040-priority-and-fairness/kep.yaml
Ref: https://github.com/kubernetes/enhancements/issues/1040
/assign @lavalamp @deads2k 
/cc @MikeSpreitzer @tkashem 
I was playing a bit with the idea on Friday and did a very simple POC of this mechanism (without handling any corner cases): https://github.com/kubernetes/kubernetes/pull/101785 And it works relatively well.
I briefly chatted with David about this idea and he seemed to be supportive [it's surprisingly simple approach and watch initialization is often hitting us during any kube-apiserver restarts with large clusters due to huge number (due to huge number (even hundreds of thousands) of watches of secrets/configmaps].
=> Update P&F KEP with support for watch initialization

keps/prod-readiness/sig-apps/2185.yaml, keps/sig-apps/2185-random-pod-select-on-replicaset-downscale/README.md, keps/sig-apps/2185-random-pod-select-on-replicaset-downscale/kep.yaml
Ref: https://github.com/kubernetes/enhancements/issues/2185
=> Update random pod scaledown KEP for beta

keps/sig-api-machinery/2161-apiserver-default-labels/README.md, keps/sig-api-machinery/2161-apiserver-default-labels/kep.yaml
ref: https://github.com/kubernetes/kubernetes/pull/101342
=> Mark KEP 2161 as implemented and stable

keps/prod-readiness/sig-storage/1855.yaml, keps/sig-storage/1855-csi-driver-service-account-token/README.md, keps/sig-storage/1855-csi-driver-service-account-token/kep.yaml
=> CSIServiceAccountToken going GA

hack/verify-build.sh, keps/NNNN-kep-template/kep.yaml, keps/prod-readiness/template/nnnn.yaml
This PR:
* Cleans the verify-build.sh to build only for amd64 (as we run the tests in amd64 only, right?) cutting a bit the tests time
* Make some statement about creating the PRR file on the right place, removing it from kep.yaml
=> Make some cleanup in KEP PRR template and building scripts

keps/prod-readiness/sig-cli/2590.yaml, keps/sig-cli/2590-kubectl-subresource/README.md, keps/sig-cli/2590-kubectl-subresource/kep.yaml
This KEP proposes adding a `--subresource` flag to kubectl to be able to fetch and update status and scale subresources.
There is a POC implementation at : https://github.com/kubernetes/kubernetes/pull/99556
For issue: https://github.com/kubernetes/enhancements/issues/2590
xref https://github.com/kubernetes/kubectl/issues/564#issuecomment-621327402, https://github.com/kubernetes/kubernetes/issues/15858#issuecomment-624686815, https://github.com/kubernetes/kubernetes/issues/67455
Follow up to https://github.com/kubernetes/kubernetes/pull/60902, https://github.com/kubernetes/kubernetes/pull/67454
=> kubectl subresource KEP

keps/prod-readiness/sig-node/2371.yaml, keps/sig-node/2371-cri-pod-container-stats/README.md, keps/sig-node/2371-cri-pod-container-stats/kep.yaml
=> Add KEP for cAdvisor-less, CRI-full Container and Pod Stats

keps/sig-node/2040-kubelet-cri/README.md, keps/sig-node/2040-kubelet-cri/kep.yaml
This reflects the new requirement of CRI going to Beta that the CRI implementation
must be able to indicate to the Kubelet an image should not be garbage collected.
This functionality will be used in leu of the Kubelet's current behavior
of keeping track of the pause image version to stop the pause image from being garbage collected.
=> Update CRI KEP with pinned Image requirement

keps/prod-readiness/sig-cli/859.yaml, keps/sig-cli/859-kubectl-headers/README.md, keps/sig-cli/859-kubectl-headers/kep.yaml
* Updates `859 kubectl headers` KEP to beta.
* Changes design to use `Kubectl-*` headers instead of `X-Kubectl-*` headers. The IETF now discourages `X-*` headers.
* Updated `Implementation History` section.
* More discussion of `MAX_HEADERS` to mitigate performance risk associated with increased REST call headers size.
* More discussion of `Kubectl-Session` unique identifier header to aggregate multiple REST call headers into a single kubectl invocation.
* Adds @johnbelamaric as PRR approver for beta
=> Update kubectl headers KEP to beta

keps/prod-readiness/sig-apps/961.yaml, keps/sig-apps/961-maxunavailable-for-statefulset/README.md, keps/sig-apps/961-maxunavailable-for-statefulset/kep.yaml
=> Add PRR information for maxUnavailable

keps/prod-readiness/sig-node/1769.yaml, keps/sig-node/1769-memory-manager/README.md, keps/sig-node/1769-memory-manager/kep.yaml
I'd like to follow up on this feature. In 1.22 cyle.
Action Items in 1.22
- Extend e2e testing
- Provide memory manager metrics via pod resources API
- Promote it to beta
Signed-off-by: Artyom Lukianov <alukiano@redhat.com>
=> Graduate memory manager to beta

keps/sig-network/536-topology-aware-routing/kep.yaml
This is a follow up to https://github.com/kubernetes/enhancements/issues/536#issuecomment-840054528.
/sig network
=> Updating latest-milestone to 1.22 for KEP-536

keps/sig-node/281-dynamic-kubelet-configuration/README.md, keps/sig-node/281-dynamic-kubelet-configuration/kep.yaml
I didn't find a good guidance for features deprecation. 
This first update is for deprecation. I think it will be a good idea to update the  PRR-like questionnaire once we will decide to move on with the feature removal. So I left some TODOs in the questions.
/assign @dchen1107 
/sig node
/cc @xlgao-zju
/kind deprecation
=> deprecate Dynamic Kubelet Config feature

keps/sig-node/2133-kubelet-credential-providers/README.md, keps/sig-node/2133-kubelet-credential-providers/kep.yaml
Updates the KEP to target Beta for 1.22
/sig node cloud-provider auth
Signed-off-by: Aditi Sharma <adi.sky17@gmail.com>
=> [KEP-2133]: Update milestone and metadata for Kubelet credential provider

keps/prod-readiness/sig-node/1539.yaml, keps/sig-node/1539-hugepages/README.md, keps/sig-node/1539-hugepages/kep.yaml
Support for multiple sizes huge pages was implemented in 1.18 and graduated to beta in 1.19.
Community feedback was positive since then, so it's time to graduate it to GA.
- Renamed release checklist item: 1.19tbd -> 1.19 as hugepages e2e tests
have been implemented in 1.19 time frame
- Updated release checklist and implementation history for release 1.22
k8s PR: kubernetes/kubernetes#99144
Documentation PR: kubernetes/website/pull/26664
=> Graduate multiple sizes huge pages to GA

keps/prod-readiness/sig-node/1558.yaml, keps/sig-node/1558-streaming-proxy-redirects/README.md, keps/sig-node/1558-streaming-proxy-redirects/kep.yaml
part of https://github.com/kubernetes/enhancements/issues/1558
In 1.22 (previously: 1.21) kubernetes/kubernetes#101647 is opened.
> Default StreamingProxyRedirects to disabled. If there is a >= 2 version skew between master
> and nodes, and the old nodes were enabling --redirect-container-streaming, this will break
> them. In this case, the StreamingProxyRedirects can still be manually enabled.
=> update streaming proxy redicts status: 1.22. Deprecated and default false

keps/prod-readiness/sig-node/1287.yaml, keps/prod-readiness/sig-node/2273.yaml, keps/sig-node/1287-in-place-update-pod-resources/README.md, keps/sig-node/1287-in-place-update-pod-resources/kep.yaml, keps/sig-node/2273-kubelet-container-resources-cri-api-changes/README.md, keps/sig-node/2273-kubelet-container-resources-cri-api-changes/kep.yaml
As per updated process for KEP inclusion into release milestone, a Production Readiness Review (PRR) section is needed. Adding it, with answers required for items for alpha feature target.
=> Request PRR approval for two KEPs: "In-place Pod Vertical Scaling" and "Kubelet CRI extension for In-Place Pod Vertical Scaling"

keps/prod-readiness/sig-network/2365.yaml, keps/sig-network/2365-ingressclass-namespaced-params/README.md, keps/sig-network/2365-ingressclass-namespaced-params/kep.yaml
Graduating [Namespace Scoped Ingress Class Parameters KEP-2365](https://github.com/kubernetes/enhancements/issues/2365) to beta for v1.22.
=> KEP-2365: graduate to beta

keps/sig-api-machinery/555-server-side-apply/README.md, keps/sig-api-machinery/555-server-side-apply/kep.yaml
=> Update SSA GA to 1.22

keps/sig-storage/1495-volume-populators/README.md, keps/sig-storage/1495-volume-populators/kep.yaml
Add a new `DataSourceRef` field to reduce risk of breakage to zero.
Remain in alpha one more release.
=> Redesign volume populators API

keps/prod-readiness/sig-network/1669.yaml, keps/prod-readiness/sig-network/1672.yaml, keps/sig-network/1669-graceful-termination-local-external-traffic-policy/README.md, keps/sig-network/1669-graceful-termination-local-external-traffic-policy/kep.yaml, keps/sig-network/1672-tracking-terminating-endpoints/README.md, keps/sig-network/1672-tracking-terminating-endpoints/kep.yaml
https://github.com/kubernetes/enhancements/issues/1669
https://github.com/kubernetes/enhancements/issues/1672
=> KEP-1669 & KEP-1672 updates for v1.22

keps/prod-readiness/sig-storage/1495.yaml, keps/sig-storage/1495-volume-populators/README.md, keps/sig-storage/1495-volume-populators/kep.yaml
This feature was planned to go to beta, but API review required another API change that required the feature to stay alpha. The KEP was updated, but the change to the stage field in key.yaml was overlooked.
=> Change populators stage back to alpha

keps/sig-cli/859-kubectl-headers/README.md
* Adds missing `Graduation Criteria` section for alpha -> beta for SIG CLI 859 kubectl commands headers KEP
* Fixes typo.
=> Adds alpha -> beta graduation criteria to KEP

keps/sig-windows/1981-windows-privileged-container-support/README.md
Adding note to make sure we remove the annotations support for Beta once Containerd support hostprocess.
xref: https://github.com/kubernetes/kubernetes/pull/99576#discussion_r635392090
Also update the graduation criteria to clarify that the requirements were for alpha -> beta and beta -> ga
/sig windows
=> Update with addtional alpha -> beta criteria

keps/prod-readiness/sig-node/2033.yaml, keps/sig-node/2033-kubelet-in-userns-aka-rootless/README.md, keps/sig-node/2033-kubelet-in-userns-aka-rootless/kep.yaml
Allow running the entire Kubernetes components (`kubelet`, CRI, OCI, CNI, and all `kube-*`) as a non-root user on the host, by using a user namespace and cgroup v2 (https://github.com/kubernetes/enhancements/pull/1370).
Rootless mode has been already adopted by [k3s](https://github.com/k3s-io/k3s/blob/master/k3s-rootless.service).
Also, [kind already supports Rootless Docker/Podman, with unmodified Kubernetes](https://kind.sigs.k8s.io/docs/user/rootless/), but it uses very dirty hack to avoid sysctl errors, so this KEP still has to be accepted.
Replaces https://github.com/kubernetes/enhancements/pull/1084
- - -
POC: https://github.com/rootless-containers/usernetes
Kubernetes PR: https://github.com/kubernetes/kubernetes/pull/92863
Tracking issue: …
=> sig-node: Kubelet-in-UserNS, aka Rootless mode

keps/sig-cli/1802-kustomize-components/README.md, keps/sig-cli/1802-kustomize-components/kep.yaml, keps/sig-cli/2206-openapi-features-in-kustomize/README.md, keps/sig-cli/2206-openapi-features-in-kustomize/kep.yaml, keps/sig-cli/2299-kustomize-plugin-composition/kep.yaml, keps/sig-cli/2377-Kustomize/README.md, keps/sig-cli/2383-extend-kustomize-patches-to-multiple-targets/README.md, keps/sig-cli/2383-extend-kustomize-patches-to-multiple-targets/kep.yaml, keps/sig-cli/993-kustomize-generators-transformers/README.md, keps/sig-cli/993-kustomize-generators-transformers/kep.yaml
This PR updates the KEP metadata and implementation history for several Kustomize-related KEPs that have already been implemented (alpha or beta).
Where the latest-milestone field was set to zero but the implementation has already merged, I looked up which Kubernetes release cycle it merged in. LMK if that's not the right thing to do.
I used the following heuristic for "stage": If it is behind an alpha flag, it's alpha. If it's a KRM resource or field therein, use the resource's version (i.e. beta for Kustomization and alpha for Component).
I'll make similar updates to the tracking issues. Here's what I think we should do for each after it is updated:
- #993 (tranformers/generators): still in alpha, leave open. To be closed when replaced with a beta graduation KEP, which I intend to work …
=> Kustomize KEP cleanup

keps/sig-storage/2485-read-write-once-pod-pv-access-mode/README.md, keps/sig-storage/2485-read-write-once-pod-pv-access-mode/kep.yaml
Updating the `kep.yaml` to include the reviewers, approvers, and prr-approvers for the previous round of KEP review.
Also included are scheduling design details, @alculquicondor and I discussed offline. Updating the `kep.yaml` to include sig-scheduling to ensure their feedback is present.
/assign @BenTheElder 
/assign @alculquicondor
=> KEP-2485: Update reviewers and approvers, scheduling design details

keps/sig-node/2413-seccomp-by-default/README.md
This patch reflects the latest changes from the implementation PR:
- Adding the kubelet configuration and CLI flag.
- Making the rollout strategy more verbose and add mitigations.
Refers to: https://github.com/kubernetes/enhancements/issues/2413
Triggered by: https://github.com/kubernetes/kubernetes/pull/101943
cc @pjbgf @liggitt @mmdriley PTAL
=> Update SeccompDefault KEP upgrade strategy

keps/sig-testing/2420-reducing-kubernetes-build-maintenance/README.md
see: https://github.com/kubernetes/enhancements/issues/2420
This KEP is now done except for the passive phase out of older release branches still using bazel, and any remaining cleanup we may consider after that is done.
=> update reducing kubernetes build maintenance status

README.md, docs/glossary.md
Signed-off-by: Anna Jung (VMware) <antheaj@vmware.com>
- Add a glossary of frequently used enhancement related terms and link to relevant pages
fixes https://github.com/kubernetes/enhancements/issues/2517
=> Add glossary doc

keps/sig-storage/2485-read-write-once-pod-pv-access-mode/README.md, keps/sig-storage/2485-read-write-once-pod-pv-access-mode/kep.yaml
- One-line PR description: Scheduler changes for beta graduation criteria, remove kube-controller-manager from feature gate consumers
- Issue link: https://github.com/kubernetes/enhancements/issues/2485
- Other comments: Included is a small change to remove the kube-controller-manager from the feature gate consumer list, it is not required for adding the feature
/assign @alculquicondor 
/assign @ahg-g
=> KEP-2485: Scheduler changes for beta graduation criteria

keps/prod-readiness/sig-auth/2784.yaml, keps/sig-auth/2784-csr-duration/README.md, keps/sig-auth/2784-csr-duration/kep.yaml
/sig auth
/assign @liggitt @smarterclayton @mikedanese
=> CSR Duration KEP

OWNERS_ALIASES
Also, remove jeefy from sig-ui-leads
Contexts:
* https://groups.google.com/g/kubernetes-dev/c/_sGC7W4YiVc/m/QkePzg--AgAJ
* https://github.com/kubernetes/community/pull/5840
=> Add shu-mutou to sig-ui-leads

keps/sig-apps/2599-minreadyseconds-for-statefulsets/README.md
During the KEP reading club meeting which happened on 06/21/2021, following points were brought up:
- Why can't we have the minReadySeconds field in pod spec so that other controllers like endpoints controller can leverage it
- How does this field interplay with existing containerProbes.
I tried clarifying about points with this commit
@dims @thockin
=> Clarify StatefulSets minReadySeconds

keps/sig-apps/2185-random-pod-select-on-replicaset-downscale/README.md
- One-line PR description: Updates the metric name to reflect changes in implementation PR: https://github.com/kubernetes/kubernetes/pull/101767
- Issue link: https://github.com/kubernetes/enhancements/issues/2185
=> KEP-2185: Update metric name in Random Pod Downscale KEP

keps/sig-api-machinery/1040-priority-and-fairness/README.md
- One-line PR description: Updates the shuffle sharding technique in APF to account for general request width and extra latency.
- Issue link:
=> KEP-1040: Generalize shuffle sharding for req width and extra latency

keps/prod-readiness/sig-scheduling/785.yaml, keps/sig-scheduling/785-scheduler-component-config-api/README.md, keps/sig-scheduling/785-scheduler-component-config-api/kep.yaml
Add notes for v1beta2.
Remove target milestone for GA.
Note that PRR was completed for 1.19, even though it was optional.
Ref kubernetes/enhancements#785
=> Update KEP for Scheduler CC in beta

keps/prod-readiness/sig-node/277.yaml, keps/sig-node/277-ephemeral-containers/kep.yaml
- One-line PR description: updating KEP-277 milestones for 1.22 release
- Issue link: #277 
- Other comments: Updating per [exception](https://groups.google.com/g/kubernetes-sig-release/c/1A49p2cGl_4/m/vYS0f46CAAAJ) for 1.22
=> KEP-277: Update milestone metadata for 1.22 cycle

keps/sig-instrumentation/647-apiserver-tracing/README.md, keps/sig-instrumentation/647-apiserver-tracing/kep.yaml
- One-line PR description: Modifying test requirements
- Other comments:  Based on https://github.com/kubernetes/kubernetes/pull/103234#pullrequestreview-707591464, e2e testing by deploying a collector on the master isn't feasible.  We are going to use an integration test instead.
/assign @logicalhan @ehashman
=> KEP-647: Change apiserver tracing to use an integration, rather than e2e test

keps/sig-auth/541-external-credential-providers/README.md, keps/sig-auth/541-external-credential-providers/kep.yaml
- One-line PR description: KEP updates for GA RC
- Issue link: https://github.com/kubernetes/enhancements/issues/541
- Other comments: marking this as WIP until v1 docs merge (https://github.com/kubernetes/website/pull/28429)
/cc @enj 
/sig auth
=> KEP-541: KEP updates for GA RC

keps/sig-network/563-dual-stack/README.md
As per the PR https://github.com/kubernetes/kubernetes/pull/97979, the family of the first ip in "--node-ip" parameter would determine the primary pod IP. The dual stack KEP currently mentions parameter "--cluster-cidr" to be the deciding factor. This PR is for correcting the KEP to have the correct parameter mentioned.
=> Dual stack KEP: correcting primary pod IP assignment criteria

OWNERS_ALIASES
Updating SIG Docs chairs.
Ref: https://github.com/kubernetes/website/issues/29354
/cc @parispittman @sftim
=> OWNERS: Update SIG Docs Chairs

api/approval.go, api/groups.go, api/proposal.go, go.mod, keps/sig-network/2595-expanded-dns-config/kep.yaml, keps/sig-node/2727-grpc-probe/kep.yaml, pkg/output/output.go, pkg/repo/repo.go, pkg/repo/repo_test.go, pkg/repo/write.go, pkg/repo/write_test.go, pkg/yaml/yaml.go
Prompted by
https://github.com/kubernetes/enhancements/pull/2867#issuecomment-899887426
I decided it would be worth having tests enforce that fields in
KEP-related yaml are well known (vs. allowing addition of unknown
fields)
This codebase largely used `gopkg.in/yaml.v3` but also `sigs.k8s.io/yaml` in
some places, which each have different ways of accomplishing "return
error if there are unknown or duplicate fields" functionality.  I opted
to pull calls to `yaml.Unmarshal` and `yaml.Marshal` into a helper
package, `k8s.io/enhancements/pkg/yaml`, so there's only one place to
change for yaml-related changes.
I then converged on a `gopkg.in/yaml.v3` implementation of
`yaml.UnmarshalStrict` to accomplish erroring on unknown fields, and
corrected the KEPs that failed tests as a result. The …
=> keps: centralize yaml calls, use UnmarshalStrict

keps/sig-testing/2290-new-label-for-trusted-PR-identification/README.md, keps/sig-testing/2290-new-label-for-trusted-PR-identification/kep.yaml, keps/sig-testing/2291-presubmit-config-inside-the-tested-repo/README.md, keps/sig-testing/2291-presubmit-config-inside-the-tested-repo/kep.yaml, keps/sig-testing/2420-reducing-kubernetes-build-maintenance/README.md, keps/sig-testing/2420-reducing-kubernetes-build-maintenance/kep.yaml, keps/sig-testing/2464-kubetest2-ci-migration/kep.yaml, keps/sig-testing/2539-continuously-deploy-k8s-prow/README.md, keps/sig-testing/2539-continuously-deploy-k8s-prow/kep.yaml, keps/sig-testing/714-break-test-tarball/README.md, keps/sig-testing/714-break-test-tarball/kep.yaml
If folks would prefer I break this up into a PR-per-KEP I can do that
too...
I wanted to make sure the output of `kepctl query --sig testing`
reflected reality. A number of fields were missing or stale, so I
reconciled:
- if we're aiming for graduation this cycle,the KEP is `status: implementable`
and `stage: the-target-stage-for-this-release`
- if this is a retroactive change, the KEP is `status: implemented` and
`stage: whatever-stage-was-reached`
- KEPs done before we had formal graduation criteria or implementation
history had best guesses added
- a `scope: out-of-tree` field was added to KEPs primarily covering code
not in kubernetes/kubernetes
- a `scope: in-tree` field was added to KEPs primarily covering code in
kubernetes/kubernetes, even if it wasn't compiled into a release …
=> keps/sig-testing: refresh KEP status

keps/prod-readiness/sig-apps/592.yaml, keps/sig-apps/592-ttl-after-finish/README.md, keps/sig-apps/592-ttl-after-finish/kep.yaml
- One-line PR description: This PR graduates TTL for completed jobs to stable in 1.23
- Issue link: Enhancement issue: #592[https://github.com/kubernetes/enhancements/issues/592]
- Other comments: This was spoken about in the sig-apps meeting on 7/26.
=> KEP-592: Graduate TTL after finish to stable

keps/sig-network/563-dual-stack/README.md, keps/sig-network/563-dual-stack/kep.yaml
We anticipate moving IPv4/IPv6 dual-stack networking to stable in 1.23.
- Issue link:
https://github.com/kubernetes/enhancements/issues/563
- This PR contains:
KEP updates for https://github.com/kubernetes/enhancements/tree/master/keps/sig-network/563-dual-stack  
=> KEP-563 - Moving IPv4/IPv6 dual-stack networking to stable in 1.23

keps/sig-apps/961-maxunavailable-for-statefulset/kep.yaml
=> KEP: 961: Updating release info maxUnavailable for StatefulSet

keps/sig-apps/19-Graduate-CronJob-to-Stable/kep.yaml
Per https://github.com/kubernetes/enhancements/issues/19#issuecomment-902261629 request this marks cronjob KEP as implemented. 
/assign @ravisantoshgudimetla @salaxander
=> Mark KEP-19 (CronJobs) implemented

keps/sig-network/2433-topology-aware-hints/kep.yaml
- One-line PR description: Updates Topology Aware Hints KEP for 1.23 - was already approved for beta, just needed to change target release versions.
/sig network
=> Updating Topology Aware Hints KEP for 1.23

keps/sig-node/277-ephemeral-containers/README.md
Add suggestions and code base TODOs as graduation criteria so we don't lose track of them.
Ref: https://github.com/kubernetes/kubernetes/pull/99576/files/75c9e1c926e06c8ddab9f38569ae8424fdf57e35#r632577140
=> KEP-277: additional graduation criteria

keps/sig-scheduling/785-scheduler-component-config-api/README.md
- One-line PR description:  Remove scheduler policy and mark scheduler ComponentConfig v1beta1 as deprecated
- Issue link: https://github.com/kubernetes/enhancements/issues/2901
- Other comments: An `Implementation History` update of kep https://github.com/kubernetes/enhancements/pull/2850
=> KEP-2901: remove scheduler policy and cc v1beta1

pkg/proposal/promote.go, pkg/repo/query.go, pkg/repo/repo.go
Related:
- Followup to https://github.com/kubernetes/enhancements/pull/2927
- Based on trying to run https://github.com/kubernetes/community/blob/master/sig-architecture/production-readiness.md#finding-keps-needing-prod-readiness-review
I wanted to run the same command a PRR approver is going to run to see
if my KEP PR would show up in their query. I discovered that:
- remote KEP PR loading was slow
- remote KEP PR loading was broken
See commits for details, but tl;dr:
- remote KEP PR loading works now (I'm not sure when it broke or if it ever worked) and has debug logging
- the command in question is faster now (took ~1m40s locally)
- PRR error messages reference the KEP in question for easier diagnosis
=> kepctl query: fix remote KEP loading

keps/prod-readiness/sig-storage/1698.yaml, keps/sig-storage/1698-generic-ephemeral-volumes/README.md, keps/sig-storage/1698-generic-ephemeral-volumes/kep.yaml
- One-line PR description: migration to GA
- Issue link: https://github.com/kubernetes/enhancements/issues/1698
No technical changes since beta and feedback from users has been positive,
therefore GA is targeted for 1.23.
/cc @wojtek-t @msau42
=> KEP-1698: generic ephemeral volumes: GA

keps/prod-readiness/sig-auth/2579.yaml, keps/sig-auth/2579-psp-replacement/README.md, keps/sig-auth/2579-psp-replacement/kep.yaml
- One-line PR description: beta updates for PodSecurity
- Issue link: #2579 
- Best reviewed commit-by-commit (for most reviewers, there's only a single relevant commit)
/sig auth
=> KEP-2579: PodSecurity beta / 1.23 updates

keps/prod-readiness/sig-node/277.yaml, keps/sig-node/277-ephemeral-containers/README.md, keps/sig-node/277-ephemeral-containers/kep.yaml
- One-line PR description: Updating ephemeral containers KEP for beta in 1.23
- Issue link: #277
- Other comments: This KEP was approved for beta for 1.21 in #2244 but then reverted to alpha in order to make an API change that landed in 1.22.
- Changes to the KEP in this PR include:
- Placing the removal of ephemeral containers out of scope for this KEP. It will be addressed in a future proposal.
- Updating PRR questions for names that changed during implementation
=> KEP-277: Update for beta in 1.23

keps/prod-readiness/sig-network/2365.yaml, keps/sig-network/2365-ingressclass-namespaced-params/kep.yaml
- Issue link: https://github.com/kubernetes/enhancements/issues/2365
Marking the enhancement as stable for v1.23 cycle as it meets graduation criteria.
=> KEP-2365: Mark as stable for v1.23

keps/sig-network/2594-multiple-cluster-cidrs/README.md, keps/sig-network/2594-multiple-cluster-cidrs/kep.yaml
Issue: https://github.com/kubernetes/enhancements/issues/2593
=> Support Multiple Cluster CIDRs

keps/prod-readiness/sig-apps/2879.yaml, keps/sig-apps/2879-ready-pods-job-status/README.md, keps/sig-apps/2879-ready-pods-job-status/kep.yaml
Ref #2879
Proposed the addition of field `Job.status.ready`.
Includes PRR
=> KEP-2879: Add count of ready Pods in Job status

keps/prod-readiness/sig-network/1864.yaml, keps/sig-network/1864-disable-lb-node-ports/kep.yaml
- One-line PR description: promote ServiceLBNodePortControl to GA in v1.23
- Issue link: https://github.com/kubernetes/enhancements/issues/1864
=> kep-1864: promote ServiceLBNodePortControl to GA

keps/prod-readiness/sig-network/2829.yaml, keps/sig-network/2829-gateway-api-to-k8s-io/README.md, keps/sig-network/2829-gateway-api-to-k8s-io/kep.yaml
- One-line PR description: This KEP is to formalize the Gateway API transition to k8s.io group and ensure we have reviewers in place that can actually review the v1alpha2 API when it is ready (hopefully mid August).
- Issue link: #2829
- Other comments: This is largely a formality of the official Kubernetes API review process, much of the traditional KEP content is not applicable.
/cc @andrewsykim @danwinship @khenidak @bowei @jpeach @hbagdi
/assign @thockin @johnbelamaric
=> KEP-2829: Formalize Gateway API transition to k8s.io group

keps/prod-readiness/sig-network/2594.yaml, keps/sig-network/2594-multiple-cluster-cidrs/README.md, keps/sig-network/2594-multiple-cluster-cidrs/kep.yaml
- One-line PR description: PR Review for [KEP 2594](https://github.com/kubernetes/enhancements/tree/master/keps/sig-network/2594-multiple-cluster-cidrs
) and marking implementable for alpha
=> KEP-2594 implementable for alpha

keps/prod-readiness/sig-testing/2420.yaml, keps/prod-readiness/sig-testing/2464.yaml, keps/sig-testing/2420-reducing-kubernetes-build-maintenance/kep.yaml, keps/sig-testing/2464-kubetest2-ci-migration/kep.yaml
Broken out of https://github.com/kubernetes/enhancements/pull/2867
KEPs this proposes for graduation in v1.23:
- graduate to stable: https://github.com/kubernetes/enhancements/issues/2420
- graduate to beta: https://github.com/kubernetes/enhancements/issues/2464
/hold
For https://github.com/kubernetes/enhancements/pull/2867 to merge
=> keps/sig-testing: propose v1.23 graduations

keps/prod-readiness/sig-storage/1682.yaml, keps/sig-storage/1682-csi-driver-skip-permission/README.md, keps/sig-storage/1682-csi-driver-skip-permission/kep.yaml
Moving CSIVolumeSupportFSGroup to GA in 1.23
- Issue link: https://github.com/kubernetes/enhancements/issues/1682
=> KEP-1682: Move CSIVolumeSupportFSGroup to GA

keps/prod-readiness/sig-storage/2644.yaml, keps/sig-storage/2644-honor-pv-reclaim-policy/README.md, keps/sig-storage/2644-honor-pv-reclaim-policy/kep.yaml
Prevent volumes from being leaked by honoring the PV delete reclaim policy if for a bound PV-PVC pair, the PV is deleted first followed by deleting the PVC.
Enhancement issue: #2644
Signed-off-by: Deepak Kinni <dkinni@vmware.com>
=> Honor Persistent Volume Reclaim Policy

keps/prod-readiness/sig-node/2403.yaml, keps/sig-node/2403-pod-resources-allocatable-resources/README.md, keps/sig-node/2403-pod-resources-allocatable-resources/kep.yaml
One-line PR description: Update PodResource API GetAllocatableResource 1.23 Beta
Issue link: Extend podresources API to report allocatable resources https://github.com/kubernetes/enhancements/issues/2403
Other comments:  
- Introduced as an alpha feature in 1.21 https://github.com/kubernetes/kubernetes/pull/95734
Signed-off-by: Swati Sehgal <swsehgal@redhat.com>
/sig node
=> KEP-2403: Update PodResource API GetAllocatableResource 1.23 Beta

keps/prod-readiness/sig-node/2902.yaml, keps/sig-node/2902-cpumanager-distribute-cpus-policy-option/README.md, keps/sig-node/2902-cpumanager-distribute-cpus-policy-option/kep.yaml
- One-line PR description: Adding new KEP
- Issue link:  #2902
=> KEP-2902: Add CPUManager policy option to distribute CPUs across NUMA nodes instead of packing them

keps/sig-node/2712-pod-priority-based-graceful-node-shutdown/kep.yaml
Updates milestone for the kep for 1.23
- Issue link: 
https://github.com/kubernetes/enhancements/issues/2712
Signed-off-by: Mrunal Patel <mpatel@redhat.com>
@deads2k @bobbypage ptal
=> KEP-2712: Update milestone for Pod Priority Based Graceful Node Shutdown

keps/prod-readiness/sig-node/2625.yaml, keps/sig-node/2625-cpumanager-policies-thread-placement/README.md, keps/sig-node/2625-cpumanager-policies-thread-placement/kep.yaml
One-line PR description: Update CPU Manager Policy Options 1.23 Beta
Issue link: https://github.com/kubernetes/enhancements/issues/2625
- Introduced as an alpha feature in 1.22 https://github.com/kubernetes/kubernetes/pull/101432
Other comments:  
- This PR updates the KEP to capture the policy name `full-pcpus-only`
based on the implementation merged in 1.22.
- Explains the use of this feature for introduction another policy option
- Changes pertaining to promotion to Beta
Signed-off-by: Swati Sehgal <swsehgal@redhat.com>
=> KEP-2625: Update CPU Manager Policy Options 1.23 Beta

keps/prod-readiness/sig-node/2400.yaml, keps/sig-node/2400-node-swap/README.md, keps/sig-node/2400-node-swap/kep.yaml
- One-line PR description: Update node swap KEP to 1.23 beta
- Issue link: #2400 
/sig node
=> KEP-2400: Update swap KEP for 1.23 beta

keps/prod-readiness/sig-scheduling/2926.yaml, keps/sig-scheduling/2926-job-mutable-scheduling-directives/README.md, keps/sig-scheduling/2926-job-mutable-scheduling-directives/kep.yaml
- One-line PR description: adding new KEP for allowing to update node affinity constraints of suspended jobs
- Issue link: #2926
=> KEP-2926: Allow updating scheduling directives of suspended jobs

keps/prod-readiness/sig-windows/2802.yaml, keps/sig-windows/2802-identify-windows-pods-apiserver-admission/README.md, keps/sig-windows/2802-identify-windows-pods-apiserver-admission/kep.yaml
https://github.com/kubernetes/enhancements/issues/2802
- Issue link:
=> Identify Pod's OS during API Server admission

keps/prod-readiness/sig-network/563.yaml, keps/sig-network/563-dual-stack/README.md, keps/sig-network/563-dual-stack/kep.yaml
Per @johnbelamaric in https://github.com/kubernetes/enhancements/issues/563#issuecomment-915537950 we need this KEP status to be correctly listed as "implementable" until completely done.
=> KEP-563: PRR updates for dual-stack move to stable

keps/sig-node/2371-cri-pod-container-stats/README.md, keps/sig-node/2371-cri-pod-container-stats/kep.yaml
This fixes some nits found in the cri stats kep. They're mostly cosmetic:
- drops some TODOs (as we've figured out what to do)
- Updates some spacing
- Fixes some names to be more clear/consistent
more detail in each commit
- Issue link:
- https://github.com/kubernetes/enhancements/pull/2364
=> KEP-2371: update kep to reflect current state of enhancement

keps/sig-cluster-lifecycle/kubeadm/1739-customization-with-patches/README.md, keps/sig-cluster-lifecycle/kubeadm/1739-customization-with-patches/kep.yaml
The customization with patches graduated to Beta as part of the
the work in the KEP 970 (added in the kubeadm v1beta3 API) during
the 1.22 release cycle.
https://github.com/kubernetes/enhancements/issues/970
Retroactively update the KEP for customization with patches to Beta
as the related actions were completed.
- Issue link:
https://github.com/kubernetes/enhancements/issues/1739
NONE
=> KEP-1739: retro-update the customization with patches to Beta

keps/sig-cli/2229-kubectl-xdg-base-dir/README, keps/sig-cli/2229-kubectl-xdg-base-dir/kep.yaml
This KEP aim to provide all requirements for kubectl use XDG Base Directory Specification.
Issue: https://github.com/kubernetes/enhancements/issues/2229
PR: https://github.com/kubernetes/kubernetes/pull/97885
Signed-off-by: Douglas Schilling Landgraf <dougsland@redhat.com>
=> sig-cli: Use XDG Base Directory Specification

keps/prod-readiness/sig-apps/2599.yaml, keps/sig-apps/2599-minreadyseconds-for-statefulsets/README.md, keps/sig-apps/2599-minreadyseconds-for-statefulsets/kep.yaml
Promote STS minReadySeconds to beta
- Issue link: #2599
=> Promote STS minReadySeconds to beta

keps/prod-readiness/sig-instrumentation/2845.yaml, keps/sig-instrumentation/2845-deprecate-klog-specific-flags-in-k8s-components/README.md, keps/sig-instrumentation/2845-deprecate-klog-specific-flags-in-k8s-components/kep.yaml
Sending PR to move KEP-2845 to implementable to start discussion as there is not a lot of time before code freeze. 
Proposal: https://github.com/kubernetes/enhancements/blob/master/keps/sig-instrumentation/2845-deprecate-klog-specific-flags-in-k8s-components/README.md
Assigning people that already volunteered to review the KEP. Thanks for offering help!
/assign @ehashman @pohly 
Still looking for approver from SIG-Arch side:
@dims, @thockin, @liggitt, @johnbelamaric
Could one of you become KEP approver?
=> Move KEP-2845 to implementable

keps/prod-readiness/sig-api-machinery/2896.yaml, keps/sig-api-machinery/2896-openapi-v3/README.md, keps/sig-api-machinery/2896-openapi-v3/kep.yaml
- One-line PR description: Initial commit for KEP-2896 OpenAPI V3
- Issue link: https://github.com/kubernetes/enhancements/issues/2896
References:
- https://github.com/kubernetes/enhancements/pull/1263
- https://github.com/kubernetes/kubernetes/issues/79472
=> KEP-2896: OpenAPI V3

keps/sig-node/2727-grpc-probe/kep.yaml
KEP #2727 
- One-line PR description: Update the milestone for the KEP
- Other comments: This KEP almost made it to 1.22 and now retargeted to 1.23
=> retarget gRPC probes KEP to 1.23

keps/prod-readiness/sig-api-machinery/2887.yaml, keps/sig-api-machinery/2887-openapi-enum-types/README.md, keps/sig-api-machinery/2887-openapi-enum-types/kep.yaml
- One-line PR description: This PR creates design for KEP-2887 
- Issue link: #2887
/label tide/merge-method-squash
=> KEP-2887: Enum Types for OpenAPI

keps/prod-readiness/sig-storage/2923.yaml, keps/sig-storage/2923-csi-migration-ceph-rbd/README.md, keps/sig-storage/2923-csi-migration-ceph-rbd/kep.yaml
- One-line PR description: Adding new KEP
- Issue link: https://github.com/kubernetes/enhancements/issues/2923
/sig storage
/cc @msau42
=> KEP-2923: Ceph RBD CSI Migration

keps/sig-storage/625-csi-migration/README.md, keps/sig-storage/625-csi-migration/kep.yaml
=> KEP-625: Update feature gate for CSI Migration kep

keps/prod-readiness/sig-storage/2589.yaml, keps/sig-storage/2589-csi-migration-portworx/README.md, keps/sig-storage/2589-csi-migration-portworx/kep.yaml
- One-line PR description: Add KEP for Portworx CSI Migration
- Issue link: https://github.com/kubernetes/enhancements/issues/2589
/sig storage
/cc @msau42
=> KEP-2589: Portworx CSI Migration

keps/sig-api-machinery/1040-priority-and-fairness/README.md
- One-line PR description: Make Fair Queuing discussion match current code
- Issue link:
- Restore original text, before the aspirational fix to do max-min fairness and concurrent dispatching in the virtual world.
- Add factored description, showing first intended behavior and later the implementation trick and issues.
- This PR covers a subset of the changes in #2766 : this PR only restores the description of the current code, while #2766 also adds descriptions of two alternate approaches to fair queuing for server requests.
=> Make Fair Queuing discussion match current code

keps/sig-release/1732-artifact-management/README.md
Part of https://github.com/kubernetes-sigs/promo-tools/issues/424.
- Update references to sigs.k8s.io/promo-tools
- Clean up lint warnings
- Line-wrap at 80 chars 
/assign @puerco @cpanato @ameukam @Verolop 
cc: @kubernetes/release-engineering
=> sig-release(1732): Update references to sigs.k8s.io/promo-tools

keps/sig-release/1734-k8s-image-promoter/kep.yaml
Related:
- Part of: https://github.com/kubernetes/community/issues/6036
- Part of: https://github.com/kubernetes/enhancements/issues/1734
Follow the rename of wg-k8s-infra to sig-k8s-infra
- One-line PR description: Update stakeholder sig
- Issue link: https://github.com/kubernetes/enhancements/issues/1734
=> keps/sig-release: mv wg-k8s-infra sig-k8s-infra

keps/prod-readiness/sig-cli/2299.yaml, keps/sig-cli/2299-kustomize-plugin-composition/README.md, keps/sig-cli/2299-kustomize-plugin-composition/kep.yaml
- One-line PR description: Update KEP contents and add information required to move it to implementable.
- Issue link: https://github.com/kubernetes/enhancements/issues/2299
- Other comments: This update does not change the core of the proposal, though it rewords it significantly for clarity and scope. Notably, terminology has been updated for better consistency with existing Kustomize features (e.g. `module`->`transformer`). Content that actually belonged in the [Catalog KEP](https://github.com/kubernetes/enhancements/pull/2908) instead of here has been removed. This KEP's implications no longer extend beyond the introduction of a new Kind that is processed differently during Kustomize builds.
Please note that this is a Kustomize-internal feature that does not introduce any novel risks. …
=> KEP-2299: Update KEP for move to implementable

keps/sig-api-machinery/2876-crd-validation-expression-language/README.md
I had incorrectly formatted a bunch of link when responding to feedback before the KEP deadline. This fixes all those and responds to one outstanding review comment about testing.
=> Fix formatting, add note about test utilities for 3rd party developers

keps/sig-network/2433-topology-aware-hints/README.md
- One-line PR description: This updates the Topology Hints KEP to exclude Control Plane Nodes
- Other comments: As suggested by @aojea in https://github.com/kubernetes/kubernetes/pull/104744
/cc @aojea @bowei 
=> Updating Topology Hints to exclude Control Plane Nodes

keps/prod-readiness/sig-security/1933.yaml, keps/sig-security/1933-secret-logging-static-analysis/kep.yaml
- One-line PR description:  Correct stable version to 1.23, not 1.22.
- Issue link: #1933
- Other comments:  This change comes at the recommendation of @gracenng as 1.23 enhancement shadow.  Since we recently merged the "official" stable state in the KEP's YAML, it should be reflected in 1.23 for enhancement tracking, not back-dating 1.22 of when scanning became blocking.
- Also, I noticed I left a trailing, empty comment line.  Trimmed that form the YAML.
/sig security
/cc gracenng
=> [KEP-1933] Correct stable version to 1.23, not 1.22

keps/sig-auth/2579-psp-replacement/README.md, keps/sig-auth/2579-psp-replacement/kep.yaml
Update the PodSecurity KEP with some monitoring changes. These changes are motivated by corner cases encountered in the implementation: https://github.com/kubernetes/kubernetes/pull/104217
- Issue link: https://github.com/kubernetes/enhancements/issues/2579
=> [PodSecurity] Update monitoring proposal

keps/sig-multicluster/2149-clusterid/README.md, keps/sig-multicluster/2149-clusterid/kep.yaml
- One-line PR description: Renaming based on community surveys for CR name[1] and API name[2], remove related `[[UNRESOLVED]]` comment block
- Issue link: #2149 
- [1] CR name was decided by SIG-MC community survey, announcement with data is in [this email](https://groups.google.com/g/kubernetes-sig-multicluster/c/90VOAKEMRKQ/m/EYb3eThvCgAJ).
- [2] API name was decided by survey, announcement with data in it is in [this email](https://groups.google.com/g/kubernetes-sig-multicluster/c/KsCecfPE0zY/m/obz49m5qAwAJ).
- Due to targeting a *.k8s.io namespace, the API naming presented here is dependent on formal API review which I will request in a separate PR to unblock this one
=> KEP-2149: adding in community-decided API names

OWNERS, OWNERS_ALIASES
- OWNERS_ALIASES: Sync with k/community
- OWNERS: @justaugustus and @LappleApple are now Emeritus subproject owners
- OWNERS_ALIASES: Promote @palnabarun to `kep-tools-approvers`
Announcement to follow.
Thnks fr th Mmrs!
/assign @mrbobbytables @kikisdeliveryservice @dims 
cc: @kubernetes/enhancements @kubernetes/sig-architecture-leads
=> Stephen & Lauri to Emeritus, Nabarun to KEP tools approver

keps/sig-storage/2317-fsgroup-on-mount/README.md
- One-line PR description: Remove the requirement to add a standalone fsgroup metric, as described in https://github.com/kubernetes/kubernetes/issues/98667
See https://github.com/kubernetes/kubernetes/issues/98667#issuecomment-965821731 for rationale. The relevant fsgroup features for this metric simply defer/reroute fsgroup calls, so the benefit of a metric to identify which code path is exercised would be marginal.
/assign @dims @gnufied
=> KEP-2317: remove requirement of standalone fsgroup metric

keps/sig-storage/625-csi-migration/kep.yaml
Updating the latest milestone to 1.23 because many providers are changing to on-by-default in 1.23
- Issue link:
https://github.com/kubernetes/enhancements/issues/1490
https://github.com/kubernetes/enhancements/issues/1885
https://github.com/kubernetes/enhancements/issues/1487
https://github.com/kubernetes/enhancements/issues/1488
=> KEP-625: Update csimigration milestone to 1.23 to reflect updates for on-by-default

keps/sig-node/2902-cpumanager-distribute-cpus-policy-option/README.md, keps/sig-node/2902-cpumanager-distribute-cpus-policy-option/kep.yaml
Update to accommodate the outcome of the discussion on sig-arch
(https://groups.google.com/u/1/g/kubernetes-sig-architecture/c/Nxsc7pfe5rw)
regarding the handling of feature gates for cpumanager policy options.
=> Change feature gate in KEP-2902 to CPUManagerPolicyAlphaOptions

keps/sig-network/2433-topology-aware-hints/README.md
- One-line PR description: Removes traffic policy interoperability as beta graduation requirement
The interoperability between InternalTrafficPolicy, ExternalTrafficPolicy, and Topology are actively being worked on by @danwinship (thanks!!). I think this is an important thing to get right, but I'm not sure it needs to block beta graduation. I expect the vast majority of users will want to user at most one of these features per Service. Open to other input here. This may all be a non-issue if all the kube-proxy updates and fixes manage to make it into 1.23, but I just wanted to start this conversation a bit earlier in case they don't.
/sig network
/cc @aojea @danwinship
=> KEP-2433: Removing traffic policy interoperability as beta graduation requirement

keps/sig-multicluster/1645-multi-cluster-services-api/README.md
- One-line PR description: Update graduation criteria based on 5/11 SIG-MC discussions
* Removed kube-proxy implementation related items (now consider these an implementation detail0
* Explicitly tied MCS API to Cluster ID KEP's maturity level
* Based on conversation on 5/11 SIG-MC meeting, see [slides](https://docs.google.com/presentation/d/1-zWVm3GplfH0A_4QIxve2rZB6ozc_T2pRTPtXbGgBVM/edit?usp=sharing) (notes in speaker notes) and [meeting recording starting at 7:20](https://youtu.be/bAno54l95VA?t=441)
=> KEP-1645: Update MCS API graduation criteria based on 5/11 SIG-MC discussions

keps/prod-readiness/sig-scheduling/1923.yaml, keps/sig-scheduling/1923-prefer-nominated-node/README.md, keps/sig-scheduling/1923-prefer-nominated-node/kep.yaml
Signed-off-by: Dave Chen <dave.chen@arm.com>
Move PreferNominatedNode to GA
- Issue link:  #1923 
@Huang-Wei @wojtek-t @ahg-g
=> Graduate `PreferNominatedNode` to GA

keps/sig-architecture/2527-clarify-status-observations-vs-rbac/README.md, keps/sig-architecture/2527-clarify-status-observations-vs-rbac/kep.yaml
Since basically the beginning of Kubernetes, we've had this sort of "litmus
test" for status fields: "If I erased the whole status struct, would everything
in it be reconstructed (or at least be reconstructible) from observation?". The
goal was to ensure that the delineation between "what I asked for" and "what it
actually is" was clear and to encourage active reconciliation of state.
Many of our APIs pass this test (sometimes we fudge it and say yes "in
theory"), but not all of them do.  This KEP proposes to clarify or remove this
guidance, especially as it pertains to state that is not derived from
observation.
One of the emergent uses of the spec/status split is access control.  It is
assumed that, for most resources, users own (can write to) all of spec and
controllers own all of …
=> KEP 2527: Clarify meaning of `status`

keps/sig-api-machinery/2876-crd-validation-expression-language/README.md, keps/sig-api-machinery/2876-crd-validation-expression-language/kep.yaml
We've dug into some important details of CEL during implementation. This PR aims to update the KEP to keep it accurate and in-sync, and enable discussion of the decisions before we merge the implementation.
The main points are:
- escaping details
- Validator field access to metadata, and more generally how validation rules defined on the root of the object behave
- handling of int-or-string, embedded and unknown data
@cici37 @sttts @alculquicondor @liggitt @deads2k
=> KEP-2876: CEL expression language: Clarify escaping, root field access, int-or-string/embedded/unknown types

keps/sig-release/3031-signing-release-artifacts/README.md, keps/sig-release/3031-signing-release-artifacts/kep.yaml
- One-line PR description: adding initial draft of the artifact signing enhancement
- Issue link: https://github.com/kubernetes/enhancements/issues/3031
=> KEP-3031: Add release artifact signing KEP

keps/sig-network/563-dual-stack/kep.yaml
* One-line PR description: Dual-stack IPv4/IPv6 Enhancement has graduated to `stable` and can be considered implemented.
* Issue link: [Add IPv4/IPv6 dual-stack support #563](https://github.com/kubernetes/enhancements/issues/563)
* Other comments: 
Fixes https://github.com/kubernetes/enhancements/issues/563
/cc @aojea @caseydavenport @danwinship @dcbw @khenidak @lachie83
=> KEP-563: dual-stack IPv4/IPv6 enhancement is implemented

keps/prod-readiness/sig-api-machinery/1904.yaml, keps/sig-api-machinery/1904-efficient-watch-resumption/README.md, keps/sig-api-machinery/1904-efficient-watch-resumption/kep.yaml
=> Update Efficient Watch Resumption KEP to Stable

keps/prod-readiness/sig-network/3070.yaml, keps/sig-network/3070-reserved-service-ip-range/README.md, keps/sig-network/3070-reserved-service-ip-range/kep.yaml
- One-line PR description: KEP-3070: adding KEP
- Issue link: https://github.com/kubernetes/enhancements/issues/3070
- Other comments: Implementation https://github.com/kubernetes/kubernetes/pull/106792
=> KEP-3070: Reserve Service IP Ranges For Dynamic and Static IP Allocation

keps/sig-cluster-lifecycle/kubeadm/2067-rename-master-label-taint/README.md, keps/sig-cluster-lifecycle/kubeadm/2067-rename-master-label-taint/kep.yaml
Mark the 2067-rename-master-label-taint KEP as implementable for 1.24. It is entering
stage 2, as outlined in the proposal.
- Issue link: https://github.com/kubernetes/enhancements/issues/2067
k/kubeadm: https://github.com/kubernetes/kubeadm/issues/2200
NONE
=> kubeadm: update 2067-rename-master-label-taint for 1.24

keps/sig-cluster-lifecycle/kubeadm/2915-kubeadm-replace-kubelet-config-x.y/README.md, keps/sig-cluster-lifecycle/kubeadm/2915-kubeadm-replace-kubelet-config-x.y/kep.yaml
The feature is graduating to Beta in 1.24.
Update the KEP files to reflect that.
- Issue link: 
https://github.com/kubernetes/enhancements/issues/2915
https://github.com/kubernetes/kubeadm/issues/1582
NONE
=> kubeadm: update 2915-kubeadm-replace-kubelet-config-x.y for 1.24

keps/sig-node/135-seccomp/README.md
Renaming the operator to it's new proposed name.
Refers to https://github.com/kubernetes/org/issues/2177
=> Rename seccomp-operator to security-profiles-operator

keps/sig-node/2129-remove-cadvisor-json-metrics/README.md, keps/sig-node/2129-remove-cadvisor-json-metrics/kep.yaml
Update status of #2129
As https://github.com/kubernetes/kubernetes/pull/99236 is merged.
Fixes #2129
As the website and code are all updated.
=> [1.21]mark Disable CAdvisor Json Metrics as implemented

keps/sig-node/2535-ensure-secret-pulled-images/kep.yaml
Signed-off-by: Mike Brown <brownwm@us.ibm.com>
- One-line PR description: bump kep release targets by one since the PR for the approved kep did not merge in time...
https://github.com/kubernetes/kubernetes/pull/94899
- Issue link: https://github.com/kubernetes/enhancements/issues/2535
Merged kep.. https://github.com/kubernetes/enhancements/pull/1608
=> #2535:ensure secret pulled images - bump targets by one

keps/sig-cli/1441-kubectl-debug/kep.yaml
- One-line PR description: Update KEP-1441 metadata to reflect that work is planned for 1.24 release
- Issue link: #1441
- Other comments: We'll be continuing work on kubectl debug profiles that did not complete in time for 1.23.
=> KEP-1441: Include in 1.24 release

keps/prod-readiness/sig-storage/625.yaml, keps/sig-storage/625-csi-migration/README.md, keps/sig-storage/625-csi-migration/csi-migration-design.md, keps/sig-storage/625-csi-migration/kep.yaml
- One-line PR description: Update CSI Migration to GA
- With components including AWS, GCE PD, Azuredisk go to GA. We declare CSI migration as stable. And will lock the feature flag in the next release.
=> KEP-625: Update CSI Migration to GA

keps/sig-instrumentation/2845-deprecate-klog-specific-flags-in-k8s-components/README.md
- One-line PR description: clarify scope and timeline: removal in 1.26
- Issue link: https://github.com/kubernetes/kubernetes/pull/106090
- Other comments: Deprecating the flags only in some binaries is not going far enough because the full feature set would still have to be supported for the remaining ones.
=> 2845: klog flag deprecation: clarify scope and timeline

keps/sig-windows/2258-node-service-log-viewer/kep.yaml
Update the milestones on the KEP for node service log viewer to 1.24.
=> KEP-2258: Update milestones to 1.24

keps/prod-readiness/sig-storage/2923.yaml, keps/sig-storage/2923-csi-migration-ceph-rbd/README.md, keps/sig-storage/2923-csi-migration-ceph-rbd/kep.yaml
This commit adds the details to the KEP for promoting Ceph RBD CSI
migration from alpha to beta in v1.24
- Issue link:  #2923
=> KEP-2923: adding beta graduation criteria

keps/sig-storage/1682-csi-driver-skip-permission/README.md, keps/sig-storage/1682-csi-driver-skip-permission/kep.yaml
KEP-1682: Mark CSIVolumeSupportFSGroup as implemented
- Issue link: https://github.com/kubernetes/enhancements/issues/1682
=> KEP-1682: Mark CSIVolumeSupportFSGroup as implemented

keps/sig-cluster-lifecycle/kubeadm/2500-kubeadm-join-control-plane-workflow/README.md, keps/sig-cluster-lifecycle/kubeadm/2500-kubeadm-join-control-plane-workflow/kep.yaml, keps/sig-cluster-lifecycle/kubeadm/2501-kubeadm-phases-to-beta/README.md, keps/sig-cluster-lifecycle/kubeadm/2501-kubeadm-phases-to-beta/kep.yaml, keps/sig-cluster-lifecycle/kubeadm/2502-Certificates-copy-for-join-control-plane/README.md, keps/sig-cluster-lifecycle/kubeadm/2502-Certificates-copy-for-join-control-plane/kep.yaml, keps/sig-cluster-lifecycle/kubeadm/2506-Remove-ClusterStatus-from-kubeadm-config/README.md, keps/sig-cluster-lifecycle/kubeadm/2506-Remove-ClusterStatus-from-kubeadm-config/kep.yaml
The work on some of the these enhancements completed a long
time ago. Perform the following cleanup:
- 2500, 2502 (HA features) have been in beta for ~7 releases
and can be considered GA without much changes other than bug fixes.
Separate tracking is already done for future improvements
that may need separate KEPs (e.g. learner mode for etcd). Promote them to GA and close.
- 2051 was about moving the kubeadm phases to beta. "upgrade apply"
still does not have phases, so a separate KEP might be required TBD. Promote the old KEP as Beta / implemented.
- 2506 the work completed in 1.22, when ClusterStatus was removed
from v1beta3. Promote to GA.
clusterstatus: https://github.com/kubernetes/kubeadm/issues/2290
phases for "apply": https://github.com/kubernetes/kubeadm/issues/1318
ha issues: …
=> kubeadm: retroactively update old KEPs

keps/prod-readiness/sig-network/2681.yaml, keps/sig-network/2681-pod-host-ip/README.md, keps/sig-network/2681-pod-host-ip/kep.yaml
If the Pod runs on an enabled IPv6 dual stack node, hope to get the IPv6 address of node
- Field status.hostIPs added for Pod
- Downward API support for status.hostIPs
KEP #2681
issue kubernetes/kubernetes#101565
PR kubernetes/kubernetes#101566
=> KEP-2681: Field status.hostIPs added for Pod

keps/prod-readiness/sig-network/2438.yaml, keps/sig-network/2438-dual-stack-apiserver/README.md, keps/sig-network/2438-dual-stack-apiserver/kep.yaml
- Issue link: https://github.com/kubernetes/enhancements/issues/2438
updates based on the comments in #2622
/assign @thockin @khenidak 
(not urgent at this point, but since it's in response to comments made a few days ago I figure you might want to look at it sooner rather than later)
=> KEP-2438: dual-stack-apiserver updates / clarifications

keps/sig-apps/592-ttl-after-finish/kep.yaml
This PR updates the status to `implemented` for KEP-592 (TTL-after-finish) which recently moved to stable state in 1.23 release.
- Issue link:
https://github.com/kubernetes/enhancements/issues/592
=> Mark TTL-after-finish KEP-592 to implemented

keps/sig-network/1864-disable-lb-node-ports/kep.yaml
- One-line PR description: Update KEP-1864 to stable in v1.24
- Issue link: #1864 
Looks like @uablrek already did the work to promote this to GA in v1.24 (https://github.com/kubernetes/kubernetes/pull/107027), this is just offically updating the KEP to reflect what is already done.
=> KEP-1864: update to stable for v1.24

keps/prod-readiness/sig-apps/2879.yaml, keps/sig-apps/2879-ready-pods-job-status/README.md, keps/sig-apps/2879-ready-pods-job-status/kep.yaml
- One-line PR description: Update milestone for Beta
- Issue link: #2879 
- Added links to testgrid
- The PRR questionnaire was already answered in the alpha release.
=> Graduate Ready Pods in Job status to Beta

keps/prod-readiness/sig-instrumentation/2845.yaml, keps/sig-instrumentation/2845-deprecate-klog-specific-flags-in-k8s-components/kep.yaml
- One-line PR description: describe goal for 1.24
- Issue link: https://github.com/kubernetes/enhancements/issues/2845
=> KEP-2845: klog deprecation: beta in 1.24
