- keps/sig-storage/1432-volume-health-monitor/README.md
- keps/sig-storage/1432-volume-health-monitor/kep.yaml
Add Volume Health to kubelet metrics.
- Issue link: #1432
- Other comments: Staying in Alpha with metrics API changes
> KEP-1432: Update Volume Health KEP to support metrics

- keps/sig-apps/1847-autoremove-statefulset-pvcs/kep.yaml
- One-line PR description: Update latest milestone to 1.23
- Issue link: #1847
> KEP-1847:Update latest milestone to 1.23

- keps/prod-readiness/sig-cluster-lifecycle/2915.yaml
- keps/sig-cluster-lifecycle/kubeadm/2915-kubeadm-replace-kubelet-config-x.y/README.md
- keps/sig-cluster-lifecycle/kubeadm/2915-kubeadm-replace-kubelet-config-x.y/kep.yaml
Initial KEP draft.
- Issue link:
https://github.com/kubernetes/enhancements/issues/2915
NONE
> KEP-2915: add proposal for replacing the kubelet-config-x.y usage

- keps/prod-readiness/sig-storage/1495.yaml
- keps/sig-storage/1495-volume-populators/README.md
- keps/sig-storage/1495-volume-populators/kep.yaml
- One-line PR description: Update Volume Populators to beta
- Issue link: https://github.com/kubernetes/enhancements/issues/1495
> KEP-1495: Update Volume Populators to beta

- keps/prod-readiness/sig-cli/1441.yaml
- keps/sig-cli/1441-kubectl-debug/README.md
- keps/sig-cli/1441-kubectl-debug/kep.yaml
- One-line PR description: Adds new feature for kubectl debug
- Issue link: #1441
- Other comments: Backfills PRR metadata but doesn't change release stage
> KEP-1441: Propose profiles for kubectl debug

- keps/sig-node/2133-kubelet-credential-providers/kep.yaml
Signed-off-by: Aditi Sharma <adi.sky17@gmail.com>
Update beta milestone for Kubelet credential provider KEP
- Issue link:https://github.com/kubernetes/enhancements/issues/2133#issuecomment-914682791
> KEP-2133: Update beta milestone to 1.23 for kubelet credential provider KEP  

- keps/prod-readiness/sig-network/2593.yaml
- keps/sig-network/2593-multiple-cluster-cidrs/README.md
- keps/sig-network/2593-multiple-cluster-cidrs/kep.yaml
- One-line PR description: KEP-2594 needs to be renamed to KEP-2593
- Other comments: I accidentally named the KEP after the initial PR number rather than the Issue number
> Rename KEP-2594 to KEP-2593

- keps/sig-windows/2802-identify-windows-pods-apiserver-admission/README.md
- Issue link:
Update release checklist for #2803
cc @marosset
> Updated release checklist

- keps/sig-autoscaling/2702-graduate-hpa-api-to-GA/kep.yaml
- One-line PR description: Updates latest-milestone to 1.23
- Issue link: https://github.com/kubernetes/enhancements/issues/2702
> KEP-2702: Release milestone Update

- README.md
> update README to add 1.22 & 1.23 tracking sheets

- keps/sig-storage/2485-read-write-once-pod-pv-access-mode/README.md
- One-line PR description: Clarify mapping strategy between K8s and CSI access modes and update mapping table
- Issue link:
- Other comments: The comment on the capability added to the KEP was [copied from the CSI spec](https://github.com/container-storage-interface/spec/blob/v1.5.0/csi.proto#L1073-L1081)
/assign @saad-ali
> KEP-2485: Update access mode mappings between K8s and CSI

- OWNERS_ALIASES
Related:
- Part of https://github.com/kubernetes/community/issues/6036
> OWNERS: mv wg-k8s-infra sig-k8s-infra

- keps/sig-api-machinery/555-server-side-apply/kep.yaml
- One-line PR description: Set SSA KEP to Implemented
- Issue link:https://github.com/kubernetes/enhancements/issues/555
cc @salaxander
> KEP-555: Update SSA Kep to implemented!

- OWNERS_ALIASES
Part of https://github.com/kubernetes/community/pull/6102
/hold on that merging
/cc @eddiezane @pwittrock @soltysh @seans3
> SIG-CLI: KnVerey to lead, pwittrock to emeritus

- keps/sig-scheduling/2926-job-mutable-scheduling-directives/kep.yaml
> update feature name of JobMutableNodeSchedulingDirectives

- keps/sig-storage/556-csi-volume-resizing/README.md
Signed-off-by: zhucan <zhucan.k8s@gmail.com>
-https://github.com/kubernetes/kubernetes/pull/105963
- Issue link: 
> doc: support 'nodeExpandSecretRef' to nodeExpandVolume

- keps/sig-auth/2579-psp-replacement/README.md
Update PodSecurity KEP for beta
- Issue link: #2579 
/sig auth
/cc @tallclair @enj
> KEP-2579: PodSecurity beta updates

- keps/prod-readiness/sig-multicluster/2149.yaml
- keps/sig-multicluster/2149-clusterid/README.md
- keps/sig-multicluster/2149-clusterid/kep.yaml
- One-line PR description: Add in PRR artifact, and attempt to answer PRR questionnaire for alpha on best effort basis as this is an out-of-tree CRD
- Issue link: #2149 
- I'm not sure that it was necessary(/right?) to fill out the PRR questionnaire since this is an out-of-tree component, but I gave it a shot.
> KEP-2149: PRR questionnaire and artifact

- keps/sig-node/2625-cpumanager-policies-thread-placement/README.md
Document the outcome of the discussion on sig-arch
(https://groups.google.com/u/1/g/kubernetes-sig-architecture/c/Nxsc7pfe5rw)
regarding the handling of feature gates for cpumanager policy options.
> KEP-2625: node: cpumanager policy: clarify feature gates

- keps/sig-network/2365-ingressclass-namespaced-params/kep.yaml
- One-line PR description: The feature is being graduated to v1.23. Code and docs have been updated accordingly so marking this as implemented. 
- Issue link: https://github.com/kubernetes/enhancements/issues/2365
/cc @robscott
> Mark 2365 as implemented

- keps/sig-instrumentation/1602-structured-logging/kep.yaml
- One-line PR description: bumps structured logging KEP to 1.23
- Issue link: https://github.com/kubernetes/enhancements/issues/1602
- Other comments: https://github.com/kubernetes/enhancements/issues/1602#issuecomment-973142446
> Bump structured logging to 1.23

- keps/sig-api-machinery/2885-server-side-unknown-field-validation/README.md
- keps/sig-api-machinery/2885-server-side-unknown-field-validation/kep.yaml
:%s/UnknownFieldValidation/ServerSideFieldValidation/g
> 2885 - Update feature gate name

- keps/sig-instrumentation/383-new-event-api-ga-graduation/README.md
- One-line PR description: Require all in-tree components to migrate to new API for GA
- Issue link: https://github.com/kubernetes/enhancements/issues/383
- Other comments: Aligns with https://github.com/kubernetes/enhancements/issues/383#issuecomment-769312331
> KEP-383: Clarify GA requirements for new event API

- keps/sig-storage/177-volume-snapshot/README.md
- One-line PR description: Updated the link to the new location of CSI Volume Snapshot design doc
- Old link: https://github.com/kubernetes/community/blob/master/contributors/design-proposals/storage/csi-snapshot.md
- New link: https://github.com/kubernetes/design-proposals-archive/blob/main/storage/csi-snapshot.md
> KEP-177: Updated the link to the new location of CSI Volume Snapshot design doc

- README.md
> update README.md with links to exception process and current release info

- keps/sig-release/3027-slsa-compliance/README.md
- keps/sig-release/3027-slsa-compliance/kep.yaml
- One-line PR description: Initial Draft
- Issue link: https://github.com/kubernetes/enhancements/issues/3027
> KEP-3027: SLSA Level 3 Compliance in the Kubernetes Release Process

- keps/sig-storage/1698-generic-ephemeral-volumes/kep.yaml
- One-line PR description: mark as implemented
- Issue link: https://github.com/kubernetes/enhancements/issues/1698
> KEP-1698: generic ephemeral volumes: completed in 1.23

- keps/sig-node/213-run-as-group/kep.yaml
Closes #213.
/cc @krmayankk @annajung
> Mark RunAsGroup as GA

- keps/sig-node/2712-pod-priority-based-graceful-node-shutdown/README.md
@derekwaynecarr @bobbypage @mrunalp
kubernetes/kubernetes#102915 errors in documents found during implementation
> Fix KEP 2712

- keps/sig-node/2221-remove-dockershim/README.md
/sig node
/kind cleanup
suggested for discoverability by @sftim
> link to FAQ from the KEP for discoverability

- keps/prod-readiness/sig-scheduling/2249.yaml
- keps/sig-scheduling/2249-pod-affinity-namespace-selector/README.md
- keps/sig-scheduling/2249-pod-affinity-namespace-selector/kep.yaml
- One-line PR description: Graduate PodAffinityNamespaceSelector to stable 
- Issue link: https://github.com/kubernetes/enhancements/issues/2249
> KEP-2249: Graduate PodAffinityNamespaceSelector to stable

- keps/prod-readiness/sig-scheduling/902.yaml
- keps/sig-scheduling/902-non-preempting-priorityclass/README.md
- keps/sig-scheduling/902-non-preempting-priorityclass/kep.yaml
- One-line PR description: Graduate NonPreemptingPriority to GA
- Issue link:  #902 
@wojtek-t @ahg-g @Huang-Wei
> Graduate NonPreemptingPriority to GA

- keps/prod-readiness/sig-api-machinery/1164.yaml
- keps/sig-api-machinery/1164-remove-selflink/README.md
- keps/sig-api-machinery/1164-remove-selflink/kep.yaml
- One-line PR description: Graduate RemoveSelfLink feature to stable
- Issue link: #1164 
- Link to Slack discussion: https://kubernetes.slack.com/archives/C0EG7JC6T/p1641382289464000
/assign @deads2k @lavalamp - for SIG approval
/assign @smarterclayton @deads2k
> Graduate RemoveSelfLink to Stable

- keps/prod-readiness/sig-apps/2232.yaml
- keps/sig-apps/2232-suspend-jobs/README.md
- keps/sig-apps/2232-suspend-jobs/kep.yaml
- Issue link: https://github.com/kubernetes/enhancements/issues/2232
/sig apps
/assign @soltysh @wojtek-t
> KEP-2232: Graduate suspend job to stable

- keps/sig-api-machinery/1040-priority-and-fairness/README.md
P&F KEP already includes support for watch requests.
> Remove support for watch requests from future goals

- keps/prod-readiness/sig-windows/2802.yaml
- keps/sig-windows/2802-identify-windows-pods-apiserver-admission/README.md
- keps/sig-windows/2802-identify-windows-pods-apiserver-admission/kep.yaml
Promote PodOS field to beta
- Issue link: #2802 
> Promote PodOS field to beta

- keps/prod-readiness/sig-scheduling/1258.yaml
- keps/sig-scheduling/1258-default-pod-topology-spread/README.md
- keps/sig-scheduling/1258-default-pod-topology-spread/kep.yaml
DefaultPodTopologySpread graduation to Stable
- Issue link: #1258 
> DefaultPodTopologySpread graduation to Stable

- keps/sig-cli/2590-kubectl-subresource/README.md
- keps/sig-cli/2590-kubectl-subresource/kep.yaml
- One-line PR description: Update milestone of the kubectl subresource KEP along with fixing a few cosmetic errors in text.
- Issue link: https://github.com/kubernetes/enhancements/issues/2590
/assign @soltysh @eddiezane 
/cc @nikhita @ykakarap
> kep: kubectl subresource - update milestone 

- keps/prod-readiness/sig-windows/2578.yaml
- keps/sig-windows/2578-windows-conformance/README.md
- keps/sig-windows/2578-windows-conformance/kep.yaml
fixes https://github.com/kubernetes/enhancements/issues/2578
- One-line PR description: Windows Operational Readiness Specification
- Issue link: https://github.com/kubernetes/enhancements/issues/2578
> KEP-2578: Windows Operational Readiness Specification

- keps/sig-apps/1847-autoremove-statefulset-pvcs/README.md
- One-line PR description: update field names in KEP to what has been implemented in 1.23.
- Issue link: #1847
> KEP-1847: Update field names

- keps/sig-network/2829-gateway-api-to-k8s-io/README.md
Fixes a small link in the gateway API KEP.
> Fix link for gateway api implementations

- keps/sig-autoscaling/2702-graduate-hpa-api-to-GA/README.md
- keps/sig-autoscaling/2702-graduate-hpa-api-to-GA/kep.yaml
Fixes: #2702
- One-line PR description: "Marks KEP 2702 as implemented."
- Issue link: https://github.com/kubernetes/enhancements/issues/2702#issuecomment-1008234820
> KEP 2702: mark as implemented.

- keps/sig-cloud-provider/1959-service-lb-class-field/README.md
- keps/sig-cloud-provider/1959-service-lb-class-field/kep.yaml
- One-line PR description: Promote KEP-1959 to GA in v1.24
- Issue link: #1959 
> KEP-1959: update to GA in v1.24

- keps/sig-node/1287-in-place-update-pod-resources/kep.yaml
- keps/sig-node/2273-kubelet-container-resources-cri-api-changes/kep.yaml
- One-line PR description: Bump up target milestone for in-place pod vertical scaling feature to 1.24 for alpha.
> Update in-place pod vertical scaling KEPS to 1.24 milestone targets

- keps/prod-readiness/sig-apps/2214.yaml
- keps/sig-apps/2214-indexed-job/README.md
- keps/sig-apps/2214-indexed-job/kep.yaml
- One-line PR description: Graduate Indexed Job to stable
- Issue link: #2214
Updated PRR questionnaire format
> Graduate Indexed Job to stable

- keps/sig-storage/625-csi-migration/README.md
- One-line PR description: Update CSI migration KEP to include steps for feature trouble shooting.
> KEP-625: update CSI Migration KEP to include troubleshooting

- keps/prod-readiness/sig-storage/1488.yaml
- keps/sig-storage/1488-csi-migration-gce-pd/README.md
- keps/sig-storage/1488-csi-migration-gce-pd/kep.yaml
This PR adds the KEP for csi migration for gce-pd csi driver.
- Issue link: https://github.com/kubernetes/enhancements/issues/1488
> KEP-1488: CSI migration for GCE PD

- keps/prod-readiness/sig-storage/1885.yaml
- keps/sig-storage/1885-csi-migration-azurefile/README.md
- keps/sig-storage/1885-csi-migration-azurefile/kep.yaml
- One-line PR description: KEP for Azurefile csi migration
- Issue link: https://github.com/kubernetes/enhancements/issues/1885
> KEP-1885: add csi migration kep for azurefile

- keps/prod-readiness/sig-storage/1489.yaml
- keps/sig-storage/1489-csi-migration-cinder/README.md
- keps/sig-storage/1489-csi-migration-cinder/kep.yaml
- One-line PR description: Add CSI Migration KEP for openstack cinder
- Issue link: https://github.com/kubernetes/enhancements/issues/1489
PR to turn it into GA: https://github.com/kubernetes/kubernetes/pull/107462
> KEP-1489: add csi migration kep for openstack cinder

- keps/prod-readiness/sig-storage/1490.yaml
- keps/sig-storage/1490-csi-migration-azuredisk/README.md
- keps/sig-storage/1490-csi-migration-azuredisk/kep.yaml
Add KEP for Azuredisk CSI migration
- Issue link: https://github.com/kubernetes/enhancements/issues/1490
> KEP-1490: Add csi migration kep for Azuredisk

- keps/prod-readiness/sig-storage/1491.yaml
- keps/sig-storage/1491-csi-migration-vsphere/README.md
- keps/sig-storage/1491-csi-migration-vsphere/kep.yaml
- One-line PR description: CSI migration KEP for vSphere
- Issue link: https://github.com/kubernetes/enhancements/issues/1491
> KEP-1491: add csi migration kep for vsphere

- keps/sig-network/2593-multiple-cluster-cidrs/kep.yaml
- One-line PR description: Updating milestones to start from alpha in 1.24
> KEP-2593: Updating kep.yaml with correct milestones

- keps/prod-readiness/sig-release/3031.yaml
- keps/sig-release/3031-signing-release-artifacts/README.md
- keps/sig-release/3031-signing-release-artifacts/kep.yaml
- One-line PR description: We update the KEP for the enhancements tracking of v1.24.
- Issue link: https://github.com/kubernetes/enhancements/issues/3031
@kubernetes/sig-release-leads PTAL
> Update container image signing KEP

- keps/prod-readiness/sig-storage/2644.yaml
- keps/sig-storage/2644-honor-pv-reclaim-policy/README.md
- keps/sig-storage/2644-honor-pv-reclaim-policy/kep.yaml
Updates the KEP to beta. The kep also includes further fixes the issue for in-tree plugin volumes as well.
- Issue link: #2644 
Signed-off-by: Deepak Kinni <dkinni@vmware.com>
> Update HonorPVReclaimPolicy to beta

- keps/prod-readiness/sig-node/2727.yaml
- keps/sig-node/2727-grpc-probe/README.md
- keps/sig-node/2727-grpc-probe/kep.yaml
Promoting gRPC Probe API to beta
/sig node
/cc @bowei 
KEP #2727
> Promote gRPC container probes to beta

- keps/prod-readiness/sig-windows/2802.yaml
Fixing KEP number in https://github.com/kubernetes/enhancements/blob/master/keps/prod-readiness/sig-windows/2802.yaml#L1
- Issue link:
/assign @rhockenbury @ravisantoshgudimetla
> Fixing KEP number for OS field PRR yaml file

- keps/sig-node/2133-kubelet-credential-providers/README.md
- keps/sig-node/2133-kubelet-credential-providers/kep.yaml
- One-line PR description: v1.24 updates for #2133
- Issue link: #2133 
> KEP-2133: updates for v1.24

- keps/prod-readiness/sig-apps/3017.yaml
- keps/sig-apps/3017-pod-healthy-policy-for-pdb/README.md
- keps/sig-apps/3017-pod-healthy-policy-for-pdb/kep.yaml
Add PodHealthyPolicy to PodDisruptionBudget
> KEP-3017: Pod Healthy Policy for PDBs

- keps/prod-readiness/sig-cloud-provider/2436.yaml
- keps/sig-cloud-provider/2436-controller-manager-leader-migration/README.md
- keps/sig-cloud-provider/2436-controller-manager-leader-migration/kep.yaml
This PR revises KEP-2436 for PRR of GA graduatin.
- Issue link: https://github.com/kubernetes/enhancements/issues/2436
> KEP-2436 Leader Migration to GA

- keps/sig-node/281-dynamic-kubelet-configuration/README.md
- keps/sig-node/281-dynamic-kubelet-configuration/kep.yaml
> Updated PRR for DynamicKubeletConfig

- keps/sig-testing/2420-reducing-kubernetes-build-maintenance/kep.yaml
mark https://github.com/kubernetes/enhancements/issues/2420 implemented
> mark reducing build maintenance implemented

- keps/sig-windows/2578-windows-conformance/README.md
Update the Active Directory test cases description. In the implementation, we add a gmsa remote storage test case which we create a folder on AD server and read/write files to the remote folder. Therefore, we update the KEP to include this test case.
- Issue link:
https://github.com/kubernetes/kubernetes/issues/100388
The implement of this test case: https://github.com/kubernetes/kubernetes/pull/108432
> Update Active Directory test cases description

- keps/sig-apps/2214-indexed-job/README.md
- One-line PR description: Add detail of scalability tests performed to compare Indexed and NonIndexed Jobs.
- Issue link: #2214
> Add details of scalability test for Indexed Jobs

- keps/sig-auth/2784-csr-duration/README.md
- One-line PR description: CSR Duration: address all GA items
- Issue link: #2784
> KEP-2784: CSR Duration: address all GA items

- keps/sig-scheduling/1923-prefer-nominated-node/kep.yaml
The feature is GA-ed.
Signed-off-by: Dave Chen <dave.chen@arm.com>
- One-line PR description: update the status to `implemented`
- Issue link: #1923
> KEP-1923: update the status to `implemented`

- keps/sig-auth/2784-csr-duration/README.md
- keps/sig-auth/2784-csr-duration/kep.yaml
- One-line PR description: KEP-2784: CSR Duration: mark as implemented
- Issue link: #2784
> KEP-2784: CSR Duration: mark as implemented

- keps/README.md
- One-line PR description: Documentation PR to fix typo in kep/README.md
- Issue link: NA
> [Docs] fix typo

- keps/sig-api-machinery/365-paginated-lists/README.MD
- keps/sig-api-machinery/365-paginated-lists/kep.yaml
Ref https://github.com/kubernetes/enhancements/issues/365
As discussed yesterday, just extracted the non-controversial part to a separate PR for now
> KEP-365: Pagination kep format

- keps/sig-scheduling/3094-pod-topology-spread-considering-taints/README.md
- keps/sig-scheduling/3094-pod-topology-spread-considering-taints/kep.yaml
- One-line PR description: Some design details changed and the feature is delayed until v1.25
- Issue link: https://github.com/kubernetes/enhancements/issues/3094
> KEP-3094: update NodeInclusionPolicyInPodTopologySpread details

- keps/sig-api-machinery/1164-remove-selflink/kep.yaml
- keps/sig-api-machinery/1904-efficient-watch-resumption/kep.yaml
> Mark 1164 and 1904 KEPs as implemented

- keps/sig-cluster-lifecycle/kubeadm/2067-rename-master-label-taint/README.md
- keps/sig-cluster-lifecycle/kubeadm/2067-rename-master-label-taint/kep.yaml
mark as implementable for 1.25
- Issue link:
https://github.com/kubernetes/enhancements/issues/2067
https://github.com/kubernetes/kubeadm/issues/2200
NONE
> sig-cl/kubeadm/2067: update for 1.25

- keps/sig-cluster-lifecycle/kubeadm/2915-kubeadm-replace-kubelet-config-x.y/README.md
- keps/sig-cluster-lifecycle/kubeadm/2915-kubeadm-replace-kubelet-config-x.y/kep.yaml
Update KEP for GA in 1.25.
- Issue link:
https://github.com/kubernetes/enhancements/issues/2915
https://github.com/kubernetes/kubeadm/issues/1582
NONE
> sig-cl/kubeadm/2915: update KEP for 1.25

- keps/sig-storage/1472-storage-capacity-tracking/kep.yaml
- One-line PR description: KEP is implemented
- Issue link: https://github.com/kubernetes/enhancements/issues/1472#issuecomment-1122462551
> KEP-1472: storage capacity: implemented

- keps/sig-storage/1490-csi-migration-azuredisk/kep.yaml
This feature has been fully implemented and is now GA in K8s version 1.24. 
- Issue link:
https://github.com/kubernetes/enhancements/issues/1490#issuecomment-1121144610
> KEP-1490: set Azure Disk CSI driver migration as implemented

- OWNERS_ALIASES
> Move ehashman to PRR emeritus

- api/groups.go
Follow up from https://github.com/kubernetes/enhancements/pull/3381
> Cleanup PRR approvers fetching

- keps/sig-apps/1591-daemonset-surge/README.md
- Issue link: #1591 
cc @marosset @soltysh @wojtek-t
>  KEP-1591: Update graduation criteria

- keps/sig-storage/2924-csi-migration-cephfs/README.md
- keps/sig-storage/2924-csi-migration-cephfs/kep.yaml
One-line PR description: Update test template and milestone
Issue link #https://github.com/kubernetes/enhancements/issues/2924
> KEP-2924: update CephFS CSI migration milestone and test plan

- keps/sig-storage/3107-csi-nodeexpandsecret/README.md
- One-line PR description: update the test plan for NodeExpansionSecret
- Issue link: #3107
> KEP-3107: update the test plan for nodeExpandSecret

- keps/sig-storage/1488-csi-migration-gce-pd/README.md
- keps/sig-storage/1488-csi-migration-gce-pd/kep.yaml
- One-line PR description: Update test template
- Issue link: #1488 
/cc @Jiawei0227 
/cc @msau42 
/cc @leiyiz 
/assign @rhockenbury
> KEP-1488: Update gce-pd csi migration test plan

- keps/sig-api-machinery/2885-server-side-unknown-field-validation/README.md
- One-line PR description: I take the oath of testing.
- Issue link: https://github.com/kubernetes/enhancements/issues/2885
> Oath of Testing

- keps/sig-auth/2799-reduction-of-secret-based-service-account-token/README.md
- keps/sig-auth/2799-reduction-of-secret-based-service-account-token/kep.yaml
Update with template and test plan changes
Issue link: https://github.com/kubernetes/enhancements/issues/2799
/assign @zshihang
> KEP-2799: Update for 1.25

- keps/prod-readiness/sig-node/2133.yaml
- keps/sig-node/2133-kubelet-credential-providers/README.md
- keps/sig-node/2133-kubelet-credential-providers/kep.yaml
KEP-2133: add GA graduation criteria
Signed-off-by: ruiwen-zhao <ruiwen@google.com>
> KEP-2133: add GA criteria

- keps/sig-storage/1491-csi-migration-vsphere/README.md
- Issue link: https://github.com/kubernetes/enhancements/issues/1491
cc: @xing-yang @gnufied
> update e2e tests for vSphere CSI Migration KEP

- keps/sig-scheduling/3094-pod-topology-spread-considering-taints/README.md
- One-line PR description: update KEP about take taints into considering when calculating with latest test plans
- Issue link:  https://github.com/kubernetes/enhancements/issues/3094
> update KEP about take taints into considering with latest test plans

- keps/sig-node/2133-kubelet-credential-providers/README.md
- One-line PR description: Add test plan for GA
- Issue link: https://github.com/kubernetes/enhancements/issues/2133#issuecomment-1159067520
> KEP-2133: Add GA test plan

- keps/sig-node/1287-in-place-update-pod-resources/README.md
- One-line PR description: Catch-up KEP to latest template sections for Test Plan.
- Issue link: #1287 
> Update Test Plan section with prerequisite section from latest template

- keps/sig-scheduling/902-non-preempting-priorityclass/kep.yaml
Signed-off-by: Alex Wang <wangqingcan1990@gmail.com>
- One-line PR description: mark non-preempting policy as implemented
- Issue link: https://github.com/kubernetes/enhancements/issues/902
> mark non-preempting policy as implemented

- keps/sig-node/2133-kubelet-credential-providers/README.md
- keps/sig-node/2133-kubelet-credential-providers/kep.yaml
Signed-off-by: ruiwen-zhao <ruiwen@google.com>
- One-line PR description: Update the test plan using the latest template.
- Issue link: https://github.com/kubernetes/enhancements/issues/2133#issuecomment-1159386170
> KEP-2133: Update test plan

- keps/sig-windows/2258-node-service-log-viewer/README.md
- keps/sig-windows/2258-node-service-log-viewer/kep.yaml
> Windows/KEP-2258: Update API and milestones for Node Log Viewer

- keps/sig-instrumentation/2831-kubelet-tracing/README.md
- keps/sig-instrumentation/2831-kubelet-tracing/kep.yaml
- One-line PR description: Updated test plan, updated milestones to 1.25, and updated implementation history
> KEP-2831: update KEP testing plan, implementation history, & milestones

- keps/sig-storage/1488-csi-migration-gce-pd/README.md
- One-line PR description: Update test plan to match format
- Issue link: #1488 
/assign @Priyankasaggu11929
> KEP-1488: Update test coverage

- keps/sig-node/2371-cri-pod-container-stats/kep.yaml
update latest-milestone to 1.25 to reflect new work being done for alpha in 1.25
- Issue link: https://github.com/kubernetes/enhancements/issues/2371
as requested in https://github.com/kubernetes/enhancements/issues/2371#issuecomment-1157271850
> KEP 2371: update latest-milestone to 1.25

- keps/sig-auth/3299-kms-v2-improvements/README.md
Signed-off-by: Anish Ramasekar <anish.ramasekar@gmail.com>
- Update the proto snippets in KMS KEP to be in sync with the changes in implementation PR: https://github.com/kubernetes/kubernetes/pull/110201
/cc @enj @ritazh
/sig auth
> update proto snippets in kms v2

- keps/NNNN-kep-template/README.md
Signed-off-by: Paul S. Schweigert <paulschw@us.ibm.com>
- One-line PR description: Fixes typo in the release signoff checklist template
- Issue link:
> [NNNN-kep-template] Fixes typo in release signoff checklist

- keps/sig-apps/3329-retriable-and-non-retriable-failures/README.md
- One-line PR description: Additional updates to the KEP-3329
- Other comments: main changes motivated by implementation in PRs https://github.com/kubernetes/kubernetes/pull/110959 and https://github.com/kubernetes/kubernetes/pull/111113:
- added graduation criteria for Beta to commonize the code for appending pod conditions between components
- added graduation criteria for Beta to do not update the pod condition if already present with `status=True`
- renamed the `Terminate` action as `FailJob`
- improved comments to the new API structures
- adjusted API for specifying the onPodConditions requirement
> Additional update for KEP-3329 "Retriable and non-retriable Pod failures for Jobs"

- keps/sig-node/2221-remove-dockershim/kep.yaml
- One-line PR description: Mark dockershim KEP as implemented
- Issue link: https://github.com/kubernetes/enhancements/issues/2221
> KEP-2221: Mark dockershim KEP as implemented

- keps/sig-apps/3329-retriable-and-non-retriable-failures/README.md
- One-line PR description: Updates to the KEP-3329 for Alpha
- Other comments: main changes motivated by implementation in PRs https://github.com/kubernetes/kubernetes/pull/110959 and https://github.com/kubernetes/kubernetes/pull/111113:
- adjustments to API comments
- add a section in design details about the new `FailureTarget` job condition
- introduce the status field in `PodFailurePolicyOnPodConditionsPattern`
- updated `Implementation History`
> Updates to KEP-3329 "Retriable and non-retriable Pod failures for Jobs"

- keps/sig-node/1287-in-place-update-pod-resources/kep.yaml
- One-line PR description: We have merged the CRI changes in 1.25 to facilitate runtime support implementation. Main feature is now targeted for alpha in 1.26
> Bump milestone targets for in-place pod update

- keps/sig-auth/3299-kms-v2-improvements/README.md
Signed-off-by: Rita Zhang <rita.z.zhang@gmail.com>
Add sub sections
/cc @aramase  @enj
/assign @enj
> Add sub sections to kms v2 KEP

- keps/sig-cluster-lifecycle/kubeadm/2067-rename-master-label-taint/README.md
- keps/sig-cluster-lifecycle/kubeadm/2067-rename-master-label-taint/kep.yaml
mark as implementable for 1.26
- Issue link:
https://github.com/kubernetes/enhancements/issues/2067
https://github.com/kubernetes/kubeadm/issues/2200
NONE
> sig-cl/kubeadm/2067: update for 1.26

- keps/sig-auth/1205-bound-service-account-tokens/kep.yaml
- keps/sig-auth/2579-psp-replacement/kep.yaml
/sig auth
/cc @mikedanese @ritazh @enj @deads2k
> Update implemented status for sig-auth keps

- keps/sig-scheduling/624-scheduling-framework/README.md
Fix the broken(404) link for scheduling framework
> Fix the broken link to scheduler extenders design

- keps/sig-scheduling/785-scheduler-component-config-api/README.md
Ref: https://github.com/kubernetes/kubernetes/pull/112038
> Update implementation history for kube-scheduler configuration API

- README.md
- Update readme, removing reference to k/contrib which is archived now.
> Contrib is archived now, drop confusing reference

- README.md
- docs/archived-tracking-sheets.md
- One-line PR description: update README to reflect new tracking boards, move deprecated spreadsheets to an archive.
- Issue link:
> update README reflect new tracking boards

- keps/sig-scheduling/785-scheduler-component-config-api/kep.yaml
refer to https://github.com/kubernetes/enhancements/issues/785
> Turn kube scheduler component config status to implemented

- OWNERS_ALIASES
Adds me to OWNERS_ALIASES
/assign @cblecker @nikhita
> OWNERS_ALIASES: Add Josh to sig-contribex.

- keps/sig-storage/2924-csi-migration-cephfs/README.md
- keps/sig-storage/2924-csi-migration-cephfs/kep.yaml
> KEP-2924: Bump alpha target version for CephFS migration

- keps/sig-storage/2923-csi-migration-ceph-rbd/README.md
- keps/sig-storage/2923-csi-migration-ceph-rbd/kep.yaml
> KEP-2923: Bump beta target versions for RBD migration

- keps/sig-apps/1847-autoremove-statefulset-pvcs/README.md
- keps/sig-apps/1847-autoremove-statefulset-pvcs/kep.yaml
- One-line PR description: Update for kube-state-metrics and 1.26 beta graduation
> 1847: Update for kube-state-metrics and 1.26 beta graduation

- keps/sig-instrumentation/3466-kubernetes-component-health-slis/README.md
Address concern about healthcheck not being checked off.
> add test plan

- keps/sig-apps/1847-autoremove-statefulset-pvcs/README.md
> KEP-1847: Fix quote typo

- keps/sig-auth/3325-self-subject-attributes-review-api/README.md
- keps/sig-auth/3325-self-subject-attributes-review-api/kep.yaml
- One-line PR description: Fixes according to the [Enhancements team request](https://github.com/kubernetes/enhancements/issues/3325#issuecomment-1252268801).
* Milestone update
* SelfSubjectAttributesReview -> SelfSubjectReview (to be inline with the implementation)
* Update Test plan section
> KEP-3325: Update milestone and test plan section for SelfSubjectReview KEP

- keps/sig-instrumentation/647-apiserver-tracing/README.md
- keps/sig-instrumentation/647-apiserver-tracing/kep.yaml
- One-line PR description: Update to the latest template
- Other comments: This feature does not introduce new endpoints.
/assign @logicalhan @dgrisonnet
> KEP-647: adding beta graduation criteria Update to latest KEP template

- keps/sig-apps/3017-pod-healthy-policy-for-pdb/kep.yaml
- One-line PR description: Update timeframe for the PDB health policy
> KEP-3017: Update timeframe for the PDB health policy

- keps/sig-node/2133-kubelet-credential-providers/kep.yaml
Signed-off-by: ruiwen-zhao <ruiwen@google.com>
- One-line PR description: Update the milestone to 1.26.
- Issue link: https://github.com/kubernetes/enhancements/issues/2133
> KEP-2133: Update milestone for 1.26

- keps/prod-readiness/sig-auth/2799.yaml
- keps/sig-auth/2799-reduction-of-secret-based-service-account-token/README.md
- keps/sig-auth/2799-reduction-of-secret-based-service-account-token/kep.yaml
- One-line PR description: update KEP milestones
> KEP-2799: LegacyServiceAccountTokenNoAutoGeneration ga and LegacyServiceAccountTokenTracking alpha

- keps/sig-api-machinery/1040-priority-and-fairness/README.md
- One-line PR description: Update API Priority and Fairness design to let admin configure a limit on how much a priority level can borrow
- Issue link: https://github.com/kubernetes/kubernetes/issues/111482
> KEP-1040: Introduce limit on borrowing as well as lending

- keps/prod-readiness/sig-storage/2317.yaml
- keps/sig-storage/2317-fsgroup-on-mount/README.md
- keps/sig-storage/2317-fsgroup-on-mount/kep.yaml
Update stable version to 1.26 and update to latest KEP Readme template.
- Issue link:
https://github.com/kubernetes/enhancements/issues/2317
> KEP-2317: Update stable version to 1.26

- keps/prod-readiness/sig-apps/3329.yaml
- keps/sig-apps/3329-retriable-and-non-retriable-failures/README.md
- keps/sig-apps/3329-retriable-and-non-retriable-failures/kep.yaml
- One-line PR description: KEP updates for Beta
> Update KEP-3329 "Retriable and non-retriable Pod failures for Jobs" for Beta

- keps/prod-readiness/sig-node/3545.yaml
- keps/sig-node/3545-improved-multi-numa-alignment/README.md
- keps/sig-node/3545-improved-multi-numa-alignment/kep.yaml
- One-line PR description: Adding new KEP - Improved multi-numa alignment in Topology Manager
- Issue link: https://github.com/kubernetes/enhancements/issues/3545
Co-authored-by: Piotr Prokop <pprokop@nvidia.com>
> KEP-3545: Improved multi-numa alignment in Topology Manager

- keps/prod-readiness/sig-network/2595.yaml
- keps/sig-network/2595-expanded-dns-config/README.md
- keps/sig-network/2595-expanded-dns-config/kep.yaml
Update KEP-2595 as https://github.com/kubernetes/kubernetes/issues/104352 issue raised.
- Issue link: #2595
/cc @aojea @liggitt
> KEP-2595: Promote to the beta stage

- keps/sig-storage/2317-fsgroup-on-mount/README.md
- One-line PR description: Update Test Plan section
> KEP-2317: Update Test Plan 1.26

- keps/sig-testing/3041-node-conformance-and-features/README.md
- keps/sig-testing/3041-node-conformance-and-features/kep.yaml
KEP: #3041
Feature, NodeConformance, NodeFeature, and Feature Gate labels cleanup
The document https://docs.google.com/document/d/19HqSyrS-4pyubqTvQV0hJKt_97nbCSt_aD0soL-RGGE/edit#heading=h.veqp9g4ihszu was discussed in a few forums and it was suggested to write this as a KEP for awareness.
> KEP-3041: Feature, NodeConformance, NodeFeature, and Feature Gate labels cleanup

- keps/sig-architecture/3136-beta-apis-off-by-default/kep.yaml
Fix #3136 
/assign @deads2k @johnbelamaric @dims
> Mark KEP 3136 as implemented

- keps/sig-node/281-dynamic-kubelet-configuration/README.md
- keps/sig-node/281-dynamic-kubelet-configuration/kep.yaml
/sig node
KEP: #281
/kind cleanup
> remove dynamic kubelet config completely

- keps/sig-node/2400-node-swap/kep.yaml
/kind cleanup
/sig node
KEP: https://github.com/kubernetes/enhancements/issues/2400
> node swap is alpha (fixing mistake in kep.yaml)

- keps/sig-api-machinery/2876-crd-validation-expression-language/README.md
- One-line PR description: editorial fix
> KEP-2876: Merge starlark sections

- keps/sig-cloud-provider/2699-add-webhook-hosting-to-ccm/README.md
- keps/sig-cloud-provider/2699-add-webhook-hosting-to-ccm/kep.yaml
* Updated test plan from template
* Update milestone to 1.26
* Clean up some wording and structure
* No substantive updates other than to test plan
- One-line PR description: Update 2699 to include updated Test Plan from KEP template.
- Issue link: https://github.com/kubernetes/enhancements/issues/2699
> KEP-2699: Include updated Test Plan

- keps/sig-auth/2718-20210511-client-exec-proxy/README.md
- One-line PR description: Update KEP-2718 to new test plan template.
- Issue link: https://github.com/kubernetes/enhancements/issues/2718
> KEP-2718: Update to new test plan template

- keps/sig-api-machinery/3352-aggregated-discovery/README.md
Update aggregated discovery group version location based on slack discussion.
> Update aggregated discovery types group version

- keps/sig-storage/3294-provision-volumes-from-cross-namespace-snapshots/kep.yaml
- One-line PR description: Update document for add reviewer
- Issue link: #3624
> Update document for add reviewer and approvers

- keps/sig-node/3063-dynamic-resource-allocation/kep.yaml
- One-line PR description: bump latest-milestone to 1.26
- Issue link: https://github.com/kubernetes/enhancements/issues/3063#issuecomment-1270997160
> KEP-3063: dynamic resource allocation: bump latest-milestone to 1.26

- keps/sig-api-machinery/3488-cel-admission-control/README.md
- One-line PR description: Add beta graduation criteria for CEL in Admission Control
- Issue link: #3488
- Other comments: Adding beta graduation criteria while code review to capture the feedback
> Add beta graduation criteria for CEL in Admission Control

- keps/sig-cli/3104-introduce-kuberc/README.md
- One-line PR description: Adding new user story to silence deprecation warnings.
> KEP-3104: Add new user story

- keps/sig-api-machinery/3488-cel-admission-control/README.md
- One-line PR description: This PR updates KEP 3488 reflecting new decisions during implementation.
> KEP-3488: updates after 1.26 release.

- keps/sig-node/3063-dynamic-resource-allocation/README.md
- One-line PR description:  match API with actual implementation in 1.26
> KEP-3063: dynamic resource allocation: match API with actual implementation in 1.26

- keps/sig-windows/1981-windows-privileged-container-support/README.md
- keps/sig-windows/1981-windows-privileged-container-support/kep.yaml
> Mark Windows HostProcess Containers KEP as implemented

- README.md
> Add link for 1.27 enhancements tracking board

- keps/sig-storage/1885-csi-migration-azurefile/kep.yaml
Update azure file csi migration status as implemented since it's done
- Issue link:
> Update azure file csi migration status as implemented

- keps/sig-network/3070-reserved-service-ip-range/kep.yaml
set kep 3070 to implemented
Fixes: #3070
> set kep 3070 to implemented

- keps/sig-network/1611-network-policy-validation/kep.yaml
> KEP-1611 (NetPol tests) is implemented

- keps/sig-storage/3141-prevent-volume-mode-conversion/kep.yaml
Fix the title in the metadata for KEP-3141
- Issue link: https://github.com/kubernetes/enhancements/issues/3141
> KEP-3141: Fix KEP title (Prevent unauthorised volume mode conversion)

- keps/sig-api-machinery/3157-watch-list/README.md
Ref #3157 
/assign @deads2k @lavalamp 
/cc @p0lyn0mial @jpbetz @liggitt
> Update API proposal for KEP 3157

- keps/prod-readiness/sig-network/3668.yaml
- keps/sig-network/3668-reserved-service-nodeport-range/README.md
- keps/sig-network/3668-reserved-service-nodeport-range/kep.yaml
- One-line PR description: KEP-3668: adding KEP
- Issue link: https://github.com/kubernetes/enhancements/issues/3668
- Other comments: https://github.com/kubernetes/kubernetes/issues/114129
> Reserve Nodeport Ranges For Dynamic And Static Port Allocation

- keps/prod-readiness/sig-scheduling/2926.yaml
- keps/sig-scheduling/2926-job-mutable-scheduling-directives/README.md
- keps/sig-scheduling/2926-job-mutable-scheduling-directives/kep.yaml
- One-line PR description: graduate mutable scheduling directives to stable
- Issue link: #2926
> KEP-2926: Graduate mutable scheduling directives to stable

- keps/prod-readiness/sig-instrumentation/3466.yaml
- keps/sig-instrumentation/3466-kubernetes-component-health-slis/README.md
- One-line PR description: update beta graduation requirements for component health SLIs
- Issue link: https://github.com/kubernetes/enhancements/issues/3466
> KEP-3466: update beta graduation requirements for component SLIs

- keps/NNNN-kep-template/README.md
Follow up from the PRR subproject meeting on Jan 25th.
/assign @johnbelamaric @deads2k 
@SergeyKanzhelev - FYI
> Extend PRR template with node resource exhaustion question

- keps/sig-api-machinery/3488-cel-admission-control/README.md
- One-line PR description: update on resource constraints 
> KEP-3488: update on resource constraints 

- keps/sig-node/277-ephemeral-containers/kep.yaml
- One-line PR description: Marks KEP-277 (Ephemeral Containers) as implemented
- Issue link: #277 
> KEP-277: Mark as implemented

- keps/prod-readiness/sig-scheduling/3633.yaml
- keps/sig-scheduling/3633-matchlabelkeys-to-podaffinity/README.md
- keps/sig-scheduling/3633-matchlabelkeys-to-podaffinity/kep.yaml
- One-line PR description: Introduce `MatchLabelKeys` to PodAffinity and PodAntiAffinity
> KEP-3633: Introduce `MatchLabelKeys` to PodAffinity and PodAntiAffinity

- keps/sig-node/3063-dynamic-resource-allocation/README.md
- One-line PR description: Dynamic Resource Allocation: Update CRI structures
- Issue link: https://github.com/kubernetes/kubernetes/issues/114209
> KEP3063: Update CRI structures

- keps/sig-node/2238-liveness-probe-grace-period/README.md
- One-line PR description: Update Liveness Probe Grace Periods for GA and removal of featuregate.
- Issue link: 
- https://github.com/kubernetes/enhancements/issues/2238
> 2238: update liveness probe grace period enhancement for GA

- keps/sig-node/2133-kubelet-credential-providers/README.md
- keps/sig-node/2133-kubelet-credential-providers/kep.yaml
Marking this KEP as "implemented" as kubelet credential provider graduated to GA in v1.26
Fixes https://github.com/kubernetes/enhancements/issues/2133
> KEP-2133: set status to implemented

- keps/prod-readiness/sig-auth/3325.yaml
- keps/sig-auth/3325-self-subject-attributes-review-api/README.md
- keps/sig-auth/3325-self-subject-attributes-review-api/kep.yaml
Signed-off-by: m.nabokikh <maksim.nabokikh@flant.com>
Beta graduation
> KEP-3325: SelfSubjectReview API Beta graduation

- keps/prod-readiness/sig-release/3720.yaml
- keps/sig-release/3720-freezing-k8s-gcr-io/README.md
- keps/sig-release/3720-freezing-k8s-gcr-io/kep.yaml
- One-line PR description: Freeze `k8s.gcr.io` image registry
- Issue link: #3720 
/cc @ameukam @puerco @BenTheElder @jeremyrickard
/label tide/merge-method-squash
> KEP-3720: Freeze `k8s.gcr.io` image registry

- keps/prod-readiness/sig-cli/2227.yaml
- keps/sig-cli/2227-kubectl-default-container/README.md
- keps/sig-cli/2227-kubectl-default-container/kep.yaml
- One-line PR description: update implementation history of #2227
- Issue link: https://github.com/kubernetes/enhancements/issues/2227
Fixes https://github.com/kubernetes/enhancements/issues/2227
> KEP-2227: update implementation history

- keps/sig-auth/3325-self-subject-attributes-review-api/kep.yaml
Signed-off-by: m.nabokikh <maksim.nabokikh@flant.com>
https://github.com/kubernetes/enhancements/issues/3325#issuecomment-1412534928
- One-line PR description: Update latest-milestone to v1.27
> KEP-3325: Update latest-milestone to v1.27

- keps/prod-readiness/sig-storage/2485.yaml
- keps/sig-storage/2485-read-write-once-pod-pv-access-mode/README.md
- keps/sig-storage/2485-read-write-once-pod-pv-access-mode/kep.yaml
- One-line PR description: Updates KEP with beta implementation plans, answers PRR survey
- Issue link: https://github.com/kubernetes/enhancements/issues/2485
/cc @jsafrane
/assign @alculquicondor 
/cc @ahg-g
> KEP-2485: ReadWriteOncePod beta production readiness

- keps/prod-readiness/sig-api-machinery/2896.yaml
- keps/sig-api-machinery/2896-openapi-v3/README.md
- keps/sig-api-machinery/2896-openapi-v3/kep.yaml
- One-line PR description: OpenAPI V3 GA
- Issue link: https://github.com/kubernetes/enhancements/issues/2896
> KEP-2896: OpenAPI V3 to GA

- keps/prod-readiness/sig-network/3668.yaml
- keps/sig-network/3668-reserved-service-nodeport-range/README.md
- keps/sig-network/3668-reserved-service-nodeport-range/kep.yaml
update KEP-3668 to implementable, including addressing a few comments [Atharva-Shinde](https://github.com/Atharva-Shinde) left in #3668
- Issue link: https://github.com/kubernetes/enhancements/issues/3668#issuecomment-1411004911_
/sig network
> KEP-3668: update to implementable

- keps/sig-api-machinery/3157-watch-list/README.md
- keps/sig-api-machinery/3157-watch-list/kep.yaml
- PR description:
- Updated milestones in the [kep.yaml](https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/3157-watch-list/kep.yaml)
- Added alpa graduation criteria to the [README.md](https://github.com/kubernetes/enhancements/blob/2d3d1d7eda751c8c29aede0d0b479cb3901bc717/keps/sig-api-machinery/3157-watch-list/README.md?plain=1#L599)
- Updated the KEP to use the latest template and include the updated test plan section.
> Update KEP 3157 for milestone 1.27

- keps/prod-readiness/sig-scheduling/3243.yaml
- keps/sig-scheduling/3243-respect-pod-topology-spread-after-rolling-upgrades/README.md
- keps/sig-scheduling/3243-respect-pod-topology-spread-after-rolling-upgrades/kep.yaml
Signed-off-by: Alex Wang <wangqingcan1990@gmail.com>
- One-line PR description: graduate MatchLabelKeysInPodTopologySpread to beta
- Issue link: https://github.com/kubernetes/enhancements/issues/3243
> KEP-3243: Graduate MatchLabelKeys In PodTopologySpread to beta

- keps/prod-readiness/sig-apps/3715.yaml
- keps/sig-apps/3715-elastic-indexed-job/README.md
- keps/sig-apps/3715-elastic-indexed-job/kep.yaml
- One-line PR description: Allow creating `Indexed` Jobs with unset `spec.completions`
- Issue link: https://github.com/kubernetes/enhancements/issues/3715
> KEP-3715: Elastic Indexed Jobs

- keps/sig-auth/3257-trust-anchor-sets/README.md
- keps/sig-auth/3257-trust-anchor-sets/kep.yaml
Update target milestone to note that we are aiming to land alpha in 1.27.
Record enj and liggitt as reviewers.
> kep-3257: Update target milestone, record reviewers / approvers

- keps/prod-readiness/sig-api-machinery/1040.yaml
- keps/sig-api-machinery/1040-priority-and-fairness/README.md
- keps/sig-api-machinery/1040-priority-and-fairness/kep.yaml
Update to the latest templates, and catch up with recent developments.
Track recent developments and update to latest templaes.
- Issue link:
- Other comments: this is part of the response to https://github.com/kubernetes/enhancements/issues/1040#issuecomment-1410977120
> KEP-1040: Update README.md and kep.yaml

- keps/prod-readiness/sig-network/1669.yaml
- keps/sig-network/1669-proxy-terminating-endpoints/README.md
- keps/sig-network/1669-proxy-terminating-endpoints/kep.yaml
KEP-1669: add GA graduation criterias for v1.27
- Issue link: #1669 
> kep-1669: add GA graduation criterias for v1.27

- keps/sig-storage/1790-recover-resize-failure/README.md
- keps/sig-storage/1790-recover-resize-failure/kep.yaml
xref https://github.com/kubernetes/enhancements/issues/1790
cc @jsafrane @msau42 @sunnylovestiramisu @xing-yang
> Update recovery kep with new APIs

- keps/sig-instrumentation/3498-extending-stability/README.md
- keps/sig-instrumentation/3498-extending-stability/kep.yaml
- One-line PR description: add PRR question and update KEP status
- Issue link: https://github.com/kubernetes/enhancements/issues/3498
> add PRR question and update KEP status

- keps/sig-api-machinery/2876-crd-validation-expression-language/README.md
- One-line PR description: Define GA graduation criteria
> KEP-2876: Define GA graduation criteria

- keps/sig-scheduling/3243-respect-pod-topology-spread-after-rolling-upgrades/README.md
Signed-off-by: Alex Wang <wangqingcan1990@gmail.com>
- One-line PR description: Answer New Question in PRR from the comment https://github.com/kubernetes/enhancements/issues/3243#issuecomment-1418177661 
- Issue link: https://github.com/kubernetes/enhancements/issues/3243
> KEP-3243: Answer New Question in PRR

- keps/prod-readiness/sig-cli/3515.yaml
- keps/sig-cli/3515-kubectl-explain-openapiv3/README.md
- keps/sig-cli/3515-kubectl-explain-openapiv3/kep.yaml
- One-line PR description: graduating to beta
- Issue link: https://github.com/kubernetes/enhancements/issues/3515
/cc @KnVerey @seans3 @apelisse
> KEP-3515: kubectl explain openapiv3 - beta graduation criteria

- keps/sig-apps/1847-autoremove-statefulset-pvcs/README.md
- One-line PR description: Update template, add node scalability question, clarify graduation criteria
@msau42
> KEP-1847: Update for 1.27 template

- keps/sig-node/1287-in-place-update-pod-resources/README.md
- One-line PR description: This PR adds a section for integration test and responds to node scalability questions in order to catch up to latest template needs.
> In-place pod resize KEP: template update housekeeping changes

- keps/sig-network/2681-pod-host-ip/README.md
> KEP-2681: Update to latest template

- keps/sig-api-machinery/2876-crd-validation-expression-language/README.md
- One-line PR description: This PR adds a new `messageExpression` field and adjusts examples accordingly, similar to https://github.com/kubernetes/enhancements/pull/3736.
- Issue link:
> KEP-2876: Add messageExpression

- keps/prod-readiness/sig-storage/1710.yaml
- keps/sig-storage/1710-selinux-relabeling/README.md
- keps/sig-storage/1710-selinux-relabeling/kep.yaml
- One-line PR description: Update SELinux mount ReadWriteOnce optimization for beta 
cc @gnufied @msau42
> KEP-1710: Update SELinux mount ReadWriteOnce optimization for beta

- keps/prod-readiness/sig-node/3386.yaml
- keps/sig-node/3386-kubelet-evented-pleg/README.md
- keps/sig-node/3386-kubelet-evented-pleg/kep.yaml
Signed-off-by: Harshal Patil <harpatil@redhat.com>
- One-line PR description: Graduate Evented PLEG to Beta
- Issue link: https://github.com/kubernetes/enhancements/issues/3386
> KEP-3386: Graduate Evented PLEG to Beta

- keps/prod-readiness/sig-node/2238.yaml
- keps/sig-node/2238-liveness-probe-grace-period/README.md
- keps/sig-node/2238-liveness-probe-grace-period/kep.yaml
Update #2238 approver to @wojtek-t 
- Issue link: #2238 
> KEP-2238: update pod readiness probe kep

- keps/prod-readiness/sig-network/3458.yaml
- keps/sig-network/3458-remove-transient-node-predicates-from-service-controller/README.md
- keps/sig-network/3458-remove-transient-node-predicates-from-service-controller/kep.yaml
- One-line PR description: **Follow-up to**: This KEP proposes a generalized and more dynamic mechanism for load balancers to health check cluster nodes, and subsequently, more efficiently and robustly react to transient cluster events.
/cc @thockin  
/sig network
> KEP 3458: address left over comments / KEP requirements

- keps/prod-readiness/sig-node/1972.yaml
KEP #1972
/sig node
See comment: https://github.com/kubernetes/enhancements/issues/1972#issuecomment-1030410033
> document the PRR approval for KEP 1972

- keps/sig-api-machinery/3488-cel-admission-control/README.md
- One-line PR description: This PR updates the informational type checking section of KEP-3488 Validating Admission Policy
- Issue link: #3488 
> KEP-3488 Update Informational Type System

- keps/prod-readiness/sig-scheduling/3280.yaml
- keps/sig-scheduling/3280-guarantee-pdb-when-preemption-happens/README.md
- keps/sig-scheduling/3280-guarantee-pdb-when-preemption-happens/kep.yaml
Signed-off-by: Alex Wang <wangqingcan1990@gmail.com>
- One-line PR description: Adding new KEP for `KEP-3280: Guarantee PodDisruptionBudget When Preemption Happens`
- Issue link: https://github.com/kubernetes/enhancements/issues/3280
> KEP-3280: Guarantee PodDisruptionBudget When Preemption Happens

- keps/sig-api-machinery/3488-cel-admission-control/README.md
Signed-off-by: Max Smythe <smythe@google.com>
- One-line PR description: Add spec for supporting custom match criteria
> KEP-3488: add spec for supporting custom match criteria

- keps/sig-node/2413-seccomp-by-default/README.md
> KEP-2413 Add new PRR question to SeccompDefault KEP

- keps/sig-api-machinery/2876-crd-validation-expression-language/kep.yaml
- keps/sig-api-machinery/3488-cel-admission-control/kep.yaml
- One-line PR description: Update milestone tag for 2876 and 3488
- Issue link: https://github.com/kubernetes/enhancements/issues/3488; https://github.com/kubernetes/enhancements/issues/2876
- Other comments: Update milestone base on [release tracking requirement](https://github.com/kubernetes/enhancements/issues/3488#issuecomment-1424880818)
> Update milestone tag for 2876 and 3488

- keps/sig-node/3570-cpumanager/kep.yaml
- Mark CPUManager KEP as implemented
- Issue link: #3570 
- Other comments: see: https://github.com/kubernetes/enhancements/issues/3570#issuecomment-1347538860
> node: cpumanager: set state "implemented"

- keps/sig-node/2570-memory-qos/README.md
Signed-off-by: David Porter <porterdavid@google.com>
- One-line PR description: Update the MemoryQoS KEP based on the latest KEP template
- Issue link: https://github.com/kubernetes/enhancements/issues/2570
> KEP-2570: Update MemoryQoS based on latest KEP template

- keps/sig-cli/3805-ssa-default/kep.yaml
- One-line PR description: Update status to implementable
- Issue link: https://github.com/kubernetes/enhancements/issues/3805
> KEP-3805: Set status to implementable

- keps/sig-storage/3141-prevent-volume-mode-conversion/README.md
- One-line PR description: Add e2e test link to KEP
- Issue link:
> KEP-3141: Add links to newly added e2e tests 

- keps/sig-apps/3017-pod-healthy-policy-for-pdb/README.md
- One-line PR description: Promote unhealthyPodEvictionPolicy for PDBs to Beta
> Update beta graduation criteria

- OWNERS_ALIASES
Part of https://github.com/kubernetes/community/issues/7158
/hold until 2/28
/sig windows
/assign @jsturtevant @jayunit100 @claudiubelu
> Updates for aravindhp sig-windows co-chair

- keps/sig-instrumentation/2831-kubelet-tracing/kep.yaml
KEP-2831: adding reviewers
Adding @saschagrunert and @vrutkovs to kubelet tracing KEP. They are leading the effort for beta graduation.
> KEP-2831: add reviewers

- keps/sig-node/3573-device-plugin/README.md
- keps/sig-node/3573-device-plugin/kep.yaml
Set an appropriate KEP title (in the committed data)
- Issue link: https://github.com/kubernetes/enhancements/issues/3573
> KEP-3573: Retitle the KEP

- keps/sig-apps/1591-daemonset-surge/kep.yaml
This updates the metadata of this KEP to reflect reality, when it was promoted to stable in https://github.com/kubernetes/enhancements/pull/3307
- Issue link:
https://github.com/kubernetes/enhancements/issues/1591
/assign @ravisantoshgudimetla
> KEP 1591: Update metadata to reflect reality

- keps/sig-scheduling/3521-pod-scheduling-readiness/README.md
- One-line PR description: Update KEP 3521 with test result of upgrade->downgrade->upgrade path
> Update KEP 3521 with test result of upgrade->downgrade->upgrade path

- OWNERS_ALIASES
Ref: https://github.com/kubernetes/community/issues/7246
/assign @mrbobbytables
> Add new contribex leads to OWNERS_ALIASES

- keps/sig-apps/2307-job-tracking-without-lingering-pods/kep.yaml
- One-line PR description: Update metadata to match reality
- Issue link: #2307
assign @alculquicondor
> KEP 2307: Update stage metadata to match reality

- keps/sig-auth/3299-kms-v2-improvements/README.md
Updates KMS KEP to reflect current design. I've moved the key hierarchy sequence diagram under alternatives, so we still have the history. 
/sig auth
/assign @enj
> update kmsv2 kep with beta design

- keps/sig-storage/2923-csi-migration-ceph-rbd/README.md
- keps/sig-storage/2923-csi-migration-ceph-rbd/kep.yaml
- Issue link: https://github.com/kubernetes/kubernetes/pull/108632
> KEP-2923 update rbd migration feature milestone in KEP to 1.27

- keps/NNNN-kep-template/README.md
Explain how integration tests are different from e2e tests.
- Issue link: https://github.com/kubernetes/enhancements/issues/3860
fixes  https://github.com/kubernetes/enhancements/issues/3860
> 3860: add explanation of integration tests

- keps/sig-node/3573-device-plugin/kep.yaml
> DeviceManager is GA now

- keps/sig-node/693-topology-manager/kep.yaml
> Topology Manager is GA now

- keps/sig-node/2727-grpc-probe/kep.yaml
> gRPC probes is GA now

- keps/sig-release/1731-publishing-packages/kep.yaml
- One-line PR description: Update milestone as per requirements stated in [the handbook](https://github.com/kubernetes/sig-release/blob/master/releases/release_phases.md#enhancements-freeze)
- Issue link: #1731 
/assign @cpanato @saschagrunert @puerco 
cc @kubernetes/release-engineering
> KEP-1731: Update milestone for KEP-1731

- README.md
Add v1.28 enhancements tracking board link to the Readme.md
- Issue link:
> Add v1.28 enhancements board link to Readme.md

- keps/sig-apps/2307-job-tracking-without-lingering-pods/README.md
We have completed all the deprecations on the job tracking KEP.
- Issue link: https://github.com/kubernetes/enhancements/issues/2307
> KEP-2307: add a note for deprecation job tracking

- keps/sig-storage/2268-non-graceful-shutdown/README.md
- One-line PR description: Update non-graceful node shutdown KEP following to latest template
- Issue link:
- Other comments: [KEP template](https://github.com/kubernetes/enhancements/blob/master/keps/NNNN-kep-template/README.md) has been updated in [this commit](https://github.com/kubernetes/enhancements/commit/400931940a25a8a6ca001f4fd9f8735bdd79edee#diff-3df430c68270e73ed3fdb8880e18ca3b3a519c544bee244361db12ad014e0775). Old template has the problem that line-wrap on **bold** syntax is broken.
> Update non-graceful node shutdown KEP following to template

- keps/sig-network/2681-pod-host-ip/kep.yaml
> KEP-2681: Target to alpha for 1.28

- keps/prod-readiness/sig-network/2595.yaml
- keps/sig-network/2595-expanded-dns-config/README.md
- keps/sig-network/2595-expanded-dns-config/kep.yaml
- One-line PR description: Promote ExpandedDNSConfig to the GA stage.
- Issue link: https://github.com/kubernetes/enhancements/issues/2595
/uncc all
> KEP-2595: Promote to the GA stage

- keps/sig-storage/3762-persistent-volume-last-phase-transition-time/kep.yaml
- One-line PR description:  marking it as implementable and add an approver
- Issue link: https://github.com/kubernetes/enhancements/issues/3762
> update kep-3762 for milestone 1.28

- keps/sig-scheduling/3633-matchlabelselectors-to-podaffinity/README.md
- keps/sig-scheduling/3633-matchlabelselectors-to-podaffinity/kep.yaml
- One-line PR description: redesign matchLabelKeys as matchLabelSelectors to introduce Operator field
- Issue link: #3633 
> fix(kep-3633): redesign matchLabelKeys as matchLabelSelectors to introduce Operator field

- keps/sig-api-machinery/4020-unknown-version-interoperability-proxy/README.md
- One-line PR description: Amends the metrics and headers described in the [KEP](https://github.com/kubernetes/enhancements/tree/master/keps/sig-api-machinery/4020-unknown-version-interoperability-proxy) 
- Issue link: https://github.com/kubernetes/enhancements/issues/4020
> KEP-4020: Unknown Version Interoperability Proxy : Remove uvip acronym from metrics/headers

- keps/sig-api-machinery/3157-watch-list/README.md
- keps/sig-api-machinery/3157-watch-list/kep.yaml
- One-line PR description: update KEP 3157 (watch-list) for milestone 1.28 
> Update KEP 3157 (watch-list) for milestone 1.28 

- keps/sig-api-machinery/1040-priority-and-fairness/README.md
- One-line PR description: Add borrowing by exempt to APF GA criteria
- Issue link:
> KEP-1040: Add borrowing by exempt to APF GA criteria

- keps/sig-api-machinery/1040-priority-and-fairness/README.md
- One-line PR description: This PR updates the GA criteria of APF to include deep disablement by the `--enable-priority-and-fairness` flag.
- Issue link:
> KEP-1040: Add deep disable to GA criteria

- keps/sig-auth/3299-kms-v2-improvements/README.md
- Add missing dependency question for KMSv2 KEP
> add missing dependency question to KMSv2 KEP

- keps/sig-api-machinery/3488-cel-admission-control/README.md
This PR updates Variable Composition section of KEP-3488 CEL for Admission Controller
- Issue link: #3488 
> KEP-3488: Update for CEL Variable Composition 

- keps/sig-node/1287-in-place-update-pod-resources/README.md
- One-line PR description: Catch up the KEP description and details to what actually got implemented after various reviews and discussions.
> KEP-1287: Catch up KEP details to actual implementation

- keps/prod-readiness/sig-apps/4017.yaml
- keps/sig-apps/4017-pod-index-label/README.md
- keps/sig-apps/4017-pod-index-label/kep.yaml
- One-line PR description: Add Pod Index Label for StatefulSets and Indexed Jobs.
- Issue link: https://github.com/kubernetes/enhancements/issues/4017
> KEP-4017: Pod Index Label for StatefulSets and Indexed Jobs

- keps/sig-node/3619-supplemental-groups-policy/kep.yaml
- One-line PR description: just update milestone version with v1.28 on behalf of https://github.com/kubernetes/enhancements/issues/3619#issuecomment-1586243152
- Other comments: none.
> KEP-3619: update milestone version with v1.28

- keps/prod-readiness/sig-network/3685.yaml
- keps/sig-network/3685-endpointslice-reconciler-to-staging/kep.yaml
- One-line PR description: moving to implementable
- Issue link: https://github.com/kubernetes/enhancements/issues/3685
> KEP-3685: moving to implementable

- keps/sig-network/3836-kube-proxy-improved-ingress-connectivity-reliability/kep.yaml
- One-line PR description: update milestone version with v1.28 on behalf of https://github.com/kubernetes/enhancements/issues/3836#issuecomment-1589966336
/sig network
> KEP 3836 - 1.28 update milestones

- keps/sig-network/3458-remove-transient-node-predicates-from-service-controller/kep.yaml
- One-line PR description: 1.28 milestone bump for KEP - 348 as requested [here](https://github.com/kubernetes/enhancements/issues/3458#issuecomment-1589964735)
/sig network
> KEP 3458 - 1.28 milestone bump

- keps/prod-readiness/sig-node/2371.yaml
- keps/sig-node/2371-cri-pod-container-stats/README.md
- keps/sig-node/2371-cri-pod-container-stats/kep.yaml
Signed-off-by: Peter Hunt~ <pehunt@redhat.com>
Updates target for KEP to beta in 1.27
- Issue link:
https://github.com/kubernetes/enhancements/issues/2371
> KEP 2371: target to beta for 1.28

- keps/sig-scheduling/3633-matchlabelkeys-to-podaffinity/README.md
- keps/sig-scheduling/3633-matchlabelkeys-to-podaffinity/kep.yaml
- keps/sig-scheduling/3633-matchlabelselectors-to-podaffinity/README.md
- One-line PR description: follow up of #4001
It's continuous work from https://github.com/kubernetes/enhancements/pull/4001. (https://github.com/kubernetes/enhancements/pull/4001 is mistakenly merged.)
> fix(kep-3633): redesign matchLabelSelectors as matchLabelKeys + mismatchLabelKeys

- keps/sig-api-machinery/4020-unknown-version-interoperability-proxy/kep.yaml
- One-line PR description: Updates the status of the [KEP](https://github.com/kubernetes/enhancements/tree/master/keps/sig-api-machinery/4020-unknown-version-interoperability-proxy)  to implementable
- Issue link: https://github.com/kubernetes/enhancements/issues/4020
> KEP-4020: Unknown Version Interoperability Proxy :  Update KEP status as 'implementable'

- keps/sig-scheduling/3633-matchlabelkeys-to-podaffinity/kep.yaml
- One-line PR description: update status on kep.yaml. It's required to be merged by enhancement freeze. ([ref](https://github.com/kubernetes/enhancements/issues/3633#issuecomment-1591843760))
> update(kep-3633): update status on kep.yaml

- keps/prod-readiness/sig-node/3085.yaml
- keps/sig-node/3085-pod-conditions-for-starting-completition-of-sandbox-creation/kep.yaml
- One-line PR description: We never went to beta and we name changed so we are leaving this in alpha.
- Issue link: https://github.com/kubernetes/enhancements/issues/3085
> KEP-3085: update kep with implementation details for alpha

- keps/sig-node/2400-node-swap/README.md
- keps/sig-node/2400-node-swap/kep.yaml
- One-line PR description: Graduate swap to Beta 1
> KEP-2400: Add missing questions from latest PRR template

- keps/prod-readiness/sig-node/4033.yaml
- keps/sig-node/4033-group-driver-detection-over-cri/README.md
- keps/sig-node/4033-group-driver-detection-over-cri/kep.yaml
- One-line PR description: KEP for discovering kubelet cgroup driver from CRI
- Issue link: #4033 
> KEP-4033: Discover cgroup driver from CRI

- keps/sig-node/3545-improved-multi-numa-alignment/kep.yaml
- One-line PR description: Update milestones in kep.yaml
- Issue link: https://github.com/kubernetes/enhancements/issues/3545
> KEP-3545: update milestones for Improved multi-numa alignment in Topology Manager

- keps/sig-node/3960-pod-lifecycle-sleep-action/README.md
- keps/sig-node/3960-pod-lifecycle-sleep-action/kep.yaml
Update kep3960's status to implementable, and address the comments https://github.com/kubernetes/enhancements/pull/3961#discussion_r1231439717 left in last pr.
- Issue link: https://github.com/kubernetes/enhancements/issues/3960#issue-1679434215
https://github.com/kubernetes/enhancements/issues/3960#issuecomment-1593964948
> kep3960: update status to "implementable"

- keps/prod-readiness/sig-node/2403.yaml
- keps/sig-node/2403-pod-resources-allocatable-resources/README.md
- keps/sig-node/2403-pod-resources-allocatable-resources/kep.yaml
- One-line PR description: graduate podresources `getallocatable` endpoint to GA
- Issue link: https://github.com/kubernetes/enhancements/issues/2403
> KEP-2403: graduate to GA

- keps/sig-network/3458-remove-transient-node-predicates-from-service-controller/README.md
- keps/sig-network/3836-kube-proxy-improved-ingress-connectivity-reliability/README.md
- One-line PR description: addressing [comment](https://github.com/kubernetes/enhancements/issues/3836#issuecomment-1592979067) applicable to both 3458 and 3836
- Issue link: https://github.com/kubernetes/enhancements/issues/3836 / https://github.com/kubernetes/enhancements/issues/3458
/sig network
/assign @Atharva-Shinde
> KEP 3458/3836 - update test plan

- keps/sig-node/2403-pod-resources-allocatable-resources/kep.yaml
- One-line PR description: graduate podresources `getallocatable` endpoint to GA
- Issue link: https://github.com/kubernetes/enhancements/issues/2403
- Other comments: forgot to update the expected maturity stage, fixing now
> node: podres: getalloc: fix expected stage

- keps/sig-api-machinery/3488-cel-admission-control/README.md
- One-line PR description: KEP-3488: Add GA criteria
> KEP-3488: Add GA criteria

- keps/sig-storage/1491-csi-migration-vsphere/README.md
- keps/sig-storage/1885-csi-migration-azurefile/README.md
- One-line PR description: Update timelines for vsphere/azurefile CSI removal for n-3 node support
- Issue link: https://github.com/kubernetes/enhancements/issues/3935
/sig storage architecture
/assign @msau42 @jsafrane
> KEP-3935: Update timelines for vsphere/azurefile CSI removal

- keps/sig-auth/2799-reduction-of-secret-based-service-account-token/kep.yaml
the feature is tracked in 1.28 but this field is forgot to update in https://github.com/kubernetes/enhancements/pull/3964
> KEP-2799: update latest-milestone to 1.28

- keps/prod-readiness/sig-api-machinery/365.yaml
- keps/sig-api-machinery/365-paginated-lists/README.MD
- keps/sig-api-machinery/365-paginated-lists/kep.yaml
Ref https://github.com/kubernetes/enhancements/issues/365
Ref https://github.com/kubernetes/kubernetes/issues/108003
/assign @deads2k @lavalamp @smarterclayton @liggitt
> KEP-365: Target API List Pagination at GA

- keps/sig-auth/3331-structured-authentication-configuration/README.md
- keps/sig-auth/3331-structured-authentication-configuration/kep.yaml
- Update alpha milestone to v1.29 for Structured Authentication Configuration
KEP issue: https://github.com/kubernetes/enhancements/issues/3331
> [StructuredAuthnConfig] update alpha milestone to v1.29

- keps/sig-auth/3221-structured-authorization-configuration/README.md
- keps/sig-auth/3221-structured-authorization-configuration/kep.yaml
Updates metadata for targeting Kubernetes 1.29
> KEP-3221: Update for 1.29

- keps/provider-aws/629-alb-ingress-controller/README.md
- keps/provider-aws/630-ebs-csi-driver/README.md
- keps/sig-api-machinery/1623-standardize-conditions/README.md
- keps/sig-api-machinery/2339-storageversion-api-for-ha-api-servers/README.md
- keps/sig-auth/1393-oidc-discovery/README.md
- keps/sig-auth/1687-hierarchical-namespaces-subproject/README.md
- keps/sig-scheduling/986-resource-quota-scope-selectors/README.md
- keps/sig-storage/2263-volume-scale-testing/README.md
- keps/sig-storage/989-extend-datasource/README.md
- keps/sig-windows/1122-windows-csi-support/README.md
- keps/sig-windows/689-windows-gmsa/README.md
> Typo fix in multiple keps

- keps/sig-cluster-lifecycle/kubeadm/3614-etcd-learner-mode/README.md
- keps/sig-cluster-lifecycle/kubeadm/3614-etcd-learner-mode/kep.yaml
ref https://github.com/kubernetes/enhancements/issues/3614
https://github.com/kubernetes/kubernetes/pull/120228
> update etcd learner mode status of kubeadm implementation

- keps/sig-storage/2268-non-graceful-shutdown/kep.yaml
- One-line PR description: mark non-graceful node shutdown as implemented 
- Issue link: https://github.com/kubernetes/enhancements/issues/2268
- Other comments: all the tasks are done.
> mark non-graceful node shutdown as implemented

- keps/sig-storage/1790-recover-resize-failure/README.md
- One-line PR description: update the description in the making-resizestatus-more-general-in-v1.28 section
- Issue link: #1790 
- Other comments: https://github.com/kubernetes/kubernetes/pull/116335#issuecomment-1624566731
> update the description in the making-resizestatus-more-general-in-v1.28 section

- keps/sig-api-machinery/1040-priority-and-fairness/README.md
- keps/sig-api-machinery/1040-priority-and-fairness/kep.yaml
- One-line PR description: This PR adjusts the GA criteria of API Priority and Fairness, to bring them more in line with our current thinking, and notes that all but one have been met.
- Issue link:
> KEP-1040: Check off most remaining GA criteria

- keps/prod-readiness/sig-network/2681.yaml
- keps/sig-network/2681-pod-host-ip/README.md
- keps/sig-network/2681-pod-host-ip/kep.yaml
Move KEP 2681 to Beta
/cc @thockin
> Move KEP 2681 to Beta

- keps/sig-auth/2799-reduction-of-secret-based-service-account-token/README.md
- keps/sig-auth/2799-reduction-of-secret-based-service-account-token/kep.yaml
LegacyServiceAccountTokenCleanUp in kep.yaml
- Issue link: [#120298](https://github.com/kubernetes/kubernetes/issues/120298)
> Add kube-apiserver to the components field for LegacyServiceAccountTokenCleanUp in kep.yaml.

- keps/prod-readiness/sig-instrumentation/3466.yaml
- keps/sig-instrumentation/3466-kubernetes-component-health-slis/README.md
- keps/sig-instrumentation/3466-kubernetes-component-health-slis/kep.yaml
Component SLIs is graduating to stable.
- Issue link: https://github.com/kubernetes/enhancements/issues/3466
> bump component slis to stable

- keps/prod-readiness/sig-auth/3299.yaml
- keps/sig-auth/3299-kms-v2-improvements/README.md
- keps/sig-auth/3299-kms-v2-improvements/kep.yaml
- Update [KEP](https://github.com/kubernetes/enhancements/tree/master/keps/sig-auth/3299-kms-v2-improvements) for GA
fixes https://github.com/kubernetes/kubernetes/issues/120308
/sig auth
/assign enj
> KMSv2: Update KEP for GA

- keps/sig-scheduling/3633-matchlabelkeys-to-podaffinity/kep.yaml
- One-line PR description: Update the target version of KEP-3633
/cc @alculquicondor @Huang-Wei @ahg-g
> Update the target version of KEP-3633

- keps/sig-api-machinery/365-paginated-lists/kep.yaml
As requested in https://github.com/kubernetes/enhancements/issues/365#issuecomment-1731740699
Ref #365
> Mark pagination kep as implementable

- keps/sig-api-machinery/2339-storageversion-api-for-ha-api-servers/README.md
- One-line PR description: This PR updates [KEP 2339](https://github.com/enj/enhancements/blob/master/keps/sig-api-machinery/2339-storageversion-api-for-ha-api-servers/README.md) to reflect current status.
1. Updates references to `storageVersion.status.commonEncodingVersion` (instead of `storageVersion.status.agreedEncodingVersion`)
2. Adds information about newly added field to the API: `storageVersion.status.storageVersions.servedVersions`
3. Adds implementation history
- Issue link: https://github.com/kubernetes/enhancements/issues/2339
> Update StorageVersion API KEP to reflect current state

- keps/sig-apps/3939-allow-replacement-when-fully-terminated/README.md
Update some of the details for beta.  
- Issue link: #3939 
> update 3939 with some items for beta.

- keps/prod-readiness/sig-api-machinery/2876.yaml
- keps/sig-api-machinery/2876-crd-validation-expression-language/kep.yaml
- One-line PR description: Promote CRD validation rule to stable
> [KEP-2876]Promote CRD validation rule to stable

- keps/prod-readiness/sig-node/2371.yaml
- keps/sig-node/2371-cri-pod-container-stats/README.md
- keps/sig-node/2371-cri-pod-container-stats/kep.yaml
- One-line PR description: retarget this KEP to Alpha
- Issue link: https://github.com/kubernetes/enhancements/issues/2371
> KEP 2371: retarget to alpha for 1.29

- keps/sig-api-machinery/2338-graduate-API-gzip-compression-support-to-GA/kep.yaml
- One-line PR description: Update the KEP data to match reality
- Issue link: https://github.com/kubernetes/enhancements/issues/2338
The feature gate is marked beta, so I assume the feature is also beta.
> KEP-2338: update KEP data for gzip compression

- keps/prod-readiness/sig-storage/3107.yaml
- keps/sig-storage/3107-csi-nodeexpandsecret/README.md
- keps/sig-storage/3107-csi-nodeexpandsecret/kep.yaml
- Issue link: https://github.com/kubernetes/enhancements/issues/3107
https://github.com/kubernetes/kubernetes/pull/115451
> Graduate CSI Node expand secret feature to GA

- keps/sig-api-machinery/3488-cel-admission-control/README.md
- One-line PR description: Update description of the CEL authz library API to reflect minor changes made during implementation/alpha.
> KEP-3488: Update table of CEL authz library methods.

- keps/sig-apps/2879-ready-pods-job-status/kep.yaml
- One-line PR description: #4237 missed setting the status to implemented.
- Issue link: #2879
> Mark KEP for JobReadyPods as implemented

- keps/prod-readiness/sig-api-machinery/4222.yaml
- keps/sig-api-machinery/4222-cbor-serializer/README.md
- keps/sig-api-machinery/4222-cbor-serializer/kep.yaml
- Issue link: https://github.com/kubernetes/enhancements/issues/4222
/assign @jpbetz
> KEP-4222: CBOR Serializer

- keps/prod-readiness/sig-apps/3939.yaml
- keps/sig-apps/3939-allow-replacement-when-fully-terminated/README.md
- keps/sig-apps/3939-allow-replacement-when-fully-terminated/kep.yaml
- One-line PR description: Promote PodReplacementPolicy KEP to beta in 1.29.
- Issue link: #3939 
> KEP-3939: promote to beta in 1.29.

- keps/prod-readiness/sig-api-machinery/3157.yaml
- keps/sig-api-machinery/3157-watch-list/README.md
- keps/sig-api-machinery/3157-watch-list/kep.yaml
- One-line PR description: Update KEP 3157 (watch-list) for milestone 1.29
> Update KEP 3157 (watch-list) for milestone 1.29

- keps/prod-readiness/sig-cli/3638.yaml
- keps/sig-cli/3638-kubectl-plugin-subcommands/README.md
- keps/sig-cli/3638-kubectl-plugin-subcommands/kep.yaml
- One-line PR description: Promotes plugin subcommand resolution to beta
- Issue link: https://github.com/kubernetes/enhancements/issues/3638
> KEP-3638: Promotes plugin subcommand resolution to beta

- keps/sig-node/753-sidecar-containers/README.md
- One-line PR description: add termination alternatives for beta
- Issue link: https://github.com/kubernetes/enhancements/issues/753
> KEP-753: add termination alternatives for beta

- keps/sig-api-machinery/3488-cel-admission-control/kep.yaml
- One-line PR description: Update the latest milestone
> [KEP-3488]Update the latest milestone

- keps/sig-node/3673-kubelet-parallel-image-pull-limit/README.md
- One-line PR description: Update parallel image pull KEP with latest template
> Update parallel image pull KEP with latest template

- keps/sig-node/4216-image-pull-per-runtime-class/README.md
Refactors some of the sentences for grammar in this KEP. There is no change to the original design
- Issue link: https://github.com/kubernetes/enhancements/issues/4216
> 4216: Refactor some of the sentences for grammar

- keps/sig-apps/4026-crojob-scheduled-timestamp-annotation/kep.yaml
> Fill in missing title

- OWNERS_ALIASES
- keps/sig-etcd/OWNERS
Seeding a folder for sig-etcd.
/cc @wenjiaswe @serathius @ahrtr @jmhbnz
> seed KEPs for sig-etcd

- keps/sig-network/784-kube-proxy-component-config/README.md
- keps/sig-network/784-kube-proxy-component-config/kep.yaml
- One-line PR description: Updated template with PRR Questionnaire
- Issue link: https://github.com/kubernetes/enhancements/issues/784
> KEP-784: update template

- keps/sig-apps/3329-retriable-and-non-retriable-failures/README.md
- keps/sig-apps/3329-retriable-and-non-retriable-failures/kep.yaml
- One-line PR description: Update the KEP about the PodGC fix
- also updated the tentative "stable" version as 1.30
> Update PodFailurePolicy about the PodGC fix

- keps/sig-etcd/4326-downgrade/4326.yaml
- keps/sig-etcd/4326-downgrade/README.md
For now moving in unchanged formed.
/sig etcd
> KEP-4326: Move etcd downgrade design into KEP directory

- keps/sig-etcd/4331-livez-readyz/4331.yaml
- keps/sig-etcd/4331-livez-readyz/README.md
Adapt etcd livez/readyz design doc to kep.
- Issue link:
https://github.com/kubernetes/enhancements/issues/4331
> KEP-4331: adapt etcd livez/readyz design doc to kep.

- keps/sig-api-machinery/1040-priority-and-fairness/README.md
- One-line PR description: Check of last GA graduation criterion
- Issue link:
> KEP-1040: Check off last GA graduation criterion

- keps/sig-auth/3331-structured-authentication-configuration/README.md
- update fields to reflect alpha implementation
KEP issue: https://github.com/kubernetes/enhancements/issues/3331
/sig auth
/assign enj
> KEP-3331: update fields to reflect alpha implementation

- keps/sig-storage/2485-read-write-once-pod-pv-access-mode/kep.yaml
- One-line PR description: Mark KEP status "implemented"
- Issue link: https://github.com/kubernetes/enhancements/issues/2485
- Other comments: The final PR (GA blog, https://github.com/kubernetes/website/pull/43418) should be merged soon, no pending feedback
/sig storage
> KEP-2485: mark status implemented

- OWNERS_ALIASES
- One-line PR description: Changing Jay Vyas handler on OWNER_ALIASES for SIG-Windows
- Issue link: https://github.com/kubernetes/community/issues/7614
> Changing Jay Vyas to Amim Knabben handler on OWNER_ALIASES

- OWNERS_ALIASES
Ref https://github.com/kubernetes/community/issues/7618
/assign @mwielgus @swatisehgal @mrbobbytables
> WG-Batch leads update

- keps/sig-network/3453-minimize-iptables-restore/kep.yaml
- One-line PR description: mark KEP-3453 as implemented
- Issue link: #3453 
- Other comments: all tasks are done
> mark KEP-3453 as implemented

- keps/sig-scheduling/4247-queueinghint/README.md
- keps/sig-scheduling/4247-queueinghint/kep.yaml
- One-line PR description: Update the GA requirement based on the current situation.
- Issue link: https://github.com/kubernetes/enhancements/issues/4247
/cc @alculquicondor
> KEP-4247: Update beta criteria for SchedulerQueueingHints

- keps/sig-auth/3325-self-subject-attributes-review-api/kep.yaml
- One-line PR description: mark KEP-3325 as implemented
- Other comments: all tasks was done in 1.28 and the issue was closed.
> mark KEP-3325 as implemented

- keps/sig-api-machinery/2876-crd-validation-expression-language/kep.yaml
- One-line PR description: mark KEP-2876 as implemented
- Other comments: all tasks are done in 1.29
> mark KEP-2876 as implemented

- keps/sig-api-machinery/3157-watch-list/README.md
- keps/sig-api-machinery/3157-watch-list/kep.yaml
- One-line PR description: Update KEP 3157 (watch-list) for milestone 1.30
> Update KEP 3157 (watch-list) for milestone 1.30

- keps/sig-apps/3939-allow-replacement-when-fully-terminated/README.md
update metrics and e2e test parts to reflect latest implementation details
- Issue link: https://github.com/kubernetes/enhancements/issues/3939
> KEP-3939: update metrics and e2e test parts to reflect latest implementation details

- keps/sig-api-machinery/3157-watch-list/README.md
- One-line PR description: Updates the feature name currently used by `KCM`. This is important during troubleshooting.
> KEP 3157 (watch-list): update the feature name used by KCM

- keps/sig-api-machinery/1040-priority-and-fairness/kep.yaml
This PR updates the kep.yaml to mark it as implemented, and sets latest-milestone to 1.30 because we are changing the storage version and widening a validation criterion in 1.30.
- Issue link: https://github.com/kubernetes/enhancements/issues/1040
> KEP-1040: Mark API Priority and Fairness as implemented

- keps/sig-scheduling/2926-job-mutable-scheduling-directives/kep.yaml
Mark KEP as implemented.
- Issue link: #2926 
> [KEP-2926]:mark kep-2926 as implemented

- keps/sig-network/3458-remove-transient-node-predicates-from-service-controller/README.md
- keps/sig-network/3458-remove-transient-node-predicates-from-service-controller/kep.yaml
- One-line PR description: extended stable to v1.30 
- Other comments: agreed to extend stable to 1.30, see: https://github.com/kubernetes/enhancements/issues/3458#issuecomment-1904338954
> KEP 3458: v1.30 update - extended stable to 1.30

- keps/sig-network/3866-nftables-proxy/README.md
Resolves unresolved section of the kep after implementation [k/k#122692](https://github.com/kubernetes/kubernetes/pull/122692)
part of nftables todo [k/k#122572](https://github.com/kubernetes/kubernetes/issues/122572)
/assign @danwinship
> KEP-3866 : update service ip behaviour

- keps/sig-api-machinery/2876-crd-validation-expression-language/README.md
- One-line PR description: Adopt the latest PRR template
> [KEP-2876] Adopt the latest PRR template

- keps/sig-storage/3107-csi-nodeexpandsecret/kep.yaml
- One-line PR description: mark 3107 as implemented
- Issue link: #3107 
- Other comments: all tasks are done.
> mark 3107 as implemented

- keps/sig-storage/3756-volume-reconstruction/README.md
- One-line PR description: update volume reconstruction KEP with https://github.com/kubernetes/kubernetes/pull/117804
- Issue link:  https://github.com/kubernetes/enhancements/issues/3756
https://github.com/kubernetes/kubernetes/pull/117804 introduces *uncertain attach-ability* of a reconstructed volume. Add it to the description of volume reconstruction.
~WIP:~
* ~links in the KEP need to be updated to code after https://github.com/kubernetes/kubernetes/pull/117804 is merged.~
cc @jingxu97 @gnufied
> Add note about uncertain attachability

- keps/sig-api-machinery/2339-storageversion-api-for-ha-api-servers/kep.yaml
- One-line PR description: Mark StorageVersion API graduation to beta in 1.30
- Issue link: https://github.com/kubernetes/enhancements/issues/2339
> Mark Storage Version API Kep for graduation to beta in 1.30

- keps/prod-readiness/sig-api-machinery/3488.yaml
- keps/sig-api-machinery/3488-cel-admission-control/README.md
- keps/sig-api-machinery/3488-cel-admission-control/kep.yaml
- One-line PR description: Clear the GA graduation criteria for ValidatingAdmissionPolicy
> [KEP-3488]Promote ValidatingAdmissionPolicy to GA

- keps/sig-api-machinery/2523-consistent-resource-versions-semantics/kep.yaml
Implemented by https://github.com/kubernetes/kubernetes/pull/91505 on 202-05-27
> Cleanup consistent resource version semantics KEP to reflect reality

- keps/sig-api-machinery/365-paginated-lists/kep.yaml
Close https://github.com/kubernetes/enhancements/issues/365
/assign @jpbetz @deads2k
> Mark pagination KEP as implemented

- keps/sig-auth/2799-reduction-of-secret-based-service-account-token/README.md
- keps/sig-auth/2799-reduction-of-secret-based-service-account-token/kep.yaml
- One-line PR description: Promote KEP-2799 to stable
> Promote kep-2799 to stable.

- keps/sig-architecture/4402-go-workspaces/kep.yaml
- One-line PR description:  Mark 4402 as implementable
- Issue link: https://github.com/kubernetes/enhancements/issues/4402
> KEP 4402: Implementable (Go workspaces for k/k)

- keps/prod-readiness/sig-network/2681.yaml
- keps/sig-network/2681-pod-host-ip/README.md
- keps/sig-network/2681-pod-host-ip/kep.yaml
Move KEP 2681 to GA
/cc @thockin
> Move KEP 2681 to GA

- keps/prod-readiness/sig-apps/3017.yaml
- keps/sig-apps/3017-pod-healthy-policy-for-pdb/README.md
- keps/sig-apps/3017-pod-healthy-policy-for-pdb/kep.yaml
- One-line PR description: Graduate UnhealthyPodEvictionPolicy for PDBs to stable
> KEP-3017: Graduate UnhealthyPodEvictionPolicy for PDBs to stable

- keps/sig-node/727-resource-metrics-endpoint/kep.yaml
- One-line PR description: Updated status of [KEP-727](https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/727-resource-metrics-endpoint) to implemented
- Issue link: https://github.com/kubernetes/enhancements/issues/727
> Update status of Kubelet Resource Metrics KEP to implemented

- keps/prod-readiness/sig-storage/3141.yaml
- keps/sig-storage/3141-prevent-volume-mode-conversion/README.md
- keps/sig-storage/3141-prevent-volume-mode-conversion/kep.yaml
- One-line PR description: Update the KEP to Stable
- Issue link: https://github.com/kubernetes/enhancements/issues/3141
> KEP-3141: Graduate "Prevent unauthorised volume mode conversion" to Stable

- keps/sig-node/2400-node-swap/README.md
Update Swap KEP with findings from beta2 testing.
- Issue link: #2400 
Our recommendation is to implement `MemorySwap = NoSwap` and to let this feature sit in beta2. We don't want to promote this to GA at this time but we realize that someone guard rails are necessary for this feature.
In this KEP, we propose some best practices and allow for opt-in support for this feature regardless of the feature toggle.
> [KEP-2400] - Update KEP with findings from beta2

- keps/sig-network/3178-iptables-cleanup/kep.yaml
- One-line PR description: Mark KEP-3178 as implemented
- Issue link: https://github.com/kubernetes/enhancements/issues/3178
> Mark KEP-3178 as implemented

- keps/sig-network/1669-proxy-terminating-endpoints/kep.yaml
- One-line PR description: mark KEP-1669 as implemented
- Issue link: #1669 
- Other comments: all task are done and feature-gate is removed in 1.30
> mark KEP-1669 as implemented

- keps/sig-node/4191-split-image-filesystem/README.md
Update KEP with items we did in 1.29.
- Issue link: [#4198 ](https://github.com/kubernetes/enhancements/issues/4191)
> KEP-4191: alpha 1 additions

- keps/prod-readiness/sig-node/2400.yaml
- keps/sig-node/2400-node-swap/kep.yaml
- One-line PR description: update swap for latest-milestone.
- Issue link: #2400 
> [KEP-2400] update latest milestone for swap KEP

- keps/sig-auth/3221-structured-authorization-configuration/README.md
- keps/sig-auth/3221-structured-authorization-configuration/kep.yaml
> KEP-3221 - WIP 1.30 update

- keps/sig-api-machinery/4192-svm-in-tree/README.md
- keps/sig-api-machinery/4192-svm-in-tree/kep.yaml
- One-line PR description: Update to the _svm-in-tree_ [KEP](https://github.com/kubernetes/enhancements/pull/4240).
- Other comments: Ref- https://github.com/kubernetes/enhancements/pull/4240#pullrequestreview-1659647831
> [UPDATE] KEP-4192: Move Storage Version Migrator in-tree

- keps/sig-node/4191-split-image-filesystem/kep.yaml
- One-line PR description: update latest milestone to 1.30
- Issue link: #4191 
Waiting on cadvisor release and working on e2e tests. Still keeping this in alpha.
> KEP-4191: update latest milestone to 1.30

- keps/prod-readiness/sig-auth/3221.yaml
- keps/sig-auth/3221-structured-authorization-configuration/README.md
- keps/sig-auth/3221-structured-authorization-configuration/kep.yaml
- One-line PR description: Add beta PRR record, update metrics
- Issue link: https://github.com/kubernetes/enhancements/issues/3221
Follow-up from https://github.com/kubernetes/enhancements/pull/4456
/assign @jpbetz 
for PRR
/assign @logicalhan 
for metrics sanity check (or delegate)
/cc @ritazh @palnabarun 
/sig auth
> KEP-3221: Add PRR, update metrics

- keps/sig-instrumentation/647-apiserver-tracing/README.md
Address https://github.com/kubernetes/enhancements/issues/647#issuecomment-1932229695
> There is an unanswered question [here](https://github.com/dashpole/enhancements/blob/47c37e437cecb2d646ae4619485a5a3deac4c056/keps/sig-instrumentation/647-apiserver-tracing/README.md#what-steps-should-be-taken-if-slos-are-not-being-met-to-determine-the-problem)
- One-line PR description: Answer additional APIServer Tracing PRR question
/assign @dgrisonnet
> KEP-647: Answer missed APIServer Tracing PRR question

- keps/sig-api-machinery/4008-crd-ratcheting/kep.yaml
- One-line PR description: updating milestone
- Issue link: https://kep.k8s.io/4008
- Other comments: no other changes needed, already approved for beta in 1.29
> bump milestone for 4008

- keps/sig-node/3673-kubelet-parallel-image-pull-limit/README.md
- One-line PR description: Add SLO description 
> KEP-3673: update to include SLO info

- keps/sig-storage/3141-prevent-volume-mode-conversion/README.md
- One-line PR description: Update failure modes in README
- Issue link: https://github.com/kubernetes/enhancements/issues/3141
- Other comments: Addressing comment from https://github.com/kubernetes/enhancements/issues/3141#issuecomment-1932131767
> KEP-3141: Add no known failure modes to README

- keps/prod-readiness/sig-storage/1710.yaml
- keps/sig-storage/1710-selinux-relabeling/README.md
- Add a new PRR chapter.
- Clarify behavior on feature gate changes.
- Issue link: #1710
> Complete the KEP for SELinuxMount alpha

- keps/prod-readiness/sig-api-machinery/3962.yaml
- keps/sig-api-machinery/3962-mutating-admission-policies/README.md
- keps/sig-api-machinery/3962-mutating-admission-policies/kep.yaml
- One-line PR description: Add MutatingAdmissionPolicy as alpha in 1.30
- Issue link: https://github.com/kubernetes/enhancements/issues/3962
> [KEP 3962]MutatingAdmissionPolicy: alpha in 1.30

- keps/sig-auth/4193-bound-service-account-token-improvements/kep.yaml
- One-line PR description: Update KEP-4193 to beta
/cc @munnerz @enj
> KEP-4193: Update kep to beta

- keps/sig-api-machinery/2339-storageversion-api-for-ha-api-servers/README.md
- One-line PR description: Update KEP to include latest scalability question. [xRef](https://github.com/kubernetes/enhancements/issues/2339#issuecomment-1932778523)
- Issue link: https://github.com/kubernetes/enhancements/issues/2339
> Update README with scalability questions addressed

- keps/sig-api-machinery/4222-cbor-serializer/kep.yaml
- One-line PR description: Updates alpha target to 1.30
> KEP-4222: Update alpha target to 1.30.

- keps/sig-instrumentation/2305-metrics-cardinality-enforcement/README.md
- One-line PR description: Add missing required sections in README.md
- Issue link: https://github.com/kubernetes/enhancements/issues/2305
> Metrics Cardinality Enforcement - Update README 

- keps/prod-readiness/sig-auth/3257.yaml
- keps/sig-auth/3257-cluster-trust-bundles/README.md
- keps/sig-auth/3257-cluster-trust-bundles/kep.yaml
Pick up changes that have been made during the implementation process.
> KEP-3257 (ClusterTrustBundles): Promote to beta; Update to reflect implementation

- OWNERS_ALIASES
@dims @mrbobbytables ptal
Fixing https://github.com/kubernetes/enhancements/pull/4458#issuecomment-1917750271
> Add sig-node-tech-leads to custom content

- OWNERS_ALIASES
- One-line PR description: We broke the CI with #4500
- Issue link:
> Fix duplicate sig-node-tech-leads key

- keps/sig-api-machinery/4346-informer-metrics/README.md
- keps/sig-api-machinery/4346-informer-metrics/kep.yaml
- One-line PR description: Supplement for KEP-4346
- Issue link:  https://github.com/kubernetes/enhancements/issues/4346
> Supplement for KEP-4346

- keps/prod-readiness/sig-api-machinery/4346.yaml
- One-line PR description: I approved the PRR in https://github.com/kubernetes/enhancements/pull/4349#issuecomment-1934901937, but I forgot to ensure the metadata file was present
- Issue link: https://github.com/kubernetes/enhancements/issues/4346
/assign @jpbetz
> KEP-4346: add PRR metadata file for 4346

- keps/sig-api-machinery/3716-admission-webhook-match-conditions/kep.yaml
KEP-3716:  CEL-based admission webhook match conditions #3716 
marks missed line stable
- Issue link: https://github.com/kubernetes/enhancements/issues/3716
Just missed setting this line in the yaml
> update stage to stable

- keps/sig-auth/3257-cluster-trust-bundles/README.md
Answer the new node-level resource scalability question.
Issue: https://github.com/kubernetes/enhancements/issues/3257
> KEP-3257 (ClusterTrustBundles): Answer node-level scalability questions

- keps/sig-cloud-provider/2436-controller-manager-leader-migration/README.md
- keps/sig-cloud-provider/2436-controller-manager-leader-migration/kep.yaml
- Issue link:https://github.com/kubernetes/enhancements/issues/2436
> KEP-2436: mark as implemented

- keps/sig-auth/3221-structured-authorization-configuration/README.md
- One-line PR description: Made metric label values consistent with subject access review status field names
xref https://github.com/kubernetes/kubernetes/pull/123333
/sig auth
/assign @ritazh @palnabarun
> KEP-3221: update metric decision label values

- keps/sig-architecture/4402-go-workspaces/kep.yaml
Fixes #4402 
- One-line PR description: #4402 is implemented
- Issue link: #4402
> KEP-4402: Workspaces is implemented

- keps/sig-multicluster/4322-cluster-inventory/README.md
- keps/sig-multicluster/4322-cluster-inventory/kep.yaml
- One-line PR description: Add a new KEP to introduce the cluster inventory API for multilple kubernetes cluster management
- Issue link: https://github.com/kubernetes/enhancements/issues/4322
> KEP-4322: Cluster Inventory API

- keps/sig-api-machinery/3352-aggregated-discovery/kep.yaml
KEP-3352 Mark Aggregated Discovery as implemented
/assign @jpbetz @deads2k
> KEP-3352 Mark Aggregated Discovery as implemented

- keps/sig-storage/1710-selinux-relabeling/README.md
- One-line PR description: Remove pod admission in kubelet for SELinuxMount feature.
It has show to be very noisy. I am moving the new kubelet pod admission from "Proposal" / "Design details" to "Alternatives considered".
WIP implementation of the admission that I used for testing + the noisy output: https://github.com/kubernetes/kubernetes/pull/123193
> 1710: Remove pod admission from the SELinux KEP

- keps/sig-auth/3221-structured-authorization-configuration/README.md
- One-line PR description: Update KEP-3221 with 1.30 changes
- Issue link:
/cc @palnabarun @liggitt
> KEP-3221: update for 1.30

- keps/sig-autoscaling/2702-graduate-hpa-api-to-GA/README.md
- One-line PR description: fix link and update it to latest
- Issue link:
> Update kep 2702 graduate-hpa-api

- OWNERS_ALIASES
part of https://github.com/kubernetes/community/issues/7759
/kind cleanup
> add stefan as apimachinery lead

- keps/sig-scheduling/3022-min-domains-in-pod-topology-spread/kep.yaml
- One-line PR description: Add kube-apiserver to feature-gate components
- Issue link: https://github.com/kubernetes/enhancements/issues/3022
> Add kube-apiserver to feature-gate components for MinDomainsInPodTopologySpread

- keps/sig-node/4381-dra-structured-parameters/README.md
- One-line PR description: Several changes to the API were made during the implementation phase.
/cc @mrunalp 
Here's the KEP update we discussed in https://github.com/kubernetes/kubernetes/pull/123516#discussion_r1524077706.
/cc @klueska 
Can you review?
> DRA: update structured parameters KEP to match API in 1.30

- keps/prod-readiness/sig-api-machinery/4358.yaml
- keps/sig-api-machinery/4358-custom-resource-field-selectors/README.md
- keps/sig-api-machinery/4358-custom-resource-field-selectors/kep.yaml
- Issue link: https://github.com/kubernetes/enhancements/issues/4358
> KEP-4358: update CRD field selector KEP for beta promotion

- OWNERS_ALIASES
Ref https://github.com/kubernetes/community/issues/7803
/assign @mpuckett159 @eddiezane
> Update sig-cli leads

- keps/sig-cloud-provider/2395-removing-in-tree-cloud-providers/README.md
- keps/sig-cloud-provider/2395-removing-in-tree-cloud-providers/kep.yaml
- One-line PR description: Book keeping for cleaning up removal of in-tree cloud providers
- Issue link: https://github.com/kubernetes/enhancements/issues/2395
- Other comments: Also see https://github.com/kubernetes/kubernetes/pull/124519
> KEP-2395: Book keeping for cleaning up removal of in-tree cloud providers

- keps/sig-network/3668-reserved-service-nodeport-range/kep.yaml
- One-line PR description: mark status as `implemented`
- Issue link: https://github.com/kubernetes/enhancements/issues/3668#issuecomment-1740265613
> KEP-3668: mark status as implemented

- keps/sig-scheduling/3633-matchlabelkeys-to-podaffinity/kep.yaml
- One-line PR description: Graduate MatchLabelKeys to beta in v1.31
/cc @alculquicondor
> Graduate MatchLabelKeys to beta in v1.31

- OWNERS_ALIASES
Updating SIG Autoscaling leads.
- Issue link: 
https://github.com/kubernetes/community/issues/7834
> SIG Autoscaling - Leads Update

- OWNERS_ALIASES
Adding myself as SIG Docs tech lead!
> Adds Kat Cosgrove as SIG Docs tech lead

- OWNERS_ALIASES
Adding salaxander as a SIG docs owner/approver
CC @natalisucks @divya-mohan0209 @reylejano
> docs: add salaxander as SIG docs tech lead

- README.md
- One-line PR description: Adding link to the v1.31 enhancements tracking board to the readme file.
- Issue link: None
- Other comments: Part of the 1.31 release enhancements team work.
> Added v1.31 enhancements tracking board to readme

- keps/sig-api-machinery/3716-admission-webhook-match-conditions/kep.yaml
update this kep to implemented so that we can close 3716
- Issue link:
https://github.com/kubernetes/enhancements/issues/3716
> kep03716: update to "implemented" from "implementable"

- keps/sig-auth/4193-bound-service-account-token-improvements/README.md
- One-line PR description: KEP-4193: Add GA docs requirements
- Issue link: #4193
> KEP-4193: Add GA docs requirements

- keps/sig-node/3619-supplemental-groups-policy/kep.yaml
- One-line PR description: update the latest milestone of KEP-3619: Fine-grained SupplementalGroups control
- Other comments: I'm working on https://github.com/kubernetes/kubernetes/pull/117842. I would like to update the milestone to the next release 🙇
> KEP-3619: update the latest milestone to v1.31

- keps/sig-node/4009-add-cdi-devices-to-device-plugin-api/kep.yaml
- Set 1.31 milestone
- Issue link: https://github.com/kubernetes/enhancements/issues/4009
- Other comments: This issue is scheduled for 1.31 in the [SIG-Node KEP Planning document](https://docs.google.com/document/d/1U10J0WwgWXkdYrqWGGvO8iH2HKeerQAlygnqgDgWv4E/edit)
> KEP-4009: set 1.31 milestone

- keps/sig-node/2008-forensic-container-checkpointing/README.md
During the discussion to graduate this KEP from Alpha to Beta certain changes were requested. This updates the KEP to reflect that all necessary changes have been implemented.
Also the GA graduation requirement "containerd support" has been merged and is now also mentioned in the KEP.
- One-line PR description: reflect current code changes
- Issue link: https://github.com/kubernetes/enhancements/issues/2008
> KEP 2008: Update KEP to reflect current code changes

- keps/sig-node/3960-pod-lifecycle-sleep-action/README.md
- One-line PR description: Fixing typo.
- Issue link:
> Fixing typo

- keps/prod-readiness/sig-network/3836.yaml
- keps/sig-network/3836-kube-proxy-improved-ingress-connectivity-reliability/kep.yaml
- One-line PR description: 1.31 milestone bump for KEP - 3836
/sig network
> KEP 3836: v1.31 milestone update

- keps/sig-api-machinery/4192-svm-in-tree/kep.yaml
- One-line PR description: Updating latest milestone for v1.31
/cc @deads2k @jpbetz @enj
> chore: updates latest milestone

- keps/sig-node/24-apparmor/kep.yaml
- One-line PR description: Updating the stable milestone to 1.31.
- Issue link: https://github.com/kubernetes/enhancements/issues/24
> KEP-24: Update GA milestone to 1.31

- keps/sig-api-machinery/4355-coordinated-leader-election/kep.yaml
> Fix kep.yaml for coordinated leader election

- keps/sig-storage/3751-volume-attributes-class/README.md
Update KEP-3751 VolumeAttributesClass Finazlier Management Design
- Issue link: https://github.com/kubernetes/kubernetes/issues/119298#issuecomment-1960594431
- Other comments: discussed in [Kubernetes CSI Implementation Meeting](https://docs.google.com/document/d/1_hvq3nleqQEYatH9V_Gfep39jMzaFJRSN2ioA0PFq-Q/edit?tab=t.0#bookmark=id.f7jtik9ajm64)
> Update KEP-3751 VolumeAttributesClass Finazlier Management Design

- keps/prod-readiness/sig-cli/4292.yaml
- keps/sig-cli/4292-kubectl-debug-custom-profile/README.md
- keps/sig-cli/4292-kubectl-debug-custom-profile/kep.yaml
- One-line PR description: Promote custom profiling in kubectl to beta 
- Issue link: https://github.com/kubernetes/enhancements/issues/4292
> KEP-4292: Update to promote it to beta

- keps/prod-readiness/sig-node/4033.yaml
- keps/sig-node/4033-group-driver-detection-over-cri/kep.yaml
bump KEP-4033 to beta
- Issue link: https://github.com/kubernetes/enhancements/issues/4033
> KEP-4033: bump to beta

- keps/sig-architecture/4330-compatibility-versions/kep.yaml
- One-line PR description: updating milestone
> update milestones of compatibility-versions

- keps/prod-readiness/sig-node/4580.yaml
- keps/sig-node/4580-deprecate-kubelet-runonce/README.md
- keps/sig-node/4580-deprecate-kubelet-runonce/kep.yaml
- One-line PR description: Deprecate and remove Kubelet RunOnce mode.
- Issue link: https://github.com/kubernetes/enhancements/issues/4580
> deprecate and remove Kubelet RunOnce mode

- keps/sig-apps/3973-consider-terminating-pods-deployment/README.md
- keps/sig-apps/3973-consider-terminating-pods-deployment/kep.yaml
- One-line PR description: add a Deployment Scaling Changes and a New Annotation for ReplicaSets section
- Other comments: Additional changes were identified during the implementation phase. See the following items for more details:
- https://github.com/kubernetes/kubernetes/pull/123670 
- https://github.com/kubernetes/kubernetes/pull/123430#issuecomment-1976423101
> KEP-3973: Update PodReplacementPolicy for Deployments

- keps/sig-api-machinery/4222-cbor-serializer/README.md
- One-line PR description: Update PRR items on release signoff checklist.
- Other comments: This KEP hasn't changed substantially since its PRR was completed for 1.29.
> KEP-4222: Update PRR items on release signoff checklist.

- keps/sig-auth/4193-bound-service-account-token-improvements/kep.yaml
- One-line PR description: Mark as updated for 1.31
/assign @munnerz
> KEP-4193: Mark as updated in 1.31

- keps/sig-instrumentation/2305-metrics-cardinality-enforcement/kep.yaml
See https://github.com/kubernetes/enhancements/issues/2305#issuecomment-2148900862.
> Update `latest-milestone` for KEP-2305

- keps/sig-storage/3751-volume-attributes-class/README.md
Detail design for PV/PVC binding the volume attributes classs
- Issue link: https://github.com/kubernetes/enhancements/issues/3751
/cc @msau42 @carlory
> KEP-3751: Add VAC binding details

- keps/sig-api-machinery/4355-coordinated-leader-election/kep.yaml
> Update CLE KEP milestone to 1.31

- keps/sig-architecture/4330-compatibility-versions/README.md
- One-line PR description: update beta criteria
> compatibility-version: update beta criteria.

- keps/sig-cli/4292-kubectl-debug-custom-profile/kep.yaml
- One-line PR description: Update latest milestone to 1.31
- Issue link: https://github.com/kubernetes/enhancements/issues/4292
> KEP-4292: Update latest milestone to 1.31

- keps/sig-auth/4601-authorize-with-selectors/README.md
- One-line PR description: KEP-4601: add graduation criteria for selector based authorization
- Issue link: #4601 
> KEP-4601: add graduation criteria for selector based authorization

- keps/prod-readiness/sig-node/4680.yaml
- keps/sig-node/4680-add-resource-health-to-pod-status/README.md
- keps/sig-node/4680-add-resource-health-to-pod-status/kep.yaml
KEP: https://github.com/kubernetes/enhancements/issues/4680
/sig node
/assign @ffromani 
/assign @mrunalp
> KEP-4680: Add Resource Health Status to the Pod Status for Device Plugin and DRA

- keps/sig-api-machinery/4222-cbor-serializer/README.md
- One-line PR description: Specify handling of JSON-only custom marshalers.
> KEP-4222: Specify handling of JSON-only custom marshalers.

- keps/sig-network/784-kube-proxy-component-config/kep.yaml
- One-line PR description: Updated milestones
- Issue link: https://github.com/kubernetes/enhancements/issues/784
> KEP 784: Update Milestones

- keps/sig-network/1880-multiple-service-cidrs/README.md
- keps/sig-network/1880-multiple-service-cidrs/kep.yaml
add graduation criteria and additional feature gate to KEP-1880
> add graduation criteria and additional feature gate to KEP-1880

- keps/sig-network/1880-multiple-service-cidrs/README.md
stay two releases on beta, one off and other on
> KEP 1880 stay two releases on beta, one off and other on

- keps/prod-readiness/sig-architecture/2527.yaml
- keps/sig-architecture/2527-clarify-status-observations-vs-rbac/README.md
- keps/sig-architecture/2527-clarify-status-observations-vs-rbac/kep.yaml
Fixes #2527
- One-line PR description: Complete
- Issue link: https://github.com/kubernetes/enhancements/issues/2527
> KEP-2527: KEP (spec vs. status) is implemented

- keps/sig-cluster-lifecycle/kubeadm/4471-cp-join-kubelet-local-apiserver/README.md
- Updating KEP to match the recent discussions and implementation at the following PR:
- https://github.com/kubernetes/kubernetes/pull/125780
- Issue link: #4471 
> KEP-4471: kubeadm: make a control-plane's kubelet talk to the local API Server on kubeadm join

- keps/sig-apps/3973-consider-terminating-pods-deployment/README.md
- One-line PR description: fix scaling calculations in PodReplacementPolicy KEP
- followup to fix https://github.com/kubernetes/enhancements/pull/4670
> KEP-3973: fix scaling calculations in PodReplacementPolicy KEP

- keps/sig-api-machinery/4222-cbor-serializer/README.md
- One-line PR description: Add transcoding opt-out as beta criteria. 
- Other comments: https://github.com/kubernetes/kubernetes/pull/125790#discussion_r1674130995
> KEP-4222: Add transcoding opt-out as beta criteria.

- keps/sig-api-machinery/1040-priority-and-fairness/README.md
- One-line PR description: This revises the borrowing between priority levels from something that scares me a lot (and is not what is implemented) to something that scares me less.
- Issue link: 
- Other comments: There is an issue in k/k about the discrepancy between KEP and code: https://github.com/kubernetes/kubernetes/issues/124125
> KEP-1040: Prescribe less extreme borrowing by exempt priority levels

- OWNERS_ALIASES
/sig node
/assign @haircommander
Related to: https://github.com/kubernetes/community/issues/8011
> added peter hunt as a sig node chair

- README.md
Add the 1.32 Enhancements Tracking Board to the README.md file for reference.
cc @katcosgrove @gracenng @fsmunoz
> Add 1.32 tracking board to readme

- keps/sig-api-machinery/4355-coordinated-leader-election/README.md
- One-line PR description: Shape of the API changed quite a bit in API review and this PR reflects it in the KEP. No other changes. I'd like to revisit the `strategy` field and have not updated it in this PR.
- Issue link: https://github.com/kubernetes/enhancements/issues/4355
> KEP-4355: Update Coordinated Leader Election KEP with details after API Review

- keps/sig-api-machinery/3157-watch-list/README.md
> KEP 3157 (watch-list): replacing standard List request with WatchList mechanism for client-go's List method.

- keps/sig-network/3458-remove-transient-node-predicates-from-service-controller/kep.yaml
- One-line PR description: mark KEP-3458 as implemented
- Other comments: StableLoadBalancerNodeSet: {Default: true, PreRelease: featuregate.GA, LockToDefault: true}, // GA in 1.30
> mark KEP-3458 as implemented

- keps/sig-storage/3141-prevent-volume-mode-conversion/kep.yaml
- One-line PR description: mark KEP-3141 as implemented
- Issue link: #3141 
- Other comments: all task are done.
> mark KEP-3141 as implemented

- keps/sig-node/3288-separate-stdout-from-stderr/README.md
- keps/sig-node/3288-separate-stdout-from-stderr/kep.yaml
- One-line PR description: Updating milestone of the `SplitStdoutAndStderr` feature
- Issue link: #3288 
> feat: move SplitStdoutAndStderr feature to v1.32

- keps/sig-node/4569-cgroup-v1-maintenance-mode/kep.yaml
- One-line PR description: The KEP was complete in the last release so we can mark it as implemented.
- Issue link: #4569 
> KEP-4569: mark as implemented

- keps/sig-node/4009-add-cdi-devices-to-device-plugin-api/kep.yaml
- One-line PR description: KEP-4009: set status to `implemented`
- Issue link: https://github.com/kubernetes/enhancements/issues/4009
- Other comments: It was done by [this request](https://github.com/kubernetes/enhancements/issues/4009#issuecomment-2335018035)
> KEP-4009: set status to `implemented`

- keps/sig-node/753-sidecar-containers/README.md
- keps/sig-node/753-sidecar-containers/kep.yaml
Some clarifications on what was imlpemented and graduation criteria for GA
- Issue link:
KEP: #753
> clarifications for sidecar container feature

- keps/sig-node/3619-supplemental-groups-policy/README.md
- keps/sig-node/3619-supplemental-groups-policy/kep.yaml
- One-line PR description: updated Release Signoff Checklist, Test Plans, and Implementation History to reflect the current (alpha release) status
- Issue link: #3619 
- Other comments: I will work on beta requirements in PRR sections to plan its beta graduation as the next step.
> KEP-3619: updated KEP with alpha release status, and added haircommander as a reviewer

- keps/sig-node/4033-group-driver-detection-over-cri/kep.yaml
addresses https://github.com/kubernetes/enhancements/issues/4033#issuecomment-2232065260
- Issue link: https://github.com/kubernetes/enhancements/issues/4033
> KEP-4033: update metadata to reflect beta status

- keps/sig-node/4438-container-restart-termination/README.md
- keps/sig-node/4438-container-restart-termination/kep.yaml
- One-line PR description: preparing KEP for 1.32 release cycle
- Issue link: https://github.com/kubernetes/enhancements/issues/4438
- Other comments: for 1.32 we'll mostly work on sidecars, however pod termination will be more broadly modified on next cycles
> KEP-4438:  update milestones

- keps/sig-node/4205-psi-metric/kep.yaml
- Issue link: https://github.com/kubernetes/enhancements/issues/4205 
> 4205: retarget to 1.32

- keps/sig-network/4427-relaxed-dns-search-validation/README.md
Also fill in the Implementation History section
- Issue link: https://github.com/kubernetes/enhancements/issues/4427
> KEP-4427: Update status of KEP

- keps/sig-api-machinery/2335-vanilla-crd-openapi-subset-structural-schemas/README.md
- keps/sig-architecture/1659-standard-topology-labels/README.md
- One-line PR description: Correct typo from 'Kuberntes' to 'Kubernetes'
- Issue link: None
> KEP 1659/2335: Correct typo from 'Kuberntes' to 'Kubernetes'

- keps/sig-storage/3762-persistent-volume-last-phase-transition-time/kep.yaml
- One-line PR description: Update status of `PersistentVolumeLastPhaseTransitionTime` feature to `implemented` so the tracker issue can be closed.
- Issue link: https://github.com/kubernetes/enhancements/issues/3762
> flag PersistentVolumeLastPhaseTransitionTime feature as implemented

- keps/sig-node/4438-container-restart-termination/README.md
- One-line PR description: updating KEP with missing info
- Issue link: https://github.com/kubernetes/enhancements/issues/4438
> KEP-4438: add missing sections

- keps/sig-network/784-kube-proxy-component-config/README.md
- keps/sig-network/784-kube-proxy-component-config/kep.yaml
- One-line PR description: milestones and design update
- Issue link:  https://github.com/kubernetes/enhancements/issues/784
> Kube proxy config v1alpha2 milestone and design

- keps/prod-readiness/sig-auth/4601.yaml
- keps/sig-auth/4601-authorize-with-selectors/README.md
- keps/sig-auth/4601-authorize-with-selectors/kep.yaml
- One-line PR description: KEP-4601: Beta updates for 1.32
- Issue link: https://github.com/kubernetes/enhancements/issues/4601
for sig-auth review
for PRR review
> KEP-4601: Beta updates for 1.32

- keps/prod-readiness/sig-auth/4193.yaml
- keps/sig-auth/4193-bound-service-account-token-improvements/README.md
- keps/sig-auth/4193-bound-service-account-token-improvements/kep.yaml
- One-line PR description: Adding stable updates for 1.32 for KEP-4193
/assign @deads2k @munnerz
> KEP-4193: stable updates for 1.32

- keps/sig-apps/3973-consider-terminating-pods-deployment/kep.yaml
- One-line PR description: Update PodReplacementPolicy alpha to 1.32
> KEP-3973: Update PodReplacementPolicy alpha to 1.32

- keps/sig-node/4381-dra-structured-parameters/README.md
> chore: fix indentation in README.md

- keps/sig-auth/4601-authorize-with-selectors/README.md
- One-line PR description: Follow-up to https://github.com/kubernetes/enhancements/pull/4894#pullrequestreview-2347427674 with test links and clarifications
- Issue link: https://github.com/kubernetes/enhancements/pull/4894
> KEP-4601: PRR test updates

- keps/sig-api-machinery/4222-cbor-serializer/kep.yaml
- One-line PR description: Updates alpha target and latest-milestone for 1.32.
- Issue link: https://github.com/kubernetes/enhancements/issues/4222
> KEP-4222: Update alpha target to 1.32.

- keps/prod-readiness/sig-storage/4049.yaml
- keps/sig-storage/4049-storage-capacity-scoring-of-nodes-for-dynamic-provisioning/README.md
- keps/sig-storage/4049-storage-capacity-scoring-of-nodes-for-dynamic-provisioning/kep.yaml
- Storage Capacity Scoring of Nodes for Dynamic Provisioning
- Issue link:
- ML(sig-storage): https://groups.google.com/g/kubernetes-sig-storage/c/RQHvFvG6pPY/m/wFoLU61bAwAJ
- Slack(#sig-storage): https://kubernetes.slack.com/archives/C09QZFCE5/p1685002022790859
> KEP-4049: Add storage capacity scoring KEP

- keps/sig-node/4381-dra-structured-parameters/README.md
- One-line PR description: DRA: document unit test coverage
> KEP-4381: DRA: document unit test coverage

- keps/sig-node/3983-drop-in-configuration/README.md
- keps/sig-node/3983-drop-in-configuration/kep.yaml
- One-line PR description: Update Beta requirements before moving to GA
- Other comments: Addressing this comment-> https://github.com/kubernetes/enhancements/issues/3983#issuecomment-2339221634
> kep-3983: update Beta requirements before moving to GA

- keps/sig-auth/3926-handling-undecryptable-resources/kep.yaml
- One-line PR description: bump the latest milestone to 1.32
- Issue link: #3926 
/assign tkashem dgrisonnet
> KEP-3926: bump latest milestone

- keps/prod-readiness/sig-node/1769.yaml
- keps/sig-node/1769-memory-manager/README.md
- keps/sig-node/1769-memory-manager/kep.yaml
- One-line PR description: Graduate Kubelet MemoryManager to GA
- Issue link: https://github.com/kubernetes/enhancements/issues/1769#issuecomment-1740902717
The following PR's commits organized as follow:
1. First commit Port the KEP format into latest template 
2. Second and third commits completing other needed documentation such as PRR reviewer.
3. The fourth commit and forward, adds the actual content needed for the feature GA graduation.
> KEP-1769: Graduate Memory Manager to GA

- keps/sig-node/1967-size-memory-backed-volumes/kep.yaml
- One-line PR description: update to stable
- Issue link:
- Other comments: I missed this in the stable update but the main PR merged.
> Update SizeMemoryBackedVolumes to stable.

- keps/prod-readiness/sig-apps/4017.yaml
- keps/sig-apps/4017-pod-index-label/README.md
- keps/sig-apps/4017-pod-index-label/kep.yaml
- One-line PR description: promote KEP-4017 to GA
- Issue link: https://github.com/kubernetes/enhancements/issues/4017
> KEP-4017: promote Pod Index Label for StatefulSets and Indexed Jobs to GA

- keps/sig-api-machinery/3962-mutating-admission-policies/README.md
- keps/sig-api-machinery/3962-mutating-admission-policies/kep.yaml
Addresses https://github.com/kubernetes/enhancements/issues/3962#issuecomment-2380657264
> KEP-3962: Mutating Admission Policies - update for 1.32

- keps/sig-storage/3314-csi-changed-block-tracking/kep.yaml
- One-line PR description: Update alpha target and latest milestone for  1.32 release in KEP-3314 
- Issue link: https://github.com/kubernetes/enhancements/issues/3314
> KEP-3314: Update alpha target and latest-milestone for 1.32

- keps/sig-api-machinery/4222-cbor-serializer/README.md
- One-line PR description: Document upgrade/downgrade and version skew strategy.
- Issue link: https://github.com/kubernetes/enhancements/issues/4222
> KEP-4222: Document upgrade/downgrade and version skew strategy.

- keps/sig-windows/4802-windows-node-shutdown/README.md
- One-line PR description: according to https://github.com/kubernetes/enhancements/issues/4802#issuecomment-2405230796
- Issue link: https://github.com/kubernetes/enhancements/issues/4802
> 4802: update release signoff

- keps/prod-readiness/sig-apps/1847.yaml
- keps/sig-apps/1847-autoremove-statefulset-pvcs/README.md
- keps/sig-apps/1847-autoremove-statefulset-pvcs/kep.yaml
Promote KEP to stable
/cc @msau42
> KEP-1847: Promote statefulset autodelete feature to stable

- keps/sig-apps/1847-autoremove-statefulset-pvcs/README.md
Clarify how the upgrade and downgrade test was performed.
> KEP-1847: Clarify upgrade & downgrade test

- OWNERS_ALIASES
I haven't been able to give enhancements the attention it deserves =/
With that, opting to step down. Happy to join a meeting or talk about tooling and workflow stuff - just shouldn't be a blocker for anything in repo^^;;
> Remove mrbobbytables as enhancements subproject owner

- keps/sig-instrumentation/4828-component-flagz/README.md
Was saying it's KEP-4827, typo
> KEP-4828: Update title of KEP-4828

- keps/sig-auth/4193-bound-service-account-token-improvements/README.md
- One-line PR description: update KEP with details around GA and extra info on what's implemented.
> KEP-4193: update KEP for v1.32 release

- keps/sig-api-machinery/2558-publish-version-openapi/kep.yaml
Nobody is working on this idea, and it has drifted from the original goal.
- Issue link: https://github.com/kubernetes/enhancements/issues/2558
> KEP-2558: mark as "withdrawn"

- keps/sig-auth/3221-structured-authorization-configuration/kep.yaml
Update KEP status to implemented
- Issue link: #3221
/sig auth
/assign liggitt
> kep-3221: update status

- keps/sig-multicluster/4322-cluster-inventory/README.md
Add the description of how to access the cluster that a cluster Profile presents.
- Issue link:
> KEP-4322:  Add the description of how to access the cluster that a cluster Profile presents

- keps/sig-auth/4412-projected-service-account-tokens-for-kubelet-image-credential-providers/README.md
Update the resource usage question based on `ServiceAccountNodeAudienceRestriction` implementation in KAS.
/assign enj liggitt
/sig auth
> KEP-4412: update resource usage question for ServiceAccountNodeAudienceRestriction

- keps/sig-auth/740-service-account-external-signing/README.md
Choice of max token lifetime was reconsidered during implementation. Documenting it accordingly. 
- Issue link:
https://github.com/kubernetes/enhancements/issues/740
For ref: https://github.com/kubernetes/kubernetes/pull/128190#discussion_r1821412614
> KEP-740: Update with decision on max token lifetime

- keps/sig-network/2681-pod-host-ip/README.md
- keps/sig-network/2681-pod-host-ip/kep.yaml
- One-line PR description: Mark KEP-2681 as implemented
- Issue link: #2681 
- Other comments: feature-gate was removed and issue was closed.
> Mark KEP-2681 as implemented

- keps/sig-apps/3335-statefulset-slice/kep.yaml
- One-line PR description: KEP-3335: Update status to `implemented`
- Issue link: https://github.com/kubernetes/enhancements/issues/3335
> Update KEP-3335 kep.yaml to status: implemented

- keps/sig-cluster-lifecycle/kubeadm/4656-add-kubelet-instance-configuration/README.md
- keps/sig-cluster-lifecycle/kubeadm/4656-add-kubelet-instance-configuration/kep.yaml
- One-line PR description: Modify the descriptions in the KEP according to the implemented PRs and the problems currently discovered.
- Issue link:
> KEP-4656: Modify KEP based on implemented PR

- keps/sig-node/1967-size-memory-backed-volumes/kep.yaml
- One-line PR description: Move the KEP to implemented.
- Issue link: #1967 
In 1.35, we can remove the feature gates.
> [KEP-1967]: mark as implemented

- keps/sig-node/4381-dra-structured-parameters/README.md
- One-line PR description: Update the GA graduation criteria for DRA structured parameters
- Issue link: #4381 
- Other comments: the driver example was discussed in the in-person meeting in SLC
/assign @pohly @klueska
> Update the GA graduation criteria for DRA structured parameters

- OWNERS_ALIASES
- One-line PR description: Add myself to sig-inst leads
- Issue link: https://github.com/kubernetes/community/issues/8149
> Add self to sig-instrumentation leads

- keps/sig-storage/3751-volume-attributes-class/README.md
Update VolumeAttributesClass Implementation History
- Issue link: https://github.com/kubernetes/enhancements/issues/3751
- Add PD CSI Driver support pointer
> KEP-3751: Update VolumeAttributesClass Implementation History

- keps/sig-apps/1847-autoremove-statefulset-pvcs/README.md
> KEP-1847: Add missing ` in README.md

- keps/sig-auth/4193-bound-service-account-token-improvements/README.md
- keps/sig-auth/4193-bound-service-account-token-improvements/kep.yaml
- One-line PR description: 1.33 updates for ServiceAccountTokenNodeBinding GA
> KEP-4193: 1.33 updates for ServiceAccountTokenNodeBinding GA

- keps/sig-network/784-kube-proxy-component-config/kep.yaml
This PR updates the milestones for the kep.
- Issue link:
https://github.com/kubernetes/enhancements/issues/784
> kep/784: update milestones

- keps/sig-cli/4292-kubectl-debug-custom-profile/README.md
- keps/sig-cli/4292-kubectl-debug-custom-profile/kep.yaml
- One-line PR description: KEP-4292 is marked as implemented as it has already been promoted to stable.
- Issue link: https://github.com/kubernetes/enhancements/issues/4292
> KEP-4292 is marked as implemented

- keps/sig-cli/3104-introduce-kuberc/kep.yaml
- One-line PR description: This PR updates the latest milestone of KEP-3104 to 1.33
> Update latest milestone of KEP-3104 to 1.33

- keps/sig-apps/4026-crojob-scheduled-timestamp-annotation/kep.yaml
- One-line PR description: Update KEP status to implemented
- Issue link: https://github.com/kubernetes/enhancements/issues/4026
/assign @atiratree
> KEP 4026: update status to implemented

- keps/sig-network/784-kube-proxy-component-config/README.md
- One-line PR description: Updated design details
- Issue link: https://github.com/kubernetes/enhancements/issues/784
> KEP-784 Design update

- README.md
- One-line PR description: Adding link to the v1.33 enhancements tracking board to the readme file.
- Issue link: None
- Other comments: Part of the 1.33 release enhancements team work.
cc @npolshakova @neoaggelos @kikisdeliveryservice
> Add 1.33 tracking board to readme 

- keps/sig-apps/4017-pod-index-label/kep.yaml
- One-line PR description: KEP-4017: Pod Index Label: mark as implemented
- Issue link: https://github.com/kubernetes/enhancements/issues/4017
> KEP-4017: Pod Index Label: mark as implemented

- keps/sig-architecture/4330-compatibility-versions/kep.yaml
- One-line PR description: Update compatibility version kep.yaml with components
/assign @jpbetz 
/cc @richabanker
> [KEP-4330] Update compatibility version kep.yaml with components

- keps/sig-node/2862-fine-grained-kubelet-authz/README.md
- One-line PR description: Update BETA and GA graduation criteria for KEP-2862 Fine-grained Kubelet API Authz.
- Issue link: #2862 
> KEP-2862: Update BETA and GA graduation criteria.

- keps/sig-storage/1495-volume-populators/README.md
- One-line PR description: Please see https://github.com/kubernetes/enhancements/issues/1495#issuecomment-2620382037
- Issue link: https://github.com/kubernetes/enhancements/tree/master/keps/sig-storage/1495-volume-populators
> Update Latest Template for KEP-1495

- keps/sig-node/4381-dra-structured-parameters/README.md
Update DRAAdminAccess featuregate status in API to reflect the latest https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/api/resource/v1beta1/types.go
- Issue link:
> Update DRAAdminAccess featuregate status in API

- keps/sig-scheduling/3243-respect-pod-topology-spread-after-rolling-upgrades/kep.yaml
- One-line PR description: updating KEP milestone
- Issue link: https://github.com/kubernetes/enhancements/issues/3243
> KEP-3243: Update milestone

- keps/sig-windows/3503-host-network-support-for-windows-pods/README.md
- keps/sig-windows/3503-host-network-support-for-windows-pods/kep.yaml
- One-line PR description: Withdraws #3503 
- Issue link: https://github.com/kubernetes/enhancements/issues/3503
/sig windows network node
/assign @jsturtevant @aojea @saschagrunert 
/milestone v1.33
> 3503: Withdraw Windows hostnetwork support

- keps/sig-node/4438-container-restart-termination/README.md
- keps/sig-node/4438-container-restart-termination/kep.yaml
- One-line PR description: updating KEP milestones
- Issue link: #4438 
> KEP-4438: update milestones

- keps/sig-node/1769-memory-manager/kep.yaml
Fixes: https://github.com/kubernetes/enhancements/issues/1769
> Memory Manager is GA now

- keps/sig-node/3545-improved-multi-numa-alignment/kep.yaml
- One-line PR description: KEP-3545 Improved multi-numa alignment in Topology Manager mark as implemented
- Issue link: https://github.com/kubernetes/enhancements/issues/3545
> KEP-3545: mark as implemented

- keps/sig-node/1769-memory-manager/kep.yaml
- One-line PR description: KEP-1769 MemoryManager GA mark as implemented
- Issue link: https://github.com/kubernetes/enhancements/issues/1769
> KEP-1769:memorymanager: mark stable as implemented

- keps/sig-auth/3331-structured-authentication-configuration/README.md
- One-line PR description: Adds current known integrations to GA section for Structured Authentication.
- Issue link: https://github.com/kubernetes/enhancements/blob/master/keps/sig-auth/3331-structured-authentication-configuration/README.md
> kep-3331: adding GA graduation criteria (integrations)

- keps/sig-auth/740-service-account-external-signing/kep.yaml
- One-line PR description: KEP-740: update KEP latest milestone to v1.33
- Issue link: #740
> KEP-740: update KEP latest milestone to v1.33

- keps/sig-node/2535-ensure-secret-pulled-images/README.md
- One-line PR description: document an additional cache write condition in the Ensure Secret Pulled Images enhancement
- Issue link: #2535 
- Other comments: discovered during implementation
/cc liggitt enj
> KEP-2535: document writes during MustAttemptImagePull()

- keps/sig-storage/3314-csi-changed-block-tracking/kep.yaml
- One-line PR description: Update alpha target and latest milestone for 1.33 release in KEP-3314
- Issue link: https://github.com/kubernetes/enhancements/issues/3314
> KEP-3314: Update alpha target and latest-milestone for 1.33

- keps/prod-readiness/sig-api-machinery/4008.yaml
- keps/sig-api-machinery/4008-crd-ratcheting/README.md
- keps/sig-api-machinery/4008-crd-ratcheting/kep.yaml
KEP-4008: Promote CRD Ratcheting to GA
- Issue link: #4008 
> KEP-4008: Promote CRD Ratcheting to GA

- keps/sig-node/4205-psi-metric/kep.yaml
- One-line PR description: Moving milestone to 1.33
- Issue link: #4205 
> KEP-4205: Update PSI KEP for 1.33

- keps/prod-readiness/sig-scheduling/4832.yaml
- keps/sig-scheduling/4832-async-preemption/README.md
- keps/sig-scheduling/4832-async-preemption/kep.yaml
- One-line PR description: promote kep-4832 to beta
- Issue link: https://github.com/kubernetes/enhancements/issues/4832
> kep-4832: promote to beta

- keps/sig-cli/3659-kubectl-apply-prune/README.md
Update KEP for clarity and based on learnings in alpha.
We would like to move to beta, but likely need to implement some of the
described subcommands (e.g. diff, listing) before doing so.
> KEP-3659: ApplySet.  Update KEP to reflect the current state of the feature.

- keps/prod-readiness/sig-network/4004.yaml
- keps/sig-network/4004-deprecate-kube-proxy-version/README.md
- keps/sig-network/4004-deprecate-kube-proxy-version/kep.yaml
- One-line PR description: According to https://github.com/kubernetes/enhancements/pull/4898 promote the feature to the disabled stage
- Issue link:
> KEP4004: Promote the feature to the disabled stage

- keps/sig-instrumentation/647-apiserver-tracing/README.md
- One-line PR description: update to latest template
> KEP-647: update apiserver tracing to the latest template

- keps/sig-scheduling/4832-async-preemption/kep.yaml
- One-line PR description: updated some fields that I forgot updating at https://github.com/kubernetes/enhancements/pull/5127
- Issue link: https://github.com/kubernetes/enhancements/issues/4832
> Update kep.yaml for KEP-4832

- keps/sig-node/4381-dra-structured-parameters/README.md
- keps/sig-node/4381-dra-structured-parameters/kep.yaml
- One-line PR description: Update GA graduation criteria related to plugin reliability efforts
> KEP-4381: Update GA graduation criteria

- keps/sig-cli/2590-kubectl-subresource/kep.yaml
- One-line PR description: update `kep.yaml` for kubectl subresource KEP
- Issue link: https://github.com/kubernetes/enhancements/issues/2590
/assign @ardaguclu
> KEP 2590: metadata update

- keps/sig-cluster-lifecycle/kubeadm/4471-cp-join-kubelet-local-apiserver/README.md
- keps/sig-cluster-lifecycle/kubeadm/4471-cp-join-kubelet-local-apiserver/kep.yaml
- One-line PR description: Document graduation to beta
- Issue link: https://github.com/kubernetes/enhancements/issues/4471
> KEP-4471: document graduation to beta

- keps/sig-node/3619-supplemental-groups-policy/kep.yaml
- One-line PR description: just updated 'latest-milestone' to "v1.33" in kep.yaml
- Other comments: This is just a housekeeping PR. See: https://github.com/kubernetes/enhancements/issues/3619#issuecomment-2652354332
> KEP-3619: update latest-milestone to v1.33

- keps/prod-readiness/sig-node/3857.yaml
- keps/sig-node/3857-rro-mounts/README.md
- keps/sig-node/3857-rro-mounts/kep.yaml
- One-line PR description: KEP-3857: Recursive Read-only (RRO) mounts: promote to GA
- Issue link:
- #3857
- Other comments: NONE
> KEP-3857: Recursive Read-only (RRO) mounts: promote to GA

- keps/sig-storage/2589-csi-migration-portworx/README.md
- One-line PR description: Update KEP for Portworx CSI Migration
- Issue link: https://github.com/kubernetes/enhancements/issues/2589
- Other comments: This PR updates the KEP readme as per the [latest template](https://github.com/kubernetes/enhancements/blob/master/keps/NNNN-kep-template/README.md?plain=1).
/sig storage
> KEP-2589: Update KEP README

- keps/prod-readiness/sig-apps/3939.yaml
- keps/sig-apps/3939-allow-replacement-when-fully-terminated/README.md
- keps/sig-apps/3939-allow-replacement-when-fully-terminated/kep.yaml
- One-line PR description: Promote Job Pod Replacement Policy to GA
- Issue link: https://github.com/kubernetes/enhancements/issues/3939
- Other comments: NONE
> KEP-3939: Job Pod Replacement Policy; promote to GA

- keps/sig-instrumentation/2831-kubelet-tracing/README.md
- One-line PR description: update kubelet tracing KEP to use the latest template
> KEP-2831: update kubelet tracing to the latest template

- keps/sig-apps/2185-random-pod-select-on-replicaset-downscale/kep.yaml
- One-line PR description: Mark KEP implemented
- Issue link: #2185 
- Other comments: Found this while working on https://github.com/kubernetes/community/pull/8334
> KEP 2185: make KEP implemented

- keps/sig-api-machinery/4988-snapshottable-api-server-cache/README.md
> Fix template and fill checklist KEP-4988

- keps/sig-node/2400-node-swap/README.md
- One-line PR description: update KEP-2400 to latest template
> KEP-2400: update release checklist to latest template

- keps/sig-storage/2644-honor-pv-reclaim-policy/README.md
- One-line PR description: update e2e link and checklist
- Issue link: https://github.com/kubernetes/enhancements/issues/2644
> [KEP-2644] update e2e link and checklist

- keps/sig-apps/3850-backoff-limits-per-index-for-indexed-jobs/README.md
- keps/sig-apps/3850-backoff-limits-per-index-for-indexed-jobs/kep.yaml
- One-line PR description: Update KEP with status as implemented
> KEP3850: Update KEP for graduating JobBackoffLimitPerIndex to GA

- keps/sig-api-machinery/4020-unknown-version-interoperability-proxy/README.md
- One-line PR description: Update the flow diagram for Mixed Version Proxy feature
- Issue link: https://github.com/kubernetes/enhancements/issues/4020
> [KEP:4020] Update flow diagram for Mixed Version Proxy

- keps/sig-cli/2590-kubectl-subresource/kep.yaml
- One-line PR description: Mark KEP 2590 as implemented
- Issue link: https://github.com/kubernetes/enhancements/issues/2590
/assign @ardaguclu
> KEP-2590: mark as implemented

- keps/sig-api-machinery/5073-declarative-validation-with-validation-gen/README.md
- keps/sig-api-machinery/5073-declarative-validation-with-validation-gen/kep.yaml
This PR updates KEP-5073 to have the updated feature gates and logic from previous conversations with our KEP reviewers.  These changes around the feature gate names -  DeclarativeValidation & DeclarativeValidationTakeover and gating logic for the feature. 
- Issue link: https://github.com/kubernetes/enhancements/issues/5073
> KEP-5073: update feature gates for finalized DeclarativeValidationTakeover usage and associated implementation logic

- keps/sig-storage/3751-volume-attributes-class/README.md
- One-line PR description: Correct ResourceQuota usage in KEP documents
- Issue link:
/assign @gnufied
> KEP-3751 Correct ResourceQuota Usage

- OWNERS_ALIASES
https://github.com/kubernetes/community/issues/8390
> SIG Auth: Leadership Change

- keps/sig-network/1860-kube-proxy-IP-node-binding/README.md
- keps/sig-network/1860-kube-proxy-IP-node-binding/kep.yaml
responding to https://github.com/kubernetes/enhancements/issues/1860#issuecomment-2585946733
> KEP-1860: mark as implemented

- keps/NNNN-kep-template/README.md
- One-line PR description: Update broken git link to existing integration tests
> KEP template:  update link to integration tests

- keps/sig-auth/5018-dra-adminaccess/README.md
> 5018-update namespace label

- OWNERS_ALIASES
https://github.com/kubernetes/community/issues/8428
> SIG Scheduling: Leadership Change

- OWNERS_ALIASES
- One-line PR description: Update SIG Autoscaling Leads
- Issue link: https://github.com/kubernetes/community/issues/8368
> SIG Autoscaling - Update leads alias

- keps/prod-readiness/sig-scheduling/4247.yaml
- keps/sig-scheduling/4247-queueinghint/kep.yaml
- One-line PR description: graduate QHint to stable
- Issue link: https://github.com/kubernetes/enhancements/issues/4247
> feat: graduate QHint to stable

- keps/sig-auth/4412-projected-service-account-tokens-for-kubelet-image-credential-providers/README.md
- Update KEP to reflect alpha implementation.
/sig auth
/assign liggitt enj
> KEP-4412: update kep with alpha implementation

- keps/sig-scheduling/3633-matchlabelkeys-to-podaffinity/kep.yaml
- One-line PR description:  move KEP-3633 status to implemented
- Issue link: https://github.com/kubernetes/enhancements/issues/3633#issuecomment-2887659700
> fix: move KEP-3633 status to implemented

- keps/prod-readiness/sig-auth/3331.yaml
- keps/sig-auth/3331-structured-authentication-configuration/README.md
- keps/sig-auth/3331-structured-authentication-configuration/kep.yaml
- Update [KEP](https://github.com/kubernetes/enhancements/tree/master/keps/sig-auth/3331-structured-authentication-configuration) for GA
/sig auth
/assign enj liggitt
> KEP-3331: update kep for GA in v1.34

- keps/sig-auth/4193-bound-service-account-token-improvements/kep.yaml
- One-line PR description: Mark KEP-4193 as implemented
- Issue link: #4193
Closes #4193
/sig auth
/cc @enj
> KEP-4193: Mark as implemented

- keps/sig-storage/2644-honor-pv-reclaim-policy/kep.yaml
- One-line PR description: KEP-2644: Mark Always Honor PersistentVolume Reclaim Policy as implemented
- Issue link: https://github.com/kubernetes/enhancements/issues/2644
- Other comments: All tasks are done.
> KEP-2644: Mark Always Honor PersistentVolume Reclaim Policy as implemented

- keps/sig-scheduling/3094-pod-topology-spread-considering-taints/kep.yaml
- One-line PR description: Update the status to implemented
- Issue link: https://github.com/kubernetes/enhancements/issues/3094
fix: https://github.com/kubernetes/enhancements/issues/3094
> KEP-3094: Update the status to implemented

- keps/sig-cli/1441-kubectl-debug/kep.yaml
- One-line PR description: Mark KEP 1441 as implemented
/assign @ardaguclu
> KEP-1441: mark as implemented

- README.md
- One-line PR description: Add link to 1.34 enhancements tracking board in readme
- Other comments: For 1.34 release team
cc @Vyom-Yadav @katcosgrove
> Add link to 1.34 enhancements tracking board in readme

- keps/sig-api-machinery/4355-coordinated-leader-election/README.md
- One-line PR description:  updates the KEP for Coordinated Leader Election (KEP-4355) to include a new proposal section for priority-based leader selection.
- Issue link: https://github.com/kubernetes/enhancements/issues/4355
> Update README.md with content about priority base CLE

- keps/sig-api-machinery/3157-watch-list/README.md
- keps/sig-api-machinery/3157-watch-list/kep.yaml
/assign @jpbetz @deads2k 
/cc @p0lyn0mial
> Update watch-list KEP for next Beta targeted 1.34

- keps/prod-readiness/sig-node/4818.yaml
- keps/sig-node/4818-allow-zero-value-for-sleep-action-of-prestop-hook/README.md
- keps/sig-node/4818-allow-zero-value-for-sleep-action-of-prestop-hook/kep.yaml
- Issue link: https://github.com/kubernetes/enhancements/issues/4818
- Other comments: No changes to PRR
> KEP 4818: Promote PodLifecycleSleepActionAllowZero to GA

- keps/sig-auth/740-service-account-external-signing/kep.yaml
- One-line PR description: KEP-740: update to beta for 1.34
- Issue link: #740
/sig auth
/cc @enj
> KEP-740: update to beta for 1.34

- keps/sig-auth/5018-dra-adminaccess/README.md
- One-line PR description: Update KEP to add a Scalability question
- Issue link:  https://github.com/kubernetes/enhancements/issues/5018
/wg device-management
> kep-5018: Scalability update

- OWNERS_ALIASES
update sig-etcd leads
- Issue link: https://github.com/kubernetes/community/issues/8478
/sig etcd
/cc @wenjiaswe @ahrtr @serathius @jmhbnz
> update sig-etcd leads

- keps/sig-node/4205-psi-metric/README.md
- build on top of https://github.com/kubernetes/enhancements/pull/5409 to fix https://github.com/kubernetes/enhancements/pull/5409/files#r2155728798
- Issue link:
- https://github.com/kubernetes/enhancements/issues/4205
> KEP-4205: add blurb about PSI performance on top of https://github.com/kubernetes/enhancements/pull/5409

- keps/sig-auth/4412-projected-service-account-tokens-for-kubelet-image-credential-providers/README.md
KEP issue: https://github.com/kubernetes/enhancements/issues/4412
/sig auth
/assign enj
> KEP-4412: add adopters

- keps/sig-node/2400-node-swap/README.md
- keps/sig-node/2400-node-swap/kep.yaml
- One-line PR description: Add the follow-up KEPs to README, fix old plans to address evictions in this KEP.
- Issue link: https://github.com/kubernetes/enhancements/issues/2400.
- Other comments: Thoroughly discussed in https://github.com/kubernetes/enhancements/pull/5360#issuecomment-2986418047 and https://docs.google.com/document/d/14OLKSPl3BDzw2BBacdN0kHpDt-JN8AOTSei_XExh-2s/edit?tab=t.0, which was presented at the sig-node meeting multiple times.
> [KEP-2400] GA KEP update

- keps/sig-autoscaling/5325-hpa-pod-selection-accuracy/kep.yaml
As discussed with @soltysh we need to postpone this KEP to 1.35.
cc @adrianmoisey @raywainman @gjtempleton
> Update KEP milestone

- keps/sig-auth/4412-projected-service-account-tokens-for-kubelet-image-credential-providers/README.md
- keps/sig-auth/4412-projected-service-account-tokens-for-kubelet-image-credential-providers/kep.yaml
- Update KEP to reflect beta implementation.
/sig auth
/assign liggitt enj
> KEP-4412: update kep with beta implementation

- keps/prod-readiness/sig-scheduling/5278.yaml
- keps/sig-scheduling/5278-nominated-node-name-for-expectation/README.md
- keps/sig-scheduling/5278-nominated-node-name-for-expectation/kep.yaml
- One-line PR description: Update the KEP-5278 to reflect its demotion to alpha in v1.34.
- Issue link: https://github.com/kubernetes/enhancements/issues/5278
> KEP-5278: Update the KEP to reflect its demotion to alpha

- keps/sig-cli/3515-kubectl-explain-openapiv3/kep.yaml
- One-line PR description: This PR marks KEP-3515 as implemented
- Issue link: https://github.com/kubernetes/enhancements/issues/3515
> Mark 3515 as implemented

- keps/sig-scheduling/3902-decoupled-taint-manager/kep.yaml
- One-line PR description: Mark KEP-3902 as implemented
- Issue link: https://github.com/kubernetes/enhancements/issues/3902
- Other comments: All task are done.
> Mark KEP-3902 as implemented

- keps/sig-node/3960-pod-lifecycle-sleep-action/kep.yaml
- One-line PR description: This pr marks KEP 3960 as implemented since it has graduated to stable.
- Issue link:https://github.com/kubernetes/enhancements/issues/3960
> Mark 3960 implemented

- keps/sig-network/4427-relaxed-dns-search-validation/README.md
- keps/sig-network/4427-relaxed-dns-search-validation/kep.yaml
- One-line PR description: Move KEP-4427 (Relaxed DNS search string validation) to implemented 
- Issue link: https://github.com/kubernetes/enhancements/issues/4427
> KEP-4427: Move to implemented

- keps/sig-api-machinery/5366-graceful-leader-transition/kep.yaml
- One-line PR description: Move kep from 1.34 to 1.35
- Issue link:
> Update graceful leader transition KEP to 1.35

- keps/sig-auth/4601-authorize-with-selectors/kep.yaml
- keps/sig-auth/4633-anonymous-auth-configurable-endpoints/kep.yaml
Mark completed 1.34 sig-auth features as implemented
Closes #4601 #4633
/sig auth
/assign @enj @deads2k
> KEP-4601 / KEP-4633: Mark completed 1.34 sig-auth features as implemented

- keps/sig-node/4569-cgroup-v1-maintenance-mode/README.md
sync the flag name according to https://github.com/kubernetes/kubernetes/pull/126031
> update flag name fail-cgroupv1 for kep 4569

- keps/sig-api-machinery/3157-watch-list/README.md
- keps/sig-api-machinery/3157-watch-list/kep.yaml
- One-line PR description: Update KEP 3157 (watch-list) for milestone 1.35
> Update KEP 3157 (watch-list) for milestone 1.35

- keps/sig-api-machinery/4192-svm-in-tree/kep.yaml
- One-line PR description: Update milestone goals to reflect the work being done on SVM in 1.35
- Other comments: Missed in prior PR that updated beta requirements.
> KEP 4192: Change milestones to reflect new work being done in 1.35

- OWNERS_ALIASES
Related to:
- https://github.com/kubernetes/community/issues/8633
- https://github.com/kubernetes/community/issues/8634
> Rotate SIG K8s Infra leads

- keps/sig-node/4381-dra-structured-parameters/README.md
- keps/sig-node/4381-dra-structured-parameters/kep.yaml
- One-line PR description: DRA: structured parameters update for 1.35
- Issue link:  https://github.com/kubernetes/enhancements/issues/4381
- Other comments: Some more changes are planned for 1.35 related to GA graduation (conformance tests, bumping storage version one release after adding v1).
> KEP-4381: DRA: structured parameters update for 1.35

- keps/sig-apps/3939-allow-replacement-when-fully-terminated/kep.yaml
- One-line PR description: Update `status` to `implemented`
- Issue link: https://github.com/kubernetes/enhancements/issues/3939
> KEP-3939: Update Job Pod Replacemenet Policy KEP status to implemented
