keps/prod-readiness/sig-storage/1487.yaml
keps/sig-storage/1487-csi-migration-aws/README.md
keps/sig-storage/1487-csi-migration-aws/kep.yaml

This PR adds csi migration kep for aws-ebs
- Issue link: https://github.com/kubernetes/enhancements/issues/1487

KEP-1487: Add csi migration kep for AWS EBS

---

keps/prod-readiness/sig-auth/2799.yaml
keps/sig-auth/2799-reduction-of-secret-based-service-account-token/README.md
keps/sig-auth/2799-reduction-of-secret-based-service-account-token/kep.yaml

- One-line PR description: Gradually deprecate Token Controller.
/assign @liggitt 
/assign @mikedanese 
/sig auth
@kubernetes/sig-auth-pr-reviews

KEP-2799: Reduction of Secret-based Service Account Tokens

---

keps/sig-api-machinery/3037-client-go-alternative-services/README.md
keps/sig-api-machinery/3037-client-go-alternative-services/kep.yaml

- One-line PR description: client-go capability to connect to multiple apiservers
- Issue link: https://github.com/kubernetes/enhancements/issues/3037
- Other comments: Implementation https://github.com/kubernetes/kubernetes/pull/106115

KEP-3037: client-go alternative services

---

keps/sig-api-machinery/3156-http3/README.md
keps/sig-api-machinery/3156-http3/kep.yaml

- One-line PR description: support http3 in the apiserver
- Issue link: https://github.com/kubernetes/enhancements/issues/3156
- Other comments: Prototype with working implementation https://github.com/kubernetes/kubernetes/pull/106707

KEP-3156: Introduce http3 support in the apiserver

---

keps/prod-readiness/sig-storage/2924.yaml
keps/sig-storage/2924-csi-migration-cephfs/README.md
keps/sig-storage/2924-csi-migration-cephfs/kep.yaml

- One-line PR description: Enable intree cephfs plugin migration with the help of migration translation lib
- Issue Link: https://github.com/kubernetes/enhancements/issues/2924

KEP-2924: Enable CSI migration for cephfs intree plugin

---

keps/prod-readiness/sig-auth/2784.yaml
keps/sig-auth/2784-csr-duration/README.md
keps/sig-auth/2784-csr-duration/kep.yaml

- One-line PR description: Update CSR Duration KEP with GA milestone details
- Issue link: #2784
/assign @liggitt @deads2k

KEP-2784: Update CSR Duration KEP with GA details

---

keps/sig-storage/1495-volume-populators/README.md
keps/sig-storage/1495-volume-populators/kep.yaml

- One-line PR description: update version for move to beta
- Issue link: https://github.com/kubernetes/enhancements/issues/1495
- Other comments: n/a

KEP-1495: bump beta version from 1.23 to 1.24

---

keps/prod-readiness/sig-storage/2589.yaml
keps/sig-storage/2589-csi-migration-portworx/README.md
keps/sig-storage/2589-csi-migration-portworx/kep.yaml

This commit adds the details to the KEP for promoting Portworx CSI migration from alpha to beta in v1.24
One-line PR description: Update KEP for Portworx CSI Migration
Issue link: Portworx file in-tree to CSI driver migration  #[2589](https://github.com/kubernetes/enhancements/issues/2589)
Other comments: 
/sig storage
/cc @msau42

Promote Portworx CSI migration to Beta in v1.24

---

keps/prod-readiness/sig-storage/3107.yaml
keps/sig-storage/3107-csi-nodeexpandsecret/README.md
keps/sig-storage/3107-csi-nodeexpandsecret/kep.yaml

- One-line PR description: Introduce nodeExpandSecret in CSI PV source and make it part of NodeExpandVolume.-
- Issue Link: https://github.com/kubernetes/enhancements/issues/3107
- Other comments:  Prototype with working implementation
https://github.com/kubernetes/kubernetes/pull/105963

KEP-3107: SecretRef field addition to NodeExpandVolume request

---

keps/prod-readiness/sig-storage/1790.yaml
keps/sig-storage/1790-recover-resize-failure/README.md
keps/sig-storage/1790-recover-resize-failure/kep.yaml

Add sections for PRR
xref https://github.com/kubernetes/enhancements/issues/1790

KEP 1790: Update recover resize failure KEP for going beta.

---

keps/prod-readiness/sig-network/1435.yaml
keps/sig-network/1435-mixed-protocol-lb/README.md
keps/sig-network/1435-mixed-protocol-lb/kep.yaml

Adding Production Readiness Review for Mixed Protocols in Services with type=LoadBalancer
- Issue link: https://github.com/kubernetes/enhancements/issues/1435
Have discussed with SIG-network and SIG-cloudprovider; see https://github.com/kubernetes/enhancements/issues/1435#issuecomment-969523031 for details.

KEP-1435: adding PRR for MixedProtocolLBService feature to move to beta

---

keps/prod-readiness/sig-storage/3141.yaml
keps/sig-storage/3141-prevent-volume-mode-conversion/README.md
keps/sig-storage/3141-prevent-volume-mode-conversion/kep.yaml

- One-line PR description: Prevent unauthorised volume mode conversion when restoring volumes.
- Issue link: https://github.com/kubernetes/enhancements/issues/3141

KEP-3141: Prevent unauthorised volume mode conversion

---

keps/prod-readiness/sig-storage/284.yaml
keps/sig-storage/284-enable-volume-expansion/README.md
keps/sig-storage/284-enable-volume-expansion/kep.yaml

This adds PRR for [xref#284.](https://github.com/kubernetes/enhancements/issues/284).  Volume expansion feature has been in beta since v1.11 and has sister feature gates which cover other aspects of expansion namely:
1. ExpandPersistentVolumes - general and parent expansion feature.
2. ExpandInUsePersistentVolumes - online volume expansion. This is the default expansion mode. 
3. ExpandCSIVolumes - Enable expansion of CSI volumes. Also in beta.
Currently I am using - this single KEP to migrate and move all the above feature-gates to GA (rather than doing them individually). At this point in v1.23 they are all very related and same. It made sense to add new feature gates when we were adding features incrementally but after 8 or 9 releases, I am not sure it makes sense.

KEP 284: Add PRR for volume expansion feature

---

keps/sig-apps/1591-daemonset-surge/README.md

The implementation defines the default value for MaxSurge being 0, as to
preserve the current behavior of rolling updates in DaemonSets. Also,
for MaxUnavailable, the rounding is up.
This change is just a copy-paste of the docblock defined in the types.go
file.
See:
- https://github.com/kubernetes/kubernetes/blob/10a3cc815bea73f78f7126cab5df95233da96e1b/pkg/apis/apps/types.go
- https://github.com/kubernetes/kubernetes/blob/10a3cc815bea73f78f7126cab5df95233da96e1b/pkg/apis/apps/v1/defaults.go#L87-L91

KEP-1591: Fix default values for MaxUnavailable and MaxSurge

---

keps/prod-readiness/sig-apps/3140.yaml
keps/sig-apps/3140-TimeZone-support-in-CronJob/README.md
keps/sig-apps/3140-TimeZone-support-in-CronJob/kep.yaml

- One-line PR description: TimeZone support in CronJob
- Issue link: https://github.com/kubernetes/enhancements/issues/3140
/assign @ravisantoshgudimetla @janetkuo 
/cc @iterion
/sig apps

KEP 3140: TimeZone support in CronJob

---

keps/prod-readiness/sig-node/688.yaml
keps/sig-node/688-pod-overhead/README.md
keps/sig-node/688-pod-overhead/kep.yaml

PodOverhead is in beta for a long time. Feedback collected: https://docs.google.com/document/d/1uZNJvR3IPDL--z6H5prgDuOAi22lhUYRXejnbaZHmSk/edit# The feature meets graduation requirement
KEP: https://github.com/kubernetes/enhancements/issues/688
/sig node
/assign @egernst 
/cc @tallclair 
/cc @ehashman 
@ehashman for PRR review. This is mostly back-filling. So should be straightforward. Lmk if I need to find somebody else

PodOverhead to GA

---

keps/prod-readiness/sig-node/2371.yaml
keps/sig-node/2371-cri-pod-container-stats/README.md
keps/sig-node/2371-cri-pod-container-stats/kep.yaml

addressing comments in https://github.com/kubernetes/enhancements/pull/2364#discussion_r716697783
- Issue link:

KEP-2371: clarify plan for cAdvisor and target at Beta for 1.24

---

keps/prod-readiness/sig-node/2008.yaml
keps/sig-node/2008-forensic-container-checkpointing/README.md
keps/sig-node/2008-forensic-container-checkpointing/kep.yaml

This KEP is about Forensic Container Checkpointing
Ref: #2008

Add Forensic Container Checkpointing KEP

---

keps/prod-readiness/sig-instrumentation/3077.yaml
keps/sig-instrumentation/3077-contextual-logging/README.md
keps/sig-instrumentation/3077-contextual-logging/kep.yaml

- One-line PR description: KEP-3077: initial draft of contextual logging KEP
- Issue link: https://github.com/kubernetes/enhancements/issues/3077

KEP-3077: contextual logging

---

keps/prod-readiness/sig-storage/596.yaml
keps/sig-storage/596-csi-inline-volumes/README.md
keps/sig-storage/596-csi-inline-volumes/kep.yaml

KEP-596: promote CSIInlineVolume to GA
- Issue link: https://github.com/kubernetes/enhancements/issues/596
KEP Preview: https://github.com/dobsonj/enhancements/tree/kep-596-ga/keps/sig-storage/596-csi-inline-volumes
/cc @jsafrane

KEP-596: promote CSIInlineVolume to GA

---

keps/prod-readiness/sig-network/2943.yaml
keps/sig-network/2943-networkpolicy-status/README.md
keps/sig-network/2943-networkpolicy-status/kep.yaml

- One-line PR description: Add initial draft on Network Policy Status for discussion
- Issue link: #2943 
This is a follow up on the requirements of Network Policy Status in #2079 review
/sig network
/assign @thockin @caseydavenport

KEP-2943: Add initial draft on Network Policy Status

---

keps/prod-readiness/sig-storage/2268.yaml
keps/sig-storage/2268-non-graceful-shutdown/README.md
keps/sig-storage/2268-non-graceful-shutdown/kep.yaml

Signed-off-by: Yassine TIJANI <ytijani@vmware.com>
Opening a PR for a first round of reviews, documented other alternatives and how to handle version skew.
/assign @smarterclayton @liggitt @yujuhong @saad-ali 
/cc @jingxu97 @derekwaynecarr @andrewsykim 
/sig node
/sig storage
/sig scalability

add non-graceful node shutdown KEP

---

keps/prod-readiness/sig-node/2221.yaml
keps/sig-node/2221-remove-dockershim/README.md
keps/sig-node/2221-remove-dockershim/kep.yaml

This patch updates the dockershim removal KEP to be track-able by SIG Release in the usual enhancements process.
cc @kubernetes/sig-release @kubernetes/sig-node-feature-requests @kubernetes/sig-release-leads 
Refers to https://github.com/kubernetes/enhancements/issues/2221

KEP-2221: Update dockershim removal KEP to reflect latest changes

---

keps/prod-readiness/sig-api-machinery/2896.yaml
keps/sig-api-machinery/2896-openapi-v3/README.md
keps/sig-api-machinery/2896-openapi-v3/kep.yaml

- One-line PR description: OpenAPI V3 to beta
- Issue link: https://github.com/kubernetes/enhancements/issues/2896
- Other comments: Seeking discussion around OpenAPI V3 to beta path

KEP-2896: OpenAPI v3 to Beta

---

keps/prod-readiness/sig-instrumentation/2831.yaml
keps/sig-instrumentation/2831-kubelet-tracing/README.md
keps/sig-instrumentation/2831-kubelet-tracing/kep.yaml

- One-line PR description: Instrument kubelet to generate and export OpenTelemetry trace data.

KEP-2831: Instrumenting Kubelet for OpenTelemetry Tracing

---

keps/prod-readiness/sig-api-machinery/2887.yaml
keps/sig-api-machinery/2887-openapi-enum-types/README.md

This PR revises KEP-2887 for its beta graduation.
- Issue link:

KEP-2887: OpenAPI Enum Types to Beta

---

keps/sig-api-machinery/2876-crd-validation-expression-language/README.md
keps/sig-api-machinery/2876-crd-validation-expression-language/kep.yaml

- One-line PR description: Propose what core library of functions we will make available to CEL for Beta
Proposed additions are:
- `isSorted` for lists with comparable elements. This is useful for ensuring that a list is kept in-order.
- `sum`, `min` and `max` functions for lists of summable/comparable elements. This is the
core set of aggregate functions for lists, with CEL they can also be used on scalars by using defining list literals
inline , e.g. `[self.val1, self.val2].max()`
- `indexOf` / `lastIndexOf` for lists (overloading the existing string functions), this can be useful for
- validating partial order (i.e. the tasks of a workflow)
Also:
- Explain mechanism to make post-alpha library updates (which will need to be done with great care given that they will make CRDs …

KEP-2876: Core library proposal for CEL

---

keps/prod-readiness/sig-apps/2804.yaml
keps/sig-apps/2804-consolidate-workload-controllers-status/README.md
keps/sig-apps/2804-consolidate-workload-controllers-status/kep.yaml

Consolidate workload controllers status
- Issue link: #2804 

Consolidate workload controllers status

---

keps/sig-apps/2804-consolidate-workload-controllers-status/README.md

- One-line PR description: do not remove the conditions on feature gate off to stay consistent
- Issue link: followup to https://github.com/kubernetes/enhancements/pull/2833#discussion_r798981236
cc @ravisantoshgudimetla @ehashman @soltysh

update KEP: consolidate workload controllers status

---

keps/sig-storage/284-enable-volume-expansion/README.md

Add graduation criteria and test plan for https://github.com/kubernetes/enhancements/issues/284

Add graduation critirea

---

keps/sig-network/2091-admin-network-policy/README.md
keps/sig-network/2091-admin-network-policy/kep.yaml

- One-line PR description: Kep incorrectly merged without updating of release signoff Checklist,  resulted in the KEP being incorrectly booted from 1.24. 
- Issue link: https://github.com/kubernetes/enhancements/issues/2091
- Other comments: This was a naive mistake, sorry about that!

KEP-2091: Update Release Signoff Checklist

---

keps/NNNN-kep-template/README.md

- One-line PR description: Add links to SIG Arch documentation on feature gates
- Other comments: See also https://github.com/kubernetes/community/pull/6238

KEP Template: Add documentation to template about feature gates

---

keps/sig-storage/1487-csi-migration-aws/README.md
keps/sig-storage/1487-csi-migration-aws/kep.yaml

- One-line PR description: updating milestone to 1.25
- Issue link: https://github.com/kubernetes/enhancements/issues/1487
- Other comments: after some internal discussions and such, better to target 1.25!

KEP-1487: Target 1.25 for aws csi migration GA

---

hack/verify-toc.sh

Use `go install` instead of `go get`
> installing executables with 'go get' in module mode is deprecated.
```
(*'-') < make verify-toc               
/Users/kenseinakada/workspace/enhancements/hack/verify-toc.sh
go get: installing executables with 'go get' in module mode is deprecated.
Use 'go install pkg@version' instead.
For more information, see https://golang.org/doc/go-get-install-deprecation
or run 'go help get' or 'go help install'.
Checking table of contents are up to date...
Cleaning up...
```
This is the same change as https://github.com/kubernetes/enhancements/pull/2817/commits/da2dac0b6aa5600c99dec19839dd2c8d610c05e1.
/cc @justaugustus
/kind cleanup

hack/verify-toc.sh: Use `go install` instead of `go get`

---

keps/sig-autoscaling/853-configurable-hpa-scale-velocity/README.md

This PR Added the `periodSecond` field under policies section which we have to mention otherwise it gives the below error on applying hpa.yaml:
> error: error validating "hpa.yaml": error validating data: ValidationError(HorizontalPodAutoscaler.spec.behavior.scaleUp.policies[0]): missing required field "periodSeconds" in io.k8s.api.autoscaling.v2beta2.HPAScalingPolicy; if you choose to ignore these errors, turn validation off with --validate=false
And also removed the` %` sign from the value, it is of int32 not string type. it gives the below error:
>  error: error validating "hpa.yaml": error validating data: [ValidationError(HorizontalPodAutoscaler.spec.behavior.scaleUp.policies[0].value): invalid type for io.k8s.api.autoscaling.v2beta2.HPAScalingPolicy.value: got "string", expected …

KEP-853: Improvement: Add periodSeconds field and fixed typo.

---

keps/sig-cli/2906-kustomize-function-catalog/README.md
keps/sig-cli/2906-kustomize-function-catalog/kep.yaml
keps/sig-cli/2985-public-krm-functions-registry/README.md

- One-line PR description: Small update to the schema for function definitions to be compatible with CRD by ensuring that where they have the same fields, they are in the same places. 
- Issue link: #2906 
- Comments: See https://github.com/kubernetes-sigs/kustomize/pull/4467 for an example use case. This really only required one change, i.e. `spec.kind` -> `spec.names.kind`. Here's the [CRD reference](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.23/#customresourcedefinition-v1-apiextensions-k8s-io), for reference. I also updated the type name for clarity (it's the CRD equivalent, not the CR). The rest of the updates are fixing examples that didn't match the schema even as it was before this PR.
/cc @mengqiy @jeremyrickard

KEP-2906: Update Catalog schema for CRD compatibility

---

keps/NNNN-kep-template/README.md

/assign @deads2k @ehashman @johnbelamaric

Update KEP template with comment wrt to enablement/disablement tests in PRR section

---

hack/verify-spelling.sh
hack/verify-toc.sh

This is _not_ a PR for a KEP.
Fixes this warning for hack scripts and updates a stale comment:
```
pjoglekar@pjoglekar-a01 enhancements % hack/verify-spelling.sh 
go get: installing executables with 'go get' in module mode is deprecated.
Use 'go install pkg@version' instead.
For more information, see https://golang.org/doc/go-get-install-deprecation
or run 'go help get' or 'go help install'.
```

Replace go get with go install in verify shell scripts

---

keps/prod-readiness/sig-storage/1472.yaml
keps/sig-storage/1472-storage-capacity-tracking/README.md
keps/sig-storage/1472-storage-capacity-tracking/kep.yaml

- One-line PR description: graduation to GA
- Issue link: https://github.com/kubernetes/enhancements/issues/1472
- Other comments: exception will be needed

KEP-1472: storage capacity tracking: GA

---

keps/sig-api-machinery/2876-crd-validation-expression-language/README.md

The original text describing how SSA collection semantics relate to CEL transition rules was ambiguous for atomic maps. This PR clarifies the text based on the outcome of the discussion [here](https://github.com/kubernetes/kubernetes/pull/108013#discussion_r814254241).

KEP-2876: Clarify which schema nodes permit oldSelf in CEL rules.

---

keps/sig-node/127-user-namespaces/README.md
keps/sig-node/127-user-namespaces/kep.yaml

Here is the high level work we discussed during Nov 2 SIG-node meeting.
Let me know if this KEP effectively reflects what we discussed and IIUC agreed. I'd like to know of any concerns or show-stoppers ASAP rather than last minute, after we already worked a lot of time on this.
If there are no concerns and this plan is agreed by all parties and this is merged, with @giuseppe we will start a PoC implementation to fill-in the rest of the details this KEP needs (CRI changes, etc.).
To the best of my knowledge, this incorporates all the feedback in the PR #2101 that @thockin @mtaufen  and others gave (see basically that almost all is automatic and the room for improvements in phase 3, in particular the per-sa/per-ns strategies are in scope, with some others).
Please let us know what you think …

127: Add KEP for user namespaces support

---

keps/sig-multicluster/2149-clusterid/README.md

- One-line PR description: Requesting API review for proposed apiGroup `about.k8s.io`, containing Kind `ClusterProperty` in [KEP-2149: ClusterID for ClusterSet Identificiation](https://github.com/kubernetes/enhancements/tree/master/keps/sig-multicluster/2149-clusterid)
- Issue link: #2149
1. This KEP proposes an out-of-tree CRD to be hosted at (provisionally named) [kubernetes-sigs/about-api](https://github.com/kubernetes-sigs/about-api). The names selected in this proposal (`about.k8s.io` API group; `ClusterProperty` kind name; `id.k8s.io` and `clusterset.k8s.io` well-known CRs) were voted on by surveys sent to the SIG-Multicluster mailing list:
- CR name announcement with data is in [this email](https://groups.google.com/g/kubernetes-sig-multicluster/c/90VOAKEMRKQ/m/EYb …

KEP-2149: Cluster id api review request

---

keps/sig-instrumentation/3077-contextual-logging/README.md

- One-line PR description: simplify scope, avoid transition
- Issue link: https://github.com/kubernetes/enhancements/issues/3077
- Other comments: See https://kubernetes.slack.com/archives/CG3518SFJ/p1643891467807349 for the initial discussion of this change.

KEP 3077: contextual logging: simplify scope, avoid transition

---

keps/sig-cli/2299-kustomize-plugin-composition/README.md
keps/sig-cli/2299-kustomize-plugin-composition/kep.yaml
keps/sig-cli/2953-kustomize-plugin-graduation/README.md
keps/sig-cli/2953-kustomize-plugin-graduation/kep.yaml

- One-line PR description: Updates KRM Function related KEPs as discussed in a meeting several weeks ago.
- Issue link: #2299 #2953 
- Other comments: Includes an idea to address the use case in https://github.com/kubernetes-sigs/kustomize/issues/4288. Please lend a critical eye to this in particular.
/cc @mengqiy @jeremyrickard

Update KEPS 2299 and 2953

---

keps/sig-storage/1472-storage-capacity-tracking/README.md

- One-line PR description: document autoscaler support
- Issue link: https://github.com/kubernetes/enhancements/issues/1472
- Other comments: this is follow-up for https://github.com/kubernetes/enhancements/pull/3229#discussion_r816968403

KEP-1472: storage capacity: update drawbacks

---

keps/sig-network/2086-service-internal-traffic-policy/README.md
keps/sig-network/2086-service-internal-traffic-policy/kep.yaml

- One-line PR description: v1.24 updates for KEP-2086: Service Internal Traffic Policy
- Issue link: #2086 
Adding work towards GA in v1.24, but not planning to actually GA until v1.25

KEP-2086: updates for v1.24

---

pkg/repo/repo.go

This PR fixes an issue from golangci-lint.
```
(*'-') < make verify-golangci-lint
...
pkg/repo/repo.go:270:2: Consider preallocating `allKEPs` (prealloc)
var allKEPs []*api.Proposal
^
make: *** [verify-golangci-lint] Error 1
```
And I think we can enable golangci-lint in prow-job. It's skipped currently.
https://github.com/kubernetes/enhancements/blob/master/hack/verify.sh#L40
/cc @justaugustus

Fix an issue from golangci-lint

---

keps/NNNN-kep-template/README.md

Updating PRR to explicitly require field feedback for monitoring and troubleshooting before transitioning to GA.
Graduation criteria of https://github.com/kubernetes/enhancements/blob/master/keps%2Fsig-architecture%2F3136-beta-apis-off-by-default%2FREADME.md#ga , https://github.com/kubernetes/enhancements/issues/3136
/assign @johnbelamaric @ehashman @wojtek-t

update PRR to explicitly require field feedback to go GA

---

keps/sig-apps/3140-TimeZone-support-in-CronJob/README.md

- One-line PR description: adds beta promotion requirement 
- Issue link: https://github.com/kubernetes/enhancements/issues/3140
This was discovered in https://github.com/kubernetes/kubernetes/issues/109220 with a temporary fix skipping the test on MacOS in https://github.com/kubernetes/kubernetes/pull/109218

KEP 3140: Add LoadLocation on MacOS issue for beta promotion for CronJob TZ

---

.github/dependabot.yml
go.mod
go.sum

- go.mod: Update module to go1.17
- github: Add dependabot config
/assign @kikisdeliveryservice @jeremyrickard @mrbobbytables @palnabarun 
cc: @kubernetes/enhancements-maintainers

Update module to go1.17 and enable dependabot updates

---

pkg/kepctl/commands/create.go
pkg/proposal/create.go

so that it outputs the necessary fields for kep creation
also fix the flags so that we can pass along the required
fields for validation, otherwise KEP creation will simply
not work.
`kepctl create` does not work and it should work if you use the example output command. This fixes that.

fix the example output for kepctl

---

keps/sig-security/1933-secret-logging-static-analysis/README.md

- One-line PR description:  Update KEP-1933 references to now-deprecated KEP-1753
- Issue link:
- https://github.com/kubernetes/enhancements/issues/1753
- https://github.com/kubernetes/enhancements/issues/1933
- Other comments:  Data policy tags will remain in scope and undeprecated in KEP-1753.  See #3096.

KEP-1933: Update references to deprecated KEP-1753.

---

keps/NNNN-kep-template/README.md

Ref #3138 
There is a lot of context for this change across the whole https://github.com/kubernetes/enhancements/pull/3139
For PRR
/assign @johnbelamaric @deads2k @ehashman 
People involved in the discussion
/assign @liggitt @lavalamp @aojea @jberkus
@kubernetes/enhancements

Update Test Plan in KEP template 

---

keps/sig-api-machinery/1040-priority-and-fairness/README.md

Remove a dead hyperlink for fair-queuing paper and fix some typos in KEP-1040
- One-line PR description: Remove dead link and fix typos in README
- Issue link:

KEP-1040: Remove dead link and fix typos in README

---

keps/sig-cluster-lifecycle/kubeadm/2067-rename-master-label-taint/README.md

- One-line PR description:  [`wg-naming`](https://github.com/kubernetes/community/tree/master/archive/wg-naming) is now archived and its recommendation moved. That resulted in some broken links which this PR fixes for the future readers of this KEP.
- Issue link: https://github.com/kubernetes/enhancements/tree/master/keps/sig-cluster-lifecycle/kubeadm/2067-rename-master-label-taint
- Other comments: My first contrib here.

KEP-2067: Fixes broken link

---

OWNERS_ALIASES

SIG Service Catalog was retired, for more information see:
https://github.com/kubernetes/community/pull/6632

Remove SIG Service Catalog

---

keps/sig-release/3000-artifact-distribution/README.md
keps/sig-release/3000-artifact-distribution/kep.yaml

- One-line PR description: KEP-3000: Artifact Promotion and Distribution Policy
- Issue link: https://github.com/kubernetes/enhancements/issues/3055

KEP-3000: Image Promotion and Distribution Policy

---

keps/sig-node/2008-forensic-container-checkpointing/README.md
keps/sig-node/2008-forensic-container-checkpointing/kep.yaml

- One-line PR description: changed KEP 2008 target to 1.25
- Issue link: https://github.com/kubernetes/enhancements/pull/1990
- https://github.com/kubernetes/kubernetes/pull/104907
@mrunalp @mikebrow @derekwaynecarr PTAL
Let me know if the KEP needs more details about the CRI API changes. Most of the discussion happened so far in the code PR (https://github.com/kubernetes/kubernetes/pull/104907)

KEP-2008: changed to target 1.25

---

keps/prod-readiness/sig-api-machinery/2876.yaml
keps/sig-api-machinery/2876-crd-validation-expression-language/README.md
keps/sig-api-machinery/2876-crd-validation-expression-language/kep.yaml

- One-line PR description:  Promote CRD Validation Expression Language to Beta

KEP-2876: Promote CRD Validation Expression Language to Beta

---

keps/sig-auth/2579-psp-replacement/README.md

Adding in the checkbox from the new testing template.
I'm not a fan of cluttering KEPs with boilerplate like this. It makes them less readable as architectural artifacts. IMO if we need things like this it should either go in the tracking issue, or a separate file in the KEP directory.

PSA GA KEP compliance

---

keps/sig-scheduling/785-scheduler-component-config-api/README.md

- One-line PR description: graduate kube-scheduler component config to GA
- Issue link: https://github.com/kubernetes/enhancements/issues/785

graduate kube-scheduler ComponentConfig to GA

---

keps/prod-readiness/sig-network/1672.yaml
keps/sig-network/1672-tracking-terminating-endpoints/README.md
keps/sig-network/1672-tracking-terminating-endpoints/kep.yaml

- One-line PR description: v1.24 KEP updates for #1672 
- Issue link: #1672 

KEP-1672: updates for v1.24

---

keps/sig-storage/625-csi-migration/README.md

- One-line PR description: Update test plan for CSI Migration KEP

KEP-625: update CSI Migration KEP on test plans

---

keps/sig-api-machinery/2885-server-side-unknown-field-validation/README.md
keps/sig-api-machinery/2885-server-side-unknown-field-validation/kep.yaml

- One-line PR description: Update PR for beta milestone targeting 1.25 (fix metadata field validation)
- Issue link: https://github.com/kubernetes/enhancements/issues/2885

Update kep for beta graduation in 1.25

---

keps/sig-storage/625-csi-migration/README.md
keps/sig-storage/625-csi-migration/kep.yaml

- One-line PR description: Update the CSI migration GA timeline

KEP-625: update CSI Migration GA timeline

---

keps/prod-readiness/sig-apps/1591.yaml
keps/sig-apps/1591-daemonset-surge/README.md
keps/sig-apps/1591-daemonset-surge/kep.yaml

Promote DS maxSurge to GA
- Issue link: #1591 

KEP-1591: Promote DS maxSurge to GA

---

keps/prod-readiness/sig-network/3178.yaml
keps/sig-network/3178-iptables-cleanup/README.md
keps/sig-network/3178-iptables-cleanup/kep.yaml

- One-line PR description: Initial draft of KEP-3178, to clean up kubelet-vs-kube-proxy IPTables chain ownership
- Issue link: #3178
- Other comments: (I'm filing this now but targeting it at 1.25 for alpha given that it requires changes to the same parts of the iptables proxy that there are already multiple other pending KEP PRs for.)

KEP-3178: Cleaning up IPTables Chain Ownership

---

api/approval.go
api/proposal.go

- One-line PR description: api: correct JSON field name for Proposal.Number
- Issue link: None
- Other comments: JSON usually has camelCase field names. Fixing that for `Number` field of `Proposal` struct.

api: correct JSON field name for Proposal.Number

---

keps/sig-storage/2923-csi-migration-ceph-rbd/README.md
keps/sig-storage/2923-csi-migration-ceph-rbd/kep.yaml

One-line PR description: Update test template and milestone
Issue Link: #2923

KEP-2923: update test plan and milestone for RBD CSI migration

---

keps/prod-readiness/sig-apps/2599.yaml
keps/sig-apps/2599-minreadyseconds-for-statefulsets/README.md
keps/sig-apps/2599-minreadyseconds-for-statefulsets/kep.yaml

Promote STS minReadySeconds to GA
- Issue link:
https://github.com/kubernetes/enhancements/issues/2599

KEP-2599: Promote STS minReadySeconds to GA

---

keps/prod-readiness/sig-apps/3140.yaml
keps/sig-apps/3140-TimeZone-support-in-CronJob/README.md
keps/sig-apps/3140-TimeZone-support-in-CronJob/kep.yaml

- One-line PR description: TimeZone support in CronJob to beta
- Issue link: https://github.com/kubernetes/enhancements/issues/3140
/assign @janetkuo @ravisantoshgudimetla 
for sig-apps review
/assign @deads2k 
for prr review

KEP-3140: TimeZone support in CronJob

---

keps/sig-storage/1491-csi-migration-vsphere/README.md
keps/sig-storage/1491-csi-migration-vsphere/kep.yaml

- Issue link: https://github.com/kubernetes/enhancements/issues/1491
cc: @xing-yang

Update vsphere csi migration test plan

---

keps/prod-readiness/sig-node/3288.yaml
keps/sig-node/3288-separate-stdout-from-stderr/README.md
keps/sig-node/3288-separate-stdout-from-stderr/kep.yaml

Signed-off-by: Jian Zeng <anonymousknight96@gmail.com>
- One-line PR description: Split stdout and stderr log stream of container
- Issue link: https://github.com/kubernetes/enhancements/issues/3288
[Rendered](https://github.com/knight42/enhancements/tree/feat/split-stdout-stderr/keps/sig-node/3288-separate-stdout-from-stderr)

KEP 3288: Split stdout and stderr log stream

---

keps/prod-readiness/sig-storage/3333.yaml
keps/sig-storage/3333-reconcile-default-storage-class/README.md
keps/sig-storage/3333-reconcile-default-storage-class/kep.yaml

Retroactive default StorageClass assignment
- Issue link:
https://github.com/kubernetes/enhancements/issues/3333

KEP-3333 Retroactive default StorageClass assignment

---

keps/sig-storage/2589-csi-migration-portworx/README.md
keps/sig-storage/2589-csi-migration-portworx/kep.yaml

This commit adds the details to the KEP for promoting Portworx CSI migration from alpha to beta in v1.25
One-line PR description: Update KEP for Portworx CSI Migration
Issue link: Portworx file in-tree to CSI driver migration #https://github.com/kubernetes/enhancements/issues/2589
/sig storage
- Issue link:

Promote Portworx CSI migration to Beta in v1.25

---

keps/prod-readiness/sig-security/3203.yaml
keps/sig-security/3203-auto-refreshing-official-cve-feed/README.md
keps/sig-security/3203-auto-refreshing-official-cve-feed/kep.yaml

- One-line PR description: Add new KEP with yaml metadata
- Issue link: https://github.com/kubernetes/enhancements/issues/3203
- Other comments: SIG Security tracking issue for the overall effort: https://github.com/kubernetes/sig-security/issues/1

KEP-3203: Add Auto-refreshing Official CVE feed

---

keps/prod-readiness/sig-node/3386.yaml
keps/sig-node/3386-kubelet-evented-pleg/README.md
keps/sig-node/3386-kubelet-evented-pleg/kep.yaml

Signed-off-by: Harshal Patil <harpatil@redhat.com>
- One-line PR description:  Kubelet Evented PLEG for Better Performance
- Issue link: https://github.com/kubernetes/enhancements/issues/3386

KEP-3386: Kubelet Evented PLEG for Better Performance

---

keps/sig-node/2371-cri-pod-container-stats/README.md
keps/sig-node/2371-cri-pod-container-stats/kep.yaml

- One-line PR description: update criteria for alpha
- Issue link: https://github.com/kubernetes/enhancements/issues/2371

KEP-2371: update criteria for alpha

---

keps/prod-readiness/sig-auth/3299.yaml
keps/sig-auth/3299-kms-v2-improvements/README.md
keps/sig-auth/3299-kms-v2-improvements/kep.yaml

Signed-off-by: Rita Zhang <rita.z.zhang@gmail.com>
One-line PR description: Introduce KMS v2alpha1 API to add performance, rotation, and observability improvements
Issue link: #3299 
> NOTE: The observability part of this KEP has been reviewed and approved for alpha as part of KEP https://github.com/kubernetes/enhancements/pull/3133. The old KEP has been marked as `replaced` as part of this KEP PR. 
FYI @ibihim @aramase @dgrisonnet

3299-kms-v2-improvements

---

keps/sig-node/2008-forensic-container-checkpointing/README.md

KEP 2008: update test plan

---

keps/sig-storage/1487-csi-migration-aws/README.md

- One-line PR description: adds a test plan since we are targeting GA for 1.25.
- Issue link: https://github.com/kubernetes/enhancements/issues/1487

KEP-1487: Add aws-ebs migration test plan

---

keps/sig-storage/596-csi-inline-volumes/README.md
keps/sig-storage/596-csi-inline-volumes/kep.yaml

KEP-596: Move GA milestone to 1.25, update PRR
- Issue link:
https://github.com/kubernetes/enhancements/issues/596
/cc @jsafrane @gnufied @xing-yang @wojtek-t

KEP-596: Move GA milestone to 1.25, update PRR

---

keps/sig-api-machinery/1040-priority-and-fairness/README.md

- One-line PR description: describe how to add borrowing to API Priority and Fairness via dynamically adjusted concurrency limits
- Issue link:
- Other comments: This is one of four approaches being considered; the others are #3290, #3389, and #3394 .  This is structured as two commits: the first equals #3290, and the second has the changes from #3290.

[Draft] KEP-1040: periodically adjusted borrowing between priority levels in APF

---

keps/prod-readiness/sig-node/2254.yaml
keps/sig-node/2254-cgroup-v2/README.md
keps/sig-node/2254-cgroup-v2/kep.yaml

Signed-off-by: David Porter <porterdavid@google.com>
- One-line PR description: Target sig-node cgroupv2 KEP to GA in 1.25
* Update the KEP.yaml
* Update based on the new KEP template and added testing info
- Issue link: https://github.com/kubernetes/enhancements/issues/2254

KEP-2254: Target sig-node cgroupv2 KEP to GA in 1.25

---

keps/prod-readiness/sig-node/277.yaml
keps/sig-node/277-ephemeral-containers/README.md
keps/sig-node/277-ephemeral-containers/kep.yaml

- One-line PR description: Mark KEP-277 (Ephemeral Containers) as targeting stable for 1.25
- Issue link: #277

KEP-277: Target GA in 1.25

---

keps/prod-readiness/sig-network/2079.yaml
keps/sig-network/2079-network-policy-port-range/README.md
keps/sig-network/2079-network-policy-port-range/kep.yaml

- One-line PR description: Propose moving portRanges field to GA in v1.23
- Issue link: https://github.com/kubernetes/enhancements/issues/2079
- Other comments: There's some need of discussion in this KEP, about the graduation criteria, performance review and other to be resolved subjects.
/cc @thockin @caseydavenport @dcbw
/cc @danwinship @tgraf @aanm
- https://github.com/kubernetes/enhancements/pull/2709#discussion_r631791927
/cc @wojtek-t 
Thanks!

KEP-2079: Move portRanges to GA

---

keps/prod-readiness/sig-network/3070.yaml
keps/sig-network/3070-reserved-service-ip-range/README.md
keps/sig-network/3070-reserved-service-ip-range/kep.yaml

- One-line PR description: KEP-3070: promote to beta
- Issue link: https://github.com/kubernetes/enhancements/issues/3070

promote ServiceIPStaticSubrange to beta

---

keps/prod-readiness/sig-node/3327.yaml
keps/sig-node/3327-align-by-socket/README.md
keps/sig-node/3327-align-by-socket/kep.yaml

- One-line PR description: Adding new KEP
- Issue link:  #3327

KEP-3327: Add CPUManager policy option to align CPUs by Socket instead of by NUMA node

---

keps/prod-readiness/sig-release/3031.yaml
keps/sig-release/3031-signing-release-artifacts/README.md
keps/sig-release/3031-signing-release-artifacts/kep.yaml

Updating the release artifact signing KEP to beta.
Refers to https://github.com/kubernetes/enhancements/issues/3031
cc @kubernetes/sig-release-leads @kubernetes/sig-release @kubernetes/release-engineering

Graduate release artifact signing to beta

---

keps/prod-readiness/sig-scheduling/3022.yaml
keps/sig-scheduling/3022-min-domains-in-pod-topology-spread/README.md
keps/sig-scheduling/3022-min-domains-in-pod-topology-spread/kep.yaml

- One-line PR description: Write the production readiness requirements to graduate to beta
- Issue link: https://github.com/kubernetes/enhancements/issues/3022

[KEP-3022] Write the production readiness requirements to graduate to beta

---

keps/prod-readiness/sig-node/3085.yaml
keps/sig-node/3085-pod-conditions-for-starting-completition-of-sandbox-creation/README.md
keps/sig-node/3085-pod-conditions-for-starting-completition-of-sandbox-creation/kep.yaml

KEP to surface `PodHasNetwork` condition in pods to indicate when pod sandbox creation and network configuration of pod through CRI runtime is complete.
- Issue link: https://github.com/kubernetes/enhancements/issues/3085

KEP-3085: Add KEP for Pod network ready condition

---

keps/prod-readiness/sig-network/1880.yaml
keps/sig-network/1880-multiple-service-cidrs/README.md
keps/sig-network/1880-multiple-service-cidrs/kep.yaml

- One-line PR description: Services IP Ranges API: Initial implementation
- Issue link: https://github.com/kubernetes/enhancements/issues/1880

KEP-1880 Multiple Service CIDRs

---

keps/prod-readiness/sig-cli/3104.yaml
keps/sig-cli/3104-introduce-kuberc/README.md
keps/sig-cli/3104-introduce-kuberc/kep.yaml

- One-line PR description: Add initial KEP.
- Issue link: #3104 
/cc @liggitt @soltysh

KEP-3104: Introduce kuberc

---

keps/prod-readiness/sig-storage/361.yaml
keps/sig-storage/361-local-ephemeral-storage-isolation/README.md
keps/sig-storage/361-local-ephemeral-storage-isolation/kep.yaml

add KEP to promote local ephemeral storage to GA
- Issue link: #361
Comments:
- This replaces #3361 so we can get it in by the freeze.

KEP-361: promote Local Ephemeral Storage to GA

---

keps/sig-network/2593-multiple-cluster-cidrs/README.md
keps/sig-network/2593-multiple-cluster-cidrs/kep.yaml

- One-line PR description: Updating milestones to start from alpha in 1.25, Updating ClusterCIDRConfig API based on modifications suggested in  https://github.com/kubernetes/kubernetes/pull/108290

KEP:2593:Update ClusterCIDRConfig API, Test plan and Milestones

---

keps/sig-network/3178-iptables-cleanup/README.md
keps/sig-network/3178-iptables-cleanup/kep.yaml

- One-line PR description: updates for alpha: mark "implementable", update Test Plan from latest template
- Issue link: https://github.com/kubernetes/enhancements/issues/3178

KEP 3178: mark implementable, update Test Plan for alpha

---

keps/prod-readiness/sig-api-machinery/1027.yaml
keps/sig-api-machinery/1027-api-unions/README.md
keps/sig-api-machinery/1027-api-unions/kep.yaml

- One-line PR description: Update KEP for API Unions. 
- Issue link: #1027 

KEP-1027: API Unions for 1.25

---

keps/prod-readiness/sig-api-machinery/3352.yaml
keps/sig-api-machinery/3352-aggregated-discovery/README.md
keps/sig-api-machinery/3352-aggregated-discovery/kep.yaml

- One-line PR description: Add KEP for publishing an aggregated discovery document. This will reduce the number of requests by clients when fetching all api resources from the server.
- Issue link: https://github.com/kubernetes/enhancements/issues/3352

KEP-3352: Aggregated Discovery KEP to Alpha

---

keps/sig-release/3031-signing-release-artifacts/README.md

As mentioned in https://github.com/kubernetes/enhancements/issues/3031#issuecomment-1163232164
cc @kubernetes/release-engineering

Update test plan for artifact signing KEP

---

keps/sig-node/2238-liveness-probe-grace-period/README.md
keps/sig-node/2238-liveness-probe-grace-period/kep.yaml

Signed-off-by: Paul S. Schweigert <paulschw@us.ibm.com>
- One-line PR description: updating KEP to new template
- Issue link:

Updates kep-2238 for v1.25

---

keps/sig-scheduling/785-scheduler-component-config-api/README.md

- One-line PR description: Mark SelectorSpread plugin as deprecated when graduating scheduler Component Config
- Issue link: https://github.com/kubernetes/enhancements/issues/785

Remove SelectorSpread plugin when graduating scheduler Component Config

---

keps/sig-network/3178-iptables-cleanup/README.md
keps/sig-network/3178-iptables-cleanup/kep.yaml

- One-line PR description: renames feature gate from `IPTablesCleanup` to `IPTablesOwnershipCleanup` based on feedback from @thockin in https://github.com/kubernetes/kubernetes/pull/110291
- Issue link: https://github.com/kubernetes/enhancements/issues/3178

KEP-3178: rename feature gate to IPTablesOwnershipCleanup

---

hack/push-manifest.sh

Adds a script to generate KEPS Manifest and push to the KEPS Bucket
Part of https://github.com/kubernetes/enhancements/issues/2095
Signed-off-by: Nabarun Pal <pal.nabarun95@gmail.com>

add script to generate and push KEP manifest to GCS bucket

---

keps/sig-apps/3329-retriable-and-non-retriable-failures/README.md
keps/sig-apps/3329-retriable-and-non-retriable-failures/kep.yaml

One-line PR description:  Updates the KEP to the implemented state
- Other comments: main changes motivated by implementation in PRs https://github.com/kubernetes/kubernetes/pull/110959 and https://github.com/kubernetes/kubernetes/pull/111113:
- update the set of introduced pod conditions and reasons
- added a note on handling a failed delete after successful patch to append the pod condition
- added a note on setting pod's phase as Failed by podgc and simplifying the related logic in job controller for Beta
- renamed the feature gate `JobBackoffPolicy` as `JobPodFailurePolicy`
- introduced a new feature gate `PodDisruptionConditions` for control appending of pod disruption conditions
- renamed the job spec field …

Update KEP-3329 "Retriable and non-retriable Pod failures for Jobs"

---

keps/sig-node/127-user-namespaces/README.md

round up the user namespace size to 2^16 IDs as there is no advantage
to use the smaller size.  65536 is also the default size shadow-utils
uses for the additional IDs to unprivileged users.
Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>
- One-line PR description: round up user namespace size to 2^16

127-user-namespaces: round userns size to 65536

---

keps/sig-release/3031-signing-release-artifacts/README.md
keps/sig-release/3031-signing-release-artifacts/kep.yaml

This changes the KEP to match the new scope as well as targeting the implementation for v1.26.
cc @kubernetes/release-engineering

KEP-3031: Update signing KEP to match new scope

---

keps/sig-storage/596-csi-inline-volumes/README.md
keps/sig-storage/596-csi-inline-volumes/kep.yaml

KEP-596: Update graduation criteria and test results
- Issue link:
https://github.com/kubernetes/enhancements/issues/596
This PR follows up on the remaining action items in the graduation criteria.
- Test results for ugprade/downgrade testing and pod startup latency have been added to their respective sections in the PRR.
- Opened a new issue (https://github.com/kubernetes-csi/csi-driver-nfs/issues/364) to align the NFS driver with the new guidance in the docs. No such issue for the SMB driver.
- Feature gate PR: https://github.com/kubernetes/kubernetes/pull/111258
/cc @jsafrane @msau42 @xing-yang @wojtek-t

KEP-596: Update graduation criteria and test results

---

keps/sig-storage/1489-csi-migration-cinder/kep.yaml

CSI migration for OpenStack Cinder was GA in 1.24, mark the KEP as `implemented`.
And close the enhancement issue:
Fixes: #1489
cc @xing-yang @msau42

KEP 1489: Mark CSI migration for Cinder as done

---

compile-tools
go.mod
go.sum
internal/tools.go
keps/sig-node/3063-dynamic-resource-allocation/Makefile

There are two things this PR fixes:
1. a missing boilerplate header from sig-node
2. go-mod-updated is dragging in a deleted dependency which is causing our test pipeline to choke.
Fixes #3471

CI is currently broken as file is missing header and tool drags in retracted dependency

---

keps/sig-auth/3299-kms-v2-improvements/README.md

Signed-off-by: Anish Ramasekar <anish.ramasekar@gmail.com>
Updating the KMSv2 KEP to reflect the latest `EncryptedObject` and prefix.
/cc @ritazh @enj
/assign @enj

update EncryptedObject struct in kms v2

---

keps/sig-auth/3325-self-subject-attributes-review-api/kep.yaml

Signed-off-by: m.nabokikh <maksim.nabokikh@flant.com>
The KEP was moved to the release v1.26.

KEP-3325: Update milestone for SelfSubjectAttributesReview KEP

---

README.md

Why:
missed verb & Incorrect article usage
What's being changed:
Changed "not actively" to "not be actively" -> missing verb, so added it for better read
Changed "for definition" to "for the definition" -> article usage fixed
Changed "in Enhancements" to "in the Enhancements" -> added a article
Check off the following:
I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
For content changes, I have completed the self-review checklist.

Updated enhancements README.md

---

keps/sig-windows/2802-identify-windows-pods-apiserver-admission/README.md
keps/sig-windows/2802-identify-windows-pods-apiserver-admission/kep.yaml

final updates to PodOs KEP

---

keps/sig-windows/2258-node-service-log-viewer/README.md
keps/sig-windows/2258-node-service-log-viewer/kep.yaml

- One-line PR description: Update the milestones on the KEP for node service log viewer to 1.26+

KEP-2258: Update milestones to 1.26

---

README.md

Remove the word deprecated in the sub-heading title to fix the broken link to #enhancements-tracking-spreadsheet subsection.

README: fix heading for enhancements spreadsheet section 

---

keps/sig-instrumentation/647-apiserver-tracing/README.md
keps/sig-instrumentation/647-apiserver-tracing/kep.yaml

- One-line PR description: Update beta version to 1.26 and add graduation criterion
- Other comments: Additional instrumentation was requested in https://github.com/kubernetes/enhancements/issues/647#issuecomment-1078834288.  APIServer tracing did not graduate in 1.24 because we were unable to update to the stable OpenTelemetry version.

KEP-647: Update beta version to 1.26 and add graduation criterion

---

keps/sig-node/3085-pod-conditions-for-starting-completition-of-sandbox-creation/kep.yaml

https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/3085-pod-conditions-for-starting-completition-of-sandbox-creation
Hey all,  This seems pretty significant for sig-network looking forward.  This PR adds a sig-net reviewer for this PR - we should make sure we are all aligned on what this really means before this goes past alpha.
cc @derekwaynecarr

KEP-3085: Add sig-net to PodHasNetwork KEP

---

keps/sig-node/1558-streaming-proxy-redirects/README.md
keps/sig-node/1558-streaming-proxy-redirects/kep.yaml

the --redirect-container-streaming flag and feature gate will be removed in 1.24
- One-line PR description: update kep status of `Streaming Proxy Redirects [DEPRECATED]`
- Issue link: https://github.com/kubernetes/enhancements/issues/1558

[1.24] Mark 1558 kep status to implemented

---

keps/prod-readiness/sig-windows/1981.yaml
keps/sig-windows/1981-windows-privileged-container-support/README.md
keps/sig-windows/1981-windows-privileged-container-support/kep.yaml

- Issue link: https://github.com/kubernetes/enhancements/issues/1981

KEP-1981: WindowsHostProcessContainers beta major changes

---

keps/prod-readiness/sig-apps/2307.yaml
keps/sig-apps/2307-job-tracking-without-lingering-pods/README.md
keps/sig-apps/2307-job-tracking-without-lingering-pods/kep.yaml

- One-line PR description: Add GA and deprecation notes
- Issue link: #2307
- Add metric `job_pod_tracking_finalizer`.
- Add legacy to finalizers migration under `MigrateJobLegacyTracking` feature gate.
- Add known failure modes.

KEP-2307: Graduate JobTrackingWithFinalizers to GA

---

keps/sig-auth/3299-kms-v2-improvements/kep.yaml

Signed-off-by: Anish Ramasekar <anish.ramasekar@gmail.com>
- One-line PR description: Update beta and GA milestone for KMS v2. It will be alpha in v1.26 release.
/assign @enj 
/sig auth

KEP-3299: update beta and GA milestone

---

keps/prod-readiness/sig-storage/1491.yaml
keps/sig-storage/1491-csi-migration-vsphere/kep.yaml

set latest milestone for vSphere migration to 1.26
- Issue link: https://github.com/kubernetes/enhancements/issues/1491

KEP-1491: set latest milestone for vSphere migration to 1.26

---

keps/sig-multicluster/2149-clusterid/README.md

- One-line PR description: Rename id.k8s.io cluster.clusterset.k8s.io.
- Issue link: #2149 
- Other comments: This rename was based on SIG-MC discussion around comments by API reviewer @thockin. See [background notes here](https://docs.google.com/document/d/12znQZGyRdUWbHkKuif0ySZdm0SMIymGJFQvAxVREMpE/preview#) and in SIG-MC discussions on 7/12, 7/26 and [on the mailing list for brainstorms](https://groups.google.com/g/kubernetes-sig-multicluster/c/OIZsM6-ANfw/m/KS9eJFmMAAAJ) and [for voting](https://groups.google.com/g/kubernetes-sig-multicluster/c/gAIh8TGMuLQ) but tl;dr since this CRD has a general apiGroup name (about.k8s.io), the ClusterProperty name `id.k8s.io` might be interpreted by users semantically on its own and used in cases its restrictions per the KEP do not align with

KEP-2149: Rename id.k8s.io --> cluster.clusterset.k8s.io

---

keps/prod-readiness/sig-storage/1885.yaml
keps/sig-storage/1885-csi-migration-azurefile/README.md
keps/sig-storage/1885-csi-migration-azurefile/kep.yaml

- One-line PR description: Update Azure File csi migration test plan
- Issue link: https://github.com/kubernetes/enhancements/issues/1885
- Other comments: related k/k PR: https://github.com/kubernetes/kubernetes/pull/110458
cc @Jiawei0227 @msau42 @xing-yang

KEP-1885: Update Azure File csi migration

---

keps/sig-network/2593-multiple-cluster-cidrs/README.md

when I reading  https://github.com/kubernetes/enhancements/tree/master/keps/sig-network/2593-multiple-cluster-cidrs , found a little mistake.
cidr allocate number vs:
2 ^( (32-17) - 4) block >  2 ^ ((32-20) - 4 )
so the order should reverse if correct.
/cc @aojea @sarveshr7

correct multi cluster cidr example order

---

keps/prod-readiness/sig-network/1672.yaml
keps/sig-network/1672-tracking-terminating-endpoints/README.md
keps/sig-network/1672-tracking-terminating-endpoints/kep.yaml

Promote EndpointSliceTerminatingCondition feature gate to GA in v1.26. This feature has been Beta since v1.22 and was pending validation from sig-scalability on the performance implications of this change.
- Issue link: #1672 

KEP-1672: promote EndpointSliceTerminatingCondition feature to GA

---

keps/prod-readiness/sig-network/1669.yaml
keps/sig-network/1669-proxy-terminating-endpoints/README.md
keps/sig-network/1669-proxy-terminating-endpoints/kep.yaml

Promote ProxyTerminatingEndpoints feature to Beta (alpha since v1.24).
- Issue link:

KEP-1669: promote ProxyTerminatingEndpoints to Beta

---

keps/prod-readiness/sig-storage/3333.yaml
keps/sig-storage/3333-reconcile-default-storage-class/README.md
keps/sig-storage/3333-reconcile-default-storage-class/kep.yaml

- One-line PR description: Graduate RetroactiveDefaultStorageClass feature to beta
- Issue link: https://github.com/kubernetes/enhancements/issues/3333

KEP-3333: Graduate RetroactiveDefaultStorageClass to beta in v1.26 

---

keps/prod-readiness/sig-storage/2268.yaml
keps/sig-storage/2268-non-graceful-shutdown/README.md
keps/sig-storage/2268-non-graceful-shutdown/kep.yaml

- One-line PR description: Move non-graceful node shutdown feature to beta.
- Issue link: #2268 

Update non-graceful node shutdown to beta

---

keps/prod-readiness/sig-api-machinery/3157.yaml
keps/sig-api-machinery/3157-watch-list/kep.yaml

updates the status to `implementable` and milestone to `v1.26`

update status and milestone for KEP 3157 (watch-list)

---

keps/prod-readiness/sig-network/3453.yaml
keps/sig-network/3453-minimize-iptables-restore/README.md
keps/sig-network/3453-minimize-iptables-restore/kep.yaml

- One-line PR description: initial proposal
- Issue link: https://github.com/kubernetes/enhancements/issues/3453
/sig network
/assign @thockin @aojea

Minimizing iptables-restore input size

---

keps/sig-cli/2379-kubectl-plugins/README.md
keps/sig-cli/2379-kubectl-plugins/kep.yaml

Add support for shell-completion for plugins.
- Issue: https://github.com/kubernetes/kubernetes/issues/74178
- Implementation: https://github.com/kubernetes/kubernetes/pull/105867
This improvement was discussed during the SIG-CLI meeting of [March 22nd], 2022(https://docs.google.com/document/d/1r0YElcXt6G5mOWxwZiXgGu_X6he3F--wKwg-9UBc29I/edit#bookmark=kix.alt3br5igshx), and it was requested to update the KEP to document the proposal.

KEP-2379: adding support for shell-completion for plugins

---

keps/sig-api-machinery/3488-cel-admission-control/README.md

- One-line PR description: Replace UNRESOLVEDs in phase 2 with notes about what needs more detailed design before implementing. Also move enforcement actions to phase 2 because we don't have enough resourcing to tackle it all in phase 1 and there are still design discussions ongoing

Clear UNRESOLVEDs, defer enforcement actions to phase 2

---

keps/prod-readiness/sig-network/2086.yaml
keps/sig-network/2086-service-internal-traffic-policy/README.md
keps/sig-network/2086-service-internal-traffic-policy/kep.yaml

Updates ServiceInternalTrafficPolicy feature to GA in v1.26. Feature has been in Beta since v1.22 and was blocked on a metric that was added in v1.24.
- Issue link: https://github.com/kubernetes/enhancements/issues/2086

KEP-2086: promote ServiceInternalTrafficPolicy to GA in v1.26

---

keps/sig-cloud-provider/2395-removing-in-tree-cloud-providers/README.md

We blew past some deadlines, so update them! Also note the dependency on the removal of in-tree storage plugins.
You may want to see the dates for the CSI migration that will drive removal of specific providers:
https://github.com/dims/enhancements/pull/new/bump-dates-for-in-tree-cloud-provider-removal
- Issue link: https://github.com/kubernetes/enhancements/issues/2395

KEP-2395: Bump dates for in-tree cloud provider removal

---

keps/sig-apps/3017-pod-healthy-policy-for-pdb/README.md

- One-line PR description: update Test Plan section to comply with the latest KEP template

Update KEP-3017: Test Plan section

---

keps/sig-network/1672-tracking-terminating-endpoints/README.md

Update KEP-1672 to use the new test plan format, per https://github.com/kubernetes/enhancements/issues/1672#issuecomment-1267833411
- Issue link: https://github.com/kubernetes/enhancements/issues/1672

KEP-1672: update to use new test plan format

---

keps/prod-readiness/sig-api-machinery/3352.yaml
keps/sig-api-machinery/3352-aggregated-discovery/README.md
keps/sig-api-machinery/3352-aggregated-discovery/kep.yaml

KEP-3352
- One-line PR description: Updating milestone and comments for 1.26
- Issue link: https://github.com/kubernetes/enhancements/issues/3352

Update Aggregated Discovery for 1.26

---

keps/sig-node/2400-node-swap/README.md
keps/sig-node/2400-node-swap/kep.yaml

Updated SWAP KEP to indicate that in 1.26 we will be working on the feature but are not ready to promote it to beta. The reason for this is that there are still many uncertainty with what guarantees we can provide and whether the feature can destabilize the system.
One possible outcome of alpha2 work is that we may decide to limit the feature to cgroupv2.
Before this is investigated, it's better to keep feature in alpha stage.
/sig node
/assign @dchen1107 @derekwaynecarr

updated swap KEP: targeting alpha2 in 1.26

---

keps/prod-readiness/sig-api-machinery/3488.yaml
keps/sig-api-machinery/3488-cel-admission-control/README.md
keps/sig-api-machinery/3488-cel-admission-control/kep.yaml

- One-line PR description: Adding PRR and test section for CEL Admission Control
- Other comments: This is based on https://github.com/kubernetes/enhancements/pull/3492

KEP-3488: Add PRR and test section for Cel admission control

---

keps/sig-api-machinery/3488-cel-admission-control/README.md

- One-line PR description: Intent is that all enforcement action work be deferred to phase 2. This removes some references to prior design ideas.

Remove references to mode

---

keps/sig-windows/1981-windows-privileged-container-support/README.md
keps/sig-windows/1981-windows-privileged-container-support/kep.yaml

- One-line PR description: KEP updates for moving `WindowsHostProcessContainers` to stable
- Issue link: https://github.com/kubernetes/enhancements/issues/1981

KEP 1981 Windows HostProcessContainers to stable

---

keps/prod-readiness/sig-cli/3515.yaml
keps/sig-cli/3515-kubectl-explain-openapiv3/README.md
keps/sig-cli/3515-kubectl-explain-openapiv3/kep.yaml

- One-line PR description: adding new draft KEP
- Issue link: https://github.com/kubernetes/enhancements/issues/3515

KEP-3515: add new kep kubectl explain openapi v3 upgrade

---

keps/sig-network/2593-multiple-cluster-cidrs/README.md
keps/sig-network/2593-multiple-cluster-cidrs/kep.yaml

- One-line PR description: Modify the feature-gate to MultiCIDRRangeAllocator, Change the API from ClusterCIDRConfig to ClusterCIDR. Update the milestones beta to 1.27 and stable to 1.29

KEP:2593:Update feature-gate, API Name and Milestones

---

keps/prod-readiness/sig-network/2433.yaml
keps/sig-network/2433-topology-aware-hints/README.md
keps/sig-network/2433-topology-aware-hints/kep.yaml

- Updates Topology Aware Hints KEP with GA Graduation Criteria
This is also closely related to https://github.com/kubernetes/enhancements/pull/3293.
/sig network
/cc @andrewsykim @bowei @dcbw @danwinship
/assign @thockin @wojtek-t

Updating Topology Aware Hints KEP with GA Graduation Criteria

---

keps/prod-readiness/sig-scheduling/3094.yaml
keps/sig-scheduling/3094-pod-topology-spread-considering-taints/README.md
keps/sig-scheduling/3094-pod-topology-spread-considering-taints/kep.yaml

- One-line PR description: Graduate NodeInclusionPolicy to Beta
- Issue link: https://github.com/kubernetes/enhancements/issues/3094

KEP-3094: Graduate NodeInclusionPolicy to Beta in v1.26

---

keps/prod-readiness/sig-scheduling/3521.yaml
keps/sig-scheduling/3521-pod-schedule-readiness/README.md
keps/sig-scheduling/3521-pod-schedule-readiness/kep.yaml

- One-line PR description: Initial KEP writeup for Pod Schedule Readiness

KEP: Pod Schedule Readiness

---

keps/sig-storage/2644-honor-pv-reclaim-policy/README.md
keps/sig-storage/2644-honor-pv-reclaim-policy/kep.yaml

- One-line PR description: Support Statically provisioned volumes
- Issue link: https://github.com/kubernetes/enhancements/issues/2644
Signed-off-by: Deepak Kinni <dkinni@vmware.com>

KEP-2644: [HonorPVReclaimPolicy] Support Statically provisioned volumes

---

keps/sig-instrumentation/3466-kubernetes-component-health-slis/README.md
keps/sig-instrumentation/3466-kubernetes-component-health-slis/kep.yaml

This amends the feature-gate name in KEP-3466 to be accurate. 
/assign @dashpole @dgrisonnet

amend feature gate name to be accurate

---

keps/sig-instrumentation/3498-extending-stability/README.md

This amends KEP-3498 to reduce scope slightly for alpha.
/assign @dashpole @dgrisonnet

reduce scope for alpha extending metrics stability

---

keps/sig-instrumentation/3466-kubernetes-component-health-slis/README.md

Since the feature will be default disabled, the e2e tests will be a beta requirement.

amend test section for component slis

---

keps/prod-readiness/sig-windows/3503.yaml
keps/sig-windows/3503-host-network-support-for-windows-pods/README.md
keps/sig-windows/3503-host-network-support-for-windows-pods/kep.yaml

KEP-3503 Initial KEP for windows host-network support

---

keps/prod-readiness/sig-apps/3335.yaml
keps/sig-apps/3335-statefulset-slice/README.md
keps/sig-apps/3335-statefulset-slice/kep.yaml

- One-line PR description: Adding new KEP to support StatefulSet slice
- Issue link: https://github.com/kubernetes/enhancements/issues/3335

KEP-3335: StatefulSet Slice

---

keps/prod-readiness/sig-storage/3294.yaml
keps/sig-storage/3294-provision-volumes-from-cross-namespace-snapshots/README.md
keps/sig-storage/3294-provision-volumes-from-cross-namespace-snapshots/kep.yaml

- One-line PR description: Provision volumes from cross-namespace snapshots
- Issue link: https://github.com/kubernetes/enhancements/issues/3294

KEP-3294: Add proposal for provisioning volumes from cross-namespace snapshots

---

keps/sig-node/2371-cri-pod-container-stats/README.md
keps/sig-node/2371-cri-pod-container-stats/kep.yaml

- One-line PR description: Updating KEP with cgroup stats of cadvisor metrics, adding CRI implementation details
- Issue link: https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/2371-cri-pod-container-stats

KEP-2371: Add cgroup metrics + CRI implementation plan

---

keps/prod-readiness/sig-api-machinery/2339.yaml
keps/sig-api-machinery/2339-storageversion-api-for-ha-api-servers/README.md
keps/sig-api-machinery/2339-storageversion-api-for-ha-api-servers/kep.yaml

- One-line PR description: beta details
- Issue link: #2339

KEP-2339: beta details

---

keps/prod-readiness/sig-api-machinery/1965.yaml
keps/sig-api-machinery/1965-kube-apiserver-identity/README.md
keps/sig-api-machinery/1965-kube-apiserver-identity/kep.yaml

Co-authored-by: Monis Khan <mok@microsoft.com>
Update KEP-1965 to include all Beta criterias and answer remaining PRR questions. 
- Issue link:  
https://github.com/kubernetes/enhancements/issues/1965 

KEP-1965: update with Beta criteria/milestone and PRR questions answered

---

keps/sig-node/2371-cri-pod-container-stats/README.md

Signed-off-by: James Sturtevant <jstur@microsoft.com>
Adding Windows stats details to the cri pod container stats KEP
- Issue link: https://github.com/kubernetes/enhancements/issues/2371
After opening https://github.com/kubernetes/kubernetes/pull/110754 we discovered there was more design work need for Windows and was suggested at sig-node to do the work in KEP.
/sig windows
/sig node

Add Windows pod sandbox stats information to KEP 2371 - cri pod container stats

---

keps/sig-network/2433-topology-aware-hints/README.md

- One-line PR description: Adds test agreement to Topology Hints KEP as requested by @rhockenbury 
/sig network

Adding test agreement to Topology Hints KEP

---

keps/sig-node/3063-dynamic-resource-allocation/README.md
keps/sig-node/3063-dynamic-resource-allocation/kep.yaml

- One-line PR description: API update and revised milestones.
- Other comments: see https://github.com/pohly/enhancements/pull/13 for a previous discussion around these API changes.

KEP-3063: dynamic resource allocation updates for 1.26

---

keps/prod-readiness/sig-auth/2718.yaml
keps/sig-auth/2718-20210511-client-exec-proxy/README.md
keps/sig-auth/2718-20210511-client-exec-proxy/kep.yaml

A KEP to propose a client-side proxy for a number of client authentication use cases.

Client Exec Proxy

---

keps/prod-readiness/sig-auth/3257.yaml
keps/sig-auth/3257-trust-anchor-sets/README.md
keps/sig-auth/3257-trust-anchor-sets/kep.yaml

This KEP proposes a new TrustAnchorSets object that signers can use to distribute their X.509 trust anchors.  Additionally, it proposes a Kubelet projected volume source to allow workloads to easily consume data from TrustAnchorSets.
Issue link: https://github.com/kubernetes/enhancements/issues/3257
Currently remaining

KEP-3257: Trust Anchor Sets

---

keps/sig-api-machinery/3488-cel-admission-control/README.md
keps/sig-api-machinery/3488-cel-admission-control/kep.yaml

- One-line PR description: Update the name of the feature gate(https://github.com/kubernetes/kubernetes/pull/112792) and check the test agreement

Update FG name and Check the test agreement

---

keps/sig-node/2400-node-swap/README.md

/sig node
this is reformatting of a node swap test plan secton to match the latest template. Minor details were added
KEP: https://github.com/kubernetes/enhancements/issues/2400

reformatting of a test plan

---

keps/prod-readiness/sig-testing/3041.yaml
keps/sig-testing/3041-node-conformance-and-features/README.md
keps/sig-testing/3041-node-conformance-and-features/kep.yaml

/sig testing
/sig node
Fix up the status of a KEP: https://github.com/kubernetes/enhancements/issues/3041

change status to implementable for feature tags alignment

---

keps/sig-api-machinery/1965-kube-apiserver-identity/README.md

- Lease garbage collection actually runs in kube-apiserver in a post start hook, not kube-controller-manager
- Lease namespace is `kube-system` and not `kube-apiserver-lease`
- Lease ID is kube-apiserver-(uuid)
- One-line PR description: update kube-apiserver identity KEP to reflect current state
- Issue link: https://github.com/kubernetes/enhancements/issues/1965

KEP-1965: update kube-apiserver identity KEP to reflect current state

---

keps/sig-release/1731-publishing-packages/README.md
keps/sig-release/1731-publishing-packages/kep.yaml

- One-line PR description: Updates the KEP-1731 to reflect current SIG Release Processes
- Issue link: #1731 
Other comments: 
- Defines the Release Manager and End User roles
- Removes references to anago (name of a bash script formerly used in this space) anago functionality has been re-implemented as a go module and subsumed into the krel command. 
- Added proper noun capitalization for defined roles 
Adds or fixes refs for
- the "officially documented package mirror"
- a Gherkin reference for the user stories
- kubepkg
This is an initial attempt to revive this KEP by bringing it into line with all of the tooling improvements that have been made by the SIG Release Team since this KEP was first written.
It will we will need careful review of experienced SIG Release Team members …

KEP-1731 : Publishing Kubernetes packages on community infrastructure

---

keps/sig-storage/2644-honor-pv-reclaim-policy/README.md

- One-line PR description: Drop support for in-tree statically provisioned volumes
- Issue link: https://github.com/kubernetes/enhancements/issues/2644
Signed-off-by: Deepak Kinni <dkinni@vmware.com>

Update KEP 2644 to reflect drop in support for in-tree statically provisioned volumes

---

keps/sig-api-machinery/1965-kube-apiserver-identity/README.md

Update the apiserver lease identity format based on this week's SIG API Machinery discussion.
- Issue link: #1965 

KEP-1965: update apiserver lease identity format

---

keps/sig-node/3327-align-by-socket/kep.yaml

KEP-3327: Updating beta target date for align-by-socket
- Issue link: https://github.com/kubernetes/enhancements/issues/3327 

Updating beta & stable target for align-by-socket

---

keps/sig-scheduling/3094-pod-topology-spread-considering-taints/README.md

- One-line PR description: Update some progress when graduating nodeInclusionPolicy to beta
- Issue link: https://github.com/kubernetes/enhancements/pull/3539
They're required when graduate nodeInclusionPolicy to beta:
1) feature enablement tests
2) upgrade and rollback tested

Update nodeInclusionPolicy beta graduation progress

---

keps/sig-apps/3329-retriable-and-non-retriable-failures/README.md

- One-line PR description: Update to reflect decisions taken during the implementation phase
The changes compared to the initial plan for Beta:
- do not introduce the `ResourceExhausted` condition (it was planned to be used for pods killed due to OOM killer or exceeding ephemeral storage limits)
- do not add `DisruptionTarget` condition in case of admission failures
- reason for the `DisruptionTarget` added by Kubelet is renamed from `DeletionByKubelet` to `TerminationByKubelet` 
- introduce a new metric called `terminated_pods_tracking_finalizer_total` instead of extending the existing one `job_pods_finished_total`
- do not implement the logic to avoid `DisruptionTarget` override in case the `status=True` for the …

Update for "Retriable and non-retriable Pod failures for Jobs"

---

OWNERS_ALIASES

Related:
- Part of: https://github.com/kubernetes/community/issues/6913

OWNERS_ALIASES: update-sig-testing-leads

---

keps/sig-network/1669-proxy-terminating-endpoints/README.md

Some manual rollback testing was performed for KEP-1669 since it will be graduating to Beta in v1.26 and enabled by default. This PR just documents the steps taken. Unfortunately automated testing for rollback was not feasible.  
- Issue link: https://github.com/kubernetes/enhancements/issues/1669

KEP-1669: document rollback testing

---

keps/sig-instrumentation/2845-deprecate-klog-specific-flags-in-k8s-components/README.md

Find some typos in this doc:
```
keps/sig-instrumentation/2845-deprecate-klog-specific-flags-in-k8s-components/README.md
```
Fixes #3666

KEP-2845: fix some typos in README.md

---

keps/sig-api-machinery/1040-priority-and-fairness/README.md

- One-line PR description: Revise initialization of SmoothSeatDemand in concurrency borrowing description
- Issue link:
- Other comments: This corresponds to a change made late in the implementation, as results from testing revealed a problem.

KEP-1040: Revise initialization of SmoothSeatDemand

---

keps/sig-storage/1491-csi-migration-vsphere/kep.yaml

-  This feature has been fully implemented and is now GA in K8s version 1.26.
- Issue link: https://github.com/kubernetes/enhancements/issues/1491#issuecomment-1347549426
cc: @xing-yang  @marosset

KEP-1491: set vSphere CSI driver migration as implemented

---

keps/sig-windows/2258-node-service-log-viewer/README.md
keps/sig-windows/2258-node-service-log-viewer/kep.yaml

- One-line PR description: Update milestones to 1.27
- Rename the feature gate to `NodeLogQuery` to match the implementation

KEP 2258: Update milestones to 1.27

---

keps/sig-storage/2317-fsgroup-on-mount/kep.yaml

- One-line PR description:  Mark KEP 2317 (Provide fsGroup of pod to CSI driver on mount) as implemented

KEP-2317: mark as implemented

---

keps/sig-apps/3017-pod-healthy-policy-for-pdb/README.md

- One-line PR description: changes to reflect the [implementation](https://github.com/kubernetes/kubernetes/pull/113375) that was considerably altered as compared to this KEP 

KEP-3017: rewrite PodHealthyPolicy KEP into UnhealthyPodEvictionPolicy

---

keps/sig-apps/3017-pod-healthy-policy-for-pdb/README.md

- One-line PR description: make API definition of UnhealthyPodEvictionPolicy unversioned; to address [review](https://github.com/kubernetes/enhancements/pull/3677#discussion_r1053076705) in https://github.com/kubernetes/enhancements/pull/3677

KEP-3017: make API definition of UnhealthyPodEvictionPolicy unversioned

---

keps/sig-auth/2799-reduction-of-secret-based-service-account-token/README.md
keps/sig-auth/2799-reduction-of-secret-based-service-account-token/kep.yaml

updating beta criteria and outdated text.

KEP-2799: update for LegacyServiceAccountTokenTracking beta

---

keps/sig-network/1435-mixed-protocol-lb/kep.yaml

* One-line PR description: `Support of mixed protocols in Services with type=LoadBalancer` has graduated to `stable` and can be considered implemented.
* Issue link: [Support of mixed protocols in Services with type=LoadBalancer #1435
](https://github.com/kubernetes/enhancements/issues/1435)
* Other comments: 
Fixes https://github.com/kubernetes/enhancements/issues/1435
/cc @marosset @janosi 

KEP-1435: Support of mixed protocols in Services with type=LoadBalancer is implemented

---

keps/sig-network/2943-networkpolicy-status/README.md
keps/sig-network/2943-networkpolicy-status/kep.yaml

- One-line PR description: Withdraw Network Policy Status
- Issue link: https://github.com/kubernetes/enhancements/issues/2943
- Other comments: Per sig-network meeting on 05/Jan/2023, we are removing this feature. We need to make sure that the protobuf names used to persist on etcd are documented, so in a future if we decide to reimplement this feature a new name should be used to avoid conflicts.

2943: Withdrawn network policy status implementation

---

keps/sig-node/1287-in-place-update-pod-resources/README.md
keps/sig-node/1287-in-place-update-pod-resources/kep.yaml

- One-line PR description: Allow resizing pod CPU and memory resources without pod restarts. We have merged the CRI changes in 1.25 to facilitate runtime support implementation. Main feature is now targeted for alpha in 1.27

Retarget in-place pod resize KEP to 1.27 alpha

---

keps/sig-instrumentation/647-apiserver-tracing/kep.yaml

One-line PR description: Update beta version to 1.27
Issue link: https://github.com/kubernetes/enhancements/issues/647
Other comments: APIServer tracing did not graduate in 1.26 because of a bug in the version of OpenTelemetry we were using: https://github.com/kubernetes/kubernetes/issues/113791

KEP-647: Update Api Server Tracing to 1.27 for beta

---

keps/sig-instrumentation/383-new-event-api-ga-graduation/README.md
keps/sig-instrumentation/383-new-event-api-ga-graduation/kep.yaml

The issue for KEP-383 can't be closed although the KEP has graduated to stable because all the Kubernetes components haven't been migrated to use the new API. The actual migration is a big effort that needs to be properly planned and as such would be better handled in a seperate KEP. There are also some changes that needs to be considered in order to not break existing behaviors. As such, the plan is to remove the migration from KEP-383's scope and instead do it as part of [KEP-3728](https://github.com/kubernetes/enhancements/issues/3728).
Fixes #383 
/cc @logicalhan @ehashman 

Update KEP-383 graduation criterias

---

keps/prod-readiness/sig-api-machinery/3352.yaml
keps/sig-api-machinery/3352-aggregated-discovery/README.md
keps/sig-api-machinery/3352-aggregated-discovery/kep.yaml

- One-line PR description: Update milestone aggregated discovery to beta 1.27
- Issue link: https://github.com/kubernetes/enhancements/issues/3352
/cc @apelisse @lavalamp @deads2k @alexzielenski

KEP-3352 Aggregated Discovery to Beta

---

keps/sig-api-machinery/1040-priority-and-fairness/README.md

Update GA graduation criteria: sort, make check-list, refine tuning item.
- 1. Convert to check list.
- 2. Re-order so that completed items come first.
- 3. Update tuning item to refer to the whole interface (e.g, including logs and metrics) rather than just the API.
- 4. Update the tuning item to replace "auto-tuning" with simply "tuning".  The thinking is that the proper focus is on observability and controllabiility; automation of the tuning was always intended to be a matter for later consideration.
/cc @wojtek-t 
/cc @lavalamp 
/cc @deads2k 
/cc @tkashem 
/cc @marseel

KEP-1040: update GA graduation criteria

---

keps/sig-network/3705-cloud-node-ips/README.md
keps/sig-network/3705-cloud-node-ips/kep.yaml

- One-line PR description: initial proposal of dual-stack cloud --node-ip KEP
/sig network
/sig node
/cc @khenidak @mdbooth

KEP-3705: Cloud Dual-Stack --node-ip Handling

---

keps/sig-network/2091-admin-network-policy/README.md

- One-line PR description: Updating changes made to API types after KEP is merged.
- Issue link: https://github.com/kubernetes/enhancements/pull/2522

KEP-2091: Update API types for AdminNetworkPolicy and BaselineAdminNetworkPolicy

---

keps/sig-scheduling/2926-job-mutable-scheduling-directives/README.md

- One-line PR description: update mutable scheduling directives KEP to follow the new test template
- Issue link: #2926

Updated mutable scheduling directives to adhere to the new test template

---

keps/sig-network/2681-pod-host-ip/kep.yaml

KEP-2681: Target to alpha for 1.27

---

keps/sig-apps/3329-retriable-and-non-retriable-failures/README.md

- One-line PR description: Update the KEP with testgrid links for e2e tests
- included typo fixes as a separate commit

Testgrid links to e2e tests for "KEP-3329: Retriable and non-retriable Pod failures for Jobs"

---

keps/prod-readiness/sig-network/3705.yaml
keps/sig-network/3705-cloud-node-ips/README.md
keps/sig-network/3705-cloud-node-ips/kep.yaml

- One-line PR description: update KEP-3705 to implementable, including addressing a few comments Tim left while approving the original PR
I think this still needs a sig-cloud-provider approver. @andrewsykim ?
(I don't think it necessarily needs a sig-node approval though even though it involves changes to kubelet?)
/sig network

KEP-3705: update CloudNodeIPs to implementable

---

keps/sig-apps/1847-autoremove-statefulset-pvcs/README.md
keps/sig-apps/1847-autoremove-statefulset-pvcs/kep.yaml

- Update KEP #1847 status for beta graduation
- Other comments: No changes are necessary for beta. This KEP was almost ready for beta in 1.26, but needs more e2e test soak time as the statefulset e2e tests were not being run in alpha clusters since cloud provider extraction / CSI migration (see also https://github.com/kubernetes/kubernetes/issues/114955).
/cc @msau42 
/cc @johnbelamaric

1847: 1.27 beta update

---

keps/sig-node/2400-node-swap/kep.yaml

/sig node
- One-line PR description: NodeSwap feature update for 1.27 release - target alpha2.
No changes in scope, last time the KEP was scheduled we didn't have enough people to work on it.
- Issue link: #2400 
Issue is already tracked for milestone 1.27
/assign @dchen1107

Update the release for alpha2

---

keps/sig-api-machinery/3488-cel-admission-control/README.md

- One-line PR description: This updates KEP-3488 as necessary for the inclusion of `string.format` in CEL/cel-go, changing some examples and adding a bit of extra relevant information.
- Issue link:

KEP-3488: Adjust for inclusion of string.format in CEL

---

keps/sig-network/3458-remove-transient-node-predicates-from-service-controller/README.md
keps/sig-network/3458-remove-transient-node-predicates-from-service-controller/kep.yaml

- One-line PR description: This KEP proposes a generalized and more dynamic mechanism for load balancers to health check cluster nodes, and subsequently, more efficiently and robustly react to transient cluster events.
/sig network

KEP-3458: Remove transient node predicates from KCCM's service controller

---

keps/prod-readiness/sig-scheduling/3521.yaml
keps/sig-scheduling/3521-pod-scheduling-readiness/README.md
keps/sig-scheduling/3521-pod-scheduling-readiness/kep.yaml

- One-line PR description: graduate PodSchedulingReadiness to beta

KEP-3521: Graduate PodSchedulingReadiness to beta

---

keps/prod-readiness/sig-apps/3140.yaml
keps/sig-apps/3140-TimeZone-support-in-CronJob/README.md
keps/sig-apps/3140-TimeZone-support-in-CronJob/kep.yaml

- One-line PR description: Promote CronJob's TimeZone support to GA
- Issue link: https://github.com/kubernetes/enhancements/issues/3140
/assign @smarterclayton

KEP 3140: Promote CronJob's TimeZone support to GA

---

keps/prod-readiness/sig-node/3673.yaml
keps/sig-node/3673-kubelet-parallel-image-pull-limit/README.md
keps/sig-node/3673-kubelet-parallel-image-pull-limit/kep.yaml

Signed-off-by: ruiwen-zhao <ruiwen@google.com>
- One-line PR description: This KEP proposes adding to kubelet a node-level limit on the number of parallel image pulls.

KEP-3673: Kubelet limit of Parallel Image Pulls

---

keps/prod-readiness/sig-release/3744.yaml
keps/sig-release/3744-stay-on-supported-go-versions/README.md
keps/sig-release/3744-stay-on-supported-go-versions/kep.yaml

- One-line PR description: initial draft for KEP-3744
- Issue link: https://github.com/kubernetes/enhancements/issues/3744

KEP-3744: Stay on supported go versions: initial draft

---

keps/sig-api-machinery/1040-priority-and-fairness/kep.yaml

- One-line PR description: Update GA target for API Priority and Fairness to release 1.28
- Issue link:
- Other comments: the reason is to allow time for feedback on the concurrency borrowing introduced in release 1.26.

KEP-1040: Push GA to release 1.28

---

keps/sig-cluster-lifecycle/kubeadm/3614-etcd-learner-mode/README.md

- Issue link: https://github.com/kubernetes/enhancements/issues/3614
- Other comments: the implemented PR was merged early in v1.27 release cycle. Just update the status to align.

[v1.27] update etcd-learner-mode KEP status

---

keps/sig-api-machinery/2896-openapi-v3/README.md

- One-line PR description: Fix testing plan
- Issue link: https://github.com/kubernetes/enhancements/issues/2896

KEP-2896 Fix testing plan and add additional PRR question

---

keps/sig-network/3453-minimize-iptables-restore/README.md
keps/sig-network/3705-cloud-node-ips/README.md

Update KEP-3453 (MinimizeIPTablesRestore) and KEP-3705 (CloudNodeIPs) with the new "resource leak" PRR question from the template. Neither KEP does anything especially different with sockets/PIDs/inodes relative to the current state, so it's an easy "No" for both of them.
- Issue link:
- https://github.com/kubernetes/enhancements/issues/3453
- https://github.com/kubernetes/enhancements/issues/3705
/sig network

add new template question to KEP-3453 and KEP-3705

---

keps/sig-node/127-user-namespaces/README.md
keps/sig-node/127-user-namespaces/kep.yaml

- One-line PR description: Change the implementation to rely on idmap mounts. This simplifies the implementation in kubernetes and container runtimes and removes several limitations we hit before
- Issue link: #127 
- Other comments: We did a prototype implementation on container runtimes (containerd, runc, CRIO, crun) with @giuseppe and we didn't find anything unexpected.
The change to make this KEP about only stateless pods was discussed last year in sig-node and when we asked for an exception for the 1.25 release (https://groups.google.com/g/kubernetes-sig-release/c/ASWlhA-tIxE/m/mMWeXx_kAwAJ). The first commits of this PR just update the KEP to be about stateless pods, as was agreed, the rest of the commits re-work the KEP to rely on idmap mounts.
cc @thockin @mrunalp @derekwaynecarr …

KEP-127: Support userns in stateless pods with idmap mounts

---

keps/sig-network/1880-multiple-service-cidrs/README.md
keps/sig-network/1880-multiple-service-cidrs/kep.yaml

During the implementation some assumptions were found to be different, per example, the kubernetes.default Service logic and the bootstrap process can not be changed without breaking compatibility
Ref https://github.com/kubernetes/enhancements/issues/1880#issuecomment-1419243520

KEP-1880: updating KEP

---

keps/prod-readiness/sig-cli/2590.yaml
keps/sig-cli/2590-kubectl-subresource/README.md
keps/sig-cli/2590-kubectl-subresource/kep.yaml

**One-line PR description**:
We’ve received good feedback for this feature and would like to move it to beta in v1.27. Some examples of feedback:
- https://github.com/kubernetes/kubernetes/pull/99556#issuecomment-1180903789 
- https://github.com/kubernetes/kubectl/issues/564#issuecomment-1369618455 
- https://twitter.com/thockin/status/1545530559073423360 
**Issue link:** https://github.com/kubernetes/enhancements/issues/2590
/assign @soltysh 
cc @MadhavJivrajani

KEP-2590: graduate kubectl subresource support to beta

---

keps/prod-readiness/sig-node/2727.yaml
keps/sig-node/2727-grpc-probe/README.md
keps/sig-node/2727-grpc-probe/kep.yaml

/sig node
/sig network
- One-line PR description: promoting grpc probes to GA
- Issue link: #2727 
- Feedback from gRPC community was positive: https://www.youtube.com/watch?v=-ruuY5F-rE8
- More examples of implementation: https://github.com/GoogleCloudPlatform/microservices-demo/pull/1102 & https://medium.com/google-cloud/grpc-health-probes-with-kubernetes-1-24-b5bd26253a4c
The feature is ready for wide adoption

2727 - promote grpc probes to GA

---

keps/prod-readiness/sig-auth/3299.yaml
keps/sig-auth/3299-kms-v2-improvements/README.md
keps/sig-auth/3299-kms-v2-improvements/kep.yaml

Signed-off-by: Anish Ramasekar <anish.ramasekar@gmail.com>
Co-authored-by: Mo Khan <i@monis.app>
- Update [KEP](https://github.com/kubernetes/enhancements/tree/master/keps/sig-auth/3299-kms-v2-improvements) for beta
fixes https://github.com/kubernetes/kubernetes/issues/114318

KEP-3299: Update kmsv2 kep for beta

---

keps/sig-api-machinery/3488-cel-admission-control/kep.yaml

- One-line PR description: Update kep.yaml for CEL admission control (ValidatingAdmissionPolicy) to reflect that alpha work will continue to be merged in 1.27
Work planned for 1.27:
- https://github.com/kubernetes/enhancements/pull/3732
- https://github.com/kubernetes/enhancements/pull/3669
- https://github.com/kubernetes/enhancements/pull/3697
- https://github.com/kubernetes/enhancements/pull/3812
- https://github.com/kubernetes/enhancements/pull/3736

Update kep.yaml for 1.27

---

keps/prod-readiness/sig-cli/3638.yaml
keps/sig-cli/2379-kubectl-plugins/kep.yaml
keps/sig-cli/3638-built-in-command-shadowing/README.md
keps/sig-cli/3638-built-in-command-shadowing/kep.yaml

Enable shadowing built-in commands by external plugins. This KEP proposes an extension to https://github.com/kubernetes/enhancements/tree/master/keps/sig-cli/2379-kubectl-plugins
- Issue link: https://github.com/kubernetes/enhancements/issues/3638
Draft implementation of the proposal https://github.com/kubernetes/kubernetes/pull/113299

KEP-3638: Enable built-in command shadowing by plugins

---

keps/sig-apps/3329-retriable-and-non-retriable-failures/README.md
keps/sig-apps/3329-retriable-and-non-retriable-failures/kep.yaml

- One-line PR description: Update graduation criteria for GA
- Main changes:
- proposal to modify Kubelet to transition into Failed scheduled Pending pods which are Terminating (and with finalizer)
- refreshed GA graduation criteria

Update for second Beta with GA criteria for "KEP-3329: Retriable and non-retriable Pod failures for Jobs"

---

keps/prod-readiness/sig-scheduling/3838.yaml
keps/sig-scheduling/3838-pod-mutable-scheduling-directives/README.md
keps/sig-scheduling/3838-pod-mutable-scheduling-directives/kep.yaml

- One-line PR description: pod mutable scheduling directives
- Issue link:  https://github.com/kubernetes/enhancements/issues/3838

Pod Mutable Scheduling Directives

---

keps/prod-readiness/sig-apps/3017.yaml
keps/sig-apps/3017-pod-healthy-policy-for-pdb/README.md
keps/sig-apps/3017-pod-healthy-policy-for-pdb/kep.yaml

- One-line PR description: Promote unhealthyPodEvictionPolicy for PDBs to Beta

KEP-3017: Promote unhealthyPodEvictionPolicy for PDBs to Beta

---

keps/sig-api-machinery/3488-cel-admission-control/README.md

- One-line PR description: Add proposed design for secondary authz via CEL validation policies.
- Other comments: This is a fork of https://github.com/kubernetes/enhancements/pull/3812

KEP-3488: Secondary authz for CEL admission control

---

keps/prod-readiness/sig-node/2053.yaml
keps/sig-node/2053-downward-api-hugepages/README.md
keps/sig-node/2053-downward-api-hugepages/kep.yaml

- One-line PR description: We now graduate the DownwardAPIHugePages feature to stable.
- Issue link: https://github.com/kubernetes/enhancements/issues/2053
- Other comments: PTAL @kubernetes/sig-node-pr-reviews

KEP-2053: Graduate DownwardAPIHugePages feature to stable

---

keps/prod-readiness/sig-storage/3756.yaml
keps/sig-storage/3756-volume-reconstruction/README.md
keps/sig-storage/3756-volume-reconstruction/kep.yaml

- One-line PR description: Add volume reconstruction KEP.
Note to reviewers: **We're going directly to beta**, because we had alpha phase in https://github.com/kubernetes/enhancements/issues/1710 and we realized that VolumeManager rework is useful outside of the SELinux feature.
/sig storage

KEP-3756: Add volume reconstruction KEP

---

keps/prod-readiness/sig-network/2593.yaml
keps/sig-network/2593-multiple-cluster-cidrs/README.md
keps/sig-network/2593-multiple-cluster-cidrs/kep.yaml

Adds a PRR for KEP-2593 to graduate to beta

PRR for 2593-multiple-cluster-cidrs

---

keps/prod-readiness/sig-storage/3762.yaml
keps/sig-storage/3762-persistent-volume-last-phase-transition-time/README.md
keps/sig-storage/3762-persistent-volume-last-phase-transition-time/kep.yaml

PersistentVolume last phase transition time
- Issue link:
https://github.com/kubernetes/enhancements/issues/3762

KEP-3762: PersistentVolume last phase transition time

---

keps/prod-readiness/sig-node/2413.yaml
keps/sig-node/2413-seccomp-by-default/README.md
keps/sig-node/2413-seccomp-by-default/kep.yaml

- One-line PR description: We now graduate `SeccompDefault` to stable by basically making the feature enabled by default.
- Issue link: https://github.com/kubernetes/enhancements/issues/2413
- Other comments: PTAL @mrunalp @kubernetes/sig-node-pr-reviews

KEP-2413: Graduate SeccompDefault to stable

---

keps/sig-api-machinery/3488-cel-admission-control/README.md

This PR fills out the expression composition/lazy eval section on KEP-3488 (CEL for Admission Control).
- Issue link:
Original KEP: https://github.com/kubernetes/enhancements/tree/master/keps/sig-api-machinery/3488-cel-admission-control

KEP-3488: Add information on expression composition

---

keps/prod-readiness/sig-node/693.yaml
keps/sig-node/693-topology-manager/README.md
keps/sig-node/693-topology-manager/kep.yaml

- One-line PR description: KEP-693: Graduate Kubelet Topology Manager to GA
- Issue link: https://github.com/kubernetes/enhancements/issues/693#issuecomment-1401799352
1. Initial Proposal to community repo: https://github.com/kubernetes/community/pull/1680
2. Proposal to the enhancement repo: https://github.com/kubernetes/enhancements/pull/781
3. KEP:  https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/693-topology-manager

KEP-693: Graduate Kubelet Topology Manager to GA

---

keps/prod-readiness/sig-node/606.yaml
keps/sig-node/606-compute-device-assignment/README.md
keps/sig-node/606-compute-device-assignment/kep.yaml

- One-line PR description: handle missing bits to graduate podresources API to GA
- Issue link: https://github.com/kubernetes/enhancements/issues/3743
The PR is organized as follows:
1. first, we move back the KEP to GA to be able to do the missing fixes, see [here](https://groups.google.com/g/kubernetes-sig-architecture/c/v4OwOaBkvVc/m/xdfLryLTGQAJ) for context
2. adapt to the most recent KEP template adding the PRR information
3. mechanical translation from the older document format to the newest available at moment of writing. Care is taken to alter as little as possible the original content, with the only purpose to make it fit in the new format
4. add all the new information not required when the original document was written, mostly concern with the PRR reviews.

KEP-606: finalize podresources API GA graduation

---

keps/prod-readiness/sig-api-machinery/3716.yaml
keps/sig-api-machinery/3716-webhook-predicates/README.md
keps/sig-api-machinery/3716-webhook-predicates/kep.yaml

Introduce a webhook `predicate` concept. A predicate is a CEL expression which must evaluate to `true` for a request to be sent to a webhook.
Tracking issue: https://github.com/kubernetes/enhancements/issues/3716
This PR proposes an alternative (though not mutually exclusive) approach to https://github.com/kubernetes/enhancements/pull/3694.
This is based on a similar proposal for ValidatingAdmissionPolicy: https://github.com/kubernetes/enhancements/pull/3697
/cc @ivelichkovich @maxsmythe @jpbetz @andrewsykim

KEP-3716: Admission Webhook Match Conditions

---

keps/prod-readiness/sig-node/3619.yaml
keps/sig-node/3619-supplemental-groups-policy/README.md
keps/sig-node/3619-supplemental-groups-policy/kep.yaml

- One-line PR description: the first draft of the KEP. This proposes a new API surface to control how supplemental groups are applied in the container
- k/k issue: https://github.com/kubernetes/kubernetes/issues/112879
- Other comments: __This needs to update CRI API and will impact CRI implementations. I'm not sure how I proceed to implement it. I really appreciated some comments/guidance from active/experienced contributors.__

KEP-3169: Fine-grained SupplementalGroups control

---

keps/prod-readiness/sig-node/3085.yaml
keps/sig-node/3085-pod-conditions-for-starting-completition-of-sandbox-creation/README.md
keps/sig-node/3085-pod-conditions-for-starting-completition-of-sandbox-creation/kep.yaml

- One-line PR description: Update KEP with PodReadyToStartContainers condition and updating milestone for Beta 
- Issue link: https://github.com/kubernetes/enhancements/issues/3085
- Other comments: This KEP updates the name of the condition to PodReadyToStartContainers (from the previous PodHasNetwork that sig-network had concerns with) as previously discussed with sig-node and sig-network leads. The description of the condition and goals are updated accordingly.

Update KEP with PodReadyToStartContainers condition for Beta

---

keps/prod-readiness/sig-instrumentation/2831.yaml
keps/sig-instrumentation/2831-kubelet-tracing/README.md
keps/sig-instrumentation/2831-kubelet-tracing/kep.yaml

- updates to KEP-2831 to track connected traces in kubelet and beta graduation
/cc @dashpole 
/cc @saschagrunert 
/cc @vrutkovs

KEP-2831: adding beta graduation criteria

---

keps/prod-readiness/sig-node/753.yaml
keps/sig-node/753-sidecar-containers/README.md
keps/sig-node/753-sidecar-containers/kep.yaml

- One-line PR description: This is sidecar containers KEP
- Issue link: #3759 
- original document: https://docs.google.com/document/d/1hRBa_tnxpldKyEVPzMe2xZ3Q-Uq3uKK5bcBREJGTzeE/edit#
/sig node
/cc @matthyx @jpbetz 
/cc @derekwaynecarr @thockin @mrunalp

Sidecar containers KEP

---

keps/prod-readiness/sig-network/3836.yaml
keps/sig-network/3836-kube-proxy-improved-ingress-connectivity-reliability/README.md
keps/sig-network/3836-kube-proxy-improved-ingress-connectivity-reliability/kep.yaml

- One-line PR description: This KEP proposes a more reliably mechanism for handling ingress connectivity for endpoints on terminating nodes and for endpoints on nodes with un-healthy Kube-proxies. 
/sig network
/assign @thockin @danwinship

KEP-3836: Improve Kube-proxy ingress connectivity reliability

---

keps/prod-readiness/sig-instrumentation/1748.yaml
keps/sig-instrumentation/1748-pod-resource-metrics/README.md
keps/sig-instrumentation/1748-pod-resource-metrics/kep.yaml

This PR update the state of KEP-1748 to stable and set the milestone to 1.27.
We won't be able to update the status of the KEP to `implemented` until metrics are updated to Stable, but they first need to be BETA.
- Issue link: #1748
The graduation criteria from BETA to GA is:
> Stability over two releases demonstrating cardinality is reasonable and the metrics remain valuable
The metrics have been in Kubernetes since 1.20 so although there are not exposed on the main kube-scheduler endpoint, they've been around for 7 releases already. During that period of time no cardinality explosion has been reported and the metrics are starting to be more widely used:
- https://github.com/kubernetes/kube-state-metrics/pull/1849
- …

KEP-1748: update to stable

---

keps/prod-readiness/sig-node/3695.yaml
keps/sig-node/3695-pod-resources-for-dra/README.md
keps/sig-node/3695-pod-resources-for-dra/kep.yaml

Signed-off-by: Moshe Levi <moshele@nvidia.com>
Extend pod resource API to for Dynamic Resource Allocation 
- Issue link:
https://github.com/kubernetes/enhancements/issues/3695

KEP-3695: extend pod resource API to for DRA

---

keps/prod-readiness/sig-autoscaling/1610.yaml
keps/sig-autoscaling/1610-container-resource-autoscaling/README.md
keps/sig-autoscaling/1610-container-resource-autoscaling/kep.yaml

- One-line PR description: update KEP to graduate the container resource metric to beta
- Issue link: https://github.com/kubernetes/enhancements/issues/1610
Other comments: 
- KEP-1610 was written in an old KEP template. So this PR needs to add lots of sections.
- This PR implies we need to change the implementation on the HPA controller a bit. 
- Collected the action items here: https://github.com/kubernetes/kubernetes/issues/115467

KEP-1610: update KEP to graduate the container resource metric to beta

---

keps/prod-readiness/sig-storage/3107.yaml
keps/sig-storage/3107-csi-nodeexpandsecret/README.md
keps/sig-storage/3107-csi-nodeexpandsecret/kep.yaml

- Issue link: https://github.com/kubernetes/enhancements/issues/3107
https://github.com/kubernetes/kubernetes/pull/115451

KEP-3107: target csiNodeExpandSecret beta in 1.27

---

keps/sig-api-machinery/3488-cel-admission-control/README.md

- One-line PR description: Update the CEL admission KEP to support graceful policy rollout by adding ability to report validation failures only as warnings or audit annotations and for enhancing metrics to container the information needed to monitor a rollout.
- Issue link: #3492

KEP-3488: CEL admission: Add graceful rollout, warning and audit support

---

keps/sig-node/2053-downward-api-hugepages/README.md

Just a formal requirement to fulfill enhancements tracking.
PTAL @mrunalp 
Refers to https://github.com/kubernetes/enhancements/issues/2053

KEP-2053 Update test plan for DownwardAPIHugePages

---

keps/sig-auth/2718-20210511-client-exec-proxy/kep.yaml

- One-line PR description: Client exec proxy KEP alpha in 1.27
- Issue link: https://github.com/kubernetes/enhancements/pull/2693

KEP-2718 Client exec proxy alpha in 1.27

---

keps/prod-readiness/sig-security/3203.yaml
keps/sig-security/3203-auto-refreshing-official-cve-feed/README.md
keps/sig-security/3203-auto-refreshing-official-cve-feed/kep.yaml

- One-line PR description: Updated graduation criteria and implementation details for alpha to beta changes
- Issue link: #3203 
- Other comments: related parent issue https://github.com/kubernetes/sig-security/issues/1

KEP-3203: Alpha->Beta Graduation Updates

---

keps/sig-cloud-provider/2699-add-webhook-hosting-to-ccm/kep.yaml

- One-line PR description: Modify kep.yaml to reflect alpha implementation in 1.27. 
- Issue link: [2699 add webhook hosting to ccm](https://github.com/kubernetes/enhancements/tree/master/keps/sig-cloud-provider/2699-add-webhook-hosting-to-ccm)

KEP-2699: Webhook KEP alpha in 1.27

---

keps/sig-node/606-compute-device-assignment/README.md

- One-line PR description: clarify GA blockers as requested in the KEP review
- Issue link: https://github.com/kubernetes/enhancements/issues/3743
Clarify GA blockers as asked in
https://github.com/kubernetes/enhancements/pull/3791#pullrequestreview-1290171354 https://github.com/kubernetes/enhancements/pull/3791#issuecomment-1423409601
1. Explicitely added windows support (and all the other platforms supported by device plugins) as GA condition.
1. Added DOS prevention as GA condition, and clarified the perimeter of the DOS attack surface area.

KEP-606: clarify GA blockers

---

keps/sig-node/3619-supplemental-groups-policy/README.md

- One-line PR description: Update Test Plan and Graduation Criteria for KEP freeze.
- criteria is described in [#3619(comment)](https://github.com/kubernetes/enhancements/issues/3619#issuecomment-1419252937)
- done in 922b5f67c76eed7b5fe7168002531c513426e937
- done in 1166c604b184374d3215e9b8dc0cb05afb3e18ec
- done in 3ccb75d2d4704d4f1991c4d48dc03c10a7b69331
- already done in the previous PR(#3620)
- PRR review has already been done in https://github.com/kubernetes/enhancements/pull/3620#issuecomment-1423402770

KEP-3619: update Test Plan and Graduation Criteria for KEP freeze

---

keps/prod-readiness/sig-cli/3805.yaml
keps/sig-cli/3805-ssa-default/README.md
keps/sig-cli/3805-ssa-default/kep.yaml

- One-line PR description: KEP attempts to provide a path toward having server-side apply enabled by default in kubectl.
- Issue link: https://github.com/kubernetes/enhancements/issues/3805
- Other comments: Very drafty for now, I haven't included any of the design, mostly went for the PRR section.
Also note that the "feature" doesn't quite fit the KEP process, we went with the KEP route as a good way to get tracking, discussion, risk, mitigation, test and design, but the alpha/beta/stable don't really make much sense for a client-side flag.

KEP-3805: Server-side apply by default in kubectl

---

keps/sig-cli/3638-built-in-command-shadowing/README.md

This PR renames KEP-3638 to `Improve kubectl plugin resolution for non-shadowing subcommands` to make it more descriptive.
/cc @soltysh

KEP-3638: Rename KEP-3638

---

keps/sig-cli/2379-kubectl-plugins/kep.yaml
keps/sig-cli/3638-kubectl-plugin-subcommands/README.md
keps/sig-cli/3638-kubectl-plugin-subcommands/kep.yaml

This PR renames the left overs from https://github.com/kubernetes/enhancements/pull/3876

More rename KEP-3638

---

keps/sig-node/2413-seccomp-by-default/README.md

- One-line PR description: Reaction on https://github.com/kubernetes/enhancements/issues/2413#issuecomment-1429969732
Reading this again I think it was clear from original text. Clarifying anyway to make it clear from the first read =).
- Issue link: #2413 
/sig node

seccomp: updated text clarifying that enabled by default doesn't mean the flag will be enabled, only feature gate

---

keps/sig-storage/1487-csi-migration-aws/kep.yaml

- One-line PR description: Mark the feature as `implemented`
- Issue link: https://github.com/kubernetes/enhancements/issues/1487

KEP-1487: Mark AWS EBS CSI migration as done

---

keps/sig-node/3673-kubelet-parallel-image-pull-limit/README.md

Sync logic with the implementation https://github.com/kubernetes/kubernetes/pull/115220.
/cc @ruiwen-zhao @dchen1107 @SergeyKanzhelev

KEP-3673 update: parallel pull defaulting and validation logics according to the merged PR

---

keps/sig-multicluster/2149-clusterid/README.md

- One-line PR description: Goal section predated final decisions to not allow this in general; see also [README.md#not-allowing-cluster-specific-targeting-via-dns](https://github.com/kubernetes/enhancements/blob/master/keps/sig-multicluster/1645-multi-cluster-services-api/README.md#not-allowing-cluster-specific-targeting-via-dns)
- Issue link: #2149 
- Other comments: cc and thank you @runakash for the catch :)

KEP-2149: Update goals section re: cluster-level DNS

---

keps/sig-storage/3756-volume-reconstruction/README.md
keps/sig-storage/3756-volume-reconstruction/kep.yaml

- One-line PR description: Rename metrics to better match other kubelet `total`/`_error_total` metrics.
See https://github.com/kubernetes/kubernetes/pull/115965 for implementation of the metrics

Rename volume reconstruction metrics

---

keps/sig-node/3619-supplemental-groups-policy/README.md

- One-line PR description: This PR is a follow-up PR to https://github.com/kubernetes/enhancements/pull/3862#issuecomment-1424933789.

KEP-3619: Cleanup After Freeze

---

keps/sig-api-machinery/1040-priority-and-fairness/README.md

- One-line PR description: Catch up with initial implementation of borrowing in APF
- Issue link:
- Other comments: This PR does two things to make the KEP match what actually transpired as we completed implementation of borrowing in APF.  One is to note the field renaming in `v1beta3`.  The other is to correct the setting of the smoothing decay coefficient.

KEP-1040: Catch up with initial implementation of borrowing in APF

---

keps/sig-multicluster/1645-multi-cluster-services-api/README.md
keps/sig-multicluster/1645-multi-cluster-services-api/specification.md
keps/sig-multicluster/2149-clusterid/README.md

Extend the specification to allow the implementations to format cluster id in a way that unambiguously identifies a cluster within a clusterset.
- Issue link:
- https://github.com/kubernetes/enhancements/tree/master/keps/sig-multicluster/1645-multi-cluster-services-api
- https://github.com/kubernetes/enhancements/tree/master/keps/sig-multicluster/2149-clusterid
- More context: https://docs.google.com/document/d/15spskKz9yNYczuvVrihq9xSsIkcj96aGeFAnRQO896k/edit
- Standardize the definitions of cluster id and cluster name.
- Standardize the format to „cluster id” (in different places called „clusterID”, „cluster ID” or „cluster id”).

KEP-1645, KEP-2149: Location-disambiguated addressing of Headless service pods

---

keps/sig-storage/3762-persistent-volume-last-phase-transition-time/README.md
keps/sig-storage/3762-persistent-volume-last-phase-transition-time/kep.yaml

- Issue link: https://github.com/kubernetes/enhancements/issues/3762

set PersistentVolumeLastPhaseTransitionTime feature for alpha in v1.28

---

keps/sig-network/3685-endpointslice-reconciler-to-staging/README.md
keps/sig-network/3685-endpointslice-reconciler-to-staging/kep.yaml

- One-line PR description: Move EndpointSlice Reconciler into Staging
- Issue link: https://github.com/kubernetes/enhancements/issues/3685

KEP-3685: Move EndpointSlice Reconciler into Staging

---

keps/sig-network/3705-cloud-node-ips/README.md
keps/sig-network/3705-cloud-node-ips/kep.yaml

- One-line PR description: Update KEP-3705 to simplify what we will do in 1.27.
While starting to implement the new dual-stack cloud `--node-ip` behavior, I realized that the constraint of preserving backward-compatible behavior for all existing `--node-ip` values means that you can't express certain things in some clusters, depending on the set of NodeAddresses provided by the cloud. (See the commit for an example.)
There are various things we could do about this, but it's too late to debate them in the 1.27 cycle. However, we know that we want to support explicit-dual-stack IPs on clouds; we know _how_ we want to support it (using the same syntax we use for bare metal); and we know there are already …

KEP-3705: simplify initial alpha, discuss possible changes to plan

---

keps/prod-readiness/sig-auth/3325.yaml
keps/sig-auth/3325-self-subject-attributes-review-api/README.md
keps/sig-auth/3325-self-subject-attributes-review-api/kep.yaml

Signed-off-by: m.nabokikh <maksim.nabokikh@flant.com>
Beta graduation

KEP-3325: Promote SelfSubjectReview to Stable

---

keps/sig-windows/2258-node-log-query/README.md
keps/sig-windows/2258-node-log-query/kep.yaml

- One-line PR description: Update node  log query
- Update the kep to reflect the decisions made at the sig-archictecture call on Feb 9th, 2023 and the current implementation status.
- Rename the KEP to reflect the name of the feature

2258: Update node log query

---

keps/sig-api-machinery/2876-crd-validation-expression-language/README.md
keps/sig-api-machinery/2876-crd-validation-expression-language/kep.yaml

- One-line PR description: Promote CRD validation rules to stable

KEP-2876: Clear Graduation Criteria for CRD validation rules to stable

---

keps/sig-api-machinery/1281-network-proxy/kep.yaml

- One-line PR description: Clarify that status is beta; introduce GA criteria.
- Issue link: https://github.com/kubernetes/enhancements/issues/1281
This KEP has been a bit dormant, but the Konnectivity Proxy has had several rounds of bugfixes, and recent [releases](https://github.com/kubernetes-sigs/apiserver-network-proxy/tags) have a good operational track record. We should graduate it from beta to GA, especially since ssh tunnels support is removed.

KEP-1281: Clarify beta status.

---

keps/sig-node/606-compute-device-assignment/README.md
keps/sig-node/606-compute-device-assignment/kep.yaml

- One-line PR description: move GA version from 1.27 to 1.28 to address the few pending work items
- Issue link: https://github.com/kubernetes/enhancements/issues/3743

node: podresources: GA in 1.28

---

keps/sig-auth/3299-kms-v2-improvements/kep.yaml

- update stable milestone for KMSv2 to `v1.29`

update stable milestone for KMSv2 to v1.29

---

keps/prod-readiness/sig-network/3705.yaml
keps/sig-network/3705-cloud-node-ips/README.md
keps/sig-network/3705-cloud-node-ips/kep.yaml

- One-line PR description: update KEP-3705 `CloudDualStackNodeIPs` to beta, dropping the parts that were not implemented in alpha
This drops the parts of the KEP that weren't implemented for alpha (`--node-ip IPv4` / `--node-ip IPv6`, and renaming the `alpha.kubernetes.io/provided-node-ip` annotation), and moves some of the old text to the "Alternatives" section explaining what we didn't do and why.

KEP-3705: update CloudDualStackNodeIPs to beta

---

keps/sig-network/1669-proxy-terminating-endpoints/kep.yaml

It skipped 1.27 but it will go GA for 1.28

update release for GA for KEP 1699

---

keps/sig-apps/3329-retriable-and-non-retriable-failures/README.md
keps/sig-apps/3329-retriable-and-non-retriable-failures/kep.yaml

- One-line PR description: KEP update for the next iteration of Beta 1.28
- fix the omission and add DisruptionTarget condition to pods preempted by Kubelet to make room for critical pods. POC PR: https://github.com/kubernetes/kubernetes/pull/117586
- Cherrypicks: 
- 1.26: https://github.com/kubernetes/kubernetes/pull/118221
- 1.27: https://github.com/kubernetes/kubernetes/pull/118219

Beta update for Kubelet preemption (1.28) "KEP-3329: Retriable and non-retriable Pod failures for Jobs" 

---

keps/prod-readiness/sig-instrumentation/3498.yaml
keps/sig-instrumentation/3498-extending-stability/README.md
keps/sig-instrumentation/3498-extending-stability/kep.yaml

- We are going to graduate "extending metrics stability" to GA.
- Issue link:
- https://github.com/kubernetes/enhancements/issues/3498

add GA requirement for extending metrics stability

---

keps/prod-readiness/sig-cli/1440.yaml
keps/sig-cli/1440-kubectl-events/README.md
keps/sig-cli/1440-kubectl-events/kep.yaml

- One-line PR description: promote kubectl events to stable
- Issue link: https://github.com/kubernetes/enhancements/issues/1440
/assign @soltysh @eddiezane 
for sig-cli review
for prr review

KEP-1440: Promote kubectl events command to stable

---

OWNERS_ALIASES

This PR updates this owners file to match https://github.com/kubernetes/community/blob/master/sig-cloud-provider/README.md#leadership (which was updated in April in https://github.com/kubernetes/community/pull/7251)
Updating SIG Cloud Provider leads
Lazy consensus back in April: https://groups.google.com/g/kubernetes-sig-cloud-provider/c/BAh7gGZhfvo
/assign @mrbobbytables

Updating SIG Cloud Provider leads

---

keps/prod-readiness/sig-apps/3850.yaml
keps/sig-apps/3850-backoff-limits-per-index-for-indexed-jobs/README.md
keps/sig-apps/3850-backoff-limits-per-index-for-indexed-jobs/kep.yaml

- One-line PR description: Support for executing all indexes in case of failures using backoff limit per Index
- superseeds: https://github.com/kubernetes/enhancements/pull/3774

Backoff limit per Job Index

---

keps/prod-readiness/sig-api-machinery/3716.yaml
keps/sig-api-machinery/3716-admission-webhook-match-conditions/README.md
keps/sig-api-machinery/3716-admission-webhook-match-conditions/kep.yaml

- One-line PR description: Add beta milestone for AdmissionWebhookMatchConditions
- Issue link: https://github.com/kubernetes/enhancements/issues/3716

KEP-3716: add beta milestone for AdmissionWebhookMatchConditions

---

OWNERS_ALIASES
keps/sig-node/2043-pod-resource-concrete-assigments/kep.yaml
keps/sig-node/2403-pod-resources-allocatable-resources/kep.yaml
keps/sig-node/2625-cpumanager-policies-thread-placement/kep.yaml
keps/sig-node/2902-cpumanager-distribute-cpus-policy-option/kep.yaml
keps/sig-node/3063-dynamic-resource-allocation/kep.yaml
keps/sig-node/3327-align-by-socket/kep.yaml
keps/sig-node/3545-improved-multi-numa-alignment/kep.yaml
keps/sig-node/3695-pod-resources-for-dra/kep.yaml
keps/sig-node/606-compute-device-assignment/kep.yaml
keps/sig-node/OWNERS

/sig node
This PR will extend the approvers pool for KEPs from 2 to 3 people.
The approach suggested is inconsistent with other SIGs, but aligned with the charter document: https://github.com/kubernetes/community/blob/master/committee-steering/governance/sig-governance.md#tech-lead. I brought it to the steering committee meeting this Monday, and there were no concerns with the approach. I'd let steering committee to decide whether this needs to be applied to other SIGs.

Make SIG Node tech leads to approve KEPs

---

keps/prod-readiness/sig-api-machinery/3488.yaml
keps/sig-api-machinery/3488-cel-admission-control/README.md
keps/sig-api-machinery/3488-cel-admission-control/kep.yaml

- One-line PR description: Clear beta graduation criteria for CEL in Admission Control

KEP-3488: promote validatingadmissionpolicy to beta

---

keps/prod-readiness/sig-node/3673.yaml
keps/sig-node/3673-kubelet-parallel-image-pull-limit/README.md
keps/sig-node/3673-kubelet-parallel-image-pull-limit/kep.yaml

- One-line PR description: Promote Parallel Image Pull Limit to Beta

KEP-3673: Promote Parallel Image Pull Limit to Beta

---

keps/sig-node/753-sidecar-containers/README.md
keps/sig-node/753-sidecar-containers/kep.yaml

/sig node
moving sidecar container KEP to 1.28
- Issue link: #753 
No changes to scope or design

move sidecar to milestone 1.28

---

keps/sig-network/2433-topology-aware-hints/README.md
keps/sig-network/2433-topology-aware-hints/kep.yaml

KEP-2433: add new heuristic to topology routing
- Issue link: https://github.com/kubernetes/enhancements/issues/2433
This simplify the existing heuristic that is based on CPUs cores because is difficult to get it working on deployments where the law of large numbers can not help with the statistics.
Add a new heuristic to only PreferZone, ie. traffic will be directed to the endpoints in the same zone if exist, or fall back to cluster wide routing if there are no endpoints in the zone
As a side benefit of this new heuristic, we can abstract the topology using an interface that will help with the KEP https://github.com/kubernetes/enhancements/issues/3685 to stage the endpointslice controller.

KEP-2433: add new heuristic to topology routing

---

keps/prod-readiness/sig-api-machinery/2340.yaml
keps/sig-api-machinery/2340-Consistent-reads-from-cache/README.md
keps/sig-api-machinery/2340-Consistent-reads-from-cache/kep.yaml

cc @wojtek-t @deads2k @mborsz @logicalhan 
Reviving the KEP and picking up previously abandoned approach to use `WatchProgressRequest`. Reason is that it allows us to drop the dependency on etcd configuration. This leaves us with problem of making apiserver aware of etcd version.
Issue https://github.com/kubernetes/enhancements/issues/2340
Original proposal: https://github.com/kubernetes/enhancements/pull/1404

Revive 2340 Consistent reads from cache KEP

---

keps/sig-node/1287-in-place-update-pod-resources/kep.yaml

- One-line PR description: This PR keeps in-place pod resize KEP in implementable/alpha state for v1.28 as per request from release management.

KEP-1287: Keep in-place pod resize KEP alpha/implementatle for v1.28

---

keps/prod-readiness/sig-storage/2268.yaml
keps/sig-storage/2268-non-graceful-shutdown/README.md
keps/sig-storage/2268-non-graceful-shutdown/kep.yaml

This PR moves non-graceful node shutdown feature to GA.
- Issue link: https://github.com/kubernetes/enhancements/issues/2268

KEP-2268: move non-graceful node shutdown to GA

---

keps/prod-readiness/sig-auth/3331.yaml
keps/sig-auth/3331-structured-config-for-oidc-authentication/README.md
keps/sig-auth/3331-structured-config-for-oidc-authentication/kep.yaml

- One-line PR description: Structured config for OIDC authentication
- Other comments: -

KEP-3331: Structured Authentication Config

---

keps/sig-storage/1790-recover-resize-failure/README.md
keps/sig-storage/1790-recover-resize-failure/kep.yaml

- One-line PR description: updating milestone
- Issue link: https://github.com/kubernetes/enhancements/issues/1790
- Other comments:  `ExpandPersistentVolumes` was GAed in 1.24 and removed in 1.27. https://github.com/kubernetes/kubernetes/pull/113942

update kep-1790 for milestone 1.28

---

keps/sig-storage/2924-csi-migration-cephfs/kep.yaml

- One-line PR description: updating milestone 
- Issue link: https://github.com/kubernetes/enhancements/issues/2924
- Other comments: [Deprecation of intree CephFS driver in 1.28](https://groups.google.com/g/kubernetes-sig-storage/c/IlHnIpwTbEg)

KEP-2923 Deprecation of intree CephFS driver in 1.28

---

keps/sig-node/127-user-namespaces/README.md

now that we use idmapped mounts, there is no real difference between stateful and stateless pods, and they can be handled in the same way.
Refers to https://github.com/kubernetes/enhancements/issues/127

KEP-127: add support for stateful pods

---

keps/prod-readiness/sig-cli/3895.yaml
keps/sig-cli/3895-kubectl-delete-interactivity/README.md
keps/sig-cli/3895-kubectl-delete-interactivity/kep.yaml

- One-line PR description: Add interactive(-i) flag to kubectl delete command that will ask confirmation to user to proceed
- Issue link: https://github.com/kubernetes/enhancements/issues/3895
- Other comments: https://github.com/kubernetes/kubernetes/pull/114530

KEP-3895: kubectl delete: Add interactive(-i) flag

---

keps/prod-readiness/sig-instrumentation/2305.yaml
keps/sig-instrumentation/2305-metrics-cardinality-enforcement/README.md
keps/sig-instrumentation/2305-metrics-cardinality-enforcement/kep.yaml

- One-line PR description: Update KEP-2305: Metric cardinality enforcement based on the reviews received on #2305 to continue the effort further.
- Issue link: #2305

KEP-2305: Metric cardinality enforcement

---

keps/sig-node/3063-dynamic-resource-allocation/kep.yaml

- One-line PR description: confirm that work continues as alpha in 1.28

KEP-3063: dra: continue as alpha in 1.28

---

keps/sig-node/2400-node-swap/README.md
keps/sig-node/2400-node-swap/kep.yaml

- One-line PR description: Graduate swap to Beta 1

KEP-2400: Graduate swap to Beta 1

---

keps/sig-node/127-user-namespaces/README.md
keps/sig-node/127-user-namespaces/kep.yaml

This KEP update outlines the required changes for Pod Security Standards in relation to the User Namespaces support. We plan to release another alpha version of this feature in 1.28, so no graduation to beta yet.
Refers to https://github.com/kubernetes/enhancements/issues/127
PTAL @giuseppe @rata @mrunalp @kubernetes/sig-auth-feature-requests

[KEP-127] Add Pod Security Standards to User Namespaces KEP

---

keps/prod-readiness/sig-node/3545.yaml
keps/sig-node/3545-improved-multi-numa-alignment/README.md
keps/sig-node/3545-improved-multi-numa-alignment/kep.yaml

- One-line PR description: Promote Improved multi-numa alignment in Topology Manager to beta
- Issue link: https://github.com/kubernetes/enhancements/issues/3545

Promote Improved multi-numa alignment in Topology Manager to beta

---

keps/prod-readiness/sig-api-machinery/4008.yaml
keps/sig-api-machinery/4008-crd-ratcheting/README.md
keps/sig-api-machinery/4008-crd-ratcheting/kep.yaml

- One-line PR description: Adds CRD Validation Ratcheting KEP
- Issue link: https://github.com/kubernetes/enhancements/issues/4008
- Proof of Concept: https://github.com/kubernetes/kube-openapi/pull/406
/cc @cici37 @jpbetz @deads2k

KEP-4008: CRD Validation Ratcheting

---

keps/prod-readiness/sig-network/3178.yaml
keps/sig-network/3178-iptables-cleanup/kep.yaml

- One-line PR description: Move to GA in 1.28
- Issue link: https://github.com/kubernetes/enhancements/issues/3178

KEP-3178: Bump 'IPTables Ownership' to GA

---

keps/prod-readiness/sig-node/2570.yaml
keps/sig-node/2570-memory-qos/README.md
keps/sig-node/2570-memory-qos/kep.yaml

- One-line PR description: Update KEP for Beta implementation of MemoryQoS feature
- Issue link: https://github.com/kubernetes/enhancements/issues/2570 
/assign @bobbypage 
/assign @mrunalp 
/assign @pacoxu

Memory QoS Beta Update and Production Readiness

---

keps/prod-readiness/sig-node/3983.yaml
keps/sig-node/3983-drop-in-configuration/README.md
keps/sig-node/3983-drop-in-configuration/kep.yaml

- One-line PR description: Initial KEP for adding support for a drop-in kubelet configuration directory

KEP-3983: Add support for a drop-in kubelet configuration directory

---

keps/sig-auth/3257-trust-anchor-sets/README.md

List affected packages in the unit testing section.  I'm unable to reliably extract coverage data; the suggested testgrid tab is so large that it crashes my tab almost immediately after loading.
Issue link: https://github.com/kubernetes/enhancements/issues/3257

KEP-3257 (ClusterTrustBundles): Update for 1.28 freeze

---

keps/prod-readiness/sig-node/3960.yaml
keps/sig-node/3960-pod-lifecycle-sleep-action/README.md
keps/sig-node/3960-pod-lifecycle-sleep-action/kep.yaml

- One-line PR description: This KEP proposes the addition of a new sleep action for the PreStop lifecycle hook in Kubernetes, allowing containers to pause for a specified duration before termination.
- Issue link: #3960 
- Other comments:  [issue in k/k](https://github.com/kubernetes/kubernetes/issues/114465)

KEP-3960: Introducing Sleep Action for PreStop Hook

---

keps/sig-node/127-user-namespaces/README.md
keps/sig-node/127-user-namespaces/kep.yaml

- One-line PR description: The actual feature gate name is `UserNamespacesStatelessPodsSupport`, which should be reflected in the KEP as well.
- Other comments: cc @mrunalp @rata @giuseppe

KEP-127: Fix user namespaces feature gate name

---

keps/sig-api-machinery/1281-network-proxy/README.md

KEP-1281: update stale content.
- One-line PR description: fix inaccuracies and use latest terminology.
- Issue link: https://github.com/kubernetes/enhancements/issues/1281
* Separating this cleanup from work to adapt the latest KEP template.

KEP-1281: update stale content.

---

keps/sig-scheduling/3521-pod-scheduling-readiness/README.md

- One-line PR description: Add new metric for excluding `PreEnqueue` duration time
This requirement is part of the [discussion](https://github.com/kubernetes/kubernetes/issues/117979) related to excluding the PreEnquue duration time in case the pod is gated.

KEP-3521: Add new metric for excluding PreEnqueue duration time

---

keps/sig-node/3695-pod-resources-for-dra/README.md
keps/sig-node/3695-pod-resources-for-dra/kep.yaml

match API with actual implementation in 1.27
- Issue link:
https://github.com/kubernetes/enhancements/issues/3695

PodResources API for DRA: match API with actual implementation in 1.27

---

keps/sig-network/3726-standard-application-protocols/README.md

- One-line PR description: This defines websocket (`ws`) and websocket secure (`wss`) as standard protocols
- Issue link: https://github.com/kubernetes/enhancements/issues/3726
- RFC: https://www.rfc-editor.org/rfc/rfc6455

KEP-3726: Add WebSocket as a standard protocol

---

keps/sig-architecture/3935-oldest-node-newest-control-plane/README.md
keps/sig-architecture/3935-oldest-node-newest-control-plane/kep.yaml

- One-line PR description: Mark KEP-3935 as implemented
- Issue link: #3935 
/assign @dims @johnbelamaric 

KEP-3935: Mark as implemented

---

keps/sig-apps/3850-backoff-limits-per-index-for-indexed-jobs/README.md

/sig apps
- One-line PR description: Update of the KEP reflecting the decisions during the implementation review under: https://github.com/kubernetes/kubernetes/pull/118009/
- don't discuss the `message` and `reason` fields of JobFailed condition, as they were too detailed. In particular, the message will not include indexes. The indexes are already present in the FailedIndexes field in a human-readable format.
- add a Beta graduation point to evaluate performance of the Job controller as the current implementation raises some concerns which are hard to verify without actual experiment. Discussion pointers:
- https://github.com/kubernetes/kubernetes/pull/118009#discussion_r1261694406
- …

Update for KEP3850 "Backoff Limit Per Index"

---

keps/sig-auth/2799-reduction-of-secret-based-service-account-token/README.md
keps/sig-auth/2799-reduction-of-secret-based-service-account-token/kep.yaml

- One-line PR description: Add the ability for the users to recover invalid legacy service account tokens; Add the ability to allow the users to dry-run the legacy service account token cleaner.
- Issue link: -[KEP]: https://github.com/kubernetes/enhancements/tree/master/keps/sig-auth/2799-reduction-of-secret-based-service-account-token

Revise KEP 2799-reduction-of-secret-based-service-account-token for LegacyServiceaccountTokenCleanup feature.

---

keps/prod-readiness/sig-network/3668.yaml
keps/sig-network/3668-reserved-service-nodeport-range/README.md
keps/sig-network/3668-reserved-service-nodeport-range/kep.yaml

- One-line PR description:  KEP-3668: promote to stable
- Issue link: https://github.com/kubernetes/enhancements/issues/3668

promote ServiceNodePortStaticSubrange to stable

---

keps/sig-network/4004-deprecate-kube-proxy-version/README.md
keps/sig-network/4004-deprecate-kube-proxy-version/kep.yaml

One-line PR description: This KEP proposes for deprecate the `status.nodeInfo.kubeProxyVersion` field of v1.Node
Issue link: https://github.com/kubernetes/enhancements/issues/4004
Other comments: https://github.com/kubernetes/kubernetes/issues/117756

KEP-4004: Deprecate the kubeProxyVersion field of v1.Node

---

keps/sig-scheduling/3902-decoupled-taint-manager/kep.yaml

- One-line PR description:  Update KEP-3902 decoupled `taintmanger` release target to 1.29
- Issue link: https://github.com/kubernetes/enhancements/issues/3902

Update KEP-3902  decoupled taintmanager  release target to 1.29

---

keps/sig-auth/3331-structured-authentication-configuration/README.md

- rename clientIDs to audiences based on current implementation
KEP issue: https://github.com/kubernetes/enhancements/issues/3331

KEP-3331: rename clientIDs to audiences based on current impl

---

OWNERS_ALIASES

This owner alias is unsued and stale. GCP has enough representation as part of SIG Cloud Provider and there is no need for a provider-specific owner alias anymore.
- Issue link:

remove unused OWNER_ALIAS for provider-gcp

---

keps/prod-readiness/sig-storage/3762.yaml
keps/sig-storage/3762-persistent-volume-last-phase-transition-time/README.md
keps/sig-storage/3762-persistent-volume-last-phase-transition-time/kep.yaml

- One-line PR description: update KEP for PersistentVolumeLastPhaseTransitionTime feature to match actual implementation and graduate to beta
- Issue link: https://github.com/kubernetes/enhancements/issues/3762
This is a followup for discussed changes:
- https://github.com/kubernetes/kubernetes/pull/116469#discussion_r1244625032
- https://github.com/kubernetes/kubernetes/pull/116469#discussion_r1244617872

KEP-3762: graduate PersistentVolumeLastPhaseTransitionTime to beta in v1.29

---

OWNERS_ALIASES

- One-line PR description: Luke Hinds is stepping down from the SRC and this PR was originally created in #4072 as part of his offboarding but was closed. This PR also updates the alias to all current SRC members.
- Issue link: https://github.com/kubernetes/committee-security-response/issues/182

Update SRC members in OWNERS_ALIASES

---

keps/sig-node/127-user-namespaces/kep.yaml

We changed the feature flag name in 1.28, when we added support for stateful pods too.
We also want to do changes in 1.29(PSS integration with sig-auth), so update the last-milestone to that.
- One-line PR description: Update feature gate name
- Issue link: #127 
cc @giuseppe @saschagrunert @mrunalp

KEP-127: Update feature gate name and update last-milestone for 1.29

---

keps/sig-storage/3751-volume-attributes-class/README.md

- One-line PR description: Address v1.29 Enhancements team's comment
- Issue link: https://github.com/kubernetes/enhancements/issues/3751#issuecomment-1735414750
- Other comments: NA

Update Graduation Criteria for kep-3751

---

keps/prod-readiness/sig-network/4004.yaml
keps/sig-network/4004-deprecate-kube-proxy-version/README.md
keps/sig-network/4004-deprecate-kube-proxy-version/kep.yaml

- One-line PR description: KEP-4004 (deprecating `node.status.kubeProxyVersion`) got merged as "provisional" rather than "implementable". This just fixes that. (Meaning it needs PRR approval now.)
- Issue link: #4004
- KEP text link: https://github.com/kubernetes/enhancements/tree/master/keps/sig-network/4004-deprecate-kube-proxy-version

KEP-4004: change from provisional to implementable

---

keps/sig-cli/1441-kubectl-debug/README.md

- One-line PR description: As discussed [#1441](https://github.com/kubernetes/enhancements/issues/1441#issuecomment-1484966305) and [k/k #118962](https://github.com/kubernetes/kubernetes/issues/118962), I've update netadmin profile to add CAP_NET_RAW and remove privileged.

KEP-1441: Update netadmin profile to add CAP_NET_RAW and remove privileged

---

keps/sig-network/2593-multiple-cluster-cidrs/README.md
keps/sig-network/2593-multiple-cluster-cidrs/kep.yaml

- One-line PR description: https://groups.google.com/g/kubernetes-sig-network/c/nts1xEZ--gQ/m/2aTOUNFFAAAJ

KEP 2593: withdrawn cluster-cidr kep

---

keps/sig-node/2570-memory-qos/README.md
keps/sig-node/2570-memory-qos/kep.yaml

- One-line PR description: Updating Memory QoS status to eventually deprecate the alpha feature  in K8s 1.30
- Issue link: https://github.com/kubernetes/enhancements/issues/2570

KEP-2570: Updating Memory QoS status to eventually deprecate the alpha feature 

---

keps/sig-auth/3299-kms-v2-improvements/kep.yaml

- Update [KEP](https://github.com/kubernetes/enhancements/tree/master/keps/sig-auth/3299-kms-v2-improvements) for GA
/sig auth
/assign enj

KEP-3299: Update KMSv2 kep stage to stable

---

keps/prod-readiness/sig-apps/3850.yaml
keps/sig-apps/3850-backoff-limits-per-index-for-indexed-jobs/README.md
keps/sig-apps/3850-backoff-limits-per-index-for-indexed-jobs/kep.yaml

- One-line PR description: Update the KEP for Beta graduation for Backoff Limit Per Index

Update KEP-3850 "Backoff Limit Per Index" for Beta

---

keps/sig-node/3960-pod-lifecycle-sleep-action/kep.yaml

We didn't get the code changes of KEP 3960 merged in v1.28, but the pr in k/k is ready to review now, and we hopefully can see this feature in v1.29.
- Issue link: https://github.com/kubernetes/enhancements/issues/3960

Track KEP 3960 in v1.29

---

keps/sig-node/3673-kubelet-parallel-image-pull-limit/README.md
keps/sig-node/3673-kubelet-parallel-image-pull-limit/kep.yaml

xref https://github.com/kubernetes/enhancements/issues/3673
this is planned to be promoted to beta in v1.28.
We have no time to add the e2e test cases, and so we postponed to promote to beta to v1.29
- The PRR review was already passed in https://github.com/kubernetes/enhancements/pull/4036 by @wojtek-t

update kubelet parallel image pull limit for v1.29

---

keps/prod-readiness/sig-node/727.yaml
keps/sig-node/727-resource-metrics-endpoint/README.md
keps/sig-node/727-resource-metrics-endpoint/kep.yaml

- One-line PR description: Migrate KEP to latest template, mark requirements for beta and GA release  as checked 
- Issue link: https://github.com/kubernetes/enhancements/issues/727#issuecomment-1536876872

Update KEP for Kubelet Resource Metrics endpoint GA release

---

keps/prod-readiness/sig-apps/2879.yaml
keps/sig-apps/2879-ready-pods-job-status/README.md
keps/sig-apps/2879-ready-pods-job-status/kep.yaml

- Issue link: https://github.com/kubernetes/enhancements/issues/2879

Graduate KEP-2879 PodsReady to stable

---

keps/sig-instrumentation/2305-metrics-cardinality-enforcement/kep.yaml

Same change for beta milestone as well.

kep-2305: bump `latest-milestone` to `v1.29`

---

keps/sig-auth/3221-structured-authorization-configuration/README.md

Updating the KEP contents based on what we have been discussing and implementing over the pas month.
/assign @ritazh @liggitt @enj 
/sig auth

3221: update KEP according to 1.29 requirements

---

keps/prod-readiness/sig-network/3836.yaml
keps/sig-network/3836-kube-proxy-improved-ingress-connectivity-reliability/README.md
keps/sig-network/3836-kube-proxy-improved-ingress-connectivity-reliability/kep.yaml

- One-line PR description: 1.29 milestone bump for KEP - 3836
/sig network

[KEP 3836]: Bump to beta for 1.29

---

keps/prod-readiness/sig-api-machinery/4192.yaml
keps/sig-api-machinery/4192-svm-in-tree/README.md
keps/sig-api-machinery/4192-svm-in-tree/kep.yaml

- One-line PR description: Move [Storage Version Migrator](https://github.com/kubernetes-sigs/kube-storage-version-migrator) in-tree.

KEP-4192: Move Storage Version Migrator in-tree

---

keps/prod-readiness/sig-node/3983.yaml
keps/sig-node/3983-drop-in-configuration/README.md
keps/sig-node/3983-drop-in-configuration/kep.yaml

- One-line PR description: Updates target for KEP to beta in 1.29

KEP 3983: target to beta for 1.29

---

keps/prod-readiness/sig-node/3085.yaml
keps/sig-node/3085-pod-conditions-for-starting-completition-of-sandbox-creation/README.md
keps/sig-node/3085-pod-conditions-for-starting-completition-of-sandbox-creation/kep.yaml

- One-line PR description: Promote KEP 3085 to beta in 1.29.
- Issue link: https://github.com/kubernetes/enhancements/issues/4138

KEP-3085: promote to beta in 1.29

---

keps/sig-auth/3299-kms-v2-improvements/README.md

- Update [KEP](https://github.com/kubernetes/enhancements/tree/master/keps/sig-auth/3299-kms-v2-improvements) to compare metrics
/sig auth
/assign enj
Fixes https://github.com/kubernetes/kubernetes/issues/120883

KEP-3299: Update KMSv2 kep to compare metrics

---

keps/sig-node/2400-node-swap/README.md
keps/sig-node/2400-node-swap/kep.yaml

- One-line PR description: Graduate swap to beta 2 after fulfing the set criteria. 

Graduate swap to beta 2 in 1.29

---

keps/prod-readiness/sig-auth/3926.yaml
keps/sig-auth/3926-handling-undecryptable-resources/README.md
keps/sig-auth/3926-handling-undecryptable-resources/kep.yaml

- One-line PR description:  Improve the identification of resources that won't decrypt. Make it possible to remove undecryptable resources by using the API.
- Issue link: https://github.com/kubernetes/enhancements/issues/3926
- Other comments: https://github.com/kubernetes/kubernetes/issues/86489

KEP-3926: handling undecryptable resources

---

keps/prod-readiness/sig-node/4191.yaml
keps/sig-node/4191-split-image-filesystem/README.md
keps/sig-node/4191-split-image-filesystem/kep.yaml

- One-line PR description: KEP for Split Filesystem
- Issue link: #4191 

KEP-4191 Split Image Filesystem

---

keps/sig-node/1029-ephemeral-storage-quotas/README.md
keps/sig-node/1029-ephemeral-storage-quotas/kep.yaml

#1029: Quotas for Ephemeral Storage
- One-line PR description: re-promote LocalStorageCapacityIsolationFSQuotaMonitoring feature to beta
- Issue link: https://github.com/kubernetes/enhancements/issues/1029
- Other comments: https://github.com/kubernetes/enhancements/issues/1029#issuecomment-1413045741
This is discussed in recent sig-node meetings.
- The last promote PR: https://github.com/kubernetes/enhancements/pull/2697, and I think this feature is almost meets the beta bar. 
- https://testgrid.k8s.io/sig-node-kubelet#kubelet-gce-e2e-fsquota-ubuntu : test grid was added.
- -  the blocker is fixed in https://github.com/kubernetes/kubernetes/pull/115314.
**Pros:** 
- without this feature, du in some scenarios will hang or take too much time. 
- metrics were added …

[v1.29] ephemeral-storage-quotas: repromote to beta

---

keps/prod-readiness/sig-cli/3895.yaml
keps/sig-cli/3895-kubectl-delete-interactivity/README.md
keps/sig-cli/3895-kubectl-delete-interactivity/kep.yaml

- One-line PR description: Promote `--interactive` flag in kubectl delete command to beta
- Issue link: https://github.com/kubernetes/enhancements/issues/3895

KEP-3895: Promote interactive flag in delete command to beta

---

keps/prod-readiness/sig-node/4210.yaml
keps/sig-node/4210-max-image-gc-age/README.md
keps/sig-node/4210-max-image-gc-age/kep.yaml

Add Kubelet option to specify the maximum age an image will be kept around before it is garbage collected
- Issue link: https://github.com/kubernetes/enhancements/issues/4210

KEP-4210: Add ImageGCMaximumAge KEP

---

keps/sig-api-machinery/4006-transition-spdy-to-websockets/README.md
keps/sig-api-machinery/4006-transition-spdy-to-websockets/kep.yaml

* Updates WebSockets KEP to reflect the latest understandings
* Updates references from `v1.28` to `v1.29`
* Updates description of new `RemoteCommand` version (`v5.channel.k8s.io`) to reflect the latest design.
* Removes all mention of `PortForward` until the design is added.

Update WebSocket KEP (4006) to reflect latest understanding

---

keps/prod-readiness/sig-node/753.yaml
keps/sig-node/753-sidecar-containers/README.md
keps/sig-node/753-sidecar-containers/kep.yaml

- One-line PR description: add PRR questionnaire answers for beta
- Issue link: https://github.com/kubernetes/enhancements/issues/753

KEP-753: add PRR questionnaire answers for beta

---

keps/prod-readiness/sig-api-machinery/4008.yaml
keps/sig-api-machinery/4008-crd-ratcheting/README.md
keps/sig-api-machinery/4008-crd-ratcheting/kep.yaml

- One-line PR description: Targets CRD Validation Ratcheting Beta for 1.29. Adds updates and further discussion about weakened form of ratcheting for beta.
- Issue link: https://github.com/kubernetes/enhancements/issues/4008
/cc @sttts @apelisse @jpbetz

KEP-4008: target CRD Ratcheting beta to 1.29

---

keps/sig-node/2535-ensure-secret-pulled-images/README.md
keps/sig-node/2535-ensure-secret-pulled-images/kep.yaml

Signed-off-by: Mike Brown [brownwm@us.ibm.com](mailto:brownwm@us.ibm.com)
One-line PR description: bump kep release targets since the PR for the approved kep did not merge in time... and a request to do beta discussed persistence was made in review.
https://github.com/kubernetes/kubernetes/pull/94899
Issue link: https://github.com/kubernetes/enhancements/issues/2535
Merged kep.. https://github.com/kubernetes/enhancements/pull/1608

#2535:ensure secret pulled images - move kep targets; add persist

---

keps/prod-readiness/sig-node/4216.yaml
keps/sig-node/4216-image-pull-per-runtime-class/README.md
keps/sig-node/4216-image-pull-per-runtime-class/kep.yaml

- One-line PR description: Adding new KEP for supporting image pull per runtime class
- Issue link: https://github.com/kubernetes/enhancements/issues/4216
- Other comments: This KEP was discussed in SIG-Windows and Kubelet GC WorkGroup and sig-nodes slack group.

4216: Image pull per runtime class KEP

---

keps/prod-readiness/sig-node/4188.yaml
keps/sig-node/4188-kubelet-pod-readiness-api/README.md
keps/sig-node/4188-kubelet-pod-readiness-api/kep.yaml

- One-line PR description: Proposal for new kubelet gRPC API with endpoint returning local pods information
- Issue link: https://github.com/kubernetes/enhancements/issues/4188

KEP-4188: New kubelet gRPC API with endpoint returning local pods information

---

keps/sig-node/1287-in-place-update-pod-resources/kep.yaml

- One-line PR description: This PR keeps in-place pod resize KEP in implementable/alpha state for v1.29 as per request from release management.
Issue link: https://github.com/kubernetes/enhancements/issues/1287
We build a list to work on here. https://github.com/kubernetes/enhancements/issues/1287#issuecomment-1738222727 and will update the KEP if needed.

KEP-1287: Keep in-place pod resize KEP alpha/implementable for v1.29

---

keps/prod-readiness/sig-network/3866.yaml
keps/sig-network/3866-nftables-proxy/README.md
keps/sig-network/3866-nftables-proxy/kep.yaml

Initial KEP proposing a kube-proxy nftables mode.
- Issue link:
https://github.com/kubernetes/enhancements/issues/3866
```
The default kube-proxy implementation on Linux is currently based on
iptables. IPTables was the preferred packet filtering and processing
system in the Linux kernel for many years (starting with the 2.4
kernel in 2001). However, problems with iptables led to the
development of a successor, nftables, first made available in the 3.13
kernel in 2014, and growing increasingly featureful and usable as a
replacement for iptables since then. Development on iptables has
mostly stopped, with new features and performance improvements
primarily going into nftables instead.
This KEP proposes the creation of a new official/supported …
```

KEP-3866: kube-proxy nftables mode

---

keps/sig-network/2433-topology-aware-hints/kep.yaml

- One-line PR description: As @npolshakova pointed out, our metadata for this KEP is out of date, this fixes that.
- Other comments: We're not making any changes to the KEP in this cycle, just trying to get the implementation to catch up to the KEP.
/sig network

KEP-2433: Bumping stable target to 1.30

---

docs/glossary.md

**Which issue(s) this PR fixes**:
Updating links from old github project (https://github.com/orgs/kubernetes/projects/13) to new github project (https://github.com/orgs/kubernetes/projects/169)
/assign @dims

Update API review project links

---

keps/sig-network/0752-endpointslices/README.md

Fix redundance words for the endpointslice describe.
- Issue link:

Fix redundance words for the endpointslice describe.

---

keps/sig-node/3063-dynamic-resource-allocation/README.md

120421: interaction with unexpected node shutdown KEP
- One-line PR description: Added a section about handling non graceful node shutdowns (see https://github.com/kubernetes/enhancements/tree/master/keps/sig-storage/2268-non-graceful-shutdown for more details
- Other comments: see https://github.com/kubernetes/enhancements/tree/master/keps/sig-storage/2268-non-graceful-shutdown for more details

DRA: handle non graceful node shutdowns

---

keps/sig-cluster-lifecycle/kubeadm/4214-separate-super-user-kubeconfig/README.md
keps/sig-cluster-lifecycle/kubeadm/4214-separate-super-user-kubeconfig/kep.yaml

Update notes about Risk and Mitigations:
- As a mistaken existing implementation detail "admin.conf" is not shared across control plane nodes, by using the "kubeadm-certs" Secret. Instead on "kubeadm join --control-plane" a new "admin.conf" is signed by using the shared in "kubeadm-certs" CA.
- Re-place upgrade clusters must apply the "kubeadm:cluster-admins" ClusterRoleBinding if they wish the "admin.conf" files on joining control plane nodes to have "cluster-admin" level access.
Update Test Plan:
- Don't add integration tests, instead add an e2e test using kinder that will do kubeadm init/join/upgrade and verify certificates stored in kubeconfig files nad RBAC.
- Issue link:
https://github.com/kubernetes/enhancements/issues/4214

keps/../kubeadm: 4214: revisit test plan and risks/mitigations

---

keps/sig-network/3726-standard-application-protocols/README.md

- One-line PR description: Update Standard Protocol KEP with latest HTTP/2 RFC - 
- Other comments: Since H2C upgrade flow is [deprecated](https://datatracker.ietf.org/doc/html/rfc9113#:~:text=The%20%22h2c%22%20string,%C2%B6) be more specific that we want to support HTTP/2 prior knowledge

Update HTTP/2 RFC - be specific about using http/2 prior

---

OWNERS_ALIASES

Part of resolving https://github.com/kubernetes/community/issues/7572.
Add @MikeZappa87 as well, as at least for the time being we're going to continue to fallback on chairs for enhancements leadership, and also move DCBW to emeritus leads.

docs: add dan winship as signet tech lead

---

keps/sig-apps/3850-backoff-limits-per-index-for-indexed-jobs/README.md

- One-line PR description: Update KEP3850 "BackoffLimitPerIndex for Indexed Jobs"
- Other comments: Updated e2e tests and benchmark tests.

Update KEP3850 "BackoffLimitPerIndex for Indexed Jobs"

---

keps/sig-api-machinery/555-server-side-apply/README.md
keps/sig-auth/1205-bound-service-account-tokens/README.md
keps/sig-cloud-provider/2390-reporting-conformance-test-results-to-testgrid/README.md
keps/sig-cloud-provider/2392-cloud-controller-manager/README.md
keps/sig-cloud-provider/providers/2530-alibaba-cloud/README.md
keps/sig-cloud-provider/providers/2531-baidu-cloud/README.md
keps/sig-cluster-lifecycle/kubeadm/3614-etcd-learner-mode/README.md
keps/sig-instrumentation/1602-structured-logging/README.md
keps/sig-network/1024-nodelocal-cache-dns/README.md
keps/sig-node/1539-hugepages/README.md
keps/sig-node/2043-pod-resource-concrete-assigments/README.md
keps/sig-node/606-compute-device-assignment/README.md
keps/sig-node/727-resource-metrics-endpoint/README.md
keps/sig-node/757-pid-limiting/README.md
keps/sig-scheduling/1258-default-pod-topology-spread/README.md
keps/sig-scheduling/1923-prefer-nominated-node/README.md
keps/sig-storage/2264-csi-release-ci-process/README.md
keps/sig-storage/3107-csi-nodeexpandsecret/README.md
keps/sig-storage/559-volume-subpath-expansion/README.md
keps/sig-storage/625-csi-migration/README.md
keps/sig-windows/1301-windows-runtime-class/README.md

What type of PR is this?
/kind cleanup
What this PR does / why we need it:
Which issue(s) this PR fixes:
Fix links to the test grid dashboard
Related Umbrella Issue https://github.com/kubernetes/test-infra/issues/30370

migrate testgrid dashboard URL from k8s-testgrid.appspot.com to testgrid.k8s.io

---

keps/sig-auth/2907-secrets-store-csi-driver/kep.yaml
keps/sig-etcd/4326-downgrade/kep.yaml
keps/sig-etcd/4331-livez-readyz/kep.yaml
keps/sig-network/2829-gateway-api-to-k8s-io/kep.yaml
pkg/kepval/approval.go
pkg/repo/validate.go

Improve validation of KEP metadata by ensuring that:
- implementable/implemented tests are providing stage and milestone
- KEPs has an associated metadata file
- fix few KEPs not passing improved validation
/assign @johnbelamaric @dims

Improve validation for KEP metadata

---

keps/sig-apps/2307-job-tracking-without-lingering-pods/README.md

- One-line PR description: add a known failure mode and mention that this feature is GA so disabling is not really an option.
- Issue link: #2307 

KEP-2307: add known failure modes

---

keps/sig-node/4205-psi-metric/README.md

- One-line PR description: markdown and Go formatting fixes for KEP-4025
- Issue link: https://github.com/kubernetes/enhancements/issues/4205

KEP-4025: several formatting fixes

---

README.md

This PR adds links two tracking boards of both 1.29 and 1.30 in the `README.md`.
- Issue link:
There is no issue for this
This PR is created following the documentation in https://github.com/kubernetes/sig-release/blob/master/release-team/role-handbooks/enhancements/README.md#week-0

Add enhancement tracking board links for both 1.29 and 1.30

---

OWNERS_ALIASES

- 1.27 shadow reviews: [6](https://github.com/orgs/kubernetes/projects/117/views/2?filterQuery=prr-shadow%3Ajpbetz)
- 1.28 shadow reviews: [9](https://github.com/orgs/kubernetes/projects/140/views/2?filterQuery=prr-shadow%3Ajpbetz)
- 1.29 - did not shadow due to time constraints with new SIG API Machinery TL role
- 1.30+ contribute to PRR, able to review roughly 12 KEPs per release.  I am happy to PRR more than 12 so long as they are SIG API Machinery KEPs, since I'll be reviewing those anyway..
Transitions from new to alpha
- https://github.com/kubernetes/enhancements/issues/3983
- PR reviewed: https://github.com/kubernetes/enhancements/pull/4031
- https://github.com/kubernetes/enhancements/pull/4031#pullrequestreview-1480170879
- …

Add jpbetz to prod-readiness-approvers

---

keps/sig-api-machinery/3157-watch-list/README.md

correct description about cacherWatcher channel.
- Issue link:
incoming chan is a property of Cacher and input chan is a property of cacheWatcher

KEP-3157: correct description of cachewatcher channel

---

keps/prod-readiness/sig-api-machinery/4358.yaml
keps/sig-api-machinery/4358-custom-resource-field-selectors/README.md
keps/sig-api-machinery/4358-custom-resource-field-selectors/kep.yaml

- One-line PR description: Add field selector support to CustomResourceDefinitions.
- Issue link: https://github.com/kubernetes/enhancements/issues/4358
Implementation: https://github.com/kubernetes/kubernetes/pull/122717

KEP: Custom Resource Field Selectors

---

keps/sig-network/3836-kube-proxy-improved-ingress-connectivity-reliability/kep.yaml

- One-line PR description: update beta and stable milestones
- Other comments: the KEP was transitioned to beta in 1.29,[ but annoyingly I forgot to update the feature gate in Kube](https://github.com/kubernetes/kubernetes/blob/v1.29.0/pkg/features/kube_features.go#L1109), so it actually never transitioned to beta in 1.29. I am therefore updating all milestones in this KEP update.  
/sig network
/cc @thockin @aojea

KEP 3836 - v1.30 updates - update beta/stable milestones 

---

keps/sig-apps/3329-retriable-and-non-retriable-failures/README.md

- One-line PR description: update according to latest decisions, no implementation changes needed in the cycle
1. keep SSA independent of the graduation cycle for pod failure policy
2. drop the idea of https://github.com/kubernetes/kubernetes/issues/116858

KEP-3329 pod failure policy update for 1.30

---

keps/sig-storage/3756-volume-reconstruction/README.md

- One-line PR description: Update the enhancement with the actual implementation. Metric name was changed to fit other kubelet metrics.
Link to the metric definition: https://github.com/kubernetes/kubernetes/blob/55f1e21fdc71ae47a51e2e78c2f72d6a5952491e/pkg/kubelet/metrics/metrics.go#L117-L118
cc @xing-yang @msau42

3746: Update orphaned pod metrics name

---

OWNERS_ALIASES

/sig node
reverting https://github.com/kubernetes/enhancements/pull/4344#issuecomment-1917607836 for sig node.
SIG Node uses this alias for enhancements.

added sig-node-tech-leads alias back to OWNER_ALIASES

---

keps/sig-node/127-user-namespaces/README.md

- One-line PR description: We decided to drop those security context fields from the integration in https://github.com/kubernetes/kubernetes/pull/118760. The KEP is now updated to reflect that.
- Other comments: PTAL @rata @mrunalp @giuseppe

KEP-127: Update KEP to reflect integration state

---

keps/sig-node/4438-sidecar-restart-termination/README.md
keps/sig-node/4438-sidecar-restart-termination/kep.yaml
keps/sig-node/753-sidecar-containers/README.md

- One-line PR description: introduce a second feature flag for restarting sidecars during pod termination
- Issue link: 
- https://github.com/kubernetes/enhancements/issues/753; 
- https://github.com/kubernetes/enhancements/issues/4438

KEP-753: introduce a second KEP and gate for restarts during pod termination

---

keps/prod-readiness/sig-api-machinery/3716.yaml
keps/sig-api-machinery/3716-admission-webhook-match-conditions/README.md
keps/sig-api-machinery/3716-admission-webhook-match-conditions/kep.yaml

Updates testing/metrics information and stages KEP for GA in 1.30.
- Issue link: https://github.com/kubernetes/enhancements/issues/3716 

KEP-3716: graduate to stable for 1.30

---

keps/sig-api-machinery/3157-watch-list/README.md

- One-line PR description: Adds an additional beta criterion for the `WatchList` feature.

KEP 3157 (watch-list): add a new beta criterion

---

keps/sig-storage/1710-selinux-relabeling/README.md
keps/sig-storage/1710-selinux-relabeling/kep.yaml

- One-line PR description: Keep the existing ROWP functionality as beta, and start Phase 2 of SELinux mount as alpha (i.e. all other PV access modes).
@gnufied @msau42 @xing-yang

Start SELinuxMount alpha

---

keps/sig-storage/1790-recover-resize-failure/kep.yaml

Change latest milestone for recover from volume expansion feature.
https://github.com/kubernetes/enhancements/issues/1790
Since this feature is staying in alpha, I am not updating the existing PRR, since it hasn't changed yet.

Change proposed milestone for recover from resize failure KEP

---

keps/sig-node/3983-drop-in-configuration/README.md
keps/sig-node/3983-drop-in-configuration/kep.yaml

- One-line PR description: Updates target for KEP to beta in 1.30

KEP-3983: target to beta for 1.30

---

keps/sig-node/3673-kubelet-parallel-image-pull-limit/README.md
keps/sig-node/3673-kubelet-parallel-image-pull-limit/kep.yaml

- One-line PR description: promoting to beta is pending to v1.30 due to PR is still in review https://github.com/kubernetes/kubernetes/pull/121604(waiting for reviewing and approval)
- Other comments: just update the kep version to meet the plan/progress.

postponed kep-3673 parallel image pull limit to v1.30 for beta

---

keps/sig-auth/3331-structured-authentication-configuration/README.md

- Update [KEP](https://github.com/kubernetes/enhancements/tree/master/keps/sig-auth/3331-structured-authentication-configuration/README.md) to add `AudienceMatchPolicy`
Slack conversation: https://kubernetes.slack.com/archives/C04UMAUC4UA/p1705511911467009

KEP-3331: add audienceMatchPolicy to authentication config

---

keps/prod-readiness/sig-scheduling/3521.yaml
keps/prod-readiness/sig-scheduling/3838.yaml
keps/sig-scheduling/3521-pod-scheduling-readiness/README.md
keps/sig-scheduling/3521-pod-scheduling-readiness/kep.yaml
keps/sig-scheduling/3838-pod-mutable-scheduling-directives/README.md
keps/sig-scheduling/3838-pod-mutable-scheduling-directives/kep.yaml

- One-line PR description: graduate PodSchedulingReadiness to stable
- Issue link: #3521 #3838
- Other comments: This PR graduates two KEPs (3521 and 3838) to stable as they're both controlled by the same feature gate `PodSchedulingReadiness`

KEP 3521/3838: graduate PodSchedulingReadiness to stable

---

keps/prod-readiness/sig-architecture/4402.yaml
keps/sig-architecture/4402-go-workspaces/README.md
keps/sig-architecture/4402-go-workspaces/kep.yaml
keps/sig-architecture/4402-go-workspaces/v2-experiment.md

- One-line PR description: First draft
- Issue link: #4402 
The main Kubernetes git repo (github.com/kubernetes/kubernetes, colloquially
called "k/k") is the empdiment of evolution.  When it was created, the only
way to build Go applications was GOPATH.  Over time we built tooling which
understood GOPATH, and it leaked into many parts of our build, test, and
release systems.  Then Go added modules, in part because GOPATH was unpleasant
and had a tendency to leak into tools.  We adopted modules, but we also added
the idea of "staging" repositories - a way to eat our cake and have, too.  We
get the benefits of a monorepo (atomic commits, fast iteration across repos)
and then publish those to standalone repos for downstream consumption.  To make
this work with modules, we abused GOPATH even …

KEP 4402: Go workspaces for k/k (first draft)

---

keps/sig-storage/2589-csi-migration-portworx/README.md
keps/sig-storage/2589-csi-migration-portworx/kep.yaml

This commit adds the details to the KEP for promoting Portworx CSI migration to Beta on-by-default on v1.31
One-line PR description: Update KEP for Portworx CSI Migration
Issue link: Portworx file in-tree to CSI driver migration #https://github.com/kubernetes/enhancements/issues/2589
/sig storage
One-line PR description:
Issue link:

Promote Portworx CSI migration to Beta in 1.31

---

keps/sig-node/2535-ensure-secret-pulled-images/README.md
keps/sig-node/2535-ensure-secret-pulled-images/kep.yaml

- One-line PR description: kep-2535: not persist on disk and add PullImageSecretRecheckDuration flag to define different behaviors
- Issue link: https://github.com/kubernetes/enhancements/issues/2535
- Other comments: discussions in sig-node and  https://github.com/kubernetes/kubernetes/pull/114847
/cc @mikebrow @haircommander 
/assign @derekwaynecarr  @dchen1107

kep-2535: not persist on disk and add PullImageSecretRecheckDuration flag to define different behaviors

---

keps/prod-readiness/sig-node/3960.yaml
keps/sig-node/3960-pod-lifecycle-sleep-action/README.md
keps/sig-node/3960-pod-lifecycle-sleep-action/kep.yaml

Promote KEP-3960 to beta in 1.30
- Issue link: https://github.com/kubernetes/enhancements/issues/3960
Works will be done for beta
1. Add additional e2e test cases.
2. Add one metric

KEP-3960: promote to beta in 1.30

---

keps/sig-node/1287-in-place-update-pod-resources/kep.yaml

- One-line PR description: Keep KEP up-to-date. There're few issues need to be resolved in v1.30

KEP-1287: Keep in-place pod resize KEP alpha/implementable for v1.30

---

keps/sig-node/4205-psi-metric/README.md
keps/sig-node/4205-psi-metric/kep.yaml

- One-line PR description: This KEP lays the initial foundations to use PSI metrics for setting Node Conditions.
- Issue link: https://github.com/kubernetes/enhancements/issues/4205

KEP-4205: updating the milestone for alpha to 1.30

---

keps/sig-node/1287-in-place-update-pod-resources/README.md

- One-line PR description: fix a typo in documentation on `InPlacePodVerticalScaling`
- Other comments: this a really, really small patch

fix: InPlacePodVerticalScaling typo

---

keps/sig-node/4369-allow-special-characters-environment-variable/README.md
keps/sig-node/4369-allow-special-characters-environment-variable/kep.yaml

- One-line PR description: Allow special characters in environment variables
- Issue link: https://github.com/kubernetes/enhancements/issues/4369

Allow almost all printable ASCII characters in environment variables

---

keps/prod-readiness/sig-network/3705.yaml
keps/sig-network/3705-cloud-node-ips/README.md
keps/sig-network/3705-cloud-node-ips/kep.yaml

- One-line PR description: bump to GA
nothing interesting to report since Beta. "It works." (It's being used in OpenShift at least.)

KEP-3705: CloudDualStackNodeIPs to GA

---

keps/prod-readiness/sig-apps/4368.yaml
keps/sig-apps/4368-support-managed-by-label-for-batch-jobs/README.md
keps/sig-apps/4368-support-managed-by-label-for-batch-jobs/kep.yaml

- One-line PR description: Proposes Job API label for Multi-Kueue
- Issue link: https://github.com/kubernetes/enhancements/issues/4368

KEP-4368: Job API managed-by label

---

keps/prod-readiness/sig-network/784.yaml
keps/sig-network/784-kube-proxy-component-config/README.md
keps/sig-network/784-kube-proxy-component-config/kep.yaml

- One-line PR description: Updated template with PRR Questionnaire
- Issue link: https://github.com/kubernetes/enhancements/issues/784

KEP-784: Update design-details

---

keps/sig-node/3085-pod-conditions-for-starting-completition-of-sandbox-creation/kep.yaml

- One-line PR description: Updating latest milestone to reflect some work needed in 1.30
- Issue link: #3085 
Its not really clear if we really need this as all we did is merge a e2e test for this feature in 1.30. for tracking purposes I bumped this.

[KEP-3085] update kep to say its being worked on in 1.30

---

keps/prod-readiness/sig-cli/1441.yaml
keps/sig-cli/1441-kubectl-debug/README.md
keps/sig-cli/1441-kubectl-debug/kep.yaml

- One-line PR description: This PR promotes `kubectl debug` to stable. In reality, this promotion seems like a more paperwork because  `kubectl debug` has been used for nearly more than 3 years and this is a sufficient time to collect feedback, incorporate changes and add unit, integration tests(https://github.com/kubernetes/kubernetes/blob/master/test/cmd/debug.sh)

Promote kubectl debug to GA

---

keps/prod-readiness/sig-cli/3895.yaml
keps/sig-cli/3895-kubectl-delete-interactivity/README.md
keps/sig-cli/3895-kubectl-delete-interactivity/kep.yaml

- One-line PR description: Promote interactive flag in kubectl delete command to stable
- Issue link: https://github.com/kubernetes/enhancements/issues/3895

KEP-3895: Promote interactive delete to stable

---

keps/prod-readiness/sig-scheduling/3022.yaml
keps/sig-scheduling/3022-min-domains-in-pod-topology-spread/README.md
keps/sig-scheduling/3022-min-domains-in-pod-topology-spread/kep.yaml

- One-line PR description: graduate Pod Topology Spread MinDomains to stable
- Issue link: https://github.com/kubernetes/enhancements/issues/3022

KEP-3022: graduate Pod Topology Spread MinDomains to stable

---

keps/prod-readiness/sig-storage/3756.yaml
keps/sig-storage/3756-volume-reconstruction/README.md
keps/sig-storage/3756-volume-reconstruction/kep.yaml

- One-line PR description: Graduate NewVolumeManagerReconstruction to GA
- Update to a new KEP template (one extra PRR question).
- Update what has been done.
cc @msau42

Graduate NewVolumeManagerReconstruction GA

---

keps/prod-readiness/sig-auth/4193.yaml
keps/sig-auth/4193-bound-service-account-token-improvements/README.md
keps/sig-auth/4193-bound-service-account-token-improvements/kep.yaml

- One-line PR description: Updating KEP milestone

KEP-4193: Update milestone for v1.30 & clarify latest state

---

keps/prod-readiness/sig-api-machinery/2340.yaml
keps/sig-api-machinery/2340-Consistent-reads-from-cache/README.md
keps/sig-api-machinery/2340-Consistent-reads-from-cache/kep.yaml

Move KEP 2340 to Beta

---

keps/prod-readiness/sig-node/4369.yaml
keps/sig-node/4369-allow-special-characters-environment-variable/README.md
keps/sig-node/4369-allow-special-characters-environment-variable/kep.yaml

- One-line PR description: promote kep 4396 into implementable
- Issue link: https://github.com/kubernetes/enhancements/issues/4369

KEP-4396: promote kep into implementable

---

keps/prod-readiness/sig-instrumentation/2305.yaml
keps/sig-instrumentation/2305-metrics-cardinality-enforcement/README.md
keps/sig-instrumentation/2305-metrics-cardinality-enforcement/kep.yaml

- One-line PR description: Mark the feature as stable, since we've been on beta for a while now.
- Issue link: https://github.com/kubernetes/enhancements/issues/2305

GA Metrics Cardinality Enforcement

---

keps/prod-readiness/sig-node/4009.yaml
keps/sig-node/4009-add-cdi-devices-to-device-plugin-api/README.md
keps/sig-node/4009-add-cdi-devices-to-device-plugin-api/kep.yaml

- One-line PR description: Update `CDI for device plugins` KEP for GA graduation
- Issue link: https://github.com/kubernetes/enhancements/issues/4009

Update CDI for device plugins KEP for GA graduation

---

keps/prod-readiness/sig-node/4210.yaml
keps/sig-node/4210-max-image-gc-age/README.md
keps/sig-node/4210-max-image-gc-age/kep.yaml

KEP-4210: retarget to beta for 1.30

---

keps/prod-readiness/sig-network/4444.yaml
keps/sig-network/4444-service-routing-preference/README.md
keps/sig-network/4444-service-routing-preference/kep.yaml

- One-line PR description: Adding new KEP-4444 proposing Routing Preference for Services
- Issue link: https://github.com/kubernetes/enhancements/issues/4444
/sig network
/cc @robscott, @aojea, @danwinship

KEP-4444: Routing Preference for Services

---

keps/prod-readiness/sig-scheduling/3633.yaml
keps/sig-scheduling/3633-matchlabelkeys-to-podaffinity/README.md
keps/sig-scheduling/3633-matchlabelkeys-to-podaffinity/kep.yaml

- One-line PR description: fill the sections need to graduate matchLabelKeys/mismatchLabelKeys to beta.

KEP-3633: graduate matchLabelKeys/mismatchLabelKeys to beta

---

keps/prod-readiness/sig-api-machinery/3352.yaml
keps/sig-api-machinery/3352-aggregated-discovery/README.md
keps/sig-api-machinery/3352-aggregated-discovery/kep.yaml

- One-line PR description: KEP-3352: Aggregated Discovery to GA
- Issue link: https://github.com/kubernetes/enhancements/issues/3352

KEP-3352: Aggregated Discovery to GA

---

keps/prod-readiness/sig-node/3857.yaml
keps/sig-node/3857-rro-mounts/README.md
keps/sig-node/3857-rro-mounts/kep.yaml

- One-line PR description: Recursive Read-only (RRO) mounts
- Issue link: https://github.com/kubernetes/enhancements/issues/3857
Related:
- https://github.com/opencontainers/runc/pull/3272
- https://github.com/containers/crun/pull/778
- https://github.com/containers/youki/pull/1398
- https://github.com/containerd/nerdctl/pull/511
- https://github.com/moby/moby/issues/44978
- https://github.com/util-linux/util-linux/issues/1501

KEP-3857: Recursive Read-only (RRO) mounts

---

keps/prod-readiness/sig-node/127.yaml
keps/sig-node/127-user-namespaces/README.md
keps/sig-node/127-user-namespaces/kep.yaml

KEP-127: graduate to Beta for 1.30

---

keps/prod-readiness/sig-node/4265.yaml
keps/sig-node/4265-proc-mount/README.md
keps/sig-node/4265-proc-mount/kep.yaml

- One-line PR description: Bump ProcMount feature to beta 
- Issue link: https://github.com/kubernetes/enhancements/issues/4265 
- Other comments: successor to https://github.com/kubernetes/community/pull/1934

Add restrospetive KEP for ProcMount and target at Beta

---

keps/prod-readiness/sig-apps/3998.yaml
keps/sig-apps/3998-job-success-completion-policy/README.md
keps/sig-apps/3998-job-success-completion-policy/kep.yaml

- One-line PR description: KEP for an API to define when a Job can be declared as succeeded.
- Issue link: #3998

KEP-3998: Job success/completion policy

---

keps/prod-readiness/sig-apps/3973.yaml
keps/sig-apps/3973-consider-terminating-pods-deployment/README.md
keps/sig-apps/3973-consider-terminating-pods-deployment/kep.yaml

- One-line PR description: Deployment should consider terminating pods when performing new rollouts and scaling. 
- supersedes https://github.com/kubernetes/enhancements/pull/3974
- similar feature for Jobs: https://github.com/kubernetes/enhancements/issues/3939

KEP-3973: Consider Terminating Pods in Deployments

---

keps/prod-readiness/sig-node/24.yaml
keps/sig-node/24-apparmor/README.md
keps/sig-node/24-apparmor/kep.yaml

Add a retroactive KEP for AppArmor, and GA promotion criteria
- Issue link: #24 
Supercedes https://github.com/kubernetes/enhancements/pull/3298
/sig node
/milestone v1.30
/cc @dchen1107

KEP-24: Promote AppArmor to GA

---

keps/prod-readiness/sig-windows/2258.yaml
keps/sig-windows/2258-node-log-query/README.md
keps/sig-windows/2258-node-log-query/kep.yaml

- Promote NodeLogQuery to beta:
- highlight that a periodic job was added
- link to the NodeLogQuery kubelet plugin
- Issue link:
- https://github.com/kubernetes/enhancements/issues/2258

KEP-2258: Promote NodeLogQuery to beta

---

keps/prod-readiness/sig-autoscaling/1610.yaml
keps/sig-autoscaling/1610-container-resource-autoscaling/README.md
keps/sig-autoscaling/1610-container-resource-autoscaling/kep.yaml

- One-line PR description: graduate ContainerResource to stable
- Issue link: https://github.com/kubernetes/enhancements/issues/1610

KEP-1610: graduate ContainerResource to stable

---

keps/prod-readiness/sig-node/3063.yaml
keps/sig-node/3063-dynamic-resource-allocation/README.md
keps/sig-node/3063-dynamic-resource-allocation/kep.yaml

- One-line PR description: This updates the README to reflect what has been done and fills in sections that were left out earlier. The next milestone is 1.30 where DRA will remain in alpha.

KEP-3063: DRA: 1.30 update

---

keps/prod-readiness/sig-node/2008.yaml
keps/sig-node/2008-forensic-container-checkpointing/README.md
keps/sig-node/2008-forensic-container-checkpointing/kep.yaml

As defined in the existing KEP the steps to graduate from Alpha to Beta are
At least one container engine has to have implemented the
corresponding CRI APIs to introduce e2e test for checkpointing.
CRI-O implemented the corresponding CRI RPC and no major bugs have been reported since the initial release in 1.25.
- One-line PR description: Graduate "Forensic Container Checkpointing" to Beta
- Issue link: https://github.com/kubernetes/enhancements/issues/2008

KEP-2008: Graduate "Forensic Container Checkpointing" to Beta

---

keps/sig-api-machinery/2887-openapi-enum-types/kep.yaml

This KEP graduated to beta in 1.24 according  to https://github.com/kubernetes/enhancements/pull/3184.
This update kep.yaml to match.

Fix status of OpenAPI Enum Types KEP

---

keps/sig-api-machinery/1601-client-go-context/kep.yaml

Given https://github.com/kubernetes/enhancements/tree/master/keps/sig-api-machinery/1601-client-go-context#graduation-criteria:
"This enhancement will be GA immediately."
Let's track in in kep.yaml as such.

Mark client-go context as stable to match GA criteria in KEP

---

keps/sig-instrumentation/3077-contextual-logging/README.md
keps/sig-instrumentation/3077-contextual-logging/kep.yaml

- One-line PR description: sync with KEP template
- Issue link: https://github.com/kubernetes/enhancements/issues/3077
- Other comments: The KEP was [removed from 1.30 milestone](https://github.com/kubernetes/enhancements/issues/3077#issuecomment-1935239175) because this question hadn't been answered.

KEP-3077: contextual logging: sync with KEP template

---

keps/prod-readiness/sig-network/1860.yaml
keps/sig-network/1860-kube-proxy-IP-node-binding/README.md
keps/sig-network/1860-kube-proxy-IP-node-binding/kep.yaml

- One-line PR description: Add missing PRR descriptions and propose beta graduation for KEP 1860
- Issue link: https://github.com/kubernetes/enhancements/issues/1860
- Other comments: Will try to achieve PRR review and exception for v1.30, sorry for missing this train!

KEP-1860 - Propose beta graduation and add missing PRR 

---

keps/sig-cli/1441-kubectl-debug/README.md

- One-line PR description: Change answer of a PRR question that is about roll out because of the promotion of kubectl debug to stable

Change the rollout question's answer for kubectl debug GA

---

OWNERS_ALIASES

Adding myself to owners, to be able to update older instrumentation-based KEP descriptions. Also excluded Elana from the list since she has stepped down.

Add `rexagod` to owners

---

keps/prod-readiness/sig-apps/4368.yaml
keps/sig-apps/4368-support-managed-by-for-batch-jobs/README.md
keps/sig-apps/4368-support-managed-by-for-batch-jobs/kep.yaml

- Issue link: https://github.com/kubernetes/enhancements/issues/4368
Changes:
* "managed-by" label -> "managedBy" field
* beta stage -> alpha
* added graduation criteria for beta "verify the validation passes during e2e tests for open-source projects (like Kueue and JobSet)"
The [doc](https://docs.google.com/document/d/1rvn4iWt841n0gwtJbCwBBldkLsGFcUmjWMOYpRgNoJM) with the notes of the meeting where we took the decision to use field instead, shared with kubernetes-dev group.

KEP-4368 update to use managedBy field instead of label

---

keps/sig-storage/3756-volume-reconstruction/kep.yaml

- One-line PR description: Mark NewVolumeManagerReconstruction as implemented, it's GA in Kubernetes 1.30
cc @msau42 @xing-yang

Mark NewVolumeManagerReconstruction as implemented

---

keps/sig-apps/4368-support-managed-by-for-batch-jobs/README.md

- One-line PR description: Add graduation criteria to adjust validation or comments with respect to the decisions
- Issue link: https://github.com/kubernetes/enhancements/issues/4368
Related to the issue: https://github.com/kubernetes/kubernetes/issues/123775

KEP-4368 update to add graduation criteria to adjust the validation based on the decisions

---

keps/prod-readiness/sig-api-machinery/4568.yaml
keps/sig-api-machinery/4568-resilient-watchcache-initialization/README.md
keps/sig-api-machinery/4568-resilient-watchcache-initialization/kep.yaml

KEP 4568: Resilient watchcache initialization

---

keps/prod-readiness/sig-api-machinery/4420.yaml
keps/sig-api-machinery/4420-retry-generate-name/kep.yaml

No changes to the plan on this one, just a beta promotion so it's on-by-default in 1.31.
- Issue link: https://github.com/kubernetes/enhancements/issues/4420

KEP-4420: Promote retry generate name to beta

---

keps/sig-cluster-lifecycle/kubeadm/4471-cp-join-kubelet-local-apiserver/README.md
keps/sig-cluster-lifecycle/kubeadm/4471-cp-join-kubelet-local-apiserver/kep.yaml

- One-line PR description: adding new KEP
- Issue link: #4471 

KEP-4471: kubeadm: make a control-plane's kubelet talk to the local API Server on kubeadm join.

---

keps/sig-api-machinery/2340-Consistent-reads-from-cache/README.md
keps/sig-api-machinery/2340-Consistent-reads-from-cache/kep.yaml

Ref #2340
/cc @serathius @deads2k

Consistent reads mitigation

---

OWNERS_ALIASES

- 1.29 shadow reviews: [9](https://github.com/orgs/kubernetes/projects/161/views/2?filterQuery=prr-shadow%3Asoltysh)
- 1.30 shadow reviews: [8](https://github.com/orgs/kubernetes/projects/175/views/2?filterQuery=prr-shadow%3Asoltysh)
- 1.31+ I'm planning to continue my contributions to PRR, hopefully reaching 10 KEPs/release cycle, aside from the ones I'm looking at as sig apps and sig cli lead.
- https://github.com/kubernetes/enhancements/pull/4211 (sig-node)
- https://github.com/kubernetes/enhancements/pull/3927 (sig-auth)
- https://github.com/kubernetes/enhancements/pull/4230 (sig-node)
- https://github.com/kubernetes/enhancements/pull/3824 (sig-network)
- https://github.com/kubernetes/enhancements/pull/3067 (sig-node)
- https://github.com/kubernetes/enhancements/pull/4184 (sig-node)
- …

Add soltysh to prod-readiness-approvers

---

keps/sig-multicluster/4322-cluster-inventory/README.md
keps/sig-multicluster/4322-cluster-inventory/kep.yaml

- One-line PR description: Update KEP-4322 by renaming API to "Cluster Profile" and adding an alternative description.
- Issue link: https://github.com/kubernetes/enhancements/issues/4322
The decision to rename the API to "Cluster Profile" was not based on personal opinion but on consensus from the SIG-MC community, through discussions in meetings, open votes, and at KubeCon EU 2024.
/sig multicluster
CC @qiujian16 @JeremyOT @dixudx @ryanzhang-oss

KEP-4322: rename API to "Cluster Profile" and add alternative section

---

OWNERS_ALIASES

In `sig-docs-leads` in k/enhancement/OWNERS_ALIASES , this PR removes Karen Bradshaw, Taylor Dolezal, and Tim Bannister who have stepped down from the tech lead role
Follow up to comment in https://github.com/kubernetes/enhancements/pull/4630#discussion_r1600072255
/cc @natalisucks @divya-mohan0209

Update sig-docs-leads in enhancements/OWNERS_ALIASES

---

keps/sig-api-machinery/3157-watch-list/README.md
keps/sig-api-machinery/3157-watch-list/kep.yaml

- One-line PR description: Update KEP 3157 (watch-list) for milestone 1.31

Update KEP 3157 (watch-list) for milestone 1.31

---

keps/sig-node/3983-drop-in-configuration/README.md

We already have a method to query the Kubelet's full effective configuration, so there's no need to implement that API. We can simply use this query: `kubectl get --raw "/api/v1/nodes/192.168.1.16/proxy/configz"`

KEP-3983: update the beta requirements

---

keps/sig-node/2000-graceful-node-shutdown/README.md

Add note indicating that  'shutdown -h now` may not trigger GracefulNodeShutdown in the KEP-2000. 
- Issue link:
https://github.com/kubernetes/kubernetes/issues/124039
Having `shutdown -h now` listed as the first way of shutting down gives the false impression that this method is recommended. But in some environments, the GracefulNodeShutdown may not trigger with `shutdown -h now`

KEP-2000: Add note in KEP Proposal for `shutdown -h now` systemd version compatibility

---

keps/sig-node/4009-add-cdi-devices-to-device-plugin-api/README.md

- One-line PR description: CDI for device plugins: update test grid and triage links
- Issue link: https://github.com/kubernetes/enhancements/issues/4009
- Other comments: [New test infra job](https://testgrid.k8s.io/sig-node-cri-o#ci-crio-cdi-device-plugins) has been  created to test CDI support for device plugins to make sure other tests will not influence graduation of this feature to GA. This PR updates test grid and triage links to point to the new job.

CDI for device plugins: update test grid and triage links

---

keps/sig-auth/4193-bound-service-account-token-improvements/README.md

- One-line PR description: note ServiceAccountTokenNodeBinding being promoted to beta
- Other comments: k/k PR: https://github.com/kubernetes/kubernetes/pull/125238
/cc @liggitt

KEP-4193: note ServiceAccountTokenNodeBinding being promoted to beta

---

keps/sig-network/4444-service-traffic-distribution/README.md
keps/sig-network/4444-service-traffic-distribution/kep.yaml

- One-line PR description: Update the name of the field (and field values) which was decided during the implementation.
- Issue link: https://github.com/kubernetes/enhancements/issues/4444
- Other comments: This PR is in preparation for targeting Beta release in v1.31. The renaming changes have been isolated from other updates to help with the review process.
/sig network
/assign @robscott

KEP-4444: Rename field routingPreference to trafficDistribution as per the decision during implementation.

---

keps/sig-scheduling/3521-pod-scheduling-readiness/kep.yaml

- One-line PR description: update Pod Scheduling Readiness to implemented

KEP-3521: update Pod Scheduling Readiness to implemented

---

keps/prod-readiness/sig-node/4569.yaml
keps/sig-node/4569-cgroup-v1-maintenance-mode/README.md
keps/sig-node/4569-cgroup-v1-maintenance-mode/kep.yaml

- One-line PR description: Deprecate cgroup v1 support
- Issue link: https://github.com/kubernetes/enhancements/issues/4569

Move cgroup v1 support into maintenance mode

---

keps/sig-auth/3331-structured-authentication-configuration/kep.yaml

- Update KEP latest milestone to `v1.31`.
- The feature will remain in beta in v1.31 but we plan to make some code changes in v1.31 release for metrics and refactoring.
/sig auth
/assign enj

KEP-3331: update kep latest milestone to v1.31

---

keps/sig-api-machinery/1601-client-go-context/kep.yaml
keps/sig-api-machinery/2155-clientgo-apply/kep.yaml
keps/sig-api-machinery/2896-openapi-v3/kep.yaml
keps/sig-api-machinery/3488-cel-admission-control/kep.yaml
keps/sig-api-machinery/95-custom-resource-definitions/kep.yaml

CEL for Admission control was implemented in 1.30
The others have been implemented for a long time and this is just cleanup.
/assign @deads2k @fedebongio @sttts

Mark implemented SIG API Machinery KEPs as such

---

OWNERS_ALIASES

Updated [OWNERS_ALIASES](https://git.k8s.io/enhancements/OWNERS_ALIASES) in [kubernetes/enhancements](https://github.com/kubernetes/enhancements) for https://github.com/kubernetes/community/issues/7865.

SIG Cloud Provider update

---

keps/sig-apps/3998-job-success-completion-policy/README.md

- One-line PR description: I updated KEP based on implementations
- I updated a Job API name  (SuccessPolicyCriteria (JSON="criteria") -> SuccessPolicyRule (JSON="rules")) based on this discussion: https://github.com/kubernetes/kubernetes/pull/123412#discussion_r1511794767
- I added validations for `status.conditions`.
- I replaced *int with *int32 in the `rules[*].succeededCount`.
- Issue link: https://github.com/kubernetes/enhancements/issues/3998

KEP-3998: Uptdate JobSuccessPolicy API Name and Validations

---

keps/prod-readiness/sig-auth/4601.yaml
keps/sig-auth/4601-authorize-with-selectors/README.md
keps/sig-auth/4601-authorize-with-selectors/kep.yaml

Still in progress, but the bones are here.
/assign @liggitt 
/assign @micahhausler 
/cc @enj 
- Issue link:

KEP-4601: authorize with field and label selectors

---

keps/prod-readiness/sig-api-machinery/4460.yaml
keps/sig-api-machinery/4460-per-request-deadline/README.md
keps/sig-api-machinery/4460-per-request-deadline/kep.yaml

- One-line PR description: adding new KEP
- Issue link: https://github.com/kubernetes/enhancements/issues/4460

KEP-4460:  Enable per-request Read/Write deadline

---

keps/prod-readiness/sig-api-machinery/4355.yaml
keps/sig-api-machinery/4355-coordinated-leader-election/README.md
keps/sig-api-machinery/4355-coordinated-leader-election/kep.yaml

- One-line PR description: Coordinated Leader Election KEP 
- Issue link: https://github.com/kubernetes/enhancements/issues/4355
-  Prototype: https://github.com/jpbetz/kubernetes/tree/leader-election-controller/demo

KEP-4355: Coordinated Leader Election

---

keps/prod-readiness/sig-auth/4633.yaml
keps/sig-auth/4633-anonymous-auth-configurable-endpoints/README.md
keps/sig-auth/4633-anonymous-auth-configurable-endpoints/kep.yaml

- One-line PR description: Adding new KEP.
- Issue link: #4633 
- Here is the implementation of the Alpha phase of this KEP: https://github.com/kubernetes/kubernetes/pull/124917

KEP-4633: Only allow anonymous auth for configured endpoints

---

keps/sig-api-machinery/4420-retry-generate-name/README.md
keps/sig-api-machinery/4420-retry-generate-name/kep.yaml

Per request: https://github.com/kubernetes/enhancements/issues/4420#issuecomment-2148615582
- Update feature gate name to match implementation
- Update implementation history
/assign @deads2k @sttts

KEP 4420:  Retry Generate Name KEP paperwork

---

keps/sig-etcd/4578-server-feature-gate/README.md
keps/sig-etcd/4578-server-feature-gate/kep.yaml

- One-line PR description: KEP to introduce feature gate in etcd
- Issue link: https://github.com/kubernetes/enhancements/issues/4578

KEP-4578: Server Feature Gate in etcd

---

keps/sig-cli/3104-introduce-kuberc/README.md
keps/sig-cli/3104-introduce-kuberc/kep.yaml

- One-line PR description: Update kuberc document.
/assign @ardaguclu @eddiezane

KEP-3104: Introduce kuberc - update for 1.31

---

keps/sig-node/4381-dra-structured-parameters/README.md

- One-line PR description: DRA: avoid kubelet API version dependency
By requiring that drivers on a node connect to the apiserver directly it becomes possible to update drivers and the control plane to a newer release than the kubelet because the kubelet doesn't need to encode/decode the resource.k8s.io API types that are used by the drivers. This simplifies cluster upgrades.

KEP-4318: DRA: avoid kubelet API version dependency

---

keps/prod-readiness/sig-network/4444.yaml
keps/sig-network/4444-service-traffic-distribution/README.md
keps/sig-network/4444-service-traffic-distribution/kep.yaml

- One-line PR description: Update PRR sections for beta release targeting 1.31
- Issue link: https://github.com/kubernetes/enhancements/issues/4444
- Other comments: There's a separate PR for the first commit involving the renaming https://github.com/kubernetes/enhancements/pull/4655. The focus of this PR is the second commit (I will rebase once the other one merges)
/sig network
/cc @robscott 
/assign @aojea, @danwinship, @thockin 
PRR reviewers:

KEP-4444: Update PRR sections for beta release targeting 1.31

---

keps/prod-readiness/sig-network/3866.yaml
keps/sig-network/3866-nftables-proxy/README.md
keps/sig-network/3866-nftables-proxy/kep.yaml

- One-line PR description: move KEP-3866 kube-proxy nftables to beta
- Issue link: https://github.com/kubernetes/enhancements/issues/3866
Started this to try and nail down what was left to be done. Still some updates pending.

KEP-3866 kube-proxy nftables to beta

---

keps/prod-readiness/sig-apps/3329.yaml
keps/sig-apps/3329-retriable-and-non-retriable-failures/README.md
keps/sig-apps/3329-retriable-and-non-retriable-failures/kep.yaml

One-line PR description: Graduate Pod Failure Policy to stable
Issue link: https://github.com/kubernetes/enhancements/issues/3329
* the feature is graduated to Beta since 1.26 and no major changes since 1.27
* the code is distributed among multiple components (kube-controller-manager,  kubelet, scheduler, api-server), and thus maintaining 2 paths in code, including possible skewed versions adds significant complexity
* other OSS projects and features within k8s are already building on top of Pod Failure Policy: 
1. https://github.com/kubernetes/enhancements/issues/4443
* there is one-edge case issue https://github.com/kubernetes/kubernetes/issues/115688, however, this is not an issue with the mechanism itself. Adding a dedicated condition for exceeded ActiveDeadlineSeconds …

Graduate Job Pod Failure Policy to stable

---

keps/prod-readiness/sig-apps/3998.yaml
keps/sig-apps/3998-job-success-completion-policy/README.md
keps/sig-apps/3998-job-success-completion-policy/kep.yaml

- One-line PR description: Graduate the JobSuccessPolicy to Beta.
- Issue link: #3998
See also: https://github.com/kubernetes/enhancements/pull/4657

KEP-3998: Graduate Job SuccessPolicy to Beta

---

keps/sig-apps/3329-retriable-and-non-retriable-failures/README.md

- One-line PR description: Correction to the GA graduation plan
- Other comments: I have realized the current graduation criteria are not consistent. We cannot add the test if we lock the feature gates JobPodFailurePolicy and PodDisruptionConditions. It is too late. Alternatively, we could move the lock to GA+1, and removal to GA+3. Since the disablement and re-enablement was tested manually for upgrade tests I propose to just drop the automated test: https://github.com/kubernetes/enhancements/tree/master/keps/sig-apps/3329-retriable-and-non-retriable-failures#were-upgrade-and-rollback-tested-was-the-upgrade-downgrade-upgrade-path-tested.

Correction to the Job pod failure policy update to GA

---

keps/prod-readiness/sig-cli/4706.yaml
keps/sig-cli/4706-deprecate-and-remove-kustomize/README.md
keps/sig-cli/4706-deprecate-and-remove-kustomize/kep.yaml

- One-line PR description: deprecate and remove kustomize from kubectl
- Issue link: https://github.com/kubernetes/enhancements/issues/4706
/assign @eddiezane @ardaguclu @mpuckett159

KEP-4706: Deprecate and remove kustomize from kubectl

---

keps/prod-readiness/sig-network/4004.yaml
keps/sig-network/4004-deprecate-kube-proxy-version/README.md
keps/sig-network/4004-deprecate-kube-proxy-version/kep.yaml

- One-line PR description: Promote the stage of KEP to beta.
- Issue link:  https://github.com/kubernetes/enhancements/issues/4004

KEP-4004: promote stage to beta

---

keps/prod-readiness/sig-apps/4443.yaml
keps/sig-apps/4443-configurable-pod-failure-policy-reasons/README.md
keps/sig-apps/4443-configurable-pod-failure-policy-reasons/kep.yaml

- One-line PR description: Configurable Job failure reason for PodFailurePolicy
- Issue link: #4443 

KEP-4443: Add more granular Job failure reason for PodFailurePolicy

---

keps/sig-api-machinery/4222-cbor-serializer/README.md

- One-line PR description: Relax description of decode allocations fuzz test.
- Other comments: The goal of this test was to be able to identify pathological inputs that cause the decoder to allocate excessive amounts of memory (for example, by trusting the length indicated by the initial bytes of a string and preallocating a slice of that length). That can be achieved without attempting to enforce a specific limit on the ratio between input length and bytes allocated, which is subject to many variables.

KEP-4222: Relax description of decode allocations fuzz test.

---

keps/sig-windows/1122-windows-csi-support/README.md

The link is broken since the original repo had been archived
- Issue link:

Fix a broken link that points to an archived repository

---

keps/sig-node/4438-container-restart-termination/README.md
keps/sig-node/4438-container-restart-termination/kep.yaml

- One-line PR description: preparing KEP for 1.31 release cycle
- Issue link: https://github.com/kubernetes/enhancements/issues/4438
- Other comments: for 1.31 we'll mostly work on sidecars, however pod termination will be more broadly modified on next cycles

KEP-4438: rename gate and update milestones

---

keps/prod-readiness/sig-apps/2185.yaml
keps/sig-apps/2185-random-pod-select-on-replicaset-downscale/README.md
keps/sig-apps/2185-random-pod-select-on-replicaset-downscale/kep.yaml

Ref: [#2185](https://github.com/kubernetes/enhancements/issues/2185)

Update random pod scaledown KEP for stable

---

keps/prod-readiness/sig-apps/3335.yaml
keps/sig-apps/3335-statefulset-slice/README.md
keps/sig-apps/3335-statefulset-slice/kep.yaml

- One-line PR description: KEP-3335: Update stable milestone to 1.31
- Issue link: https://github.com/kubernetes/enhancements/issues/3335
- Other comments: e2e tests will not be graduated (per the [conformance criteria](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/conformance-tests.md), as using the `.spec.ordinals` field is optional.

KEP-3335: Update stable milestone to 1.31

---

keps/sig-storage/3751-volume-attributes-class/README.md

- One-line PR description: update VolumeAttributesClass Deletion Protection
- Issue link: #3751 

update VolumeAttributesClass Deletion Protection

---

keps/prod-readiness/sig-node/4191.yaml
keps/sig-node/4191-split-image-filesystem/README.md
keps/sig-node/4191-split-image-filesystem/kep.yaml

- One-line PR description: Graduate [KEP-4191](https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/4191-split-image-filesystem/README.md) "Split Image Filesystem" to Beta
- Issue link: https://github.com/kubernetes/enhancements/issues/4191
We would like to move ahead with the graduation of KEP-4191 to Beta as part of the upcoming Kubernetes v1.31 release. 
Especially as not much work remains to be completed (the majority of work planned for the Alpha release has been completed). As such, we would want to take advantage of the opportunity to move ahead with the graduation process for this KEP.
While at it, improve KEP's style and correct wording in several places. No other changes are intended.

KEP-4191: Split Image Filesystem graduation to Beta

---

keps/prod-readiness/sig-storage/3751.yaml
keps/sig-storage/3751-volume-attributes-class/README.md
keps/sig-storage/3751-volume-attributes-class/kep.yaml

- One-line PR description: Update milestone 1.31 and fill out PRR
- Issue link: https://github.com/kubernetes/enhancements/issues/3751
- Other comments: Few items to be updated by enhancement freeze.

KEP-3751: Update for milestone 1.31

---

keps/sig-node/4191-split-image-filesystem/README.md

- One-line PR description: Updated [KEP-4191](https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/4191-split-image-filesystem/README.md) "Split Image Filesystem" with a failure scenario
- Issue link: https://github.com/kubernetes/enhancements/issues/4191
This is related to https://github.com/kubernetes/enhancements/pull/4684, where the PRR has been updated following review feedback. I wanted to also add a failure scenario, but I wasn't fast enough before the Pull Request was approved and merged. This change does exactly that.

KEP-4191: Split Image Filesystem add failure scenario

---

keps/prod-readiness/sig-node/3857.yaml
keps/sig-node/3857-rro-mounts/README.md
keps/sig-node/3857-rro-mounts/kep.yaml

- One-line PR description: KEP-3857: Recursive Read-only (RRO) mounts: promote to Beta
- Issue link: #3857
- Other comments: The KEP can be moved to beta, as the feature is now ready for containerd, CRI-O, and cri-dockerd: 
- https://github.com/containerd/containerd/pull/9787
- https://github.com/cri-o/cri-o/pull/7962
- https://github.com/Mirantis/cri-dockerd/pull/370

KEP-3857: Recursive Read-only (RRO) mounts: promote to Beta

---

keps/prod-readiness/sig-apps/3715.yaml
keps/sig-apps/3715-elastic-indexed-job/README.md
keps/sig-apps/3715-elastic-indexed-job/kep.yaml

- One-line PR description: graduate to stable
- Issue link: https://github.com/kubernetes/enhancements/issues/3715

Graduate elastic indexed job to stable

---

hack/verify-spelling.sh

- One-line PR description: ignore YAML files when doing spell check
- Issue link: https://github.com/kubernetes/enhancements/issues/4674
- Other comments: implements: https://github.com/kubernetes/enhancements/issues/4674#issuecomment-2155698014

spell: ignore YAML files

---

keps/prod-readiness/sig-node/1029.yaml
keps/sig-node/1029-ephemeral-storage-quotas/README.md
keps/sig-node/1029-ephemeral-storage-quotas/kep.yaml

Modifications to push the changes to beta 1.31
KEP-1029: adding beta graduation criteria
- One-line PR description: Adding Implementation Details
- Issue link: https://github.com/kubernetes/enhancements/issues/1029

sig-node/1029-ephemeral-storage-quotas/*:

---

keps/sig-node/3063-dynamic-resource-allocation/README.md
keps/sig-node/4381-dra-structured-parameters/README.md

- One-line PR description: Update the DRA API and design for Kubernetes 1.31
- Issue links:
- https://github.com/kubernetes/enhancements/issues/4381
- https://github.com/kubernetes/enhancements/issues/3063
This is based on https://github.com/kubernetes/enhancements/pull/4667 which got already merged.
**If you review this anew, start with 4381, then circle back to 3063.**
This update is the result of the prototyping in
https://github.com/kubernetes-sigs/wg-device-management/tree/main/dra-evolution.
The key changes compared to 1.30 are:
- Removal of CRD support. Vendor configuration parameters
are still supported as raw extensions of the in-tree types.
- Removal of immediate allocation.
- Removal of "claim.status.sharable": all claims can be shared when multiple pods …

KEP-4381: DRA update for 1.31

---

keps/prod-readiness/sig-node/4622.yaml
keps/sig-node/4622-topologymanager-max-allowable-numa-nodes/README.md
keps/sig-node/4622-topologymanager-max-allowable-numa-nodes/kep.yaml

- One-line PR description:  New TopologyManager Policy: max-allowable-numa-nodes
- Issue link: https://github.com/kubernetes/enhancements/issues/4622
- Other comments: https://github.com/kubernetes/kubernetes/pull/124148

KEP-4622: New TopologyManager Policy: max-allowable-numa-nodes

---

keps/prod-readiness/sig-network/1880.yaml
keps/sig-network/1880-multiple-service-cidrs/README.md
keps/sig-network/1880-multiple-service-cidrs/kep.yaml

- One-line PR description: graduate to beta
- Issue link: https://github.com/kubernetes/enhancements/issues/1880
- Other comments: Since the feature depends on a beta API, it will be disabled by default

KEP-1880: graduating to beta

---

keps/sig-node/127-user-namespaces/README.md

KEP-127: update based on current PSS integration approach

---

keps/sig-multicluster/4322-cluster-inventory/README.md

Add the definition of a cluster Inventory and some notes on how it should be consumed.
- Issue link:

KEP-4322: Add cluster inventory definition

---

keps/sig-node/3619-supplemental-groups-policy/README.md

- One-line PR description: Add `SupplementalGroupsPolicy` feature fields in Kubernetes API(`Node.Status`) and CRI(`RuntimeStatusResponse`)
- Summary
- The PR proposes to add a new field `NodeStatus.Features (type: NodeFeatures)` and its corresponding field in CRI so that kubernetes can capture if the feature is implemented by the underlying CRI implementation in each node.
- `SupplementalGroupsPolicy` lives under `NodeFeatures`
- This is a different field from `NodeStatus.RuntimeHandlers[].Features` (which contains rro, user ns) recently introduced in [KEP-3857(RRO)](https://github.com/kubernetes/enhancements/issues/3857)
- This PR makes a clear distinction between them:
- `NodeStatus.Features` (this kep): focuses on features that do NOT require to inspect [OCI runtime spec's …

KEP-3619: Add `SupplementalGroupsPolicy` feature fields in Kubernetes API(`Node.Status`) and CRI(`RuntimeStatusResponse`)

---

keps/sig-auth/2718-20210511-client-exec-proxy/kep.yaml

- One-line PR description: Mark client exec proxy as withdrawn
- Issue link: #2718 
- Other comments: There have been no updates in 1.5 years nor have there been any community requests.  That combined with a high complexity implementation lead me to believe that we will not pursue this KEP.

KEP-2718: Mark client exec proxy as withdrawn

---

keps/sig-storage/3751-volume-attributes-class/README.md

Editing KEP-3751 milestone for 1.31.
- Issue link: #3751 
Edits KEP to mention:
- Why Quota support will not be supported at Kubernetes v1.31
- Why Default VolumeAttributesClass will not be supported at Kubernetes v1.31
- Add more details to metrics section
- Fix typos

KEP-3751: corrections for milestone 1.31

---

keps/sig-node/4639-oci-volume-source/README.md
keps/sig-node/4639-oci-volume-source/kep.yaml

Updating the KEP after the merge of: https://github.com/kubernetes/kubernetes/pull/125659
This reflects the current state of the enhancement.
Refers to https://github.com/kubernetes/enhancements/issues/4639
PTAL @haircommander @mikebrow @mrunalp

KEP-4639: Update CRI API and workflow

---

keps/sig-network/4427-relaxed-dns-search-validation/README.md
keps/sig-network/4427-relaxed-dns-search-validation/kep.yaml

- One-line PR description: As per https://github.com/kubernetes/kubernetes/issues/125883, it was decided to update KEP-4427 with an additional relaxation (to allow a single dot character). This PR updates the KEP to reflect that decision.
- Issue link: https://github.com/kubernetes/enhancements/issues/4427
- Other comments: None.

KEP-4427: Add additional DNS search validation relaxation 

---

keps/sig-apps/3973-consider-terminating-pods-deployment/README.md

- One-line PR description: fix replicaset preference in leftover calculation in PodReplacementPolicy KEP

KEP-3973: fix replicaset preference in leftover calculation in PodReplacementPolicy KEP

---

OWNERS_ALIASES

pmorie moving to emeritus, skitt becoming co-chair, jeremyot unchanged; see
https://groups.google.com/g/kubernetes-sig-multicluster/c/xhj2OnFO-8M for the discussion and lazy consensus (deadline July 1, 2024).

SIG-Multicluster leadership change: pmorie emeritus, skitt co-chair

---

keps/sig-api-machinery/4006-transition-spdy-to-websockets/README.md

* Adds GA requirement for currently missing websocket HTTPS proxy support.
* See: https://github.com/kubernetes/kubernetes/issues/126134
https://github.com/kubernetes/enhancements/issues/4006

KEP-4006: Adds GA requirement for websocket HTTPS proxy support

---

keps/prod-readiness/sig-auth/4633.yaml
keps/sig-auth/4633-anonymous-auth-configurable-endpoints/README.md
keps/sig-auth/4633-anonymous-auth-configurable-endpoints/kep.yaml

- One-line PR description: Graduate KEP-4633 to BETA.
- Issue link: https://github.com/kubernetes/enhancements/issues/4633

KEP-4633: Graduate to BETA.

---

keps/sig-apps/3329-retriable-and-non-retriable-failures/README.md

One-line PR description: Update the KEP after the graduation to GA
Issue link: https://github.com/kubernetes/enhancements/issues/3329
Changes:
- Move "Modify the code to ignore the PodDisruptionConditions and JobPodFailurePolicy feature gates" to reflect the actual state"
- Update the implementation history

KEP-3329: Update the Job Pod Failure Policy KEP after GA

---

keps/prod-readiness/sig-auth/3221.yaml
keps/sig-auth/3221-structured-authorization-configuration/kep.yaml

- Update KEP latest milestone to v1.31.
- The feature remains in beta in v1.31. plan to move to stable in v1.32
Issue link: https://github.com/kubernetes/enhancements/issues/3221
/sig auth
/assign liggitt

KEP-3221: update kep milestone and stage

---

keps/sig-apps/3998-job-success-completion-policy/README.md

One-line PR description: Add a graduation point to verify reason for the Job's complete condition
Issue link: https://github.com/kubernetes/enhancements/issues/3998
- The update was prompted by the [comment](https://github.com/kubernetes/kubernetes/pull/126169#discussion_r1759182682)
- We don't verify currently the reason for the Complete condition in conformance tests, as the conformance suite does not enable beta features (including "Success Policy" feature which changed the reason for the condition)

Job Success Policy - add a GA graduation point to verify success reason in conformance tests

---

keps/sig-apps/3850-backoff-limits-per-index-for-indexed-jobs/README.md

- One-line PR description: KEP update to revisit extending the pod failure policy tutorial before GA
Follow up to discussion: https://github.com/kubernetes/website/pull/46896?notification_referrer_id=NT_kwDOAJ4RjbQxMTE2ODEwMjc3NzoxMDM1OTE4MQ#discussion_r1700516273

KEP update to extend the Pod Failure Policy guide for FailIndex

---

keps/sig-network/4004-deprecate-kube-proxy-version/README.md
keps/sig-network/4004-deprecate-kube-proxy-version/kep.yaml

- One-line PR description: We replaced the `DisableNodeKubeProxyVersion` feature gate with Deprecated in https://github.com/kubernetes/kubernetes/pull/126720, modifying the KEP to be consistent with the implementation
- Issue link:  https://github.com/kubernetes/enhancements/issues/4004

KEP-4004: Replace with Deprecated feature gates

---

keps/sig-apps/1847-autoremove-statefulset-pvcs/README.md
keps/sig-apps/1847-autoremove-statefulset-pvcs/kep.yaml

- One-line PR description: describe the update to owner reference controller usage
- Other comments: See https://github.com/kubernetes/kubernetes/issues/122400
/cc @msau42

KEP-1847: ownerRef controller update

---

keps/sig-node/1769-memory-manager/OWNERS
keps/sig-node/2000-graceful-node-shutdown/OWNERS
keps/sig-node/2625-cpumanager-policies-thread-placement/OWNERS
keps/sig-node/3545-improved-multi-numa-alignment/OWNERS
keps/sig-node/3960-pod-lifecycle-sleep-action/OWNERS
keps/sig-node/3983-drop-in-configuration/OWNERS
keps/sig-node/4176-cpumanager-spread-cpus-preferred-policy/OWNERS
keps/sig-node/4369-allow-special-characters-environment-variable/OWNERS
keps/sig-node/4438-container-restart-termination/OWNERS
keps/sig-node/4622-topologymanager-max-allowable-numa-nodes/OWNERS

In SIG Node we want to start scaling ownership for KEPs. We will start with KEPs introducing some already accepted concepts so the person, assigned as an approver can help move the KEP forward thru stages.
More complex KEPs and new KEPs will be kept for tech-leads to approve.
/sig node
I used these assignments and applied my judgement. Open for corrections if I have mistaken in any of those: https://github.com/orgs/kubernetes/projects/186/views/7?filterQuery=status%3A%22Draft+Stage%22%2C%22Proposed+for+consideration%22+&visibleFields=%5B%22Title%22%2C%22Status%22%2C130447354%2C126885563%2C130446877%2C130446939%2C%22Reviewers%22%2C130446997%5D&sortedBy%5Bdirection%5D=desc&sortedBy%5BcolumnId%5D=130447354&sortedBy%5Bdirection%5D=asc&sortedBy%5BcolumnId%5D=126885563

Owners scale

---

keps/sig-apps/3998-job-success-completion-policy/README.md
keps/sig-apps/3998-job-success-completion-policy/kep.yaml

- One-line PR description: Based on [this discussion](https://github.com/kubernetes/kubernetes/pull/126067), I updated the  `jobs_finished_total` metric reasons and the `Complete` and `SuccessCriteriaMet` condition reasons.
- Issue link: #3998 
- Other comments: I updated the e2e test cases with the actual e2e testing implementations.

KEP-3998: Update the metrics and condition reason for the Beta graduation

---

keps/sig-node/2570-memory-qos/README.md

- One-line PR description: Clarify that this KEP was not promoted to  beta in 1.28
- Issue link: https://github.com/kubernetes/enhancements/issues/2570

KEP-2570 : Clarify the beta status of the KEP

---

keps/sig-node/753-sidecar-containers/README.md

/sig node
KEP:  #753
We tried once but we always get in debates with the alpha features that are coming up. https://github.com/kubernetes/kubernetes/pull/115643
Last one is that PodLevel resource KEP will need to pick up this work.

remove total resource calculation proposal from the sidecar KEP

---

keps/sig-node/3673-kubelet-parallel-image-pull-limit/kep.yaml

This KEP currently shows up as `KEP Template` in aggregators like https://www.kubernetes.dev/resources/keps/; fix that.
cc @pacoxu

Fix title of KEP 3673 in metadata

---

keps/sig-etcd/4743-kuberernetes-etcd-interface/README.md
keps/sig-etcd/4743-kuberernetes-etcd-interface/kep.yaml

- One-line PR description: Moving https://docs.google.com/document/d/1-nIpoW87qqQ9FxINOzXPkhu7CD_FWW1piYqHZDr39nU/edit?usp=sharing to KEP
- Issue link: https://github.com/kubernetes/enhancements/issues/4743
/cc @ahrtr @wojtek-t @dims @jpbetz @deads2k

KEP-4743: Kubernetes-etcd interface

---

keps/prod-readiness/sig-apps/4368.yaml
keps/sig-apps/4368-support-managed-by-for-batch-jobs/README.md
keps/sig-apps/4368-support-managed-by-for-batch-jobs/kep.yaml

One-line PR description: Update the KEP to prepare for update to Beta in 1.32
Issue link: https://github.com/kubernetes/enhancements/issues/4368
- Update the kep.yaml targeting Beta in 1.32
- Update the check box list
- Update the decision to make the field immutable
- Added a point to re-visit the decision wrt skip to enqueue
- Update the integration tests with links
- Update the implementation history
- Typo fixes
Graduation criteria:
*  Jobset test PR: https://github.com/kubernetes-sigs/jobset/pull/678 (5 runs, all passed on 1.30 & 1.31 with JobManagedBy enabled)
* Kueue test PR: https://github.com/kubernetes-sigs/kueue/pull/3074 (5 runs, all passed on 1.30 & 1.31 with JobManagedBy enabled)

Update "KEP-4368  Job API managed-by mechanism" targeting Beta in 1.32

---

keps/prod-readiness/sig-api-machinery/4358.yaml
keps/sig-api-machinery/4358-custom-resource-field-selectors/README.md
keps/sig-api-machinery/4358-custom-resource-field-selectors/kep.yaml

We realized when discussing informers that client side evaluation of field selectors is not possible since built-in field selectors have custom server-side logic and so it is not possible to perform client side field selection based purely on the name of the field selector.

Promote CRD field selectors to GA

---

keps/prod-readiness/sig-api-machinery/4420.yaml
keps/sig-api-machinery/4420-retry-generate-name/README.md
keps/sig-api-machinery/4420-retry-generate-name/kep.yaml

- One-line PR description: Promote RetryGenerateName to GA in 1.32
- Issue link: https://github.com/kubernetes/enhancements/issues/4420

KEP-4420: Promote RetryGenerateName to GA in 1.32

---

keps/prod-readiness/sig-node/2862.yaml
keps/sig-node/2862-fine-grained-kubelet-authz/README.md
keps/sig-node/2862-fine-grained-kubelet-authz/kep.yaml

- One-line PR description:  Adding a new KEP
- Issue link: #2862 

KEP-2862: Fine-grained Kubelet API Authorization

---

keps/prod-readiness/sig-node/4369.yaml
keps/sig-node/4369-allow-special-characters-environment-variable/README.md
keps/sig-node/4369-allow-special-characters-environment-variable/kep.yaml

- One-line PR description: promote feature gate to beta
- Issue link:

KEP-4369:  Promote to beta (allow ~all ASCII characters in env vars)

---

keps/sig-apps/4368-support-managed-by-for-batch-jobs/kep.yaml

One-line PR description: Bump latest-milestone to 1.32
Issue link: https://github.com/kubernetes/enhancements/issues/4368
- The main KEP update changes for 1.32 were done in https://github.com/kubernetes/enhancements/pull/4856, this PR is to align the omitted latest-milestone as per https://github.com/kubernetes/enhancements/issues/4368#issuecomment-2381647225

KEP4368-Job managedBy - update latest-milestone

---

keps/sig-node/3288-separate-stdout-from-stderr/README.md

Note down why we decide not to support the combination of `Stream` and `TailLines`.
Per https://github.com/kubernetes/kubernetes/pull/127360#discussion_r1765526177

feat: update kep 3288

---

keps/sig-scheduling/4247-queueinghint/README.md
keps/sig-scheduling/4247-queueinghint/kep.yaml

- One-line PR description: Update the metrics and beta criteria as we are targeting to enable the feature by default in v1.32.
- Issue link: https://github.com/kubernetes/enhancements/issues/4247

KEP-4247: Update criteria targeting to enable the QueueingHints by default

---

keps/sig-multicluster/1645-multi-cluster-services-api/README.md

- One-line PR description: This PR attempt to explain the reasons why the resolution algorithm was chosen by considering other conflict resolution algorithm in the alternatives sections and explaining why those were not selected.
- Issue link: #1645 
- Other comments: I tried to consider some other approaches based on what was discussed on the sig-multicluster meeting the 2024/04/30. However as this decision was made several years ago and I tried to fill the gap and imagine the reasons why those alternatives approach were not chosen, those reasons could not fully reflect what was brought up during this KEP original design. So if you remember some other reasons from that time (or any other reasons why we would not want to chose those) feel free to chime in!

KEP 1645: clarify the chosen conflict resolution algorithm

---

keps/prod-readiness/sig-apps/4026.yaml
keps/sig-apps/4026-crojob-scheduled-timestamp-annotation/README.md
keps/sig-apps/4026-crojob-scheduled-timestamp-annotation/kep.yaml

- One-line PR description: Promote job creation timestamp annotation to stable
- Issue link: https://github.com/kubernetes/enhancements/issues/4026
/assign @janetkuo @atiratree 
/cc @helayoty

KEP 4026: promote to stable

---

keps/sig-network/1860-kube-proxy-IP-node-binding/README.md

- One-line PR description: Add the implementation history section
- Issue link: https://github.com/kubernetes/enhancements/issues/1860

Add the implementation history section

---

keps/sig-auth/3331-structured-authentication-configuration/kep.yaml

- Update KEP latest milestone to `v1.32`.
- The feature will remain in beta in v1.32 but we plan to make some code changes in v1.32 release for metrics and tighter validation.
/sig auth
/assign enj

KEP-3331: update kep latest milestone to v1.32

---

keps/sig-cluster-lifecycle/kubeadm/4656-add-kubelet-instance-configuration/README.md
keps/sig-cluster-lifecycle/kubeadm/4656-add-kubelet-instance-configuration/kep.yaml

- One-line PR description: Add kubelet instance configuration to configure CRI socket for each node.
- Issue link: https://github.com/kubernetes/enhancements/issues/4654

kubeadm: Add kubelet instance configuration to configure CRI socket for each node

---

keps/sig-node/1029-ephemeral-storage-quotas/README.md

Modifications to push the changes to beta 1.31
KEP-1029: adding beta graduation criteria
One-line PR description: Adding Details about using Quotas in UserNamespace
Issue link: https://github.com/kubernetes/enhancements/issues/1029

Add details about using quotas in UserNamespaces in Proposal

---

keps/prod-readiness/sig-node/3960.yaml
keps/sig-node/3960-pod-lifecycle-sleep-action/README.md
keps/sig-node/3960-pod-lifecycle-sleep-action/kep.yaml

PodLifecycleSleepAction is planned to graduate to ga in 1.32.
- Issue link: https://github.com/kubernetes/enhancements/issues/3960

[KEP 3960]: Promote PodLifecycleSleepAction to stable 

---

keps/sig-node/3063-dynamic-resource-allocation/README.md
keps/sig-node/3063-dynamic-resource-allocation/kep.yaml

- One-line PR description: Classic DRA: withdraw the KEP
- Other comments: There isn't sufficient justification for keeping it around when there is no clear path forward.

KEP-3063: Classic DRA: withdraw the KEP

---

keps/prod-readiness/sig-cli/4292.yaml
keps/sig-cli/4292-kubectl-debug-custom-profile/README.md
keps/sig-cli/4292-kubectl-debug-custom-profile/kep.yaml

- One-line PR description:  Promote custom profiling in kubectl to GA
- Issue link: https://github.com/kubernetes/enhancements/issues/4292

Promote KEP-4292 custom profiling in kubectl debug to GA

---

keps/sig-multicluster/1645-multi-cluster-services-api/README.md

- One-line PR description: Remove MCS EndpointSlice ownership requirement
- Other comments: It was discussed at a recent sig meeting that the KEP shoudn't mandate an MCS EndpointSlice to have an OwnerReference to its ServiceImport as long as there is another cleanup mechanism in place.

KEP 1645: remove MCS EndpointSlice ownership requirement

---

keps/prod-readiness/sig-node/2535.yaml
keps/sig-node/2535-ensure-secret-pulled-images/README.md
keps/sig-node/2535-ensure-secret-pulled-images/kep.yaml

This PR modifies the original KEP according to recent discussions between sig-node and sig-auth.
- Issue link: https://github.com/kubernetes/enhancements/issues/2535
- Modify the strategy of the KEP from a feature-gated behavior goal to aim for an on-by-default feature.
- Remove the periodical cache cleanup mentions, defer it for a possible follow-up KEP.
- Stress that no unnecessary pulls should be performed so that registries' availability does not become blocking when it shouldn't be.
- Add TODOs for unresolved talking points.
/cc mikebrow haircommander enj liggitt pacoxu sairameshv

KEP-2535: update the KEP with on-by-default strategy

---

keps/prod-readiness/sig-node/4381.yaml
keps/sig-node/4381-dra-structured-parameters/README.md
keps/sig-node/4381-dra-structured-parameters/kep.yaml

- One-line PR description: PRR and API for beta of structured parameters in 1.32
Much of the PRR text that was originally written for "classic DRA" applies also to "structured parameters". It gets moved from #3063 to #4381, with some minor adaptions. The placeholder comments get restored in #3063 because further work on the KEP would be needed to move it forward - if it gets moved forward at all instead of being abandoned.
The v1beta1 API will be almost identical to the v1alpha3 API, with just some minor tweaks to fix oversights.
The kubelet gRPC gets bumped with no changes. Nonetheless, drivers should get updated, which can be done by updating the Go dependencies and optionally changing the API import.

KEP-4381: DRA: PRR and API for beta of structured parameters in 1.32

---

keps/sig-storage/1790-recover-resize-failure/README.md
keps/sig-storage/1790-recover-resize-failure/kep.yaml

xref https://github.com/kubernetes/enhancements/issues/1790
We are planning to move this feature to beta. The KEP has PRR review already filled in, but please do review closely, if I missed something.
/assign @jsafrane @deads2k

Move recover from volume expansion feature to beta

---

keps/sig-node/4603-tune-crashloopbackoff/README.md

- One-line PR description: Update testgrid/prow links in PRR
- Issue link: #4603 
- Other comments: Follow on PR addressing nit from https://github.com/kubernetes/enhancements/pull/4893#pullrequestreview-2355196871

KEP-4603: PRR testgrid/prow link updates

---

keps/prod-readiness/sig-instrumentation/4828.yaml
keps/sig-instrumentation/4828-component-flagz/README.md
keps/sig-instrumentation/4828-component-flagz/kep.yaml

- One-line PR description: Add a KEP for flagz page in Kubernetes components.
- Issue link: https://github.com/kubernetes/enhancements/issues/4828

KEP for flagz page for Kubernetes Components

---

keps/prod-readiness/sig-node/1967.yaml
keps/sig-node/1967-size-memory-backed-volumes/README.md
keps/sig-node/1967-size-memory-backed-volumes/kep.yaml

- One-line PR description: Promote 1967 to stable.
- Issue link: #1967 

KEP-1967: promote size memory backed volumes to stable

---

keps/prod-readiness/sig-auth/4412.yaml
keps/sig-auth/4412-projected-service-account-tokens-for-kubelet-image-credential-providers/README.md
keps/sig-auth/4412-projected-service-account-tokens-for-kubelet-image-credential-providers/kep.yaml

- One-line PR description: Add Projected Service Account Tokens for Kubelet Image Credential Providers alpha KEP

KEP-4412: Projected Service Account Tokens for Kubelet Image Credential Providers

---

keps/prod-readiness/sig-auth/740.yaml
keps/sig-auth/740-service-account-external-signing/README.md
keps/sig-auth/740-service-account-external-signing/kep.yaml

- One-line PR description: Update KEP for External ServiceAccount JWT signing
- Issue link: #740 
- The KEP was marked `provisional` in #3653 due to being stale for over 3 years.
- This PR attempts to bring the KEP up to speed with recent changes.
- The intention is that underlying implementation can be picked back up.
- A consensus regarding external JWT signing was achieved in the community (as documented [here](https://docs.google.com/document/d/1QVtBX8J2Tk70toefDegXMXigMFzrdQfezjlhBrKR29Y/edit?tab=t.0))

update KEP 740

---

keps/prod-readiness/sig-auth/4317.yaml
keps/sig-auth/4317-pod-certificates/README.md
keps/sig-auth/4317-pod-certificates/kep.yaml

This PR adds the initial content for KEP-4317, which outlines machinery for:
* Representing pod identities in X.509 certificates and certificate requests,
* Generically provisioning certificates to pods,
* Specifically provisioning kube-apiserver client certificates to pods, and
* Using pod identity certificates to authenticate to kube-apiserver,.
This KEP is still in the draft/discussion phase.  Significant changes are anticipated based on review and discussion in SIG Auth.
- Issue link: https://github.com/kubernetes/enhancements/issues/4317
- Draft implementation: https://github.com/kubernetes/kubernetes/pull/121596

KEP-4317: Pod Certificates

---

keps/sig-node/2837-pod-level-resource-spec/README.md

/sig node
KEP: https://github.com/kubernetes/enhancements/pull/4678
Added following:
* validation rule to check user is not using in-place pod resize feature
* Burstable pods vs pod-level resources resource sharing

Adding more details to KEP for Pod Level Resources

---

keps/sig-node/3695-pod-resources-for-dra/README.md
keps/sig-node/3695-pod-resources-for-dra/kep.yaml

- One-line PR description: Update KEP 3695 to reflect current implementation
- Issue link: [KEP-3695](https://github.com/kubernetes/enhancements/issues/3695)
- Other comments: as per the discussion on https://github.com/kubernetes/enhancements/issues/3695 I have removed all references to Networking to focus solely on the Node elements for this KEP.

KEP-3695: Update podResourceV1 API

---

keps/prod-readiness/sig-windows/4802.yaml
keps/sig-windows/4802-windows-node-shutdown/README.md
keps/sig-windows/4802-windows-node-shutdown/kep.yaml

This is to implement node shutdown feature for windows node, comparable with linux part, which is describe in KEP-2000
- Issue link: https://github.com/kubernetes/enhancements/issues/4802
code PR: https://github.com/kubernetes/kubernetes/pull/127404

Add KEP 4802 - windows node shutdown

---

keps/sig-node/753-sidecar-containers/README.md

- Issue link: #753
https://github.com/kubernetes/kubernetes/issues/120234
The implementation is different from the current documentation.
This updates the documentation to clarify the relationship between the container-level restartPolicy and the pod-level restartPolicy.
We may introduce a new concept (or policy) for the restart behavior of the initialization.
/cc @SergeyKanzhelev

KEP-753: Update documentation to clarify `restartPolicy` behavior

---

keps/prod-readiness/sig-node/4815.yaml
keps/sig-node/4815-dra-partitionable-devices/README.md
keps/sig-node/4815-dra-partitionable-devices/kep.yaml

* One-line PR description: Adding new KEP for Partitionable Devices in DRA
* Issue link: https://github.com/kubernetes/enhancements/issues/4815
* Other comments:

KEP-4815: DRA Partitionable Devices

---

keps/sig-auth/3257-cluster-trust-bundles/README.md
keps/sig-auth/3257-cluster-trust-bundles/kep.yaml

Adds a mention of a new default trust bundle and its signer + one more non-goal
- Issue link: #3257 
/cc ahmedtd enj liggitt

KEP-3257: cluster trust bundles: add a new in-tree signer and its CTB

---

keps/prod-readiness/sig-storage/3476.yaml
keps/sig-storage/3476-volume-group-snapshot/README.md
keps/sig-storage/3476-volume-group-snapshot/kep.yaml

The PR updates VolumeGroupSnapshot KEP to target Beta in 1.32.
- Issue link: https://github.com/kubernetes/enhancements/issues/3476

Update VolumeGroupSnapshot KEP for Beta

---

keps/prod-readiness/sig-node/4817.yaml
keps/sig-node/4817-resource-claim-device-status/README.md
keps/sig-node/4817-resource-claim-device-status/kep.yaml

- One-line PR description: Add driver-owned fields in ResourceClaim.Status with possible standardized network interface data
- Issue link: https://github.com/kubernetes/enhancements/issues/4817
I would like to get early feedback for this KEP document.
Please take a look at the drawbacks as this is uncertain to me. It is probably related to the [discussion to include the device state as part of the `Pod.Status`](https://kubernetes.slack.com/archives/C0409NGC1TK/p1726679433650409).
I followed option 5 here: https://docs.google.com/document/d/1smjEm7WxFm8btQwywdr_F5BZkiifatNqDvrQUaesu1M/edit?usp=sharing and this PoC here: https://gist.github.com/LionelJouin/5cfc11eecf73663b5657ed3be1eb6c00

[KEP-4817]: DRA: Resource Claim Status with possible standardized network interface data

---

keps/prod-readiness/sig-windows/4885.yaml
keps/sig-windows/4885-windows-cpu-and-memory-affinity/README.md
keps/sig-windows/4885-windows-cpu-and-memory-affinity/kep.yaml

- One-line PR description: Add CPU and memory Affinity support to Windows nodes with CPUManager, MemoryManager and Topology manager
- Issue link: https://github.com/kubernetes/enhancements/issues/4885

KEP-4885: Windows CPU and Memory Affinity

---

keps/sig-node/4680-add-resource-health-to-pod-status/README.md
keps/sig-node/4680-add-resource-health-to-pod-status/kep.yaml

/sig node
/cc @johnbelamaric 
KEP: https://github.com/kubernetes/enhancements/issues/4680

updates to device failures for alpha2

---

keps/sig-api-machinery/4222-cbor-serializer/README.md

- One-line PR description: One of the KEP requirements is to demonstrate spec conformance for a CBOR implementation in one of the supported Kubernetes client languages, other than Go. An evaluation was performed using a Python implementation.
- Issue link: https://github.com/kubernetes/enhancements/issues/4222

KEP-4222: Add link to Python spec conformance demo.

---

keps/sig-node/4369-allow-special-characters-environment-variable/README.md

- One-line PR description: Fixed incorrect description when promoting to beta stage
- Issue link: https://github.com/kubernetes/enhancements/issues/4369

KEP-4396 Fix beta stage description

---

keps/sig-cli/3104-introduce-kuberc/README.md

- One-line PR description: Update fields with finalized version of Preference in https://github.com/kubernetes/kubernetes/pull/125230 

Update kuberc example with finalized version

---

keps/sig-node/4381-dra-structured-parameters/README.md

- One-line PR description: DRA: update unit test coverage for 1.32
- Issue link: #4381 
- Other comments: This is close to what the code coverage will be in 1.32.
Fixes: https://github.com/kubernetes/kubernetes/issues/127949

DRA: update unit test coverage for 1.32

---

keps/sig-architecture/4330-compatibility-versions/README.md

- One-line PR description: add linting as beta criteria
- Other comments: As discussed in
https://github.com/kubernetes/kubernetes/pull/125830#issuecomment-2261025071, the stand-alone linter was okay as the initial solution, but integration into golangci-lint is expected to perform better and thus should be done before graduation to beta.

4330: compatibility versions: add linting as beta criteria

---

keps/sig-api-machinery/3962-mutating-admission-policies/README.md

This is only a clarification, the goals of the KEP are unchanged.
/assign @Jefftree

Clarify JSON Patch support in mutating admission policy

---

keps/sig-auth/3257-cluster-trust-bundles/README.md

- One-line PR description: Updating the label `kubernetes.io/cluster-trust-bundle-version` to `k8s.example/cluster-trust-bundle-version` as per the discussion on https://github.com/kubernetes/website/issues/41481#issuecomment-2200910649
- Issue link: https://github.com/kubernetes/enhancements/issues/3257

updating label in KEP-3257

---

keps/sig-cli/4706-deprecate-and-remove-kustomize/README.md
keps/sig-cli/4706-deprecate-and-remove-kustomize/kep.yaml

- One-line PR description: update KEP status to rejected following sig-arch discussion, see [this comment](https://github.com/kubernetes/enhancements/issues/4706#issuecomment-2506018548)
- Issue link: https://github.com/kubernetes/enhancements/issues/4706
/assign @ardaguclu @eddiezane @mpuckett159

KEP-4706: update its status to rejected, after sig-arch discussion

---

keps/sig-multicluster/1645-multi-cluster-services-api/README.md

- One-line PR description: Clarify port conflict rules based on Service port rules
- Other comments: The existing version of the KEP doesn't state explicitly the associated Service port rules and what should be implemented is confusing here and prone to implementation errors.

KEP 1645: clarify port conflict rules

---

keps/sig-multicluster/1645-multi-cluster-services-api/README.md

- One-line PR description: add labels and annotations export
- Other comments: Add new fields in the ServiceExport resources to sync labels and annotations. This approach is inspired by the GatewayAPI (https://gateway-api.sigs.k8s.io/geps/gep-1762/#labels-and-annotations) one to have dedicated fields for that and there's some explanation inline in the KEP why we might favor that.

KEP 1645: add labels and annotations export

---

OWNERS_ALIASES

Add myself (@xmudrii) as a SIG K8s Infra Tech Lead.
**Which issue(s) this PR fixes**:
xref https://github.com/kubernetes/community/issues/8204
/assign @BenTheElder @dims @ameukam @upodroid

Add xmudrii as K8s Infra Tech Lead

---

keps/prod-readiness/sig-network/1880.yaml
keps/sig-network/1880-multiple-service-cidrs/README.md
keps/sig-network/1880-multiple-service-cidrs/kep.yaml

- One-line PR description: graduate to ga
- Issue link: https://github.com/kubernetes/enhancements/issues/1880
There was only one bug opened during this time https://github.com/kubernetes/kubernetes/issues/127588 that was caused by a copy and paste error.
It is available in GKE https://cloud.google.com/kubernetes-engine/docs/how-to/use-beta-apis and used in production clusters.
It can be used by OSS users with installers that allow to set the feature gates and enable the beta apis, see kops https://github.com/kubernetes/test-infra/pull/33864/
It is been tested by the community https://github.com/spidernet-io/spiderpool/pull/4089#issuecomment-2505499043
There is also an external blog about it https://engineering.doit.com/scaling-kubernetes-how-to-seamlessly-expand-service- …

KEP 1880: graduation to GA

---

keps/sig-network/1880-multiple-service-cidrs/README.md

- One-line PR description: Graduate to GA KEP-1880 but don't lock it by default
- Issue link: https://github.com/kubernetes/enhancements/issues/1880
- Other comments: This change requires an action item on infrastructure providers or components that depend on the convention that the Service CIDR on the cluster was unique and immutables, also, the restriction of disabling beta APIs by default made that the signal is still low for a complex feature of this magnitude.
Net setting the feature gate locked by default allow infrastructure providers and users to still disable the feature gate without having to install webhooks or Validating Admission Policies.

KEP-1880: don't lock ServiceCIDR by default

---

keps/sig-auth/4412-projected-service-account-tokens-for-kubelet-image-credential-providers/kep.yaml

- Update KEP alpha and latest milestone to `v1.33`.
/sig auth
/assign enj

KEP-4412: update alpha and latest milestone to v1.33

---

keps/sig-auth/3331-structured-authentication-configuration/kep.yaml

- Update KEP latest milestone to `v1.33`.
- The feature will remain in beta in v1.33 but we plan to make some code changes in v1.33 release for metrics.
/sig auth
/assign enj

KEP-3331: update kep latest milestone to v1.33

---

keps/prod-readiness/sig-storage/2589.yaml
keps/sig-storage/2589-csi-migration-portworx/README.md
keps/sig-storage/2589-csi-migration-portworx/kep.yaml

- One-line PR description: Update KEP for Portworx CSI Migration
- Issue link: https://github.com/kubernetes/enhancements/issues/2589
- Other comments: This PR adds the details to the KEP for promoting Portworx CSI migration to GA in v1.33
/sig storage

KEP-2589: Promote Portworx CSI migration to GA in 1.33

---

keps/sig-auth/3257-cluster-trust-bundles/kep.yaml

- One-line PR description: bump latest milestone for ClusterTrustBundles up a version
- Issue link: https://github.com/kubernetes/enhancements/issues/3257

KEP-3257: bump CTB beta/latest-milestone to 1.33

---

keps/sig-storage/3751-volume-attributes-class/README.md

- One-line PR description: Add Quota with Scope Design Details of VolumeAttributesClass
- Issue link:
- Other comments: discussed in the api-machinery meeting, [the quota restriction should not block status update](https://docs.google.com/document/d/1x9RNaaysyO0gXHIr1y50QFbiL1x8OWnk2v3XnrdkT5Y/edit?tab=t.0#bookmark=id.dzxerooqaesh).

Add Quota with Scope Design Details of VolumeAttributesClass

---

api/approval.go
api/proposal.go
keps/NNNN-kep-template/kep.yaml

- One-line PR description:  Clarify the stage name of deprecated feature gates
- Issue link:
- Other comments: This is a trivial matter, but we had some discussions about it before, so I would like to bring it up here for further discussion. Ref: https://github.com/kubernetes/enhancements/pull/4803/files#r1747083311
For us, deprecating a user-visible feature, or adding a bug fix that could be seen as 'removal', requires a small KEP for discussion and to document them and we also should add a Deprecated feature gate for such cases.
For these Deprecated feature gates, their lifecycle is shorter than a full feature gate lifecycle, typically following featuregate.Deprecated → wait a few releases → remove. So, we only need two phases to describe them, but we haven't clearly defined the names …

KEP-Template: Clarify the stage name of deprecated feature gates

---

keps/sig-scheduling/4247-queueinghint/kep.yaml

- One-line PR description: Change the beta milestone to v1.32
- Issue link: https://github.com/kubernetes/enhancements/issues/4247
- Other comments: So, the context is that we once graduate it as beta at v1.28, but we soon reverted it because we found a memory leak bug. v1.32 fixes the bug, and we tried again to graduate it to beta. So, I believe we should note the graduation of beta was v1.32.

KEP-4247: correct the milestone at kep.yaml

---

api/approval.go
api/approval_test.go

- One-line PR description: Fix some validation bugs/issues that were introduced in https://github.com/kubernetes/enhancements/pull/4898.
The validation assumes release stages for a feature to only be Alpha->Beta->Stable but now we have another sort of release for removal of functionality that follows Deprecated->Disabled->Removed stages, so we need to update the KEP unit and verification tests to support these types of KEP proposals.
- Issue link:

KEP-Template: Fix KEP validation to correctly handle deprecated->disabled->removed releases.

---

keps/prod-readiness/sig-node/3386.yaml
keps/sig-node/3386-kubelet-evented-pleg/README.md
keps/sig-node/3386-kubelet-evented-pleg/kep.yaml

- One-line PR description: Sync status of the feature, reverted to alpha
- Issue link: https://github.com/kubernetes/enhancements/issues/3386

sync EventedPLEG status after the revert change

---

keps/sig-autoscaling/853-configurable-hpa-scale-velocity/README.md

- One-line PR description: This fixes the value of the periodSeconds field in the example for the stabilization window in HPA scale down behavior.
- Other comments: The text under the example talks about how the scale down behavior will be limited to 5 pods per minute, however, the periodSeconds field is set to 600s (10m).

N/A: Fixed periodSeconds in HPA scaleDown example

---

keps/prod-readiness/sig-node/2862.yaml
keps/sig-node/2862-fine-grained-kubelet-authz/README.md
keps/sig-node/2862-fine-grained-kubelet-authz/kep.yaml

- One-line PR description: Graduate KEP-2862 to BETA.
- Issue link: #2862 

KEP-2862: Graduate to BETA.

---

keps/prod-readiness/sig-storage/1495.yaml
keps/sig-storage/1495-volume-populators/README.md
keps/sig-storage/1495-volume-populators/kep.yaml

Update Release Signoff Checklist from Template for KEP-1495 Volume Populators
- Issue link: https://github.com/kubernetes-csi/lib-volume-populator/issues/180
- Other comments: GA tasks are tracked in https://github.com/kubernetes-csi/lib-volume-populator/issues?q=is%3Aissue+%22GA+Blocker%22

Update Release Signoff Checklist for KEP-1495 Volume Populators

---

keps/sig-autoscaling/4951-configurable-hpa-tolerance/kep.yaml

Set the expected alpha milestones to v1.33.
KEP discussion: https://github.com/kubernetes/kubernetes/issues/116984

KEP-4951: Update alpha milestones to v1.33.

---

keps/sig-scheduling/3243-respect-pod-topology-spread-after-rolling-upgrades/README.md

- One-line PR description: As discussed [#129480](https://github.com/kubernetes/kubernetes/issues/129480#issuecomment-2575417106), I've updated this KEP related to 
labelSelector.
- Issue link: https://github.com/kubernetes/enhancements/issues/3243

KEP-3243: Update the design to mutate the label selector based on matchLabelKeys at api-server instead of the scheduler handling it

---

keps/prod-readiness/sig-storage/4876.yaml
keps/sig-storage/4876-mutable-csinode-allocatable/README.md
keps/sig-storage/4876-mutable-csinode-allocatable/kep.yaml

- One-line PR description: This PR adds a new KEP for Mutable CSINode Allocatable Property.
- Issue link: https://github.com/kubernetes/enhancements/issues/4876

KEP-4876: Mutable CSINode Allocatable Property

---

keps/sig-node/2535-ensure-secret-pulled-images/kep.yaml

- One-line PR description: bump latest milestone/alpha for Ensure secret-pulled images up a version
- Issue link: https://github.com/kubernetes/enhancements/issues/2535

KEP-2535: bump ensure secret images alpha/latest-milestone to 1.33

---

keps/sig-architecture/4330-compatibility-versions/README.md

update minCompatibilityVersion range to make it more consistent and clear.

KEP-4330: update minCompatibilityVersion range.

---

keps/sig-scheduling/4816-dra-prioritized-list/README.md
keps/sig-scheduling/4816-dra-prioritized-list/kep.yaml

- One-line PR description: Updates to the KEP to reflect changes discussed on the PR https://github.com/kubernetes/kubernetes/pull/128586
- Issue link: https://github.com/kubernetes/enhancements/issues/4816

KEP-4816 DRA Prioritized List design update

---

.github/ISSUE_TEMPLATE/enhancement.md

GitHub issue templates must now be put into the ISSUE_TEMPLATE dir and have the metadata at the top.

Fix github issue template

---

keps/sig-node/4265-proc-mount/README.md
keps/sig-node/4265-proc-mount/kep.yaml

update timeline and release to reflect it will go on by default in 1.33, in line with user namespaces
- Issue link: https://github.com/kubernetes/enhancements/issues/4265

KEP-4265: move to on by default beta

---

keps/sig-node/127-user-namespaces/README.md
keps/sig-node/127-user-namespaces/kep.yaml

update user namespace KEP to be on by default beta
- Issue link:
- https://github.com/kubernetes/enhancements/issues/127

KEP-127: update beta to be on by default

---

keps/sig-node/3288-separate-stdout-from-stderr/kep.yaml

The feature gate has been renamed to PodLogsQuerySplitStreams
- Issue link: https://github.com/kubernetes/enhancements/issues/3288

KEP-3288: correct the feature gate's name

---

keps/prod-readiness/sig-network/4427.yaml
keps/sig-network/4427-relaxed-dns-search-validation/README.md
keps/sig-network/4427-relaxed-dns-search-validation/kep.yaml

- One-line PR description: Updates sections for beta release targeting 1.33
- Issue link: https://github.com/kubernetes/enhancements/issues/4427
- Other comments: This is my first time doing this. I think I covered everything, but forgive me if I missed something
/sig network
/assign aojea danwinship thockin
PRR reviewers:
/assign jpbetz

KEP-4427: Relaxed DNS search validation to beta

---

keps/prod-readiness/sig-storage/5040.yaml
keps/sig-storage/5040-remove-gitrepo-driver/README.md
keps/sig-storage/5040-remove-gitrepo-driver/kep.yaml

- One-line PR description: Initial KEP to remove support for gitRepo volume driver.
- Issue link: #5040 

KEP-5040: Remove gitRepo volume driver.

---

keps/prod-readiness/sig-node/753.yaml
keps/sig-node/753-sidecar-containers/README.md
keps/sig-node/753-sidecar-containers/kep.yaml

SidecarContainer feature is going GA.
- Issue link:
#753
All bugs listed were reviewed and are not critical for GA promotion.

KEP 753: SidecarContainers is GA

---

keps/sig-architecture/4330-compatibility-versions/README.md

- One-line PR description: change api availability to forward compatible to make it easier to handle API graduation in compatibility version. 
- Other comments: more discussions can be found in https://github.com/kubernetes/kubernetes/issues/127791

KEP-4330: Change API availability to forward compatibility

---

keps/prod-readiness/sig-api-machinery/5080.yaml
keps/sig-api-machinery/5080-ordered-namespace-deletion/README.md
keps/sig-api-machinery/5080-ordered-namespace-deletion/kep.yaml

- One-line PR description: Add the KEP for ordered namespace deletion.
- Issue link: https://github.com/kubernetes/enhancements/issues/5080

[KEP 5080]Ordered Namespace Deletion

---

keps/sig-instrumentation/647-apiserver-tracing/kep.yaml

- One-line PR description: update milestone for stable to 1.33

KEP-647: update stable milestone to 1.33

---

keps/sig-auth/3926-handling-undecryptable-resources/kep.yaml

- One-line PR description: KEP-3926: update KEP latest milestone to v1.33 as implementable
- Issue link: https://github.com/kubernetes/enhancements/issues/3926

KEP-3926: update KEP latest milestone to v1.33 as implementable

---

keps/sig-node/127-user-namespaces/README.md

- One-line PR description: KEP-127 (UserNS): allow customizing subids length
- Issue link:  #127
The number of subuids and subgids for each of pods is hard-coded to 65536, regardless to the total ID count specified in `/etc/subuid` and `/etc/subgid`: https://github.com/kubernetes/kubernetes/blob/v1.32.0/pkg/kubelet/userns/userns_manager.go#L211-L228
This is not enough for some images.
Nested containerization needs a huge number of subids too.

KEP-127 (UserNS): allow customizing subids length  

---

keps/sig-autoscaling/853-configurable-hpa-scale-velocity/README.md

A YAML example has 600 as value for the `periodSeconds` attribute, but in the text below it is referenced as a minute. The value should therefore be 60 to avoid confusion for the reader.

Fix typo in HPA scale velocity document

---

keps/sig-node/4680-add-resource-health-to-pod-status/kep.yaml

I didn't merge it last release. Nothing changed except the milestones.
- Issue link: https://github.com/kubernetes/enhancements/issues/4680
/sig node

bump the release for Add Resource Health Status to the Pod Status for Device Plugin and DRA

---

keps/prod-readiness/sig-node/2902.yaml
keps/sig-node/2902-cpumanager-distribute-cpus-policy-option/README.md
keps/sig-node/2902-cpumanager-distribute-cpus-policy-option/kep.yaml

- One-line PR description: Add CPUManager policy option to distribute CPUs across NUMA nodes instead of packing them
- Issue link: https://github.com/kubernetes/enhancements/issues/2902
- Other comments: Introduced as an alpha feature in v1.23

KEP-2902: Promote CPUManager policy option to distribute CPUs across NUMA nodes to Beta

---

keps/prod-readiness/sig-apps/3850.yaml
keps/sig-apps/3850-backoff-limits-per-index-for-indexed-jobs/README.md
keps/sig-apps/3850-backoff-limits-per-index-for-indexed-jobs/kep.yaml

One-line PR description: Prepare graduation of KEP3850 Backoff Limit Per Index for Jobs to stable
Issue link: https://github.com/kubernetes/enhancements/issues/3850

KEP3850: graduate Backoff Limit Per Index for Job to stable

---

keps/prod-readiness/sig-apps/3998.yaml
keps/sig-apps/3998-job-success-completion-policy/README.md
keps/sig-apps/3998-job-success-completion-policy/kep.yaml

- One-line PR description: Graduate JobSuccessPolicy to GA.
- Issue link: https://github.com/kubernetes/enhancements/issues/3998

KEP-3998: Graduate JobSuccessPolicy to GA

---

keps/sig-api-machinery/3157-watch-list/README.md

xref: https://github.com/kubernetes/kubernetes/pull/126996

KEP 3157 (watch-list): new GA criterion for supporting AcceptContentType=application/json;as=Table

---

keps/sig-api-machinery/3157-watch-list/README.md

- One-line PR description: Update KEP 3157 (watch-list) for milestone 1.33

Update KEP 3157 (watch-list) for milestone 1.33

---

keps/sig-ui/5008-kep-template/README.md
keps/sig-ui/5008-kep-template/kep.yaml
keps/sig-ui/OWNERS

- One-line PR description: Adding new KEP 5008 for introducing a Kubernetes Desktop project
- Issue link: https://github.com/kubernetes/enhancements/issues/5008

KEP-5008: Introduce Kubernetes Desktop

---

keps/prod-readiness/sig-network/4974.yaml
keps/sig-network/4974-deprecate-endpoints/README.md
keps/sig-network/4974-deprecate-endpoints/kep.yaml

```
The `v1.Endpoints` API has been essentially deprecated since
EndpointSlices became GA in 1.21. Several new Service features (such
as dual-stack and topology, not to mention "services with more than
1000 endpoints") are implemented only for EndpointSlice, not for
Endpoints. Kube-proxy no longer uses Endpoints ever, for anything, and
the Gateway API conformance tests also require implementations to use
EndpointSlices.
Despite this, kube-controller-manager still does all of the work of
managing Endpoints objects for all Services, and a cluster cannot pass
the conformance test suite unless the Endpoints and EndpointSlice
Mirroring controllers are running, even though in many cases nothing
will ever look at the output of the Endpoints controller (and the
EndpointSlice Mirroring controller …
```

KEP-4974: initial proposal for deprecating v1.Endpoints

---

keps/prod-readiness/sig-network/2433.yaml
keps/sig-network/2433-topology-aware-hints/README.md
keps/sig-network/2433-topology-aware-hints/kep.yaml

- One-line PR description: Update KEP-2433 to indicate that only the `Hints` field is planned to graduate to GA as part of this KEP
- Issue link: https://github.com/kubernetes/enhancements/issues/2433
- I've been scratching my head to find the right balance between updating the KEP to reflect only the `Hints` graduating while still maintaining all the valuable information present here. I didn't find that perfect balance and have started out with adding an explanatory note towards the beginning and some minor updates elsewhere. Happy to iterate on any feedback received.
/cc @robscott 
/assign @aojea @danwinship @thockin

KEP-2433: Graduate Topology Aware Hints with only the Hints field to GA

---

keps/prod-readiness/sig-storage/1710.yaml
keps/sig-storage/1710-selinux-relabeling/README.md
keps/sig-storage/1710-selinux-relabeling/kep.yaml

- One-line PR description: Update the KEP with current development (1.32/33) and a plan to graduate to Beta in 1.33
- Other comments: See individual small commits.
* Specify SELinux controller tests.
* Add notes about other Linux distros (tested on Debian).
* Add a note that the controller / KCM cannot implement SELinux label defaulting.

1710: selinux: Update the KEP for 1.33 and graduate to Beta

---

keps/prod-readiness/sig-node/2625.yaml
keps/sig-node/2625-cpumanager-policies-thread-placement/README.md
keps/sig-node/2625-cpumanager-policies-thread-placement/kep.yaml

- One-line PR description: CPU Manager Policy option `full-pcpus-only` 1.33 GA
- Issue link: https://github.com/kubernetes/enhancements/issues/2625
* Introduced as an alpha feature in 1.22 https://github.com/kubernetes/kubernetes/pull/101432
* Graduated as beta feature in 1.23 https://github.com/kubernetes/enhancements/pull/2933
* The GA graduation would mean:
*  the `full-pcpus-only` option [will graduate to GA](https://github.com/kubernetes/kubernetes/blob/v1.32.1/pkg/kubelet/cm/cpumanager/policy_options.go#L51)
* the `CPUManagerPolicyOptions` [master FG](https://github.com/kubernetes/kubernetes/blob/v1.32.1/pkg/features/kube_features.go#L125) will be locked to true, and removed 3 versions later

KEP-2625: Promote the CPUManager Policy Option `full-pcpus-only` to GA

---

keps/prod-readiness/sig-cli/2590.yaml
keps/sig-cli/2590-kubectl-subresource/README.md
keps/sig-cli/2590-kubectl-subresource/kep.yaml

- One-line PR description: Graduate kubectl subresource to GA
- Issue link: https://github.com/kubernetes/enhancements/issues/2590
- Other comments: this PR is composed from changes from the original PR (https://github.com/kubernetes/enhancements/pull/4468) which tried to promote this feature to GA, and my updates to match current template and addressing review comments from that other PR. 
/assign @MadhavJivrajani @nikhita 
for reviews
/assign @ardaguclu 
for sig-cli approval
for prr approval

KEP 2590: Graduate kubectl subresource to GA

---

keps/prod-readiness/sig-node/4818.yaml
keps/sig-node/4818-allow-zero-value-for-sleep-action-of-prestop-hook/README.md
keps/sig-node/4818-allow-zero-value-for-sleep-action-of-prestop-hook/kep.yaml

- One-line PR description: KEP update for KEP #4818 for beta graduation
- Issue link: #4818

KEP 4818: Promote zero value for Pod Lifecycle Sleep action to beta

---

keps/prod-readiness/sig-network/4444.yaml
keps/sig-network/4444-service-traffic-distribution/README.md
keps/sig-network/4444-service-traffic-distribution/kep.yaml

- One-line PR description: Rename PreferClose option to PreferSameZone
- Issue link: https://github.com/kubernetes/enhancements/issues/4444
/assign @aojea @danwinship @thockin

KEP-4444: Graduate trafficDistribution:PreferClose to GA

---

keps/prod-readiness/sig-node/4817.yaml
keps/sig-node/4817-resource-claim-device-status/README.md
keps/sig-node/4817-resource-claim-device-status/kep.yaml

- One-line PR description: Add beta graduation criteria + implementation history
- Issue link: https://github.com/kubernetes/enhancements/issues/4817
- Other comments: KEP-4817

KEP-4817: Add beta graduation criteria + implementation history

---

keps/prod-readiness/sig-network/4858.yaml
keps/sig-network/4858-ip-cidr-validation/README.md
keps/sig-network/4858-ip-cidr-validation/kep.yaml

- One-line PR description: Initial draft of KEP-4858 IP/CIDR Validation Improvements
- Issue link: https://github.com/kubernetes/enhancements/issues/4858

KEP-4858: IP/CIDR Validation Improvements

---

keps/prod-readiness/sig-node/3619.yaml
keps/sig-node/3619-supplemental-groups-policy/README.md
keps/sig-node/3619-supplemental-groups-policy/kep.yaml

- One-line PR description: updated Production Readiness Review Questionnaire for beta release
- Issue link: #3619 
- Other comments: None.

KEP-3619: updated Production Readiness Review Questionnaire for beta release

---

keps/sig-node/4603-tune-crashloopbackoff/kep.yaml

- One-line PR description: Bumping kep.yaml to represent this is still actively in progress in 1.33
- Issue link: https://github.com/kubernetes/enhancements/issues/4603

KEP-4603: Track latest milestone as 1.33

---

keps/prod-readiness/sig-autoscaling/4951.yaml
keps/sig-autoscaling/4951-configurable-hpa-tolerance/README.md
keps/sig-autoscaling/4951-configurable-hpa-tolerance/kep.yaml

Add files needed to start the PRR process.
[Issue link](https://github.com/kubernetes/enhancements/issues/4951).

KEP-4951: Fill PRR questionnaire

---

keps/prod-readiness/sig-scheduling/5027.yaml
keps/prod-readiness/sig-scheduling/5055.yaml
keps/sig-scheduling/5027-dra-admin-controlled-device-attributes/README.md
keps/sig-scheduling/5027-dra-admin-controlled-device-attributes/kep.yaml
keps/sig-scheduling/5055-dra-device-taints-and-tolerations/README.md
keps/sig-scheduling/5055-dra-device-taints-and-tolerations/kep.yaml

- One-line PR description: DRA: admin-controlled device attributes + taints
- Issue links:
- https://github.com/kubernetes/enhancements/issues/5027
- https://github.com/kubernetes/enhancements/issues/5055
- Other comments: first revision
/cc @johnbelamaric

KEP-5027 + 5055: DRA: admin-controlled device attributes + taints

---

keps/prod-readiness/sig-windows/5100.yaml
keps/sig-windows/5100-windows-dsr-and-overlay-support/README.md
keps/sig-windows/5100-windows-dsr-and-overlay-support/kep.yaml

- One-line PR description: Retroactive KEP for WinDSR and WinOverlay
- Issue link: https://github.com/kubernetes/enhancements/issues/5100
/milestone v1.33
/sig windows network
/wip

5100: Adding retroactive KEP for WinDSR and WinOverlay

---

keps/prod-readiness/sig-node/4639.yaml
keps/sig-node/4639-oci-volume-source/README.md
keps/sig-node/4639-oci-volume-source/kep.yaml

- One-line PR description: bump https://github.com/kubernetes/enhancements/issues/4639 to beta
- Issue link: https://github.com/kubernetes/enhancements/issues/4639
- Other comments: @saschagrunert is on leave this week and is the primary author of this KEP, I am opening this in his stead to get it on PRR radar, but it may change once he returns.

KEP-4639: update to most recent implementation state and graduate to beta

---

keps/prod-readiness/sig-node/5067.yaml
keps/sig-node/5067-pod-generation/README.md
keps/sig-node/5067-pod-generation/kep.yaml

- One-line PR description: Create new KEP 5067: Pod Generation
- Issue link: https://github.com/kubernetes/enhancements/issues/5067

KEP 5067: Pod Generation KEP creation

---

keps/sig-node/3673-kubelet-parallel-image-pull-limit/kep.yaml

- One-line PR description: Update the status of the KEP
- Adding e2e test means the FG is beta: https://github.com/kubernetes/kubernetes/pull/121604. Not FG.
- Issue link: #3673

[cleanup] update KEP-3673 status: e2e added in v1.32 for beta

---

keps/sig-node/753-sidecar-containers/README.md

- One-line PR description: update OOM score calculation. 
- Issue link: https://github.com/kubernetes/enhancements/issues/753
- Other comments : 
The OOM adjustment for sidecar container will match or **fall below** the OOM score adjustment of regular containers in the Pod.

KEP-753: SidecarContainers update oom score adj logic

---

keps/prod-readiness/sig-instrumentation/2831.yaml
keps/sig-instrumentation/2831-kubelet-tracing/README.md
keps/sig-instrumentation/2831-kubelet-tracing/kep.yaml

- One-line PR description: updating stable target for 1.33

KEP-2831: update kubelet tracing KEP to target GA in 1.33

---

keps/sig-storage/4049-storage-capacity-scoring-of-nodes-for-dynamic-provisioning/README.md

- One-line PR description: Update KEP readme to use the latest template and add explanation about [this discussion](https://kubernetes.slack.com/archives/C09QZFCE5/p1737426940201959).
- Issue link: https://github.com/kubernetes/enhancements/issues/4049

KEP-4049: Update KEP readme

---

keps/sig-node/2837-pod-level-resource-spec/README.md
keps/sig-node/2837-pod-level-resource-spec/kep.yaml

- One-line PR description: Details about IPPR, memory manager, and huge pages for another alpha in 1.33
- Issue link: https://github.com/kubernetes/enhancements/issues/2837

KEP-2837: PodLevelResources changes for 1.33 alpha stage

---

keps/prod-readiness/sig-api-machinery/4355.yaml
keps/sig-api-machinery/4355-coordinated-leader-election/README.md
keps/sig-api-machinery/4355-coordinated-leader-election/kep.yaml

- One-line PR description: Add beta requirements for Coordinated Leader Election.
- Issue link: https://github.com/kubernetes/enhancements/issues/4355

Coordinated Leader Election to Beta

---

keps/sig-storage/2589-csi-migration-portworx/README.md

- One-line PR description: Update KEP for Portworx CSI Migration
- Issue link: https://github.com/kubernetes/enhancements/issues/2589
- Other comments: This PR updates the Troubleshooting section in KEP readme as per the [latest template](https://github.com/kubernetes/enhancements/blob/master/keps/NNNN-kep-template/README.md?plain=1).
/sig storage

KEP-2589: Update Troubleshooting section in README

---

keps/sig-node/2400-node-swap/README.md
keps/sig-node/2400-node-swap/kep.yaml

Add updates, GA criterias and clarifications
This PR updates the KEP in the following ways:
**Emphasize that this KEP is about basic swap enablement**
The original KEP indicated that pod-level swap APIs are out of scope:
https://github.com/kubernetes/enhancements/blob/155a949378fe85d4ca936176ad48103bf9567402/keps/sig-node/2400-node-swap/README.md?plain=1#L163-L166
https://github.com/kubernetes/enhancements/blob/155a949378fe85d4ca936176ad48103bf9567402/keps/sig-node/2400-node-swap/README.md?plain=1#L142-L144
However, the lack of APIs and the implicit nature of the current implementation sometimes brings suggestions to extend the API under this KEP.
This KEP focuses on a basic …

[KEP-2400] swap updates, beta3 graduation and GA criterias

---

keps/prod-readiness/sig-node/4742.yaml
keps/sig-node/4742-node-topology-downward-api/README.md
keps/sig-node/4742-node-topology-downward-api/kep.yaml

- One-line PR description: support node topologies in downward API
- Issue link: https://github.com/kubernetes/enhancements/issues/4742, https://github.com/kubernetes/kubernetes/issues/40610
- Other comments: This PR replaces https://github.com/kubernetes/enhancements/pull/4747

KEP-4724: support node topologies in downward API

---

keps/sig-api-machinery/4020-unknown-version-interoperability-proxy/README.md

- One-line PR description: Replace StorageversionAPI with AggregatedDisovery to fetch served resources by peer apiservers. Also some formatting changes.
- Issue link: https://github.com/kubernetes/enhancements/issues/4020

KEP-4020: Replace StorageversionAPI with AggregatedDiscovery to fetch served resources by peer apiservers

---

keps/sig-storage/1710-selinux-relabeling/README.md
keps/sig-storage/1710-selinux-relabeling/kep.yaml

During implementation, we joined both proposed SELinuxWarningController metrics into one, distinguished by label. And we renamed the metric to have the controller name as a prefix, which seems to be a common pattern in KCM.

1710: selinux: Rename SELinuxWarningController metric

---

keps/sig-multicluster/1645-multi-cluster-services-api/README.md

- One-line PR description: Relax a bit the sentence about EndpointSlice marked as not managed by the endpointslice controller as some EndpointSlice might be actually managed by the endpointslice controller directly.
For instance Cilium implementation currently uses the default endpointslice controller to manage the EndpointSlice from the local cluster.
The sentence below still implies that imported EndpointSlice must be managed by a MCS-API controller which means that this mixed scenario can be conformant while still keeping a strong guideline for EndpointSlice managed by a MCS-API controller.

KEP 1645: slightly relax the managed by requirements on EndpointSlices

---

keps/sig-scheduling/4815-dra-partitionable-devices/README.md

Update the API design for PartitionableDevice

---

keps/sig-node/4817-resource-claim-device-status/README.md
keps/sig-node/4817-resource-claim-device-status/kep.yaml

- One-line PR description: fix metrics to use apiserver_request_total
- Issue link: https://github.com/kubernetes/enhancements/issues/4817
- Other comments: KEP-4817
Changes requested during the implementation of the metrics for KEP-4817
https://github.com/kubernetes/kubernetes/pull/130812#discussion_r1995854873

KEP-4817: fix metrics to use apiserver_request_total

---

keps/sig-architecture/4330-compatibility-versions/README.md

Update KEP-4330 description about version introspection

KEP-4330: update version introspection details for compatibility versions

---

keps/sig-auth/3257-cluster-trust-bundles/README.md

Corrects the example ClusterRole in the README.md of KEP-3257
- Issue link:
https://github.com/kubernetes/enhancements/issues/3257
It was using singular "signer" which doesn't work. It has to be "signers", like in the tests: https://github.com/kubernetes/kubernetes/blob/6b8e5a9457a015e5568d7ae21b94d8a4eeb41bb3/test/integration/clustertrustbundles/admission_establishtrust_test.go#L142

KEP-3257: fix ClusterRole example

---

keps/sig-autoscaling/4951-configurable-hpa-tolerance/README.md

Clarify that only the v2 API will support the new field, and how other versions will implement round-trip requirements.
- Issue link: https://github.com/kubernetes/enhancements/issues/4951
- Other comments: This clarification has been requested during the code review of https://github.com/kubernetes/kubernetes/pull/130797

KEP-4951: clarify which API versions are impacted by the change.

---

keps/README.md

This updates the `keps/README.md` file to drop the information about the process being in beta. Shoutout to @brandtkeller for noticing this one. 

Drop the beta stage from the KEP readme

---

keps/NNNN-kep-template/README.md

The template gives the impression that both integration and e2e tests must be written. Let's be a bit more flexible and document that feature owners can opt out of that if it makes sense.
Linking to the triage tool is not sufficient. We want an empty result there, but that could also have been caused by not running the tests at all. A link to the periodic job which included the tests is more important.
To ensure more consistency, the suggested bullet list gets extended to be more realistic. Otherwise feature owners have to guess how they are meant to fill in the placeholders.
This was triggered by the discussion in https://github.com/kubernetes/enhancements/pull/5035#issuecomment-2607686987.
/sig testing
/cc @aojea @BenTheElder

KEP template: enhance suggestions for integration and e2e tests

---

keps/sig-api-machinery/5000-api-linting-crd-schema-tooling/README.md
keps/sig-api-machinery/5000-api-linting-crd-schema-tooling/kep.yaml

- One-line PR description: Adding new KEP for API Linting and CRD Schema Change Validation Tooling
- Issue link: #5000 

KEP-5000: API Linting and CRD Schema Change Validation Tooling

---

keps/sig-api-machinery/5073-declarative-validation-with-validation-gen/README.md

This addresses how we intend to handle subresources with Declarative Validation.
A separate PR will update the ratcheting section to address the need to skip unchanged fields when validating.

KEP-5073: Declarative Validation: Explain subresources

---

keps/sig-node/1287-in-place-update-pod-resources/README.md

- One-line PR description: sync proposal to implemented details, fix up PodResizeInProgress condition, document swap constraint, and a couple other cleanups.

KEP-1287: cleanup errors & add changes from implementation

---

keps/NNNN-kep-template/README.md
keps/prod-readiness/sig-architecture/5241.yaml
keps/sig-architecture/5241-beta-featuregate-promotion-requirements/README.md
keps/sig-architecture/5241-beta-featuregate-promotion-requirements/kep.yaml

- One-line PR description: Features gates must include all functional, security, and testing requirements along with resolving all issues and gaps identified prior to being enabled by default.
- Issue link: https://github.com/kubernetes/enhancements/issues/5241

KEP-5241: Beta Feature Gate Promotion Requirements

---

keps/prod-readiness/sig-api-machinery/5116.yaml
keps/sig-api-machinery/5116-streaming-response-encoding/README.md
keps/sig-api-machinery/5116-streaming-response-encoding/kep.yaml

Ref https://github.com/kubernetes/enhancements/issues/5116
Proposing to move the KEP-5116 to GA. 
There were no issues discovered in the implementation, so the only pending work is preventing regressions.
Added some information about regression we have already caught by just eyeballing the graph.
Don't think there is a need to block the GA on implementation of other serialization formats. While they are supported by apiserver, they are not used in Kubernetes core projects (`kubectl get pod -o yaml` will request JSON and generate yaml on client side) and should not be recommended. 
/assign @deads2k @liggitt

Move KEP-5116 to GA

---

keps/prod-readiness/sig-api-machinery/2340.yaml
keps/sig-api-machinery/2340-Consistent-reads-from-cache/README.md
keps/sig-api-machinery/2340-Consistent-reads-from-cache/kep.yaml

Ref https://github.com/kubernetes/enhancements/issues/2340
/assign @jpbetz @wojtek-t @deads2k

Graduate KEP-2340 to Stable

---

keps/sig-apps/3939-allow-replacement-when-fully-terminated/README.md
keps/sig-apps/3998-job-success-completion-policy/kep.yaml

- One-line PR description: Updating status for JobSuccessPolicy.
- Issue link: #3998
- Issue link: #3939
I additionally added the GA graduation criteria to KEP-3939 as we discussed in https://github.com/kubernetes/kubernetes/pull/130658

KEP-3998: Update JobSuccessPolicy feature Status

---

keps/sig-scheduling/5027-dra-admin-controlled-device-attributes/README.md
keps/sig-scheduling/5027-dra-admin-controlled-device-attributes/kep.yaml
keps/sig-scheduling/5055-dra-device-taints-and-tolerations/README.md

- One-line PR description: DRA: admin-controlled attributes and device taints in 1.33
- Issue link: https://github.com/kubernetes/enhancements/issues/5055, https://github.com/kubernetes/enhancements/issues/5027
This documents the actual work that happened (for device taints and tolerations) and that didn't happen (for admin-controlled attributes).
Plans for 1.34 will follow in a separate PR.
/assign @dom4ha

KEP-5055: DRA: admin-controlled attributes and device taints in 1.33

---

keps/prod-readiness/sig-auth/5018.yaml
keps/sig-auth/5018-dra-adminaccess/README.md
keps/sig-auth/5018-dra-adminaccess/kep.yaml

- One-line PR description: Update KEP to prepare for beta in 1.34
- Issue link: https://github.com/kubernetes/enhancements/issues/5018
- Other comments: Some of the material is already covered in [KEP-4381: DRA Structure Parameters](https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/4381-dra-structured-parameters), so that KEP is referenced in some places.
/wg device-management
/assign @liggitt for sig auth
/assign @pohly
/assign @soltysh for PRR

KEP-5018: move to beta in 1.34

---

keps/sig-api-machinery/2340-Consistent-reads-from-cache/README.md

/assign @jpbetz @wojtek-t @deads2k
Applying feedback from @wojtek-t in https://github.com/kubernetes/enhancements/pull/5330#discussion_r2109344135

Revert decision to return retry-after based on feedback

---

keps/prod-readiness/sig-cli/5295.yaml
keps/sig-cli/5295-kyaml/README.md
keps/sig-cli/5295-kyaml/kep.yaml

This KEP proposes to add a new output format for kubectl, tentatively called “KYAML” (as in `kubectl get -o kyaml ...`). This format is a strict subset (aka “dialect”) of standard YAML, and so should be parseable by the existing ecosystem. This dialect seeks to emphasize syntactical choices which avoid many of the most common traps in YAML. For example, unlike standard YAML output, this dialect is not whitespace-sensitive, which makes it vastly easier to patch correctly in things like Helm charts.
This KEP further proposes to make KYAML the standard format for all project-owned documentation and examples.
- One-line PR description: First draft
- Issue link: https://github.com/kubernetes/enhancements/issues/5295

KEP-5295: KYAML

---

keps/sig-api-machinery/5073-declarative-validation-with-validation-gen/README.md

This PR fixes the +k8s:listMapItem syntax which currently in the KEP uses a prototype version of the syntax for this tag but it should be updated to the actual named argument grammar validation-gen has adopted

KEP-5073: Declarative Validation: fix listMapItem syntax to be aligned with named argument grammar

---

keps/prod-readiness/sig-node/4369.yaml
keps/sig-node/4369-allow-special-characters-environment-variable/README.md
keps/sig-node/4369-allow-special-characters-environment-variable/kep.yaml

- One-line PR description: promote feature gate to ga
- Issue link: https://github.com/kubernetes/enhancements/issues/4369#issuecomment-2933136156

KEP-4369: Promote to GA (allow ~all ASCII characters in env vars)

---

keps/sig-node/4800-cpumanager-split-uncorecache/OWNERS
keps/sig-node/4800-cpumanager-split-uncorecache/kep.yaml

Scaling the SIG Node approvers. @ffromani was identified as an approver. Since the KEP passed the alpha stage, meaning it is an approved direction, it is fine to expand the approvership for the KEP on beta and GA stages
- Issue link: #4800

make a ffromani an approver for KEP 4800

---

keps/sig-node/4381-dra-structured-parameters/README.md

- One-line PR description: This PR introduces one standard device attribute: `kubernetes.io/pcieRoot`. Standard attributes will allow users to request hardware topology alignment for their workloads, even when devices are managed by different DRA drivers.
/wg device-management
/assign @klueska 
/assign @pohly

KEP-4381: Define standard device attributes

---

keps/prod-readiness/sig-storage/3751.yaml
keps/sig-storage/3751-volume-attributes-class/README.md
keps/sig-storage/3751-volume-attributes-class/kep.yaml

- One-line PR description: Update Release Signoff Checklist
- Issue link:
- Other comments: Add dashboard to indicate feature health
- E2E test link: https://github.com/kubernetes/kubernetes/blob/master/test/e2e/storage/testsuites/volume_modify.go

KEP-3751: Update release signoff Checklist before GA

---

keps/prod-readiness/sig-scheduling/3902.yaml
keps/sig-scheduling/3902-decoupled-taint-manager/README.md
keps/sig-scheduling/3902-decoupled-taint-manager/kep.yaml

- One-line PR description: promote KEP-3902 to stable
- Issue link: #3902 

[1.34] promote KEP-3902 to stable

---

keps/prod-readiness/sig-auth/4601.yaml
keps/sig-auth/4601-authorize-with-selectors/README.md
keps/sig-auth/4601-authorize-with-selectors/kep.yaml

- One-line PR description: Graduate KEP-4601 to stable
- Issue link: #4601
- Other comments: No changes since beta in 1.32
/sig auth
/cc @deads2k 
for sig-auth
/cc @wojtek-t 
for PRR

KEP-4601: Graduate authorize with selector to stable

---

keps/prod-readiness/sig-api-machinery/3962.yaml
keps/sig-api-machinery/3962-mutating-admission-policies/README.md
keps/sig-api-machinery/3962-mutating-admission-policies/kep.yaml

- Issue link: https://github.com/kubernetes/enhancements/issues/3962

[KEP-3962]Promote MAP to beta in 1.34

---

keps/sig-api-machinery/5073-declarative-validation-with-validation-gen/kep.yaml

One-line PR description: This PR explains the work being done in Declarative Validation in v1.34 as part of the PRR process.  Related comment here: https://github.com/kubernetes/enhancements/issues/5073#issuecomment-2958130141 
Issue link: #5073
"Beta - v1.33"
- `validation-gen` framework core pieces
- migration of subset of fields from `ReplicaSet`
"Beta - v1.34"
- ratcheting support (https://github.com/kubernetes/enhancements/pull/5292)
- cross-field validation support (https://github.com/kubernetes/enhancements/pull/5290, https://github.com/kubernetes/enhancements/pull/5363)
- immutability support (https://github.com/kubernetes/enhancements/pull/5373)
- migration of subset of fields of from `CertificateSigningRequest`
From the conversation …

KEP-5073: PRR update for v1.34

---

keps/sig-node/4680-add-resource-health-to-pod-status/README.md
keps/sig-node/4680-add-resource-health-to-pod-status/kep.yaml

/sig node
/cc @Jpsassine
/assign @mrunalp 
It was approved and PRR reviewed already for 1.33. Moved to 1.34 as implementation slipped the release

KEP-4680 is targeting alpha for DRA in 1.34

---

keps/sig-node/3960-pod-lifecycle-sleep-action/README.md
keps/sig-node/3960-pod-lifecycle-sleep-action/kep.yaml

PodLifecycleSleepAction is planned to graduate to ga in 1.34
- Issue link:
https://github.com/kubernetes/enhancements/issues/3960
We once brought this to ga in v1.32: https://github.com/kubernetes/enhancements/pull/4866
But reverted because of flaky tests.
So this pr only changes the version information, the rest part should be fine.

[KEP 3960]: Promote PodLifecycleSleepAction to stable

---

keps/prod-readiness/sig-network/5311.yaml
keps/sig-network/5311-relaxed-validation-for-service-names/README.md
keps/sig-network/5311-relaxed-validation-for-service-names/kep.yaml

- One-line PR description: Relaxed validation for Services names
- Issue link: https://github.com/kubernetes/enhancements/issues/5311

KEP-5311: Relaxed validation for Services names

---

keps/sig-instrumentation/2831-kubelet-tracing/README.md
keps/sig-instrumentation/2831-kubelet-tracing/kep.yaml

- One-line PR description: updating stable target for 1.34
It was already approved for stable in 1.33, but I was out on leave and wasn't able to put up PRs.  I looked at the current template, and don't see any differences.
cc @kubernetes/sig-instrumentation-leads

Update kubelet tracing to target stable in v1.34

---

keps/prod-readiness/sig-storage/1790.yaml
keps/sig-storage/1790-recover-resize-failure/README.md
keps/sig-storage/1790-recover-resize-failure/kep.yaml

https://github.com/kubernetes/enhancements/issues/1790

Target GA for recover from Volume Expansion failure feature

---

keps/sig-node/4639-oci-volume-source/README.md

- One-line PR description: updating ImageVolume KEP
- Issue link: https://kep.k8s.io/4639
- Other comments: discussion link in slack https://kubernetes.slack.com/archives/C0BP8PW9G/p1747855940240409

[KEP-4639] Image Volume: remove noexec option

---

keps/sig-storage/3476-volume-group-snapshot/README.md
keps/sig-storage/3476-volume-group-snapshot/kep.yaml

Update KEP to incorporate changes made while moving the feature to Beta.
Moved to beta in 1.32.
Update API to v1beta2 in 1.34.
- Issue link: https://github.com/kubernetes/enhancements/issues/3476

Update volume group snapshot KEP

---

keps/prod-readiness/sig-auth/4412.yaml
keps/sig-auth/4412-projected-service-account-tokens-for-kubelet-image-credential-providers/README.md
keps/sig-auth/4412-projected-service-account-tokens-for-kubelet-image-credential-providers/kep.yaml

- One-line PR description: Promote KEP-4412 to beta in v1.34
- Post Alpha work has been moved into beta graduation (making this KEP work with KEP-2535)
/sig auth
/assign enj liggitt

KEP-4412: promote wi for image pulls to beta in v1.34

---

keps/prod-readiness/sig-network/4762.yaml
keps/sig-network/4762-allow-arbitrary-fqdn-as-pod-hostname/README.md
keps/sig-network/4762-allow-arbitrary-fqdn-as-pod-hostname/kep.yaml

- One-line PR description: Allows users to set any FQDN as the hostname of a pod
- Issue link: https://github.com/kubernetes/enhancements/issues/4762

KEP-4762: Allows setting any FQDN as the pod's hostname

---

keps/prod-readiness/sig-cli/3104.yaml
keps/sig-cli/3104-introduce-kuberc/README.md
keps/sig-cli/3104-introduce-kuberc/kep.yaml

- One-line PR description: promote kuberc to beta
/assign @ardaguclu 
for sig-cli review
for PRR review
/hold 
so it doesn't merge accidentally before I get both of the above reviews in

KEP-3104: promote kuberc to beta

---

keps/prod-readiness/sig-apps/961.yaml
keps/sig-apps/3335-statefulset-slice/README.md
keps/sig-apps/961-maxunavailable-for-statefulset/README.md
keps/sig-apps/961-maxunavailable-for-statefulset/kep.yaml

Supersedes #4474 
- One-line PR description: Bump Statefulset MaxUnavailable to beta
- Issue link: #961 
- Other comments: kept @kerthcet's and @knelasevero's commits here. My commits: adding metric information
Metrics PR: https://github.com/kubernetes/kubernetes/pull/130951

KEP-961: Bump Statefulset MaxUnavailable to beta (built on top of #4474)

---

keps/sig-node/4639-oci-volume-source/README.md
keps/sig-node/4639-oci-volume-source/kep.yaml

- Issue link:
https://github.com/kubernetes/enhancements/issues/4639

4639: bump to 1.34 and document noexec drop

---

keps/prod-readiness/sig-auth/4872.yaml
keps/sig-auth/4872-harden-kubelet-cert-validation/README.md
keps/sig-auth/4872-harden-kubelet-cert-validation/kep.yaml

- One-line PR description: Add first version of doc
- Issue link: https://github.com/kubernetes/enhancements/issues/4872
- Other comments: I left a few `TODO`s with things I think can use a discussion.

KEP-4872: Harden Kubelet serving cert validation

---

keps/sig-node/1287-in-place-update-pod-resources/README.md
keps/sig-node/1287-in-place-update-pod-resources/kep.yaml

- Add a section about the priority for attempting in-place resize requests. 

KEP-1287: Priority of Resize Requests

---

keps/prod-readiness/sig-node/5067.yaml
keps/sig-node/5067-pod-generation/README.md
keps/sig-node/5067-pod-generation/kep.yaml

Promoting Pod Generation to beta. All the requirements were implemented in 1.33, so this update is just filling out the PRR questionnaire for beta.
Issue link: https://github.com/kubernetes/enhancements/issues/5067

KEP-5067: promote Pod Generation to beta

---

keps/prod-readiness/sig-node/3721.yaml
keps/sig-node/3721-support-for-env-files/README.md
keps/sig-node/3721-support-for-env-files/kep.yaml

- One-line PR description: Support for env files.
- Issue link: https://github.com/kubernetes/enhancements/issues/3721
- Other comments: This PR replaces #4524. The previous PR had too many commits, so I didn’t cherry-pick them. I copied and pasted the changes, while also refining some parts that were missed or left pending in the earlier PR.

KEP-3721: Support for env files.

---

keps/prod-readiness/sig-node/4033.yaml
keps/sig-node/4033-group-driver-detection-over-cri/README.md
keps/sig-node/4033-group-driver-detection-over-cri/kep.yaml

- One-line PR description: graduate [KEP-4033](https://github.com/kubernetes/enhancements/issues/4033) to GA
- Issue link: #4033

KEP-4033: graduate to GA

---

keps/prod-readiness/sig-storage/4876.yaml
keps/sig-storage/4876-mutable-csinode-allocatable/README.md
keps/sig-storage/4876-mutable-csinode-allocatable/kep.yaml

- One-line PR description: Updating milestone to beta for sig-storage `KEP-4876` Mutable CSINode Allocatable.
- Issue link: https://github.com/kubernetes/enhancements/issues/4876

Update KEP-4876 Mutable CSINode Allocatable for Beta

---

keps/prod-readiness/sig-node/4800.yaml
keps/sig-node/4800-cpumanager-split-uncorecache/README.md
keps/sig-node/4800-cpumanager-split-uncorecache/kep.yaml

- One-line PR description: Promoting CPUManager feature prefer-align-cpus-by-uncorecache to beta
- Issue link: https://github.com/kubernetes/enhancements/issues/5109

KEP-4800: Promote prefer-align-cpus-by-uncorecache CPUManager feature to beta

---

keps/sig-scheduling/3243-respect-pod-topology-spread-after-rolling-upgrades/README.md
keps/sig-scheduling/3243-respect-pod-topology-spread-after-rolling-upgrades/kep.yaml

One-line PR description: Update KEP milestone v1.33 to v1.34 since [the code change](https://github.com/kubernetes/kubernetes/pull/129874) have not meet the v1.33 code freeze, and  I've added the new feature gate for [#129874](https://github.com/kubernetes/kubernetes/pull/129874) as discussed in https://github.com/kubernetes/kubernetes/pull/129874#issuecomment-2714245915.
Issue link: https://github.com/kubernetes/enhancements/issues/3243

KEP-3243: Update milestone v1.33 to v1.34 and add the new feature gate to control the design change of TopologySpreadConstraint's matchLabelKeys

---

keps/sig-node/1287-in-place-update-pod-resources/README.md
keps/sig-node/1287-in-place-update-pod-resources/kep.yaml

- Add section with details about the metrics we plan to instrument for IPPR

KEP 1287: Instrumentation for in-place pod resize

---

keps/prod-readiness/sig-node/5307.yaml
keps/sig-node/5307-container-restart-policy/README.md
keps/sig-node/5307-container-restart-policy/kep.yaml

- One-line PR description: Initial KEP for container restart exceptions
- Issue link: https://github.com/kubernetes/enhancements/issues/5307
- Other comments: Discussion link https://docs.google.com/document/d/13fQu343OBEM2ICHLXfWHrApmzskd4nY3xWI27EbMJyI/edit?tab=t.0
- Future improvement direction: Discussion link https://docs.google.com/document/d/1UmJHJzdmMA1hWwkoP1f3rG9nS0oZ2cRcOx8rO8MsExA/edit?resourcekey=0-OuKspBji_1KJlj2JbnZkgQ&tab=t.0#heading=h.e2gx4umk9f64

KEP-5307 Initial KEP for container restart exceptions

---

keps/prod-readiness/sig-node/5365.yaml
keps/sig-node/5365-ImageVolume-with-image-digest/README.md
keps/sig-node/5365-ImageVolume-with-image-digest/kep.yaml

- One-line PR description: Report ImageVolume's image digest as part of the pod's status.
- Issue link: https://github.com/kubernetes/enhancements/issues/5365.

[KEP-5365] ImageVolume with an image digest

---

keps/sig-node/4603-tune-crashloopbackoff/README.md

While there was a PR 4604 (https://github.com/kubernetes/enhancements/pull/4604), as far as I can tell KEP-4603 is the correct number here (see kep.yaml, the directory name, etc).
- Issue link:
https://github.com/kubernetes/enhancements/issues/4603

KEP-4603: fix KEP number in README

---

keps/prod-readiness/sig-node/5394.yaml
keps/sig-node/5394-psi-node-conditions/README.md
keps/sig-node/5394-psi-node-conditions/kep.yaml

- One-line PR description: Introduce PSI-based node conditions. This is split from the original KEP https://github.com/kubernetes/enhancements/issues/4205, so we can track the progress separately.
- Issue link: https://github.com/kubernetes/enhancements/issues/5394
- Other comments: See https://github.com/kubernetes/enhancements/issues/5062. CPU PSI cannot be used the same way as memory / IO PSI due to CPU being a compressible resource.
/sig node
/cc @haircommander @ndixita @tiraboschi

KEP-5394: PSI-based node conditions

---

keps/prod-readiness/sig-scheduling/4816.yaml
keps/sig-scheduling/4816-dra-prioritized-list/README.md
keps/sig-scheduling/4816-dra-prioritized-list/kep.yaml

- One-line PR description: Update KEP to prepare for beta in 1.34
- Issue link: https://github.com/kubernetes/enhancements/issues/4816
- Other comments: Some of the material is already covered in [KEP-4381: DRA Structure Parameters](https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/4381-dra-structured-parameters), so that KEP is referenced in some places.

KEP-4816 update for beta in 1.34

---

keps/sig-node/5419-pod-level-resources-in-place-resize/README.md

- One-line PR description: Adding non goals and risks and mitigations section
- Issue link: https://github.com/kubernetes/enhancements/issues/5419
- Other comments: Non goals and risks and mitigations for this KEP are same as for KEP #1287

KEP-5419: Add non-goals, and risks and mitigations

---

keps/sig-node/4680-add-resource-health-to-pod-status/README.md

Update DRA implementation details by updating the reference to Device, the Variable `NamedResourcesInstance` is now located in a diff path with the name `BasicDevice` 
- Issue link: #4680

KEP-4680: Update DRA implementation details

---

keps/sig-cli/5295-kyaml/README.md

- One-line PR description: Fix the typo from `kayml` to `kyaml`
- Issue link: #5295 

KEP-5295: Fix the typo from kayml to kyaml

---

keps/sig-multicluster/OWNERS

We're adding a group of reviewers to help with SIG-MC KEP reviews.

Add SIG-Multicluster reviewers

---

keps/sig-node/3721-support-for-env-files/README.md

- One-line PR description: Align KEPs with implemented PRs and documentation.
relate: 
- https://github.com/kubernetes/website/pull/51814
- https://github.com/kubernetes/website/pull/51415
- https://github.com/kubernetes/kubernetes/pull/132626
- Issue link:

[KEP-3721] Align KEPs with implemented PRs and documentation.

---

keps/sig-apps/961-maxunavailable-for-statefulset/README.md
keps/sig-apps/961-maxunavailable-for-statefulset/kep.yaml

This PR is to update the KEP with the latest set of test PRs and the new metrics names. Also to update the release number for the beta release.
/sig apps
/assign @soltysh

KEP-961: Update test links and metrics for beta release

---

.githooks/pre-commit

Previous usage of exec caused only the first script to be run.

githooks: run all checks in pre-commit hook

---

keps/prod-readiness/sig-network/5495.yaml
keps/sig-network/5495-deprecate-ipvs-mode-in-kube-proxy/README.md
keps/sig-network/5495-deprecate-ipvs-mode-in-kube-proxy/kep.yaml

- One-line PR description: Initial attempt at KEP-5495: Deprecate IPVS mode in kube-proxy
- Issue link: https://github.com/kubernetes/enhancements/issues/5495
- Other comments: It feels a little weird to have a KEP that only deprecates ipvs, and doesn't remove it. As such, a lot of the sections are filled in as "N/A". I wonder if renaming this as "Remove IPVS mode in kube-proxy"  makes sense, and start the journey of removing IPVS. The first PR (for K8s 1.35) would only focus on deprecating, meaning a lot of the KEP may be blank as we figure out the removal plan.

KEP-5495: Deprecate IPVS mode in kube-proxy

---

keps/sig-api-machinery/4192-svm-in-tree/README.md

- One-line PR description: Update the beta requirements for KEP-4192 based on discussions in sig-apimachinery

KEP-4192: Update beta requirements

---

OWNERS_ALIASES

Updates SIG Autoscaling TL from myself to @adrianmoisey per [this announcement](https://groups.google.com/g/kubernetes-sig-autoscaling/c/VH_Dj1nWCUw/m/ulj2jMCuAQAJ).
See https://github.com/kubernetes/community/issues/8629.

Update SIG-Autoscaling TL to adrianmoisey

---

keps/sig-cli/1441-kubectl-debug/README.md

- One-line PR description: This PR updates KEP-1441 by dropping the auto profile mentions. We decided that we can default to `general` profile.
- Other comments: Agreed upon sig-cli biweekly meeting on October 1st 2025.

KEP-1441: Drop auto profile

---

keps/prod-readiness/sig-network/3015.yaml
keps/sig-network/3015-prefer-same-node/README.md
keps/sig-network/3015-prefer-same-node/kep.yaml

Update https://github.com/kubernetes/enhancements/issues/3015 to GA.
The GA graduation criteria are just "Time passes, no major objections". The biggest change will be the docs updates reflecting that `PreferClose` is now deprecated in favor of `PreferSameZone`.

KEP-3015: update PreferSame* TrafficDistribution to GA

---

keps/sig-node/127-user-namespaces/README.md
keps/sig-node/127-user-namespaces/kep.yaml

KEP-127: retarget beta to 1.35 and include PSA updates there

---

keps/prod-readiness/sig-api-machinery/5589.yaml
keps/sig-api-machinery/5589-gogo-dependency/README.md
keps/sig-api-machinery/5589-gogo-dependency/kep.yaml

- One-line PR description: Initial draft for gogo protobuf removal
- Issue link: #5589
/sig api-machinery architecture
/cc @deads2k @jpbetz @dims

KEP-5589: Initial draft for gogo protobuf removal

---

keps/prod-readiness/sig-node/4639.yaml
keps/sig-node/4639-oci-volume-source/README.md
keps/sig-node/4639-oci-volume-source/kep.yaml

- One-line PR description: Graduate the image volume feature as GA for 1.35.
- Issue link: https://github.com/kubernetes/enhancements/issues/4639

[KEP-4639] Graduate image volumes to GA

---

keps/sig-cli/3104-introduce-kuberc/README.md
keps/sig-cli/3104-introduce-kuberc/kep.yaml

- One-line PR description: Add `kubectl kuberc` command to generate kuberc files.
- Issue link:
* [Discussion link](https://www.youtube.com/watch?v=7CxnjCu4Pms&list=PL69nYSiGNLP28HaTzSlFe6RJVxpFmbUvF&index=2)
* https://github.com/kubernetes/enhancements/issues/3104

KEP-3104: Add kubectl kuberc command section

---

keps/prod-readiness/sig-api-machinery/4006.yaml
keps/sig-api-machinery/4006-transition-spdy-to-websockets/README.md
keps/sig-api-machinery/4006-transition-spdy-to-websockets/kep.yaml

* Adds requirement for new synthetic RBAC CREATE permission check for WebSocket upgrade request.
* Feature Gate for this functionality: `AuthorizePodWebsocketUpgradeCreatePermission`; enabled by default
* Beta in v1.35
* Refactor GA/stable requirement for transitioning to streaming WebSockets from client to Kubelet (but **NOT** from Kubelet to container runtime).
* Updates KEP to reflect graduating WebSockets functionality to GA in v1.36
- Issue link: https://github.com/kubernetes/enhancements/issues/4006

KEP-4006: Updated KEP for 1.35
